### ISSUE TITLE
Struct value doesn't initialize correctly on .NET Framework target

### ISSUE THREAD

**Issue by Zonciu** [dotnet/coreclr#25852] opened 2019-07-24 09:21 UTC
By adding redundant type cast, `Vec2` gets correct result.
## S1 (bug)
```
    public struct S1
    {
        public Vector2 Vec2;

        public S1_1 A;

        public S1(Vector2 p, float a)
        {
            Vec2 = p;
            A = new S1_1(a);
        }
    }

    public struct S1_1
    {
        public float A;

        public float B;

        public S1_1(float a)
        {
            A = (float) Math.Cos(a);
            B = (float) Math.Sin(a);
        }

        public Vector2 GetVector2()
        {
            return new Vector2(A, B);
        }
    }
```
## S2 (ok)
```
    public struct S2
    {
        public Vector2 Vec2;

        public S2_1 A;

        public S2(Vector2 p, float a)
        {
            Vec2 = p;
            A = new S2_1(a);
        }
    }

    public struct S2_1
    {
        public float A;

        public float B;

        public S2_1(float a)
        {
            A = (float) Math.Cos(a);
            B = (float) Math.Sin(a);
        }

        public Vector2 GetVector2()
        {
            return new Vector2((float) A, (float) B);
        }
    }
```
```
    internal class Program
    {
        public static void Main(string[] args)
        {
            {
                var s = new S1(Vector2.Zero, 0.34324f);
                s.Vec2 = s.A.GetVector2();
                Console.WriteLine($"s1.Vec2 == s1.A.GetVector2() {s.Vec2} == {s.A.GetVector2()}: {s.Vec2 == s.A.GetVector2()}");
            }
            {
                var s = new S1(Vector2.Zero, 0.34324f);
                s.Vec2 = new Vector2(s.A.A, s.A.B);
                Console.WriteLine($"s1.Vec2 == s1.A.GetVector2() {s.Vec2} == {s.A.GetVector2()}: {s.Vec2 == s.A.GetVector2()}");
            }
            {
                var s = new S2(Vector2.Zero, 0.34324f);
                s.Vec2 = s.A.GetVector2();
                Console.WriteLine($"s2.Vec2 == s2.A.GetVector2() {s.Vec2} == {s.A.GetVector2()}: {s.Vec2 == s.A.GetVector2()}");
            }
            {
                var s = new S2(Vector2.Zero, 0.34324f);
                s.Vec2 = new Vector2(s.A.A, s.A.B);
                Console.WriteLine($"s1.Vec2 == s1.A.GetVector2() {s.Vec2} == {s.A.GetVector2()}: {s.Vec2 == s.A.GetVector2()}");
            }
        }
    }
```
## Test results

Reproduction project: [BugTest.zip](https://github.com/dotnet/coreclr/files/3425749/BugTest.zip)

Tested version:

| net472 fx | net472 | net461 | 3.0 | 2.2 | 2.1 |
| --------- | ------ | ------ | --- | --- | --- |
| - | bug | bug | - | - | - |

* NETCore3.0 (SDK 3.0.100-preview7-012821)
```
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.33653986> == <0.9416692, 0.33653986>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.33653986> == <0.9416692, 0.33653986>: True
s2.Vec2 == s2.A.GetVector2() <0.9416692, 0.33653986> == <0.9416692, 0.33653986>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.33653986> == <0.9416692, 0.33653986>: True
```

* NETCore2.2
```
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s2.Vec2 == s2.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
```

* NETCore2.1
```
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s2.Vec2 == s2.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
```

* NET472 - dotnet
```
s1.Vec2 == s1.A.GetVector2() <-4.630952E+21, 4.591074E-41> == <0.9416692, 0.3365399>: False
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s2.Vec2 == s2.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
```

* NET461 - dotnet
```
s1.Vec2 == s1.A.GetVector2() <-4.649399E+21, 4.591074E-41> == <0.9416692, 0.3365399>: False
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s2.Vec2 == s2.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
```

* NET472 Fx - msbuild
```
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s2.Vec2 == s2.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
s1.Vec2 == s1.A.GetVector2() <0.9416692, 0.3365399> == <0.9416692, 0.3365399>: True
```

**Comment by AndyAyersMS** [comment] 2019-07-28 17:04
@Zonciu .NET Framework bugs are best reported via the [community portal](https://developercommunity.visualstudio.com/).

Also, can you report the version number of clrjit.dll in your results?

cc @CarolEidt @briansull in case this seems familiar.

**Comment by Zonciu** [comment] 2019-08-07 13:06
@AndyAyersMS Where can I find clrjit.dll?

**Comment by AndyAyersMS** [comment] 2019-08-07 15:41
It should be something like `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll`

**Comment by Zonciu** [comment] 2019-08-07 16:06
The version is `4.7.3416.0`

**Comment by AndyAyersMS** [comment] 2019-08-07 16:28
@Zonciu which version does that correspond to in your table above (NET472?)

@BruceForstall this is a .NET Framework issue which we normally do not handle here. But it seems like we could check if it is fixed already (seems likely) and if so point @Zonciu at .NET Framework versions with the fix.

**Comment by Zonciu** [comment] 2019-08-07 16:44
I have uploaded the reproduction project. 
For classic .NET Framework project(old csproj) and .NET Core project the result is correct.
Only for new csproj with NET Framework runtime, the result is incorrect.

**Comment by CarolEidt** [comment] 2019-08-07 21:41
This doesn't ring a bell, but if my understanding is correct, the "old csproj" and "new csproj" are using the same .NET Framework version, which seems to indicate that it might be exposed due to different code generation from the C# compiler. Of course, even if that's the case it doesn't indicate whether the bug is a JIT or C# bug.

**Comment by jeffschwMSFT** [comment] 2019-08-20 23:28
@Zonciu given this is a .NET Framework related request, can you create a VS Feedback item (then paste the issue back here - to link them)?  .NET Framework is receiving fewer updates (please read https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/ for more context), but we can more appropriate track it in that feedback system.  Thanks

**Comment by Zonciu** [comment] 2019-08-21 08:06
https://developercommunity.visualstudio.com/content/problem/702612/struct-value-doesnt-initialize-correctly-on-net-fr.html

feedback is here
ps: that editor is so hard to use

**Comment by jeffschwMSFT** [comment] 2019-08-21 16:09
Thanks @Zonciu.  I am going to close this issue.  As I mentioned, please do read the blog post to set expectations on if/when we may/may not be able to address this.  I have assigned this feedback item to our team internally.  My goal is to at least investigate the root cause to help determine the impact.

**Closed by jeffschwMSFT** 2019-08-21 16:09 UTC
Labels: tracking-external-issue
