### ISSUE TITLE
Multiple JIT Stress test failures

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#17027] opened 2018-03-19 02:41 UTC
While working on https://github.com/dotnet/coreclr/pull/16957 I found there were multiple unrelated tests that were failing.

#### General Failure

* baseservices_threading._regressions_269336_objmonhelper_objmonhelper_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0x3_prtest/19/testReport/junit/baseservices_threading/_regressions_269336_objmonhelper_objmonhelper_/_regressions_269336_objmonhelper_objmonhelper_cmd/
* baseservices_threading._generics_threadstart_GThread02_GThread02_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_jitstressregs8_prtest/24/testReport/junit/baseservices_threading/_generics_threadstart_GThread02_GThread02_/_generics_threadstart_GThread02_GThread02_cmd/
* baseservices_threading._waithandle_waitany_waitanyex5_waitanyex5_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0x3_prtest/15/testReport/junit/baseservices_threading/_waithandle_waitany_waitanyex5_waitanyex5_/_waithandle_waitany_waitanyex5_waitanyex5_cmd/
* CoreMangLib_cti._system_reflection_emit_DynMethodJumpStubTests_DynMethodJumpStubTests_DynMethodJumpStubTests_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_prtest/47/testReport/CoreMangLib_cti/_system_reflection_emit_DynMethodJumpStubTests_DynMethodJumpStubTests_DynMethodJumpStubTests_/_system_reflection_emit_DynMethodJumpStubTests_DynMethodJumpStubTests_DynMethodJumpStubTests_cmd/
* JIT_Methodical._ELEMENT_TYPE_IU__il_dbgu_fld__il_dbgu_fld_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_minopts_heapverify1_prtest/10/testReport/JIT_Methodical/_ELEMENT_TYPE_IU__il_dbgu_fld__il_dbgu_fld_/_ELEMENT_TYPE_IU__il_dbgu_fld__il_dbgu_fld_cmd/
* JIT_Methodical._ELEMENT_TYPE_IU__il_relu_fld__il_relu_fld_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_minopts_heapverify1_prtest/17/testReport/junit/JIT_Methodical/_ELEMENT_TYPE_IU__il_relu_fld__il_relu_fld_/_ELEMENT_TYPE_IU__il_relu_fld__il_relu_fld_cmd/
* JIT_Performance._CodeQuality_BenchmarksGame_k_nucleotide_k_nucleotide_9_k_nucleotide_9_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_zapdisable_heapverify1_prtest/8/testReport/junit/JIT_Performance/_CodeQuality_BenchmarksGame_k_nucleotide_k_nucleotide_9_k_nucleotide_9_/_CodeQuality_BenchmarksGame_k_nucleotide_k_nucleotide_9_k_nucleotide_9_cmd/
* Loader_classloader._TypeInitialization_CircularCctors_CircularCctorFourThreads_CircularCctorFourThreads_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_prtest/47/testReport/Loader_classloader/_TypeInitialization_CircularCctors_CircularCctorFourThreads_CircularCctorFourThreads_/_TypeInitialization_CircularCctors_CircularCctorFourThreads_CircularCctorFourThreads_cmd/
* Loader_classloader._TypeInitialization_CircularCctors_CircularCctorThreeThreads02_CircularCctorThreeThreads02_: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_zapdisable_heapverify1_prtest/8/testReport/junit/Loader_classloader/_TypeInitialization_CircularCctors_CircularCctorThreeThreads02_CircularCctorThreeThreads02_/_TypeInitialization_CircularCctors_CircularCctorThreeThreads02_CircularCctorThreeThreads02_cmd/

#### Jobs with many failures
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_jitstress2_prtest/8/#showFailuresLink
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_jitstress2_prtest/12/#showFailuresLink
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_jitstress1_prtest/12/#showFailuresLink
* https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_jitstress1/68/

#### baseservices_threading._mutex_misc_mutexctor1_mutexctor1

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_minopts_heapverify1_prtest/10/testReport/baseservices_threading/_mutex_misc_mutexctor1_mutexctor1_/_mutex_misc_mutexctor1_mutexctor1_cmd/

```
	Assert failure(PID 9080 [0x00002378], Thread: 2304 [0x0900]): CONTRACT VIOLATION by Frame::Push at \"d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\frames.cpp\" @ 394

	MODE_COOPERATIVE encountered while thread is in preemptive state.

	 CONTRACT in Frame::Push at \"d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\frames.cpp\" @ 394
	 OVERRIDE_TYPE_LOAD_LEVEL_LIMIT in MethodDescCallSite::CallTargetWorker at \"d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\callhelpers.cpp\" @ 371
	 CONTRACT in MethodDescCallSite::CallTargetWorker at \"d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\callhelpers.cpp\" @ 361
	 CONTRACT in ThreadNative::KickOffThread_Worker at \"d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\comsynchronizable.cpp\" @ 206
	 CONTRACT in ManagedThreadBase_DispatchInner at \"d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\threads.cpp\" @ 8816
	 CONTRACT in ManagedThreadBase_FullTransitionWithAD at \"d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\threads.cpp\" @ 9197
	 CONTRACT in ThreadNative::KickOffThread at \"d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\comsynchronizable.cpp\" @ 305

	We can't find the violated contract. Look for an old-style non-holder-based contract.

	CORECLR! CONTRACT_ASSERT + 0x458 (0x00007ffe`f1db47f8)
	CORECLR! EEContract::DoChecks + 0x252 (0x00007ffe`f1ed1032)
	CORECLR! Frame::Push + 0xD4 (0x00007ffe`f216ecd4)
	CORECLR! LinkFrameAndThrow + 0x32 (0x00007ffe`f1ed0d92)
	CORECLR! NakedThrowHelper2 + 0x9 (0x00007ffe`f23981b9)
	CORECLR! NakedThrowHelper_RspAligned + 0x1E (0x00007ffe`f23981eb)
	CORECLR! NakedThrowHelper_FixRsp + 0x5 (0x00007ffe`f23981f5)
	SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ffe`f1811e90)
	SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ffe`f18f0ed4)
	<no module>! <no symbol> + 0x0 (0x00007ffe`92ce616f)
	 File: d:\\j\\workspace\\x64_checked_w---e8fbcb57\\src\\vm\\frames.cpp Line: 394
	 Image: D:\\j\\workspace\\x64_checked_w---e8fbcb57\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root\\CoreRun.exe
```

#### JIT_Methodical._refany__il_relarray3__il_relarray3_

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_minopts_heapverify1_prtest/17/testReport/junit/JIT_Methodical/_refany__il_relarray3__il_relarray3_/_refany__il_relarray3__il_relarray3_cmd/

```
	Assert failure(PID 5580 [0x000015cc], Thread: 7364 [0x1cc4]): !hasPartialArgInfo || isZero(argHigh) || (argHigh == CONSTRUCT_ptrArgTP(1, (argCnt-1)))

	CORECLR! scanArgRegTableI + 0x5F3 (0x7261e063)
	CORECLR! EECodeManager::EnumGcRefs + 0x322 (0x72617a62)
	CORECLR! GcStackCrawlCallBack + 0x169 (0x727eda29)
	CORECLR! Thread::MakeStackwalkerCallback + 0x45 (0x7246b345)
	CORECLR! Thread::StackWalkFramesEx + 0x177 (0x7246c9dc)
	CORECLR! Thread::StackWalkFrames + 0x15E (0x7246c7e2)
	CORECLR! ScanStackRoots + 0x18C (0x728f74da)
	CORECLR! GCToEEInterface::GcScanRoots + 0x10F (0x728f6adc)
	CORECLR! WKS::gc_heap::mark_phase + 0x1B1 (0x728c1c2e)
	CORECLR! WKS::gc_heap::gc1 + 0x133 (0x728bc800)
	 File: d:\\j\\workspace\\x86_checked_w---9da75386\\src\\vm\\eetwain.cpp Line: 2658
	 Image: D:\\j\\workspace\\x86_checked_w---9da75386\\bin\\tests\\Windows_NT.x86.Checked\\Tests\\Core_Root\\CoreRun.exe
```

#### JIT_Performance._CodeQuality_BenchmarksGame_regex_redux_regex_redux_5_regex_redux_5_

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1_prtest/8/testReport/JIT_Performance/_CodeQuality_BenchmarksGame_regex_redux_regex_redux_5_regex_redux_5_/_CodeQuality_BenchmarksGame_regex_redux_regex_redux_5_regex_redux_5_cmd/

```
	Assert failure(PID 6868 [0x00001ad4], Thread: 760 [0x02f8]): Consistency check failed: hit privileged instruction!FAILED: !ExecutionManager::IsManagedCode(GetIP(pContext))
	 File: d:\\j\\workspace\\x86_checked_w---a898fbbe\\src\\vm\\excep.cpp Line: 6944
	 Image: D:\\j\\workspace\\x86_checked_w---a898fbbe\\bin\\tests\\Windows_NT.x86.Checked\\Tests\\Core_Root\\CoreRun.exe
```

#### JIT_HardwareIntrinsics._X86_Sse2_ConvertToDouble_r_ConvertToDouble_r_

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstressregs4_prtest/31/testReport/junit/JIT_HardwareIntrinsics/_X86_Sse2_ConvertToDouble_r_ConvertToDouble_r_/_X86_Sse2_ConvertToDouble_r_ConvertToDouble_r_cmd/

```
	Assert failure(PID 16440 [0x00004038], Thread: 11024 [0x2b10]): Assertion failed '(unsigned)ins < _countof(insCodesRM)' in 'IntelHardwareIntrinsicTest.Program:Main(ref):int' (IL size 243)

	 File: d:\\j\\workspace\\x64_checked_w---db056dfb\\src\\jit\\emitxarch.cpp Line: 1249
	 Image: D:\\j\\workspace\\x64_checked_w---db056dfb\\bin\\tests\\Windows_NT.x64.Checked\\Tests\\Core_Root\\CoreRun.exe
```

**Comment by tannergooding** [comment] 2018-03-19 02:42
These all need further investigating/resolution (and to possibly be split out into their own issues). Several of these issues were showing in multiple jobs.

**Comment by 4creators** [comment] 2018-03-19 11:27
@tannergooding 

JIT_HardwareIntrinsics.X86_Sse2_ConvertToDouble_r_ConvertToDouble_r seems to be recent regression as test was always passing in the same job before.

**Comment by tannergooding** [comment] 2018-03-19 14:56
@4creators, that one has been failing since https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_jitstressregs4/465/

It may have not been running before since the JIT Stress Reg jobs don't set `EnableIncompleteISAClass`.

@CarolEidt, @fiigii, we should ensure we run the full suite of JIT Stress jobs (Reg, GC, etc) on any PR which marks an ISA as complete.

**Comment by AndyAyersMS** [comment] 2018-03-21 23:39
Think the ConvertToDouble case may need to use `movsdsse2` to distinguish it from the normal `movsd`. Trying that now.

**Comment by AndyAyersMS** [comment] 2018-03-21 23:46
Seems like that did the trick; the StressRegs=4 needs one reg, reg movsd while without stress regs the movsds are all reg/mem variants.
```
       C4410310F7           vmovsd   xmm14, xmm15
```

**Comment by AndyAyersMS** [comment] 2018-03-22 01:11
I can't repro the k-nucleotide-9 failure in isolation (tried may be 50 runs). Seems like in CI we may be running a lot of tests concurrently and this test is multithreaded so it may experience quite different scheduling on a heavily loaded machine. So I'll see if I can simulate that sort of setup.

**Comment by AndyAyersMS** [comment] 2018-03-22 02:35
Ok, I can repro it now, maybe once every 20 runs or so.

**Comment by AndyAyersMS** [comment] 2018-03-22 17:22
Think the k-nucleotide-9 may be an issue with GCStress, I see a lot of `c0000096` exceptions (priveledged instruction) before a final AV, RAX looks correct, and there is no heap corruption at the point of failure.
```
(1198.39b8): Unknown exception - code c0000096 (first chance)
(1198.3988): Unknown exception - code c0000096 (first chance)
(1198.3988): Unknown exception - code c0000096 (first chance)
(1198.39b8): Unknown exception - code c0000096 (first chance)
...
(1198.39b8): Unknown exception - code c0000096 (first chance)
(1198.3988): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
System_Private_CoreLib!System.Collections.Generic.ArraySortHelper`1[[System.Int32, System.Private.CoreLib]].CreateArraySortHelper()+0x68:
00007ff9`55c0cc78 ff5028          call    qword ptr [rax+28h] ds:00007ff9`555fc920={System_Private_CoreLib!System.RuntimeType.get_TypeHandle() (00007ff9`55664790)}

;; memory at RAX
00007ff9`555fc8f8 00007ff955630840 System.Type.GetProperty(System.String, System.Reflection.BindingFlags)
00007ff9`555fc900 00007ff955665890 System_Private_CoreLib!System.Type.GetProperty(System.String, System.Reflection.BindingFlags, System.Reflection.Binder, System.Type, System.Type[], System.Reflection.ParameterModifier[])
00007ff9`555fc908 00007ff955665960 System_Private_CoreLib!System.RuntimeType.GetPropertyImpl(System.String, System.Reflection.BindingFlags, System.Reflection.Binder, System.Type, System.Type[], System.Reflection.ParameterModifier[])
00007ff9`555fc910 00007ff955630fe8 System.RuntimeType.GetProperties(System.Reflection.BindingFlags)
00007ff9`555fc918 00007ff955630d98 System.RuntimeType.GetDefaultMembers()
00007ff9`555fc920 00007ff955664790 System_Private_CoreLib!System.RuntimeType.get_TypeHandle()
```
Will see if I can catch one of these earlier exceptions...

**Comment by AndyAyersMS** [comment] 2018-03-22 21:00
Similar looking failure in regex-redux-5:
```
(276c.4d3c): Unknown exception - code c0000096 (first chance)
(276c.4e88): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
System_Private_CoreLib!System.Reflection.Emit.DynamicILGenerator.GetTokenFor(System.Reflection.RuntimeFieldInfo, System.RuntimeType)+0x1b:
00007ff9`58d275cb ff5030          call    qword ptr [rax+30h] ds:00007ff9`5889ab20={System.Reflection.RtFieldInfo.get_FieldHandle() (00007ff9`58777618)}
```
Both these tests are heavily multi-threaded so would guess we are hitting some kind of race condition in gcstress here. @swaroop-sridhar does this look at all familiar?

Suggest we disable these from running in stress for now.

**Comment by AndyAyersMS** [comment] 2018-03-27 01:21
JIT_Methodical.refany__il_relarray3__il_relarray3 fails deterministically for x86, gcstress 0xC, minopts. Have split this into its own issue #17242.

**Comment by AndyAyersMS** [comment] 2018-03-27 23:57
jit\HardwareIntrinsics\X86\Avx\ConvertToVector_ro fails deterministically for x86, gcstress, jitstress=2. Haves split this into its own issue #17278.

**Comment by AndyAyersMS** [comment] 2018-03-29 02:58
Can't get waitanyex5 to fail for me locally.

 I can get CoreMangLib_cti.system_reflection_emit_DynMethodJumpStubTests to fail about one in every 10 runs or so. Usually with an AV though sometimes with a GC mode contract failure.

A number of the multithreaded tests seem to be getting random AVs under stress and I suspect it's from the race condition mentioned here:
https://github.com/dotnet/coreclr/blob/757cb82a5800fd043713d7ee40feba1dd2c89793/src/vm/gccover.cpp#L1507-L1517

There are several places now where we update instructions without waiting for EE suspension, eg in code just below the aforementioned comment when we're in partially interruptible code and have broken in at a non-safepoint, or over in `RemoveGcCoverageInterrupt` if we discover are looking at the call that checks for GC in a pinvoke epilog.

I don't know if we can just defer all instruction updates and tolerate the extra interrupts somehow or whether there is some deeper issue that needs sorting.

For 2.1 we might consider stress disabling any multithreaded tests that fails GC stress. But I will see if there is some simple way to clean up the races first.

**Comment by AndyAyersMS** [comment] 2018-03-29 08:09
Instead of avoiding races that lead to spurious AVs, we might also be able to tolerate them, by enabling this code more broadly:
https://github.com/dotnet/coreclr/blob/1265ced3ee70de32246055a3915410583d338b67/src/vm/excep.cpp#L6946-L6966

**Comment by AndyAyersMS** [comment] 2018-03-29 16:57
Broadening the tolerance scheme seems to fix the frequent AV issue. But in multithreaded tests I see the following around 2% of the time:
```
Assert failure(PID 12008 [0x00002ee8], Thread: 18072 [0x4698]): Consistency check failed: hit privileged instruction!FAILED: !ExecutionManager::IsManagedCode(GetIP(pContext))

CORECLR! CHECK::Trigger + 0x2C2 (0x00007ff9`b947da82)
CORECLR! IsGcMarker + 0x203 (0x00007ff9`b9564153)
CORECLR! CLRVectoredExceptionHandlerShim + 0x9C (0x00007ff9`b9550c2c)
```

I think this might be a different symptom of the same race. Am going to see retrying `OnGcCoverageInterrupt` helps here.

Also there seem to be some instruction stream updates where we don't call `FlushInstructionCache` afterwards, or do call it but perhaps don't pass in a large enough extent. Fixing those might reduce the frequency of the races.

**Comment by AndyAyersMS** [comment] 2018-04-04 23:52
I think the various failures here have been fully parceled out to other issues so I'm closing this.

**Closed** 2018-04-05 17:56 UTC
Labels: GCStress, JitStress, Post-ZBB, area-CodeGen, bug, reliability
