### ISSUE TITLE
JetBrains dotMemory and dotTrace fail on 3.0 preview

### ISSUE THREAD

**Issue by Wraith2** [dotnet/coreclr#21559] opened 2018-12-16 12:02 UTC
I've reported this as an issue through JetBrains support because it looks like an internal assumption in their software which is no longer true in 3.0. I realised it might be a good idea to post here in case it isn't.

When attempting to do a cpu or memory profile against CoreRun with one of the tools in the title the run will fail attempting to use the profiling api with the error in the screenshot below:
![capture](https://user-images.githubusercontent.com/13322696/50053278-23a85780-012a-11e9-91b9-166907d59fb8.PNG)

I interpret this to be a request for a specific type in the runtime and that the failure is unexpected and unhandled. My assumption is that the type is no longer named as expected or no longer present because of changed to internal structures (probably to do with unloadable assemblies).

**Comment by AaronRobinsonMSFT** [comment] 2018-12-17 01:46
This looks like it may be the result of some interop call. Assigning the interop label until something proves otherwise.

**Comment by jkotas** [comment] 2018-12-17 13:19
If possible, could you please add a link to the to the JetBrains support issue or tag the JetBrains engineers looking into this?

My guess is that this is likely side-effect of one of the AppDomain-related cleanups (cc @janvorli).

**Comment by janvorli** [comment] 2018-12-17 15:16
The error says "the shared domain have to be detected there. The shared domain was removed from the runtime in #21031. If JetBrains calls ClrDataAccess::GetAppDomainStoreData from DAC and expects the DacpAppDomainStoreData.sharedDomain to be non-NULL, it can be causing the issue.

**Comment by jkotas** [comment] 2018-12-17 16:54
`ClrDataAccess::GetAppDomainStoreData` is internal SOS/debugger interface. I doubt that the profiler calls this API.

My guess is that the profiler calls `ProfToEEInterfaceImpl::GetAppDomainInfo` and gets confused because of it does not see the shared domain anymore. This old comment touches on this: https://github.com/dotnet/coreclr/blob/49ca3db92a48da71d25c607af9716a30bafb3ff8/src/vm/proftoeeinterfaceimpl.cpp#L5672

**Comment by Wraith2** [comment] 2018-12-17 18:40
Thanks for the info. I've updated the ticket with the info and link to this thread.

**Comment by ww898** [comment] 2018-12-17 19:21
Hi there, I'm took a look in JB memory profiler sources. It's too complicated to debug the issue without repro case (our test team can't reproduce it now). However, I gathered following information. The exception appears during `GarbageCollectionFinished()` callback when profiler is fully active. At this moment I expect that the shared application domain was loaded and initialized. However, the shared app domain detector failed in the JB profiler, so, we got the exception. It's possible in following cases:
- GC appears before first `ModuleLoadFinished` call (unreal on my opinion)
- `CORPROF_E_DATAINCOMPLETE` during `GetModuleInfo` in `ModuleLoadFinished` callback
- the name of the shared app domain changed, I expect `EE Shared Assembly Repository`.
- `GetAssemblyInfo` in `ModuleLoadFinished` callback returns zero `AppDomainID`
...

@Wraith2 Could you please send to support@jetbrains.com  the repro case? It's very importnat for fixing.

**Comment by Wraith2** [comment] 2018-12-17 19:44
Just working on putting the replication together now, will upload to the ticket as soon as I can. 

It's CoreRun specific at the moment because that's the only thing pulling in the latest clr bits, the preview runtime publicly available doesn't have the changes that cause the issue. It will affect very few people unless they're on nightly builds and those people know what they've getting into.

**Comment by benaadams** [comment] 2018-12-17 19:53
> It's CoreRun specific at the moment because

Can reference the dotnet myget in NuGet.config https://dotnet.myget.org/F/dotnet-core/api/v3/index.json and add the latest runtime to the .csproj via `RuntimeFrameworkVersion`?

e.g.
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <TieredCompilation>false</TieredCompilation>
    <RuntimeFrameworkVersion>3.0.0-preview-27217-02</RuntimeFrameworkVersion>
  </PropertyGroup>
</Project>
```

Goes funny when capturing a snapshot in dotMemory

**Comment by benaadams** [comment] 2018-12-17 20:17
Install latest 3.0.x runtime sdk https://github.com/dotnet/core-sdk and/or latest runtime https://github.com/dotnet/core-setup#daily-builds

You'll want to reference the version number of the latest runtime (currently 3.0.0-preview-27217-02)

Then this project will repo it https://aoa.blob.core.windows.net/aspnet/dotMemory.zip

**Comment by Wraith2** [comment] 2018-12-18 16:32
Public issue is here: https://youtrack.jetbrains.com/issue/PROF-790

**Comment by Anna-Guseva** [comment] 2018-12-18 16:39
Hi, I'm a member of JetBrains memory profiler team. We've reproduced this issue in our environment. Profiling works properly if run application via dotnet.exe 3.0.27122.1 but it fails if run via dotnet.exe 3.0.27214.1. We are debugging it now and you can follow the ticket in our bug tracker.

**Comment by ww898** [comment] 2018-12-18 18:17
The issue appears after commit `b6d47b3a1b5b05c25968701615707e381f35a7ce` "Delete code related to LoaderOptimization and SharedDomain (#21031)".

It surprised me a lot. Could you please tell me how can I collect static app domain variables in this case?

**Comment by jkotas** [comment] 2018-12-18 18:30
@ww898 Thanks for looking into this. Could you please explain why you mean by "static app domain variables"? Which profiler API are you calling that does not return the expected result anymore?

**Comment by jkotas** [comment] 2018-12-19 01:18
Correct, there is no shared domain in CoreCLR.

Do you think it would be useful to change CoreCLR to return fake extra domain from `GetAppDomainsContainingModule` API and make `GetAppDomainInfo` to return `EE Shared Assembly Repository` name for it to mimic the old behavior? Or would you prefer a clean design and rather just update your profiler implementation?

**Comment by ww898** [comment] 2018-12-19 13:15
Surely clean design. I'm writing the fix.

**Comment by ww898** [comment] 2018-12-20 23:12
Fix is ready. We need time to test it on all frameworks.

**Comment by davidfowl** [comment] 2019-01-05 06:00
@ww898 Any ETA? Will it be in the next EAP?

**Comment by ww898** [comment] 2019-01-05 12:57
@davidfowl The fix is in 2019 EAP1 now.

**Comment by Wraith2** [comment] 2019-01-05 13:08
what is EAP?

**Comment by benaadams** [comment] 2019-01-05 13:13
Early Access Program (prerelease)

**Comment by davidfowl** [comment] 2019-01-05 16:38
Where do I find that? I keep finding the Version: 2018.3.1 EAP

**Comment by Anna-Guseva** [comment] 2019-01-10 11:45
@davidfowl 2019 EAP1 will be available not earlier than February 2019.

**Comment by davidfowl** [comment] 2019-01-10 15:00
😞 I can wait I guess, I'm using dotTrace timeline mode to look at memory allocations for now.

**Comment by davidfowl** [comment] 2019-02-09 06:36
@Anna-Guseva any word?

**Comment by maartenba** [comment] 2019-03-15 12:24
FYI latest 2019.1 EAP has 3.0 support

**Closed** 2019-04-14 09:35 UTC
Labels: area-Diagnostics
