### ISSUE TITLE
Enum.ToString() for flags-enums can produce inconsistent results

### ISSUE THREAD

**Issue by wizofaus** [dotnet/coreclr#14843] opened 2017-11-03 12:13 UTC
[Flags]
        enum TestEnum
        {
            A = 3, B = 4
        }
        [Flags]
        enum TestEnum2
        {
            A = 3, B = 4, C = 5
        }
        static void Main(string[] args)
        {
            Console.WriteLine(TestEnum.A|TestEnum.B);
            Console.WriteLine(TestEnum2.A|TestEnum2.B);
        }

Expected output would surely be
A,B
A,B
But actual output is:
A,B
7

This is due to the fact that Enum.ToString() for [Flags] enums assumes that if the value 7 (3|4) happens to include the value 5 (C) via a bitwise mask, then it must be representable by combining C with a lower permitted value.

dotnet version 2.0.0

**Comment by jkotas** [comment] 2017-11-03 15:05
The above enums do not follow guidelines for Flags enums https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=netcore-2.0 : "Define enumeration constants in powers of two, that is, 1, 2, 4, 8, and so on".

**Comment by wizofaus** [comment] 2017-11-03 19:25
"Guidelines", sure, but it's not an actual language error to define a flags enum as above, and there are definitely potential use cases - e.g. to make it clear that not all bit combinations are permitted or meaningful.
If it were required that you stick to powers of two the ToString() algorithm as is could be greatly simplified.

**Comment by karelz** [comment] 2018-01-18 04:55
This gets quickly tricky IMO - different output may satisfy different scenarios. I believe that current output 7 is pretty good - giving up on bits combinations as soon as there is bit overlap in the values.

Given it would be also a breaking change and divergence from .NET Framework, I don't think it is worth it - closing as By Design / Won't Fix.
If anyone needs this functionality, it should be implementable as a library.
If there is clear/strong "obvious behavior/improvement", we could consider it, but I don't see it in this case.

**Closed by karelz** 2018-01-18 04:55 UTC
Labels: area-Meta-corelib

**Comment by jzabroski** [comment] 2019-04-26 14:58
https://github.com/DotNetAnalyzers/ReflectionAnalyzers/issues/213
