### ISSUE TITLE
System.Numerics.Tensor, can't create with > 2G elements

### ISSUE THREAD

**Issue by jignparm** [dotnet/coreclr#23754] opened 2019-04-05 00:59 UTC
The constructor of Tensor()  class takes an int32 value, and thus cannot create large tensor objects.

https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Tensors/src/System/Numerics/Tensors/Tensor.cs#L269

OnnxRuntime depends on System.Numerics.Tensor to score machine learning models, some of which produce quite large tensors. While the native C++ API can handle large tensors produced by some models, the C# API is not able to handle them due to this 2G limitation.

See the corresponding issue below:

https://github.com/Microsoft/onnxruntime/issues/713

**Comment by tannergooding** [comment] 2019-04-05 01:04
The 2b element limitation is a fundamental one in the runtime for both `Span<T>` and `T[]`.

CC. @jkotas, @danmosemsft

**Comment by jkotas** [comment] 2019-04-05 02:57
Right. Duplicate of https://github.com/dotnet/coreclr/issues/23132 that has more discussion on this topic.

**Closed by jkotas** 2019-04-05 02:57 UTC

**Comment by faxu** [comment] 2019-08-14 23:05
https://github.com/dotnet/coreclr/issues/23132
