### ISSUE TITLE
[JitStress=2] JIT/Directed/Arrays/Complex2/Complex2.exe fails

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#2652] opened 2016-01-14 16:58 UTC
**Configuration:**
 coreclr, mscorlib: Checked
 coreclr tests: Checked
 corefx: Release
 OS: Linux
commit: c84ac790576e774bf7b72f28da8367ee35372c5a

JIT/Directed/Arrays/Complex2

**Expected Output:**
  Starting...
 
 Try to get count!
 128Count is:128
 Everything Worked!
 ($? = 100)

**Output under COMPlus_JitStress=2**

 Starting...
 
 Try to get count!
 128Count is:128
 Sum is:450

 Everything Didnt Work!
 ($? = 1)

**Comment by hoyMS** [comment] 2016-01-14 22:52
Not repro on either Windows and Linux.

**Comment by RussKeldorph** [comment] 2016-01-15 00:37
Still repros (for me & others).

**Comment by hoyMS** [comment] 2016-01-15 16:59
This is caused by calling fgMorph in optPerformHoistExpr:

Before 
N043 (  1,  1) [000806] ------------                         /--*  lclVar    int    V04 loc3         u:7 $380
N044 (  3,  3) [000805] ------------                      /--*  +         int    $348
N042 (  1,  1) [000807] ------------                      |  \--*  lclVar    int    V05 loc4         u:7 $381
N045 (  5,  5) [000804] ------------                   /--*  +         int    $349
N041 (  1,  1) [000808] ------------                   |  \--*  lclVar    int    V06 loc5         u:7 $382
N046 (  7,  7) [000803] ------------                /--*  +         int    $34a
N040 (  1,  1) [000809] ------------                |  \--*  lclVar    int    V07 loc6         u:7 $383
N047 (  9,  9) [000802] ------------             /--*  +         int    $34b
N039 (  1,  1) [000810] ------------             |  \--*  lclVar    int    V08 loc7         u:7 $384
N048 ( 11, 11) [000801] ------------             *  +         int    $34c
N038 (  1,  1) [000811] ------------             \--*  lclVar    int    V09 loc8         u:7 $385

After
 (  1,  1) [001747] -------H----             |  /--*  lclVar    int    V04 loc3         u:7 $380
     ( 11, 11) [001737] -------H----             \--*  +         int    $34c
     (  1,  1) [001746] -------H----                |  /--*  lclVar    int    V05 loc4         u:7 $381
     (  9,  9) [001739] ------------                \--*  +         int    $34b
     (  1,  1) [001744] -------H----                   |  /--*  lclVar    int    V06 loc5         u:7 $382
     (  7,  7) [001741] ------------                   \--*  +         int    $34a
     (  1,  1) [001742] -------H----                      |  /--*  lclVar    int    V07 loc6         u:7 $383
     (  5,  5) [001743] ------------                      \--*  +         int    $349
     (  1,  1) [001740] -------H----                         |  /--*  lclVar    int    V08 loc7         u:7 $384
     (  3,  3) [001745] ------------                         \--*  +         int    $348
     (  1,  1) [001738] -------H----                            \--*  lclVar    int    V09 loc8         u:7 $385

See the value number $34b doesn't reflect the same expressions before and after.

**Comment by hoyMS** [comment] 2016-01-15 17:17
When fgMorph is called after value numbering, we have to ensure that a correct or a new value number is assigned to the resulting tree.

**Comment by hoyMS** [comment] 2016-01-16 03:10
Fix checked in by PR#2686

**Closed by hoyMS** 2016-01-16 03:10 UTC
Labels: bug, CodeGen
