### ISSUE TITLE
ReadOnlySpan stackalloc arrays initializer issue

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#20340] opened 2018-10-10 02:48 UTC
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        for (int length = 0; length < byte.MaxValue; length++)
        {
            char[] a = new char[length];
            for (int i = 0; i < length; i++)
            {
                a[i] = (char)(i + 1);
            }
            ReadOnlySpan<char> span = new ReadOnlySpan<char>(a);

            for (int targetIndex = 0; targetIndex < length; targetIndex++)
            {
                // Using new *****************
                ReadOnlySpan<char> values = new[] { (char)a[targetIndex], (char)0, (char)0, (char)0, (char)0 };
                int idx = span.IndexOfAny(values);
                if (targetIndex != idx)
                {
                    Console.WriteLine($"Error, targetIndex:{targetIndex} length: {length}");
                    return;
                }
            }
        }

        Console.WriteLine("All fine");
    }
}
```
outputs `All fine`
```csharp
public class Program
{
    public static void Main(string[] args)
    {
        for (int length = 0; length < byte.MaxValue; length++)
        {
            char[] a = new char[length];
            for (int i = 0; i < length; i++)
            {
                a[i] = (char)(i + 1);
            }
            ReadOnlySpan<char> span = new ReadOnlySpan<char>(a);

            for (int targetIndex = 0; targetIndex < length; targetIndex++)
            {
                // Using stackalloc instead of new *****************
                ReadOnlySpan<char> values = stackalloc[] { (char)a[targetIndex], (char)0, (char)0, (char)0, (char)0 };
                int idx = span.IndexOfAny(values);
                if (targetIndex != idx)
                {
                    Console.WriteLine($"Error, targetIndex:{targetIndex} length: {length}");
                    return;
                }
            }
        }

        Console.WriteLine("All fine");
    }
}
```
outputs `Error, targetIndex:0 length: 1`

**Comment by benaadams** [comment] 2018-10-10 05:43
Looks like it might have core dumped on OSX and Linux for a similar pattern

**Comment by benaadams** [comment] 2018-10-10 09:42
Yes relatated, the pre-version of https://github.com/dotnet/corefx/pull/32734/commits/d9571bf8594fee0e3e8191a637c45ed62dc2027d segfaults on OSX and Linux arm

**Comment by AndyAyersMS** [comment] 2018-10-10 18:08
I'll take a look.

**Comment by AndyAyersMS** [comment] 2018-10-10 18:21
This looks like an IL issue -- the IL simply says to set all the values to zero.
```
  IL_002b:  ldc.i4.s   10
  IL_002d:  conv.u
  IL_002e:  localloc
  IL_0030:  dup
  IL_0031:  ldc.i4.0
  IL_0032:  ldc.i4.s   10
  IL_0034:  initblk
  IL_0036:  ldc.i4.5
  IL_0037:  newobj     instance void valuetype [System.Private.CoreLib]System.Span`1<char>::.ctor(void*,
                                                                                                  int32)
```
contrast with the working version where one element is set nonzero:
```
  IL_002b:  ldc.i4.5
  IL_002c:  newarr     [System.Private.CoreLib]System.Char
  IL_0031:  dup
  IL_0032:  ldc.i4.0
  IL_0033:  ldloc.1
  IL_0034:  ldloc.s    targetIndex
  IL_0036:  ldelem.u2
  IL_0037:  stelem.i2
  IL_0038:  call       valuetype [System.Private.CoreLib]System.ReadOnlySpan`1<!0> valuetype [System.Private.CoreLib]System.ReadOnlySpan`1<char>::op_Implicit(!0[])
```
cc @jaredpar

**Comment by jaredpar** [comment] 2018-10-10 19:47
Looks like a duplicate of https://github.com/dotnet/roslyn/issues/29092

**Comment by AndyAyersMS** [comment] 2018-10-10 23:14
I would not expect this to lead to core dumps though, just a lack of non-zero values. Let me look into that part.

**Comment by benaadams** [comment] 2018-10-10 23:28
May have been coincidence.

The other active path when core dumping was running methods as part of the init if that makes a difference: 
```csharp
stackalloc[] { (char)rnd.Next(1, 256), (char)rnd.Next(1, 256), (char)rnd.Next(1, 256), (char)rnd.Next(1, 256) };
```

**Comment by RussKeldorph** [comment] 2019-01-14 18:30
@AndyAyersMS Any update?

**Comment by AndyAyersMS** [comment] 2019-01-14 18:41
No -- need to actually go look.

**Comment by AndyAyersMS** [comment] 2019-02-08 18:45
I can't repro any crashes with 3.0 preview 2.

@benaadams I'm going to close this. Please re-open if you run across a current repro case.

**Closed by AndyAyersMS** 2019-02-08 18:45 UTC
Labels: area-CodeGen, bug, needs repro
