### ISSUE TITLE
When running published executable with PublishReadyToRun=True Unhandled Exception: System.BadImageFormatException: Could not load file or assembly

### ISSUE THREAD

**Issue by wieslawsoltes** [dotnet/coreclr#24565] opened 2019-05-14 06:45 UTC
Exception:
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '/home/wieslaw_soltes/projects/Draw2D/Draw2D_netcoreapp3.0_debian.8-x64/Draw2D.dll'. An attempt was made to load a program with an incorrect format.
```
OS:
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
.NET Core version:
```
3.0.100-preview5-011568
```
Publish Command:
```
dotnet publish ./src/Draw2D/Draw2D.csproj -f netcoreapp3.0 -c Release -r debian.8-x64 -o Draw2D_netcoreapp3.0_debian.8-x64
```
to fix I had to change rid from `debian.8-x64` to `debian.9-x64`:
```
dotnet publish ./src/Draw2D/Draw2D.csproj -f netcoreapp3.0 -c Release -r debian.9-x64 -o Draw2D_netcoreapp3.0_debian.9-x64
```
than it works.

**Comment by jkotas** [comment] 2019-05-14 13:26
cc @fadimounir

**Comment by fadimounir** [comment] 2019-05-16 00:10
@wieslawsoltes Thanks for filing this issue. I was able to repro this failure, and confirmed that debian 9 works. I'll investigate.

**Comment by fadimounir** [comment] 2019-05-16 01:03
@wieslawsoltes I couldn't repro the BadImageFormatException, but I got a different error on my end. When I published for Debian8 and tried to run it, I got this error:
``` console
Failed to initialize CoreCLR,, HRESULT: 0x80131500
```

I used the same publish command that you posted above. What am I missing? The error i'm getting is kind of expected because I can see that the SDK is copying the runtime bits from the runtime.debian.8-x64.microsoft.netcore.runtime.coreclr/1.0.7/runtimes/debian.8-x64 package, which is incorrect.

BTW, my .NET Core version was `3.0.100-preview5-011569` (Release/3.0.1XX from https://github.com/dotnet/core-sdk)

@nguerrera Could someone on your team start taking a look at this bug and figure out why we're copying the wrong runtime bits to the `bin` folder?

On Debian9 targets, the runtime bits are copied correctly. On Debian8, the SDK doesn't resolve correctly. Here's an example error I got: 

``` console
/home/fadi/dotnet_preview5/sdk/3.0.100-preview5-011569/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(39,5): message NETSDK1041: Encountered conflict between 'CopyLocal:/home/fadi/.nuget/packages/runtime.debian.8-x64.microsoft.netcore.runtime.coreclr/1.0.7/runtimes/debian.8-x64/native/libcoreclr.so' and 'CopyLocal:/home/fadi/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/3.0.0-preview5-27709-08/runtimes/linux-x64/native/libcoreclr.so'.  NETSDK1037: Could not determine winner due to equal file and assembly versions. [/home/fadi/git/Draw2D/src/Draw2D/Draw2D.csproj]
```

Also, it ends up copying the runtime bits from the 1.0.7 runtime package. Example:

``` console
Copying file from "/home/fadi/.nuget/packages/runtime.debian.8-x64.microsoft.netcore.runtime.coreclr/1.0.7/runtimes/debian.8-x64/native/libcoreclr.so" to "/home/fadi/git/Draw2D/src/Draw2D/bin/Release/netcoreapp3.0/debian.8-x64/libcoreclr.so".
```

Repro app is here: https://github.com/wieslawsoltes/Draw2D

**Comment by fadimounir** [comment] 2019-06-13 21:45
@wieslawsoltes Do you have a callstack for the BadImageFormat exception?
It could be the same issue as #25009.

**Comment by wieslawsoltes** [comment] 2019-06-14 09:25
> @wieslawsoltes Do you have a callstack for the BadImageFormat exception?
> It could be the same issue as #25009.

I do not have call stack.

**Comment by fadimounir** [comment] 2019-06-17 20:19
Closing as a duplicate of #25009.
Filed https://github.com/dotnet/sdk/issues/3336 on the SDK side to track the dependency resolution issue that makes R2R crash.

**Closed by fadimounir** 2019-06-17 20:19 UTC
Labels: area-ReadyToRun
