### ISSUE TITLE
Unhandled Exception on Ubuntu 16.10 when running csc

### ISSUE THREAD

**Issue by mellinoe** [dotnet/coreclr#6510] opened 2016-07-28 19:54 UTC
We're planning on adding support for Ubuntu 16.10 in the next release cycle, along with a few other refreshed versions of distros. The product builds cleanly on Ubuntu 16.10, and can run a variety of `dotnet` commands (from the CLI SDK), but I'm hitting an unhandled exception when running csc.dll (C# compiler used in `dotnet build`). I can provide a repro or some additional information about the crash.

[Stack trace here](https://gist.github.com/mellinoe/c8731a10f3941b34cc0495f340802e55)

The kernel version: `4.4.0-31-generic`

Have we seen any other issues like this? I'm aware of the seg-fault affecting newer kernels, but I think this one (4.4.0) should be okay, and it doesn't seem to look the same.

**Comment by mellinoe** [comment] 2016-07-28 19:54
@janvorli , @jkotas, @ellismg

**Comment by jkotas** [comment] 2016-07-28 19:56
@sergiy-k

**Comment by sergiy-k** [comment] 2016-07-28 21:22
What is the call stack for the managed code?

**Comment by mellinoe** [comment] 2016-07-28 21:32
```
(lldb) clrstack
OS Thread Id: 0x51cc (1)
        Child SP               IP Call Site
00007FFFFFFF8688 00007ffff6d7a3c8 [PrestubMethodFrame: 00007fffffff8688] System.Reflection.Internal.FileStreamReadLightUp+NativeMethods.ReadFileModern(System.Runtime.InteropServices.SafeHandle, Byte*, Int32, Int32 ByRef, IntPtr)
00007FFFFFFF87C0 00007FFF7D371CC0 System.Reflection.Internal.FileStreamReadLightUp.TryReadFile(System.IO.Stream, Byte*, Int64, Int32)
00007FFFFFFF8810 00007FFF7D370CE4 Error: Fail to initialize CoreCLR
System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(System.IO.Stream, Boolean, Int64, Int32)
00007FFFFFFF8860 00007FFF7D370E25 Error: Fail to initialize CoreCLR
System.Reflection.Internal.StreamMemoryBlockProvider.GetMemoryBlockImpl(Int32, Int32)
00007FFFFFFF88C0 00007FFF7D370870 Error: Fail to initialize CoreCLR
System.Reflection.Internal.MemoryBlockProvider.GetMemoryBlock(Int32, Int32)
00007FFFFFFF88F0 00007FFF7D32FA76 Error: Fail to initialize CoreCLR
System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()
00007FFFFFFF89B0 00007FFF7D683800 Error: Fail to initialize CoreCLR
System.Diagnostics.StackTraceSymbols.GetPdbPathFromPeStream(System.String, IntPtr, Int32, Int32 ByRef, System.Guid ByRef, UInt32 ByRef)
00007FFFFFFF8AC0 00007FFF7D683578 Error: Fail to initialize CoreCLR
System.Diagnostics.StackTraceSymbols.GetReader(System.String, IntPtr, Int32, IntPtr, Int32)
00007FFFFFFF8B70 00007FFF7D68316C Error: Fail to initialize CoreCLR
System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(System.String, IntPtr, Int32, IntPtr, Int32, Int32, Int32, System.String ByRef, Int32 ByRef, Int32 ByRef)
00007FFFFFFF8D30 00007FFF7D5F01F4 Error: Fail to initialize CoreCLR
System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32, Boolean, System.Exception)
00007FFFFFFF8EE0 00007FFF7D5EF5E1 Error: Fail to initialize CoreCLR
System.Diagnostics.StackTrace.CaptureStackTrace(Int32, Boolean, System.Threading.Thread, System.Exception)
00007FFFFFFF9000 00007FFF7D5EF378 Error: Fail to initialize CoreCLR
System.Diagnostics.StackTrace..ctor(System.Exception, Boolean)
00007FFFFFFF9040 00007FFF7D5EF268 Error: Fail to initialize CoreCLR
System.Environment.GetStackTrace(System.Exception, Boolean)
00007FFFFFFF9090 00007FFF7D5EF170 Error: Fail to initialize CoreCLR
System.Exception.GetStackTrace(Boolean)
00007FFFFFFF9100 00007FFF7D5EED16 Error: Fail to initialize CoreCLR
System.Exception.ToString(Boolean, Boolean)
00007FFFFFFF91D0 00007FFF7D5EE97C Error: Fail to initialize CoreCLR
System.Exception.InternalToString()
00007FFFFFFF9688 00007ffff5bd584f [GCFrame: 00007fffffff9688] 
00007FFFFFFF9DE8 00007ffff5bd584f [GCFrame: 00007fffffff9de8] 
00007FFFFFFFB088 00007ffff5bd584f [HelperMethodFrame: 00007fffffffb088] 
00007FFFFFFFB190 00007FFF7D65B9DD Error: Fail to initialize CoreCLR
System.Diagnostics.FileVersionInfo.GetVersionInfo(System.String)
00007FFFFFFFB1B0 00007FFF7CD5DCB6 Error: Fail to initialize CoreCLR
Roslyn.Utilities.PortableShim+Misc.GetFileVersion(System.String)
00007FFFFFFFB1D0 00007FFF7CC3D05F Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CommonCompiler.GetAssemblyFileVersion()
00007FFFFFFFB200 00007FFF7C3EF2A7 Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(System.IO.TextWriter)
00007FFFFFFFB230 00007FFF7CC3DD7D Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CommonCompiler.RunCore(System.IO.TextWriter, Microsoft.CodeAnalysis.ErrorLogger, System.Threading.CancellationToken)
00007FFFFFFFB440 00007FFF7CC3DBCE Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CommonCompiler.Run(System.IO.TextWriter, System.Threading.CancellationToken)
00007FFFFFFFB4A0 00007FFF7BE858ED Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CSharp.CommandLine.Csc+<>c__DisplayClass1_0.<Run>b__0(System.IO.TextWriter)
00007FFFFFFFB4C0 00007FFF7BE85099 Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[[System.Int32, System.Private.CoreLib]](Boolean, System.IO.TextWriter, System.Func`2<System.IO.TextWriter,Int32>)
00007FFFFFFFB4E0 00007FFF7BE8369D Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(System.String[], Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)
00007FFFFFFFB560 00007FFF7BE839DE Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(System.String[], Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter)
00007FFFFFFFB5E0 00007FFF7BE84A58 Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.BuildPaths, System.IO.TextWriter)
00007FFFFFFFB6F0 00007FFF7BE83920 Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.RequestLanguage, Microsoft.CodeAnalysis.CommandLine.CompileFunc)
00007FFFFFFFB770 00007FFF7BE8382D Error: Fail to initialize CoreCLR
Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(System.String[])
00007FFFFFFFBC38 00007ffff5bd584f [GCFrame: 00007fffffffbc38] 
00007FFFFFFFC3E8 00007ffff5bd584f [GCFrame: 00007fffffffc3e8]
```

(I don't know why it prints out "Error: Fail to initialize CoreCLR" so many times)

It looks like it may be happening on [this line](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Diagnostics.FileVersionInfo/src/System/Diagnostics/FileVersionInfo.cs#L271) which is trying to construct/throw a `FileNotFoundException`.

**Comment by sergiy-k** [comment] 2016-07-28 21:52
Thank you! I wonder what does sos PrintException command show you?

**Comment by mellinoe** [comment] 2016-07-28 22:01
```
(lldb) pe
Exception object: 00007fff63b0e350
Exception type:   System.DllNotFoundException
Message:          Unable to load DLL 'api-ms-win-core-file-l1-1-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
InnerException:   <none>
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80131524
```

**Comment by sergiy-k** [comment] 2016-07-28 23:08
OK. This means that you are picking up a Windows specific version of some managed assembly that tries to p/invoke into a Windows library. You need to get the version compiled for Linux.

**Comment by jkotas** [comment] 2016-07-28 23:29
> This means that you are picking up a Windows specific version of some managed assembly that tries to p/invoke into a Windows library

This exception in System.Reflection.Metadata. It has Windows-specific light-up - it catches all exceptions and uses slower path if the light-up did not work:

https://github.com/dotnet/corefx/blob/3b057505de7a83df40bf5a7f80fb0bc36733264c/src/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/FileStreamReadLightUp.cs#L107

This crash is likely caused by catching all exceptions not working in this case.

**Comment by sergiy-k** [comment] 2016-07-28 23:34
Yeah, @mellinoe and I came to the same conclusion. Exception is handling is partially broken on this platform: it causes a crash in this specific case (when p/invoking into a library that does not existing) and in case of unhandled exception (i.e. just throwing from Main without having a catch handler). But basic exception handling functionality seems to work.

**Comment by janvorli** [comment] 2016-08-08 16:19
@mellinoe I suppose we can close this issue now that the JITter was fixed, right?

**Comment by janvorli** [comment] 2016-09-06 13:48
@mellinoe I am closing the issue since it should be fixed by a jitter fix made about a month ago..

**Closed by janvorli** 2016-09-06 13:48 UTC
