### ISSUE TITLE
Custom LoadContext cannot be unloaded once created

### ISSUE THREAD

**Issue by Suriman** [dotnet/coreclr#15623] opened 2017-12-23 12:33 UTC
Are there already defined plans of when this feature might be available?

This feature is sufficient for many scenarios and it would not be necessary to implement the download of the assemblies selectively.

**Comment by jkotas** [comment] 2017-12-23 17:28
This is called collectible assemblies. It is in our longer term plan, but it is not in the current plan for next release (.NET Core 2.1).

Duplicate of #552.

**Closed by jkotas** 2017-12-23 17:28 UTC
Labels: area-AssemblyLoader, question
