### ISSUE TITLE
[Linux]Build failed in release_ubuntu

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#23607] opened 2019-04-01 01:32 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/job/release_ubuntu/10611/

**Failed log:**
```
/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/dir.traversal.targets(25,5): error : (No message specified) [/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/src/dirs.proj]
/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/dir.traversal.targets(25,5): error : (No message specified) [/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/build.proj]

Build FAILED.

/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/dir.traversal.targets(25,5): error : (No message specified) [/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/src/dirs.proj]
/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/dir.traversal.targets(25,5): error : (No message specified) [/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/build.proj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:03:50.30
ERROR: An error occurred in /mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/.dotnet/dotnet msbuild /nologo /verbosity:minimal /clp:Summary /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount /mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/tests/build.proj /flp:Verbosity=normal;LogFile=/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Release.log;Append=true /flp1:WarningsOnly;LogFile=/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Release.wrn;Append=true /flp2:ErrorsOnly;LogFile=/mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Release.err;Append=true /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:__BuildArch=x64 /p:__BuildType=Release /p:__BuildOS=Linux /p:CLRTestPriorityToBuild=1. Check logs under /mnt/j/workspace/dotnet_coreclr/master/release_ubuntu.
Failed to build Managed tests build (build tests). See the build logs:
    /mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Release.log
    /mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Release.wrn
    /mnt/j/workspace/dotnet_coreclr/master/release_ubuntu/bin/Logs/Tests_Managed.Linux.x64.Release.err
Build step 'Execute shell' marked build as failure
```

**Comment by RussKeldorph** [comment] 2019-04-01 18:31
Assuming duplicate of #22142

**Closed by RussKeldorph** 2019-04-01 18:31 UTC
Labels: os-linux
