### ISSUE TITLE
JIT_Regression._JitBlue_GitHub_10940_GitHub_10940_GitHub_10940 test fails in Helix on non-Windows

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#11112] opened 2017-04-20 19:19 UTC
Test fails with a non-diagnostic error message:

> \n\nReturn code:      1\nRaw output file:      /home/helixbot/dotnetbuild/work/0ccaf8d7-0c9a-4880-915d-a2377f2380dc/Work/2b24fdb2-6b5b-4a83-b3bc-00d82818e9eb/Unzip/Reports\JIT.Regression\JitBlue\GitHub_10940\GitHub_10940\GitHub_10940.output.txt\nRaw output:\nBEGIN EXECUTION\n/home/helixbot/dotnetbuild/work/0ccaf8d7-0c9a-4880-915d-a2377f2380dc/Payload/corerun GitHub_10940.exe\nExpected: 100\nActual: 0\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\n\nTo run the test:\n> set CORE_ROOT=/home/helixbot/dotnetbuild/work/0ccaf8d7-0c9a-4880-915d-a2377f2380dc/Payload\n> /home/helixbot/dotnetbuild/work/0ccaf8d7-0c9a-4880-915d-a2377f2380dc/Work/2b24fdb2-6b5b-4a83-b3bc-00d82818e9eb/Unzip/JitBlue/GitHub_10940/GitHub_10940/GitHub_10940.sh\n\nExpected: True\nActual:   False

https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170420.03/workItem/JIT.Regression.XUnitWrapper/analysis/xunit/JIT_Regression._JitBlue_GitHub_10940_GitHub_10940_GitHub_10940_~2F_JitBlue_GitHub_10940_GitHub_10940_GitHub_10940_cmd

@pgavlin any idea why this could be happening?

**Comment by pgavlin** [comment] 2017-04-20 19:35
The only thing that comes to mind is that Helix is not using an up-to-date build. Is there any way to get the artifacts that were used to run the test when it failed? If so, we can find the corresponding commit for the build and ensure that it has the fix associated with this regression test.

**Comment by wtgodbe** [comment] 2017-04-20 19:40
I can get you the test binaries & Core_Root, if that would help. That test has been failing for at least a couple of days, and it looks like we haven't updated CoreClr's package dependencies for the last 3 days - could that have something to do with it? Will this test fail if we run it against binaries from 3-day old packages?

**Comment by pgavlin** [comment] 2017-04-20 19:43
Yes, absolutely. That test was just checked in yesterday and will fail if your build of clrjit does not contain commit 961f24096a9c2bfe4f848c27e0756669042a8985.

**Comment by wtgodbe** [comment] 2017-04-20 19:44
Well that'll be it, then. I'll re-assign this to myself & close it if it starts passing once we merge an auto-update PR. Thanks Pat!

**Comment by gkhanna79** [comment] 2017-04-21 19:08
Closed since fixed.

**Closed** 2017-04-21 19:08 UTC
Labels: area-Infrastructure
