### ISSUE TITLE
[RyuJIT][CQ] Loop trip count test is not efficient

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#3903] opened 2016-03-24 17:15 UTC
Per @hoyMS 
For the following loop, 

```
        long iterations = Int64.Parse(args[0]);
        for (long i = 0; i < iterations; i++)
        {
        }
```

RyuJit generates

```
G_M63536_IG03:
IN000d: 000041 mov      rdx, rax
IN000e: 000044 inc      rcx

G_M63536_IG04:
IN000f: 000047 cmp      rcx, rsi
IN0010: 00004A setl     r8b
IN0011: 00004E movzx    r8, r8b
IN0012: 000052 test     r8d, r8d
IN0013: 000055 jne      SHORT G_M63536_IG03
IN0014: 000057 mov      rax, rdx
```

Better would be:

```
00007ffb`45800545 488bce         :
00007ffb`4580054d 48ffc3          inc     rbx
00007ffb`45800550 483bdf          cmp     rbx,rdi
00007ffb`45800553 7cf0            jl      enum!M.NoTime(Int64)+0x35 (00007ffb`45800545)
```

There’s probably a phase ordering issue with the folding away of the setcc/cmp branch.

**Comment by mikedn** [comment] 2016-03-24 18:44
I can't reproduce this, the current CoreCLR build already generates the "better" code:
```
       E85C3C3F5E           call     System.Number:ParseInt64(ref,int,ref):long
       33D2                 xor      rdx, rdx
       4885C0               test     rax, rax
       7E08                 jle      SHORT G_M28756_IG04

G_M28756_IG03:
       48FFC2               inc      rdx
       483BD0               cmp      rdx, rax
       7CF8                 jl       SHORT G_M28756_IG03
```

And anyway, the better code would be no code at all as the loop doesn't do anything :)

**Comment by cmckinsey** [comment] 2016-03-24 20:55
Probably depends on whether you compile with csc /o+ or not.

**Comment by mikedn** [comment] 2016-03-24 21:22
If csc /o- is used then cmp-setl does show up but there are also a bunch of stack load/stores. Perhaps this happens on an internal branch that isn't published yet :)

**Comment by AndyAyersMS** [comment] 2018-04-24 19:49
Seems like we could perhaps close this...

**Comment by mikedn** [comment] 2018-04-24 19:59
I've checked that the current build still produces the expected code:
```asm
G_M33480_IG04:
       48FFC1               inc      rcx
       483BC8               cmp      rcx, rax
       7CF8                 jl       SHORT G_M33480_IG04
```
The relevant IL produced by the IL compiler is
```
    IL_0014:  ldloc.2
    IL_0015:  ldloc.1
    IL_0016:  blt.s      IL_000f
```
and I don't see how `blt` could expand to `(x < y) != 0`. Perhaps some stress mode...

I don't see any reason to keep this opened without a clear repro.

**Comment by AndyAyersMS** [comment] 2018-05-03 22:45
Agreed; closing.

**Closed by AndyAyersMS** 2018-05-03 22:45 UTC
Labels: area-CodeGen, enhancement, optimization, tenet-performance
