### ISSUE TITLE
Enabling FeaturePerfTracing in mscorlib breaks support for EventListeners on Windows

### ISSUE THREAD

**Issue by nategraf** [dotnet/coreclr#15656] opened 2017-12-28 15:57 UTC
If FeaturePerfTracing is enabled in clr.coreclr.props, EventListeners no longer receive events. I should be possible to enable this feature without breaking EventListeners

**Comment by brianrob** [comment] 2018-01-29 23:45
Duplicate of #15494.

**Closed by brianrob** 2018-01-29 23:45 UTC
Labels: area-Tracing
