### ISSUE TITLE
[arm/linux] Tests failed in arm_cross_checked_ubuntu_corefx_jitstressregs1_tst

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21464] opened 2018-12-10 07:14 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/37/
**Failed tests:**
```
===== Failed tests:
=====     Microsoft.Win32.Primitives.Tests
=====     System.Collections.Immutable.Tests
=====     System.ComponentModel.TypeConverter.Tests
=====     System.Composition.Tests
=====     System.Data.Common.Tests
=====     System.ComponentModel.Composition.Tests
=====     System.Collections.Tests
=====     System.Globalization.Tests
=====     System.IO.Compression.ZipFile.Tests
=====     System.IO.FileSystem.Watcher.Tests
=====     System.IO.MemoryMappedFiles.Tests
=====     System.IO.Compression.Brotli.Tests
=====     System.IO.Compression.Tests
=====     System.Net.NetworkInformation.Functional.Tests
=====     System.Net.Ping.Functional.Tests
=====     System.IO.Pipes.Tests
=====     System.Net.Security.Tests
=====     System.Linq.Parallel.Tests
=====     System.Net.WebSockets.Client.Tests
=====     System.Reflection.Extensions.Tests
=====     System.Private.Uri.Functional.Tests
=====     System.Reflection.Metadata.Tests
=====     System.Reflection.Tests
=====     System.Runtime.InteropServices.RuntimeInformation.Tests
=====     System.Runtime.InteropServices.Tests
=====     System.Runtime.Extensions.Tests
=====     System.Net.Sockets.Tests
=====     System.Reflection.Emit.Tests
=====     System.Security.Cryptography.Csp.Tests
=====     System.Security.Cryptography.Algorithms.Tests
=====     System.Security.Cryptography.Encoding.Tests
=====     System.Security.Cryptography.Pkcs.Tests
=====     System.Security.Cryptography.OpenSsl.Tests
=====     System.Security.Cryptography.X509Certificates.Tests
=====     System.Threading.Overlapped.Tests
=====     System.Runtime.Numerics.Tests
=====     System.Threading.Thread.Tests
=====     System.Transactions.Local.Tests
=====     System.Threading.Tests
=====     System.Xml.XmlSerializer.Tests
=====     System.Xml.Xsl.XslTransformApi.Tests
=====     System.Xml.Xsl.XslCompiledTransformApi.Tests
```
**Some logs:**
```
/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/Microsoft.Win32.Primitives.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/Microsoft.Win32.Primitives.Tests/netcoreapp-Linux-Release-arm
[37m  Discovering: Microsoft.Win32.Primitives.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  Microsoft.Win32.Primitives.Tests (found 2 test cases)
[m[37m  Starting:    Microsoft.Win32.Primitives.Tests (parallel test collections = on, max threads = 4)
[m[31;1m    System.ComponentModel.Tests.Win32ExceptionTestType.InstantiateExceptionWithLongErrorString [FAIL]
[m[37m      System.DllNotFoundException : Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
[m[30;1m      Stack Trace:
[m[37m           at System.ComponentModel.Tests.Win32ExceptionTestType.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/Microsoft.Win32.Primitives/tests/Win32ExceptionTests.cs(33,0): at System.ComponentModel.Tests.Win32ExceptionTestType.IsExceptionMessageLong(Int32 errorCode)
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/Microsoft.Win32.Primitives/tests/Win32ExceptionTests.cs(97,0): at System.ComponentModel.Tests.Win32ExceptionTestType.InstantiateExceptionWithLongErrorString()
[m[37m  Finished:    Microsoft.Win32.Primitives.Tests
[m[37m=== TEST EXECUTION SUMMARY ===
[m[37m   Microsoft.Win32.Primitives.Tests  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 5.710s
[m[m/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/Microsoft.Win32.Primitives.Tests/netcoreapp-Linux-Release-arm
----- end 21:07:30 ----- exit code 1 ----------------------------------------------------------
```
```
/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Collections.Immutable.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Collections.Immutable.Tests/netcoreapp-Linux-Release-arm
[37m  Discovering: System.Collections.Immutable.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Collections.Immutable.Tests (found 919 test cases)
[m[37m  Starting:    System.Collections.Immutable.Tests (parallel test collections = on, max threads = 4)
[m[31;1m    System.Collections.Immutable.Tests.ImmutableArrayTest.CreateRangeSliceWithSelectorAndArgument [FAIL]
[m[37m      System.IndexOutOfRangeException : Index was outside the bounds of the array.
[m[31;1m    System.Collections.Immutable.Tests.ImmutableArrayTest.CreateRangeSliceWithSelector [FAIL]
[m[37m      System.IndexOutOfRangeException : Index was outside the bounds of the array.
[m[31;1m    System.Collections.Immutable.Tests.ImmutableArrayTest.CreateRangeWithSelector [FAIL]
[m[37m      System.IndexOutOfRangeException : Index was outside the bounds of the array.
[m[31;1m    System.Collections.Immutable.Tests.ImmutableArrayTest.CreateRangeWithSelectorAndArgument [FAIL]
[m[37m      System.IndexOutOfRangeException : Index was outside the bounds of the array.
[m[37m  Finished:    System.Collections.Immutable.Tests
[m[37m=== TEST EXECUTION SUMMARY ===
[m[37m   System.Collections.Immutable.Tests  Total: 1876, Errors: 0, Failed: 4, Skipped: 0, Time: 185.023s
[m[m/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Collections.Immutable.Tests/netcoreapp-Linux-Release-arm
----- end 21:12:03 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment] 2018-12-11 22:02
This also shows up in the baseline run.

@dotnet/arm32-contrib Looks like a pretty fundamental regression.

**Comment by danmosemsft** [comment] 2018-12-12 23:35
The first log above is because you are not excluding Windows-only tests.  This test is not intended for Windows. Can you check the script is passing the appropriate trait flags to xunit?
```
        [PlatformSpecific(TestPlatforms.Windows)]  // Uses P/Invokes to check whether the exception resource length >256 chars
        public static void InstantiateExceptionWithLongErrorString()
```
I don't know about the other failures but I wouldn't waste time analyzing until you've re run with just the tests applicable to Linux ARM.

Separately, note that we have a fair bit of test-disabling to do for ARM, many of these test failures are tests that should not have run on ARM: https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Atest-run-core+label%3Aarch-arm32+author%3Ajoperezr
So the run will not yet be clean.

**Comment by danmosemsft** [comment] 2018-12-12 23:35
cc @joperezr

**Comment by danmosemsft** [comment] 2018-12-13 00:09
I had a real quick look to see whether there were other systemic issues and it seems the run did not exclude tests with active issues either eg:
```
  162          [ActiveIssue(25498)]
  163:         public void MergeResult_ResultWithNullErrorsAsResultArgument_ShouldReturnResultWithSameErrors()
```

There are a few failures that look like cases that CoreFX should fix tests for eg `System.ComponentModel.Composition.AssemblyCatalogConstructorTests.Constructor4_TooLongFileNameAsCodeBaseArgument_ShouldThrowPathTooLong [FAIL]` is because they seem to have enabled long paths by default now.

But I expect your run will be in far better shape when you have fixed the filters.

**Comment by BruceForstall** [comment] 2018-12-13 01:06
@danmosemsft Thanks for looking. Between Dec. 2 and Dec. 9 we went from failures in 2 assemblies to failures in 42 assemblies. As far as I know, we haven't changed how we build the corefx tests. You can see it here:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_jitstressregs1/46/consoleFull
```
12:39:23 12:51:46 [/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/tests/scripts/run-corefx-tests.py]: ./build.sh -test -Release /p:OSGroup=Linux /p:ArchGroup=arm -SkipTests  /p:WithoutCategories=IgnoreForCI /p:PreExecutionTestScript=/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/set_stress_test_env.sh /p:TestWithLocalNativeLibraries=true
12:51:47 /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/.dotnet/sdk/2.1.401/MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/eng/common/../../artifacts/log/Release/Build.binlog /clp:Summary /nr:true /p:Configuration=Release /p:Projects=/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/eng/common/../../*.sln /p:RepoRoot=/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/eng/common/../.. /p:Restore=false /p:Build=false /p:Rebuild=false /p:Test=true /p:Pack=false /p:IntegrationTest=false /p:PerformanceTest=false /p:Sign=false /p:Publish=false /p:ContinuousIntegrationBuild=false /p:ConfigurationGroup=Release /p:SkipTests=true /p:OSGroup=Linux /p:ArchGroup=arm /p:WithoutCategories=IgnoreForCI /p:PreExecutionTestScript=/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/set_stress_test_env.sh /p:TestWithLocalNativeLibraries=true /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/tempHome/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18603.8/tools/Build.proj
```

The previous build looks identical:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_jitstressregs1/44/consoleFull
```
12:55:23 [/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/tests/scripts/run-corefx-tests.py]: ./build.sh -test -Release /p:OSGroup=Linux /p:ArchGroup=arm -SkipTests  /p:WithoutCategories=IgnoreForCI /p:PreExecutionTestScript=/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/set_stress_test_env.sh /p:TestWithLocalNativeLibraries=true
12:55:24 /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/.dotnet/sdk/2.1.401/MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/eng/common/../../artifacts/log/Release/Build.binlog /clp:Summary /nr:true /p:Configuration=Release /p:Projects=/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/eng/common/../../*.sln /p:RepoRoot=/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/eng/common/../.. /p:Restore=false /p:Build=false /p:Rebuild=false /p:Test=true /p:Pack=false /p:IntegrationTest=false /p:PerformanceTest=false /p:Sign=false /p:Publish=false /p:ContinuousIntegrationBuild=false /p:ConfigurationGroup=Release /p:SkipTests=true /p:OSGroup=Linux /p:ArchGroup=arm /p:WithoutCategories=IgnoreForCI /p:PreExecutionTestScript=/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/set_stress_test_env.sh /p:TestWithLocalNativeLibraries=true /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/tempHome/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.18578.2/tools/Build.proj
```

Has anything (obvious) changed on the corefx build side?

How *should* the test build be done, to get the proper RunTests.cmd/sh files generated?

fyi, the corefx build commands are constructed here: https://github.com/dotnet/coreclr/blob/master/tests/scripts/run-corefx-tests.py

**Comment by danmosemsft** [comment] 2018-12-13 02:43
@viktorhofer can you explain this msybe?

**Comment by ViktorHofer** [comment] 2018-12-13 17:36
Before I will take a closer look, who is producing the RunTest.cmd/sh scripts. CoreFx or CoreClr to know if we are talking about the arcade testing package or the buildtools one.

**Comment by BruceForstall** [comment] 2018-12-13 18:20
We're talking here about the corefx test build, and the RunTest.cmd/sh wrapper scripts generated by that build.

Comments above indicate that we have a lot of test failures because the xunit command that is in those generated scripts is not excluding the correct set of tests based on the platform or other configuration.

**Comment by ViktorHofer** [comment] 2018-12-13 18:38
Ok got it. Is there a way to inspect one of the generated RunTests.cmd/sh files? That would help a lot.

**Comment by ViktorHofer** [comment] 2018-12-13 18:45
Ok it seems the command is parsed wrong:

```
/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm/dotnet xunit.console.dll CoreFx.Private.TestUtilities.Tests.dll -xml testResults.xml -nologo -notrait category=nonnetcoreapptests -notrait category=nonlinuxtestsIgnoreForCI
```

Let me find out if that's something on our side.

**Comment by ViktorHofer** [comment] 2018-12-13 18:59
Found the reason. In the rewrote of testing infrastructure a bug slipped in which causes the `WithCategories` and `WithoutCategories` global properties not being handled correctly. Fix is out: https://github.com/dotnet/arcade/pull/1577/

**Comment by BruceForstall** [comment] 2018-12-13 19:15
Excellent! Can't wait for the fix!

Btw, once the fix is in arcade, how does it get to corefx?

**Comment by safern** [comment] 2018-12-13 19:45
> Btw, once the fix is in arcade, how does it get to corefx?

We need to update the CoreFx testing package (Darc automatic update) -- however we're planning on running it manually so that it is faster.

**Closed** 2018-12-13 20:04 UTC
Labels: arch-arm32, os-linux

**Comment by BruceForstall** [comment] 2018-12-13 20:20
@safern @ViktorHofer Can you please let me know when corefx master has this fix?

**Comment by ViktorHofer** [comment] 2018-12-13 20:48
Sure

**Comment by ViktorHofer** [comment] 2018-12-13 21:20
Should be in master in ~2h. Manual update PR is open: https://github.com/dotnet/corefx/pull/34082

**Comment by ViktorHofer** [comment] 2018-12-14 01:01
@BruceForstall the changes are now in master.

**Comment by BruceForstall** [comment] 2018-12-14 07:14
@ViktorHofer Thanks!
