### ISSUE TITLE
Unable to debug on Visual Studio 2017 Mac  (Sierra 10.12.4 Beta)

### ISSUE THREAD

**Issue by AAimson** [dotnet/coreclr#10279] opened 2017-03-18 12:00 UTC
When trying to debug a MVC Web project in VS 2017 Mac I get the error message: Unable to attach to CoreCLR. 

dotnet
>Microsoft .NET Core Shared Framework Host
>Version  : 1.1.0

dotnet --info
>.NET Command Line Tools (1.0.1)
>
>Product Information:
> Version:            1.0.1
> Commit SHA-1 hash:  005db40cd1
>
>Runtime Environment:
> OS Name:     Mac OS X
> OS Version:  10.12
> OS Platform: Darwin
 >RID:         osx.10.12-x64
 >Base Path:   /opt/dotnet/sdk/1.0.1

**Comment by suqram** [comment] 2017-03-20 21:32
Got the same issue (also on Sierrs 10.12.4 beta)

**Comment by mikem8361** [comment] 2017-03-21 17:31
This will be fixed in the next 1.0 and 1.1 service releases and has been fixed in the master branch.

**Comment by AntoineVht** [comment] 2017-03-28 11:50
When will it be available ? Thanks

**Comment by robbpriestley** [comment] 2017-03-28 17:03
Sierra 10.2.4 is now being pushed as an update by Apple. I installed the update this morning and now I can no longer debug in VS Code ("Unable to attach to CoreCLR."). I believe this is the same issue reported above. I installed the latest .NET Core SDK (`dotnet --version` now says `1.0.1`). Is the fix available elsewhere, or any advice please?

**Comment by mikem8361** [comment] 2017-03-28 17:39
Here is a work around that worked for Gregg Miskelly:
1.	Download https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.osx.10.10-x64.Microsoft.NETCore.Runtime.CoreCLR/1.1.2-servicing-25123-01
2.	Open the resulting file as a zip, and copy out runtimes/osx.10.10-x64/native/libdbgshim.dylib
3.	Open a terminal
4.	cd ~/.vscode/extensions/ms-vscode.csharp-1.8.0/.debugger
5.	cp <path-to-extracted-libdbgshim> .
As I said above, but just to repeat here, I expect to have a real fix out soon. But hopefully this will unblock folks in the mean time.

**Comment by robbpriestley** [comment] 2017-03-28 18:16
Confirmed workaround works. Thanks for the info. When the real fix is released, will I need to "reverse" the workaround, or will installing the new software get me back to consistency?

**Comment by armartinez** [comment] 2017-03-29 06:18
Is there a workaround for Visual Studio Mac ?

**Comment by mikem8361** [comment] 2017-03-29 17:26
@gregg-miskelly Is there a workaround for VS for Mac?

**Comment by MacFriis** [comment] 2017-03-29 18:24
Until a fix for the VS for Mac is up and running, I use VS for Mac, as editor, and compiler (for checking code) then I run my project locally using the command line "dotnet run", at least I can test my code, before uploading to server, debug... not so much

**Comment by gregg-miskelly** [comment] 2017-03-29 18:33
I don't have precise steps, but you can work around this by downloading https://vsdebugger.azureedge.net/coreclr-debug-1-9-0/coreclr-debug-osx.10.11-x64.zip, and replacing the version of vsdbg that VS for Mac is using with that version.

@DavidKarlas do you have better instructions?

**Comment by suqram** [comment] 2017-03-29 18:54
This fixed it for me, in Visual Studio for Mac:

1. Download https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.osx.10.10-x64.Microsoft.NETCore.Runtime.CoreCLR/1.1.2-servicing-25123-01
2. Open the resulting file as a zip, and copy out runtimes/osx.10.10-x64/native/libdbgshim.dylib
3. Navigate to /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/DotNetCore.Debugger/Adapter/ in Finder or Terminal
4. Rename libdbgshim.dylib to libdbgshim.dylib.old
5. Paste in the new libdbgshim.dylib

**Comment by MacFriis** [comment] 2017-03-29 19:05
@suqram  You just saved my day and night! Thx.

**Comment by EltonAlvess** [comment] 2017-03-29 20:51
@suqram it worked well!

Thanks

**Closed** 2017-03-29 21:12 UTC
Labels: area-Diagnostics

**Comment by swilliams-a3digital** [comment] 2017-03-29 22:36
fix it for me!

**Comment by rosascarlos** [comment] 2017-03-30 18:30
@suqram Excellent!
Work for me!
Thanks

**Comment by robvdveer** [comment] 2017-03-30 20:31
Excellent, copying the libdbgshim file as instructed by @suqram did the trick.

**Comment by jhallam3** [comment] 2017-03-31 09:34
@suqram Excellent!
Work for me!
Thanks

**Comment by kinliang** [comment] 2017-03-31 09:48
Works for me too!

thanks!

**Comment by githubBrandon** [comment] 2017-03-31 14:28
> Open the resulting file as a zip, and copy out runtimes/osx.10.10-x64/native/libdbgshim.dylib

@mikem8361 what does this mean?

**Comment by mikem8361** [comment] 2017-03-31 16:53
A nuget file is a zip file. Rename to .zip and run unzip on it.

**Comment by bryanross** [comment] 2017-04-01 13:31
@suqram Work for me as well - thank you.

**Comment by RexLKW** [comment] 2017-04-01 13:44
@suqram Thanks so much! It works!

**Comment by robbpriestley** [comment] 2017-04-01 15:13
Is this issue fixed in production now, or is it still in workaround? I noticed a new C# Extension and installed it yesterday. Does that contain the fix?

**Comment by LokeSonne** [comment] 2017-04-03 10:42
@robbpriestley Sure seems like it. This is in the changelog for the extension in vs code:
What's New in 1.8.1
Fixes debugging on macOS Sierra 10.12.4.

(and it's working)
Brilliant!

**Comment by joristt** [comment] 2017-04-03 11:05
I did precisely what @suqram suggested, but now I get a popup when I try to run my application:

> Debugger operation failed
> Unknown Error: 0x92330062

I don't get the "Unable to attach to CoreCLR" message in my Application Output window anymore, so that's fixed.

**Comment by gregg-miskelly** [comment] 2017-04-03 14:49
@joristt if you have the 1.8.1 extension installed and you are still running into an issue, your issue isn't related to this issue. Please open a new issue, this issue is long enough :).

**Comment by robvdveer** [comment] 2017-04-03 15:37
I was working on aspnet core when this issue started, and with VS preview it used to start a new Browser with a new debug session. Am i looking for the wrong setting now?

**Comment by joristt** [comment] 2017-04-03 15:50
@gregg-miskelly Yeah you're right, sorry :). You said
> replace the version of vsdbg that VS for Mac is using

and I interpreted that as: replace only the vsdbg Unix executable. Tried copying everything from that zip to the VS Adapter directory 1 minute after commenting here and that fixed the problem.

**Comment by gregg-miskelly** [comment] 2017-04-03 16:05
@robvdveer by 'VS Preview' you mean 'VS For Mac Preview' correct? If so - VS For Mac hasn't shipped an update vsdbg package containing the fix yet (at least to my knowledge), so you are very likely at the right place. There are two work arounds posted above, but I will give you the latest version of it --

* Download https://vsdebugger.azureedge.net/coreclr-debug-1-9-1/coreclr-debug-osx.10.11-x64.zip
* Navigate to /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/AddIns/DotNetCore.Debugger/Adapter/ in Finder or Terminal
* Extract the zip to this folder

**Comment by robvdveer** [comment] 2017-04-03 16:27
Thanks @gregg-miskelly for such a quick response!

**Comment by knilecrack** [comment] 2017-04-04 00:58
@gregg-miskelly  well played. Thanks

**Comment by akhilanair94** [comment] 2017-04-05 09:22
@gregg-miskelly saved the day!!!!

**Comment by mclarenengineering** [comment] 2017-11-23 15:49
@gregg-miskelly this will work on the visual studio preview the debug gives an execution error
