### ISSUE TITLE
Runtime does not always delete the debug pipe files created for each managed process

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/coreclr#2126] opened 2015-11-20 23:46 UTC
The pipe files must be deleted on runtime shutdown.

**Comment by mmitche** [comment] 2015-12-09 16:05
@Sridhar-MS What's the status of this?  This is causing significant problems in the lab.

**Comment by mikem8361** [comment] 2015-12-09 19:14
I'm going to start working on it today.

mikem

**Comment by mmitche** [comment] 2015-12-11 19:14
@mikem8361 What is the status of this? I am suspicious this is the cause of a lot of failures in the lab.

**Comment by mikem8361** [comment] 2015-12-11 19:27
I've been working on it. This has been broken for many months.  Why is it affecting the lab now? Is there anyway to clean out the /tmp directory before every job?

mikem

**Comment by mmitche** [comment] 2015-12-11 19:30
I'm not sure, but something changed very recently that caused a serious upswing in the number of files.  /tmp/ was being cleaned already every few hours.  Earlier this week suddenly it was taking hours and hours to clean the directory.

**Comment by Sridhar-MS** [comment] 2015-12-11 19:44
@mmitche I think that this issue is not the culprit but caused by https://github.com/aspnet/dnx/issues/1835. The CLI repo restores (with `no-cache`) a ton of nuget packages and it is polluting the tmp directory.

/cc: @anurse

**Comment by mmitche** [comment] 2015-12-11 19:45
@Sridhar-MS Most of the files are clr-debug-pipe

**Comment by Sridhar-MS** [comment] 2015-12-11 20:00
@mmitche I am looking at the debug-pipe files and they are always size 0. But then I am just building dotnet/cli repo.

**Comment by mikem8361** [comment] 2015-12-12 05:24
Fixed in PR #2318

**Closed** 2015-12-12 05:24 UTC
Labels: Diagnostics
