### ISSUE TITLE
[Linux/arm64] test b80373 fails

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#20029] opened 2018-09-18 17:44 UTC
Fails in many arm64 Ubuntu jobs. e.g.,

https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress1_flow_prtest/14/

```
JIT_Regression._VS_ia64_JIT_M00_b80373_b80373_b80373_._VS_ia64_JIT_M00_b80373_b80373_b80373_sh [FAIL]
18:29:30         
18:29:30 
        Assert failure(PID 20420 [0x00004fc4], Thread: 20420 [0x4fc4]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
18:29:30             File: /mnt/j/workspace/dotnet_coreclr/dev_unix_test_workflow/arm64_cross_checked_ubuntu16.04_prtest/src/vm/jithelpers.cpp Line: 5157
18:29:30             Image: /home/robox/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm64_cross_checked_ubuntu16.04_jitstress1_tst_prtest/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun
18:29:30         
18:29:30         /home/robox/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm64_cross_checked_ubuntu16.04_jitstress1_tst_prtest/bin/tests/Linux.arm64.Checked/JIT/Regression/VS-ia64-JIT/M00/b80373/b80373/b80373.sh: line 244: 20420 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
18:29:30         /n/nReturn code:      1/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm64_cross_checked_ubuntu16.04_jitstress1_tst_prtest/bin/tests/Linux.arm64.Checked/JIT/Regression/Reports/JIT.Regression/VS-ia64-JIT/M00/b80373/b80373/b80373.output.txt/nRaw output:/nBEGIN EXECUTION
18:29:30         /home/robox/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm64_cross_checked_ubuntu16.04_jitstress1_tst_prtest/bin/tests/Linux.arm64.Checked/Tests/Core_Root/corerun b80373.exe
18:29:30         Expected: 100
18:29:30         Actual: 134
18:29:30         END EXECUTION - FAILED
18:29:30         Test Harness Exitcode is : 1
18:29:30         /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm64_cross_checked_ubuntu16.04_jitstress1_tst_prtest/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm64_cross_checked_ubuntu16.04_jitstress1_tst_prtest/bin/tests/Linux.arm64.Checked/JIT/Regression/VS-ia64-JIT/M00/b80373/b80373/b80373.sh/n
18:29:30         Expected: True
18:29:30         Actual:   False
18:29:30         Stack Trace:
18:29:30           /mnt/j/workspace/dotnet_coreclr/dev_unix_test_workflow/arm64_cross_checked_ubuntu16.04_prtest/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs(85719,0): at JIT_Regression._VS_ia64_JIT_M00_b80373_b80373_b80373_._VS_ia64_JIT_M00_b80373_b80373_b80373_sh()
```

Related: https://github.com/dotnet/coreclr/issues/20024

Test is disabled in issues.targets.

**Comment by shimingsg** [comment] 2018-10-25 02:20
similar failing in https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstress2_jitstressregs3_tst/45/

the log:
TEST_CMD_LINE: JIT\Regression\VS-ia64-JIT\M00\b80373\b80373> C:\Users\robox\j\workspace\arm64_cross_c---0d2bec9b\bin\tests\Windows_NT.arm64.Checked\JIT\Regression\VS-ia64-JIT\M00\b80373\b80373\b80373.cmd 


BEGIN EXECUTION
 "C:\Users\robox\j\workspace\arm64_cross_c---0d2bec9b\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\corerun.exe" b80373.exe 

Assert failure(PID 6868 [0x00001ad4], Thread: 10048 [0x2740]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! GetCLRRuntimeHost + 0x222D88 (0x00007ff9`d4c96178)
CORECLR! GetCLRRuntimeHost + 0x2084BC (0x00007ff9`d4c7b8ac)
!  + 0x0 (0x00007ff9`75ab92d0)
    File: d:\j\workspace\arm64_cross_c---0aaef436\src\vm\jithelpers.cpp Line: 5178
    Image: C:\Users\robox\j\workspace\arm64_cross_c---0d2bec9b\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED

**Comment by AndyAyersMS** [comment] 2019-01-25 03:17
I'll take a look.

**Comment by AndyAyersMS** [comment] 2019-01-25 06:47
Test was modified by #20321 to fix a test issue on 64 bit hosts and was removed from exclusion

Can't repro the failure, seems to be passing in recent CI runs too. So closing as fixed.

**Closed by AndyAyersMS** 2019-01-25 06:47 UTC
Labels: JitStress, arch-arm64, area-CodeGen, os-linux
