### ISSUE TITLE
About 30% performance regression in SpinLock 

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/coreclr#17345] opened 2018-03-30 16:01 UTC
Here are the graphs showing timings from Aug to now for these two tests. 

<img width="1155" alt="screen shot 2018-03-30 at 9 08 29 am" src="https://user-images.githubusercontent.com/5897654/38144632-6ff9deb8-33fa-11e8-8b1f-d9634e453b46.png">

<img width="1155" alt="screen shot 2018-03-30 at 9 08 04 am" src="https://user-images.githubusercontent.com/5897654/38144636-752eccfe-33fa-11e8-97af-7fcfc4d8c930.png">

There was a noticeable jump in September in these tests that does not seem to have been corrected since.

The code changes are in CoreCLR. Here's the coreclr commit 4a7ee67a60fb2c40d755dfd4f7e2824954650193 and here's a [github diff](https://github.com/dotnet/coreclr/commit/4a7ee67a60fb2c40d755dfd4f7e2824954650193) 

Refer to [benchview](https://benchview/trendline?build_selector=latest&count=2000&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[957]&archids=[23]&mpids=[1292]&cfgids=[2785,2706]&testids=[63826,63827,63828]&jobid=94550&) for more details.

cc: @kouvel @danmosemsft

**Comment by AndyAyersMS** [comment] 2018-03-30 16:19
Note depending on the test this may be expected, either from deliberate changes and/or the impact of the test harness setting up an affinity mask that leads to increased spinning (see eg #16615 / #16801 / #16807).

**Comment by RussKeldorph** [comment] 2018-03-30 16:33
I believe @kouvel was the intended mention.

**Comment by kouvel** [comment] 2018-03-30 18:19
There were changes to the spinning path in 03bf95c8db9003a5925ca9383dca722a4c651e27 but it looks like these tests don't go through those paths (they only test the fast path of entering an unlocked SpinLock and exiting). The timing roughly corresponds with the change above though, I'll take a closer look.

**Comment by kouvel** [comment] 2018-04-01 18:30
I have confirmed that 03bf95c8db9003a5925ca9383dca722a4c651e27 did not cause the issue. I thought that the 10-ms YieldProcessor() measurement might be affecting it, but it looks like not, by the time these two tests run it has long passed the 10 ms of startup.

These below are coreclr changes that went into the first build that regressed. Does anything else look suspect?

```
4a7ee67a60fb2c40d755dfd4f7e2824954650193 Thu Sep 7 15:56:30 2017 GitHub - Make dumpmd work with tiered jitting. Now displays previous code addresses (#13805)
e390d7202605f3e5c9eb123f37c67ec5685c3fee Thu Sep 7 15:39:06 2017 GitHub - Retry linux arm legs on a new agent (#13839)
b7cce5a59f7c6bd5a33b88f2af252693bbbd7373 Thu Sep 7 14:28:07 2017 GitHub - New jit intrinsic support (#13815)
eb2e9f90ba3679fa8386c4130f81c8061e8d4ca4 Thu Sep 7 11:36:37 2017 Jan Kotas - Spelling and grammar corrections - A through L (#13683)
2fbf7f1e80a3dcb4ac5c2c0518158f38f483663c Thu Sep 7 11:19:20 2017 Jan Kotas - Update CoreClr, CoreFx to preview2-25707-02, preview2-25707-02, respectively (#13808)
11a10f8fc00f61f6c8fcaa8a13e0f4f271818178 Thu Sep 7 11:14:29 2017 Jan Kotas - Fix for #13830 issue (#13831)
0644d5bd599b4562b1509429b8ae0ec62f4d7766 Thu Sep 7 08:55:21 2017 GitHub - Fix incorrect treatment of pointer as fixed (#13816)
bb449c7489a7fb466dda7c7b6bce5122ded913ea Wed Sep 6 18:14:19 2017 GitHub - Segregate merged returns by constant value (#13792)
9f38303221294f45740feefc1b6ddf72347ff882 Wed Sep 6 16:12:25 2017 GitHub - Vendor the volatile.h header into src/gc/env for the standalone GC build (#13656)
a6a61438b3451151b79c6d0a1188218d4fe121bb Wed Sep 6 15:51:22 2017 Pat Gavlin - Fix VSO 487701 and 487702.
b426e68b8f0a894216dc1e24526c4f11210c9249 Wed Sep 6 15:49:27 2017 Pat Gavlin - Add tests for VSO 487701 and 487702.
26648051369757beb170f4ce9a77a70b06b26a0f Wed Sep 6 14:34:48 2017 Pat Gavlin - Add a regression test.
6be064c11e0714e92d821025f3b630161f740577 Wed Sep 6 12:51:14 2017 Pat Gavlin - Do not remove NOPs used by calls.
03ef5b4cf46ba6b276706bf65fd76caf636f72cb Wed Sep 6 12:38:58 2017 GitHub - Fix DevDiv_278523 test for r2r x86. (#13709)
32ce0bc7012f7ebac0532aa66cfd89c6f60bb0ea Wed Sep 6 11:23:53 2017 Jan Kotas - Restore Array.Empty
27611bc9db08741afe0043f98ffa1bb440c0fd23 Wed Sep 6 11:00:18 2017 GitHub - Jit doesn't reload shift index if it was spilled to rcx. (#13757)
8fa850cd22d390f2f4b702a093ec46ebbc4c114b Wed Sep 6 09:26:22 2017 jashook - Fix potentially uninitialized local variable 'regCount'
5fd50d8d7ab96dbb3868ab3e60d0e4fc10f44ca0 Wed Sep 6 08:48:01 2017 GitHub - Add Memory-based Stream overloads to coreclr (#13769)
b33f729d71f7a222c304f0fe817bb19032a34522 Wed Sep 6 07:14:19 2017 Jan Kotas - Removed renamed method. (#13803)
1f9aeeb7a3685bc7fd1098fc50d91ac81bae4873 Wed Sep 6 05:19:48 2017 Atsushi Kanamori - Support for not wrapping exceptions with TargetInvocationException. (#13767)
8c64be6cf63b278c918c2280a82ee773e1e15647 Tue Sep 5 21:53:24 2017 Jan Kotas - Update CoreClr, CoreFx to preview2-25706-01, preview2-25706-01, respectively (#13734)
2e27217069d349775136e2f32591013447a7e1fb Tue Sep 5 20:16:30 2017 adiaaida - Add nopgo option for throughput runs
25b6eef888e07f7dd0b0fea873554e786a952bf7 Tue Sep 5 18:37:55 2017 Jan Kotas - Fix for CoreRT issue https://github.com/dotnet/corert/issues/3672 (ar… (#13777)
7e52c5341ca170c84632e1ef32c685d280f9824b Tue Sep 5 18:06:50 2017 Sung Yoon Whang - implementing profiler ELT callbacks for AMD64 Linux (#12603)
e59fab0c899343fc5d382583bd07f4595659ac54 Tue Sep 5 17:38:54 2017 GitHub - Moving the Windows Performance runs from Server 2012 to Server 2016. (#13725)
a8f83b615708c529b112898e7d2fbc3f618b26ee Tue Sep 5 16:22:55 2017 Jan Vorlicek - Add support for building under glibc 2.26 (#13785)
449a1ad94c530492656afc2308fda6708e45aceb Tue Sep 5 15:27:24 2017 jashook - Disable tests based on 13796
e75f090a379da4d1f6016b2c73922387cc84e420 Tue Sep 5 14:52:23 2017 GitHub - Fix SemaphoreSlim throughput (#13766)
472a0e568d3dffa2ce4db4b999ba47005081aadd Tue Sep 5 11:42:15 2017 jashoo - revert_13687
2abbf00b943aa57c8a04b9edc521bd8884ded852 Tue Sep 5 11:34:56 2017 Jan Kotas - Add Intel hardware intrinsic API (#13576)
5d67a732d55546217f4c454f6d4c1b818c808db8 Tue Sep 5 09:36:53 2017 GitHub - Fix access order for double pointer (#13759)
47bb5bcbb4f5b96e829523b59d9a66cc730fce14 Tue Sep 5 07:23:55 2017 GitHub - JIT: allow inlines of methods with calli (#13756)
f05b7526970249489d00d6b1538e53f6309f5f0d Mon Sep 4 22:26:33 2017 Jan Kotas - Print zapper stats on verbose mode (#13774)
801a82174519795f0e54f2f6aaacd3e331f78801 Mon Sep 4 16:33:13 2017 Jan Kotas - Fix uninitialized fields of ZapperStats (#13773)
36180faa982e1a8c32f6df990cd6c5617a36aaf2 Sat Sep 2 03:01:37 2017 shimingsg - update correct file path if the working folder is not test case folder
bac965ea8d3977a08257ee6758e14ccda34547e3 Fri Sep 1 16:19:07 2017 GitHub - Change identifier for EventProviders from GUID to string name (#13370)
15b62467035e97f8b1d9cb070f6ff689e34f91bc Fri Sep 1 15:21:47 2017 GitHub - need casting for size calculation (#13754)
b1ebfd0ed5c154a847bd02503e606a3464fdea68 Fri Sep 1 13:59:23 2017 Bruce Forstall - Add an assert to getRegisterRecord() that regNum is legal
03bf95c8db9003a5925ca9383dca722a4c651e27 Fri Sep 1 13:09:40 2017 GitHub - Add normalized equivalent of YieldProcessor, retune some spin loops (#13670)
12db0a3ccf42ab21333872cc3984009aecd06eeb Fri Sep 1 11:20:39 2017 GitHub - JIT: fix some instruction size estimates (#13432)
707de9c8d9ebae02828535ed789bfce31bb29da8 Fri Sep 1 10:57:33 2017 GitHub - Clear the init-locals bit for CoreLib to workaround #1279 (#13728)
3d111d9e5f7804039764303509c78722a7c7e818 Fri Sep 1 10:04:47 2017 GitHub - Update Type.GetMethods() to be generics friendly (#13745)
8fae16552cc5efbb0b14804a097c4a0676967810 Fri Sep 1 10:03:50 2017 GitHub - Share four exception types (#13492)
eec68ee1326e4795e463db0da391b67b91c2f3a6 Fri Sep 1 09:42:02 2017 jashook - Lst File updates.
a741f5f1f4eae22fa2ee42541a9b6851e01cee73 Fri Sep 1 08:42:26 2017 Jan Kotas - [ARM64/Windows] Add JIT_Stelem_Ref helper (#13687)
566aed2348f3c65de148d36b445c1aa06f3684ac Fri Sep 1 08:41:01 2017 Jan Kotas - Initialize m_failedILStubs of ZapperStats (#13742)
d8f56562dffa57b203dae38e33f17a969f06da33 Fri Sep 1 07:12:30 2017 Jan Kotas - Avoid StringBuilder allocation in ResourceManager (#13732)
4d57d4014a17e63ef6607cd6cc47d6ba37d58398 Fri Sep 1 06:29:22 2017 Atsushi Kanamori - Merge pull request dotnet/corert#4370 from dotnet/nmirror
8b3639715d42c0f629fc57c206cd8f74686cab71 Fri Sep 1 03:51:12 2017 Alexander Soldatov - [RyuJIT/ARM32] Add regression tests
b6ffa91f6dacc6b20abafc48d53e07079076e779 Wed Aug 30 23:03:06 2017 Shiming Ge - add test dependency files
819cec771bab28584d89d7dc83ba806a10e8108b Tue Aug 29 13:42:46 2017 Mike Danes - Fix getCastDescription to use the actual source type
2de13cfabfe6ad43cd8e00f6a0884e546c7516f1 Fri Aug 25 11:51:39 2017 Steve MacLean, Qualcomm Datacenter Technologies Inc - [Arm64/Windows] Disable JIT_WriteBarrier optimization
7091c756f8da0e547290a2f5d43e3c4009e59010 Fri Aug 25 11:10:47 2017 Steve MacLean, Qualcomm Datacenter Technologies Inc - [Arm64] Optimize JIT_WriteBarriers
```

Aside from that, these microbenchmarks are not very good. The tests (including outer iterations and inner iterations) run in the order of 1-10 us. That is far too small for a microbenchmark and in local runs I'm seeing ~30% error in samples (though the mean/median would have less error, it's still very high). I'm not sure why xunit perf is designed to run a fixed number of iterations (measuring time) rather than for a fixed amount of time (measuring iterations per unit of time). The latter scales better across processors and platforms. The former is easier to profile, but that is not the main purpose of these tests. When profiling is necessary, it should be trivial to change the test to run a fixed number of iterations for that rare purpose.

In any case, I believe I will change all of the threading perf tests to figure out an appropriate number of iterations dynamically by measuring it (effectively changing the tests to run for a fixed amount of time).

**Comment by kouvel** [comment] 2018-04-01 18:37
Also of course, I'm not sure if xunit-perf does any warmup (essential for microbenchmarks) but from the test authoring I don't see any warmup. I don't see how xunit-perf could do warmup on its own, as what is required for warmup would not always be known by the harness (xunit-perf). These tests need a warmup.

**Comment by kouvel** [comment] 2018-04-01 19:08
Moving to future. Unless someone sees a different source of the problem, it's reasonable to classify this as not-very-important.

**Comment by kouvel** [comment] 2018-04-01 19:16
Moved to area-Meta, please reactivate and change the area label if you can show that there is a change that caused the regression and there is reason for concern. Until then, it's not even worth spending any more time on this.

**Closed by kouvel** 2018-04-01 19:16 UTC
Labels: area-Meta, tenet-performance

**Comment by danmosemsft** [comment] 2018-04-01 20:24
@adamsitnik and @brianrob for comments on observations above.

If these tests are not useful, we should fix them. What do you recommend?

**Comment by AndyAyersMS** [comment] 2018-04-01 21:09
@kouvel would strongly encourage you to collaborate with the perf harness folks to make any necessary improvements.

The guidance is for test authors to increase the inner iteration count until each iteration takes some reasonable amount of time. Would suggest at least a few milliseconds if not more (currently 0.007 ms, so maybe increase the inner iteration count by 1000x).

Xunit-perf will increase/limit the number of outer iterations until total time takes 10 seconds or in the CI triggered tests, the count reaches 21 iterations. The benchmark site shows the an aggregate value deduced from those iterations. You can see the raw data in the CI, eg [here](https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_windows_nt_release/5126/artifact/bin/tests/System.Threading.Performance.Tests/netcoreapp-Windows_NT-Release-x64/Perf-System.Threading.Performance.Tests.xml).
```
<test name="System.Threading.Tests.Perf_SpinLock.TryEnterExit" type="System.Threading.Tests.Perf_SpinLock" method="TryEnterExit">
<performance>
<metrics>
<Duration displayName="Duration" unit="msec"/>
</metrics>
<metrics>...</metrics>
<iterations>
<iteration index="0" Duration="0.00798288924710278"/>
<iteration index="1" Duration="0.00741268287231378"/>
<iteration index="2" Duration="0.00741268287231378"/>
<iteration index="3" Duration="0.0076977860597367"/>
<iteration index="4" Duration="0.00741268287231378"/>
<iteration index="5" Duration="0.00741268287231378"/>
<iteration index="6" Duration="0.00741268287231378"/>
<iteration index="7" Duration="0.00741268287231378"/>
<iteration index="8" Duration="0.00769778605967986"/>
<iteration index="9" Duration="0.00741268287231378"/>
<iteration index="10" Duration="0.00741268287231378"/>
<iteration index="11" Duration="0.00741268287231378"/>
<iteration index="12" Duration="0.00741268287231378"/>
<iteration index="13" Duration="0.00741268287231378"/>
<iteration index="14" Duration="0.00741268287231378"/>
<iteration index="15" Duration="0.00769778605967986"/>
<iteration index="16" Duration="0.0076977860597367"/>
<iteration index="17" Duration="0.00741268287231378"/>
<iteration index="18" Duration="0.00741268287231378"/>
<iteration index="19" Duration="0.00741268287225694"/>
<iteration index="20" Duration="0.00741268287231378"/>
<iteration index="21" Duration="0.00741268287231378"/>
</iterations>
```
The fact that the measured iteration counts seem to map to particular discrete values is another indication that the inner iteration count is way too short.

Xunit-perf does indeed do warmups; the first iteration's data is discarded from aggregation.

There was a windows OS update on the benchmark machines during that time range, so that might be a factor. But the linux perf jumped in a similar fashion at the same time, so that would indicate perhaps it is a code path change.

**Comment by kouvel** [comment] 2018-04-01 22:41
Sorry I misspoke when I said the tests take 1-10 us including outer and inner iterations. They take 1-10 us per outer iteration. Increasing the inner iteration count will work fine and it would be the easiest change to make, but if I was to create perf benchmarks I would not use this.

Regarding the regression, yes I'm sure there is a reason for it. I'm not sure however whether the reason (whatever it is) is meaningful given what is measured.

**Comment by kouvel** [comment] 2018-04-02 10:58
I tried using Microsoft.NetCore.App packages close to the base/changed versions and different coreclr package versions around that time and I'm seeing the opposite, where the base is running in ~20 us for both tests and the changed side is running in ~10 us. I tried syncing corefx back to the commits but it failed to build. I'm not able to repro the issue.

**Comment by kouvel** [comment] 2018-04-03 19:47
@AndyAyersMS:
> @kouvel would strongly encourage you to collaborate with the perf harness folks to make any necessary improvements.

Opened issue https://github.com/Microsoft/xunit-performance/issues/266 with some of my suggestions

**Comment by danmosemsft** [comment] 2018-04-03 20:09
I thought that our long term plan was to move to Benchmark.NET - @adamsitnik do you know how concrete those plans are?

**Comment by kouvel** [comment] 2018-04-04 18:42
> Speaking of @kouvel requirements BDN meets 100% of the requirements as of today without any extra work.

Thanks @adamsitnik, does that include the suggestions I posted in https://github.com/Microsoft/xunit-performance/issues/266 as well? I'll have to read up on BDN, sounds interesting.

**Comment by adamsitnik** [comment] 2018-04-05 14:31
@kouvel yes, it does. I have just replied in in Microsoft/xunit-performance#266

btw I am soon going to give a Modern BCL talk about BenchmarkDotNet and I will try to show all it;s features

**Comment by kouvel** [comment] 2018-04-05 17:35
Sounds very interesting, looking forward to the talk.
