### ISSUE TITLE
AssemblyName ctor throws FileLoadException in UWP debug mode

### ISSUE THREAD

**Issue by ridomin** [dotnet/coreclr#7046] opened 2016-09-03 00:04 UTC
Using 5.2.2 UWP DotNetCore 

File new project add 2 lines to App ctor
                string qualifiedName = this.GetType().AssemblyQualifiedName;  
                AssemblyName an = new AssemblyName(qualifiedName);

Run the app in debug and got 

System.IO.FileLoadException was unhandled by user code
  HResult=-2146234297
  Message=The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
  Source=mscorlib
  StackTrace:
       at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean forIntrospection, Boolean raiseResolveEvent)
       at System.Reflection.AssemblyName..ctor(String assemblyName)
       at MyUWPApp.ViewModels.AboutThisAppViewModel.GetAssemblyVersions()
       at MyUWPApp.ViewModels.AboutThisAppViewModel..ctor()
       at MyUWPApp.Pages.AboutPage..ctor()
       at MyUWPApp.Pages.ShellPage.InitializeNavigationItems()
       at MyUWPApp.Pages.ShellPage.OnNavigatedTo(NavigationEventArgs e)
  InnerException: 

note, this works in release with dotnetNative

**Comment by gkhanna79** [comment] 2017-01-04 23:56
@rahku PTAL

**Comment by danmosemsft** [comment] 2017-06-28 20:14
@safern can you please paste these 2 lines into a test and check they work now on CoreCLR UWP? If so you can close.

**Comment by safern** [comment] 2017-06-28 20:15
Sure, assigning to me.

**Comment by kouvel** [comment] 2017-06-28 20:25
I was just looking at this, it still seems to be failing

**Comment by safern** [comment] 2017-06-29 00:28
Thanks @kouvel then I will reassign it to you.

**Comment by kouvel** [comment] 2017-06-29 03:27
I believe the issue is that what is being passed is the assembly-qualified type name, not a qualified assembly name. You can get the latter with typeof(...).Assembly.FullName. It shouldn't work in .NET Native either, filed an issue in CoreRT.

**Closed** 2017-06-29 03:28 UTC
Labels: area-Assembly Loader, bug
