### ISSUE TITLE
Question：Are there any experimental projects about reference counting instead of GC?

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#24130] opened 2019-04-20 00:29 UTC
There's Snowflake project about manual memory management, but are there any experimental projects about reference counting instead of GC?

**Comment by jkotas** [comment] 2019-04-21 03:41
There are none that I am aware of. 

Duplicate of https://github.com/dotnet/coreclr/issues/430

**Closed by jkotas** 2019-04-21 03:41 UTC
Labels: area-GC, question
