### ISSUE TITLE
Sse2.Shuffle throws SEHException

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#21855] opened 2019-01-07 20:46 UTC
The following code crashes with SEHException at the last line:
```csharp
Vector128<byte> src = Vector128.Create((byte)1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16);
Vector128<uint> srcAsUInt32 = src.AsUInt32();
Vector128<uint> result = Sse2.Shuffle(srcAsUInt32, _MM_SHUFFLE(0, 1, 2, 3));
```
Am I doing something wrong? 
C-equivalent works fine:
```c
const __m128i src = _mm_set_epi8(
	//1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
	16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1
);
__m128i result =  _mm_shuffle_epi32(src, _MM_SHUFFLE(0, 1, 2, 3));
```

Windows 10, Core i7 8700K, .NET Core master

**Comment by tannergooding** [comment] 2019-01-07 21:10
What is the codegen?

**Comment by tannergooding** [comment] 2019-01-07 21:18
Also, what build-type (debug, checked release for coreclr and debug vs release for you failing code) did you test under?

**Comment by tannergooding** [comment] 2019-01-07 21:36
it shouldn't crash with non-constant values; that means something is broken in the jump table fallback

**Comment by tannergooding** [comment] 2019-01-07 21:45
Reopening, something is wrong with the codegen here. It is generating `C5F972001B` when it should be generating `C5F970001B`

**Comment by tannergooding** [comment] 2019-01-07 21:46
This looks to be specific to the `SSE2` code and wasn't caught because the `SSE2` intrinsics aren't on the templated test framework yet (so they aren't validating the fallback scenario).

**Comment by tannergooding** [comment] 2019-01-07 21:47
CC. @CarolEidt, @fiigii

**Comment by fiigii** [comment] 2019-01-07 21:52
Seems a codegen issue similar to https://github.com/dotnet/coreclr/issues/18553. I will take a look.

**Comment by EgorBo** [comment] 2019-01-07 21:54
1) 0x1B constant, works fine:
```csharp
static void Main(string[] args)
{
    Vector128<byte> src = Vector128.Create((byte) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16);
    Vector128<uint> srcAsInt32 = src.AsUInt32();
    Vector128<uint> result = Sse2.Shuffle(srcAsInt32, 0x1B);

    Console.WriteLine(result.ToString());
}
```
Output (`COMPlus_JitDisasm=Main`):
```asm
; Assembly listing for method Program:Main(ref)
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;* V00 arg0         [V00    ] (  0,  0   )     ref  ->  zero-ref    class-hnd
;* V01 loc0         [V01    ] (  0,  0   )  simd16  ->  zero-ref    ld-addr-op
;* V02 loc1         [V02    ] (  0,  0   )  simd16  ->  zero-ref   
;  V03 loc2         [V03    ] (  2,  2   )  simd16  ->  [rsp+0x20]   do-not-enreg[XS] must-init addr-exposed ld-addr-op
;  V04 OutArgs      [V04    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;  V05 tmp1         [V05,T01] (  2,  2   )  simd16  ->  mm0         "Inline return value spill temp"
;  V06 tmp2         [V06,T00] ( 30, 30   )  simd16  ->  mm0         "Inline stloc first use temp"
;
; Lcl frame size = 56

G_M33758_IG01:
       4883EC38             sub      rsp, 56
       33C0                 xor      rax, rax
       4889442420           mov      qword ptr [rsp+20H], rax
       4889442428           mov      qword ptr [rsp+28H], rax

G_M33758_IG02:
       B901000000           mov      ecx, 1
       C5F96EC1             vmovd    xmm0, ecx
       B902000000           mov      ecx, 2
       C4E37920C101         vpinsrb  xmm0, xmm0, xrcx, 1
       B903000000           mov      ecx, 3
       C4E37920C102         vpinsrb  xmm0, xmm0, xrcx, 2
       B904000000           mov      ecx, 4
       C4E37920C103         vpinsrb  xmm0, xmm0, xrcx, 3
       B905000000           mov      ecx, 5
       C4E37920C104         vpinsrb  xmm0, xmm0, xrcx, 4
       B906000000           mov      ecx, 6
       C4E37920C105         vpinsrb  xmm0, xmm0, xrcx, 5
       B907000000           mov      ecx, 7
       C4E37920C106         vpinsrb  xmm0, xmm0, xrcx, 6
       B908000000           mov      ecx, 8
       C4E37920C107         vpinsrb  xmm0, xmm0, xrcx, 7
       B909000000           mov      ecx, 9
       C4E37920C108         vpinsrb  xmm0, xmm0, xrcx, 8
       B90A000000           mov      ecx, 10
       C4E37920C109         vpinsrb  xmm0, xmm0, xrcx, 9
       B90B000000           mov      ecx, 11
       C4E37920C10A         vpinsrb  xmm0, xmm0, xrcx, 10
       B90C000000           mov      ecx, 12
       C4E37920C10B         vpinsrb  xmm0, xmm0, xrcx, 11
       B90D000000           mov      ecx, 13
       C4E37920C10C         vpinsrb  xmm0, xmm0, xrcx, 12
       B90E000000           mov      ecx, 14
       C4E37920C10D         vpinsrb  xmm0, xmm0, xrcx, 13
       B90F000000           mov      ecx, 15
       C4E37920C10E         vpinsrb  xmm0, xmm0, xrcx, 14
       B910000000           mov      ecx, 16
       C4E37920C10F         vpinsrb  xmm0, xmm0, xrcx, 15
       C5F970C01B           vpshufd  xmm0, xmm0, 27
       C5F929442420         vmovapd  xmmword ptr [rsp+20H], xmm0
       488D4C2420           lea      rcx, bword ptr [rsp+20H]
       E89DE4FFFF           call     Vector128`1:ToString():ref:this
       488BC8               mov      rcx, rax
       E8CDF3FFFF           call     Console:WriteLine(ref)
       90                   nop      

G_M33758_IG03:
       4883C438             add      rsp, 56
       C3                   ret      

; Total bytes of code 225, prolog size 16 for method Program:Main(ref)
; ============================================================
<269422093, 202050057, 134678021, 67305985>
```

Doesn't work:
```csharp
static byte _MM_SHUFFLE(byte fp3, byte fp2, byte fp1, byte fp0) => (byte)(((fp3) << 6) | ((fp2) << 4) | ((fp1) << 2) | ((fp0)));

static void Main(string[] args)
{
    Vector128<byte> src = Vector128.Create((byte) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16);
    Vector128<uint> srcAsInt32 = src.AsUInt32();
    Vector128<uint> result = Sse2.Shuffle(srcAsInt32, _MM_SHUFFLE(0, 1, 2, 3));

    Console.WriteLine(result.ToString());
}
```
Output:
```asm
; Assembly listing for method Program:Main(ref)
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;* V00 arg0         [V00    ] (  0,  0   )     ref  ->  zero-ref    class-hnd
;* V01 loc0         [V01    ] (  0,  0   )  simd16  ->  zero-ref    ld-addr-op
;  V02 loc1         [V02,T03] (  2,  2   )  simd16  ->  mm0        
;  V03 loc2         [V03    ] (  2,  2   )  simd16  ->  [rsp+0x30]   do-not-enreg[XS] must-init addr-exposed ld-addr-op
;  V04 OutArgs      [V04    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;  V05 tmp1         [V05,T04] (  2,  2   )  simd16  ->  mm0         "Inline return value spill temp"
;  V06 tmp2         [V06,T00] ( 30, 30   )  simd16  ->  mm0         "Inline stloc first use temp"
;  V07 tmp3         [V07,T01] (  2,  4   )  simd16  ->  mm0         "Inlining Arg"
;* V08 tmp4         [V08    ] (  0,  0   )   ubyte  ->  zero-ref    "Inlining Arg"
;  V09 tmp5         [V09    ] (  2,  4   )  simd16  ->  [rsp+0x20]   do-not-enreg[XSB] addr-exposed "by-value struct argument"
;  V10 tmp6         [V10,T02] (  2,  4   )    long  ->  rcx         "argument with side effect"
;
; Lcl frame size = 72

G_M33760_IG01:
       4883EC48             sub      rsp, 72
       33C0                 xor      rax, rax
       4889442430           mov      qword ptr [rsp+30H], rax
       4889442438           mov      qword ptr [rsp+38H], rax

G_M33760_IG02:
       B901000000           mov      ecx, 1
       C5F96EC1             vmovd    xmm0, ecx
       B902000000           mov      ecx, 2
       C4E37920C101         vpinsrb  xmm0, xmm0, xrcx, 1
       B903000000           mov      ecx, 3
       C4E37920C102         vpinsrb  xmm0, xmm0, xrcx, 2
       B904000000           mov      ecx, 4
       C4E37920C103         vpinsrb  xmm0, xmm0, xrcx, 3
       B905000000           mov      ecx, 5
       C4E37920C104         vpinsrb  xmm0, xmm0, xrcx, 4
       B906000000           mov      ecx, 6
       C4E37920C105         vpinsrb  xmm0, xmm0, xrcx, 5
       B907000000           mov      ecx, 7
       C4E37920C106         vpinsrb  xmm0, xmm0, xrcx, 6
       B908000000           mov      ecx, 8
       C4E37920C107         vpinsrb  xmm0, xmm0, xrcx, 7
       B909000000           mov      ecx, 9
       C4E37920C108         vpinsrb  xmm0, xmm0, xrcx, 8
       B90A000000           mov      ecx, 10
       C4E37920C109         vpinsrb  xmm0, xmm0, xrcx, 9
       B90B000000           mov      ecx, 11
       C4E37920C10A         vpinsrb  xmm0, xmm0, xrcx, 10
       B90C000000           mov      ecx, 12
       C4E37920C10B         vpinsrb  xmm0, xmm0, xrcx, 11
       B90D000000           mov      ecx, 13
       C4E37920C10C         vpinsrb  xmm0, xmm0, xrcx, 12
       B90E000000           mov      ecx, 14
       C4E37920C10D         vpinsrb  xmm0, xmm0, xrcx, 13
       B90F000000           mov      ecx, 15
       C4E37920C10E         vpinsrb  xmm0, xmm0, xrcx, 14
       B910000000           mov      ecx, 16
       C4E37920C10F         vpinsrb  xmm0, xmm0, xrcx, 15
       488D4C2430           lea      rcx, bword ptr [rsp+30H]
       C5F929442420         vmovapd  xmmword ptr [rsp+20H], xmm0
       488D542420           lea      rdx, bword ptr [rsp+20H]
       41B81B000000         mov      r8d, 27
       E85FEAFFFF           call     Sse2:Shuffle(struct,ubyte):struct
       488D4C2430           lea      rcx, bword ptr [rsp+30H]
       E88DE4FFFF           call     Vector128`1:ToString():ref:this
       488BC8               mov      rcx, rax
       E8BDF3FFFF           call     Console:WriteLine(ref)
       90                   nop      

G_M33760_IG03:
       4883C448             add      rsp, 72
       C3                   ret      

; Total bytes of code 241, prolog size 16 for method Program:Main(ref)
; ============================================================
```

Diff: https://www.diffchecker.com/qP17T9BF

**Comment by tannergooding** [comment] 2019-01-07 21:54
This is probably one of the places doing `code |= 2` that isn't correctly handling the SIMD instructions

**Comment by fiigii** [comment] 2019-01-07 21:58
> Does it mean we can't have _MM_SHUFFLE method? :(

@EgorBo A `_MM_SHUFFLE` method will make the intrinsic being jamp-table fallback. I am trying to address this drawback via https://github.com/dotnet/coreclr/issues/17108. However, this work is blocked by some extra vector copies. Will let you know when I get progress.

**Comment by fiigii** [comment] 2019-01-07 22:02
@tannergooding Agree, could you assign this issue to me if you are not already working on it? I believe there are some other similar issues about containment codegen.

**Comment by tannergooding** [comment] 2019-01-07 22:03
@fiigii, if you are going to fix this as part of #18553, it does indeed look like its the places where the emitter is doing `code |= 2`:
* `emitOutputAM`: https://github.com/dotnet/coreclr/blob/master/src/jit/emitxarch.cpp#L9309
* `emitOutputSV`: https://github.com/dotnet/coreclr/blob/master/src/jit/emitxarch.cpp#L10127
* `emitOutputCV`: https://github.com/dotnet/coreclr/blob/master/src/jit/emitxarch.cpp#L10568
* `emitOutputRR`: https://github.com/dotnet/coreclr/blob/master/src/jit/emitxarch.cpp#L11278

The `emitOutputRR` case covers this by having a completely separate code-path for the `Sse/Avx` instructions, so it never hits the condition. The `emitOutputSV` case already has some additional checks to catch some of these cases, but the other paths don't. We should probably update the other paths to not modify the opcode for `Sse/Avx` instructions as well (since I don't think it is ever needed).

**Comment by fiigii** [comment] 2019-01-07 22:09
Thanks! Will look into it.

**Comment by fiigii** [comment] 2019-01-15 21:40
The problem is actually larger than what I expected. 
https://github.com/dotnet/coreclr/blob/3f0903598d0e269e6aaf8e237b47269abe4ab7e8/src/jit/emitxarch.cpp#L10554-L10568

Currently, the emitter incorrectly encodes the imm-operand depends on the `addc` paths, which should only work on certain "scalar instructions" that operates over `reg/mem` or `imm`, e.g., `ADD [mem], reg` vs `ADD [mem], imm`. However, we cannot simply skip this path for SSE/AVX encoding because the relocation memory seems to depends on this mechanism (that is the CV case) with via `addlDelta`.

Trying different approaches to fix.

cc @CarolEidt @jkotas

**Closed** 2019-01-16 17:48 UTC
Labels: arch-x64, arch-x86, area-CodeGen, bug
