### ISSUE TITLE
SIGSEGV_HEAPCORRUPT_Cast10!Verification.AllequalComparer[[System.Int64, mscorlib]]

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#3660] opened 2016-03-11 16:32 UTC
**The notes in this bug refer to the dump [projectk-23902-00-amd64ret_00C4](https://dotnetjobresults.blob.core.windows.net/projectk-23902-00-stress/205a2398-dc2e-44be-9125-57ca41f21391/stress/generated/09_01hr/projectk-23902-00-amd64ret_00C4/projectk-23902-00-amd64ret_00C4.csproj/projectk-23902-00-amd64ret_00C4.zip?sv=2015-04-05&sr=c&sig=6KxVqZbsAaAIyiRvWzyl0J%2FHK6%2FEVaQyb%2BqJDtORajg%3D&se=2017-03-04T03:45:11Z&sp=rw). While some sos functionality is not available to fully diagnose this from the dump, this issue repro's quite redily under gcstress 3.  Also we have many other instances of this failure if those are needed.**  

**This failure is a heap corruption where we segfault in mark phase of a GC.  The segfault is because we have an invalid root in Cast10!Verification.AllequalComparer[[System.Int64, mscorlib]] on thread 6 of the dump.**

    FAILURE_HASH:
    SIGSEGV_HEAPCORRUPT_Cast10!Verification.AllequalComparer[[System.Int64, mscorlib]]

    CORRUPT_ROOT_THREAD:
    thread #6: tid = 54440, 0x00007fa5078bb414 libpthread.so.0`__pthread_cond_wait + 196 at pthread_cond_wait.S:185, stop reason = signal SIGSEGV

    CORRUPT_ROOT_FRAME_PC:
    0x7fa48c94182c

    CORRUPT_ROOT_FRAME:
    Cast10!Verification.AllequalComparer[[System.Int64, mscorlib]]

**Looking at thread 6 we can see that the last exceptoin on this thread occured very recently in a callout from Cast10!Verification.AllequalComparer to System.Linq.dll!System.Linq.Enumerable+<CastIterator>d__29`1[[System.Int64, mscorlib]].MoveNext()** 

        (lldb) thread select 6
        * thread #6: tid = 54440, 0x00007fa5078bb414 libpthread.so.0`__pthread_cond_wait + 196 at pthread_cond_wait.S:185, stop reason = signal SIGSEGV
            frame #0: 0x00007fa5078bb414 libpthread.so.0`__pthread_cond_wait + 196 at pthread_cond_wait.S:185
        (lldb) btm
        0       0x7fa5078bb414 libpthread.so.0!__pthread_cond_wait
        1       0x7fa5068d97d2 libcoreclr.so!CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*)
        2       0x7fa5068d9490 libcoreclr.so!CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*)
        3       0x7fa5068ddf71 libcoreclr.so!CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int)
        4       0x7fa5068de092 libcoreclr.so!WaitForSingleObjectEx
        5       0x7fa5064f9a31 libcoreclr.so!CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*)
        6       0x7fa5064f9a2c libcoreclr.so!CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*)
        7       0x7fa5064f9a23 libcoreclr.so!CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*)
        8       0x7fa5064f99c0 libcoreclr.so!CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*)
        9       0x7fa5065e1e01 libcoreclr.so!WKS::WaitLonger(int)
        10      0x7fa5065e1dd1 libcoreclr.so!WKS::WaitLonger(int)
        11      0x7fa5065e5786 libcoreclr.so!WKS::enter_spin_lock(WKS::GCDebugSpinLock*)
        12      0x7fa5065ef0c3 libcoreclr.so!WKS::GCHeap::GarbageCollectGeneration(unsigned int, WKS::gc_reason)
        13      0x7fa5066120ca libcoreclr.so!WKS::GCHeap::GarbageCollect(int, int, int)
        14      0x7fa506612093 libcoreclr.so!WKS::GCHeap::GarbageCollect(int, int, int)
        15      0x7fa506611733 libcoreclr.so!WKS::GCHeap::StressHeap(alloc_context*)
        16      0x7fa506437e05 libcoreclr.so!_GCStress::GCStress<(gcs_trigger_points)11, mpl::null_type, mpl::null_type, mpl::null_type>::MaybeTriggerAndProtect(Object*&)
        17      0x7fa506437ded libcoreclr.so!_GCStress::GCStress<(gcs_trigger_points)11, mpl::null_type, mpl::null_type, mpl::null_type>::MaybeTriggerAndProtect(Object*&)
        18      0x7fa506435d1c libcoreclr.so!VSD_ResolveWorker
        19      0x7fa50652d551 libcoreclr.so!ResolveWorkerAsmStub
    --> 20      0x7fa48c94182c Cast10!Verification.AllequalComparer[[System.Int64, mscorlib]](System.Collections.Generic.IEnumerable`1<Int64>, System.Collections.Generic.IEnumerable`1<Int64>, System.Collections.Generic.IEqualityComparer`1<Int64>)
        21      0x7fa48c940466 Cast10!Verification.Allequal[[System.Int64, mscorlib]](System.Collections.Generic.IEnumerable`1<Int64>, System.Collections.Generic.IEnumerable`1<Int64>)
        22      0x7fa48c93fcb0 Cast10!FX.Linq.Cast.Cast10.Test10()
        23      0x7fa48c93f73c Cast10!FX.Linq.Cast.Cast10.MainMethod()
        24      0x7fa48c93f6d4 Cast10!FX.Linq.Cast.Cast10.TestRunner()
        25      0x7fa48c93e0be projectk-23902-00-amd64ret_00C4!stress.generated.UnitTests.UT3()
        ...
        
        
    (lldb) pe
    Exception object: 00007fa4680b8e38
    Exception type:   System.InvalidCastException
    Message:          Unable to cast object of type 'System.Int32' to type 'System.Int64'.
    InnerException:   <none>
    StackTrace (generated):
        SP               IP               Function
        00007FA4FFA5C2E0 00007FA48C941C35 System.Linq.dll!System.Linq.Enumerable+<CastIterator>d__29`1[[System.Int64, mscorlib]].MoveNext()+0xc5
        00007FA4FFA5C310 00007FA48C941783 Cast10.dll!Verification.AllequalComparer[[System.Int64, mscorlib]](System.Collections.Generic.IEnumerable`1<Int64>, System.Collections.Generic.IEnumerable`1<Int64>, System.Collections.Generic.IEqualityComparer`1<Int64>)+0x383

    StackTraceString: <none>
    HResult: 80004002
        
**Looking at the dissasembly for Cast10!Verification.AllequalComparer we can see that we are in a EH funclet. Unfortunately getting the GCInfo for this method with sos doesn't appear to be working.  But I think it is highly likely that this failure is related to gc rooting or stack walking during the most recent exception.**

    (lldb) clru 0x7fa48c94182c
    ...
    00007fa48c941780 41ff13               call    qword ptr [r11]
    00007fa48c941783 8945cc               mov     dword ptr [rbp - 0x34], eax
    00007fa48c941786 8b7dcc               mov     edi, dword ptr [rbp - 0x34]
    00007fa48c941789 81e7ff000000         and     edi, 0xff
    00007fa48c94178f 897de4               mov     dword ptr [rbp - 0x1c], edi
    00007fa48c941792 8b7de4               mov     edi, dword ptr [rbp - 0x1c]
    00007fa48c941795 85ff                 test    edi, edi
    00007fa48c941797 0f85f7feffff         jne     0x7fa48c941694
    00007fa48c94179d 90                   nop
    00007fa48c94179e eb00                 jmp     0x7fa48c9417a0
    00007fa48c9417a0 488b3c24             mov     rdi, qword ptr [rsp]
    00007fa48c9417a4 e83f000000           call    0x7fa48c9417e8 (Verification.AllequalComparer[[System.Int64, mscorlib]](System.Collections.Generic.IEnumerable`1<Int64>, System.Collections.Generic.IEnumerable`1<Int64>, System.Collections.Generic.IEqualityComparer`1<Int64>), mdToken: 000000000600000B)
    00007fa48c9417a9 90                   nop
    00007fa48c9417aa 90                   nop
    00007fa48c9417ab 488bbd78ffffff       mov     rdi, qword ptr [rbp - 0x88]
    00007fa48c9417b2 393f                 cmp     dword ptr [rdi], edi
    00007fa48c9417b4 e847690900           call    0x7fa48c9d8100 (System.Collections.Generic.List`1[[System.Int64, mscorlib]].get_Count(), mdToken: 0000000006001C6E)
    00007fa48c9417b9 8945a8               mov     dword ptr [rbp - 0x58], eax
    00007fa48c9417bc 8b45a8               mov     eax, dword ptr [rbp - 0x58]
    00007fa48c9417bf 85c0                 test    eax, eax
    00007fa48c9417c1 740a                 je      0x7fa48c9417cd
    00007fa48c9417c3 90                   nop
    00007fa48c9417c4 c745a401000000       mov     dword ptr [rbp - 0x5c], 0x1
    00007fa48c9417cb eb05                 jmp     0x7fa48c9417d2
    00007fa48c9417cd 33c0                 xor     eax, eax
    00007fa48c9417cf 8945a4               mov     dword ptr [rbp - 0x5c], eax
    00007fa48c9417d2 90                   nop
    00007fa48c9417d3 8b45a4               mov     eax, dword ptr [rbp - 0x5c]
    00007fa48c9417d6 8945e8               mov     dword ptr [rbp - 0x18], eax
    00007fa48c9417d9 90                   nop
    00007fa48c9417da eb00                 jmp     0x7fa48c9417dc
    00007fa48c9417dc 90                   nop
    00007fa48c9417dd 8b45e8               mov     eax, dword ptr [rbp - 0x18]
    00007fa48c9417e0 488d65f8             lea     rsp, [rbp - 0x8]
    00007fa48c9417e4 415d                 pop     r13
    00007fa48c9417e6 5d                   pop     rbp
    00007fa48c9417e7 c3                   ret
    00007fa48c9417e8 55                   push    rbp
    00007fa48c9417e9 4155                 push    r13
    00007fa48c9417eb 50                   push    rax
    00007fa48c9417ec 488b2f               mov     rbp, qword ptr [rdi]
    00007fa48c9417ef 48892c24             mov     qword ptr [rsp], rbp
    00007fa48c9417f3 488dad90010000       lea     rbp, [rbp + 0x190]
    00007fa48c9417fa 488bbd48ffffff       mov     rdi, qword ptr [rbp - 0xb8]
    00007fa48c941801 4885ff               test    rdi, rdi
    00007fa48c941804 400f94c7             sete    dil
    00007fa48c941808 400fb6ff             movzx   edi, dil
    00007fa48c94180c 897de4               mov     dword ptr [rbp - 0x1c], edi
    00007fa48c94180f 8b7de4               mov     edi, dword ptr [rbp - 0x1c]
    00007fa48c941812 85ff                 test    edi, edi
    00007fa48c941814 7517                 jne     0x7fa48c94182d
    00007fa48c941816 488bbd48ffffff       mov     rdi, qword ptr [rbp - 0xb8]
    00007fa48c94181d 49bbf050738ca47f0000 movabs  r11, 0x7fa48c7350f0
    00007fa48c941827 393f                 cmp     dword ptr [rdi], edi
    00007fa48c941829 41ff13               call    qword ptr [r11]
    >>> 00007fa48c94182c 90                   nop
    ...

**Here's the data for the root we are currently examining**

    frame #4: 0x00007fa506601163 libcoreclr.so`WKS::GCHeap::Promote(ppObject=0x00007fa4ffa5c3d8, sc=0x00007fa466ff5728, flags=<unavailable>) + 307 at gc.cpp:33730 [opt]
    (lldb) fr v -D 1
    (Object **) ppObject = 0x00007fa4ffa5c3d8
    (ScanContext *) sc = 0x00007fa466ff5728
    (uint32_t) flags = <variable not available>

    (lldb) fr v *ppObject
    (Object *) *ppObject = 0x00007fa468025710

**Comment by janvorli** [comment] 2016-03-11 20:40
This test was run with CoreCLR that doesn't include my change #3584 and the issue is very likely caused by that. I will try to repro it locally with both the bits from the crashdump package and my local build of the latest coreclr to confirm that.

**Comment by janvorli** [comment] 2016-03-12 00:42
I've verified it was fixed by my change.

**Closed by janvorli** 2016-03-12 00:42 UTC
Labels: bug, reliability
