### ISSUE TITLE
[Arm64/Ubuntu] gcServer=1 NoGC test fails

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16537] opened 2018-02-24 00:20 UTC
`corerun NoGC.exe` with
```
export COMPlus_gcServer=1
export COMPlus_GCgen0size=0x100000
```

I saw

```
Server on 64-bit with 44 procs
=====allocating 200mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 45, after GC: 45
ended no gc region
current GC count: 89

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 135, after GC: 135
ended no gc region
current GC count: 179

=====allocating 400mb allowing full blocking GC first Succeeded=====
=====allocating 400mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 224, after GC: 224
ended no gc region
current GC count: 269

=====allocating 400mb disallowing full blocking GC first Succeeded=====
=====allocating 45056mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 45,056 MB
By Design: 45,056 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see "Latency Modes" in http://go.microsoft.com/fwlink/?LinkId=522706
Parameter name: totalSize
current GC count: 359

=====allocating 45056mb allowing full blocking GC first Succeeded=====
=====allocating 45056mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 45,056 MB
By Design: 45,056 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see "Latency Modes" in http://go.microsoft.com/fwlink/?LinkId=522706
Parameter name: totalSize
current GC count: 449

=====allocating 45056mb disallowing full blocking GC first Succeeded=====
=====allocating 200mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 495, after GC: 495
ended no gc region
current GC count: 539

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 585, after GC: 585
ended no gc region
```

Test ends with a Segmentation Fault.

**Comment by sdmaclea** [comment] 2018-02-24 00:23
`corerun NoGC.exe` with 
```
export COMPlus_gcServer=1
```

I see `We did GCs in no gc mode!!!` When tryin gto protect 45GBs!!!

```
Server on 64-bit with 44 procs
=====allocating 200mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 1, after GC: 1
ended no gc region
current GC count: 3

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 4, after GC: 4
ended no gc region
current GC count: 5

=====allocating 400mb allowing full blocking GC first Succeeded=====
=====allocating 400mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 6, after GC: 6
ended no gc region
current GC count: 7

=====allocating 400mb disallowing full blocking GC first Succeeded=====
=====allocating 45056mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 45,056 MB
By Design: 45,056 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see "Latency Modes" in http://go.microsoft.com/fwlink/?LinkId=522706
Parameter name: totalSize
current GC count: 7

=====allocating 45056mb allowing full blocking GC first Succeeded=====
=====allocating 45056mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 45,056 MB
By Design: 45,056 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see "Latency Modes" in http://go.microsoft.com/fwlink/?LinkId=522706
Parameter name: totalSize
current GC count: 8

=====allocating 45056mb disallowing full blocking GC first Succeeded=====
=====allocating 200mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 9, after GC: 9
ended no gc region
current GC count: 10

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 11, after GC: 11
ended no gc region
current GC count: 12

=====allocating 400mb allowing full blocking GC first Succeeded=====
=====allocating 400mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 13, after GC: 13
ended no gc region
current GC count: 14

=====allocating 400mb disallowing full blocking GC first Succeeded=====
=====allocating 45056mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 45,056 MB
45,056 MB SUCCEEDED, did 1 gen2 GCs
before GC: 15, after GC: 76
We did GCs in no gc mode!!!
ended no gc region
End NoGC region: 45,056 MB InvalidOperationException Allocated memory exceeds specified memory for NoGCRegion mode
current GC count: 76

=====allocating 45056mb allowing full blocking GC first Failed=====
=====allocating 45056mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 45,056 MB
45,056 MB SUCCEEDED, did 1 gen2 GCs
before GC: 77, after GC: 157
We did GCs in no gc mode!!!
ended no gc region
End NoGC region: 45,056 MB InvalidOperationException Allocated memory exceeds specified memory for NoGCRegion mode
current GC count: 157

=====allocating 45056mb disallowing full blocking GC first Failed=====
=====allocating 45056mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 45,056 MB
45,056 MB SUCCEEDED, did 1 gen2 GCs
before GC: 158, after GC: 158
ended no gc region
current GC count: 159

=====allocating 45056mb allowing full blocking GC first Succeeded=====
```
Command exited with non-zero status 1

**Comment by Maoni0** [comment] 2018-02-28 20:16
@sdmaclea thanks for reporting. could you please show us the callstack for the seg fault?

@sywhang could you please take a look? you can try to repro these on one of the 48-proc intel machines we have (I don't think being on arm64 should make a difference). please let me know if you need help.

**Comment by sdmaclea** [comment] 2018-02-28 20:21
@Maoni0 When I get a chance, I'll try to reproduce to get a stack trace

**Comment by Maoni0** [comment] 2018-02-28 20:25
thank you @sdmaclea

**Comment by sywhang** [comment] 2018-02-28 23:45
@Maoni0 we don't have any 48 proc intel machines running Ubuntu (they're all Windows). I'll try to repro this behavior on the Windows anyway and see where we land.

**Comment by sdmaclea** [comment] 2018-03-05 18:51
With the recent tip 430331c01, I do not see the segmentation fault (tried 3 times).  
I always see the thread killed presumably by the Out of Memory killer.

**Comment by sywhang** [comment] 2018-04-18 21:32
@sdmaclea Just FYI.. I tried repro'ing this on both Windows/Ubuntu on x64 machines, but I can't get a repro on this. I don't have access to any arm64 hardware at the moment. I will let you know once I can access to any arm64 machine.

**Comment by BruceForstall** [comment] 2019-01-09 00:46
@sywhang Are you still planning to look at this?

If we can't repro, should we close the issue?

**Comment by sywhang** [comment] 2019-01-09 18:37
@BruceForstall I still don't have an access to Linux/ARM64 machine to repro this and it doesn't repro on any other architectures I tried. As far as I know Maoni doesn't have one either. We should probably leave the issue open to track it but I'm not sure when I will have the HW to look at it.

**Comment by RussKeldorph** [comment] 2019-04-03 14:44
@sywhang Let me know if you want access to a Linux/ARM64 machine.  We have one you can use.

**Comment by Maoni0** [comment] 2019-04-04 05:37
I spent hours today to get an arm64 build to work. and then it did not repro  :crying_cat_face: I will close this now.

it's by design that it's trying to allocate 46gb on a 46-proc machine.

**Closed by Maoni0** 2019-04-04 05:37 UTC
Labels: arch-arm64, area-GC, blocking-3.0-preview-5
