### ISSUE TITLE
GCStress Failure: JIT._Methodical_flowgraph_bug619534_NonVirtualCall

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3767] opened 2016-03-16 19:12 UTC
JIT._Methodical_flowgraph_bug619534_NonVirtualCall_NonVirtualCall_._Methodical_flowgraph_bug619534_NonVirtualCall_NonVirtualCall_cmd
\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\JIT\Methodical\flowgraph\bug619534\NonVirtualCall\NonVirtualCall.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\JIT\Methodical\flowgraph\bug619534\NonVirtualCall\NonVirtualCall.cmd\n\r\nExpected: True\r\nActual:   False
   at JIT._Methodical_flowgraph_bug619534_NonVirtualCall_NonVirtualCall_._Methodical_flowgraph_bug619534_NonVirtualCall_NonVirtualCall_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\JIT\JIT.XUnitWrapper.cs:line 184396

**Comment by AndyAyersMS** [comment] 2016-03-16 19:21
@gkhanna79 Is this a regression?

**Comment by gkhanna79** [comment] 2016-03-16 19:23
@AndyAyersMS I dont know. I enabled GCstress support just last night/today and this came out of the run.

**Comment by AndyAyersMS** [comment] 2016-03-16 20:58
I probably need a more explicit repro instructions.

How does this differ from the jitstress that runs in the CI system, eg [this 0xC run](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_gcstress0xc/)?

**Comment by gkhanna79** [comment] 2016-03-16 21:45
Build Pri0 tests for GCStressLevel 15 (see instructions at https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-test-instructions.md) and then run the test.

These were exposed after tests were compiled with "crossgen" argument to precompile using R2R.

**Comment by AndyAyersMS** [comment] 2016-03-17 01:00
@LLITCHEV is going to triage these; reassigning.

**Comment by LLITCHEV** [comment] 2016-03-18 19:14
I tried reproducing this several times locally using a fresh enlistment and could not. It seems to work fine. Could you give me steps how you get it to happen locally, please?
I use GCStress=3,0xc and 15 as you mention above.

**Comment by LLITCHEV** [comment] 2016-03-18 20:20
It looks there is some kind of inconsistency in the manifest file. Below is an accessibility chack failure while compiling the test. It looks like a test or a library issue.
D:\TestRepo\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b29351\b29351>cd ..\..\..\..\..\Methodical\flowgraph\bug619534\NonV
irtualCall

D:\TestRepo\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Methodical\flowgraph\bug619534\NonVirtualCall>NonVirtualCall.cmd
BEGIN EXECUTION
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Warning: Could not load type 'System.Security.SecurityRulesAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
'. while resolving 0x1000002 - System.Security.SecurityRulesAttribute.
Warning: Could not load type 'System.Security.SecurityRuleSet' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. whil
e resolving 0x1000003 - System.Security.SecurityRuleSet.
Warning: Could not load type 'System.Security.SecurityRulesAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
'. while resolving 0xa000002 - System.Security.SecurityRulesAttribute..ctor.

Assert failure(PID 23760 [0x00005cd0], Thread: 21032 [0x5228]): Consistency check failed: Accessibility check failed while compiling platform assembly. Are you
missing FriendAccessAllowed attribute? Caller: NonVirtualCall <Module> Main Target: System.ConsoleFAILED: !pContext->GetCallerAssembly()->GetManifestFile()->IsP
rofileAssembly()

CROSSGEN! CHECK::Trigger + 0x2B4 (0x00007ff7`a8fa85e8)
CROSSGEN! AccessCheckOptions::DemandMemberAccessOrFail + 0x2C9 (0x00007ff7`a8cc010d)
CROSSGEN! CheckTransparentAccessToCriticalCode + 0xC8 (0x00007ff7`a8cbdd14)
CROSSGEN! ClassLoader::CanAccessClass + 0x54 (0x00007ff7`a8cbd0d8)
CROSSGEN! ClassLoader::CheckAccessMember + 0x3F (0x00007ff7`a8cbd9ef)
CROSSGEN! ClassLoader::CanAccess + 0x85 (0x00007ff7`a8cbcf25)
CROSSGEN! CEEInfo::getCallInfo + 0x118D (0x00007ff7`a8ce379d)
CROSSGEN! ZapInfo::getCallInfo + 0x8C (0x00007ff7`a8f9745c)
CROSSGEN! Compiler::impImportBlockCode + 0x5A18 (0x00007ff7`a8eb8958)
CROSSGEN! Compiler::impImportBlock + 0xFA (0x00007ff7`a8eb23e2)
    File: d:\testrepo\coreclr\src\vm\clsload.cpp Line: 5135
    Image: D:\TestRepo\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\crossgen.exe

 "D:\TestRepo\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" NonVirtualCall.exe

Assert failure(PID 21052 [0x0000523c], Thread: 16832 [0x41c0]): ZapRequire: Could not get native image for NonVirtualCall.
Use FusLogVw.exe to check the reason.

CORECLR! DomainFile::CheckZapRequired + 0x1D9 (0x00007ffc`2aa59ae5)
CORECLR! DomainAssembly::FindNativeImage + 0x784 (0x00007ffc`2aa5bd04)
CORECLR! DomainFile::DoIncrementalLoad + 0x1DD (0x00007ffc`2aa5a791)
CORECLR! AppDomain::TryIncrementalLoad + 0x20F (0x00007ffc`2a81c76f)
CORECLR! AppDomain::LoadDomainFile + 0xA07 (0x00007ffc`2a7fecaf)
CORECLR! AppDomain::LoadDomainAssemblyInternal + 0xB97 (0x00007ffc`2a7fdfbf)
CORECLR! AppDomain::LoadDomainAssembly + 0xE0 (0x00007ffc`2a7fd3c4)
CORECLR! AssemblySpec::LoadDomainAssembly + 0x7E3 (0x00007ffc`2a929d07)
CORECLR! AssemblySpec::LoadAssembly + 0x111 (0x00007ffc`2a9287ad)
CORECLR! AssemblySpec::LoadAssembly + 0x47D (0x00007ffc`2a92934d)
    File: d:\testrepo\coreclr\src\vm\domainfile.cpp Line: 963
    Image: D:\TestRepo\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe

**** MessageBox invoked, title 'CoreRun.exe - Assert Failure (PID 21052, Thread 16832/0x41c0)' ****
  ZapRequire: Could not get native image for NonVirtualCall.
Use FusLogVw.exe to check the reason.

CORECLR! DomainFile::CheckZapRequired + 0x1D9 (0x00007ffc`2aa59ae5)
CORECLR! DomainAssembly::FindNativeImage + 0x784 (0x00007ffc`2aa5bd04)
CORECLR! DomainFile::DoIncrementalLoad + 0x1DD (0x00007ffc`2aa5a791)
CORECLR! AppDomain::TryIncrementalLoad + 0x20F (0x00007ffc`2a81c76f)
CORECLR! AppDomain::LoadDomainFile + 0xA07 (0x00007ffc`2a7fecaf)
CORECLR! AppDomain::LoadDomainAssemblyInternal + 0xB97 (0x00007ffc`2a7fdfbf)
CORECLR! AppDomain::LoadDomainAssembly + 0xE0 (0x00007ffc`2a7fd3c4)
CORECLR! AssemblySpec::LoadDomainAssembly + 0x7E3 (0x00007ffc`2a929d07)
CORECLR! AssemblySpec::LoadAssembly + 0x111 (0x00007ffc`2a9287ad)
CORECLR! AssemblySpec::LoadAssembly + 0x47D (0x00007ffc`2a92934d)

d:\testrepo\coreclr\src\vm\domainfile.cpp, Line: 963

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
D:\TestRepo\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe

********

Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED

**Comment by gkhanna79** [comment] 2016-03-19 17:41
Repro steps: 

1) Build Pri1 tests with GCstress 15 using instructions at https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-test-instructions.md.

Example: tests\buildtests.cmd clean Release crossgen priority 1 gcstresslevel 15

2) Run the tests

Example: tests\runtest.cmd Release

3) Take a look at the results and repro steps in the failure report.

**Comment by LLITCHEV** [comment] 2016-03-20 22:14
Got this to happen.
It looks like there are couple of problems - the firest is benign, I think.
1. mscorlib doesn't contain the 'System.Security.SecurityRules*' attribute classes.
2. It looks like the importer is trying to verify the accessibility of the method for the call that it will need to import and decides to use a runtime check (for a delegate call), which is not supported functunality be R2R.
Also the Jit tries to call CORINFO_HELP_VERIFICATION method to verify the IL (parameters/access to) of a non final virtual method and it looks the R2R has no this functionality either.  

Not sure if this is a valid test for R2R. The interesting thing is that a ni image is still produced with these errors. I wonder if we should just fail.

Below is the output of the compilation (in 1.) and the dump of the Jit importer to the place where it gets one of the failures (in 2.)

Gaurav, please provide more information on what the desired behavior of this should be in R2R case and dispatch the issue as appropriate.


1.
D:\TestRepo\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Methodical\flowgraph\bug619534\NonVirtualCall>"%CORE_ROOT%\crossgen.exe" /Platform_Assemblies_Paths %CO
RE_ROOT%;. NonVirtualCall.exe
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Warning: Could not load type 'System.Security.SecurityRulesAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
'. while resolving 0x1000002 - System.Security.SecurityRulesAttribute.
Warning: Could not load type 'System.Security.SecurityRuleSet' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. whil
e resolving 0x1000003 - System.Security.SecurityRuleSet.
Warning: Could not load type 'System.Security.SecurityRulesAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
'. while resolving 0xa000002 - System.Security.SecurityRulesAttribute..ctor.
Verification failure:  importer.cpp:4232 : The 'this' parameter to the call must be either the calling method's 'this' parameter or a boxed value type., while c
ompiling <Module>:Test_CallNonFinalVirtualOutside_Neg() opcode call, IL offset 5
Verification failure:  importer.cpp:4232 : The 'this' parameter to the call must be either the calling method's 'this' parameter or a boxed value type., while c
ompiling <Module>:Test_CallNonFinalVirtualOutside_Neg() opcode call, IL offset 5
ReadyToRun: JIT helper not supported: CORINFO_HELP_VERIFICATION
Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL)) while compiling method <Module>.Test_CallNonFinalVirtualOutside_Neg
Verification failure:  importer.cpp:4080 : The 'this' parameter to the call must be either the calling method's 'this' parameter or a boxed value type., while c
ompiling <Module>:Test_DelegateNonFinalVirtualOutside_Neg() opcode newobj, IL offset b
Verification failure:  importer.cpp:4080 : The 'this' parameter to the call must be either the calling method's 'this' parameter or a boxed value type., while c
ompiling <Module>:Test_DelegateNonFinalVirtualOutside_Neg() opcode newobj, IL offset b
ReadyToRun: JIT helper not supported: CORINFO_HELP_VERIFICATION
Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL)) while compiling method <Module>.Test_DelegateNonFinalVirtualOutside_Neg
ReadyToRun: Runtime method access checks not supported
Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL)) while compiling method <Module>.Main


2.
Warning: Could not load type 'System.Security.SecurityRulesAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. while resolving 0x1000002 - System.Security.SecurityRulesAttribute.
Warning: Could not load type 'System.Security.SecurityRuleSet' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. while resolving 0x1000003 - System.Security.SecurityRuleSet.
Warning: Could not load type 'System.Security.SecurityRulesAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. while resolving 0xa000002 - System.Security.SecurityRulesAttribute..ctor.
****** START compiling <Module>:Test_CallNonFinalVirtualOutside_Neg() (MethodHash=b53911be)
OPTIONS: compCodeOpt = BLENDED_CODE
OPTIONS: compDbgCode = true
OPTIONS: compDbgInfo = true
OPTIONS: compDbgEnC  = false
OPTIONS: compProcedureSplitting   = false
OPTIONS: compProcedureSplittingEH = false
OPTIONS: Jit invoked for ngen
OPTIONS: Stack probing is DISABLED
IL to import:
IL_0000  73 03 00 00 0a    newobj       0xA000003
IL_0005  28 04 00 00 0a    call         0xA000004
IL_000a  2a                ret         
; Initial local variable assignments
;
*************** In compInitDebuggingInfo() for <Module>:Test_CallNonFinalVirtualOutside_Neg()
getVars() returned cVars = 0, extendOthers = true
info.compStmtOffsetsCount    = 0
info.compStmtOffsetsImplicit = 0007h ( STACK_EMPTY NOP CALL_SITE )
*************** In fgFindBasicBlocks() for <Module>:Test_CallNonFinalVirtualOutside_Neg()
Jump targets:
  none
New Basic Block BB01 [000000A463D88920] created.
BB01 [000..00B)
OPTIONS: opts.MinOpts() == true
Basic block list for '<Module>:Test_CallNonFinalVirtualOutside_Neg()'

-------------------------------------------------------------------------------------------------------------------------------------
BBnum         descAddr ref try hnd                 weight   [IL range]      [jump]      [EH region]         [flags]
-------------------------------------------------------------------------------------------------------------------------------------
BB01 [000000A463D88920]  1                              1   [000..00B)        (return)                     
-------------------------------------------------------------------------------------------------------------------------------------
*************** In impImport() for <Module>:Test_CallNonFinalVirtualOutside_Neg()

impImportBlockPending for BB01

Importing BB01 (PC=000) of '<Module>:Test_CallNonFinalVirtualOutside_Neg()'
    [ 0]   0 (0x000) newobj
lvaGrabTemp returning 0 (V00 tmp0) called for NewObj constructor temp.


               [000004] ------------             *  stmtExpr  void  (top level) (IL 0x000...  ???)
               [000001] --CXG-------             |  /--*  call help ref    HELPER.CORINFO_HELP_READYTORUN_NEW
               [000003] -ACXG-------             \--*  =         ref   
               [000002] D------N----                \--*  lclVar    ref    V00 tmp0         
 0A000003

               [000007] ------------             *  stmtExpr  void  (top level) (IL   ???...  ???)
               [000006] --C-G-------             \--*  call      void   ChildClass..ctor
               [000005] ------------ this in rcx    \--*  lclVar    ref    V00 tmp0         

    [ 1]   5 (0x005) call 0A000004Verification failure:  importer.cpp:4232 : The 'this' parameter to the call must be either the calling method's 'this' parameter or a boxed value type., while compiling <Module>:Test_CallNonFinalVirtualOutside_Neg() opcode call, IL offset 5
Verification failure:  importer.cpp:4232 : The 'this' parameter to the call must be either the calling method's 'this' parameter or a boxed value type., while compiling <Module>:Test_CallNonFinalVirtualOutside_Neg() opcode call, IL offset 5


               [000013] ------------             *  stmtExpr  void  (top level) (IL 0x000...  ???)
               [000012] --CXG-------             \--*  call help void   HELPER.CORINFO_HELP_VERIFICATION
               [000010] ------------ arg0           \--*  const     int    0

**Comment by jkotas** [comment] 2016-03-25 05:58
This is invalid test for .NET Core. I have deleted it in https://github.com/dotnet/coreclr/pull/3888/commits/4d3b8acd161bcd5890be78af5130526575264ccc

**Closed by jkotas** 2016-03-25 05:58 UTC
Labels: blocking-release, bug, CodeGen, GCStress, ReadyToRun
