### ISSUE TITLE
GCStress Failure: WeakReference Tests

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3792] opened 2016-03-17 17:43 UTC
CoreMangLib._cti_system_weakreference_WeakReferenceCtor1_PSC_WeakReferenceCtor1_PSC_._cti_system_weakreference_WeakReferenceCtor1_PSC_WeakReferenceCtor1_PSC_cmd
\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\CoreMangLib\cti\system\weakreference\WeakReferenceCtor1_PSC\WeakReferenceCtor1_PSC.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\CoreMangLib\cti\system\weakreference\WeakReferenceCtor1_PSC\WeakReferenceCtor1_PSC.cmd\n\r\nExpected: True\r\nActual:   False
   at CoreMangLib._cti_system_weakreference_WeakReferenceCtor1_PSC_WeakReferenceCtor1_PSC_._cti_system_weakreference_WeakReferenceCtor1_PSC_WeakReferenceCtor1_PSC_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\CoreMangLib\CoreMangLib.XUnitWrapper.cs:line 123676
3.226864s ✘  CoreMangLib._cti_system_weakreference_WeakReferenceCtor2_PSC_WeakReferenceCtor2_PSC_._cti_system_weakreference_WeakReferenceCtor2_PSC_WeakReferenceCtor2_PSC_cmd
\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\CoreMangLib\cti\system\weakreference\WeakReferenceCtor2_PSC\WeakReferenceCtor2_PSC.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\CoreMangLib\cti\system\weakreference\WeakReferenceCtor2_PSC\WeakReferenceCtor2_PSC.cmd\n\r\nExpected: True\r\nActual:   False
   at CoreMangLib._cti_system_weakreference_WeakReferenceCtor2_PSC_WeakReferenceCtor2_PSC_._cti_system_weakreference_WeakReferenceCtor2_PSC_WeakReferenceCtor2_PSC_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\CoreMangLib\CoreMangLib.XUnitWrapper.cs:line 123786
1.0865406s ✘  CoreMangLib._cti_system_weakreference_WeakReferenceCtor2b_PSC_WeakReferenceCtor2b_PSC_._cti_system_weakreference_WeakReferenceCtor2b_PSC_WeakReferenceCtor2b_PSC_cmd
\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\CoreMangLib\cti\system\weakreference\WeakReferenceCtor2b_PSC\WeakReferenceCtor2b_PSC.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\CoreMangLib\cti\system\weakreference\WeakReferenceCtor2b_PSC\WeakReferenceCtor2b_PSC.cmd\n\r\nExpected: True\r\nActual:   False
   at CoreMangLib._cti_system_weakreference_WeakReferenceCtor2b_PSC_WeakReferenceCtor2b_PSC_._cti_system_weakreference_WeakReferenceCtor2b_PSC_WeakReferenceCtor2b_PSC_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\CoreMangLib\CoreMangLib.XUnitWrapper.cs:line 123731
1.129263s ✘  CoreMangLib._cti_system_weakreference_WeakReferenceIsAlive_PSC_WeakReferenceIsAlive_PSC_._cti_system_weakreference_WeakReferenceIsAlive_PSC_WeakReferenceIsAlive_PSC_cmd
\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\CoreMangLib\cti\system\weakreference\WeakReferenceIsAlive_PSC\WeakReferenceIsAlive_PSC.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\CoreMangLib\cti\system\weakreference\WeakReferenceIsAlive_PSC\WeakReferenceIsAlive_PSC.cmd\n\r\nExpected: True\r\nActual:   False
   at CoreMangLib._cti_system_weakreference_WeakReferenceIsAlive_PSC_WeakReferenceIsAlive_PSC_._cti_system_weakreference_WeakReferenceIsAlive_PSC_WeakReferenceIsAlive_PSC_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\CoreMangLib\CoreMangLib.XUnitWrapper.cs:line 123896
0.8274408s ✘  CoreMangLib._cti_system_weakreference_WeakReferenceIsAliveb_PSC_WeakReferenceIsAliveb_PSC_._cti_system_weakreference_WeakReferenceIsAliveb_PSC_WeakReferenceIsAliveb_PSC_cmd
\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\CoreMangLib\cti\system\weakreference\WeakReferenceIsAliveb_PSC\WeakReferenceIsAliveb_PSC.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\CoreMangLib\cti\system\weakreference\WeakReferenceIsAliveb_PSC\WeakReferenceIsAliveb_PSC.cmd\n\r\nExpected: True\r\nActual:   False
   at CoreMangLib._cti_system_weakreference_WeakReferenceIsAliveb_PSC_WeakReferenceIsAliveb_PSC_._cti_system_weakreference_WeakReferenceIsAliveb_PSC_WeakReferenceIsAliveb_PSC_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\CoreMangLib\CoreMangLib.XUnitWrapper.cs:line 123841

**Comment by gkhanna79** [comment] 2016-03-28 17:44
Affects x86 as well

**Comment by gkhanna79** [comment] 2016-05-10 19:25
Look for GCstress Pri1R2R jobs to see results for these at http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/

**Comment by fadimounir** [comment] 2016-05-20 20:24
These failures are by design. These tests are not supposed to run the GCStress configuration, because they are testing weak-gchandles (GCStress mode makes the GC aggressively collect dead references, making it impossible for the test to validate the functionality of weak GC handles).

The tests also fail without R2R. This is not a R2R specific issue.

**Comment by RussKeldorph** [comment] 2016-05-26 16:54
These are still failing (see failures in #5243).  These tests need to be disabled for GCStress.  Add <GCStressIncompatible>true</GCStressIncompatible> property to the test's project file.

**Comment by fadimounir** [comment] 2016-05-27 22:26
Fixed with PR #5289

**Closed by fadimounir** 2016-05-27 22:26 UTC
Labels: blocking-release, GCStress, ReadyToRun, Test-Issue
