### ISSUE TITLE
Test Failed: JIT.jit64.opt.cse.HugeArray1.HugeArray1 seg faults on RHEL7.2

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#6283] opened 2016-07-14 19:27 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_rhel7.2_pri1_tst/175/testReport/junit/JIT.jit64.opt.cse/HugeArray1/HugeArray1/

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_rhel7.2_pri1_tst/259/testReport/junit/JIT.jit64.opt.cse/HugeArray1/HugeArray1/

These are 2 examples I can find of this happening. I've also seen code coverage jobs time out after waiting for a similar test to complete (HugeExpr1) - http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_release_ubuntu_coverage_tst_prtest/35/console

**Comment by janvorli** [comment] 2016-07-14 19:41
This is a problem that @adityam , @sergiy-k and @janvorli have been investigating for quite some time. It seems to happen on RHEL and CentOS only and we cannot repro it locally. What happens is that it seg faults on a read from memory that is mapped as read / write and valid (based on data from core dumps) and the si_code is 2 => SEGV_ACCERR, which is really strange.

**Comment by adityamandaleeka** [comment] 2016-09-09 21:15
After much debugging and investigation, the problem turned out to be a bug in the memory management code in the kernel used by our RHEL and CentOS machines. The bug causes some page table entries to lose the `_PAGE_USER` pagetable bit when page migration races with mprotect.

I'm working with RedHat to have the fix released in an update to RHEL7.

I observed that I am not able to reproduce the issue when transparent hugepage support is disabled. Based on what we know now, THP isn't related to the problem, but it triggers page migrations (which lead to the bug). As a temporary stopgap until the fixed kernel is released, we could just disable THP on the RHEL CI machines.

**Comment by tmds** [comment] 2017-01-06 08:31
@adityamandaleeka is there a bug report at bugzilla.redhat.com for this issue?

**Comment by adityamandaleeka** [comment] 2017-01-06 18:01
@tmds Yes, the bug number for the report I opened is 1374548.

**Comment by karelz** [comment] 2017-03-05 01:17
Here's the bug link: https://bugzilla.redhat.com/show_bug.cgi?id=1374548 (sadly restricted as internal only to RedHat)

@adityamandaleeka is there an easy way how to identify a segfault as dupe of this bug? Particular patterns or something?

**Comment by adityamandaleeka** [comment] 2017-03-06 22:00
@karelz If the crash is a segfault with code SEGV_ACCERR when accessing a valid region of memory (mapped with the correct permissions), it's likely a result of this bug. As an additional data point, every occurrence of the crash I've seen has been in JIT code, with `compCompile` on the stack.

**Comment by karelz** [comment] 2017-03-06 22:07
Great, thanks @adityamandaleeka!

**Comment by Jiayili1** [comment] 2017-08-11 06:38
failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20170811.01/workItem/JIT.jit64.XUnitWrapper/analysis/xunit/JIT_jit64._opt_cse_HugeArray1_HugeArray1_~2F_opt_cse_HugeArray1_HugeArray1_cmd

**Comment by tmds** [comment] 2017-08-11 06:57
This issue was fixed as part of rhel 7.4.

**Comment by Sunny-pu** [comment] 2018-03-15 08:07
failed again:
https://mc.dot.net/#/product/netcore/200/source/official~2Fcoreclr~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20180314.01/workItem/JIT.jit64.XUnitWrapper/analysis/xunit/JIT_jit64._opt_cse_HugeArray1_HugeArray1_~2F_opt_cse_HugeArray1_HugeArray1_cmd

**Comment by BruceForstall** [comment] 2019-09-20 18:17
I'm going to close this. If it fails again, open a new bug or re-open this bug.

**Closed by BruceForstall** 2019-09-20 18:17 UTC
Labels: area-CodeGen, bug, tracking-external-issue
