### ISSUE TITLE
Regressions on threading-related unittests

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#11773] opened 2017-05-22 02:10 UTC
Suddenly, several threading-related tests failed to find a relevant script:
```
FAILED   - [ 11076 :    3 sec ] baseservices/threading/interlocked/add/CheckAddInt_1/CheckAddInt_1.sh
               BEGIN EXECUTION
               export CDPATH=.
               /bin/sh -c ..CheckAddIntCheckAddInt.sh
               /bin/sh: 1: ..CheckAddIntCheckAddInt.sh: not found
               Expected: 0
               Actual: 127
               END EXECUTION - FAILED
```

It seems that the relevant script uses incorrect path separator:
```
echo export CDPATH="$(dirname "$0")"
export CDPATH="$(dirname "$0")"
echo /bin/sh -c  ..\CheckAddInt\CheckAddInt.sh
/bin/sh -c ..\CheckAddInt\CheckAddInt.sh
CLRTestExitCode=$?
CLRTestExpectedExitCode=0
```

**Comment by parjong** [comment] 2017-05-22 02:11
@jkotas As I know, this script is built by buildtools (downloaded during init-tools.sh). Is there any changes in script generator? Could you let me know who is responsible to this issue?

**Comment by jkotas** [comment] 2017-05-22 04:49
@wtgodbe Looks like regression introduce by recent build-tools update

**Comment by wtgodbe** [comment] 2017-05-22 18:07
@swgillespie when did you start seeing these failures? Also, can you point me where these scripts are generated? I only know of https://github.com/dotnet/coreclr/blob/master/tests/src/CLRTest.Execute.targets & the related files

**Comment by swgillespie** [comment] 2017-05-23 03:26
@wtgodbe I haven't seen these failures before. As far as I know CLRTest.Execute.*.tests and friends are the only target files involved in bash script generation.

**Comment by wtgodbe** [comment] 2017-05-23 18:02
Wait, I'm confused - if you haven't seen them, where did the failure in the issue come from? And what did you mean by:

> As I know, this script is built by build-tools (downloaded during init-tools.sh).

**Comment by swgillespie** [comment] 2017-05-23 18:04
@wtgodbe did you mean @parjong ?

**Comment by wtgodbe** [comment] 2017-05-23 18:10
Oh yeah, I did - my mistake.

**Comment by wtgodbe** [comment] 2017-05-23 18:13
@parjong the relevant portion of the script is generated here: https://github.com/dotnet/coreclr/blob/master/tests/src/CLRTest.Execute.Bash.targets#L265

Have the tests failed in the last 22 hours? And did they start failing on Friday? If so, this is probably related to https://github.com/dotnet/coreclr/commit/aad6903366ed6d70f218b92bfc762feb29a73773, which was merged on Friday & reverted 22 hours ago. CC @rartemev

**Closed** 2017-05-24 04:40 UTC
