### ISSUE TITLE
Prefer32Bit is ignored

### ISSUE THREAD

**Issue by iskiselev** [dotnet/coreclr#26014] opened 2019-08-05 21:08 UTC
Project file setting <Prefer32Bit>true</Prefer32Bit> is ignored on CoreCLR 3.0 it produce x64 executable. Technically, produced executable is only entry point and is unmanaged - so corflags will even not show anything. But this flag option is still visible in VisualStudio, which mislead.

I'm not sure where it should be reported - here, in core-setup, sdk or Visual Studio.

**Comment by mikedn** [comment] 2019-08-05 21:10
Duplicate of https://github.com/dotnet/project-system/issues/5074

**Closed** 2019-08-05 21:14 UTC
