### ISSUE TITLE
Register .NET Core type for COM interop

### ISSUE THREAD

**Issue by ericjohannsen** [dotnet/coreclr#27573] opened 2019-10-31 05:19 UTC
I built a trivial .NET Core 3 library project to test ComVisibleAttribute:
``` C#
[Guid("a843456f-3657-4a01-a133-fd333a84aa58")]
[ClassInterface(ClassInterfaceType.None)]
[ComVisible(true)]
public class Foo
{        
    public string Bar()
    {
        return "42";
    }
}
```
Then run `regasm my.dll` and get this error:

Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Is this currently supposed to work? If so, what am I doing wrong?

**Comment by AaronRobinsonMSFT** [comment] 2019-10-31 06:44
@ericjohannsen The `regasm` tool is not support on .NET Core. The ensure COM server model has been updated to more align with COM and avoid special casing by .NET. For full details on activation see https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/COM-activation.md. Examples on COM servers in .NET Core can be found [here](https://github.com/dotnet/samples/tree/master/core/extensions/COMServerDemo).

**Comment by AaronRobinsonMSFT** [comment] 2019-10-31 06:51
A walk through for exposing .NET Core types is at https://docs.microsoft.com/dotnet/core/native-interop/expose-components-to-com

**Comment by ericjohannsen** [comment] 2019-10-31 16:12
When following that tutorial with a fresh project, I get the compiler error:

error NETSDK1091: Unable to find a .NET Core COM host. The .NET Core COM host is only available on .NET Core 3.0 or higher when targeting Windows.

My code:
``` C#
using System;
using System.Runtime.InteropServices;

namespace MyCom
{
    [ComVisible(true)]
    [Guid("226E5561-C68E-4B2B-BD28-25103ABCA3B1")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IServer
    {
        int Fibonacci();
    }

    [ComVisible(true)]
    [Guid("09E01FCD-9970-4DB3-B537-0EC555967DD9")]
    public class Server
    {
        public ulong Fibonacci(ulong whichTerm)
        {
            if (whichTerm < 1) throw new ArgumentException("");
            ulong a = 0;
            ulong b = 1;
            for (ulong i = 0; i < whichTerm; i++)
            {
                ulong tmp = a;
                a = b;
                b = tmp + b;
            }
            return a;
        }
    }
}
```

Here's my .csproj:

``` XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <EnableComHosting>true</EnableComHosting>
  </PropertyGroup>
</Project>
```

I'm working in VS2019 on Windows 10 with the release version of .NET Core 3.

**Comment by AaronRobinsonMSFT** [comment] 2019-10-31 17:13
@ericjohannsen I am unclear why this error was happening but went away after adding a new project. I can only postulate this is related to some issue in the restore operation for .NET Core from with Visual Studio. If you can reproduce this again - would require purging your NuGet cache - I would file a bug at https://developercommunity.visualstudio.com/spaces/8/index.html.

I am going to close this issue for now. Thanks.

**Closed by AaronRobinsonMSFT** 2019-10-31 17:13 UTC
Labels: area-Interop, question

**Comment by AaronRobinsonMSFT** [comment] 2019-10-31 18:25
>The presence of the xUnit project in the solution causes the error. I can consistently reproduce or remove the error by loading and unloading the xUnit project.

@ericjohannsen That is even worse. I can't reproduce that behavior either, but thank you for reporting this.

**Comment by ericjohannsen** [comment] 2019-10-31 19:50
I was only getting the error before registering the COM assembly with regsvr32.

When I unregistered it with regsvr32 /u, I got the error again after a clean and rebuild. I "fixed" it again by re-registering the COM assembly (again a clean and rebuild was needed).
