### ISSUE TITLE
Build.bat not working on windows 7

### ISSUE THREAD

**Issue by raizam** [dotnet/coreclr#12268] opened 2017-06-14 12:45 UTC
Here is the console output. Any help appreciated

> D:\Forks\coreclr>.\build skiptests
> Starting Build at 14:41:51,87
> BUILD: Commencing CoreCLR Repo build
> BUILD: Checking prerequisites
> BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat"
> Tools are already initialized.
> Running: D:\Forks\coreclr\Tools\dotnetcli\dotnet.exe D:\Forks\coreclr\Tools\run.
> exe D:\Forks\coreclr\config.json build -Project=D:\Forks\coreclr\build.proj -gen
> erateHeaderWindows -NativeVersionHeaderFile="D:\Forks\coreclr\bin\obj\_version.h " -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64
> 
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
>    at Newtonsoft.Json.JsonConvert.DeserializeObject
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T]
>    at Microsoft.DotNet.Execute.Executor.OpenFile()
>    at Microsoft.DotNet.Execute.Executor.Main(String[] args)
> BUILD: Commencing build of native components for Windows_NT.x64.Debug
> BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\C
> ommon7\Tools\\..\..\VC\vcvarsall.bat" x86_amd64
> BUILD: Regenerating the Visual Studio solution
> -- VS_PLATFORM_TOOLSET is v140
> -- VS_PLATFORM_NAME is x64
> CMake Error at CMakeLists.txt:70 (message):
>   MC not found
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/Forks/coreclr/bin/obj/Windows_NT.x64.Debug/CMakeFiles/CMakeOutput.log".
> See also "D:/Forks/coreclr/bin/obj/Windows_NT.x64.Debug/CMakeFiles/CMakeError.log".
> BUILD: Error: failed to generate native component build project

**Comment by raizam** [comment] 2017-06-14 12:51
This issue was already reported #12176

**Comment by RussKeldorph** [comment] 2017-12-01 17:11
Duplicate of #12176.

**Closed by RussKeldorph** 2017-12-01 17:11 UTC
Labels: area-Build
