### ISSUE TITLE
CoreFX test failures, incl. System.Buffers.Tests.ArrayBufferWriterTests_Byte.Advance

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#24159] opened 2019-04-22 01:30 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs0x80/842/

**Failed tests:**
System.Buffers.Tests.ArrayBufferWriterTests_Byte.Advance
System.Buffers.Tests.ArrayBufferWriterTests_Char.Advance

**Failed log:**
```
System.Buffers.Tests.ArrayBufferWriterTests_Byte.Advance [FAIL]
  [Long Running Test] 'System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData_MemberData', Elapsed: 00:15:58
  [Long Running Test] 'System.IO.Tests.Pipes.AnonymousPipeReadViaFileStream', Elapsed: 00:15:38
        Assert.True() Failure
  [Long Running Test] 'System.IO.Tests.FileStream_FlushAsync.FlushAfterReading', Elapsed: 00:15:37
  [Long Running Test] 'System.IO.Tests.FileStream_WriteAsync_AsyncWrites.WriteAsyncInternalBufferOverflow', Elapsed: 00:15:34
        Expected: True
  [Long Running Test] 'System.IO.Tests.FileStream_BeginEndWrite_AsyncWrites.WriteAsyncCancelledFile', Elapsed: 00:14:43
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---ac310d4a\_\fx\src\System.Memory\tests\ArrayBufferWriter\ArrayBufferWriterTests.T.cs(95,0): at System.Buffers.Tests.ArrayBufferWriterTests`1.Advance()
  [Long Running Test] 'System.IO.Tests.Sync_FileStream_ReadWrite_Span.EmptyFile_ReadAsync_Succeeds', Elapsed: 00:14:31
  [Long Running Test] 'System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_sync', Elapsed: 00:14:30
  [Long Running Test] 'System.IO.Tests.File_Copy_str_str_b.CopyFileWithData_MemberData', Elapsed: 00:14:27
      System.Buffers.Tests.ArrayBufferWriterTests_Char.Advance [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
     System.Linq.Expressions.Tests: [Long Running Test] 'System.Linq.Expressions.Tests.ArrayBoundsTests.NewArrayBounds', Elapsed: 00:10:23
        Stack Trace:
          D:\j\workspace\x64_checked_w---ac310d4a\_\fx\src\System.Memory\tests\ArrayBufferWriter\ArrayBufferWriterTests.T.cs(95,0): at System.Buffers.Tests.ArrayBufferWriterTests`1.Advance()
     System.IO.FileSystem.Tests: [Long Running Test] 'System.IO.Tests.Sync_DerivedFileStream_ReadWrite_Span.NonEmptyWriteAsync_CustomMemoryManager_WritesExpectedData', Elapsed: 00:17:55
  [Long Running Test] 'System.IO.Tests.File_AppendAllTextAsync.OverwriteAsync', Elapsed: 00:18:15
  [Long Running Test] 'System.IO.Tests.File_ReadWriteAllLines_Enumerable_EncodedAsync.DisposingEnumeratorClosesFileAsync', Elapsed: 00:18:04
  [Long Running Test] 'System.IO.Tests.FileStream_BeginEndRead_AsyncReads.EmptyFileReadAsyncSucceedSynchronously', Elapsed: 00:18:17
  [Long Running Test] 'System.IO.Tests.File_AppendAllLinesAsync_Encoded.NullLinesAsync', Elapsed: 00:18:14
  [Long Running Test] 'System.IO.Tests.File_ReadWriteAllTextAsync.ValidWriteAsync', Elapsed: 00:18:08
  [Long Running Test] 'System.IO.Tests.FileStream_DisposeAsync.DisposeAsyncFlushes', Elapsed: 00:18:13
  [Long Running Test] 'System.IO.Tests.File_ReadWriteAllLines_EnumerableAsync.ValidWriteAsync', Elapsed: 00:18:12
  [Long Running Test] 'System.IO.Tests.File_AppendAllTextAsync_Encoded.OverwriteAsync', Elapsed: 00:18:11
  [Long Running Test] 'System.IO.Tests.FileInfo_CopyTo_str.CopyFileWithData_MemberData', Elapsed: 00:18:06
  [Long Running Test] 'System.IO.Tests.File_Copy_str_str.CopyFileWithData_MemberData', Elapsed: 00:18:08
  [Long Running Test] 'System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData_MemberData', Elapsed: 00:18:01
  [Long Running Test] 'System.IO.Tests.Pipes.AnonymousPipeReadViaFileStream', Elapsed: 00:17:40
  [Long Running Test] 'System.IO.Tests.FileStream_FlushAsync.FlushAfterReading', Elapsed: 00:17:40
  [Long Running Test] 'System.IO.Tests.FileStream_WriteAsync_AsyncWrites.WriteAsyncInternalBufferOverflow', Elapsed: 00:17:36
  [Long Running Test] 'System.IO.Tests.FileStream_BeginEndWrite_AsyncWrites.WriteAsyncCancelledFile', Elapsed: 00:16:45
  [Long Running Test] 'System.IO.Tests.Sync_FileStream_ReadWrite_Span.EmptyFile_ReadAsync_Succeeds', Elapsed: 00:16:33
  [Long Running Test] 'System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_sync', Elapsed: 00:16:33
  [Long Running Test] 'System.IO.Tests.File_Copy_str_str_b.CopyFileWithData_MemberData', Elapsed: 00:16:30
     System.Linq.Expressions.Tests: [Long Running Test] 'System.Linq.Expressions.Tests.ArrayBoundsTests.NewArrayBounds', Elapsed: 00:12:25
    Finished:    System.Memory.Tests
  === TEST EXECUTION SUMMARY ===
     System.Memory.Tests  Total: 45349, Errors: 0, Failed: 2, Skipped: 0, Time: 268.522s
  ----- end 17:02:04.68 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment] 2019-04-22 19:08
Test also fails on Linux/arm64, so is apparently all-platform failure.

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/177/consoleFull

**Comment by BruceForstall** [comment] 2019-04-22 19:15
@ahsonkhan Looks like this might be your test

cc @joshfree @karelz

**Comment by BruceForstall** [comment] 2019-04-24 00:53
If I set `COMPlus_JitMinOpts=1`, the test passes. That makes it likely some kind of codegen bug.

@dotnet/jit-contrib

**Comment by BruceForstall** [comment] 2019-04-24 00:56
Test source lives:

https://github.com/dotnet/corefx/blob/9e2f3b630a51875fc0455a7cabb8803f6527f81e/src/System.Memory/tests/ArrayBufferWriter/ArrayBufferWriterTests.T.cs#L90-L98

**Comment by ahsonkhan** [comment] 2019-04-24 01:01
If its reproducible, it might help to see the actual length/content mismatch (for example here: https://github.com/ahsonkhan/corefx/commit/4440b5cdcea7e33ac085eccae5ed303ca4d777e9), that is, if the underlying object/buffer is being modified at JIT time between the two property accesses (`WrittenMemory` vs `WrittenSpan`).

**Comment by BruceForstall** [comment] 2019-04-24 01:08
Note that https://github.com/dotnet/coreclr/pull/24201 disabled these tests, and any fix here should re-enable them.

**Comment by BruceForstall** [comment] 2019-04-24 17:02
My guess here is that this test only passes in corefx testing because TieredCompilation is enabled, but has always failed when it is disabled, as it is for corefx-in-coreclr-CI testing.

**Comment by erozenfeld** [comment] 2019-04-26 01:59
I'll investigate.

**Comment by erozenfeld** [comment] 2019-05-03 21:31
This is a bug in jit value numbering. It has some assumptions that are not valid when there is struct reinterpretation via Unsafe.As.

I created a simple repro that's not using any corefx types. The code below prints 0 (incorrect) when optimizations are enabled and it prints 7 (correct) when optimizations are disabled.

```
public struct Str1
    {
        public int i1;
        public int i2;
        public int i3;
        public int i4;
        public int i5;
    }

    public struct Str2
    {
        public int i1;
        public int i2;
        public int i3;
        public int i4;
        public int i5;
    }

    class Test
    {
        static int i;

        public static int Main()
        {
            i = 0;

            Str1 str1 = new Str1();

            str1.i2 = 7;

            if (i != 0)
            {
                str1 = new Str1();
            }
            else
            {
                str1.i2 = 7;
            }

            Str2 str2 = Unsafe.As<Str1, Str2>(ref str1);

            int j = str2.i2;

            Console.WriteLine(j);

            return j + 93;

        }
    }
```

**Comment by erozenfeld** [comment] 2019-05-03 22:50
Before value numbering 
`str1.i2 = 7;`
is
```
     (  5,  6) [000019] ------------              *  STMT      void  (IL 0x01F...0x022)
N001 (  1,  1) [000016] ------------              |  /--*  CNS_INT   int    7
N003 (  5,  6) [000018] -A------R---              \--*  ASG       int   
N002 (  3,  4) [000014] U------N----                 \--*  LCL_FLD   int    V00 loc0         ud:2->3[+4] Fseq[i2, bd778140]
```
and 
`int k = str2.j2;`
is

```
     (  3,  4) [000030] ------------              *  STMT      void  (IL   ???...  ???)
N001 (  3,  4) [000046] ------------              |  /--*  LCL_FLD   int    V00 loc0         u:5[+4] Fseq[j2, bd7782d8] (last use)
N003 (  3,  4) [000029] -A--G---R---              \--*  ASG       int   
N002 (  1,  1) [000028] D------N----                 \--*  LCL_VAR   int    V02 tmp1         d:2
```
The dumps above include actual CORINFO_FIELD_HANDLE's (FieldSeqNode.m_fieldHnd) for field accesses. Note that they are different in the trees above (bd778140) and (bd7782d8) yet the variable is the same (V00 loc0) and the offset is the same ([+4]).

Value numbering uses FieldSeqNode.m_fieldHnd when computing keys into into store maps:
https://github.com/dotnet/coreclr/blob/75ae3b5b05f4ab9639fbc24871aafdc7d706c35f/src/jit/valuenum.cpp#L3655-L3657
and the assumption is that two different field sequence handles on the same object can't refer to the same field.

The use of Unsafe.As breaks that assumption.

**Comment by erozenfeld** [comment] 2019-05-03 22:59
I don't see a simple fix here. Conceptually, we could avoid the problem if we used offsets to compute keys instead of field sequence handles but that would be a big change. Value numbering has field sequence ids baked in pretty deeply. Another option is to disable value-numbering-based optimizations for methods that have Unsafe.As struct reinterpretation. That might cause CQ issues.

I'll continue explore options.

@dotnet/jit-contrib Let me know if you have thoughts on this.

**Comment by erozenfeld** [comment] 2019-05-03 23:40
In the original corefx issue Unsafe.As is used here:

```System.Buffers.ArrayBufferWriter`1<char>::get_WrittenMemory()``` calls
```System.Memory`1<char>::op_Implicit(valuetype System.Memory`1<char>)``` calls
```Internal.Runtime.CompilerServices.Unsafe::As<valuetype System.Memory`1<char>, valuetype System.ReadOnlyMemory`1<char>>(valuetype System.Memory`1<char>&)```

**Comment by mikedn** [comment] 2019-05-04 08:26
I'd say that the tree
```
     (  3,  4) [000030] ------------              *  STMT      void  (IL   ???...  ???)
N001 (  3,  4) [000046] ------------              |  /--*  LCL_FLD   int    V00 loc0         u:5[+4] Fseq[j2, bd7782d8] (last use)
N003 (  3,  4) [000029] -A--G---R---              \--*  ASG       int   
N002 (  1,  1) [000028] D------N----                 \--*  LCL_VAR   int    V02 tmp1         d:2
```
is basically incorrect. Well, it's debatable since there's no accurate description of what should happen in this case but the fact that the `LCL_FLD` has field sequence `Str.j2` when the type of the lclvar is `Str1` is pretty dubious from the point of view of field sequences. The field sequence should either be changed to `Str1.i2` or to "not a field" if this is too difficult to implement or in cases where there's no 1:1 mapping between the fields of the structs.

**Comment by briansull** [comment] 2019-05-06 16:45
It should be possible to fix this issue. 
We should generate a "NotAField" for such a case.
That is what we already do when a struct is marked as containing overlapping fields.

So we can trigger this one of two ways:
1) Whenever we see Unsafe.As used the source struct can be consider to have all overlapping fields.
2) When the field use is not a member of the struct type that we are using.

**Comment by CarolEidt** [comment] 2019-05-06 17:03
> Whenever we see Unsafe.As used the source struct can be consider to have all overlapping fields.

We would have to be quite careful about being that conservative here, as `Unsafe.As` is used heavily in the intrinsics. Of course, in that case we don't expect to see field references.

**Comment by BruceForstall** [comment] 2019-05-08 21:05
@karelz @danmosemsft It seems like a meta-issue here is that apparently corefx testing is done using "default" coreclr optimization levels, but in the coreclr CI we specifically with with JIT tiering both default (i.e., enabled) and disabled (to force full JIT optimization). Since most unit tests probably run once and thus never get "tiered up", it's likely all corefx testing is done with the JIT in "MinOpts" or "no optimization" mode. This seems a little dangerous. You should consider adding a tiering disabled test mode in the corefx CI. As I said, coreclr CI does do this, so hopefully we're covered here, but adding one in corefx CI testing would "upstream" the check, and might be valuable.

cc @RussKeldorph

**Comment by danmosemsft** [comment] 2019-05-08 21:12
@BruceForstall that is interesting. I wonder if we can build this in in some pairwise fashion, eg., half our existing configurations one way and the other half the other.

@jkotas what are your thoughts about the risk tiering adds here - ie., that corefx tests are likely only running some code in tier 1 ? I would expect much of the implementation to go over the threshold as a test library run through it. Should we be explicitly forcing off, as well as on?

**Comment by danmosemsft** [comment] 2019-05-08 21:18
cc @kouvel

**Comment by jkotas** [comment] 2019-05-09 01:54
> @jkotas what are your thoughts about the risk tiering adds here - ie., that corefx tests are likely only running some code in tier 1 ?

Tiering is another dimension in the codegen/runtime test matrix. Yes, we need to have a plan how to cover the matrix: optimizations on/off, tiering on/off, R2R on/off, number of different hardware intrinsics combinations, different JIT and GC stress modes, across platforms and different test assets. I believe that the JIT team has a plan like that.

> You should consider adding a tiering disabled test mode in the corefx CI. 

I have not seen enough evidence that we need to a coverage for this specific mode in corefx CI. We have it covered by coreclr runs already and this issues demonstrates that it works as designed. The bugs found by this coverage are most likely going to be runtime bugs, that need to be investigate and fixed by runtime or JIT engineers, so it is more natural for it to live in coreclr, I think.

**Comment by BruceForstall** [comment] 2019-05-09 05:13
I agree with @jkotas.

> We have it covered by coreclr runs already 

My main concern is that while we do have quite a few variants of stress + corefx testing, we don't have "all" of them. E.g., no R2R-specific testing, no GCStress testing. Also, we have experienced so many "flaky" test failures with the corefx runs that I worry we will miss real bugs as we aggressively disable tests due to failure, and not get back to investigate them. Note that we have investigated failures during various "bug fix pushes". Corefx test failures that represent real product problems but which reproduce only periodically are very unlikely to be properly investigated, and are almost always closed as "didn't fail on rerun".

**Comment by ahsonkhan** [comment] 2019-05-09 06:26
> I don't see a simple fix here

> In the original corefx issue Unsafe.As is used here

I realize that the investigation is still on-going, but please let me know if an implementation change within the `ArrayBufferWriter` library would be required as a workaround to this issue (if a fix is infeasible within the next month or so).

**Comment by erozenfeld** [comment] 2019-05-09 06:37
@ahsonkhan #24482 has a fix for this issue.

**Comment by danmosemsft** [comment] 2019-05-09 09:54
> we have experienced so many "flaky" test failures with the corefx runs that I worry we will miss real bugs 

We maybe should reset this disabled list at some point. Progress has been made fixing flaky tests because we have switched off retires on inner loop tests.

**Comment by jkotas** [comment] 2019-05-09 11:13
> we have experienced so many "flaky" test failures with the corefx runs 

Majority of the flakiness and false alarms that I have seen have been caused by running mismatched or outdated bits. This should be addressed 

> We maybe should reset this disabled list at some point

Agree. Sooner rather than later. We have the new proper setup now. The disabled list for new proper setup is in https://github.com/dotnet/coreclr/blob/master/tests/CoreFX/CoreFX.issues.rsp and it is separate from the not-yet-converted runs that still use the old setup.

@davmason Do you plan to work on narrowing down the list of disabled tests as you have mentioned in 
https://github.com/dotnet/coreclr/pull/24259#issue-273716819 ? Is there a workitem tracking it?

**Comment by davmason** [comment] 2019-05-09 18:11
I did not get to it in my infrastructure sprint, so I don’t currently plan on going through the list. 

Here is an issue with the remaining work to make the CoreFX runs complete #24501

**Closed** 2019-05-10 00:16 UTC
Labels: area-CodeGen, test-corefx
