### ISSUE TITLE
GcStress: Linux: Assert failure in _il_rellcs

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2768] opened 2016-01-21 01:46 UTC
```
corerun JIT/Methodical/refany/_il_rellcs/_il_rellcs.exe
Test searches for longest common subsequence of 4 strings

Assert failure(PID 20477 [0x00004ffd], Thread: 20477 [0x4ffd]): (GetComponentSize() <= 2) || IsArray()
    File: /home/swaroops/git/a/coreclr/src/vm/methodtable.cpp Line: 7619
    Image: /home/swaroops/git/a/coreclr/bin/Product/Linux.x64.Debug/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 20477, Thread 20477/0x4ffd)' ****
  (GetComponentSize() <= 2) || IsArray()

/home/swaroops/git/a/coreclr/src/vm/methodtable.cpp, Line: 7619

Abort - Kill program
Retry - Debug
Ignore - Keep running

Image:
/home/swaroops/git/a/coreclr/bin/Product/Linux.x64.Debug/corerun

********

/home/swaroops/bin/runn: line 3: 20477 Aborted                 (core dumped) 
```

This could be related to #2765

Repro steps are:

* cp \scratch2\scratch\swaroops\coredistools\libcoredistools.so somewhere
* export LD_LIBRARY_PATH=somewhere
* export COMPlus_GCStress=0xC
* Run the above test

**Comment by sivarv** [comment] 2016-01-29 03:50
Mkrefany test.  Fix to correctly handle TypedReference will fix this.

**Comment by sivarv** [comment] 2016-01-29 04:22
This is a duplicate of #2764

**Closed by sivarv** 2016-01-29 04:22 UTC
Labels: bug, CodeGen, GCStress, Linux
