### ISSUE TITLE
Edit and Continue regression: unable to add instance and static methods

### ISSUE THREAD

**Issue by tmat** [dotnet/coreclr#26016] opened 2019-08-05 21:21 UTC
Repro:

1. Create a simple console app that targets `netcoreapp3.0`:

```C#
class Program
{
  static void Main(string[] args)
  {
      Console.WriteLine("Hello World!"); // Add a breakpoint
  }
}
```

2. Place breakpoint.
3. Start debugging and break at specific line;
4. Add a new method to the class:

```C#
static void Foo()
{ 
}
```

5. EnC will fail and the debug session will stop.

The error occurs in the runtime while applying the change.

The same repro works fine when targeting .NET Framework (net472, for example). 
I have also tried .NET Core 2.1.12 and it works there as well.

**Comment by AaronRobinsonMSFT** [comment] 2019-08-06 05:36
cc @tommcdon @gregg-miskelly

**Comment by hoyosjs** [comment] 2019-08-06 21:04
Caused by #24177. Investigating on the root cause which seems to be an AV

**Comment by hoyosjs** [comment] 2019-08-07 01:22
Looks like the function `GetThread` called by the macro `ACQUIRE_STACKING_ALLOCATOR` returns a null pointer because it is being called on a native thread which doesn't have the managed thread as a thread local variable.

**Comment by hoyosjs** [comment] 2019-08-17 00:28
Obtaining a stacking allocator pointer to pass to the method table builder in `EEClass::AddMethod` resulted in an AV after #24177. Prior to this, a compiler optimization caused it be populated as an offset from a thread-local global Thread object. However, the base pointer - the Thread pointer - was always `NULL` as this method runs on the unmanaged RC thread. A partial fix was checked in to work around the issue: using `NULL` as a stack allocator pointer. As no complaint had come in before and this is consistent with long-standing behavior, this felt like the lowest risk fix possible. 

This also affected adding instance methods but the same fix applied for both. During this investigation another point of concern came up, when trying to set the entry point for the method desc https://github.com/dotnet/coreclr/blob/b9177c03b592a0583af576530552ecca0d8b2ad9/src/vm/class.cpp#L631 we see an assert about the method trying to use a virtual slot in the method table. that being said, the method desc is then set to now use slots in the table. The assert warrants an investigation just to make sure the method table is in a consistent state.

**Closed** 2019-08-20 20:06 UTC
Labels: area-Diagnostics
