### ISSUE TITLE
ReadOnlySpan<T> ToString() leads to System.InvalidProgramException

### ISSUE THREAD

**Issue by mharthoorn** [dotnet/coreclr#15458] opened 2017-12-10 22:23 UTC
Tried out System.Memory package
https://www.nuget.org/packages/System.Memory/4.4.0-preview1-25305-02

The use of ReadOnlySpan.ToString() compiles correctly, but leads to an invalid program. 

*In Visual Studio 15.5:*
"Your app has entered a break state, but no code is currently executing that is supported by the   
selected debug engine (e.g. only native runtime code is executing)."

*dotnet cli:*
"Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program. at SpanOfTest.Program.Main(String[] args)"

Minimal example that leads to this error
```csharp
  static void Main(string[] args)
  {
      var span = "Hello world!".AsSpan();
      Console.WriteLine(span.ToString());
  }
```
(Not sure if this is the right place to post this)

**Comment by jkotas** [comment] 2017-12-11 02:24
cc @ahsonkhan

**Comment by ahsonkhan** [comment] 2017-12-11 03:28
Duplicate of https://github.com/dotnet/corefx/issues/21629?

**Comment by jkotas** [comment] 2018-01-05 22:44
Fixed by #15458

**Closed by jkotas** 2018-01-05 22:44 UTC
Labels: area-System.Memory

**Comment by ahsonkhan** [comment] 2018-01-05 23:20
This is the PR where the issue got fixed: https://github.com/dotnet/coreclr/pull/15745
