### ISSUE TITLE
[linux] corerun HelloWorld.exe 0x8007001f when connected using ssh

### ISSUE THREAD

**Issue by Piot** [dotnet/coreclr#174] opened 2015-02-09 21:48 UTC
When executing `corerun` with `HelloWorld.exe` over ssh it fails. However running from the same directory on the local console it works (however it shows the windows logo).

Can it have something to do with terminfo parsing?

### Local Console
```
$ ./corerun HelloWorld.exe 
Hello, Windows...
(Win logo)
Press ENTER to exit ...

$ echo $TERM
linux
````

### Over ssh
```
$ ./corerun HelloWorld.exe 
ExecuteAssembly failed - status: 0x8007001f

$ echo $TERM
xterm-256color
````
```
$ gdb --args ./corerun HelloWorld.exe
(gdb) run
Starting program: /home/peter/coreclr/binaries/Product/amd64/debug/corerun HelloWorld.exe
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
ExecuteAssembly failed - status: 0x8007001f
[Inferior 1 (process 6968) exited normally]
```

**Comment by kangaroo** [comment] 2015-02-09 22:01
I have run it over vagrant ssh without issue.  Can you:

export COMPlus_DumpJittedMethods=1

It would be interesting to see how far that gets.

**Comment by janvorli** [comment] 2015-02-09 22:16
I think it failed during PAL_Initialize. The error code means ERROR_GEN_FAILURE and these are errors that I have added there yesterday when something that cannot be expressed by an existing error code happens. Enabling debug channels will most likely show the culprit. You can use e.g. this:
export PAL_DBG_CHANNELS=+all.all:-VIRTUAL.TRACE

**Comment by Piot** [comment] 2015-02-09 22:18
```
$ export PAL_DBG_CHANNELS=+all.all:-VIRTUAL.TRACE
$ ./corerun HelloWorld.exe 
{0x7fce992b7780-0x7fce97d15840} ENTRY [PAL    ] at /home/peter/coreclr/src/pal/src/init/pal.cpp.245: PAL_Initialize(argc = 1 argv = 96394630)
{0x7fce992b7780-0x7fce97d15840} TRACE [UNICODE] at CODEPAGEInit.231: CODEPAGEInit( void )
{0x7fce992b7780-0x7fce97d15840} ERROR [PAL    ] at PAL_Initialize.263: Unable to initialize the locks or the codepage.
{0x7fce992b7780-0x7fce97d15840} EXIT  [PAL    ] at /home/peter/coreclr/src/pal/src/init/pal.cpp.589: PAL_Initialize returns int -1
{0x7fce992b7780-0x7fce97d15840} ENTRY [MISC   ] at /home/peter/coreclr/src/pal/src/misc/error.cpp.103: GetLastError ()
{0x7fce992b7780-0x7fce97d15840} EXIT  [MISC   ] at /home/peter/coreclr/src/pal/src/misc/error.cpp.115: GetLastError returns 31
ExecuteAssembly failed - status: 0x8007001f
```

**Comment by Piot** [comment] 2015-02-09 22:20
@kangaroo `export COMPlus_DumpJittedMethods=1` didn't show any extra information. But good to know in the future.

**Comment by janvorli** [comment] 2015-02-09 22:31
There were no methods jitted yet, hence no extra information showed with the COMPlus_DumpJittedMethods set.
The issue is that the codepage initialization has failed. Based on the debug dump, I believe the `setlocale( LC_CTYPE, "" )` returned `NULL`.
Looking at the man page of the `setlocale`, it says:
> If locale is an empty string, "", each part of the locale that should
       be modified is set according to the environment variables.  The
       details are implementation-dependent.  For glibc, first (regardless
       of category), the environment variable LC_ALL is inspected, next the
       environment variable with the same name as the category (see the
       table above), and finally the environment variable LANG.  The first
       existing environment variable is used.  If its value is not a valid
       locale specification, the locale is unchanged, and setlocale()
       returns NULL.

So I guess your SSH session somehow doesn't set any of the locale env variables.

**Comment by cnblogs-dudu** [comment] 2015-02-10 09:51
`export LC_ALL=en_US.UTF-8` can fix it.
`export LC_ALL=zh_CN.UTF-8` can reproduce it.

**Comment by Piot** [comment] 2015-02-11 19:29
It is related to the `Set locale environment variables on startup` checkbox in Mac OS X.

If checked (not working):
```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```

If unchecked (working):

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```

![locale_environment](https://cloud.githubusercontent.com/assets/544158/6154424/e7d29af0-b22b-11e4-9001-49964e9331fb.png)

**Comment by kangaroo** [comment] 2015-02-12 03:47
@janvorli Should we just fall back to the C locale in this case?

**Comment by kangaroo** [comment] 2015-02-12 03:54
On OS X we probably want to probe CFLocale in the GetUserDefaultLCID rather than rely on the environment variable as well.

**Comment by janvorli** [comment] 2015-02-12 10:13
@kangaroo I can see that at other place, in the locale.cpp we are using `querylocale` if the platform provides that instead of the `setlocale`.
```c
        /* get current locale */
#if HAVE_XLOCALE
        lpCurrentLocale = querylocale(LC_CTYPE_MASK, LC_GLOBAL_LOCALE);
#else // HAVE_XLOCALE
        lpCurrentLocale = setlocale(LC_CTYPE,NULL);
#endif // HAVE_XLOCALE
```
It seems that OSX has `querylocale`. Could you please try if using this in the unicode.cpp would work on OSX?

**Comment by kangaroo** [comment] 2015-02-12 15:43
@janvorli We're already using that on OS X:

basalt:src plasma$ grep -r HAVE_XLOCALE config.h.osx
#define HAVE_XLOCALE 1

**Comment by kangaroo** [comment] 2015-02-12 16:10
It might be worthwhile to spend some time looking at Apple's implementation:

http://www.opensource.apple.com/source/Libc/Libc-1044.1.2/locale/FreeBSD/

**Comment by janvorli** [comment] 2015-02-12 16:56
@kangaroo I meant using it in the `BOOL CODEPAGEInit( void )`. The code there uses the `setlocale` only and that's where I believe the initialization fails:
```c
BOOL CODEPAGEInit( void )
{
    BOOL bRetVal = FALSE;

    TRACE( "CODEPAGEInit( void )\n" );
    /* Init the rwlock. */
    if ( 0 != pthread_rwlock_init( &lock, NULL ) )
    {
    ERROR( "Unable to init the read write lock! Reason %s(%d)\n",
        strerror( errno ), errno );
    }
#if !HAVE_COREFOUNDATION
    else
    {
        /* get the systems code page. */
        LPSTR lpCodePage = setlocale( LC_CTYPE, "" );
```

**Comment by janvorli** [comment] 2015-02-12 16:57
As for looking at the Apple's implementation, I will need to get approval for that first. We are not allowed to look at any open source stuff without that.

**Comment by kangaroo** [comment] 2015-02-12 17:01
@janvorli Understood on the approval.  For your reference their libc is  APSL 2 licensed.

w.r.t CODEPAGEInit we currently:

#define HAVE_COREFOUNDATION 1

so we don't fall into that code path.

**Comment by janvorli** [comment] 2015-02-12 17:15
@kangaroo I see, that's strange then. From Piot's log posted here before, I can see this:
`PAL_Initialize.263: Unable to initialize the locks or the codepage.`
This message is produced here:
```c
        if( !CODEPAGEInit() )
        {
            ERROR( "Unable to initialize the locks or the codepage.\n" );
            goto done;
        }
```
And if the `HAVE_COREFOUNDATION` was really set, then the method would never return`FALSE` even if the lock initialization failed.

**Comment by kangaroo** [comment] 2015-02-12 18:56
@janvorli The original bug is tagged [linux], perhaps the log form @Piot is from there?  also see:

'''
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
'''

I think this issue is conflating two different sub-issues.

**Comment by janvorli** [comment] 2015-02-12 20:20
@kangaroo Ah, I am sorry, I was confused by the fact that @piot was talking about the Mac OSX settings dialog.

**Comment by Piot** [comment] 2015-02-12 21:43
Yes, sorry for the confusion @kangaroo and @janvorli. I was using ssh from OS X to Ubuntu and was running the corerun on Ubuntu.

**Comment by MattWhilden** [comment] 2015-04-03 18:10
Just coming by to bump old issues. Checking back to see if this is resolved by now.

**Comment by janvorli** [comment] 2015-10-28 23:01
There is no code dealing with codepages in PAL anymore, so I am closing the issue.

**Closed by janvorli** 2015-10-28 23:01 UTC
Labels: PAL
