### ISSUE TITLE
Regressions from switching corelib to R2R

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#22128] opened 2019-01-22 17:24 UTC
We have enough perf history now that we can call out a few regressions from #21497, where corelib prejitting was changed from fragile ngen to R2R.

Crypto regressed ~4% on windows (505 -> 525) and ~6% on linux (515 -> 545)

![image](https://user-images.githubusercontent.com/10121823/51552537-a0afa680-1e25-11e9-939e-e2dc80a6c3da.png)

Csc/Dataflow regressed ~5% on windows (413 -> 432) and ~5% on linux (450 -> 470, noisy)

![image](https://user-images.githubusercontent.com/10121823/51552694-fd12c600-1e25-11e9-9df6-23e5bc9d75fa.png)

PerfLab / GetMethod20 regressed ~7% (3.52 -> 3.72). The other GetMethod tests regressed as well.

![image](https://user-images.githubusercontent.com/10121823/51553153-051f3580-1e27-11e9-952a-d7109e640b59.png)

There may be some other cases that turn up -- will add them here.

cc @fadimounir

**Comment by jkotas** [comment] 2019-01-22 17:55
@AndyAyersMS Are these numbers with Tiered JITing on - do the compute intensive benchmarks (crypto, GetMethod20) allow for the system to warm up and the Tiered JIT to kick in?

**Comment by AndyAyersMS** [comment] 2019-01-22 17:58
I think these all still run with tiering disabled -- @jorive can confirm.

**Comment by jkotas** [comment] 2019-01-22 18:32
I would primarily interested in cases where switch to R2R regressed perf and tiered JITing does not recover the regression. Do we have any cases like that? Those would be P1 to look into.

The regressions in compute intensive benchmarks with R2R and tiered JITing disable are P2. We can look at them to see whether it is something easy to fix, but we know that the R2R is not perfect by design. We expect tiered JIT to recover the loss and in places to generate even better code than what fragile NGen for CoreLib ever had.

**Comment by jorive** [comment] 2019-01-22 18:39
I was looking at the script/configuration on how those results are measured. In this case, the tests run with ful_opt: `COMPlus_TieredCompilation=0`. It's set [here](https://github.com/dotnet/coreclr/blob/master/tests/scripts/run-xunit-perf.py#L460), and specified by the CI script [here](https://github.com/dotnet/coreclr/blob/master/perf.groovy#L34).
Currently, the performance micro benchmarks are not running with tiering enabled.

**Comment by jkotas** [comment] 2019-01-22 18:46
> the performance micro benchmarks are not running with tiering enabled

It means that we are not measuring the performance that our customers are going to see in default configuration. Do we have a plan/issue to fix this?

**Comment by sergiy-k** [comment] 2019-01-22 18:49
+1. I was going to ask the same question as @jkotas. Was it intentional to turn Tiered JIT'ing off?
Regardless, I'll ask @fadimounir to take a look when he is back from vacation at least to understand the problem.

**Comment by jorive** [comment] 2019-01-22 19:02
@jkotas essentially, micro benchmarks run multiple iterations within a loop, and discard the warmup iteration. Thus, most of them do not report tiering information. For tier jitting we use real-world scenarios such as JitBench/MusicStore.
But I agree we should be running the default configuration we are shipping, so feel free to open an issue or send a PR.

**Comment by benaadams** [comment] 2019-01-22 20:46
There was a regression in ASP.NET Core db benchmarks around the same time; but could just be coincidence? https://github.com/aspnet/Benchmarks/issues/607

![image](https://user-images.githubusercontent.com/1142958/51564263-adb0b200-1e86-11e9-885b-1cc1c8ad6964.png)

Didn't seem to effect the non-Db benchmarks

/cc @sebastienros

**Comment by benaadams** [comment] 2019-01-22 20:56
Note ASP.NET Core took a while get a continuous updating runtime flow working, so its also a jump in versions between before and after (27219-3 => 27317-3) 😢

**Comment by jkotas** [comment] 2019-01-22 22:30
> I agree we should be running the default configuration we are shipping, so feel free to open an issue

#22134

**Comment by fadimounir** [comment] 2019-06-17 20:06
Closing along with #23640

**Closed by fadimounir** 2019-06-17 20:06 UTC
Labels: area-ReadyToRun, tenet-performance-benchmarks
