### ISSUE TITLE
Test failure in tracing\runtimeeventsource\runtimeeventsource\runtimeeventsource.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19340] opened 2018-08-07 21:39 UTC
There is a recent regression in tracing\runtimeeventsource\runtimeeventsource\runtimeeventsource.cmd in (at least?) the Window x64 zapdisable test leg, run with:

```
COMPlus_TieredCompilation=0 
COMPlus_ZapDisable=1
COMPlus_ReadyToRun=0 
```

starting with:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_zapdisable/586/

```
      tracing_runtimeeventsource._runtimeeventsource_runtimeeventsource_._runtimeeventsource_runtimeeventsource_cmd [FAIL]
        
  Unhandled Exception: System.Exception: Condition 'listener.EventCount > 0' is not true
           at Tracing.Tests.Common.Assert.True(String name, Boolean condition) in D:\j\workspace\x64_checked_w---fa5d14d7\tests\src\tracing\common\Assert.cs:line 11
           at Tracing.Tests.RuntimeEventSourceTest.Main(String[] args) in D:\j\workspace\x64_checked_w---fa5d14d7\tests\src\tracing\runtimeeventsource\RuntimeEventSourceTest.cs:line 44
  
  
  Return code:      1
  Raw output file:      D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\Reports\tracing.runtimeeventsource\runtimeeventsource\runtimeeventsource.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x64_checked_w---fa5d14d7\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" runtimeeventsource.exe 
        [Simple] ThreadID = 5928 ID = 200 Name = IncreaseMemoryPressure
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.7268529
        	Name = "BytesAllocated" Value = "3984"
        	Name = "ClrInstanceID" Value = "0"
        
  
        [Simple] ThreadID = 5928 ID = 70 Name = ThreadCreating
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.9582825
        	Name = "ID" Value = "1763982960"
        	Name = "ClrInstanceID" Value = "0"
        
  
        [Simple] ThreadID = 7124 ID = 10 Name = GCAllocationTick_V3
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.6601227
        	Name = "AllocationAmount" Value = "104712"
        	Name = "AllocationKind" Value = "0"
        	Name = "ClrInstanceID" Value = "0"
        	Name = "AllocationAmount64" Value = "104712"
        	Name = "TypeID" Value = "1787297752"
        	Name = "TypeName" Value = "System.Object"
        	Name = "HeapIndex" Value = "0"
        	Name = "Address" Value = "2396152"
        
  
        [Simple] ThreadID = 2872 ID = 85 Name = ThreadCreated
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.6193479
        	Name = "ManagedThreadID" Value = "1763982960"
        	Name = "AppDomainID" Value = "1723735920"
        	Name = "Flags" Value = "0"
        	Name = "ManagedThreadIndex" Value = "7"
        	Name = "OSThreadID" Value = "2872"
        	Name = "ClrInstanceID" Value = "0"
        
  
        [Simple] ThreadID = 2872 ID = 71 Name = ThreadRunning
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.6194882
        	Name = "ID" Value = "1763982960"
        	Name = "ClrInstanceID" Value = "0"
        
  
        [Simple] ThreadID = 2872 ID = 145 Name = MethodJittingStarted_V1
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.6193243
        	Name = "MethodID" Value = "1791492016"
        	Name = "ModuleID" Value = "1785724832"
        	Name = "MethodToken" Value = "100670965"
        	Name = "MethodILSize" Value = "133"
        	Name = "MethodNamespace" Value = "System.Diagnostics.Tracing.EventPipeEventDispatcher"
        	Name = "MethodName" Value = "TimeStampToDateTime"
        	Name = "MethodSignature" Value = "instance value class System.DateTime  (int64)"
        	Name = "ClrInstanceID" Value = "0"
        
  
        [Simple] ThreadID = 2872 ID = 143 Name = MethodLoadVerbose_V2
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.6150592
        	Name = "MethodID" Value = "1791492016"
        	Name = "ModuleID" Value = "1785724832"
        	Name = "MethodStartAddress" Value = "1792016304"
        	Name = "MethodSize" Value = "264"
        	Name = "MethodToken" Value = "100670965"
        	Name = "MethodFlags" Value = "8"
        	Name = "MethodNamespace" Value = "System.Diagnostics.Tracing.EventPipeEventDispatcher"
        	Name = "MethodName" Value = "TimeStampToDateTime"
        	Name = "MethodSignature" Value = "instance value class System.DateTime  (int64)"
        	Name = "ClrInstanceID" Value = "0"
        	Name = "ReJITID" Value = ""
        
  
        [Simple] ThreadID = 2872 ID = 190 Name = MethodILToNativeMap
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.6151830
        	Name = "MethodID" Value = "1791492016"
        	Name = "ReJITID" Value = "0"
        	Name = "MethodExtent" Value = "0"
        	Name = "CountOfMapEntries" Value = "15"
        
  
        [Simple] ThreadID = 2872 ID = 145 Name = MethodJittingStarted_V1
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.6200239
        	Name = "MethodID" Value = "1792540664"
        	Name = "ModuleID" Value = "1785724832"
        	Name = "MethodToken" Value = "100670993"
        	Name = "MethodILSize" Value = "892"
        	Name = "MethodNamespace" Value = "System.Diagnostics.Tracing.EventPipePayloadDecoder"
        	Name = "MethodName" Value = "DecodePayload"
        	Name = "MethodSignature" Value = "class System.Object[]  (value class EventMetadata&,value class System.ReadOnlySpan`1<unsigned int8>)"
        	Name = "ClrInstanceID" Value = "0"
        
  
        [Simple] ThreadID = 2872 ID = 143 Name = MethodLoadVerbose_V2
        TimeStamp: 8/2/2018 7:09:15 AM
        LocalTime: 8/2/2018 7:09:19 AM
        Difference: 00:00:03.4660610
        	Name = "MethodID" Value = "1792540664"
        	Name = "ModuleID" Value = "1785724832"
        	Name = "MethodStartAddress" Value = "1792016368"
        	Name = "MethodSize" Value = "2299"
        	Name = "MethodToken" Value = "100670993"
        	Name = "MethodFlags" Value = "8"
        	Name = "MethodNamespace" Value = "System.Diagnostics.Tracing.EventPipePayloadDecoder"
        	Name = "MethodName" Value = "DecodePayload"
        	Name = "MethodSignature" Value = "class System.Object[]  (value class EventMetadata&,value class System.ReadOnlySpan`1<unsigned int8>)"
        	Name = "ClrInstanceID" Value = "0"
        	Name = "ReJITID" Value = ""
        
  
        Expected: 100
        Actual: -532462766
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\tracing\runtimeeventsource\runtimeeventsource\runtimeeventsource.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\TestWrappers\tracing.runtimeeventsource\tracing.runtimeeventsource.XUnitWrapper.cs(109,0): at tracing_runtimeeventsource._runtimeeventsource_runtimeeventsource_._runtimeeventsource_runtimeeventsource_cmd()
```

**Comment by RussKeldorph** [comment] 2018-08-07 22:10
Duplicate of #19268?

**Comment by BruceForstall** [comment] 2018-08-07 22:27
Looks like it. @brianrob can decide.

**Comment by brianrob** [comment] 2018-08-07 22:59
It could be, but I'm not sure.  Let's keep this open for now.  I'm currently investigating #19268, and so far that only repros in Helix, and I can't yet explain what's happening.

**Comment by BruceForstall** [comment] 2018-08-08 05:16
@brianrob FWW, it looks like this test fails on Ubuntu arm32 as well:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_debug_ubuntu_tst/116/consoleText

```
FAILED   - tracing/runtimeeventsource/runtimeeventsource/runtimeeventsource.sh
               BEGIN EXECUTION
               /ssd/j/workspace/dotnet_coreclr/master/arm_cross_debug_ubuntu_tst/bin/tests/Linux.arm.Debug/Tests/Core_Root/corerun runtimeeventsource.exe
               [Simple] ThreadID = 12688 ID = 85 Name = ThreadCreated
               TimeStamp: 8/7/2018 5:00:11 PM
               LocalTime: 8/7/2018 5:00:13 PM
               
               Unhandled Exception: Difference: 00:00:02.0909010
               	Name = "ManagedThreadID" Value = "2899335424"
               	Name = "AppDomainID" Value = "398264"
               	Name = "Flags" Value = "4"
               	Name = "ManagedThreadIndex" Value = "5"
               	Name = "OSThreadID" Value = "12688"
               	Name = "ClrInstanceID" Value = "0"
               
               
               [Simple] ThreadID = 12688 ID = 10 Name = GCAllocationTick_V3
               TimeStamp: 8/7/2018 5:00:11 PM
               LocalTime: 8/7/2018 5:00:13 PM
               Difference: 00:00:02.1440494
               	Name = "AllocationAmount" Value = "103340"
               	Name = "AllocationKind" Value = "0"
               	Name = "ClrInstanceID" Value = "0"
               	Name = "AllocationAmount64" Value = "103340"
               	Name = "TypeID" Value = "-1273547244"
               	Name = "TypeName" Value = "System.Object[]"
               	Name = "HeapIndex" Value = "0"
               	Name = "Address" Value = "-1318523728"
               
               
               [Simple] ThreadID = 12688 ID = 200 Name = IncreaseMemoryPressure
               TimeStamp: 8/7/2018 5:00:11 PM
               LocalTime: 8/7/2018 5:00:13 PM
               Difference: 00:00:02.1579725
               	Name = "BytesAllocated" Value = "2304"
               	Name = "ClrInstanceID" Value = "0"
               
    .... and a LOT more...
```

**Comment by shimingsg** [comment] 2018-10-19 08:55
also failed in CI job https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_zapdisable_tst/598/

tracing_runtimeeventsource._runtimeeventsource_runtimeeventsource_._runtimeeventsource_runtimeeventsource_sh [FAIL]
        
        Unhandled Exception: System.Exception: Condition 'listener.EventCount > 0' is not true
           at Tracing.Tests.Common.Assert.True(String name, Boolean condition) in /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/tests/src/tracing/common/Assert.cs:line 15
           at Tracing.Tests.RuntimeEventSourceTest.Main(String[] args) in /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/tests/src/tracing/runtimeeventsource/RuntimeEventSourceTest.cs:line 35
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_zapdisable_tst/bin/tests/Linux.x64.Checked/tracing/runtimeeventsource/runtimeeventsource/runtimeeventsource.sh: line 251: 116302 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
        /n/nReturn code:      1

**Comment by brianrob** [comment] 2018-10-19 20:13
Moving to @noahfalk who owns this area now.

**Comment by noahfalk** [comment] 2018-10-19 22:01
@jorive is on point for these at the moment actually

**Comment by sandreenko** [comment] 2019-01-24 19:21
@jorive @noahfalk could you please exclude this test until this issue is fixed?
It will make this [job ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_zapdisable/)happy.

**Comment by jorive** [comment] 2019-02-13 04:17
@sandreenko Looking into it.

**Comment by jorive** [comment] 2019-02-27 21:43
Test disabled with https://github.com/dotnet/coreclr/pull/22899

**Closed by jorive** 2019-02-27 21:43 UTC
Labels: area-Tracing, test bug
