### ISSUE TITLE
GcStress: Exclude doublearray/* Tests from GcStress runs

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2759] opened 2016-01-21 00:19 UTC
Exception failure in the following tests
JIT/Methodical/doublearray/dblarray1_cs_d/dblarray1_cs_d.exe
JIT/Methodical/doublearray/dblarray1_cs_r/dblarray1_cs_r.exe
JIT/Methodical/doublearray/dblarray2_cs_d/dblarray2_cs_d.exe
JIT/Methodical/doublearray/dblarray2_cs_r/dblarray2_cs_r.exe
JIT/Methodical/doublearray/dblarray3_cs_d/dblarray3_cs_d.exe
JIT/Methodical/doublearray/dblarray3_cs_r/dblarray3_cs_r.exe
JIT/Methodical/doublearray/dblarray4_cs_d/dblarray4_cs_d.exe
JIT/Methodical/doublearray/dblarray4_cs_r/dblarray4_cs_r.exe

All the tests had a similar failure/output.

```
corerun JIT/Methodical/doublearray/dblarray1_cs_d/dblarray1_cs_d.exe
Generation 2
Exception of type 'System.Exception' was thrown.
   at DblArray1.f0()
   at DblArray1.Main()
FAILED

// Goal: Test arrays of doubles are allocated on large object heap and therefore 8 byte aligned
// Assumptions:
// 1) large object heap is always 8 byte aligned
// 2) double array greater than 1000 elements is on large object heap
// 3) non-double array greater than 1000 elements but less than 85K is NOT on large object heap
// 4) new arrays allocated in large object heap is of generation 2
// 5) new arrays NOT allocated in large object heap is of generation 0 
```

**Comment by swaroop-sridhar** [comment] 2016-01-21 00:27
Repro steps are:

* Enlist adityamandaleeka/coreclr:gc_stress and build CoreCLR
* cp \scratch2\scratch\swaroops\coredistools\libcoredistools.so somewhere
* export LD_LIBRARY_PATH=somewhere
* export COMPlus_GCStress=0xC
* Run the test below

**Comment by sivarv** [comment] 2016-01-21 18:31
These test failures are by design under gc-stress.  In fact these were tagged on desktop to be excluded from gcstress=0xc runs.  Moving this to future to tag these tests to be excluded from gc-stress runs.

**Closed** 2016-03-15 14:17 UTC
Labels: 2 - In Progress, CodeGen, GCStress, Linux, Test-Issue
