### ISSUE TITLE
Test failed: JIT_Directed._PREFIX_unaligned_1_arglist_arglist_._PREFIX_unaligned_1_arglist_arglist_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25411] opened 2019-06-26 02:12 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-ci/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190625.38/workItem/JIT.Directed/analysis/xunit/JIT_Directed._PREFIX_unaligned_1_arglist_arglist_~2F_PREFIX_unaligned_1_arglist_arglist_cmd

**Failed tests:**
JIT_Directed._PREFIX_unaligned_1_arglist_arglist_._PREFIX_unaligned_1_arglist_arglist_cmd

**Log:**
```
Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\2c1b9a21-57d8-4631-be8d-e7184ccef280\\Exec\\JIT\\Directed\\Reports\\JIT.Directed\\PREFIX\\unaligned\\1\\arglist\\arglist.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload\\corerun.exe\" arglist.exe 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload
> C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\2c1b9a21-57d8-4631-be8d-e7184ccef280\\Exec\\JIT\\Directed\\PREFIX\\unaligned\\1\\arglist\\arglist.cmd
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment] 2019-06-26 16:23
Related to https://github.com/dotnet/coreclr/pull/25429?

**Comment by RussKeldorph** [comment] 2019-06-26 23:56
Assuming duplicate of #25376

**Closed by RussKeldorph** 2019-06-26 23:56 UTC
Labels: arch-arm32, os-windows
