### ISSUE TITLE
java.io.IOException: Failed to mkdirs

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#21952] opened 2019-01-11 06:58 UTC
failed in job: 
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_linux_arm_flow/1322/
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_linux_x64_flow/1325/

failed log:
Building remotely on win201-528f87 (win2012-20180911) in workspace D:\j\w\perf_throughp---03c540a2@94
[WS-CLEANUP] Deleting project workspace...
java.io.IOException: Failed to mkdirs: D:\j\w\perf_throughp---03c540a2@94
	at hudson.FilePath.mkdirs(FilePath.java:1170)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1200)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1724)
	at com.cloudbees.plugins.flow.FlowRun.run(FlowRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

**Comment by AaronRobinsonMSFT** [comment] 2019-01-14 05:20
@RussKeldorph and @jashook This seems like a flakey Jenkins issue. Is this really something we can do anything about?

**Comment by RussKeldorph** [comment] 2019-01-14 12:34
@AaronRobinsonMSFT Jenkins issues will be with us as long as we're on it, but that will likely change in the near future when we switch to Azure DevOps.  We could see similar issues there since any system is going to have a certain spurious failure rate, but hopefully it's better.

**Comment by AaronRobinsonMSFT** [comment] 2019-01-14 16:51
@RussKeldorph Sorry, you might be misunderstanding my question. Is there anything we can do if this happens in Jenkins other than restart the CI - i..e should this issue be closed because it isn't something we can control?

**Comment by RussKeldorph** [comment] 2019-01-14 17:01
@AaronRobinsonMSFT The individual job is not recoverable AFAIK, if that's what you're asking.  Yes, you should just re-run the job and hope for the best if you need the results.

In theory the issue is not useless because there is absolutely "something we can do about it," which would be to prevent it from happening by investigating what went wrong and preventing it from happening in the future.  We aren't going to do that, though, so closing it "won't fix" is probably the best thing to do for now.

**Comment by AaronRobinsonMSFT** [comment] 2019-01-14 17:50
@RussKeldorph Thanks for the clarification. 👍 

Closing.

**Closed by AaronRobinsonMSFT** 2019-01-14 17:50 UTC
Labels: area-Infrastructure, bug
