### ISSUE TITLE
'Inspecting the state of an object in the debuggee of type System.Type' error for non-reflection related type

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#11580] opened 2017-05-12 22:58 UTC
I was debugging a C# project of my own recently. I noticed that variables of type X were being stringified to the fully qualified name of X in the debugger, e.g. `{PolynomialReducer.CompactR.Polynomial}`, even though I had overriden `ToString()` for X. Forcing evaluation via putting `[DebuggerDisplay("{ToString()}")]` on top of X gave this error:

<img width="382" alt="isoot_systemtype_nsitc" src="https://cloud.githubusercontent.com/assets/9159214/26019608/98985eb6-3744-11e7-9c64-2e0b4daeb7d8.PNG">

The full error message was `Inspecting the state of an object in the debuggee of type System.Type is not supported in this context.` I thought it was strange because the type is not remotely related to reflection, it is a custom type that lives in my library. Why does this happen?

**Additional info:** Trying to call `ToString()` on the variables via the Immediate Window also gives this error message.

**Related issue:** https://github.com/dotnet/coreclr/issues/4734

**Comment by karelz** [comment] 2017-05-13 04:46
@jamesqo which version of .NET Core? 2.0?

**Comment by gkhanna79** [comment] 2017-05-14 15:43
@noahfalk @lt72 PTAL and move to VS Debugger if applicable. Also, please rest the milestone as appropriate.

**Comment by noahfalk** [comment] 2017-05-15 20:32
@gregg-miskelly @plnelson -  does one of you know under what conditions VS reports that error condition @jamesqo described above?

**Comment by gregg-miskelly** [comment] 2017-05-15 20:52
I believe this would happen if:
1. We are in a situation where we can't do a real function evaluation (ex: top frame of the call stack is optimized and not stopped at a safe spot, or a func eval has already timed out)
2. Something in the code being interpreted calls a method on an existing System.Type object

**Comment by plnelson** [comment] 2017-05-15 20:55
Gregg is correct.  To help narrow down what's going on can you let us know if `Polynomial` is a struct (vs. class)?  Also is it possible to share a minimal set of code that reproduces the problem?

**Comment by karelz** [comment] 2017-05-23 01:08
@noahfalk can you please chime in why you moved it to 2.1?

**Comment by karelz** [comment] 2017-05-23 01:09
@jamesqo will you have time to provide more details?

**Comment by noahfalk** [comment] 2017-05-23 01:50
Oh I was just guessing that 2.1 was the right place for issues at this point, feel free to make it 2.0 again if you think it should be.

**Comment by karelz** [comment] 2017-05-23 08:33
@noahfalk I let you as area owner decide - it would be nice to have some explanation why something is moved to next release (maybe corner case scenario / pre-existing bugs, etc.)

**Comment by noahfalk** [comment] 2017-05-23 12:21
Sure thing, I'll include a note in the future when I change it. For now I think the best next step is to get more details so we can localize what the problem is and what product (VS/CLR/other) any potential change would go into. At that point we can certainly revisit what is the most appropriate milestone for the work.

**Comment by noahfalk** [comment] 2018-03-14 01:35
There hasn't been any activity here in a long time so I am going to close the issue. We can reopen if needed. Next steps appeared to be getting more details about the code being run, ideally a small app that can reproduce the problem.

**Closed by noahfalk** 2018-03-14 01:35 UTC
Labels: area-Diagnostics, bug
