### ISSUE TITLE
Backward compat issue using RyuJIT

### ISSUE THREAD

**Issue by rominator1983** [dotnet/coreclr#3130] opened 2016-02-11 12:35 UTC
It seems that the issue found at https://connect.microsoft.com/VisualStudio/Feedback/Details/1602437 has not been addressed at the moment. Attached there are some simple repro-files.

Can anyone confirm that this issue is either fixed or still present?

kind regards

**Comment by redknightlois** [comment] 2016-02-11 17:16
It is still there... it is a codegen issue. 

This is simplier (less variables repro).
```csharp
public const int I = 1;
public static void Main(string[] args)
{
    int[] arr = new int[3];
    arr[I] = -7777777;
    arr[I] = arr[I] > 0 ? arr[I] + 5 : arr[I] - 5;        
    Console.WriteLine(arr[I]);
}
```
The issue is caused by improperly tracking the correct register to send to the Console.WriteLine call.  

Codegen error:
```asm
            arr[I] = -7777777;
00007FF9008D3418  mov         ecx,dword ptr [rax+8]  
00007FF9008D341B  mov         dword ptr [rax+14h],0FF89520Fh  
00007FF9008D3422  mov         rcx,rax  
            arr[I] = arr[I] > 0 ? arr[I] + 5 : arr[I] - 5;
00007FF9008D3425  mov         ecx,dword ptr [rcx+14h]  
00007FF9008D3428  test        ecx,ecx  
00007FF9008D342A  jg          00007FF9008D3431  
00007FF9008D342C  lea         edx,[rcx-5]  
00007FF9008D342F  jmp         00007FF9008D3434  
00007FF9008D3431  lea         edx,[rcx+5]  
00007FF9008D3434  mov         dword ptr [rax+14h],edx  
            Console.WriteLine(arr[I]);
00007FF9008D3437  call        00007FF9666C85D8  
```

Now this is the correct code:

```asm
            arr[I] = -7777777;
00007FF900903418  mov         ecx,dword ptr [rax+8]  
00007FF90090341B  mov         dword ptr [rax+14h],0FF89520Fh  
            if (arr[I] <= 0)
00007FF900903422  mov         ecx,dword ptr [rax+14h]  
00007FF900903425  test        ecx,ecx  
00007FF900903427  jg          00007FF900903431  
                arr[I] = arr[I] - 5;            
00007FF900903429  add         ecx,0FFFFFFFBh  
00007FF90090342C  mov         dword ptr [rax+14h],ecx  
00007FF90090342F  jmp         00007FF900903437  
            else
                arr[I] = arr[I] + 5;
00007FF900903431  add         ecx,5  
00007FF900903434  mov         dword ptr [rax+14h],ecx  

            Console.WriteLine(arr[I]);
00007FF900903437  mov         ecx,dword ptr [rax+14h]  
00007FF90090343A  call        00007FF9665085D8  
```

Notice in the failure case the JIT is optimizing away the move of the data to the ecx register (correct is in the edx register), which means that it will have an improper value sent to the Console.WriteLine(I) call. Moreover in the correct case the instruction at 00007FF900903437 is useless and potentially costly as it will probably cause a stall in the pipeline because of the data hazard. --- need to check that under a profiler to be sure, that is why I said probably.

**Comment by mikedn** [comment] 2016-02-11 19:49
> It is still there... it is a codegen issue. This is simplier (less variables repro).

I can't seem to reproduce this issue in the current CoreCLR build. The generated code is:
```
G_M45811_IG01:
       4883EC28             sub      rsp, 40

G_M45811_IG02:
       48B9425CF8D9FB7F0000 mov      rcx, 0x7FFBD9F85C42
       BA03000000           mov      edx, 3
       E898EF3A5F           call     CORINFO_HELP_NEWARR_1_VC
       8B5008               mov      edx, dword ptr [rax+8]
       C740140F5289FF       mov      dword ptr [rax+20], -0x76ADF1
       488BD0               mov      rdx, rax
       8B5214               mov      edx, dword ptr [rdx+20]
       85D2                 test     edx, edx
       7F05                 jg       SHORT G_M45811_IG03
       8D4AFB               lea      ecx, [rdx-5]
       EB03                 jmp      SHORT G_M45811_IG04

G_M45811_IG03:
       8D4A05               lea      ecx, [rdx+5]

G_M45811_IG04:
       894814               mov      dword ptr [rax+20], ecx
       8B4014               mov      eax, dword ptr [rax+20]

G_M45811_IG05:
       4883C428             add      rsp, 40
       C3                   ret
```

> is useless and potentially costly as it will probably cause a stall in the pipeline because of the data hazard

Unlikely, store forwarding should take care of that.

**Comment by redknightlois** [comment] 2016-02-11 20:19
I am not at the office now but I think i have run that on the latest build. But may have run it in x86 rc- update1 if I made a mistake.

**Comment by redknightlois** [comment] 2016-02-11 23:13
@mikedn Looking at that code, there is no call there to Console.WriteLine() therefore you wont see the issue. The issue is the optimization that happens right before the call (passing parameters to ```Console.WriteLine(arr[I]);```).

On the other hand, unless I have understood it unproperly (article is detailed but not so easy to follow), the penalty even with store forwarding is 5 clock ticks against 1 for independent reads (no L1 hit access required because it is already in the register). [1] 

[1] http://blog.stuffedcow.net/2014/01/x86-memory-disambiguation/

**Comment by mikedn** [comment] 2016-02-12 06:34
> Looking at that code, there is no call there to Console.WriteLine() therefore you wont see the issue. 

Even if I add back Console.WriteLine I still can't reproduce the problem:

```
G_M45811_IG01:
       4883EC28             sub      rsp, 40

G_M45811_IG02:
       48B9425CDFF7FF7F0000 mov      rcx, 0x7FFFF7DF5C42
       BA03000000           mov      edx, 3
       E898EF385F           call     CORINFO_HELP_NEWARR_1_VC
       8B4808               mov      ecx, dword ptr [rax+8]
       C740140F5289FF       mov      dword ptr [rax+20], -0x76ADF1
       488BC8               mov      rcx, rax
       8B4914               mov      ecx, dword ptr [rcx+20]
       85C9                 test     ecx, ecx
       7F05                 jg       SHORT G_M45811_IG03
       8D51FB               lea      edx, [rcx-5]
       EB03                 jmp      SHORT G_M45811_IG04

G_M45811_IG03:
       8D5105               lea      edx, [rcx+5]

G_M45811_IG04:
       895014               mov      dword ptr [rax+20], edx
       8B4814               mov      ecx, dword ptr [rax+20]
       E8412E335E           call     System.Console:WriteLine(int)
       90                   nop

G_M45811_IG05:
       4883C428             add      rsp, 40
       C3                   ret
```

>  the penalty even with store forwarding is 5 clock ticks against 1 for independent reads (no L1 hit access required because it is already in the register

I'm not saying that the redundant load has no cost, it's just that store forwarding should avoid the full cost of a "true" data hazard. It really depends what you mean by data hazard, if you include all read-after-write scenarios or only those where store forwarding is blocked due to whatever reasons (alignment, mismatched size etc.). Anyway, this is an optimization issue unrelated to the bug. In general, the JIT doesn't do a lot when it comes to load/stores. If it would do that then the whole code would reduce to `Console.WriteLine(-7777782)`.

**Comment by rominator1983** [comment] 2016-02-12 08:33
Thanks for looking into this! I appreciate it!

**Comment by erozenfeld** [comment] 2016-02-13 03:29
I checked and I get the same correct code as @mikedn with current CoreCLR sources.

**Comment by erozenfeld** [comment] 2016-02-13 03:41
@redknightlois Can you please specify what version of RyuJit you used to get the incorrect code? The bug mentioned in connect was fixed both on desktop and the current CoreCLR. Here are the KBs for desktop updates including the fix for this issue:

https://support.microsoft.com/en-us/kb/3088955 - Hotfix rollup 3088955 for the .NET 4.6 on Windows Server 2012 and Windows 8 
https://support.microsoft.com/en-us/kb/3088956 - Hotfix rollup 3088956 for the .NET 4.6 on Windows Server 2012 R2 and Windows 8.1
https://support.microsoft.com/en-us/kb/3088957 - Hotfix rollup 3088957 for the .NET 4.6 on Windows 7 SP1, Windows Server 2008 SP2, Windows Server 2008 R2 SP1, and Windows Vista SP2 
 
https://support.microsoft.com/en-us/kb/3093266 - Cumulative update for Windows 10: September 30, 2015 (available through Windows Update)

**Comment by redknightlois** [comment] 2016-02-13 04:05
@erozenfeld Yes I will check on monday. The machine is an upgraded Windows 10, but I am pretty sure it was a CoreCLR. As I mentioned it could have been an update1 because I was doing some tests on it.

**Comment by redknightlois** [comment] 2016-02-13 04:17
@erozenfeld No need to wait to monday until I get to the office :) ... I reproduced it at home, the error manifests in a CoreCLR x64 RC1 Update1 instance (not in x86). 

Latest unstable RC2-16357 generates the proper code. You can close as fixed IMHO.

**Comment by erozenfeld** [comment] 2016-02-13 04:24
@redknightlois The fix was ported to CoreCLR in https://github.com/dotnet/coreclr/commit/121d095 post RC1 so what you see is expected.

**Closed** 2016-02-13 16:49 UTC
Labels: bug, CodeGen

**Comment by rominator1983** [comment] 2016-02-15 05:24
Thanks for the information on that one.

**Comment by rominator1983** [comment] 2016-02-15 05:26
When will that hit the market? Any KB-number or .NET Version number?

**Comment by erozenfeld** [comment] 2016-02-15 06:01
@rominator1983 I provided KB numbers for hotfixes for each OS in one of my previous comments here. Is that what you are asking?

**Comment by rominator1983** [comment] 2016-02-17 13:49
@erozenfeld yes that was what i was searching for. All but the last KB have to be installed manually, right?

**Comment by erozenfeld** [comment] 2016-02-17 20:24
@rominator1983 Yes, that's correct.

**Comment by rominator1983** [comment] 2016-03-16 07:50
Do you maybe know, when the 3 hotfixes will be available via windows update?
We want to deploy .NET 4.6.1 to a production machine in the near future. Windows update is of course more practical as we do not have to manually install all hotfix exe files to EVERY installation.

**Comment by erozenfeld** [comment] 2016-03-18 20:11
@leecow @BrettLopez Can you answer this question regarding the hot fixes above?

**Comment by leecow** [comment] 2016-03-21 18:02
@rominator1983 / @erozenfeld, Windows 10 is currently the only platform where .NET Framework hotfixes are being pushed via Windows Update. Everything else will need a manual download and install.
