### ISSUE TITLE
Setting a BaseIntermediateOutputPath and Output gives `Could not load file or assembly 'System.ComponentModel.Primitives, `

### ISSUE THREAD

**Issue by mohamedmansour** [dotnet/coreclr#13381] opened 2017-08-15 19:43 UTC
The error I am having is this uncaught exception:

`System.IO.FileLoadException: 'Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'`

In Program.cs
```
WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
```

My csproj is the following:
```

<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <TypeScriptToolsVersion>2.4</TypeScriptToolsVersion>
    <OutputPath>..\bin\</OutputPath>
    <BaseIntermediateOutputPath>..\obj</BaseIntermediateOutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**\*.ts;wwwroot\**\*.less;wwwroot\**\*.js;wwwroot\**\*.css" CopyToPublishDirectory="Never" />
    <Content Update="wwwroot\**\*.min.js;wwwroot\**\*.min.css" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="dotnet bundle" />
  </Target>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.4.337" />
  </ItemGroup>

</Project>

```

When I remove BaseIntermediateOutputPath and Output from csproj, it works just fine.

**Comment by weshaggard** [comment] 2017-08-16 17:59
If this is caused by changing the OutputPath and/or BaseIntermediateOutputPath then this seems more like a tooling issue that should probably be filed at https://github.com/dotnet/sdk so moving this issue there.

**Comment by weshaggard** [comment] 2017-08-16 18:00
Issue moved to [dotnet/sdk #1497](https://github.com/dotnet/sdk/issues/1497) via [**ZenHub**](https://www.zenhub.com/)

**Comment by weshaggard** [comment] 2017-08-16 18:00
Issue moved to [dotnet/sdk #1498](https://github.com/dotnet/sdk/issues/1498) via [**ZenHub**](https://www.zenhub.com/)

**Closed by weshaggard** 2017-08-16 18:00 UTC
