### ISSUE TITLE
Memory limit in containers

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#9719] opened 2017-02-22 16:03 UTC
From @Maoni0 

> We have job support on Windows, ie, you can set commit/working set limits with an NT job object and GC will recognize that. But we don’t have the equivalent on Linux 

See https://www.infoq.com/news/2017/02/java-memory-limit-container for what other runtimes are doing.

**Comment by janvorli** [comment] 2017-02-22 22:10
There is an issue #5551 to implement support for handling low memory situations in GC on Unix.

**Comment by janvorli** [comment] 2017-02-22 23:09
For Linux, we can implement an equivalent of what we have for Windows job limits using the cgroups. 
`memory.limit_in_bytes` - physical memory usage limit
`memory.memsw.limit_in_bytes` - physical + swap memory usage limit
These limits are per group and they can be read from 
`/sys/fs/cgroup/memory/{GROUP_NAME}/memory.limit_in_bytes`
`/sys/fs/cgroup/memory/{GROUP_NAME}/memory.memsw.limit_in_bytes`
The `GROUP_NAME` for the current process can be retrieved from `/proc/self/cgroup`

There are also per process limits that can be read using the `getrlimit` API.
RLIMIT_AS - The maximum size of the process's virtual memory

**Comment by rahku** [comment] 2017-03-27 19:38
Fixed in PR #10064

**Closed by rahku** 2017-03-27 19:38 UTC
Labels: area-GC

**Comment by mhalenar** [comment] 2017-08-24 14:16
what exactly is the impact of this fix? Because when i run dotnet core 2.0 application inside a Docker container (version 17.06 CE on Ubuntu 16.04), the memory usage is quite high when I compare two Docker hosts with different available memory size. For example application scaffolded with dotnet new webapi consumes around 1.3GB memory on 128GB host and only ~100MB on host with 16GB.

**Comment by Maoni0** [comment] 2017-08-24 22:31
are 128GB and 16GB what the memory the container is assigned to use or the total amount of physical memory of the machine these containers live on? the fix is to take into consideration the memory the container is assigned to use vs assuming it can consume all physical memory the machine the container live on has.

**Comment by mhalenar** [comment] 2017-08-25 06:04
the second option, total physical memory of the machine these container live on. The memory limitation on container (-m switch on docker run) has only the effect that container is killed sooner by the host, because the memory consumption grows over the limit pretty fast. So it seems to me that this fix doesn't help in situation i describe.

**Comment by Maoni0** [comment] 2017-08-25 06:42
I don't have sufficient understanding of your situation to say that's the case or not at all.

you haven't mentioned what the memory limit set on the container was. you mentioned 1.3 GB on a 128GB host. what was the container limit there? when was 1.3 GB measured? was it measured right before the container got killed?

**Comment by mhalenar** [comment] 2017-08-25 07:33
Memory limit on container was set to 256MB, the container got killed when app process reached ~250MB (measured by top command only). 1.3GB was memory usage of app process when no limit is set for container.

**Comment by jbednarik1** [comment] 2017-08-25 08:24
I am working on the same issue as mhalenar. Very same app (https://bitbucket.org/jbednarik/membug/branch/core2.0) executed with -m 50mB does not even start on the server with 128GB RAM (bare metal). On same Ubuntu (16.04, in hyper-v) with 8GB RAM the app starts 

8GB Virtualized Ubuntu 16.04 LTS
```
MEM USAGE / LIMIT   MEM %
42.24MiB / 50MiB    84.48%
```

```
jbe@ubuntu:~/SimpleServer$ docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:24 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:16 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

128GB Virtualized Ubuntu 16.04 LTS
```
root@sh-brn-mko:~/dev/test2# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:50:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

The linked source (branch core2.0) was build with
```
docker build -t simpleserver . --no-cache
```
then started with
```
docker run --name simpleserver -it -d -p 89:80 -m 50mB simpleserver
```

When the memory limit is set higher (e.g.~ 256MB) and performed test with bombardier
```
./bombardier-linux-amd64 -c 16 -d 1h localhost:89/api/values
```
the docker process survives for only few secconds (depends on the memory limit)

Currently working on repro on bare metal with same versions but with 16BG ram (laptop) to remove if hyper-v could have any effect on this.

**Comment by Maoni0** [comment] 2017-08-25 08:41
do you know what the live data size (what your app actually uses) is? if it's bigger than what you set limit for the fix is not going to do anything - we can't shrink the live data size. to find out what it is you can do a GC.Collect at steady state. 

you also might want to disable concurrent GC because concurrent GC doesn't compact - and if you have pins that already scattered on the heap it would be hard to retract. If memory footprint is the highest priority then disabling concurrent would be the right choice.

**Comment by jbednarik1** [comment] 2017-08-25 09:55
Setting GC non-server mode seems to fix the issue. Will do some more testing in LXC as well, though. It is very wierd to set GC to non-server mode when it is running on server mode. Anyway, thank you for a good pointer.

**Comment by Maoni0** [comment] 2017-08-25 12:52
Well, setting GC to Workstation mode has a much bigger effect than disabling non concurrent. You could experience some serious throughput drop. 

Also setting GC to Workstation should not change the total data GC needs to handle so my guess is by setting it to Workstation you just don't have as big a live data size (because Workstation GC makes it slower, you might be processing less data. I dunno what kind of app you have but this is common to see in request oriented apps - by accepting fewer concurrent requests the total live data size is smaller); if that's not the case that would be not by design because as far as memory limit goes both GC flavors should use the same one.

**Comment by mhalenar** [comment] 2017-08-25 13:10
I'm not sure that I understand correctly the term live data - is it the data being actually processed during request? Because my observations were made on aspnet core app, which has just one controller returning json ["value1", "value2"], and I stressed the app with Bombardier tool. Also the VIRT memory demand (or how is it called properly), is around 10x bigger when System.GC.Server is set to true (on 128gb host it is 60GB vs 8GB VIRT). I don't have a clue how GC mode can impact that?

**Comment by Maoni0** [comment] 2017-08-25 20:17
live data means what your code asks to keep alive. for example, you (or a library you use) allocate an array that's 8mb in size and you are using it. this means there's no way GC can make the heap smaller than 8mb. when you do a GC.Collect it means it will do a full blocking GC and shrink the heap size to the smallest that just has data survived by the app, ie, live data size. 

based on some stackoverflow post, VIRT just means the total reserved and yes Server GC will reserve much more memory than Workstation by design because Server GC has larger segment size and multiple heaps. but that doesn't say anything about how much physical memory your process is actually using - that would be the amount of committed memory, ie, what you can write data into (reserved means you can't write anything to it yet - it's not backed up by physical storage).
