### ISSUE TITLE
“(BYTE*)mbi.BaseAddress + mbi.RegionSize > regionStart” assertion in dynamic tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#632] opened 2015-04-03 13:52 UTC
@janvorli is investigating.  The System.Dynamic.Runtime.Tests are failing with an assertion in clrhost_nodependencies.cpp: “(BYTE*)mbi.BaseAddress + mbi.RegionSize > regionStart”.

**Comment by stephentoub** [comment] 2015-04-03 17:03
(This is on Linux.)

**Comment by janvorli** [comment] 2015-04-16 08:30
This assert is no longer happening, so I am closing this as no repro. There was another issue in the tests caused by a tailcail via helper, I have fixed that in #703 and #716.
I have verified that now 3022 tests in this suite complete ok, 147 are skipped and 2 fail due to the #717

**Closed by janvorli** 2015-04-16 08:30 UTC
Labels: Linux
