### ISSUE TITLE
Cannot compile CoreCLR on ARM

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#4500] opened 2016-04-22 02:23 UTC
On a clean checkout, I get the following error trying to build very early on in the build process:

```
CMake Error at functions.cmake:174 (add_library):
  Cannot find source file:

    /home/ubuntu/local/Microsoft/coreclr/bin/obj/Linux.arm.Debug/version.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  src/corefx/System.Globalization.Native/CMakeLists.txt:55 (_add_library)


-- Build files have been written to: /home/ubuntu/local/Microsoft/coreclr/bin/obj/Linux.arm.Debug
Failed to generate native component build project!
```

**Comment by manu-silicon** [comment] 2016-04-22 02:30
Commit at fault is: https://github.com/dotnet/coreclr/commit/250a206c98d8e3992512246e02bf0820ef95578b

**Comment by manu-silicon** [comment] 2016-04-22 02:36
The issue is because of an earlier warning that I did not see at first look:

```
Running: "/home/ubuntu/local/Microsoft/coreclr/Tools/corerun" "/home/ubuntu/local/Microsoft/coreclr/Tools/MSBuild.exe" "/home/ubuntu/local/Microsoft/coreclr/build.proj" /t:GenerateVersionSourceFile /p:NativeVersionSourceFile=/home/ubuntu/local/Microsoft/coreclr/bin/obj/Linux.arm.Debug/version.cpp /p:GenerateVersionSourceFile=true /v:minimal
./build.sh: line 156: /home/ubuntu/local/Microsoft/coreclr/Tools/corerun: No such file or directory
```

**Comment by manu-silicon** [comment] 2016-04-22 02:37
The workaround is to ensure to specify `skipmscorlib` on the command line used to build CoreCLR. This was needed before.

**Comment by seanshpark** [comment] 2016-04-22 03:13
@manu-silicon , does this happen when building in ARM-Linux machine? 
I usually build cross in x86_64 linux with `skipmscorlib` since I was told that `mscorlib.dll` should be cross build in Windows. Can we build `mscorlib.dll` in ARM-Linux machine? or can we also build in x86_64 linux?

**Comment by manu-silicon** [comment] 2016-04-22 03:28
@seanshpark Yes it does.

I usually use both Linux x64 and ARM to compile for ARM. However I've always built mscorlib.dll on Linux x64 (simply because on ARM the toolchain is simply not present) and I had no obvious issue in doing so.

**Comment by janvorli** [comment] 2016-04-22 15:02
This happens for me on CentOS x64 as well. The issue was caused by a recent change #4393. 
@joperezr, for some reason, it seems that the generateversion command line option doesn't work as expected and it is bound to the skipmscorlib - forced to be true if we are building the mscorlib. I believe this is confusing and those two options should be independent. One more detail that I have noticed is that all other options that we have in the build.sh use 0 / 1 as a true / false value, so it would be nice to unify your one with them when you'll be fixing the issue.

**Comment by joperezr** [comment] 2016-04-22 17:25
@janvorli The reason why I tied it with skipmscorlib variable is because in some archs the toolchain doesn't exist as @manu-silicon explains. My reasoning was that if you are able to build mscorlib, then you should be able to generate the cpp file. I guess another thing I can do instead, is to try to use the variable [__isMSBuildOnNETCoreSupported](https://github.com/dotnet/coreclr/blob/master/build.sh#L212) and depending on the value of that, I can generate cpp or not.

**Comment by joperezr** [comment] 2016-04-22 17:25
I'll assign this issue to me and push a PR soon.

**Comment by joperezr** [comment] 2016-04-22 17:35
@manu-silicon I don't have a ARM machine to test [my fix](https://github.com/dotnet/coreclr/pull/4517/commits/b8d6909fa5504bd5290c96121671ed6a6b78b053), if you have time do you mind checking if that small change fixes it?

Sorry for the trouble.

**Closed** 2016-04-22 21:09 UTC
Labels: 2 - In Progress

**Comment by manu-silicon** [comment] 2016-04-23 00:27
I'll be able to test this on Monday. Thanks for looking into this.

**Comment by manu-silicon** [comment] 2016-04-25 01:24
@joperezr Thanks. It works now. Meaning that on ARM if no skipmscorlib option is given, it will try to build it and report an error:
```
Commencing build of mscorlib components for Linux.arm.Debug
./build.sh: line 271: /home/ubuntu/local/Microsoft/coreclr/Tools/corerun: No such file or directory
Failed to build mscorlib.
```
which is was I expected.
