### ISSUE TITLE
[JIT32/x86][GCStress=C][ReadyToRun] 143837.exe JIT helper not supported: CORINFO_HELP_CHECK_OBJ

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#5572] opened 2016-06-07 20:33 UTC
**Environment**
Windows x86 (JIT32)
set COMPlus_GCStress=C
set COMPlus_JitStress=2
set RunCrossGen=1

```
\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(100293): error : JIT._jit64_gc_regress_vswhidbey_143837_143837_._jit64_gc_regress_vswhidbey_143837_143837_cmd [FAIL] [tests\runtest.proj]
  Return code:      1
  Raw output file:      bin\tests\Windows_NT.x86.Checked\Reports\JIT\jit64\gc\regress\vswhidbey\143837\143837.output.txt
  Raw output:
  BEGIN EXECUTION
        " tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\crossgen.exe" /Platform_Assemblies_Paths tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root;bin\tests\Windows_NT.x86.Checked\JIT\jit64\gc\regress\vswhidbey\143837\ 143837.exe
        Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
        Copyright (c) Microsoft Corporation.  All rights reserved.
        ReadyToRun: JIT helper not supported: CORINFO_HELP_CHECK_OBJ
        Native image \tests\Windows_NT.x86.Checked\JIT\jit64\gc\regress\vswhidbey\143837\143837.ni.exe generated successfully.
         "tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" 143837.exe 
        Error
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1

```

**Comment by RussKeldorph** [comment] 2016-06-07 22:34
@gkhanna79 @rahku Could this be the same root cause as #5505.  Could you take a look?
/cc @sivarv

**Comment by gkhanna79** [comment] 2016-06-07 22:37
@JohnChen0 Can you PTAL?

@RussKeldorph @jashook Does this repro without R2R?

**Comment by RussKeldorph** [comment] 2016-06-07 22:41
@gkhanna79 It doesn't fail for me without R2R.

**Comment by gkhanna79** [comment] 2016-06-08 01:27
@fadimounir Can you PTAL?

**Comment by RussKeldorph** [comment] 2016-06-08 16:55
Putting in RTM until impact is determined.

**Comment by fadimounir** [comment] 2016-06-08 19:15
@RussKeldorph @gkhanna79 This is the same issue as #5505 (confirmed with @rahku)

**Comment by fadimounir** [comment] 2016-06-08 19:20
Closing issue as duplicate of #5505.

**Closed by fadimounir** 2016-06-08 19:20 UTC
Labels: GCStress, ReadyToRun, x86
