### ISSUE TITLE
[JitStressRegs=4] System.Reflection.Emit.Tests fails with System.TypeLoadException : Non-Static Global Method

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2734] opened 2016-01-19 22:39 UTC
**Configuration**

Linux
Coreclr checked build
Corefx release build

Coreclr: 761fa46 (Wed Jan 13 18:15:58 2016 -0500)
Corefx: 0824d9745687271503f7538d16f44f17f5ef5f18 (Tue Jan 12 14:49:52 2016 -0800)

**Failure**

Fail with JitStressReg=0x4
Pass without JitStressReg=0x4

```
corefx/bin/tests/Linux.AnyCPU.Release/System.Reflection.Emit.Tests/dnxcore50$ COMPlus_JitStressRegs=4 ./corerun xunit.console.netcore.exe System.Reflection.Emit.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Reflection.Emit.Tests
Discovered:  System.Reflection.Emit.Tests
Starting:    System.Reflection.Emit.Tests
   System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestWithMultipleGlobalMethods [FAIL]
      System.TypeLoadException : Non-Static Global Method.
      Stack Trace:
            at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
            at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
            at System.Reflection.Emit.TypeBuilder.CreateType()
            at System.Reflection.Emit.ModuleBuilder.CreateGlobalFunctionsNoLock()
            at System.Reflection.Emit.ModuleBuilder.CreateGlobalFunctions()
   System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestWithSingleGlobalMethod [FAIL]
      System.TypeLoadException : Non-Static Global Method.
      Stack Trace:
            at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
            at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
            at System.Reflection.Emit.TypeBuilder.CreateType()
            at System.Reflection.Emit.ModuleBuilder.CreateGlobalFunctionsNoLock()
            at System.Reflection.Emit.ModuleBuilder.CreateGlobalFunctions()
            at System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestWithSingleGlobalMethod()
   System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestThrowsExceptionOnMultipleCallsToCreateGlobalFunctions [FAIL]
      System.TypeLoadException : Non-Static Global Method.
      Stack Trace:
            at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
            at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
            at System.Reflection.Emit.TypeBuilder.CreateType()
            at System.Reflection.Emit.ModuleBuilder.CreateGlobalFunctionsNoLock()
            at System.Reflection.Emit.ModuleBuilder.CreateGlobalFunctions()
            at System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestThrowsExceptionOnMultipleCallsToCreateGlobalFunctions()
Finished:    System.Reflection.Emit.Tests

=== TEST EXECUTION SUMMARY ===
   System.Reflection.Emit.Tests  Total: 704, Errors: 0, Failed: 3, Skipped: 0, Time: 10.162s
```

**Comment by sivarv** [comment] 2016-01-20 01:06
Does this test pass without JitStressRegs=3 ?

**Comment by sejongoh** [comment] 2016-01-20 08:39
Yes, I corrected the description above. It only fail with JitStressRegs=4 so far.

**Comment by hoyMS** [comment] 2016-01-21 00:39
This is a duplicate of Issue #2380

**Closed by hoyMS** 2016-01-21 00:39 UTC
Labels: bug, CodeGen, Linux
