### ISSUE TITLE
GcStress: Linux: Sanity Check failed in _il_dbglongsig

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2767] opened 2016-01-21 01:40 UTC
This could be the same issue as #2764 

Failing Tests:
```
JIT/Methodical/refany/_il_dbgshortsig/_il_dbgshortsig
JIT/Methodical/refany/_il_dbglongsig/_il_dbglongsig.exe
```

```
corerun JIT/Methodical/refany/_il_dbglongsig/_il_dbglongsig.exe

Assert failure(PID 20091 [0x00004e7b], Thread: 20091 [0x4e7b]): SanityCheck()
    File: /home/swaroops/git/a/coreclr/src/vm/methodtable.cpp Line: 9739
    Image: /home/swaroops/git/a/coreclr/bin/Product/Linux.x64.Debug/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 20091, Thread 20091/0x4e7b)' ****
  SanityCheck()

/home/swaroops/git/a/coreclr/src/vm/methodtable.cpp, Line: 9739

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/home/swaroops/git/a/coreclr/bin/Product/Linux.x64.Debug/corerun

********

/home/swaroops/bin/runn: line 3: 20091 Aborted
```

Repro steps are:

* cp \scratch2\scratch\swaroops\coredistools\libcoredistools.so somewhere
* export LD_LIBRARY_PATH=somewhere
* export COMPlus_GCStress=0xC
* Run the above test

**Comment by sivarv** [comment] 2016-01-21 18:42
My guess is that all these refany category of tests might be failing for the same reason.

**Comment by sivarv** [comment] 2016-01-29 03:50
Mkrefany tests. Fix to correctly handle TypedReference will fix this.

**Comment by sivarv** [comment] 2016-01-29 04:21
This is a duplicate of #2764

**Closed by sivarv** 2016-01-29 04:21 UTC
Labels: bug, CodeGen, GCStress, Linux
