### ISSUE TITLE
Passing struct by value via PInvoke on OSX not working

### ISSUE THREAD

**Issue by toptensoftware** [dotnet/coreclr#954] opened 2015-05-07 15:42 UTC
Passing a structure by value through pinvoke on OSX results in random data in the native code.  [Sample Code Here](https://www.dropbox.com/s/07tzgb2cjizdps9/clrtest3.zip?dl=0).

eg: 

```
		[DllImport("clrtest.dylib")]
		public static extern double GetWidthByVal(RECT r);

		[DllImport("clrtest.dylib")]
		public static extern double GetWidthByRef(ref RECT r);

		static void Main(string[] args)
		{
			var r = new RECT();
			r.x = 10;
			r.y = 20;
			r.width = 30;
			r.height = 40;

			Console.WriteLine("ByVal: {0}", GetWidthByVal(r));
			Console.WriteLine("ByRef: {0}", GetWidthByRef(ref r));
		}
```

Gives:

```
ByVal: 2.2319740764649E-314
ByRef: 30
```

**Comment by cmckinsey** [comment] 2015-05-07 16:57
This is known. Lubo is working on this. @LLITCHEV

**Comment by jkotas** [comment] 2015-05-07 17:14
Duplicate of #200

**Closed by jkotas** 2015-05-07 17:14 UTC
Labels: CodeGen
