### ISSUE TITLE
WeakReference instance remains alive after GC.Collect() in Debug builds

### ISSUE THREAD

**Issue by am11** [dotnet/coreclr#13490] opened 2017-08-19 20:09 UTC
### A.cs

```c#
using System;

class A
{
    static void Main(string[] args)
    {
        var subject = new object();
        var wref = new WeakReference(subject);

        subject = null;
        GC.Collect();
        GC.WaitForPendingFinalizers();

        Console.WriteLine("Should be false: " + wref.IsAlive);
        Console.WriteLine("Should be false: " + wref.IsAlive);
        Console.WriteLine("Should be false: " + wref.IsAlive);
        Console.WriteLine("Should be false: " + wref.IsAlive);
        Console.WriteLine("Should be false: " + wref.IsAlive);
    }
}
```

### A.csproj

```c#
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.0;netcoreapp1.0;net462</TargetFrameworks>
  </PropertyGroup>

</Project>
```

### Outputs:

After running `dotnet restore` once:

`dotnet run -f net462 -c debug`

> Should be false: False ✅ 

`dotnet run -f netcoreapp1.0 -c debug`

> Should be false: False ✅ 

`dotnet run -f netcoreapp2.0 -c debug`

> Should be false: True 🛑
 
This seems like a regression in .NET Core 2.0. However, with `-c release`, IsAlive returns False on .NET Core 2.0 as well.

**Comment by danmosemsft** [comment] 2017-08-19 21:39
@swgillespie

**Comment by mikedn** [comment] 2017-08-19 21:44
See https://github.com/dotnet/coreclr/issues/12847

**Comment by swgillespie** [comment] 2017-08-19 21:47
Yeah, this is a duplicate of the issue mikedn issued and not a bug. The JIT is permitted to arbitrarily extend the lifetimes of local variables, and in the debug case the JIT has reported that `subject` is still live.

**Closed by swgillespie** 2017-08-19 21:47 UTC
Labels: area-GC

**Comment by AArnott** [comment] 2018-02-17 17:10
I just hit this myself while getting VS MEF tests running on netcoreapp2.0 as it caused tests to fail that passed on netcoreapp1.0.
I can workaround it now that this and the linked issue documents that this is by design and suggests the workaround. But thought I'd +1 that this was a small stumbling block, and unexpected since no other runtime seems to have this behavior.
