### ISSUE TITLE
ReadyToRun: JIT\jit64\regress\vsw\543645\test fails

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3604] opened 2016-03-09 02:40 UTC
Test: JIT\jit64\regress\vsw\543645\test

Repro steps:
 Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

BEGIN EXECUTION
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image E:\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\jit64\regress\vsw\543645\test\ovfldiv1.ni.exe generated successfully.
 "E:\coreclr\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" test.exe  
Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED

**Comment by LLITCHEV** [comment] 2016-03-10 00:07
This looks like an issue having to do with unwinding exceptions in ReadyToRun.
It looks like the Jit is calling correctly the overflow throw handler.
Here is the stack that leads to the crash...
>	coreclr.dll!`RaiseTheExceptionInternalOnly'::`81'::__Body::Run(RaiseTheExceptionInternalOnly::__l2::Param * pParam) Line 3114	C++
 	coreclr.dll!RaiseTheExceptionInternalOnly(OBJECTREF throwable, int rethrow, int fForStackOverflow) Line 3114	C++
 	coreclr.dll!UnwindAndContinueRethrowHelperAfterCatch(Frame * pEntryFrame, Exception * pException) Line 8747	C++
 	coreclr.dll!JIT_Overflow() Line 5484	C++

**Comment by jkotas** [comment] 2016-03-12 18:16
Code for the offending method:
```
0:000> u 00007ffe`52df26b0 L30
ovfldiv1_ni!Overflow.test1() [c:\coreclr\tests\src\JIT\jit64\regress\vsw\543645\test.il @ 94]:
push    rbp
mov     rbp,rsp
nop
mov     eax,0FFFFFFFFh
movsxd  rax,eax
mov rdx,8000000000000000h
imul    rax,rdx
jno     ovfldiv1_ni!Overflow.test1()+0x22
call    JIT_Overflow
nop
pop     rbp
ret
```

**Comment by jkotas** [comment] 2016-03-12 18:18
The problem is the method is calling the `JIT_Overflow` helper, but there is no shadow argument area allocated on the stack.

**Comment by gkhanna79** [comment] 2016-03-14 16:01
@LLITCHEV Should this go to you?

**Comment by RussKeldorph** [comment] 2016-03-28 22:07
Only affects Debuggable code, so, even though this is really bad silent bad code, we don't think it's likely to hit RC2 scenarios.

**Comment by LLITCHEV** [comment] 2016-03-31 22:51
Fixed with PR #3953

**Closed by LLITCHEV** 2016-03-31 22:51 UTC
Labels: bug, CodeGen, ReadyToRun
