### ISSUE TITLE
Interop LPSTRTest failing in Windows_NT x86 Debug Legacy Backend  with AV

### ISSUE THREAD

**Issue by tijoytom** [dotnet/coreclr#3571] opened 2016-03-08 01:35 UTC

**Comment by tijoytom** [comment] 2016-03-23 21:37
There  tests are also affected by same issue. 
Interop\BestFitMapping\BestFitMapping\BestFitMapping.cmd      
Interop\StringMarshalling\LPSTR\LPSTRTest\LPSTRTest.cmd
Interop\StringMarshalling\LPTSTR\LPTSTRTest\LPTSTRTest.cmd
Interop\MarshalAPI\FunctionPointer\FunctionPtrTest\FunctionPtrTest.cmd

**Comment by tijoytom** [comment] 2016-03-23 21:42
13:10:51 d:\j\workspace\x86_lb_releas---618496d6\tests\src\TestWrappers_x86_Release\Interop\Interop.XUnitWrapper.cs(351): error : Interop._StringMarshalling_LPSTR_LPSTRTest_LPSTRTest_._StringMarshalling_LPSTR_LPSTRTest_LPSTRTest_cmd [FAIL] [d:\j\workspace\x86_lb_releas---618496d6\tests\runtest.proj]
13:10:51         
13:10:51   Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
13:10:51            at System.String.wcslen(Char* ptr)
13:10:51            at NativeDefs.PInvokeDef.RPinvoke_DelMarshal_InOut(DelMarshal_InOut d, String s)
13:10:51            at Test.Main(String[] args)
13:10:51   
13:10:51   
13:10:51   Raw output:      d:\j\workspace\x86_lb_releas---618496d6\bin\tests\Windows_NT.x86.Release\Reports\Interop\StringMarshalling\LPSTR\LPSTRTest\LPSTRTest.output.txt
13:10:51   To run the test:
13:10:51   > set CORE_ROOT=d:\j\workspace\x86_lb_releas---618496d6\bin\tests\Windows_NT.x86.Release\Tests\Core_Root
13:10:51   > d:\j\workspace\x86_lb_releas---618496d6\bin\tests\Windows_NT.x86.Release\Interop\StringMarshalling\LPSTR\LPSTRTest\LPSTRTest.cmd
13:10:51   
13:10:51         Expected: True
13:10:51         Actual:   False
13:10:51           src\TestWrappers_x86_Release\Interop\Interop.XUnitWrapper.cs(351,0): at Interop._StringMarshalling_LPSTR_LPSTRTest_LPSTRTest_._StringMarshalling_LPSTR_LPSTRTest_LPSTRTest_cmd()
13:10:51 d:\j\workspace\x86_lb_releas---618496d6\tests\src\TestWrappers_x86_Release\Interop\Interop.XUnitWrapper.cs(126): error : Interop._BestFitMapping_BestFitMapping_BestFitMapping_._BestFitMapping_BestFitMapping_BestFitMapping_cmd [FAIL] [d:\j\workspace\x86_lb_releas---618496d6\tests\runtest.proj]
13:10:51         
13:10:51   Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
13:10:51            at BestFitMapping.DoSCallBack_LPSTR_In(SCallBackIn callback)
13:10:51            at BestFitMapping.Main()
13:10:51   
13:10:51   
13:10:51   Raw output:      d:\j\workspace\x86_lb_releas---618496d6\bin\tests\Windows_NT.x86.Release\Reports\Interop\BestFitMapping\BestFitMapping\BestFitMapping.output.txt
13:10:51   To run the test:
13:10:51   > set CORE_ROOT=d:\j\workspace\x86_lb_releas---618496d6\bin\tests\Windows_NT.x86.Release\Tests\Core_Root
13:10:51   > d:\j\workspace\x86_lb_releas---618496d6\bin\tests\Windows_NT.x86.Release\Interop\BestFitMapping\BestFitMapping\BestFitMapping.cmd
13:10:51   
13:10:51         Expected: True
13:10:51         Actual:   False
13:10:51           src\TestWrappers_x86_Release\Interop\Interop.XUnitWrapper.cs(126,0): at Interop._BestFitMapping_BestFitMapping_BestFitMapping_._BestFitMapping_BestFitMapping_BestFitMapping_cmd()
13:10:51     Discovered:  managed.XUnitWrapper
13:10:51     Finished:    Exceptions.XUnitWrapper
13:10:51     Finished:    Loader.XUnitWrapper
13:10:51 d:\j\workspace\x86_lb_releas---618496d6\tests\src\TestWrappers_x86_Release\Interop\Interop.XUnitWrapper.cs(396): error : Interop._StringMarshalling_LPTSTR_LPTSTRTest_LPTSTRTest_._StringMarshalling_LPTSTR_LPTSTRTest_LPTSTRTest_cmd [FAIL] [d:\j\workspace\x86_lb_releas---618496d6\tests\runtest.proj]
13:10:51         
13:10:51   Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
13:10:51            at System.String.wcslen(Char* ptr)
13:10:51            at NativeDefs.PInvokeDef.ReverseP_MarshalStrB_InOut(Del_MarshalStrB_InOut d, String s)
13:10:51            at Test.Main(String[] args)
13:10:51

**Comment by jkotas** [comment] 2016-03-25 06:02
These failures are likely caused by x86 calling convention mismatches - similar to what I have fixed in #3917

**Closed** 2016-05-04 03:52 UTC
Labels: interop
