### ISSUE TITLE
Remove the VC Redist pre-req

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#7994] opened 2016-11-04 06:27 UTC
We need to come up with a solution that doesn't require users to first install the VC Redist in order to install .NET Core.

**Comment by gkhanna79** [comment] 2017-03-30 01:56
Fixing this can be done by including the required files when building the RID split version of M.N.App. @weshaggard Do you still want uCRT binaries to go in their own package, like the apiset one, and be a dependency of CoreCLR package?

**Comment by weshaggard** [comment] 2017-03-30 17:49
I don't think I ever wanted them to be in their own package. We should see if the C++ team already provides them as a package and if so then we can use that but if not then I would be hesitant for us to package them by themselves and instead would prefer we package them directly in the CoreCLR package or the M.N.App package.

**Comment by Petermarcu** [comment] 2017-03-30 18:10
Why not just have them delivered with coreclr? That sounds simplest.

**Comment by gkhanna79** [comment] 2017-04-03 18:00
@wtgodbe As discussed, I am assigned this to you. Fixing this involves two stages:

1) Package the UCRT binaries into the CoreCLR nuget package. During the build, use `UniversalCRTSDKDir` environment variable to get the base location to find the binaries for the architecture in question. We will **not** be doing this for Arm64 since the problem is not applicable there. Also, we should package the binaries only during `Release` build.

2) Once the CoreCLR package with this change is published and Maestro update has been merged in Core-Setup, please update the Core-Setup Windows platform installers to remove the VCRedist installer dependency. The installers live under https://github.com/dotnet/core-setup/tree/master/packaging/windows.

**Closed** 2017-04-04 15:51 UTC
Labels: area-Infrastructure
