### ISSUE TITLE
Add Linux runtime-events tracing info

### ISSUE THREAD

**Issue by karelz** [dotnet/coreclr#10600] opened 2017-03-31 04:36 UTC
Let's take technical stable info from @goldshtn's [blog post](http://blogs.microsoft.co.il/sasha/2017/03/30/tracing-runtime-events-in-net-core-on-linux/) and add it to CoreCLR docs.
Keep link to the blog post as credits of course.

Where?
Either enhance [Linux Performance Tracing](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md) docs, or create a sibling doc (I think this is winner).

@brianrob @vancem any preference where? Could you please help review / advise which parts to grab into CoreCLR?

**Comment by karelz** [comment] 2017-03-31 04:43
For context, @goldshtn agreed: https://twitter.com/goldshtn/status/847662168807849987

I suggest to create how-to similar to [Linux performance tracing](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md) doc. Setup/prep, collect, analyze + gotchas and maybe a little bit of intro what can be achieved with that.
Thoughts?

Motivation: I think it is valuable to have important how-to docs in repo. When we find useful technical info for customers, or contribution newbies, we should add it here (with credits to seeding article). Blog posts are great for additional opinions, screenshots, and iterative approach -- repo can then hold the summary (e.g. after we figure out stacks ;-)) ... feel free to push back on my view point (just testing waters).

**Comment by karelz** [comment] 2017-03-31 04:48
For big-picture context, I plan to link these docs (and blog posts) from master CoreFX/CoreCLR contributor documentation as laid out here: https://github.com/dotnet/corefx/issues/17534

**Comment by karelz** [comment] 2017-03-31 04:51
Idea:
Would it make sense to add a sample output with explanation? Something like the tweet picture? https://twitter.com/goldshtn/status/847426411820269574

**Comment by karelz** [comment] 2017-03-31 05:29
@brianrob how far are you with the we-need-stacks story? 1.5 year ago we were discussing changes in perf (which were rejected AFAIK), or option to revive CLRStack ... @goldshtn is interested in the topic ;-)

**Comment by karelz** [comment] 2017-04-01 18:36
Just a quick update: I had a chat with @brianrob earlier this week. There is some development happening in the space that we are not ready to disclose yet (it might not work out, more partners involved, etc.) - it has a potential to simplify the overall tracing story on Linux (incl. stacks).
It might be best to wait for a few weeks / couple of months for the story to crystallize and then make the decision what we should document. We will release more details when we are ready. Until then, let's just point people interested to @goldshtn's blog post as primary documentation.

**Comment by goldshtn** [comment] 2017-04-01 18:43
In the meantime, it looks like LTTNG 2.10 is going to have stacks support. I'm not 100% clear on whether this will work for userspace events, though. Here's the patch: https://lists.lttng.org/pipermail/lttng-dev/2017-March/026985.html

**Comment by brianrob** [comment] 2017-04-03 05:38
@goldshtn, thanks for sharing.  I read through Mathieu's patch and it looks like userspace events are covered - there is a user-space call-stack context.  From the RFC: "Add kernel and user callstack contexts".  This would be a great addition!

**Comment by goldshtn** [comment] 2017-04-03 05:54
@brianrob Yes, but are you sure the stack events would be collectable without the LTTng kernel modules? Or do we currently require LTTng kernel modules in any case? (I am not very familiar with LTTng internals...)

**Comment by goldshtn** [comment] 2017-04-03 05:56
In the meantime, you might also find my [second post](http://blogs.microsoft.co.il/sasha/2017/04/02/tracing-net-core-on-linux-with-usdt-and-bcc/) useful, where I show some of the things that would be possible if we had stack trace support for LTTng right now. Perhaps we could use something similar to [my patch](https://gist.github.com/goldshtn/eae953dfccd2eb4b4d43d4c326b62fb5) that embeds both USDT and LTTng markers in the binary? I don't expect the overhead to be significant, especially since it is all gated by the environment variable anyway (which is something I disagree with in any case...).

/cc @brianrob

**Comment by goldshtn** [comment] 2017-04-06 04:17
@brianrob Mathieu confirmed on Twitter that this LTTNG patch would not support user space events.

**Comment by brianrob** [comment] 2017-04-06 04:49
@goldshtn, thanks for confirming this.  Good to know.  I appreciate your dedication to the tracing space.

With respect to adding USDT markers, I think this is interesting, but before we do so, there's some work happening internally that we're not quite ready to discuss yet.  Once we are, I think this will fit in nicely.  I'll include you in the discussion once it's here on GitHub.

**Comment by goldshtn** [comment] 2017-04-06 04:53
@brianrob Thanks - do you have any rough timeline on when this should become public? I ask because .NET Core is not in preview anymore (for quite a while now). I have clients who are concerned about the fidelity of tracing they can achieve on Linux compared to Windows.

**Comment by brianrob** [comment] 2017-04-06 14:11
I expect this to become public in the next 1-2 months.

**Comment by gkhanna79** [comment] 2017-04-20 23:57
@brianrob Marking this for 2.0 based upon your response at https://github.com/dotnet/coreclr/issues/10600#issuecomment-292186538

**Comment by karelz** [comment] 2017-04-21 00:09
Thinking about it more ... we might as well close this issue. It does not track the new work and that will be the key anyway. @brianrob can you please do it if you agree?

**Comment by brianrob** [comment] 2017-04-21 00:12
Yes, let's close this.  @goldshtn is going to work on some collection improvements and we can use that opportunity to improve our documentation.

**Closed by brianrob** 2017-04-21 00:12 UTC
Labels: area-EventSource, documentation, os-linux
