### ISSUE TITLE
Tizen differing behavior with variable vs array element of sbyte

### ISSUE THREAD

**Issue by DamianMehers** [dotnet/coreclr#20102] opened 2018-09-22 11:45 UTC
Using the latest public bits (VS2017 15.8.5, VS Tools for Tizen 1.5.0.0,  Wearable (Preview) package 0.0.38), testing on a real Galaxy Watch (SM-R800, Tizen Version 4.0.0.0, Software version R800XXU1BRH3)), when I run this code:

``` csharp
            int result = 0;
            sbyte[] v = {  -1 };

            result |= (v[0] & 0x000000FF);
            log.WriteLine("Result using array element is " + result);

            result = 0;
            sbyte v3 = -1;
            result |= (v3 & 0x000000FF);
            log.WriteLine("Result using variable is " + result);
```

I get:

```
Result using array element is -1
Result using variable is 255
```

When I use the same code on **Windows using .NET Core, I get 255 in both cases**.  It seems like a bug ... but not sure whether it is compile time or runtime.

Thanks,

   Damian

**Comment by AaronRobinsonMSFT** [comment] 2018-09-23 15:34
seems like a JIT issue.

cc @AndyAyersMS

**Comment by AndyAyersMS** [comment] 2018-09-23 17:31
cc @RussKeldorph

**Comment by jkotas** [comment] 2018-09-24 21:40
cc @alpencolt

**Comment by alpencolt** [comment] 2018-09-25 10:10
@DamianMehers thank you for information.
@jkotas I think there was similar bug some time ago. Tizen 4 has CoreCLR 2.0 version with additional patches. Fix for this may be missed.

**Comment by alpencolt** [comment] 2018-09-25 10:35
Looks the same #16675

**Comment by mikedn** [comment] 2018-09-25 11:16
FWIW I can't reproduce the problem using ARM32 altjit in the current master, the generated code looks correct. I don't have ARM/Tizen hardware to actually test.

**Comment by alpencolt** [comment] 2018-09-25 12:40
@mikedn current master doesn't have legacy JIT code as far as I know.

Issue reproduce on code pre 2.1 release in regular Linux/ARM: RuyJIT works well, legacy prints:
```
Result using array element is -1
Result using variable is 255
```

**Closed** 2018-09-26 01:38 UTC
Labels: area-CodeGen, os-tizen
