### ISSUE TITLE
Working towards 2.0.0 release

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#11248] opened 2017-04-26 23:59 UTC
@hqueue @jyoungyun @hseok-oh 

I wanted to share some additional data with you all since we forked for release/2.0.0.

We are working towards getting all bugs, identified to be fixed for .NET Core 2.0 Preview2 and RTM release, by 5/10 for CoreCLR, CoreFX and Core-Setup repos. Please plan to get your fixes in the respective master branches by 5/10 EOD PST.

After 5/10, master branch contents will be pushed into respective release/2.0.0branches and master version will become 2.1. Any fixes required for 2.0 release, post 5/10, we will be taking fixes in release/2.0.0 branches but they would be subject to higher bar. For any such fixes that you deem need to be made, I would suggest the following:

1) Make the PR against release/2.0.0 branch and CC @leecow and me.
2) Have the PR description detail the importance of getting the change in.

Likewise, if you have any fixes that need to go into Preview1 (which is what release/2.0.0 branch is versioned as right now), please follow the same process. The timeline for those is EOW.

Please share this with your team as well and do let me know if you have any questions.

CC @leecow @weshaggard @richlander @Petermarcu @shawnro

**Comment by gkhanna79** [comment] 2017-04-28 15:02
@hqueue @hseok-oh @jyoungyun Please let me know if you have any questions around this.

**Comment by jyoungyun** [comment] 2017-05-02 05:56
@gkhanna79 In fact, I would like to enable CI for tizen if tizen runtime nupkgs starts to upload to dotnet-core myget normally. The Tizen CI of CoreCLR and CoreFX are not able to generate tizen runtime pkg at present due to lack of tizen runtime nupkg on dotnet-core myget and Core-setup is not enabled tizen CI yet due to the same reason. If possible, try to incorporate all of this before May 10, but the build cycle issue must be resolved. Currently, it triggers CoreCLR, CoreFX and Core-setup builds six times a day, every four hours. But I think it should be triggered at the same time to use the same code, isn't it? If you are okay I can upload tizen nupkgs to dotnet-core myget for CI test before resolving the build cycle issue. Currently I'm uploading to [Tizen dotnet-core myget](https://tizen.myget.org/gallery/dotnet-core).

**Comment by gkhanna79** [comment] 2017-05-04 05:22
> I would like to enable CI for tizen if tizen runtime nupkgs starts to upload to dotnet-core myget normally.

Can you make Tizen CI to use Tizen's myget feed to get the CI going?

> but the build cycle issue must be resolved.
>  But I think it should be triggered at the same time to use the same code, isn't it?

Are you trying to ensure that you get the same build number as us so that whatever build number is for the Tizen package referenced in the Microsoft.NETCore.App Identity package (which we produce), you can use the same build number at to produce runtime.* packages at your end? If so, the answer to that depends upon your response to https://github.com/dotnet/core-setup/issues/1566#issuecomment-299098368.

**Comment by jyoungyun** [comment] 2017-05-08 06:26
@gkhanna79 Sure. As you know, coreclr does not have other pkgs dependency. But corefx does. So I can fix the Tizen CI of corefx to use Tizen myget feed by using `/p:OverridePackageSource=https://tizen.myget.org/F/dotnet-core/api/v3/index.json` option. But this patch will be unnecessary after I upload tizen runtime nupkgs to dotnet-core myget. Do you want to add a temporary patch? And could you share API keys of dotnet-core myget to test uploading tizen runtime nupkgs. 

And did you see my answer of [dotnet/core-setup#1566](https://github.com/dotnet/core-setup/issues/1566#issuecomment-299151543)? Please let me know if you have any more questions.

**Comment by gkhanna79** [comment] 2017-05-08 17:44
> But this patch will be unnecessary after I upload tizen runtime nupkgs to dotnet-core myget.

Yes, I am suggesting we use this approach to first get everything working so that we have a baseline infrastructure that is flexible and independent of our infrastructure.

**Comment by jyoungyun** [comment] 2017-05-10 09:43
@gkhanna79 I'm patching for tizen runtime nupkgs in Tizen CI. Can I put it in the master branch only? Or should I put it in release/2.0.0 branch too? I will update ASAP.

**Comment by jyoungyun** [comment] 2017-05-10 10:17
@gkhanna79 Since coreclr has no dependencies on other runtime pkgs, there are no patches to fix.
For core-setup, Tizen CI is not yet implemented and I will make a PR at least until 5/14.
As you know, the build trigger issues of your builds and oru builds have not been resolved yet. Currently the tizen runtime pkgs are built every 6 hours. So, the minor number exists only until 04th. Therefore,
 when the dependencies (https://github.com/dotnet/corefx/blob/master/dependencies.props#L25, https://github.com/dotnet/core-setup/blob/master/dependencies.props#L18-19, https://github.com/dotnet/core-setup/blob/master/src/pkg/projects/Microsoft.NETCore.App/src/project.json.template#L3-L4) in corefx and core-setup change, it must be changed within 04.

**Comment by gkhanna79** [comment] 2017-05-10 14:54
@jyoungyun All PRs need to be made against master branch (which is targeting preview2) since our release/2.0.0 branches are locked down (for preview1). If you need something for Preview1 in Tizen packages you are producing, you will need to (temporarily) make those changes in your copy of release/2.0.0 branches.

> the build trigger issues of your builds and oru builds have not been resolved yet

I think the response at https://github.com/dotnet/core-setup/issues/1566#issuecomment-300491777 is what you are looking for.

**Comment by jyoungyun** [comment] 2017-05-11 06:30
@gkhanna79 Is it a lock down on May 15 for preview1? Or did you already have a preview1 release?

**Comment by gkhanna79** [comment] 2017-05-11 16:16
@jyoungyun Preview1 release was already snapped in April and is released (see https://blogs.msdn.microsoft.com/dotnet/2017/05/10/announcing-net-core-2-0-preview-1/).

We will be snapping for PReview2, latest, by early next week (if not this week).

**Comment by gkhanna79** [comment] 2017-05-16 23:22
@hqueue @jyoungyun @hseok-oh We are approaching the point where preview2 commits can only be made in release/2.0.0 branch and master will fork for vnext. I will let you know in a day or so when that happens.

We are working towards the goal of getting all our preview2 fixes in by 5/26 EOD. 

This is just FYI so that you can plan accordingly. Post 5/26, the criteria to get fixes in will be essentially of a ship-stopper bug.

**Comment by jyoungyun** [comment] 2017-05-17 02:37
@lemmaa @hqueue @hseok-oh @chunseoklee Well, I think the jobs for enabling the Linux arm and armel are almost over. I am now adding the Tizen CI into the core-setup and it is likely to end up today. Another remaining job is the pipeline build issue. Although we have a issue in the build cycle btw MS and Tizen, but some work. I'm checking the 'dotnet/versions' repository and the version file in runtime M.N.App nupkgs that @gkhanna79 and @weshaggard shared to solve the build cycle issue. Is there anything else we should take care of the preview2 release besides this?

**Comment by jyoungyun** [comment] 2017-05-17 04:12
Related remaining issues:
https://github.com/dotnet/core-setup/issues/725 Enalbling Linux ARM32 for .NET Core
https://github.com/dotnet/core-setup/issues/790 Enable CI support for Linux ARM32
https://github.com/dotnet/core-setup/issues/1566 Enable Pipeline build support for Linux armel(Tizen)

https://github.com/dotnet/corefx/issues/16335 [armel][Tizen] Enable CoreFX Pipeline build support for Linux for armel (Tizen)

https://github.com/dotnet/coreclr/issues/9689 Enable PipeLine build support for Linux armel (Tizen) area-Tizen

**Comment by gkhanna79** [comment] 2017-05-17 04:36
@jyoungyun Were you able to extract the SHAs from the runtime.* packages @joperezr pointed at to address the cycle issue?

**Comment by jyoungyun** [comment] 2017-05-17 05:32
@gkhanna79 Yes, I see the SHAs for coreclr, corefx and core-setup in runtime.* packages. I'm searching for how to poll runtime.M.N.App nupkgs whenever new version is pushed. I think if you add a webhook for our  webservice, this issue is solved. Can you add webhook for us? And is there other way to poll the runtime.M.N.App nupkg ?

**Comment by gkhanna79** [comment] 2017-05-18 14:09
@jyoungyun Can you do timed polls (say, around 7am and 7pm)?

Also, master branch for CoreCLR/CoreFX/Standard repos are now forked to be 2.1-preview1. Core-Setup is still being worked upon to move to 2.1 - so, if you have any changes for it, please let me know. I will let you know when Core-Setup master is 2.1-preview1 (hopefully today).

Release/2.0.0 of CoreCLR/CoreFX/Standard/Core-Setup now carry 2.0.0-Preview2 payload and all commits there are now subject to a checkin bar. Thus, for any fixes that you deem necessary for Preview2, please make them against 2.0.0 and CC me. I will help shepherd them for the merge. Ofcourse, do make them in master first (subject to Core-Setup caveat above temporarily) to ensure they are not lost from 2.1 :)

**Comment by hqueue** [comment] 2017-05-18 14:26
> @jyoungyun Can you do timed polls (say, around 7am and 7pm)?

@gkhanna79 Just to make sure, I think you meant time in PST(UTC-8) or PDT(UTC-7) ?

**Comment by gkhanna79** [comment] 2017-05-18 14:32
Seattle time :)

**Comment by jyoungyun** [comment] 2017-05-19 04:39
@gkhanna79 Thank you for information about new version naming. I saw that the version was changed as you said.

>@jyoungyun Can you do timed polls (say, around 7am and 7pm)?

If your pipeline build is triggered every 7am and 7pm, I can drive our build as the same time schedule. However when I look at dotnet-core myget, there are *-03 nupkgs. If you build twice a day,  you should upload only 2 versions, 01, 02. If I manage by time, I can not know that you triggered separately. What I want is to create a nupkg of the samd build number with the same code as you. And I want to provide all versions of nupkg you upload. When you change the dependency version, we guarantee that we are providing the same version nupkgs of the same code so that Tizen CI may not fail. :)

**Comment by gkhanna79** [comment] 2017-05-23 18:45
@jyoungyun Were you able to use suggestion from @dagood to use information in Versions repo to get this going?

**Comment by gkhanna79** [comment] 2017-05-23 18:52
@jyoungyun @hqueue @hseok-oh We will be taking the last of the fixes for Preview2 by EOD 5/26. Are you tracking the product issues for Tizen (https://github.com/dotnet/coreclr/issues?q=label%3Aarea-Tizen+is%3Aissue+is%3Aopen+milestone%3A2.0.0) to be resolved by then since starting 5/30, the bar to commit changes will be high?

Please note that 5/29 is holiday here and folks may not be around.

**Comment by jyoungyun** [comment] 2017-05-26 10:08
@gkhanna79 I think we can close build pipeline issue now. :) And i will check #11386 issue next monday and ping you.

**Comment by gkhanna79** [comment] 2017-05-26 14:00
@jyoungyun Thank you for you hardwork on bringing up the Tizen infrastructure! We really appreciate it it being brought up on time for Preview2 :)

**Comment by jyoungyun** [comment] 2017-05-29 01:53
@gkhanna79 @dagood @eerhardt @joperezr @weshaggard @ericstj and all other developers who have helped me :)
Thank  you for giving me a detailed explanation and guide on Tizen infra bring-up. Thanks to you, I was able to proceed smoothly. Thank you very much :)

**Comment by jyoungyun** [comment] 2017-05-30 04:36
@gkhanna79 Can I know the sha1 value of below packages to provide the tizen runtime packages for Preview1 ? The version patch(https://github.com/dotnet/core-setup/pull/2330) was merged after May 01 so I couldn't get the sha1 value from coreclr package and the core-setup package seems to have not been built with the release process because the build number ends with -00. Should I create a package with the same number in Tizen? And can you give me a corresponding sha1 value?

coreclr : https://www.nuget.org/packages/Microsoft.NETCore.Runtime.CoreCLR/2.0.0-preview1-25301-02
core-setup : https://www.nuget.org/packages/Microsoft.NETCore.App/2.0.0-preview1-002111-00

I got the corefx sha value from [here](https://www.nuget.org/packages/Microsoft.NETCore.Platforms/2.0.0-preview1-25305-02).
corefx sha1 : af7d2ae49c79bb279625de4e92f7f91f9fe94f5d (build date:20170505-02)

**Comment by eerhardt** [comment] 2017-05-30 13:04
There are a few ways to figure out the coreclr sha:

1. We have 'tags' in GitHub for each release: https://github.com/dotnet/coreclr/commits/v2.0.0-preview1
1. If you look at the File Properties of `coreclr.dll` from https://www.nuget.org/packages/runtime.win-x64.Microsoft.NETCore.Runtime.CoreCLR/2.0.0-preview1-25301-02, you'll see we put the Commit Hash in the Product Version property

![image](https://cloud.githubusercontent.com/assets/8291187/26584325/08bb42fe-450e-11e7-9dbc-b10db236e716.png)

For core-setup:

1. we also have a tag in GitHub: https://github.com/dotnet/core-setup/commits/v2.0.0-preview1
1. If you look at the File Properties of `dotnet.exe` from https://www.nuget.org/packages/runtime.win-x64.Microsoft.NETCore.DotNetHost/2.0.0-preview1-002111-00, you'll see we put the Commit Hash in the Product Version property as well:

![image](https://cloud.githubusercontent.com/assets/8291187/26584467/79a882f6-450e-11e7-9896-d597857e987f.png)

**Comment by jyoungyun** [comment] 2017-05-31 01:11
@eerhardt Thank you :)

**Comment by gkhanna79** [comment] 2017-05-31 16:43
Now that @jyoungyun has been able to bringup the Tizen build infrastructure, it will be good to understand the plan for the Tizen issues marked for 2.0.0 Release:

 https://github.com/dotnet/coreclr/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-Tizen+milestone%3A2.0.0

@hqueue @jyoungyun @hseok-oh What are your thoughts? Also, for other issues in label area-Tizen but not marked for 2.0.0, have they been triaged as they are not targeted for .NET Core 2.0 release?

Two additional things:

1) This is just a reminder - the checkin bar is now extremely high to get fixes in for 2.0.0 PReview2/RTM. If you think there are issues that need to make it, please have a PR for 2.0.0 branch, with details on why it needs to be in .NET Core 2.0.0 Preview2/RTM and CC me on it. I will help shepherd it per the checkin-bar requirements.

2) We have made changes in Core-Setup and CoreFX (both master and release/2.0.0 branches) to build with portable RID (e.g. win-*, linux-*, osx-*) by default. We are working to get it completed for CoreCLR today (https://github.com/dotnet/coreclr/pull/11985 is the CoreCLR change for master, for example).

Since Tizen does not build for portable RID, please ensure you are passing "-PortableBuild=false" for all your build/packaging scenarios to ensure you are not accidentally going down the portable RID path.

**Comment by jyoungyun** [comment] 2017-06-01 01:42
@gkhanna79 I have passed "-PortableBuild=false" option in Tizen core-setup build/packaging scenarios. And Tizen CI is too. And as I know the #11975  PR should be merged in release/2.0.0. Please discuss the PR with @chunseoklee .

**Comment by jyoungyun** [comment] 2017-06-01 02:16
@gkhanna79 Should I add the "-PortableBuild=false" option to coreclr build? Even if I do not include the option, it is being built for tizen runtime. My command line is like below:
```
docker run --rm -v ${WORKSPACE}/dotnet_coreclr:/opt/code -w=/opt/code -e ROOTFS_DIR=/crossrootfs/${targetArch}.tizen.build hqueue/dotnetcore:ubuntu1404_cross_prereqs_v4-tizen_rootfs ./build.sh cross ${config} ${targetArch} cmakeargs -DFEATURE_GDBJIT=TRUE stripSymbols -OfficialBuildId=${buildid} -- /p:Authors=Tizen
```
And the latest release/2.0.0 branch of corefx still generates the tizen runtime. The master branch of corefx generates linux-armel runtime package. Should I add the option both release/2.0.0 and master branch?

**Comment by gkhanna79** [comment] 2017-06-01 02:36
@jyoungyun CoreCLR (master and 2.0.0) build for Tizen because of https://github.com/dotnet/coreclr/commit/a2abadfe7f67249cbe2b107d0b3f1b8d6f2ee06b#diff-0b83f9dedf40d7356e5ca147a077acb4R835.

> the master branch of corefx generates linux-armel runtime package.

@weshaggard has been looking into CoreFX branch. Since, for the Tizen build, the RID is expected to be tizen.4.0.0-armel, and not linux-armel, you should probably fix it in CoreFX master and 2.0.0 (for 2.0.0, please, loop @weshaggard  and me on the PR).

**Comment by gkhanna79** [comment] 2017-06-01 02:42
Actually, I misread your comment. @weshaggard made a change in CoreFX master that is still not in release/2.0.0 branch. @weshaggard can you confirm that once your change makes into 2.0.0, it will generate tizen RID?

**Comment by jyoungyun** [comment] 2017-06-01 03:48
@gkhanna79 
> can you confirm that once your change makes into 2.0.0, it will generate tizen RID?

I mean when I do not add "-PortableBuild=false" option, the release/2.0.0 branch generates linux-armel runtime pakcage but the master branch still generates tizen runtime packages. If I build master branch without the option, I think this should also generates linux-armel runtime package, but it is not. Is it normal operation?

Anyway I will add the "-PortableBuild=false" option for all builds (coreclr, corefx, core-setup already did) on both release/2.0.0 and master.

**Comment by gkhanna79** [comment] 2017-06-01 04:14
> If I build master branch without the option, I think this should also generates linux-armel runtime package, but it is not. Is it normal operation?

No, this is not expected. Can you please look into it to understand what is going on? Essentially:

1) Default (without any option specified) should produce portable RID packages (aka linux-armel).
2) -PortableBuild=true is same as (1) above.
3) -PortableBuild=false should produce Tizen RID specific packages.

If this does not happen, something is wrong.

**Comment by jyoungyun** [comment] 2017-06-01 09:08
@gkhanna79 When I build the latest master corefx code(https://github.com/dotnet/corefx/commits/fd6bae5b5500d51cb1255d277721ba836be14a24) with the "-PortableBuild=true" option (it is the same as default setting), it generates tizen runtime packages.

And today I upload the Microsoft.NETCore.App Preview1 packages for tizen runtime to Nuget.org. So now we can build application by using "tizen.4.0.0-armel" Runtime ID. :) Thank you for all developers help.

Then, I can not find the *.Private.CoreFX.* packages in Nuget.org. Is there any reason that you don't upload it? And should I upload the CoreCLR packages to Nuget.org ? If true, where does the CoreCLR runtime packages use ?

**Comment by gkhanna79** [comment] 2017-06-01 15:09
> So now we can build an application by using "tizen.4.0.0-armel" Runtime ID. :)

This is excellent - congratulations!

> but that option does not support space

@ericstj Do you have any suggestions? Would encoding the space work?

> And I couldn't find the Microsoft.Private.CoreFx.NETCoreApp and runtime package in Nuget.org

These packages are for our internal repo dependency closure only and are not supposed to be on nuget (only our development feeds like myget). @dagood can share the list of packages we upload to nuget that you can use as reference - excluding the Identity packages and private packages that you should not upload.

> And should I upload the CoreCLR packages to Nuget.org ? If true, where does the CoreCLR runtime packages use ?

Yes, you should be uploading the runtime.tizen.4.0.0-armel.* packages that you built to Nuget. If you can share the list that you have built, @dagood or I can help confirm it.

**Comment by dagood** [comment] 2017-06-01 16:12
Here's a list of every package we pushed for 2.0.0 preview1: https://gist.github.com/dagood/08610c5857be0a3b154ff01b9bd0d7e7. For example, a runtime package "set" for CoreCLR:

```
runtime.*.Microsoft.NETCore.ILAsm
runtime.*.Microsoft.NETCore.ILDAsm
runtime.*.Microsoft.NETCore.Jit
runtime.*.Microsoft.NETCore.Native
runtime.*.Microsoft.NETCore.Runtime.CoreCLR
runtime.*.Microsoft.NETCore.TestHost
```

and Core-Setup:
```
runtime.*.Microsoft.NETCore.App
runtime.*.Microsoft.NETCore.DotNetAppHost
runtime.*.Microsoft.NETCore.DotNetHost
runtime.*.Microsoft.NETCore.DotNetHostPolicy
runtime.*.Microsoft.NETCore.DotNetHostResolver
```

**Comment by weshaggard** [comment] 2017-06-01 18:46
>Anyway I will add the "-PortableBuild=false" option for all builds (coreclr, corefx, core-setup already did) on both release/2.0.0 and master.

To clarify for corefx builds the option is `-portable=false`. @gkhanna79 that was what I was trying to get you to use in coreclr as well. We should try to make this consistent.

**Comment by jyoungyun** [comment] 2017-06-07 01:42
@gkhanna79 @dagood 
> Yes, you should be uploading the runtime.tizen.4.0.0-armel.* packages that you built to Nuget. If you can share the list that you have built, @dagood or I can help confirm it.

I had the same runtime packages above. So I already uploaded the core-setup result packages but I didn't upload yet the coreclr result packages because I'm not sure why these packages should be uploaded to nuget and where it uses. All native files are already included in Core-setup runtime packages so we don't need CoreCLR runtime packages for `netcoreapp` build. Where does the CoreCLR runtime packages use?

@weshaggard 

> To clarify for corefx builds the option is -portable=false. @gkhanna79 that was what I was trying to get you to use in coreclr as well. We should try to make this consistent.

When I see the config.json file, the `porable` option is linked to `PortableBuild`. And in netci.groovy file in core-setup, it uses the `PortableBuild` option. On the other hands, coreclr and corefx use the `portable` option. Are you going to use different option in core-setup and coreclr/corefx?

**Comment by jyoungyun** [comment] 2017-06-07 05:00
I made a commit(https://github.com/dotnet/coreclr/commit/118ad17e94890a250622ce021f6e473dd860d9be) for using `-portable=false` option in coreclr. But as @weshaggard said, some patch should be merged first. Please let me know if you are ready. :)

**Comment by gkhanna79** [comment] 2017-06-07 06:01
> Where does the CoreCLR runtime packages use?

For consistency, we upload the CoreCLR repo produced packages incase folks wish to explicitly reference a specific version of the package and/or JIT package.

@jyoungyun Are you uploading them to nuget right now? I ask because we are not doing so for Preview2 until few more weeks.

I use the "-PortableBuild" option explicitly since that is the primary option that is passed to the "run" infrastructure (i.e. run.sh and run.cmd).

**Comment by weshaggard** [comment] 2017-06-07 17:33
>When I see the config.json file, the porable option is linked to PortableBuild. And in netci.groovy file in core-setup, it uses the PortableBuild option. On the other hands, corefx uses the portable option. Are you going to use different option in core-setup and coreclr/corefx? Or should I change the core-setup netci.groovy file too? Please confirm it then I will update as you guideline.

When I did the work originally I left it as "portable" to try and not break existing usages, however if coreclr and corefx are using `PortableBuild=false` then it would be easy to do the same in corefx to keep consistency. In fact feel free to do it in your https://github.com/dotnet/corefx/pull/20761 if you want to make it consistent.

**Comment by jyoungyun** [comment] 2017-06-09 05:24
@gkhanna79 

> @jyoungyun Are you uploading them to nuget right now? I ask because we are not doing so for Preview2 until few more weeks.

I just uploaded the CoreCLR packages to nuget.org. And I confirmed that an app restores `Microsoft.NETCore.Runtime.CoreCLR` with `2.0.0-preview1-25301-02` version successfully by using nuget feed.

**Comment by gkhanna79** [comment] 2017-06-09 14:02
@jyoungyun I simply asked that because we do not plan to upload to nuget until we decide on the build that will be shipped. Is there a reason you are not using myget feed for Tizen for this purpose?

**Comment by jyoungyun** [comment] 2017-06-12 03:35
@gkhanna79 For development, we are using Tizen myget feed. When you decide on the build that will be shipped, we will upload the same version to nuget. Preview1 was already uploaded to nuget before our infra setup. But our Tizen development want to restore Preveiw1 for Tizen by nuget feed so I just uploaded them. I just want to put nuget on the same set of things you upload to reduce the chaos of our Tizen developers. There is no problem using tizen feed only.

**Comment by gkhanna79** [comment] 2017-06-19 17:34
@hqueue @jyoungyun @hseok-oh Going forward, please loop in @weshaggard and @janvorli for any changes will be bringing in.

**Comment by jyoungyun** [comment] 2017-06-21 10:12
@gkhanna79 Okay Thanks :)

**Comment by Petermarcu** [comment] 2017-06-30 00:31
@jyoungyun do you see a need to keep this issue open at this point?

**Comment by danmosemsft** [comment] 2017-07-19 20:57
I think this has served its purpose.

**Closed by danmosemsft** 2017-07-19 20:57 UTC
Labels: area-Tizen, Discussion
