### ISSUE TITLE
Is it possible to improve exceptions message from unbox.any?

### ISSUE THREAD

**Issue by xunilrj** [dotnet/coreclr#7655] opened 2016-10-17 12:08 UTC
I was analyzing the runtime code and realized that maybe it is possible to improve the unbox.any exception message with the involved types.
For more details see:
http://stackoverflow.com/questions/39914845/why-does-unbox-any-not-provide-a-helpful-exception-text-the-way-castclass-do

For example:

```
IL_0001: newobj instance void [mscorlib]System.Text.StringBuilder::.ctor()
IL_0006: stloc.0
IL_0007: ldloc.0
IL_0008: castclass [mscorlib]System.String
```

As far as I understood, the runtime will step through these functions:
- https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/vm/interpreter.cpp#L6137
- https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/vm/eedbginterfaceimpl.cpp#L1633
- https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/vm/excep.cpp#L13997

wich will throw the InvalidCastException

`COMPlusThrow(kInvalidCastException, IDS_EE_CANNOTCAST, strCastFromName.GetUnicode(), strCastToName.GetUnicode());
`

This exception is detailed, it has both the castFromName and the castToName.
But with the following IL:

```
IL_0001: newobj instance void [mscorlib]System.Text.StringBuilder::.ctor()
IL_0006: stloc.0
IL_0007: ldloc.0
IL_0008: unbox.any [mscorlib]System.Int64
```

The runtime will call this function
at 
https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/vm/interpreter.cpp#L8766

for some reason the exception is thrown as

`COMPlusThrow(kInvalidCastException);`

So, my question is, could not the runtime do something like below and improve the exception message by having both the "From" and the "To" in its message?

```
auto thCastFrom = obj->GetTypeHandle();
auto thCastTo = TypeHandle(boxTypeClsHnd);
RealCOMPlusThrowInvalidCastException(thCastFrom, thCastTo);
```

I am still trying to compile the coreclr repository to make deeper analysis, so forget me if there is something obvious that I am no seeing.

**Comment by mikedn** [comment] 2016-10-17 12:28
Looks like a duplicate of #1453 which has been fixed already in .NET Core. However, the fix hasn't appeared in the .NET Framework yet.

**Comment by gkhanna79** [comment] 2017-03-09 18:20
Closing this issue for now as nothing appears actionable for the moment. Please feel free to reopen if there are followup questions.

**Closed by gkhanna79** 2017-03-09 18:20 UTC
Labels: FollowingUp
