### ISSUE TITLE
Several Interop tests failing in Helix on ARM

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#12488] opened 2017-06-27 19:48 UTC
The following Interop tests are failing:

> Interop_ArrayMarshalling._BoolArray_MarshalBoolArrayTest_MarshalBoolArrayTest_._BoolArray_MarshalBoolArrayTest_MarshalBoolArrayTest_cmd()
Interop_ArrayMarshalling._ByValArray_MarshalArrayByValTest_MarshalArrayByValTest_._ByValArray_MarshalArrayByValTest_MarshalArrayByValTest_cmd()
Interop_FuncPtrAsDelegateParam._FuncPtrAsDelegateParam_FuncPtrAsDelegateParam_._FuncPtrAsDelegateParam_FuncPtrAsDelegateParam_cmd()
Interop_MarshalAPI._IUnknown_IUnknownTest_IUnknownTest_._IUnknown_IUnknownTest_IUnknownTest_cmd()
Interop_NativeCallable._NativeCallableTest_NativeCallableTest_._NativeCallableTest_NativeCallableTest_cmd()
Interop_PrimitiveMarshalling._Bool_BoolTest_BoolTest_._Bool_BoolTest_BoolTest_cmd()
Interop_PrimitiveMarshalling._EnumMarshalling_EnumTest_EnumTest_._EnumMarshalling_EnumTest_EnumTest_cmd()
Interop_PrimitiveMarshalling._UIntPtr_PInvokeUIntPtrTest_PInvokeUIntPtrTest_._UIntPtr_PInvokeUIntPtrTest_PInvokeUIntPtrTest_cmd()
Interop_SizeConst._SizeConstTest_SizeConstTest_._SizeConstTest_SizeConstTest_cmd()
Interop_StringMarshalling._LPSTR_LPSTRTest_LPSTRTest_._LPSTR_LPSTRTest_LPSTRTest_cmd()
Interop_StringMarshalling._LPTSTR_LPTSTRTest_LPTSTRTest_._LPTSTR_LPTSTRTest_LPTSTRTest_cmd()
Interop_StringMarshalling._UTF8_UTF8Test_UTF8Test_._UTF8_UTF8Test_UTF8Test_cmd()

All failed with messages like:

> Expected: 100\r\nActual: -532462766

Interestingly, these tests all have native .dll's in their test directories, and several other Interop tests failed with a System.DllNotFoundException in failing to find the native .dll in _their_ test directory, so that may be related.

**Comment by wtgodbe** [comment] 2017-06-27 19:48
@yizhang82 can you route these failures to the right person?

**Comment by wtgodbe** [comment] 2017-06-27 19:48
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170626.03

**Comment by yizhang82** [comment] 2017-06-27 22:00
@botaberg Please work with @wtgodbe / @tijoytom to figure out where the problem is.

**Comment by botaberg** [comment] 2017-06-29 00:27
@wtgodbe do we know where these tests are looking when trying to load the DLLs (loader snaps)? This looks like a CoreCLR test infrastructure issue, and I do not know very much about this infrastructure.

Also, it is possible to get hold of a repro machine?

**Comment by tijoytom** [comment] 2017-06-29 00:34
@wtgodbe is this arm64 on wow32 mode?

**Comment by wtgodbe** [comment] 2017-06-29 01:02
@tijoytom I believe so (the tests were built for Arm32, but are running on Arm64 machines)

@botaberg they should be looking in their own directory, which is where we'd expect those .DLL's to be. You can find the binaries used to run these tests in Azure, in the storage account dotnetbuildoutput, in the container coreclr-beta-20170626-03-windows-test (The .dll is in the right place, so it's odd we're not finding it). @MattGal may be able to help you get a repro machine.

**Comment by MattGal** [comment] 2017-06-30 16:05
@tijoytom I'm happy to help get you onto a repro machine but only manually; we only have 8 currently and they're quite slow.  Ping me and we'll do that.

One thing I am recalling from setting up the CoreCLR repo's tests for normal Helix execution was that we had to manually install a CRT 14 MSI before stuff would work as expected.   If such a package is needed, we definitely have not done this already.  (This may have only been for < Windows 10 SKUs though?).  Definitely worth checking, although ideally tests would bring along their own specific dependencies.

**Comment by tijoytom** [comment] 2017-06-30 16:31
@MattGal You may be right , we can give that a try..Attaching a debugger and getting loader snaps should tell us what is missing.

**Comment by tijoytom** [comment] 2017-07-06 18:17
this should be fixed , @MattGal  update this issue when you get a change to fix the dependencies  for the test

**Comment by MattGal** [comment] 2017-07-06 18:19
@wtgodbe can you look into this?  I'm happy to help for any infra-related questions but this is simply a matter of payload construction

**Comment by BruceForstall** [comment] 2017-07-06 23:19
#12519 looks like the same failure as this.

**Comment by wtgodbe** [comment] 2017-07-10 18:33
@tijoytom do we know what package contains the missing binaries here? I can update the dependency list once I know what needs to be added

**Closed** 2017-07-13 18:45 UTC
Labels: arch-arm32, test-run-uwp-coreclr

**Comment by wtgodbe** [comment] 2017-07-13 20:09
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170713.02 these tests are now passing
