### ISSUE TITLE
CRST level violation using custom AssemblyLoadContext

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#23412] opened 2019-03-22 19:39 UTC
I was trying to extend [jitutils PMI](https://github.com/dotnet/jitutils) to use custom assembly load contexts and am hitting a CRST level lock violation.

I can provide a repro if needed; it is a bit messy.

An assembly is loaded into a custom context and PMI is using reflection to enumerate its types. This causes further assembly loading and the custom loader reads an environment var to determine where to search. Reading this env var triggers an array pool rental, which loads up event source, which tries to take a lock, and hits the level violation:
```
Assert failure(PID 18376 [0x000047c8], Thread: 18868 [0x49b4]): Consistency check failed:
Crst Level violation: Can't take level 18 lock CrstEventPipe because you already holding level 17 lock CrstPendingTypeLoadEntry
FAILED: false
```
Stack at this point is:
```

00 KERNELBASE!DebugBreak
01 KERNELBASE!wil::details::DebugBreak
02 CoreCLR!CHECK::Setup
03 CoreCLR!CrstBase::IsSafeToTake
04 CoreCLR!CrstBase::Enter
05 CoreCLR!CrstBase::CrstHolder::{ctor}
06 CoreCLR!EventPipeConfiguration::RegisterProvider
07 CoreCLR!EventPipeConfiguration::CreateProvider
08 CoreCLR!EventPipe::CreateProvider
09 CoreCLR!EventPipeInternal::CreateProvider
0a System_Private_CoreLib!ILStubClass.IL_STUB_PInvoke(System.String, EtwEnableCallback)
0b System_Private_CoreLib!System.Diagnostics.Tracing.EventPipeEventProvider.System.Diagnostics.Tracing.IEventProvider.EventRegister(System.Diagnostics.Tracing.EventSource, EtwEnableCallback, Void*, Int64 ByRef)
0c System_Private_CoreLib!System.Diagnostics.Tracing.EventProvider.EventRegister(System.Diagnostics.Tracing.EventSource, EtwEnableCallback)
0d System_Private_CoreLib!System.Diagnostics.Tracing.EventProvider.Register(System.Diagnostics.Tracing.EventSource)
0e System_Private_CoreLib!System.Diagnostics.Tracing.EventSource.Initialize(System.Guid, System.String, System.String[])
0f System_Private_CoreLib!System.Buffers.ArrayPoolEventSource..ctor()
10 System_Private_CoreLib!System.Buffers.ArrayPoolEventSource..cctor()
11 CoreCLR!CallDescrWorkerInternal
12 CoreCLR!`DispatchCallDebuggerWrapper'::`6'::__Body::Run
13 CoreCLR!DispatchCallDebuggerWrapper
14 CoreCLR!DispatchCallSimple
15 CoreCLR!MethodTable::RunClassInitEx
16 CoreCLR!MethodTable::DoRunClassInitThrowing
17 CoreCLR!MethodTable::CheckRunClassInitThrowing
18 CoreCLR!DynamicHelperFixup
19 CoreCLR!DynamicHelperWorker
1a CoreCLR!DelayLoad_Helper
1b System_Private_CoreLib!System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1[[System.Char, System.Private.CoreLib]].Rent(Int32)
1c System_Private_CoreLib!System.Environment.GetEnvironmentVariableCore(System.String)
1d System_Private_CoreLib!System.Environment.GetEnvironmentVariable(System.String)
1e pmi!Resolver.Resolve(System.String, System.Runtime.Loader.AssemblyLoadContext)
1f pmi!CustomLoadContext.Load(System.Reflection.AssemblyName)
20 System_Private_CoreLib!System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(System.Reflection.AssemblyName)
21 System_Private_CoreLib!System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr, System.Reflection.AssemblyName)
22 CoreCLR!CallDescrWorkerInternal
23 CoreCLR!MethodDescCallSite::CallTargetWorker
24 CoreCLR!MethodDescCallSite::Call_RetOBJECTREF
25 CoreCLR!RuntimeInvokeHostAssemblyResolver
26 CoreCLR!BINDER_SPACE::AssemblyBinder::BindUsingHostAssemblyResolver
27 CoreCLR!CLRPrivBinderAssemblyLoadContext::BindAssemblyByName
28 CoreCLR!AssemblySpec::Bind
29 CoreCLR!AppDomain::BindAssemblySpec
2a CoreCLR!PEFile::LoadAssembly
2b CoreCLR!Module::LoadAssembly
2c CoreCLR!Assembly::FindModuleByTypeRef
2d CoreCLR!ClassLoader::LoadTypeDefOrRefThrowing
2e CoreCLR!ClassLoader::LoadApproxTypeThrowing
2f CoreCLR!ClassLoader::LoadApproxParentThrowing
30 CoreCLR!ClassLoader::CreateTypeHandleForTypeDefThrowing
31 CoreCLR!ClassLoader::CreateTypeHandleForTypeKey
32 CoreCLR!ClassLoader::DoIncrementalLoad
33 CoreCLR!ClassLoader::LoadTypeHandleForTypeKey_Body
34 CoreCLR!ClassLoader::LoadTypeHandleForTypeKey
35 CoreCLR!ClassLoader::LoadTypeDefThrowing
36 CoreCLR!ClassLoader::LoadTypeDefOrRefThrowing
37 CoreCLR!GetTypesInner
38 CoreCLR!COMModule::GetTypes
39 System_Private_CoreLib!System.Reflection.RuntimeModule.GetTypes()
3a System_Private_CoreLib!System.Reflection.Assembly.GetTypes()
3b pmi!Worker.LoadTypes(System.Reflection.Assembly)
3c pmi!Worker.Work(System.String)
3d pmi!PrepareMethodinator.Main(System.String[])
3e CoreCLR!CallDescrWorkerInternal
3f CoreCLR!MethodDescCallSite::CallTargetWorker
40 CoreCLR!MethodDescCallSite::Call_RetArgSlot
41 CoreCLR!``RunMain'::`30'::__Body::Run'::`5'::__Body::Run
42 CoreCLR!`RunMain'::`30'::__Body::Run
43 CoreCLR!RunMain
```

**Comment by jkotas** [comment] 2019-03-22 20:19
@cshung Is this covered by the Crst leveling fixes that you have been working on?

**Comment by sywhang** [comment] 2019-03-22 21:31
cc @jorive @noahfalk

**Comment by noahfalk** [comment] 2019-03-22 22:38
@cshung is out on a recruiting trip but I'm not aware his testing had yet encountered it.

I suspect it could be resolved by adding PendingTypeLoadEntry > EventPipe to the ordering rules.

**Comment by sywhang** [comment] 2019-03-23 00:19
I'm hitting the same assertion error with https://github.com/dotnet/coreclr/pull/23379/ (still WIP) which addresses part of #23087 . I'll fix this in that PR while I'm at it.

**Comment by tommcdon** [comment] 2019-04-15 18:01
@sywhang has this issue been fixed?

**Comment by sywhang** [comment] 2019-04-17 21:06
I'll be taking out the relevant bits out of #23379 and submit a new PR since #23379 has some more work to do.

**Comment by tommcdon** [comment] 2019-04-26 17:36
@AndyAyersMS can you let us know if #24101 fixed this issue

**Comment by tommcdon** [comment] 2019-05-17 23:58
@AndyAyersMS we are closing this issue - let us know if the problem is not resolved

**Closed by tommcdon** 2019-05-17 23:58 UTC
Labels: area-Tracing

**Comment by AndyAyersMS** [comment] 2019-05-18 00:43
I'll revive the changes I had that ran into this and see if it now works.

**Comment by AndyAyersMS** [comment] 2019-05-18 01:09
Yes, seems to be working now. Thanks!

**Comment by tommcdon** [comment] 2019-05-18 01:10
@AndyAyersMS thanks for the confirmation!
