### ISSUE TITLE
Assertion when coregen-ing mscorlib.dll with JitStress= 1 or 2 on Linux

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2511] opened 2016-01-03 23:13 UTC
A failure in the Jit code. Happens with stress modes set to 1 and 2 (JitStress flag) and debug build of the CoreCLR. Assertion failure in lowerxarch.cpp, line 307.

Command to get it:
crossgen /App_Paths . /Platform_Assemblies_Paths . /MissingDependenciesOK  ./mscorlib.dll

Also happens for Microsoft.CodeAnalysis.VisualBasic.dll and Microsoft.CodeAnalysis.Workspaces.dll 
and Microsoft.CodeAnalysis.Workspaces.portable.dll.

The exact assertion is:
Assert failure(PID 49573 [0x0000c1a5], Thread: 49573 [0xc1a5]): Assertion failed 'varDsc->lvDontPromote' in 'System.Decimal:Remainder(struct,struct):struct' (IL size 257)

    File: /home/lubo/SVS/src/jit/lowerxarch.cpp Line: 307
    Image: /home/lubo/coreclr-tests/Windows_NT.x64.Debug/Tests/coreoverlay/crossgen

Aborted (core dumped)

**Comment by sivarv** [comment] 2016-01-04 23:54
This is a duplicate of issue #2297 . Mark this one as closed by pasting repro steps to issue #2297

**Closed** 2016-01-04 23:56 UTC
Labels: bug, CodeGen, CrossGen/NGEN
