### ISSUE TITLE
ARM64: GC Stress infrastructure 

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3824] opened 2016-03-19 00:45 UTC
Area: GC
Estimate 1 week

**Comment by russellhadley** [comment] 2016-03-19 07:41
@swaroop-sridhar can you take a look at what we need to do to get the GC Stress infra up for ARM64?

**Comment by swaroop-sridhar** [comment] 2016-03-21 19:46
Yes, I spoke to Aditya on Friday, and got some pointers about what needs to be done.
I'm working on the first step #3772

**Comment by swaroop-sridhar** [comment] 2016-04-05 01:17
GC_Stress=0xC infrastructure seems to be working for ARM64.
I verified that the VM sprinkles the invalid-instruction traps, and starts a GC at every legal instruction when in stress mode. 

The stress-runruns into a failure after about 15 collections in the Appdomain.SetupDomain function of MsCorlib. Investigating this now -- this failure seems to be caused by a VM  bug (not related to the GCstress infrastructure itself).

**Comment by swaroop-sridhar** [comment] 2016-04-16 00:26
We are now able to run several tests with GCStress on ARM64.
Resolving this issue, since test pass is covered by #3825

**Closed by swaroop-sridhar** 2016-04-16 00:26 UTC
Labels: ARM64, GCStress, VM
