### ISSUE TITLE
Unsafe.As produces incorrect data with Vectors (in Release) 

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#16254] opened 2018-02-07 17:53 UTC
Follow on from https://github.com/dotnet/coreclr/issues/15237

Seem to still be getting bad results https://github.com/dotnet/corefx/pull/25510#issuecomment-363304529

```
at System.Numerics.Tests.QuaternionTests.QuaternionAddTest()
 in System.Numerics.Vectors\tests\QuaternionTests.cs:line 545
Assert.Equal() Failure
Expected: {X:6 Y:8 Z:10 W:12}
Actual:   {X:2.978865E-34 Y:5 Z:6 W:7}
```

```csharp
public static Quaternion Add(Quaternion value1, Quaternion value2)
{
    Vector4 q1 = Unsafe.As<Quaternion, Vector4>(ref value1);
    Vector4 q2 = Unsafe.As<Quaternion, Vector4>(ref value2);

    Vector4 result = q1 + q2;

    return Unsafe.As<Vector4, Quaternion>(ref result);
}
```
```csharp
public void QuaternionAddTest()
{
    Quaternion a = new Quaternion(1.0f, 2.0f, 3.0f, 4.0f);
    Quaternion b = new Quaternion(5.0f, 6.0f, 7.0f, 8.0f);

    Quaternion expected = new Quaternion(6.0f, 8.0f, 10.0f, 12.0f);
    Quaternion actual;

    actual = Quaternion.Add(a, b);
    Assert.Equal(expected, actual);
}
```

The aim is to make use of the Vector acceleration for Quaternions

**Comment by AndyAyersMS** [comment] 2018-02-07 19:41
Do we know if this is the same underlying issue as #16210?

**Comment by xoofx** [comment] 2018-02-07 20:56
> Do we know if this is the same underlying issue as #16210?

Intuitively, I would say unlikely. For #16210 the problem is that we are taking the address of a single field (while fixed on `this` is working) but here this is just a plain cast from/to Vector4/Quaternion, looks more related to SIMD. Same code without SIMD structs (with plain struct) should just work.

**Closed** 2018-02-08 19:43 UTC
Labels: area-CodeGen, bug
