### ISSUE TITLE
sleep1 needs more tolerance

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#10312] opened 2017-03-20 17:24 UTC
```
MESSAGE:
The sleep function slept for 201 ms when it should have slept for 50 ms
+++++++++++++++++++
STACK TRACE:
```

I guess this could be increased in the sleep tests (?)
```
/* Milliseconds of error which are acceptable Function execution time, etc. */
DWORD AcceptableTimeError = 150;
```

https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/pal/tests/palsuite/threading/SleepEx/test1/test1.cpp

**Comment by kouvel** [comment] 2017-03-20 17:49
Duplicate of #8321, I'll disable the sleep tests for the moment

**Closed by kouvel** 2017-03-20 17:49 UTC
Labels: area-PAL, test bug
