### ISSUE TITLE
Add String.Contains(String, StringComparison) overload

### ISSUE THREAD

**Issue by Atomosk** [dotnet/coreclr#2251] opened 2015-12-06 09:13 UTC
Currently you have to use IndexOf:
```
"ABA".IndexOf("ab", StringComparison.InvariantCultureIgnoreCase) >= 0
```
With new api it will be
```
"ABA".Contains("ab", StringComparison.InvariantCultureIgnoreCase)
```

**Comment by mikedn** [comment] 2015-12-06 09:51
Looks like a duplicate of dotnet/corefx#1565

**Closed** 2015-12-06 11:36 UTC
