### ISSUE TITLE
Assembly.LoadFrom throws 'already loaded' even if the assembly is not in memory

### ISSUE THREAD

**Issue by raffaeler** [dotnet/coreclr#12764] opened 2017-07-12 10:50 UTC
I am using 2.0.0-preview1-005977.
I have a Self Contained Deployment folder with all the needed dependencies to run my code.
The hosting part (exe) is in C++, so I load the CLR, create the AppDomain, load a first Assembly and everything works fine.

Later on, when C++ requests for it, I execute some .net code that execute an Assembly.LoadFrom(fullpathassemblyname.dll).
This causes the following exception:
`System.IO.FileLoadException: 'Assembly with same name is already loaded'`
But the assembly is not in memory. I can't see it either in VS Modules while debugging or even in process explorer.

The code I use to load the assembly is:
`var assembly = Assembly.LoadFrom(fullname);`
or
`var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(fullname);`
For testing purposes only I also tried the following:
`var assembly = Assembly.LoadFile(fullname);`
and it works but it is not suitable as it loads just the given assembly and not the entire graph (if any).

So I have two questions:
- why Assembly.LoadFrom throws even if the given assembly is not in memory?
- if I remember well, the Assembly.LoadFrom of the .NET Framework does not throw even if the assembly was already loaded. Why did the behavior change?

**Comment by gkhanna79** [comment] 2017-07-12 21:55
Is the assembly being loaded present on the TPA path you constructed for your host?

**Comment by raffaeler** [comment] 2017-07-12 22:06
Yes it is, but given that I will allow others to 'drop' other assemblies in any folder, I would prefer not to make special cases for the assemblies in TPA.
Does this change the LoadFrom behavior? It never did AFAIR.

**Comment by gkhanna79** [comment] 2017-07-12 22:21
.NET Core Binder/Loader are very different, by design, from Desktop Loader. Please see https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md for details. Assembly.LoadFrom is equivalent to loading in DefaultContext.

We are running into a failure at https://github.com/dotnet/coreclr/blob/13e7c4368da664a8b50228b1a5ef01a660fbb2dd/src/vm/assemblynative.cpp#L230. It is possible that the message may not be the most appropriate but looks like we did run into an error loading the assembly.

CC @kouvel

**Comment by raffaeler** [comment] 2017-07-13 06:14
I still don't get the problem.
Since I can it using Assembly.LoadFile, I know the assembly is good and the path is correct.
Also, even after failing with LoadFrom, the load succeeds if I invoke Type.GetType(full type name).

Even if the path is full qualified, it contains a "..\" segment. Do you believe this can be the problem? (I can't test until later today, GMT+1 time).

**Comment by jkotas** [comment] 2017-07-13 07:08
> Even if the path is full qualified, it contains a ".." segment. Do you believe this can be the problem?

Unlikely. The first thing done by LoadFrom is to normalize the path using Path.GetFullPath that will eliminate the ".." segment:

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Reflection/Assembly.CoreCLR.cs#L74

**Comment by raffaeler** [comment] 2017-07-13 08:49
@jkotas I see.
Do you have any specific test I can make to better diagnose the problem?
For example I can run procmon to see what happens at the filesystem level.
Are there any CoreCLR environment vars to set to see a verbose tracer here?

Thanks

**Comment by jkotas** [comment] 2017-07-13 09:02
I would run the process under C++ debugger (either attach as "native" in visual studio; or use windbg), stop on C++ exception and get the stacktrace where the C++ exception is thrown. The C++ part of the runtime is using C++ exceptions for error handling, so stopping on C++ exceptions tends to be a good way to find out where things went wrong.

**Comment by raffaeler** [comment] 2017-07-13 09:18
@jkotas As my host is C++, it will be extremely simple to do later this night.
Are the symbols for the  2.0.0-preview1-005977 on the public MS server or should I clone the matching branch from the coreclr repo and build?

**Comment by jkotas** [comment] 2017-07-13 09:24
Yes, the symbols should be published.

**Comment by raffaeler** [comment] 2017-07-13 19:56
@jkotas the exception happens in this function:
[LoadFromPath](https://github.com/dotnet/coreclr/blob/13e7c4368da664a8b50228b1a5ef01a660fbb2dd/src/vm/assemblynative.cpp#L250)

This function throws if the dll exists in the TPA path but you try to load from a different path.
In other words I had this situation:
- The TPA contains the 'release' version of the dll
- LoadFrom tries to load the 'debug' version from a different path
If I delete the file in the TPA *or* try to load the file inside the TPA, it works.
(sorry, I initially believe the file was loaded from the TPA)

Questions:
- Is this a bug or what?
- I loaded the symbols but there is no source. Can I load the sources from github or what should I do to see them?

Thank you

**Comment by gkhanna79** [comment] 2017-07-13 20:03
This is by design.


Thanks,
Gaurav

________________________________

**Comment by raffaeler** [comment] 2017-07-13 20:06
@gkhanna79 thanks to you.
Is there any chance to obtain a more specific message?
I was totally cheated from the message, otherwise it would have been easier to find the culcprit.

**Comment by jkotas** [comment] 2017-07-13 20:18
> Can I load the sources from github or what should I do to see them?

All .NET Core .dlls are stamped with git SHA1 hash they were built from (e.g. look for "Commit Hash" string in the binary). The VS debugger will eventually learn 

> Is there any chance to obtain a more specific message?

Yes. Would you mind submitting PR to improve the message, or describe what you would like to see in the message?

**Comment by raffaeler** [comment] 2017-07-13 21:41
@jkotas got it but the sources does not show up even if I enabled the source server support in the options.
The github path should already be in the pdb themselves, so what I am missing?

There are a couple of points where the same exception is thrown. I am trying to get the exact point with the sources and than I can submit the PR.

Thanks

**Comment by raffaeler** [comment] 2017-07-16 08:58
@jkotas In other words, what is your GitLink setup to sync the public sources with this repo sources?
I tried in several ways with no luck at all...
Thank you

**Comment by jkotas** [comment] 2017-07-16 19:31
> The github path should already be in the pdb themselves, so what I am missing?

I do not think that the binaries are getting stamped properly for source server or gitlink to work. @dotnet/dnceng What is missing to get the source server or gitlink working for .NET Core binaries?

Here are  steps that I have been using to get matching sources for given coreclr.dll (substitute `c:\dotnet` and `c:\coreclr` as appropriate):

```
c:\>powershell (Get-Item c:\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview1-001978-00\coreclr.dll).VersionInfo.FileVersion
4.6.25212.04 built by: dlab-DDVSOWINAGE006. Commit Hash: 79727651f0cab62c46cb1fe34e12f2122d6d554c
c:\>cd coreclr & git checkout 79727651f0cab62c46cb1fe34e12f2122d6d554c
```

**Comment by raffaeler** [comment] 2017-07-16 20:35
I read about the hash being in the FileVersion attribute, but without gitlink, the debugger will never know where to look for the sources, even if I download the whole repo with the matching hashes.
There must be some additional step I am now aware of...

**Comment by dleeapho** [comment] 2017-07-17 20:06
@dagood, can you help with @jkotas question?

**Comment by dagood** [comment] 2017-07-17 21:01
@jkotas Adding gitlink to the builds so that sources are indexed to GitHub is tracked by https://github.com/dotnet/core-eng/issues/499. It seems to me that we'll also need to get more serious about building portable PDBs, as a prereq: Windows builds are still making Windows PDBs right now. I'm not able to find a discussion (issue on CoreCLR or core-eng) about moving to Portable PDBs.

The external source server support we've had for some products is based on MyGet. If a symbol package has sources matching the PDBs, MyGet does some PDB rewriting and hosts the sources for us. I haven't seen CoreCLR put native code in the symbol packages. There's also the issue of Core-Setup redistributing the CoreCLR bits: I don't know what the MyGet behavior would be, and these sources might need to be flowed to Core-Setup too. Not sure this path is worth going down vs. gitlink to GitHub.

@raffaeler I haven't tried it for native debugging, but in my experience I get a dialog box that I can point to the current source file, then the debugger find others based on that. With the repo checked out on disk at the right commit, I would think you can rig it up that way.

**Comment by jkotas** [comment] 2017-07-17 21:24
@dagood This discussion is about gitlink support for C/C++ code. I believe that gitlink works for C/C++ fine, with classic non-portable PDBs. The portable PDBs should not be tied to this.

**Comment by raffaeler** [comment] 2017-07-17 21:45
@dagood the link you posted gave me a 404.
I tried putting a function breakpoint but VS2017.3 didn't ask me to find the source file, therefore I can't make it work. I guess I am missing something.
Also, if I have to browse the sources, what is gitlink useful for?

P.S. afaik gitlink works with old pdbs while sourcelink/sourcelinkv2 work with portable pdbs

**Comment by MattGal** [comment] 2017-07-17 21:51
@raffaeler that's because it's a private repository.

**Comment by dagood** [comment] 2017-07-17 23:04
@jkotas Noted, thanks.

@raffaeler Ah, I was thinking of the situation where you're already paused somewhere (e.g. at an exception). I'm not sure about setting a breakpoint first. To clarify about gitlink: in that section I was talking about a potential way to do this *without* gitlink to get where you need to go, because currently it's not in place.

**Comment by mjsabby** [comment] 2017-07-25 06:07
Also commenting here for completeness: We should stick to the SourceLink specification (https://github.com/dotnet/core/blob/master/Documentation/diagnostics/source_link.md) regardless of what tool we end up using to stamp the pdb.

Specifically injecting something like the following into the PDB (got this from the source link spec):

{
    "documents": {
        "C:\\src\\CodeFormatter\\*": "https://raw.githubusercontent.com/dotnet/codeformatter/bcc51178e1a82fb2edaf47285f6e577989a7333f/*"
    }
}

**Comment by raffaeler** [comment] 2017-07-26 06:57
@mjsabby I still can't understand if there is any way to get it work with the current bits.
I am trying with gitlink with no luck, but if you tell me that it works with sourcelink or any other way, it is fine for me.
Please note that I would need to make it work with both (or alternatively) native and managed code.

Thank you

**Comment by dagood** [comment] 2017-07-31 14:04
@raffaeler The talk about SourceLink and GitLink is about what we can add to future builds to make the debugging process better. I'm not aware of anything that will help you set source breakpoints in your current 2.0.0-preview1 build.

**Comment by raffaeler** [comment] 2017-07-31 20:49
Thank you @dagood. So basically when you want to debug, you clone the repo locally, then rebuild and than point your runtime to these binaries?
Or do you think that I can tweak the pdbs to force pointing to github (or a local clone)?

**Comment by dagood** [comment] 2017-07-31 21:24
I haven't debugged CoreCLR myself, but building your own CoreCLR does sound like the most straightforward way to get PDBs pointing at your sources.

I believe MyGet repoints PDBs for their symbol package sources support, meaning it's possible, but I'm not familiar with tooling to do that.

**Comment by raffaeler** [comment] 2017-07-31 21:39
@jkotas do you have any suggestion? What is your strategy? TIA

**Comment by jkotas** [comment] 2017-08-01 01:56
When I want to debug, I checkout the sources that match the build:  https://github.com/dotnet/coreclr/issues/12764#issuecomment-315631416 . No rebuilding required.

**Closed** 2017-09-21 15:49 UTC
Labels: area-Assembly Loader
