### ISSUE TITLE
CodeGen for WebAssembly

### ISSUE THREAD

**Issue by ghost** [dotnet/coreclr#5303] opened 2016-05-28 09:09 UTC
WebAssembly (wasm): http://webassembly.github.io/ 

According to MicrosoftEdge status page -> https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webassemblymvp?filter=f3f0000bf&search=WebAssembly, WebAssembly is in development.

IMO, it would be great to consolidate efforts right from the beginning between Edge, CoreCLR/CoreRT and VC teams to provide robust WebAssembly code generation and optimizations.

In case of LLILC the LLVM compiler has already started to support WebAssembly, but having first hand code gen in CoreCLR has its own advantages. Perhaps we can have a draft implementation started in CoreCLR where community can chime in?

**Comment by jkotas** [comment] 2016-06-01 10:50
WebAssembly version of CoreCLR would be pretty hard to do. CoreRT is better candidate for this. 

It should not be hard to built a small demo - using CoreRT CppCodeGen - that compiles and runs a simple program as WebAssembly. It can be then iterated on from there (e.g. generate the WebAssembly directly without going through CppCodeGen, etc.).

**Comment by jkotas** [comment] 2016-06-02 16:53
https://github.com/WebAssembly/design/blob/master/GC.md would be likely required to make this practical for C#.

**Comment by jasonwilliams200OK** [comment] 2016-06-06 22:53
Thanks @jkotas!

There is their official tool-chain for experimentation: https://github.com/WebAssembly/binaryen.

Here are the simple build steps for Windows (VC++ build tools / VS2015) which I just updated:https://github.com/brakmic/brakmic/blob/master/webassembly/COMPILING_WIN32.md.

In four simple commands (given msbuild v14+, cmake 3+ and git 2+ in PATH):

```cmd
git clone https://github.com/WebAssembly/binaryen.git --recursive
cd binaryen
cmake .
cmake --build . --config Release
```

it produces assembler, disassembler, linker and decompiler etc.:

```cmd
asm2wasm.exe
binaryen-shell.exe
binaryen.dll
binaryen.js
empty.txt
s2wasm.exe
wasm-as.exe
wasm-dis.exe
wasm.js
```

We can probably incorporate this tool-chain (or take some inspirations) for CoreRT and add the spec suite as a submodule to validate the conformance.

Can you please take a look and point me to the area of CppCodeGen to focus on so I don't get lost in figuring out the starting point. :)

**Comment by jkotas** [comment] 2016-06-06 23:16
"Using CPP Code Generator" steps at https://github.com/dotnet/corert/blob/master/Documentation/how-to-build-and-run-ilcompiler-in-visual-studio-2015.md are probably the place to start.

**Comment by svick** [comment] 2016-06-18 00:28
[ilwasm](https://github.com/WebAssembly/ilwasm), an incomplete IL to wasm compiler might also be of interest.

**Comment by jasonwilliams200OK** [comment] 2016-07-15 19:39
@kg, do you think the CoreRT route would help ilwasm project or somehow efforts can be combined to build something awesome? I am scratching the surface with binaryen's S-Expression builder in conjunction with 'building ilcompiler' doc suggested by @jkotas above.

**Comment by kg** [comment] 2016-07-16 05:05
You could AOT-compile large portions of an application to webassembly, yes. Given the runtime constraints, though, I don't know how far this would get you. I believe Unity does an IL->C++->x mapping right now with Emscripten, and that approach generally works, but is constrained.

**Comment by zezba9000** [comment] 2016-07-23 19:50
@kg Why would compiling IL to C/C++ be constrained?

**Comment by jasonwilliams200OK** [comment] 2016-09-01 22:07
Related: WASM MVP progress on JavaScript engine: https://github.com/Microsoft/ChakraCore/issues/1127.

**Comment by Thaina** [comment] 2017-04-14 08:49
Nearly a year now we have working webassembly on browser

Are there any plan we could hope for yet?

**Comment by kg** [comment] 2017-04-14 08:51
The initial version of the WebAssembly spec is missing some things you'd need for a first-class .NET implementation, but a stripped down version of mono applications might be feasible. Lots of legwork to be done to prove it, though.

**Comment by listepo** [comment] 2017-05-26 10:52
Any news?

**Comment by Thaina** [comment] 2017-05-26 11:05
@kg I wish we don't need to AOT the C#. Because webassembly actually don't need AOT. IL should directly convert to wasm. Both system could do dynamic codegen

I use unity webgl everyday and I would like to say that it totally impractical. Round trip and limitation caused by unnecessary AOT is too much headache

**Comment by zezba9000** [comment] 2017-05-26 15:33
Funny how Mono ran on nacl and pnacl for years without the need for AOT. I remember running Unity3D's version (and a custom build) on old Linux computers with NaCl and it ran fast and used very little ram. Now with WASM, its slow and uses tons of ram. Really wish pnacl was just been adopted across browsers instead (as it has been powerful and full featured for years [.NET Core could probably be make to run on it without AOT]).

For now because the .NET eco system still lacks a "stable" cross platform UI you might look into using Bridge.NET. If you're writing games, not sure whats faster though, Bridge.NET, JSIL or Unity3D for C#.

**Comment by kg** [comment] 2017-05-26 15:41
WASM will eventually be able to handle JIT (at least for some scenarios), so the question is how long it will take for it to arrive, and whether WASM JIT will be performant or expressive enough to cut it for .NET Core's runtime or for Unity games. My informed guesses would be based on dated information, since I haven't been involved in the WASM spec process for a while.

For more limited scenarios where you just need to JIT a little code at runtime, you can generate blobs of regular JS and let the javascript VM compile those on the fly to interact with your heap. Your performance is going to suffer though, from the 1-2 punch of losing WASM optimizations and having to reach across the WASM foreign function interface (it has pinvoke-ish overhead for crossing runtime boundaries, much like asm.js)

When it comes to performance right now your best bet is still an Emscripten-based toolchain (Unity3d uses it). The main caveat is that the Emscripten approach has startup time and memory usage issues but the performance (once started) is difficult to beat. Emscripten can also produce WebAssembly executables right now, IIRC.

**Comment by zezba9000** [comment] 2017-05-26 16:13
> but the performance (once started) is difficult to beat
From benchmarks I've seen on the web for rendering instanced objects in WebGL, pnacl was around 4x as fast as asm.js in real world situations. Same goes for physics simulations. WASM is a good notion but I see it as a regressive effort for what exists today in the Chrome browser. Not all competition is healthy (but thats a different matter).

**Comment by Thaina** [comment] 2017-08-08 11:15
For such times we was thinking about webassembly approach as compilation target for C# or IL so we need to build a compiler for translation. But I have seen some small size VM was built to run VM itself in the webassembly

So is it possible that we could build the coreCLR / coreRT itself into VM on webassembly and just throw pure IL into that VM?

**Comment by gulshan** [comment] 2017-08-08 11:47
https://github.com/aspnet/Blazor-Hackathonhttps://github.com/aspnet/Blazor-Hackathon seems relevant.

**Comment by zezba9000** [comment] 2017-08-08 18:21
Blazor-Hackathon uses DotNetAnywhere (DNA) which is an interpreted .NET runtime. Bridge.NET which compiles to JS probably gets better performance. We need CoreRT to function like Unity's IL2CPP so we can target any C/C++ compiler and thus any platform/environment with minimal work.

**Comment by Thaina** [comment] 2017-08-09 01:44
@zezba9000 Isn't dotnet core written in C++? If so can we just emscripten it?

**Comment by zezba9000** [comment] 2017-08-09 03:22
@Thaina No because the JIT has to made to support each platform target, x86, x64, ARM, MIPS, SPARK, RISC-V, WASM, etc. If you compile .NET IL directly to "C98" for example you could target almost any platform out there with little work (its why Unity3D made IL2CPP). I would guess the GC would be the part needing tweaks to get it working on some platforms. In fact with a GC designed for low memory you could probably replace .NET Micro with CoreRT getting huge performance and memory boosts.

**Comment by morganbr** [comment] 2017-10-03 21:05
We’ve started a WebAssembly experiment in the CoreRT repo and we need your help! Take a look at https://github.com/dotnet/corert/issues/4659 for more details on what’s happening and how to get involved.

**Comment by morganbr** [comment] 2018-05-03 23:56
Sounds good. Closing against dotnet/corert#4659.

**Closed by morganbr** 2018-05-03 23:56 UTC
Labels: area-CodeGen, enhancement
