### ISSUE TITLE
"Failed to generate native image for mscorlib." happened when build mscorlib for Linux/ARM on Ubuntu 14.04

### ISSUE THREAD

**Issue by leemgs** [dotnet/coreclr#3529] opened 2016-03-05 03:38 UTC
I have been doing the cross build of the mscorlib from coreCLR on Ubuntu 14.04 x86 64bit PC. There are two methods  to generated managed mscorlib binary for Linux/ARM on Ubuntu 14.04 PC as following:
First method is to build entire codes of coreCLR (including mscorlib):
u14.04@leemgs$> time ROOTFS_DIR=/work/dotnet/rootfs-coreclr/arm ./build.sh arm release clean cross skiptests
Second method is to build only mscorlib:
u14.04@leemgs$> time ./build.sh arm release clean verbose 

Anyone who tried to do first method?  I have got the "Failed to generate native image for mscorlib." error message.
#### Error messages

```
                        . . . . .  OMISSION . . . . 
warn : Detected package downgrade: Microsoft.Build.Utilities.Core from 0.0.0 to 0.1.0-preview-00017 
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Targets (>= 0.1.0-preview-00017) -> Microsoft.Build.Utilities.Core  
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Utilities.Core (>= 0.1.0-preview-00017)
warn : Detected package downgrade: Microsoft.Build.Tasks.Core from 0.0.0 to 0.1.0-preview-00017 
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Targets (>= 0.1.0-preview-00017) -> Microsoft.Build.Tasks.Core  
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Tasks.Core (>= 0.1.0-preview-00017)
warn : Detected package downgrade: MSBuild from 0.0.0 to 0.1.0-preview-00017 
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Targets (>= 0.1.0-preview-00017) -> MSBuild  
warn :  tool-runtime (>= 1.0.0) -> MSBuild (>= 0.1.0-preview-00017)
warn : Detected package downgrade: Microsoft.Build.Framework from 0.0.0 to 0.1.0-preview-00017 
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build (>= 0.1.0-preview-00017) -> Microsoft.Build.Framework  
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Framework (>= 0.1.0-preview-00017)
warn : Detected package downgrade: Microsoft.Build.Framework from 0.0.0 to 0.1.0-preview-00017 
warn :  tool-runtime (>= 1.0.0) -> MSBuild (>= 0.1.0-preview-00017) -> Microsoft.Build.Framework  
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Framework (>= 0.1.0-preview-00017)
warn : Detected package downgrade: Microsoft.Build from 0.0.0 to 0.1.0-preview-00017 
warn :  tool-runtime (>= 1.0.0) -> MSBuild (>= 0.1.0-preview-00017) -> Microsoft.Build  
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build (>= 0.1.0-preview-00017)
warn : Detected package downgrade: Microsoft.Build.Utilities.Core from 0.0.0 to 0.1.0-preview-00017 
warn :  tool-runtime (>= 1.0.0) -> MSBuild (>= 0.1.0-preview-00017) -> Microsoft.Build.Utilities.Core  
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Utilities.Core (>= 0.1.0-preview-00017)
warn : Detected package downgrade: Microsoft.Build.Tasks.Core from 0.0.0 to 0.1.0-preview-00017 
warn :  tool-runtime (>= 1.0.0) -> MSBuild (>= 0.1.0-preview-00017) -> Microsoft.Build.Tasks.Core  
warn :  tool-runtime (>= 1.0.0) -> Microsoft.Build.Tasks.Core (>= 0.1.0-preview-00017)
info : Committing restore...
log  : Restore completed in 9119ms.
NuGet Config files used:
    /home/invain/.nuget/NuGet/NuGet.Config
Feeds used:
    https://www.myget.org/F/dotnet-core/
    https://www.myget.org/F/dotnet-buildtools/
    https://www.nuget.org/api/v2/
Publishing tool-runtime for DNXCore,Version=v5.0/ubuntu.14.04-x64
Compiling tool-runtime for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:04.2504338


Published to /work/dotnet/arm-32bit/coreclr/Tools
Published 1/1 projects successfully
log  : Restoring packages for /work/dotnet/arm-32bit/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00177/lib/portableTargets/project.json...
info :   GET https://www.myget.org/F/dotnet-buildtools/FindPackagesById()?id='Microsoft.Portable.Targets'
info :   OK https://www.myget.org/F/dotnet-buildtools/FindPackagesById()?id='Microsoft.Portable.Targets' 4218ms
info :   GET https://dotnet.myget.org/F/dotnet-buildtools/api/v2/package/Microsoft.Portable.Targets/0.1.1-dev
info :   OK https://dotnet.myget.org/F/dotnet-buildtools/api/v2/package/Microsoft.Portable.Targets/0.1.1-dev 3603ms
log  : Installing Microsoft.Portable.Targets 0.1.1-dev.
info : Committing restore...
log  : Restore completed in 9553ms.
NuGet Config files used:
    /home/invain/.nuget/NuGet/NuGet.Config
Feeds used:
    https://www.myget.org/F/dotnet-buildtools/
Installed:
    1 package(s) to /work/dotnet/arm-32bit/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00177/lib/portableTargets/project.json
Commencing build of mscorlib components for Linux.arm.Release
/work/dotnet/arm-32bit/coreclr/Tools/Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/work/dotnet/arm-32bit/coreclr/src/mscorlib/mscorlib.csproj]
  mscorlib -> /work/dotnet/arm-32bit/coreclr/bin/obj/Linux.arm./mscorlib.dll
  mscorlib -> /work/dotnet/arm-32bit/coreclr/bin/Product/Linux.arm.Release/mscorlib.dll
  log  : Restoring packages for /work/dotnet/arm-32bit/coreclr/src/.nuget/init/project.json...
  info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.platforms/index.json
  info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.platforms/index.json 829ms
  info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.platforms/1.0.1-rc2-23712/microsoft.netcore.platforms.1.0.1-rc2-23712.nupkg
  info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.platforms/1.0.1-rc2-23712/microsoft.netcore.platforms.1.0.1-rc2-23712.nupkg 195ms
  info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.targets/index.json
  info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.targets/index.json 215ms
  info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.targets/1.0.1-rc2-23712/microsoft.netcore.targets.1.0.1-rc2-23712.nupkg
  info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.targets/1.0.1-rc2-23712/microsoft.netcore.targets.1.0.1-rc2-23712.nupkg 207ms
  info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.targets.dnxcore/index.json
  info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.targets.dnxcore/index.json 208ms
  info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.targets.dnxcore/5.0.0-rc2-23712/microsoft.netcore.targets.dnxcore.5.0.0-rc2-23712.nupkg
  info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.targets.dnxcore/5.0.0-rc2-23712/microsoft.netcore.targets.dnxcore.5.0.0-rc2-23712.nupkg 198ms
  log  : Installing Microsoft.NETCore.Targets.DNXCore 5.0.0-rc2-23712.
  log  : Installing Microsoft.NETCore.Targets 1.0.1-rc2-23712.
  log  : Installing Microsoft.NETCore.Platforms 1.0.1-rc2-23712.
  info : Committing restore...
  log  : Restore completed in 15991ms.
  NuGet Config files used:
      /work/dotnet/arm-32bit/coreclr/src/NuGet.Config
      /home/invain/.nuget/NuGet/NuGet.Config
  Feeds used:
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
  Installed:
      3 package(s) to /work/dotnet/arm-32bit/coreclr/src/.nuget/init/project.json
Generating native image for mscorlib.
/lib/ld-linux-armhf.so.3: No such file or directory
Failed to generate native image for mscorlib.

real    31m54.752s
user    98m26.616s
sys 3m24.516s
invain@E120:/work/dotnet/arm-32bit/coreclr$ 
```
### Related Source code : in build_mscorlib()  of ./coreclr/build.sh
- CC: @JohnChen, @benpye, @jkotas 

```

invain@E120:/work/dotnet/arm-32bit/coreclr$ git blame -L 233,245 ./build.sh 
614d58f9 (Matt Ellis 2015-08-10 22:36:57 -0700 233)     # Invoke MSBuild
a6c65d50 (John Chen  2016-01-24 21:47:58 -0800 234)     $__ProjectRoot/Tools/corerun "$__MSBuildPath" /nologo "$__ProjectRoot/build.proj" /verbosity:minimal "/fileloggerparameters:Verbosity=normal;LogFile=$_
37e660b6 (Matt Ellis 2015-09-01 15:17:54 -0700 235) 
37e660b6 (Matt Ellis 2015-09-01 15:17:54 -0700 236)     if [ $? -ne 0 ]; then
37e660b6 (Matt Ellis 2015-09-01 15:17:54 -0700 237)         echo "Failed to build mscorlib."
37e660b6 (Matt Ellis 2015-09-01 15:17:54 -0700 238)         exit 1
37e660b6 (Matt Ellis 2015-09-01 15:17:54 -0700 239)     fi
3079b400 (John Chen  2016-01-08 16:14:24 -0800 240) 
a6c65d50 (John Chen  2016-01-24 21:47:58 -0800 241)     if [ $__SkipCoreCLR == 0 -a -e $__BinDir/crossgen ]; then
3079b400 (John Chen  2016-01-08 16:14:24 -0800 242)         echo "Generating native image for mscorlib."
3079b400 (John Chen  2016-01-08 16:14:24 -0800 243)         $__BinDir/crossgen $__BinDir/mscorlib.dll
3079b400 (John Chen  2016-01-08 16:14:24 -0800 244)         if [ $? -ne 0 ]; then
3079b400 (John Chen  2016-01-08 16:14:24 -0800 245)             echo "Failed to generate native image for mscorlib."
invain@E120:/work/dotnet/arm-32bit/coreclr$ 


```

**Comment by jkotas** [comment] 2016-03-06 00:16
The native image is generated using crossgen tool that was just built. It does not work well for crossbuild - the error is caused by trying to execute arm binary on x64 machine.

For now, you should disable generation of native images for crossbuild.

There are two options how to make this work the generation of native images work during crossbuild:

- Option 1: Build x64 hosted, arm targeting flavor of the crossgen tool (define `_AMD64_` + `_TARGET_ARM_`). We have done x86 hosted, arm targeting flavor of the crossgen tool in the past, so you would not be starting from zero.

- Option 2: Add support for generation of CoreCLR-compatible native images to the ilc compiler built in the CoreRT repo. The ilc compiler is better structured to support the cross-compilation scenarios. It is the right long-term option.

**Comment by leemgs** [comment] 2016-03-07 01:11
@jkotas, Thank you more information on the crossgen tool. I will try to make a patch to disable generation of native image for crossbuild.

**Comment by benpye** [comment] 2016-03-07 01:32
I would think it should be possible to run the ARM crossgen binary on x64
to generate the native image using qemu's user emulation (binfmt) support
to run binaries from other architectures. I haven't looked into doing this
though.

**Comment by BruceForstall** [comment] 2018-04-25 00:57
This bug looks obsolete; I am going to close it.

**Closed by BruceForstall** 2018-04-25 00:57 UTC
Labels: arch-arm32
