### ISSUE TITLE
Investigate performance caveats of covariant interface casts

### ISSUE THREAD

**Issue by VSadov** [dotnet/coreclr#1592] opened 2015-09-18 15:51 UTC
I have heard multiple times that covariant interface casts may run into degenerate cases exhibiting fairly bad performance. Sometimes this leads to people being reluctant to rely on covariance in perf-sensitive code.

The problem needs to be understood and either fixed or, if unavoidable, there should be more concrete example of scenarios to avoid.

**Comment by VSadov** [comment] 2015-09-18 15:59
If impact is real and common, we should review use of covariant interface casts in some scenarios in Fx vs. the alternatives.

**Comment by Eyas** [comment] 2015-09-18 21:58
To emphasize the importance of this, many methods (e.g. Linq, but also in other libraries) often have fast-path cases for `IList<T>`, but they only take advantage of the read-only methods.

Having a fast-path case for `IReadOnlyList<T>` unfortunately currently doesn't make sense because the `x as IReadOnlyList<T>` is quite expensive. See the discussion/perf numbers that happened in #1460.

While `IReadOnlyList` is useful percisely because its covariant, it also means that its implementers often need to implement `IList` with throwing mutating methods, just to get the performance.

**Comment by ikopylov** [comment] 2015-09-21 10:56
Related issue: #603.

**Comment by jkotas** [comment] 2016-05-09 23:07
Duplicate of #603

**Closed by jkotas** 2016-05-09 23:07 UTC
Labels: optimization, performance, question, VM
