### ISSUE TITLE
[arm64] Assertion failed 'varDsc->lvOnFrame && !varDsc->lvRegister'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17574] opened 2018-04-14 22:11 UTC
x64_arm64_altjit corefx assertion:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_baseline/157/consoleFull#-102414311f66db340-b3cd-4e23-8190-9b52cb916333

```
12:06:47   ===========================================================================================================
12:06:47   xUnit.net console test runner (64-bit .NET Core)
12:06:47   Copyright (C) 2014 Outercurve Foundation.
12:06:47   
12:06:48   Discovering: System.ValueTuple.Tests
12:06:50   Discovered:  System.ValueTuple.Tests
12:06:51   Starting:    System.ValueTuple.Tests
12:06:56   
12:06:56 
  Assert failure(PID 5032 [0x000013a8], Thread: 13340 [0x341c]): Assertion failed 'varDsc->lvOnFrame && !varDsc->lvRegister' in 'System.Tests.ValueTupleTests:LongTuplesWithNull()' (IL size 741)
12:06:56   
12:06:56       File: d:\j\workspace\x64_arm64_alt---734a66f6\src\jit\codegenarmarch.cpp Line: 752
12:06:56       Image: D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe
12:06:56   
12:06:56   ----- end 12:06:56.86 ----- exit code 123456789 ----------------------------------------------------------
12:06:56 D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\Tools\tests.targets(492,5): warning MSB3073: The command "D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\bin/tests/System.ValueTuple.Tests/netcoreapp-Windows_NT-Release-x64//RunTests.cmd D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\bin/testhost/netcoreapp-Windows_NT-Release-x64/" exited with code 123456789. [D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\src\System.ValueTuple\tests\System.ValueTuple.Tests.csproj]
12:06:56 
D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\Tools\tests.targets(500,5): error : One or more tests failed while running tests from 'System.ValueTuple.Tests' please check D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\bin/tests/System.ValueTuple.Tests/netcoreapp-Windows_NT-Release-x64/testResults.xml for details! [D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\src\System.ValueTuple\tests\System.ValueTuple.Tests.csproj]
```

also: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstress2/154/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs3/158/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs4/156/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs8/155/

and probably others.

**Comment by BruceForstall** [comment] 2018-04-14 22:11
@sdmaclea @dotnet/arm64-contrib

**Comment by sdmaclea** [comment] 2018-04-15 01:12
This is a duplicate of #16377

**Closed** 2018-04-15 15:49 UTC
Labels: arch-arm64, area-CodeGen, bug
