### ISSUE TITLE
Test Failure: System.Collections.Immutable.Tests terminated

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#26311] opened 2019-08-22 01:53 UTC
**Details:**
https://helix.dot.net/api/2019-06-17/jobs/7b08c819-87fd-42e8-b0a3-fdc2e3f52809/workitems/System.Collections.Immutable.Tests/console

**Failed tests:**
System.Collections.Immutable.Tests

**Log:**
```
C:\dotnetbuild\work\7b08c819-87fd-42e8-b0a3-fdc2e3f52809\Work\3f4404e0-0e73-445e-8abb-7d18cf951161\Exec>"C:\dotnetbuild\work\7b08c819-87fd-42e8-b0a3-fdc2e3f52809\Payload\dotnet.exe" exec --runtimeconfig System.Collections.Immutable.Tests.runtimeconfig.json xunit.console.dll System.Collections.Immutable.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\7b08c819-87fd-42e8-b0a3-fdc2e3f52809\Payload\CoreFX.issues.rsp 
  Discovering: System.Collections.Immutable.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Immutable.Tests (found 928 of 932 test cases)
  Starting:    System.Collections.Immutable.Tests (parallel test collections = on, max threads = 2)
Process terminated. Assertion failed.
Check the arguments in the caller!
   at System.Collections.Generic.GenericArraySortHelper`1.BinarySearch(T[] array, Int32 index, Int32 length, T value, IComparer`1 comparer) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/ArraySortHelper.cs:line 367
   at System.Collections.Generic.List`1.BinarySearch(Int32 index, Int32 count, T item, IComparer`1 comparer) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs:line 285
   at System.Collections.Immutable.Tests.ImmutableListTestBase.BinarySearchPartialSortedListHelper(ImmutableArray`1 inputData, Int32 sortedIndex, Int32 sortedLength) in /_/src/System.Collections.Immutable/tests/ImmutableListTestBase.cs:line 447
   at System.Collections.Immutable.Tests.ImmutableListTestBase.BinarySearchPartialSortedList() in /_/src/System.Collections.Immutable/tests/ImmutableListTestBase.cs:line 427
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 434
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/System.Private.CoreLib/shared/System/Reflection/MethodBase.cs:line 49
   at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 150
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 257
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<InvokeTestMethodAsync>b__1()
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<InvokeTestMethodAsync>b__0() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 242
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
   at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 241
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
   at Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(Object testClassInstance) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestInvoker.cs:line 112
   at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 206
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0()
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 107
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
   at Xunit.Sdk.TestInvoker`1.RunAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 189
   at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestRunner.cs:line 84
   at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestRunner.cs:line 67
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
   at Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestRunner.cs:line 149
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 107
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
   at Xunit.Sdk.TestRunner`1.RunAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestRunner.cs:line 149
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestRunner`1.RunAsync()
   at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestCaseRunner.cs:line 139
   at Xunit.Sdk.TestCaseRunner`1.RunAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs:line 82
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestCaseRunner`1.RunAsync()
   at Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestCase.cs:line 162
   at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestMethodRunner.cs:line 45
   at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 136
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
   at Xunit.Sdk.TestMethodRunner`1.RunAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 106
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestMethodRunner`1.RunAsync()
   at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestClassRunner.cs:line 168
   at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 213
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
   at Xunit.Sdk.TestClassRunner`1.RunAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 171
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestClassRunner`1.RunAsync()
   at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestCollectionRunner.cs:line 158
   at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs:line 130
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
   at Xunit.Sdk.TestCollectionRunner`1.RunAsync() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs:line 101
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 978
   at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
   at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(IMessageBus messageBus, ITestCollection testCollection, IEnumerable`1 testCases, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs:line 235
   at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs:line 184
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Future.cs:line 506
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2372
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 172
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2329
   at System.Threading.Tasks.Task.ExecuteEntry() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2240
   at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskScheduler.cs:line 608
   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 107
   at Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass11_0.<WorkerThreadProc>b__0(Object _) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 96
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 172
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 132
   at Xunit.Sdk.ExecutionContextHelper.Run(Object context, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Utility\ExecutionContextHelper.cs:line 111
   at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 89
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in C:\Dev\xunit\xunit\src\common\XunitWorkerThread.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2393
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2372
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 172
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2329
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2271
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/ThreadPoolTaskScheduler.cs:line 37
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state) in /_/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 50
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart(Object obj) in /_/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 83
exit code -2146232797
```

category:correctness
theme:tail-call
skill-level:expert
cost:medium

**Comment by jeffschwMSFT** [comment] 2019-08-22 16:17
cc @danmosemsft

**Comment by stephentoub** [comment] 2019-08-22 16:26
This looks like a runtime issue to me.  The assert is failing:
https://github.com/dotnet/coreclr/blob/47a155800eecb965e7f49e19f6109e93f370716c/src/System.Private.CoreLib/shared/System/Collections/Generic/ArraySortHelper.cs#L367
presumably because this call:
https://github.com/dotnet/coreclr/blob/47a155800eecb965e7f49e19f6109e93f370716c/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs#L285
passed in a `null` `_items`.  But `_items` should never be null: every ctor initializes it to a non-null array, and it's then never assigned to anything but a non-null array.  That suggests to me that there's some kind of corruption / codegen issue / etc. causing the parameter to be read as null.  But maybe I'm missing something.

**Comment by jeffschwMSFT** [comment] 2019-08-22 17:04
Good point, I missed that this was a jitstress mode.

**Comment by BruceForstall** [comment] 2019-08-23 18:35
This run was:
```
COMPlus_JitStress=1
COMPlus_TieredCompilation=1
```

**Comment by sandreenko** [comment] 2019-09-04 19:03
a stable repro settings:
```
COMPlus_ContinueOnAssert=0
COMPlus_JitNoInline=1
complus_JitStressModeNames=STRESS_TAILCALL
complus_JitStressModeNamesOnly=1
complus_jitstressrange=3826701918-3826701918
COMPlus_NoGuiOnAssert=0
COMPlus_ReadyToRun=0
complus_TieredCompilation=0
COMPlus_ZapDisable=1
```

**Comment by sandreenko** [comment] 2019-09-06 23:53
I added a small repro test for this bug. The bug is complex and is caused by code path that would be replaced soon by @jakobbotsch, so we have decided not to fix that in the old implementation of slow tail calls via helpers.

In short `TailCallCopyArgsThunk` can't restore register arguments for the tail call in this case because it has a shifted pointer to the arg array on the stack (shift is 0x10),
so when `jihelpers.cpp:JIT_TailCall` calls `INVOKE_COPY_ARGS_HELPER(copyArgs, args, &ctx, (DWORD_PTR*)pbTempStackFill, cbArgArea);` `ctx` doesn't get valid values for the arguments.

It happens because in this case have additional arguments that are not checked correctly.

That is how the call looks like with a tail call prefix:
```
                                                              /--*  t268   ref    this in rcx
                                                              +--*  t269   ref    arg2 in rdx
                                                              +--*  t270   int    arg3 in r8
                                                              +--*  t271   int    arg4 in r9
                                                              +--*  t272   long   arg1 in r11
                                                              +--*  t274   long   control expr
Generating: N109 ( 58, 59) [000055] --CXG-------        t55 = *  CALLV stub int    GitHub_26311.Interface`1[Int32][System.Int32].TailCallWithManyArgs REG rax $38a
```
`r11` is for VSD.

but with tail call via helper we have:
```
N049 ( 86, 82) [000055] -ACXG-------              *  CALLV stub void   GitHub_26311.Interface`1[Int32][System.Int32].TailCallWithManyArgs
N024 ( 27, 33) [000245] -ACXG---R-L- arg3 SETUP   +--*  ASG       ref   
N023 (  1,  1) [000244] D------N----              |  +--*  LCL_VAR   ref    V11 tmp7         d:2
N022 ( 27, 33) [000223] -ACXG-------              |  \--*  COMMA     ref   
N020 ( 26, 32) [000243] -ACXG-------              |     +--*  COMMA     void  
N017 ( 23, 30) [000218] -ACXG---R---              |     |  +--*  ASG       ref   
N016 (  1,  1) [000217] D------N----              |     |  |  +--*  LCL_VAR   ref    V10 tmp6         d:2
N015 ( 23, 30) [000137] --CXG-------              |     |  |  \--*  COMMA     ref   
N012 ( 18, 18) [000136] H-CXG-------              |     |  |     +--*  CALL help long   HELPER.CORINFO_HELP_CLASSINIT_SHARED_DYNAMICCLASS
N008 (  3, 10) [000132] ------------ arg0 in rcx  |     |  |     |  +--*  CNS_INT   long   0x7ff9d6e6a1d8
N009 (  1,  1) [000133] ------------ arg1 in rdx  |     |  |     |  \--*  CNS_INT   int    0
N014 (  5, 12) [000130] n---G-------              |     |  |     \--*  IND       ref   
N013 (  3, 10) [000242] ------------              |     |  |        \--*  CNS_INT(h) long   0x1bb90002cf8 static Fseq[s_default]
N019 (  3,  2) [000220] ---X--------              |     |  \--*  IND       int   
N018 (  1,  1) [000219] ------------              |     |     \--*  LCL_VAR   ref    V10 tmp6         u:2
N021 (  1,  1) [000222] ------------              |     \--*  LCL_VAR   ref    V10 tmp6         u:2 (last use)
N025 (  3, 10) [000215] ------------ arg4 out+20  +--*  CNS_INT(h) long   0x7ff9d6b40028 ftn REG r11
N026 (  1,  1) [000050] ------------ arg5 out+28  +--*  LCL_VAR   ref    V00 loc0         u:2 (last use)
N027 (  1,  1) [000051] ------------ arg6 out+30  +--*  LCL_VAR   int    V02 loc2         u:2 (last use)
N028 (  1,  1) [000052] ------------ arg7 out+38  +--*  LCL_VAR   int    V03 loc3         u:2 (last use)
N029 (  3,  2) [000053] ------------ arg8 out+40  +--*  LCL_VAR   int    V01 loc1         u:2 (last use)
N030 (  1,  1) [000054] ------------ arg9 out+48  +--*  CNS_INT   ref    null
N041 (  1,  1) [000246] ------------ arg3 in r9   +--*  LCL_VAR   ref    V11 tmp7         u:2 (last use)
N042 (  3, 10) [000229] ------------ arg0 in rcx  +--*  CNS_INT(h) long   0x7ff9d6b3d0a0 ftn
N043 (  1,  1) [000227] ------------ arg1 in rdx  +--*  CNS_INT   long   0
N044 (  3, 10) [000225] ------------ arg2 in r8   \--*  CNS_INT(h) long   0x7ff9d6b40028 ftn REG NA
```
where `[000052]` and `[000053]` are actual `r8` and `r9` for the calls.

**Closed** 2019-10-31 00:04 UTC
Labels: arch-x64, area-CodeGen, os-windows, test-corefx
