### ISSUE TITLE
RyuJIT x86: Assertion failed '(farthestRefPhysRegRecord != nullptr) && (farthestLocation > refLocation || refPosition->isFixedRegRef)

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7087] opened 2016-09-07 16:31 UTC
In Windows_NT.ryujit.x86.Checked.jit_stress_regs.2

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=2

/JIT/Regression/VS-ia64-JIT/M00/b113493/b113493/b113493.cmd

> D:\j\workspace\x86_ryujit_ch---eaa82168\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(377535): error : JIT._Regression_VS_ia64_JIT_M00_b113493_b113493_b113493_._Regression_VS_ia64_JIT_M00_b113493_b113493_b113493_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---eaa82168\tests\runtest.proj]
> Assert failure(PID 3376 [0x00000d30], Thread: 4968 [0x1368]): Assertion failed '(farthestRefPhysRegRecord != nullptr) && (farthestLocation > refLocation || refPosition->isFixedRegRef)' in 'DefaultNamespace.ExternalException:runtest():this' (IL size 345)
> File: d:\j\workspace\x86_ryujit_ch---eaa82168\src\jit\lsra.cpp Line: 5582
> Image: D:\j\workspace\x86_ryujit_ch---eaa82168\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---eaa82168\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\VS-ia64-JIT\M00\b113493\b113493\b113493.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---eaa82168\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b113493.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

**Comment by BruceForstall** [comment] 2016-09-07 18:27
cc @CarolEidt @sivarv

**Comment by sivarv** [comment] 2016-09-08 22:08
This is a jitstressregs=2 only issue on x86.

IR has the following expression
v01 = v02/(v02-v01)

t0 = GT_SUB(v02, v01)
v01 = GT_DIV(v02, t0)

v02 was allocated to edx and v01 was allocated to ecx.

The Def position of GT_SUB has  the following Candidates { ecx, ebx, esi, edi }.  Note that eax and edx were not present in Candidates of GT_SUB since those regs are killed by GT_DIV.

Lsra is in allocateBusyReg() for Def position of GT_SUB.
JitstressRegs=2 means LSRA_LIMIT_CALLER.  Under this mode, Candidates of GT_SUB get limited to RBM_CALLEE_TRASH (= {eax, ecx, edx} on x86) by intersecting with Candidate set.  Note that ecx is the only common between RBM_CALLEE_TRASH and Candidates of GT_SUB.  But ecx cannot be allocated to Def position of GT_SUB since ecx is allocated v01 (in GT_SUB Def = v02-v01) is marked as delayRegFree (because targetReg of non-commutative oper like GT_SUB cannot be same as op2's reg).

**Comment by BruceForstall** [comment] 2016-09-12 18:03
@sivarv I still see this assert in 8 different stress modes:

JitStress=2 JitStressRegs=1
JitStress=2 JitStressRegs=2
JitStress=2 JitStressRegs=3
JitStress=2 JitStressRegs=8
JitStressRegs=1
JitStressRegs=2
JitStressRegs=3
JitStressRegs=8

e.g., JitStress=2 JitStressRegs=1:
Interop\MarshalAPI\Copy\CopyDoubleArray\CopyDoubleArray.cmd
Interop\PrimitiveMarshalling\EnumMarshalling\EnumTest\EnumTest.cmd
Loader\classloader\TypeInitialization\Inlining\GenTypeInlined_Multinested\GenTypeInlined_Multinested.cmd
JIT\Methodical\NaN\r8NaNadd_cs_ro\r8NaNadd_cs_ro.cmd
JIT\SIMD\BitwiseOperations_r\BitwiseOperations_r.cmd
JIT\IL_Conformance\Old\Conformance_Base\clt_i8\clt_i8.cmd
JIT\Methodical\explicit\misc\_opt_dbgexplicit6\_opt_dbgexplicit6.cmd
JIT\IL_Conformance\Old\Base\ceq\ceq.cmd

**Comment by sivarv** [comment] 2016-09-12 18:27
Even though it is the same assert, these could potentially be different issues.  I will look into them.

**Comment by sivarv** [comment] 2016-09-12 19:15
I have looked at JIT\IL_Conformance\Old\Base\ceq\ceq.cmd failure under JitStressRegs=1/2/3/8

In each of the above stress modes, the candidates set is constrained to a set containing 3 regs.  The repro program has a long comparision (GT_EQ) that requires 4 registers (srcCount=4) and hence the assert not being able to find a reg to allocate. Our current implementation of GT_EQ is inefficient (also when compared to Jit32) and we should be able to lower this so that we don't need 4 registers at the same time to do a long comparison.

I am going to look into others to see if it is the same issue.

**Comment by BruceForstall** [comment] 2016-09-12 19:17
Feel free to open different issues for each individual root cause.

**Comment by mikedn** [comment] 2016-09-12 19:25
> Our current implementation of GT_EQ is inefficient (also when compared to Jit32) and we should be able to lower this so that we don't need 4 registers at the same time to do a long comparison.

Sounds like we should deal with long compares in lowering as discussed in #7038.

**Comment by sivarv** [comment] 2016-09-16 17:43
This was fixed by PR https://github.com/dotnet/coreclr/pull/7194

**Closed by sivarv** 2016-09-16 17:43 UTC
Labels: bug, CodeGen, JitStress, x86
