### ISSUE TITLE
Document code patterns that might get optimized by the JIT

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#12135] opened 2017-06-07 15:24 UTC
There are certain code patterns that are explicitly recognized by the JIT which will get optimized into more optimal instructions.

As an example, RyuJIT now recognizes a few common patterns which get optimized into the rotate hardware instructions, rather than separate ShiftLeft, ShiftRight instructions (https://github.com/dotnet/coreclr/issues/1619).

However, there are always caveats to each pattern which may cause the runtime to not inline it if the code is slightly different. For example: to rotate a signed integer, you need to cast to unsigned before performing the shift operations. This is required so that the shift operations cause zero-extension rather than sign-extension for negative numbers.

It would be immensely useful if the set of patterns recognized by the JIT were documented and accessible. This would not only be beneficial to those who are writing performance minded code, but it would also be beneficial to contributors so we can easily see what other patterns are worth recognizing.

category:documentation
theme:optimization
skill-level:expert
cost:large

**Comment by mikedn** [comment] 2017-06-07 15:31
I'm not sure how this would help anyone. There is no guarantee that the JIT always recognizes those patterns it knows, the only way to be sure is to check the generated assembly code.

**Comment by tannergooding** [comment] 2017-06-07 15:37
@mikedn, there are certain patterns that should always be recognized if the hardware supports it.

There are also patterns which really should be supported but aren't today, and that isn't obvious either.

For example, I would expect that the following code pattern is recognized and optimized into a single `idiv` instruction (since `idiv` computes both the quotient and remainder simultaneously).
```C#
public static int DivRem(int dividend, int divisor, out int remainder)
{
    var quotient = dividend / divisor;
    remainder = dividend % divisor;
    return quotient;
}
```

However, that is not the case and it is a clear area for where the JIT could be improved.

Having a list of things that are recognized when the hardware supports it lets me suggest new features (such as the above) where they are lacking and additionally validate that codegen is doing the right thing when I am digging into the produced assembly (if the documentation indicates that a pattern should be recognized on my hardware).

**Comment by tannergooding** [comment] 2017-06-07 15:40
https://github.com/dotnet/coreclr/issues/3439 tracks the idiv issue

**Comment by tannergooding** [comment] 2017-06-07 15:42
https://github.com/dotnet/coreclr/issues/12090 tracks making CodeGen recognize FMA patterns

**Comment by mikedn** [comment] 2017-06-07 15:55
> there are certain patterns that should always be recognized if the hardware supports it

That may be true in an offline compiler. It's not necessarily true in a JIT.

> For example, I would expect that the following code pattern is recognized and optimized into a single idiv instruction (since idiv computes both the quotient and remainder simultaneously).

The `idiv` thing is a good example. It wasn't and it still isn't trivial to recognize that pattern and generate code for it.

> Having a list of things that are recognized when the hardware supports it lets me suggest new features (such as the above) where they are lacking

Usually it's the other way around, people come up with a list of missing things and then decide what's worth adding. Nobody's going to add things just because they are missing.

**Comment by tannergooding** [comment] 2017-06-07 16:08
> Usually it's the other way around, people come up with a list of missing things and then decide what's worth adding. Nobody's going to add things just because they are missing.

In my mind, the current process is:
1. Writing code, preferring readability over anything else
2. Profiling code to determine hotspots
3. Investigating those hot spots to determine what is wrong
4. Finding places that are producing sub-optimal assembly
5. Logging bugs for the sub-optimal assembly generation

Now, if we had some documentation listing recognized code patterns, I could insert additional steps between 4 and 5:
4.A Check the documentation to determine if the pattern is supported at all, if not, go to 5
4.B If the pattern is supported, see if I am following the pattern that is recognized (maybe I need to move code around just a little to match the pattern)
4.C If I am following the pattern, but the JIT is still not optimizing it, then I can continue investigating what is causing the JIT to skip the optimization (perhaps my method is too complex, so the JIT cut some corners to save time)

> That may be true in an offline compiler. It's not necessarily true in a JIT.

Yes, there are cases where the JIT won't perform certain optimizations (such as if a method is abnormally large/complex). However, a simple console app in release mode or a method wrapping the explicit pattern (to my knowledge) should always get optimized correctly (we have unit tests for a lot of the existing patterns to validate this even).

The documentation just provides a handy way to determine if I am doing something wrong or if there is an area where the JIT could produce better code (a lot of times, it is difficult to definitely determine the former).

**Comment by mikedn** [comment] 2017-06-07 16:12
> Now, if we had some documentation listing recognized code patterns

And as I already stated, due to certain implementation details there is no way for the JIT to guarantee that documented patterns are always recognized.

**Comment by tannergooding** [comment] 2017-06-07 16:26
Even if it isn't guaranteed (a disclaimer can always be added at the top of the documentation), it is still a resource that can help users diagnose why the generated code is sub-optimal.

If the pattern is not recognized by the JIT at all:
* A bug can be logged as the JIT could potentially be improved by recognizing this pattern
-and/or-
* The user can try rewriting their code to be manually optimized (doing left shift/right shift instead of multiply/divide, multiplying the quotient by the divisor and then subtracting from the dividend to get the remainder, etc...).

If the pattern is recognized by the JIT and will (under some scenarios) be optimized:
* The user can try to rework their code to ensure they have better codegen (either manual optimization, breaking the method up to be less complex, moving the pattern into a specific method with AggressiveInlining, etc...)
-and/or-
* A bug can be logged to see why the JIT isn't optimizing in this scenario

The key point here is that the documentation helps the user in diagnosing the issue. It helps them determine how best they could improve their code and whether or not logging a bug against CoreCLR is even worthwhile in the first-place.

**Comment by tannergooding** [comment] 2017-06-07 16:29
Additionally, due to the fact that the JIT can't guarantee that a pattern is always recognized, it is all that more important for certain intrinsic functions to be added so that the guarantee can be made, these could (and should) be documented on the same page.

Users can look at the page and say, oh if I follow this pattern my code might perform better (but it should preform no worse than what it is currently), but if I really want to make this fast (hot-spot) I can explicitly call `BitOperations.RotateLeft`, `Math.DivRem`, `Math.FusedMultiplyAdd`, etc...

**Comment by RussKeldorph** [comment] 2017-06-09 23:01
@dotnet/jit-contrib 

A noble cause, but I have a hard time believing the time wouldn't be better spent creating and harnessing micro-benchmarks containing said patterns that can be monitored for regressions and moved strictly forward in performance over time.  You'll never convince me that we'll manage to keep a doc in synch with optimizer source at this level long term.

The intrinsic idea has merit, and I think we'll move in this direction over time for both machine-dependent and machine-independent intrinsics--hopefully including a more streamlined API review process once the groundwork is laid.

**Comment by tannergooding** [comment] 2017-07-31 18:21
https://github.com/dotnet/designs/issues/13

**Comment by BruceForstall** [comment] 2019-09-20 00:29
I would like to close this issue, as I don't expect we will ever attempt to document JIT optimizations at the level suggested here. I don't disagree that having such a document might be useful, but I can't imagine a document that is comprehensive and up-to-date, and worth the time investment to write. We do have some high-level documents describing the JIT architecture, and I would support improving those, as appropriate.

**Closed** 2019-09-20 05:54 UTC
Labels: Design Discussion, area-CodeGen, documentation
