### ISSUE TITLE
Accessing first character of a string without using fixed

### ISSUE THREAD

**Issue by simplejackcoder** [dotnet/coreclr#23359] opened 2019-03-20 08:33 UTC
Is it possible to retrieve the _firstchar property of a string reference without having to put it inside a `fixed` block in C#?

I tried to use the `Unsafe` class but I'm not available to get a working solution.

Is this only possible in IL?

Is it safe to do? My hunch is yes because it is used in coreclr quite often. I'm fine using `OffsetToStringData` but without having to put it as fixed.

In other words can I make the first char a byref so it is tracked safely by GC.

**Comment by stephentoub** [comment] 2019-03-20 13:45
`string.AsSpan()` creates a span by effectively doing `new Span<char>(ref _firstChar, Length)`.  So you can use `AsSpan` to get a span and then use `MemoryMarshal.GetReference` to retrieve the byref stored in the span, something like:
```C#
public static ref char GetFirstChar(this string s) => ref MemoryMarshal.GetReference(s.AsSpan());
```

**Comment by Joe4evr** [comment] 2019-03-20 14:03
Sounds like you'll want to keep an eye on dotnet/corefx#36133.

**Comment by simplejackcoder** [comment] 2019-03-20 21:50
@stephentoub Thanks, that works. Is it as fast it can be? Does JIT elide all the extraneous stuff?

To me a good JIT test will be if accessing String.cs's _firstchar and the code you pasted generate the assembly code.

@Joe4evr I wonder if it will help. Strings are not arrays, and strings already have `OffsetToStringData`. @stephentoub or others can feel free to correct what I've said.

**Comment by GrabYourPitchforks** [comment] 2019-03-21 05:29
Would it make sense for us to expose a method like this on `string`?

```cs
public sealed class String
{
    /* new method */
    public ref readonly char GetPinnableReference();
}
```

Behavior would be that it simply returns a reference to the `_firstChar` field (or, if we ever change the internal layout of `string` for some reason - to where the data is actually stored). It follows the well-established `GetPinnablerReference` pattern used by `Span<T>` and other types. And in this particular case it's a 100% safe method since it always returns something guaranteed GC-tracked and dereferenceable. In the worst case for empty strings it'll return a reference to the null terminator.

**Comment by jkotas** [comment] 2019-03-21 05:42
> `GetPinnableReference`

Yes, this has been the plan, but nobody got to it yet. Note that once this method gets exposed, the existing logic in C# compiler should pick it automatically and start using it for `fixed` instead of the `RuntimeHelpers.OffsetToStringData` hack.

**Comment by jkotas** [comment] 2019-03-21 05:53
For reference:

CSharp lang design: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/pattern-based-fixed.md

Roslyn test: https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenMscorlib.cs#L970

**Comment by GrabYourPitchforks** [comment] 2019-03-21 05:56
Huh, I never would've expected that the compiler would prefer `String.GetPinnableReference` over its own knowledge of how to pin strings. Nifty!

**Comment by simplejackcoder** [comment] 2019-03-21 06:26
Thanks for the great discussion. I would love such a feature. Do you all think it should be a bug if the JIT can't convert `ref MemoryMarshal.GetReference(s.AsSpan());` to the equivalent access on `String`?

**Comment by jkotas** [comment] 2019-03-21 06:31
`ref MemoryMarshal.GetReference(s.AsSpan())` needs to do more work by design. It does not have equivalent behavior to direct access to string when `s` is null (return null - more work, vs. throw null reference exception - less work).

**Comment by jkotas** [comment] 2019-03-21 06:35
The fix for this should be to add the `GetPinnableReference()` method. Are you interested in submitting a PR?

(We do not need API review for that - it has been reviewed with the overall pinnable pattern design.)

**Comment by simplejackcoder** [comment] 2019-03-25 04:50
I have submitted a PR now. Thank you.

**Comment by jkotas** [comment] 2019-03-28 15:23
This is not done yet. It also needs to be exposed in the reference assemblies in CoreFX repo. @simplejackcoder Could you please submit PR to corefx as well?

https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/changing-corelib.md

**Comment by simplejackcoder** [comment] 2019-03-28 19:53
I'm reading that document now to see what I have to do

**Comment by GrabYourPitchforks** [comment] 2019-04-10 23:15
Turns out this likely has to be an extension method. If the compiler will favor `string.GetPinnableReference` over the normal pinned local logic, we don't want `fixed (char* p = <null>)` to suddenly start throwing null refs where previously it would have returned null.

**Comment by jkotas** [comment] 2019-04-10 23:22
@GrabYourPitchforks Roslyn codegen emits explicit null check upfront, ie: `fixed (char* p = s)` compiles into something like `p = (s != null) ? s.GetPinnableReference() : null`.

cc @VSadov

**Comment by GrabYourPitchforks** [comment] 2019-04-10 23:23
You're right. I wrote my test incorrectly. :)

**Comment by VSadov** [comment] 2019-04-11 00:04
Yes. `fixed` is not supposed to throw on nulls/empties. 
Pinned `null` just becomes a `nullptr`, which user can handle whichever way desired inside the block.

**Closed** 2019-04-11 07:01 UTC
Labels: area-System.Runtime, question
