### ISSUE TITLE
List<T>.Sort(Comparison<T>) don't throw InvalidOperationException when called in a foreach loop

### ISSUE THREAD

**Issue by DmitryDzuba** [dotnet/coreclr#8943] opened 2017-01-13 16:52 UTC
We know, if we change a collection in a `foreach` loop, the following exception is thrown:

>InvalidOperationException: Collection was modified; enumeration operation may not execute.

But there is a method that behaves differently: [`List<T>.Sort(Comparison<T>)`](https://msdn.microsoft.com/en-us/library/w56d4y5z).

For example ([dotnetfiddle.net](https://dotnetfiddle.net/PnRrAi)):

    List<int> list = new List<int> { 2, 1 } ;
    foreach (int i in list)
    {
        //list.Sort(Comparer<int>.Default);		// InvalidOperationException
        //list.Sort();				// InvalidOperationException
        list.Sort((a, b) => a.CompareTo(b));	// No exception
			
        Console.WriteLine(i);
    }
According to the [referencesource.microsoft.com](https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,a406b86aecf46aa1) we can see that there is no version increment in this particular method, while there is one in the method above:

    public void Sort(int index, int count, IComparer<T> comparer) {
        ...
        _version++;
    }
Version is incremented also in all other methods that modify the list.

**Comment by mikedn** [comment] 2017-01-13 17:31
Duplicate of #8071

**Closed** 2017-01-13 18:12 UTC
