### ISSUE TITLE
GcStress: Linux: Crash in _il_dbglcs

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2765] opened 2016-01-21 01:36 UTC
Looks like a crash while unwinding the stack.

```
corerun JIT/Methodical/refany/_il_dbglcs/_il_dbglcs.exe
Test searches for longest common subsequence of 4 strings

/home/swaroops/bin/runn: line 3: 20031 Segmentation fault      (core dumped) 
```

Stack trace is 
```
(gdb) bt
#0  0x00007fe3a32f8267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007fe3a32f9eca in __GI_abort () at abort.c:89
#2  0x00007fe3a2cd108c in PROCEndProcess (hProcess=0xffffff01, uExitCode=1, bTerminateUnconditionally=1)
    at /home/swaroops/git/a/coreclr/src/pal/src/thread/process.cpp:1346
#3  0x00007fe3a2cd11a0 in TerminateProcess (hProcess=0xffffff01, uExitCode=1) at /home/swaroops/git/a/coreclr/src/pal/src/thread/process.cpp:1262
#4  0x00007fe3a2453fd5 in UnwindManagedExceptionPass1 (ex=...) at /home/swaroops/git/a/coreclr/src/vm/exceptionhandling.cpp:4614
#5  0x00007fe3a2454295 in DispatchManagedException (ex=...) at /home/swaroops/git/a/coreclr/src/vm/exceptionhandling.cpp:4666
#6  0x00007fe3a23120d6 in IL_Throw (obj=0x7fe3040a0600) at /home/swaroops/git/a/coreclr/src/vm/jithelpers.cpp:5381
#7  0x00007fe3287c0f82 in ?? ()
#8  0x00007fe304047e38 in ?? ()
#9  0x0000000000000000 in ?? ()
```
Repro steps are:

* cp \scratch2\scratch\swaroops\coredistools\libcoredistools.so somewhere
* export LD_LIBRARY_PATH=somewhere
* export COMPlus_GCStress=0xC
* Run the above test

**Comment by sivarv** [comment] 2016-01-29 03:51
Mkrefany test. Fix to correctly handle TypedReference will fix this.

**Comment by sivarv** [comment] 2016-01-29 04:21
This is a duplicate of issue #2764

**Closed by sivarv** 2016-01-29 04:21 UTC
Labels: bug, CodeGen, GCStress, Linux
