### ISSUE TITLE
Possibly unreliable test: GC.API.GCHandleCollector.Usage.Usage

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#4400] opened 2016-04-19 00:25 UTC
Test failed for a PR that should have made no difference.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/872/testReport/

GC.API.GCHandleCollector.Usage.Usage
MESSAGE:
BEGIN EXECUTION /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun Usage.exe Case 1 Passed! 100, 100 Case 2 Passed! Case 3 failed: threshold not increasing! Test Failed! Expected: 100 Actual: 1 END EXECUTION - FAILED
+++++++++++++++++++
STACK TRACE:

**Comment by swgillespie** [comment] 2016-04-19 00:27
possibly related to https://github.com/dotnet/coreclr/issues/4093, will investigate

**Comment by swgillespie** [comment] 2016-05-06 16:59
After investigation, closing as a dupe of https://github.com/dotnet/coreclr/issues/4093

**Closed by swgillespie** 2016-05-06 16:59 UTC
Labels: GC, Test-Issue
