### ISSUE TITLE
Setup MSBuild requires a private package for Microsoft.Net.Compilers.Targets.NetCore 

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/coreclr#2698] opened 2016-01-15 23:31 UTC
Resolving issue #1934 requires setting up an MSBuild that runs under CoreCLR. Currently, this setup requires a private NuGet package for Microsoft.Net.Compilers.Targets.NetCore. This package needs to be made available on a public feed.

**Comment by dsplaisted** [comment] 2016-01-16 00:14
I believe @joperezr is going to make sure the package is available, or otherwise modify the buildtools package so it doesn't need this package.

**Comment by JohnChen0** [comment] 2016-01-19 18:11
@joperezr: Do you have an ETA of when we will have buildtools that don't depend on the private NuGet package? Thanks.

**Comment by tzwlai** [comment] 2016-01-21 16:32
@joperezr, I have tagged this issue with "blocking-release" since it's currently blocking #1934, which is a blocking issue itself.

CC @leecow

**Comment by joperezr** [comment] 2016-01-21 17:12
The problem is not the dependency in the private packages, since they can be uploaded to the build tools easily. The problem is that the MSBuild that we have right now doesn't run in Mac OS X since it crashes just after we invoke it. @rainersigwald is helping us fix this and hopefully he can get this working today so that we can depend on new packages that work across all platforms.

**Comment by rainersigwald** [comment] 2016-01-21 17:45
@joperezr Tracking that as Microsoft/msbuild#441. Currently working to resolve flakiness with build and test after updating our .NET Core dependencies.

**Comment by rainersigwald** [comment] 2016-01-26 18:20
Microsoft/msbuild#441 is fixed as of MSBuild packages version `0.1.0-preview-00014` and higher (use 15 since it has another bugfix).

**Comment by joperezr** [comment] 2016-01-27 16:46
The packages have been published and the code change was made with dotnet/buildtools#396
I will generate a new build tools package version with the change and report back the number.

**Comment by joperezr** [comment] 2016-01-27 17:23
Done, package version 00157 contains .Net Core MSBuild. @JohnChen0 if you want to see an example of how to use it, please take a look at dotnet/corefx#5711. The most important files you want to keep an eye on, are init-tools.sh and init-tools.cmd in the corefx repo, and how we call them from the build.cmd and build.sh. If you have any questions please let me know. I'm closing this issue since the package is ready.

**Closed by joperezr** 2016-01-27 17:23 UTC
Labels: blocking-release, Build
