### ISSUE TITLE
Investigate if EventSource can be made more robust in the fact of incorrect event ID

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#11976] opened 2017-05-30 14:41 UTC
See the failure in https://github.com/dotnet/corefx/pull/20379#issuecomment-304401130

The issue is whether incorrect event IDs can be found more easily.   Note that we should be careful with the  extra checking we introduce.  We want it to be 'light' on the 'hot' path of actually logging an event (or even more important, filtering events).    Incorrect EventIDs are rare, so it is VERY easy for the cure to be worse than the disease.   However in this case it seems like we CAN have checking and throwing an error when we failed to set the 'Parameters' field that was null in this case.   This should cost next to nothing (one time startup cost).  

@stephentoub  @brianrob

**Comment by omariom** [comment] 2017-05-30 19:36
@sharwell 
The case for an analyzer?

**Comment by brianrob** [comment] 2018-03-22 19:39
Duplicate of #9494.

**Closed by brianrob** 2018-03-22 19:39 UTC
Labels: area-EventSource
