### ISSUE TITLE
[Linux/arm64] R2R JitForceRelocs ThreadStartDelegate_1 Failure

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#20990] opened 2018-11-14 01:10 UTC
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitforcerelocs_tst_prtest/2/

```
[/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitforcerelocs_tst_prtest/bin/tests/Linux.arm64.Checked/baseservices/threading/paramthreadstart/ThreadStartDelegate_1/ThreadStartDelegate_1.sh]: 

/n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitforcerelocs_tst_prtest/bin/tests/Linux.arm64.Checked/baseservices/threading/Reports/baseservices.threading/paramthreadstart/ThreadStartDelegate_1/ThreadStartDelegate_1.output.txt/nRaw output:/nTest Harness Exitcode is : 137
/nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitforcerelocs_tst_prtest/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitforcerelocs_tst_prtest/bin/tests/Linux.arm64.Checked/baseservices/threading/paramthreadstart/ThreadStartDelegate_1/ThreadStartDelegate_1.sh/n
Expected: True
Actual:   False


Return code:      137
Raw output file:      /home
obox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitforcerelocs_tst_prtest/bin/tests/Linux.arm64.Checked/baseservices/threading/Reports/baseservices.threading/paramthreadstart/ThreadStartDelegate_1/ThreadStartDelegate_1.output.txt
Raw output:
Test Harness Exitcode is : 137

To run the test:
> set CORE_ROOT=/home
obox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitforcerelocs_tst_prtest/bin/tests/Linux.arm64.Checked/Tests/Core_Root
> /home
obox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitforcerelocs_tst_prtest/bin/tests/Linux.arm64.Checked/baseservices/threading/paramthreadstart/ThreadStartDelegate_1/ThreadStartDelegate_1.sh

Expected: True
Actual:   False
```

**Comment by RussKeldorph** [comment] 2019-01-16 21:57
Assuming duplicate of #22010.  Feel free to re-open if not.

**Closed by RussKeldorph** 2019-01-16 21:57 UTC
Labels: arch-arm64, area-ReadyToRun, os-linux
