### ISSUE TITLE
Error compiling on MacOSX with latest XCode

### ISSUE THREAD

**Issue by wilsonge** [dotnet/coreclr#15005] opened 2017-11-13 13:28 UTC
```
[ 14%] Building CXX object tests/src/Exceptions/ForeignThread/CMakeFiles/ForeignThreadExceptionsNative.dir/ForeignThreadExceptionsNative.cpp.o
In file included from __ROOT_GIT_REPO__/coreclr/tests/src/Exceptions/ForeignThread/ForeignThreadExceptionsNative.cpp:9:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:97:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__mutex_base:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__threading_support:156:1: error: unknown type name
      'mach_port_t'
mach_port_t __libcpp_thread_get_port();
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__threading_support:300:1: error: unknown type name
      'mach_port_t'
mach_port_t __libcpp_thread_get_port() {
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__threading_support:301:12: error: use of undeclared
      identifier 'pthread_mach_thread_np'
    return pthread_mach_thread_np(pthread_self());
           ^
3 errors generated.
make[2]: *** [tests/src/Exceptions/ForeignThread/CMakeFiles/ForeignThreadExceptionsNative.dir/ForeignThreadExceptionsNative.cpp.o] Error 1
make[1]: *** [tests/src/Exceptions/ForeignThread/CMakeFiles/ForeignThreadExceptionsNative.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I've substituted __ROOT_GIT_REPO__ for the root path to my git clone of this repo. Building from current master (which at time of submission of this issue was commit cbcdbd25e74ff9d963eafa202dd63504ca537f7e )

**Comment by wilsonge** [comment] 2017-11-13 13:53
So for a horrible hackjob solution i pulled in https://github.com/tensorflow/tensorflow/issues/13220#issuecomment-331579775 and hacked up XCode

**Comment by jkotas** [comment] 2017-11-14 03:27
I have upgraded to latest XCode today - Version 9.1 (9B55). It does not repro for me. Maybe Apple has fixed it already?

**Comment by wilsonge** [comment] 2017-11-14 10:06
Just did the upgrade. It didn't change the file `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__threading_support` (the last modification to that file was the one I made yesterday based on the hacked up tensorflow approach) and I still have the same error if I revert that change.

**Comment by janvorli** [comment] 2017-11-14 14:01
I have also upgraded to the latest XCode and MacOS and I cannot repro the issue - everything builds just fine. @wilsonge would you be willing to generate preprocessed file for the ForeignThreadExceptionsNative.cpp and share it e.g. via gist? It seems that you might have something additional on your include paths that I or @jkotas don't have and that's causing the trouble. The preprocessed file would show that clearly.
You can generate the preprocessed file this way (assuming you have already attempted to build for Debug). Go to your coreclr root folder and then:
```sh
cd bin/obj/OSX.x64.Debug/tests/src/Exceptions/ForeignThread
make ForeignThreadExceptionsNative.cpp.i
```
The file gets created in `CMakeFiles/ForeignThreadExceptionsNative.dir/ForeignThreadExceptionsNative.cpp.i
`

**Comment by 4creators** [comment] 2017-11-14 23:05
@wilsonge
In case of macOS build errors described in issue #14279 I have had problem when upgrading to Xcode v9.0 when first Xcode 9.0 command line tools were installed. This messed up my headers and besides reproducible compile errors there were errors specific to broken headers. They were fixed by AFAIR by reinstall of new version of Xcode. Perhaps this is similar situation.

**Comment by BruceForstall** [comment] 2017-11-16 23:34
It looks like this is happening in the CI:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_prtest/9113/consoleFull#1326600353a82fefab-f698-416f-8fca-58544c94cd4e

**Comment by jkotas** [comment] 2017-11-16 23:55
@dotnet/dncenghot Was there any update installed on the MacOS CI machines today that would explain this build break?

**Comment by janvorli** [comment] 2017-11-17 00:00
Strangely, the clang version is the same as the one on my local Mac (AppleClang 9.0.0.9000038) where things work. I was assuming the xcode installation is a self-contained thing with no opt-out or opt-in parts, so that's really strange.
But at least we can now repro it ourselves.

**Comment by karajas** [comment] 2017-11-17 00:14
Filed issue https://github.com/dotnet/core-eng/issues/2129

**Comment by karajas** [comment] 2017-11-17 00:53
On the build machines, running clang --version returns Apple LLVM version 8.0.0 (clang-800.0.42.1)

**Comment by karajas** [comment] 2017-11-17 01:43
Some of the machines were force updated to clang 9. Started the process to revert these back to the original clang (8.1.0)

**Comment by jashook** [comment] 2017-11-17 23:14
I have reproed this on Sierra. I have a feeling it may not repro in High Sierra.

**Comment by karajas** [comment] 2017-11-17 23:36
These seem to be on the latest (9.0.0) Would we like to update CI macOS machines to High Sierra?

**Closed** 2017-11-18 09:02 UTC
Labels: area-Build, blocking-clean-ci, os-mac-os-x, up-for-grabs

**Comment by wilsonge** [comment] 2017-11-18 15:59
Thanks guys - apologies I'm at a conference so didn't reply. But I can confirm this fixed the issue I had :)
