### ISSUE TITLE
Need PAL accessible SString

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/coreclr#1374] opened 2015-08-11 03:27 UTC
Want to leverage to replace [MAX_PATH] stack allocations.

**Comment by janvorli** [comment] 2015-08-11 11:08
@JeremyKuhne It looks like the `SString` is unnecessarily heavy for the purpose you need and it would likely be difficult to make it build in PAL due to its dependencies.
It also looks like there are many places where `[MAX_PATH]` is used unnecessarily, where a much smaller buffer would be sufficient due to the fact that we know the path cannot be longer than some limit (for example places where we create a path into the `/proc` filesystem and where the only variable is the length of an integer number formatted as string).

Besides tests, it looks like the places where we would need a dynamic sized string are:
```
src\pal\src\file\directory.cpp
src\pal\src\file\file.cpp
src\pal\src\file\find.cpp
src\pal\src\file\path.cpp
src\pal\src\loader\module.cpp
src\pal\src\map\virtual.cpp
src\pal\src\misc\perftrace.cpp
src\pal\src\shmemory\shmemory.cpp
src\pal\src\synchmgr\synchmanager.cpp
src\pal\src\thread\process.cpp
```
It seems that none of these places needs anything fancy, in majority of the places the dynamic sized string is used to keep a filename converted from wchar to char and vice versa. 
So I would recommend to create a very simple dynamic string class from scratch instead. Maybe even just a holder for a dynamically allocated memory with size specified in the constructor would be enough for the usage in PAL.

**Comment by JeremyKuhne** [comment] 2015-08-11 18:19
I was thinking we needed something akin to StackSString- but maybe stack allocating for shorter paths isn't that important in the PAL. Frequent path access is more of a CoreFX thing. Is that a fair statement?

**Comment by janvorli** [comment] 2015-08-11 19:17
I was thinking that your goal is to fix the issue with MAX_PATH in PAL. The issue is that the MAX_PATH / PATH_MAX is not necessarily the real limit of path on Unixes. That's why there is a pathconf function that allows querying real limits. However, these limits can be huge and not necessarily suitable for memory allocation.
So my thinking was that the best way would be to avoid these limits and create helper string buffers based on the real needed size. 
To avoid the need to allocate memory dynamically in the cases where the needed size is "reasonably" small, the string class can have an inner buffer that it would use if the requested size is smaller than the size of this buffer and dynamically allocate in the less likely case when more memory is needed.
So for example, let's say we have a class defined like this:
```C
template<int MaxStaticSize>
class StackString
{
    char m_innerBuffer[MaxStaticSize];
    char* m_buffer;
public:
    StackString(int size)
    {
        if (size <= MaxStaticSize)
        {
            m_buffer = m_innerBuffer;
        }
        else
        {
            m_buffer = (char*)malloc(size);
        }
    }

    ~StackString()
    {
        if (m_buffer != m_innerBuffer)
        {
            free(m_buffer);
        }
    }
};
```

And then we can use it this way:
```C
void ProcessString(char* s)
{
    StackString<4096> str(strlen(s) + 1);
}
```

**Comment by JeremyKuhne** [comment] 2015-08-18 22:26
@Priya91

**Comment by Priya91** [comment] 2015-10-29 18:32
This should now be fixed with [StackString] (https://github.com/dotnet/coreclr/blob/master/src/pal/src/include/pal/stackstring.hpp)

**Closed** 2015-10-29 18:33 UTC
Labels: PAL
