### ISSUE TITLE
Add a way to get the upper 64 bits of a 64x64 bit multiplication

### ISSUE THREAD

**Issue by nitroxis** [dotnet/coreclr#20610] opened 2018-10-25 14:31 UTC
There appears to be no efficient way to get the upper 64 bits of an ulong * ulong multiplication. One can of course implement this in user code with a big impact on performance, but since all major architectures support this, it would make sense to expose this functionality in a public static method. A fallback implementation can be used should the CLR ever support a platform that does not have an intrinsic for this, such as:

```csharp
public static ulong mul64(ulong x, ulong y, out ulong high)
{
	unchecked
	{
		ulong xl = (uint)x;
		ulong xh = x >> 32;
		ulong yl = (uint)y;
		ulong yh = y >> 32;

		ulong hh = xh * yh;
		ulong lh = xl * yh;
		ulong hl = xh * yl;
		ulong ll = xl * yl;

		ulong m = hl + (ll >> 32) + (uint)lh;
		high = hh + (m >> 32) + (lh >> 32);
		return (m << 32) | (uint)ll;
	}
}
```

Alternatively, it could be exposed as intrinsic in the System.Runtime.Instrinsics.X86 and .Arm namespaces, so that a user has to check whether this operation is supported.

**Comment by jkotas** [comment] 2018-10-25 15:39
Thanks for the API suggestion. This is duplicate of https://github.com/dotnet/corefx/issues/32075 . (We track all API proposals in CoreFX repo, even if they may end up being implemented in the runtime.)

**Comment by jkotas** [comment] 2018-10-25 15:39
cc @tannergooding

**Closed by jkotas** 2018-10-25 15:39 UTC

**Comment by nitroxis** [comment] 2018-10-25 15:43
Ah sorry, I did see that issue but only read the initial comment which was just about DivMod. But yeah, that's exactly the same feature request. Thanks.

**Comment by tannergooding** [comment] 2018-10-25 15:43
(Was just about to comment something similar.)

If you would like to open an explicit proposal to track a `Multiply128` or `MultiplyHigh` API (either as part of `System.Math` or as runtime intrinsics), you should follow the steps listed here: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md#steps
* Noting that we have a "good example" listed as part of step 1 that gives an overview of the general format we like the API proposals to be given in.
