### ISSUE TITLE
GCStress Failure: GC._API_GC_GetTotalMemory

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3764] opened 2016-03-16 18:56 UTC
GC._API_GC_GetTotalMemory_GetTotalMemory_._API_GC_GetTotalMemory_GetTotalMemory_cmd

\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\GC\API\GC\GetTotalMemory\GetTotalMemory.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\GC\API\GC\GetTotalMemory\GetTotalMemory.cmd\n\r\nExpected: True\r\nActual:   False
   at GC._API_GC_GetTotalMemory_GetTotalMemory_._API_GC_GetTotalMemory_GetTotalMemory_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\GC\GC.XUnitWrapper.cs:line 2676

**Comment by JohnChen0** [comment] 2016-05-10 21:36
This is a duplicate of issue #4708. The test case appears to be incompatible with GC stress, and the failure is not related to ReadyToRun. This test case does heap allocations, and then compares the actual heap size with expected heap size. When GC stress is turned on, additional memory can be allocated on GC heap, making the actual heap size different from expected heap size, triggering failures. This test case has already been excluded from GC stress runs.

**Closed by JohnChen0** 2016-05-10 21:36 UTC
Labels: blocking-release, bug, GCStress, ReadyToRun
