### ISSUE TITLE
[arm64] Test failed: readytorun\tests\fileversionpreservation\fileversionpreservation\fileversionpreservation.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24409] opened 2019-05-06 01:43 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_r2r_gcstress15_tst/53/

**Failed tests:**
readytorun\tests\fileversionpreservation\fileversionpreservation\fileversionpreservation.cmd

**Log:**
```
Native image fileversionpreservation.exe generated successfully.
         "C:\j\workspace\arm_cross_che---27c9527e\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\corerun.exe" fileversionpreservation.exe 
        Expected: 100
        Actual: -1073740286
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\j\workspace\arm_cross_che---27c9527e\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root
        > C:\j\workspace\arm_cross_che---27c9527e\bin\tests\Windows_NT.arm.Checked\readytorun\tests\fileversionpreservation\fileversionpreservation\fileversionpreservation.cmd
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\arm_cross_che---57645b35\bin\tests\Windows_NT.arm.Checked\TestWrappers\readytorun.tests\readytorun.tests.XUnitWrapper.cs(129,0): at readytorun_tests._fileversionpreservation_fileversionpreservation_fileversionpreservation_._fileversionpreservation_fileversionpreservation_fileversionpreservation_cmd()
        Output:
          
          Assert failure(PID 7060 [0x00001b94], Thread: 8920 [0x22d8]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
          
          <no module>! <no symbol> + 0x0 (0x00000000)
              File: d:\j\workspace\arm_cross_che---57645b35\src\vm\jithelpers.cpp Line: 5091
              Image: C:\j\workspace\arm_cross_che---27c9527e\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
          
          
          Return code:      1
```

**Comment by VincentBu** [comment] 2019-06-10 02:12
Test failed due to this assertion:
https://mc.dot.net/#/user/coreclr-outerloop-gcstress0x3-gcstress0xc/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190609.1/workItem/Interop/analysis/xunit/Interop_ICustomMarshaler._Primitives_ICustomMaraler_ICustomMaraler_~2F_Primitives_ICustomMarshaler_ICustomMarshaler_sh

**Comment by sergiy-k** [comment] 2019-06-24 20:47
@fadimounir, could please take a first look and triage?

**Comment by fadimounir** [comment] 2019-06-24 21:05
Taking a look

**Comment by fadimounir** [comment] 2019-06-24 23:09
@sergiy-k  I can't repro the assert above. I tried a good number of times with and without complus_gcstress=15.
Not sure what the issue is. Are there dumps for this failure?
I'm running this test in a loop on an arm device. If it still doesn't fail, i'm not sure what can be done without a dump to investigate

**Comment by fadimounir** [comment] 2019-06-25 15:26
It's been running overnight, no assert hit. Closing as no-repro.

**Closed by fadimounir** 2019-06-25 15:26 UTC
Labels: arch-arm32
