### ISSUE TITLE
[RyuJIT/arm32][JitStress=2][JitStressRegs=4] Assertion failed '(regSet.rsMaskVars & regMask) == 0'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#14374] opened 2017-10-06 23:37 UTC
Found in an x86_arm_altjit run.

```
Assert failure(PID 5064 [0x000013c8], Thread: 4296 [0x10c8]): Assertion failed '(regSet.rsMaskVars & regMask) == 0' in 'ILGEN_0x372a9ae6:Method_0xdc6ff1a4(byte,byte,int,int,char,double,long,long):int' (IL size 11052)

    File: d:\j\workspace\x86_arm_altji---82a001f9\src\jit\codegencommon.cpp Line: 598
    Image: D:\j\workspace\x86_arm_altji---82a001f9\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

Tests, configurations:

```
COMPlus_JitStress=2
COMPlus_JitStressRegs=4

JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b59782\b59782\b59782.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b60142\b60142\b60142.cmd
```

**Comment by BruceForstall** [comment] 2017-10-06 23:37
@dotnet/arm32-contrib

**Comment by hqueue** [comment] 2017-10-18 02:56
This is reproduced in `Checked` and `Debug`. I will take a look at this.

@BruceForstall Please assign this to me.

**Comment by hqueue** [comment] 2017-10-19 14:36
PR #14588 fixes `JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b60142\b60142\b60142.cmd`.

And there is another bug related to `JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b59782\b59782\b59782.cmd` which still raises the assertion.

**Comment by hqueue** [comment] 2017-11-02 11:31
@BruceForstall I think we can close this issue now, because two PR #14588 and #14614 merged.
I also ran above two tests with the latest master and confirmed tests are passed.

**Closed** 2017-11-02 15:34 UTC
Labels: arch-arm32, area-CodeGen, bug, JitStress
