### ISSUE TITLE
Collecting StackTrace performance

### ISSUE THREAD

**Issue by Mr-Daomi** [dotnet/coreclr#18114] opened 2018-05-24 09:26 UTC
Why can't I collect stack information?
Currently, in the slow tracking details or error details, the stack information corresponding to the .NET Core code method cannot be consulted.

The root cause is the poor performance of collecting StackTrace on the .NET Core 2.0 platform. After evaluation, each execution of StackTrace will result in millisecond CPU usage.

Technically speaking, we can collect the stack, but due to performance issues, releasing this feature will result in serious impact on user application performance, so at present we have not yet opened the stack.

To solve this problem, you must expect the .NET Core kernel team to develop a more efficient StackTrace approach.

**Comment by 0xd4d** [comment] 2018-05-24 16:05
Dupe of https://github.com/dotnet/coreclr/issues/17701

**Comment by RussKeldorph** [comment] 2018-05-24 17:52
@dotnet/dotnet-diag Please re-open if this is not a duplicate of #17701.

**Closed by RussKeldorph** 2018-05-24 17:52 UTC
Labels: area-Diagnostics
