### ISSUE TITLE
[Perf] CreateStore task failing in scenario benchmark testing

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#17494] opened 2018-04-10 14:23 UTC
I've tested this a few times locally, and I can consistently repro it. When the MusicStore/AllReady CreateStore task runs in our perf harness infrastructure, we get the following error:

```
    Running Process: powershell.exe .\AspNet-GenerateStore.ps1 -InstallDir .store -Architecture x64 -Runtime win7-x64
    Working Directory: C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K
    Additional Environment Variables: PATH=C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\.dotnet;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\CMake\bin;C:\Program Files (x86)\Vim\vim80;C:\Program Files\Git\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\michelm\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Users\michelm\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\michelm\AppData\Local\Programs\Python\Python36-32\;C:\Users\michelm\AppData\Local\Microsoft\WindowsApps;C:\Users\michelm\.dotnet\tools;C:\michelm\optimization\output\CLRx64WIN2.1\PGO\DotNet_FirstTimeXP\user\AppData\Local\Microsoft\WindowsApps;C:\Users\michelm\AppData\Roaming\npm;C:\michelm\optimization\output\CLRx64WIN2.1\PGO\DotNet_FirstTimeXP\user\.dotnet\tools;C:\output\CLRx86WIN2.1\PGO\DotNet_FirstTimeXP\user\.dotnet\tools;C:\output\CLRx64WINmas\PGO\DotNet_FirstTimeXP\user\.dotnet\tools;C:\output\CLRx64WIN2.1\PGO\DotNet_FirstTimeXP\user\.dotnet\tools, JITBENCH_TARGET_FRAMEWORK_MONIKER=netcoreapp2.1, JITBENCH_FRAMEWORK_VERSION=2.1.0-preview3-26327-01
    {
        00:00.482: Running dotnet store --manifest .\CreateStore\CreateStore.proj -f netcoreapp2.1 -r win7-x64 --framework-version 2.1.0-preview3-26327-01 -w C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.temp -o C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.store --skip-symbols
        00:01.085: Microsoft (R) Build Engine version 15.5.178.35674 for .NET Core
        00:01.085: Copyright (C) Microsoft Corporation. All rights reserved.
        00:01.085: 
        00:01.879:   Restoring packages for C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\CreateStore\CreateStore.proj...
        00:02.232:   Generating MSBuild file C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.temp\Optimize\CreateStore.proj.nuget.g.props.
        00:02.238:   Generating MSBuild file C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.temp\Optimize\CreateStore.proj.nuget.g.targets.
        00:02.253:   Restore completed in 365.67 ms for C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\CreateStore\CreateStore.proj.
        00:02.743:   Restoring packages for C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\CreateStore\CreateStore.proj...
        00:02.976: C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\.dotnet\sdk\2.2.0-preview1-007558\NuGet.targets(103,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\CreateStore\CreateStore.proj]
        00:02.976: C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\.dotnet\sdk\2.2.0-preview1-007558\NuGet.targets(103,5): error :   Unknown error (0xffffffff) [C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\CreateStore\CreateStore.proj]
        00:03.081: C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\.dotnet\sdk\2.2.0-preview1-007558\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(249,5): error : Assets file 'C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.temp\Microsoft.AspNetCore.All_\\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\CreateStore\CreateStore.proj]
        00:03.087:   Files were composed in C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.store\x64\netcoreapp2.1\
        00:03.087:   The list of packages stored is in C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.store\x64\netcoreapp2.1\artifact.xml 
        00:03.393: Setting JITBENCH_ASPNET_MANIFEST to C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.store\x64\netcoreapp2.1\artifact.xml
        00:03.394: Setting DOTNET_SHARED_STORE to C:\michelm\coreclr\bin\sandbox_logs\Scenarios\Off\JitBench\K\.store
    }
    Exit code: 0 ( 00:03.429 elapsed)
```

When I use the dotnet.exe downloaded by the tooling (with all environment variables set up correctly), but outside the harness, I get the same failure. However, when I manually download the exact same SDK and runtime versions using the Dotnet-Install script, I can successfully run AspNet-GenerateStore.ps1.

I'm not exactly sure what is going on here.

**Comment by adiaaida** [comment] 2018-04-10 14:25
@adamsitnik @noahfalk @jorive Do any of you have any idea why this might be happening. It doesn't appear to be an environment issue. And the dotnet we install works with other benchmarks, just not with AspNet-GenerateStore.ps1.

**Comment by adamsitnik** [comment] 2018-04-10 18:17
I have no idea, but I will try to repro it.

**Comment by adamsitnik** [comment] 2018-04-10 18:47
@adiaaida I tried to reproduce the problem, but it works fine on my machine.

```
    Running Process: powershell.exe .\AspNet-GenerateStore.ps1 -InstallDir .store -Architecture x64 -Runtime win7-x64
    Working Directory: C:\Users\adsitnik\AppData\Local\Temp\JitBench_2018_04_10_08_26_01_9571\K
    Additional Environment Variables: Path=C:\Users\adsitnik\AppData\Local\Temp\JitBench_2018_04_10_08_26_01_9571\.dotnet;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Xoreax\IncrediBuild;C:\Program Files (x86)\GitExtensions\;C:\Program Files\CMake\bin;C:\Python27;C:\Program Files\Git\cmd;C:\windows\System32\OpenSSH\;C:\Users\adsitnik\AppData\Local\Microsoft\WindowsApps;C:\Users\adsitnik\.dotnet\tools, DOTNET_MULTILEVEL_LOOKUP=0, JITBENCH_TARGET_FRAMEWORK_MONIKER=netcoreapp2.1, JITBENCH_FRAMEWORK_VERSION=2.1.0-preview3-26327-01
    {
        00:00.583: Running dotnet store --manifest .\CreateStore\CreateStore.proj -f netcoreapp2.1 -r win7-x64 --framework-version 2.1.0-preview3-26327-01 -w C:\Users\adsitnik\AppData\Local\Temp\JitBench_2018_04_10_08_26_01_9571\K\.temp -o C:\Users\adsitnik\AppData\Local\Temp\JitBench_2018_04_10_08_26_01_9571\K\.store --skip-symbols
        00:00.948: Microsoft (R) Build Engine version 15.5.178.35674 for .NET Core
        00:00.948: Copyright (C) Microsoft Corporation. All rights reserved.
        00:00.948: 
        00:01.600:   Restoring packages for C:\Users\adsitnik\AppData\Local\Temp\JitBench_2018_04_10_08_26_01_9571\K\CreateStore\CreateStore.proj...
        04:26.170:   Installing runtime.win-x64.Microsoft.NETCore.DotNetAppHost 2.1.0-preview3-26327-01.
        04:26.197:   Installing runtime.win-x64.Microsoft.NETCore.DotNetHostResolver 2.1.0-preview3-26327-01.
        04:26.200:   Installing runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy 2.1.0-preview3-26327-01.
        04:26.203:   Installing runtime.win-x64.Microsoft.NETCore.App 2.1.0-preview3-26327-01.
        04:34.353:   Generating MSBuild file C:\Users\adsitnik\AppData\Local\Temp\JitBench_2018_04_10_08_26_01_9571\K\.temp\Optimize\CreateStore.proj.nuget.g.props.
        04:34.368:   Generating MSBuild file C:\Users\adsitnik\AppData\Local\Temp\JitBench_2018_04_10_08_26_01_9571\K\.temp\Optimize\CreateStore.proj.nuget.g.targets.
        04:34.406:   Restore completed in 4,55 min for C:\Users\adsitnik\AppData\Local\Temp\JitBench_2018_04_10_08_26_01_9571\K\CreateStore\CreateStore.proj.
```

0. Does it fail every time? Or should I try  to run it few times?
1. Could you try to modify `AspNet-GenerateStore.ps1` and run the `dotnet store` with different log verbosity level to get more info about this error? for example: `--verbosity diagnostic`? Warning: the output is going to be huge.
2. Could you try to modify `AspNet-GenerateStore.ps1` and run the `dotnet restore --ignore-failed-sources` before running `dotnet store`? This is my best idea for a workaround right now.  

> When I use the dotnet.exe downloaded by the tooling (with all environment variables set up correctly), but outside the harness, I get the same failure. However, when I manually download the exact same SDK and runtime versions using the Dotnet-Install script, I can successfully run AspNet-GenerateStore.ps1.

In such cases I typically run dotnet with --verbosity diagnostics for both cli configurations and diff the log file. It's still a pita, but so far it worked for me.

**Comment by noahfalk** [comment] 2018-04-10 21:38
FWIW, the entire usage of AspNet-GenerateStore.ps1 was a workaround for earlier CLI's that didn't have proper store integration built in. Presumably that is no longer an issue and no customer would run a script like this when they ran their own ASP.NET app. It might be more efficient to drop the powershell script and modify the test to use the supported steps real customers use.

**Comment by adiaaida** [comment] 2018-04-12 16:11
It looks like this is working again. Not sure what changed, but it's all back.

**Comment by RussKeldorph** [comment] 2018-04-13 17:14
@adiaaida Does this need to be fixed in 2.1?

**Comment by adiaaida** [comment] 2018-04-13 19:40
Yes, it appears this is an issue in the 2.1 branch as well. I'm wondering if it is actually a machine issue, rather than a test issue, since @adamsitnik can't repro it.

**Comment by RussKeldorph** [comment] 2018-04-13 21:25
@valenis Do you have someone to assign to this?

**Comment by noahfalk** [comment] 2018-04-14 03:26
FWIW, here is a WIP commit that does most of what is necessary to get rid of CreateStore. It can either use the ASP.NET that would come by default in more recent versions of the SDK, or you can set an exact version to get it to line up with a specific CoreFX you want to use.

https://github.com/noahfalk/coreclr/tree/avoid_createstore

**Comment by noahfalk** [comment] 2018-04-16 08:35
Sorry somehow I started thinking this was a different issue, but obviously its the same NuGet symptom as before. I still think that it is likely a machine/network issue (albeit not a transient one), and I don't think eliminating CreateStore will workaround it. The same nuget task will just get invoked during build and presumably fail there instead. If we have a way to reimage the machine, or run the perf test on a different machine that might be a quick way to overcome the problem. If not someone will have to get access to the machine and do deeper investigation.

I still think there is value in eliminating CreateStore and I needed the changes for some experiments I wanted to run privately, but it can be handled separately.

**Comment by adamsitnik** [comment] 2018-04-16 11:08
I can't repo it and I am using a totally different network (I work remotely from Poland). 

As I said previously we should try `dotnet restore --ignore-failed-sources` before running `dotnet store` to see if it helps.

**Comment by RussKeldorph** [comment] 2018-04-24 17:11
Sounds like this isn't going to block 2.1.  Please correct if so.

**Comment by noahfalk** [comment] 2018-04-27 10:27
I was able to repro and I believe diagnose it. Given the difficulties others were having reproing and its similarity to existing network issues other NuGet users reported it did appear like a machine issue, but actually it was our old friend the CoreCLR <-> CoreFX version mismatch in disguise. It further convinces me we should spend some additional time to get the automated version updates the functional tests are benefiting from.

The real issue appears to be that if you sync your CoreCLR source beyond a certain commit (I didn't work out exactly which one) and then run JitBench using your local build, your mismatched CoreCLR/CoreFX bits will be used to run the NuGet restore that is occurring inside the CreateStore. A MissingMethodException will get thrown inside the managed socket networking code. Due to some questionable exception handling code in the networking layer the MissingMethodException will wind up being caught, ignored, and a new SocketErrorException will be thrown in its stead with a SocketError code of -1. That exception eventually ripplies upward through the stack resulting in the NuGet failure unknown error 0xffffffff. I've got more details logged if anyone wants to see it, but the fix is relatively simple, update the CoreFX version we install to match CoreCLR's mscorlib and everything runs smoothly.

The fix is included with some other fixes here: #17811 
I don't know yet whether it works in our automation, but it did resolve the problems I was able to repro locally.

**Comment by danmosemsft** [comment] 2018-04-27 13:49
> questionable exception handling code in the networking layer

@stephentoub anything need fixing?

**Comment by stephentoub** [comment] 2018-04-27 14:59
What code?

**Comment by noahfalk** [comment] 2018-04-27 20:34
I already sent @karelz  an email with all the details last night for networking aspect. Its arguable whether there will enough other issues similar to the obscure case we had here to make it worth changing and I didn't spend time trying to understand the constraints they were under to write the exception handling the way it is.

**Comment by RussKeldorph** [comment] 2019-05-22 17:52
@billwert @adiaaida @adamsitnik I assume this should be closed in favor of the dotnet/performance-based infra.  Please re-open if I'm wrong.

**Closed by RussKeldorph** 2019-05-22 17:52 UTC
Labels: area-Infrastructure
