### ISSUE TITLE
Try to build with VS2015

### ISSUE THREAD

**Issue by cnblogs-dudu** [dotnet/coreclr#359] opened 2015-02-27 13:20 UTC
Modified some build scripts and ran building with VS2015. But got 104 errors. 
![screen shot 2015-02-27 at 21 16 55](https://cloud.githubusercontent.com/assets/3196961/6413047/10710b8a-bec6-11e4-9002-c3fd7dd937ed.png)
Searched the CoreCLR_Windows_NT__x64__debug.log, Found 208 following errors.
```
error C2220: warning treated as error - no 'object' file generated
```
The fearture branch: https://github.com/cnblogs-dudu/coreclr/tree/build-with-vs2015

**Comment by benpye** [comment] 2015-02-27 16:55
Duplicate of #30 ?

**Comment by cnblogs-dudu** [comment] 2015-02-28 03:36
If remove `add_compile_options(/WX)` from CMakeLists.txt, the C220 errors disappear. But get 1315  errors with `error LNK2001: unresolved external symbol`.
![screen shot 2015-02-28 at 11 31 07](https://cloud.githubusercontent.com/assets/3196961/6424668/6df1403c-bf3d-11e4-900c-8ad21b5d7160.png)
The detail errors: https://gist.github.com/cnblogs-dudu/36b92fdad1944b4694d0

**Comment by cnblogs-dudu** [comment] 2015-02-28 07:32
There are 1384 errors when opening and building "binaries\intermediates\Windows_NT.x64.debug\CoreCLR.sln" with VS2015. CoreCLR.sln is produced by cmake -G "Visual Studio 14 2015 Win64".
![screen shot 2015-02-28 at 15 17 30](https://cloud.githubusercontent.com/assets/3196961/6425283/08565eea-bf5d-11e4-9393-de10c1a6b9be.png)
View full errors: https://gist.github.com/cnblogs-dudu/7660ac9832f3a9323435

**Comment by davidfowl** [comment] 2015-02-28 09:43
Looks like a dupe of #30

**Closed** 2015-02-28 23:56 UTC
