### ISSUE TITLE
JIT tests failing in CI

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#3664] opened 2016-03-11 20:36 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/353/testReport/junit/JIT/_Methodical_MDArray_basics_classarr_cs_d_classarr_cs_d_/_Methodical_MDArray_basics_classarr_cs_d_classarr_cs_d_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/353/testReport/junit/JIT/_Methodical_int64_misc__il_relbinop__il_relbinop_/_Methodical_int64_misc__il_relbinop__il_relbinop_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/353/testReport/junit/JIT/_CodeGenBringUpTests_FPDivConst_FPDivConst_/_CodeGenBringUpTests_FPDivConst_FPDivConst_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/353/testReport/junit/JIT/_Directed_Convert_FPZero_FPZero_/_Directed_Convert_FPZero_FPZero_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/353/testReport/junit/JIT/_Methodical_explicit_basic__opt_dbgrefarg_i4__opt_dbgrefarg_i4_/_Methodical_explicit_basic__opt_dbgrefarg_i4__opt_dbgrefarg_i4_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/353/testReport/junit/JIT/_Methodical_Boxing_functional__orelfibo_cs__orelfibo_cs_/_Methodical_Boxing_functional__orelfibo_cs__orelfibo_cs_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/353/testReport/junit/JIT/_Methodical_NaN_r8NaNmul_cs_r_r8NaNmul_cs_r_/_Methodical_NaN_r8NaNmul_cs_r_r8NaNmul_cs_r_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/353/testReport/junit/JIT/_Methodical_tailcall__il_dbgcompat_i4_u__il_dbgcompat_i4_u_/_Methodical_tailcall__il_dbgcompat_i4_u__il_dbgcompat_i4_u_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/343/testReport/JIT/_jit64_valuetypes_nullable_castclass_null_castclass_null025_castclass_null025_/_jit64_valuetypes_nullable_castclass_null_castclass_null025_castclass_null025_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/x64_release_windows_nt_pri1/344/testReport/JIT/_Methodical_divrem_rem_r8rem_cs_do_r8rem_cs_do_/_Methodical_divrem_rem_r8rem_cs_do_r8rem_cs_do_cmd/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/73/testReport/junit/JIT.Performance.CodeQuality.BenchmarksGame.pidigits/pi-digits/pi_digits/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/73/testReport/junit/JIT.Regression.CLR-x86-EJIT.V1-M09.5-PDC.b14426/b14426/b14426/
There may be more.

**Comment by RussKeldorph** [comment] 2016-03-12 05:17
The repro is very inconsistent.

**Comment by RussKeldorph** [comment] 2016-03-14 14:06
@sejongoh @LLITCHEV Re-running tests on *Release* bits will sometimes repro failures like above, but it is far from consistent, and failures occur in many different tests, both inside and outside the JIT folder, so I'm skeptical these are due to the JIT.  Please keep an eye on this, though.  If they continue to repro, we'll need to investigate with more urgency.

**Comment by jkotas** [comment] 2016-03-16 17:24
For reference, the last two fail with:

JIT.Performance.CodeQuality.BenchmarksGame.pidigits.pi-digits.pi-digits:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Numerics, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040 (FUSION_E_REF_DEF_MISMATCH))


JIT.Regression.CLR-x86-EJIT.V1-M09.5-PDC.b14426.b14426.b14426:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.Debug, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040 (FUSION_E_REF_DEF_MISMATCH))

**Comment by dagood** [comment] 2016-03-17 20:38
I have a local OSX repro for those last two that I'm trying to make sense of. In short, it doesn't seem like a nuget problem, but I don't know what the desired behavior of some tools are so I don't know how to go about solving it.

My repro is running
`~/core-win/coreclr/bin/tests/Windows_NT.x64.Debug/Tests/coreoverlay/corerun ~/core-win/coreclr/bin/tests/Windows_NT.x64.Debug/JIT/Performance/CodeQuality/BenchmarksGame/pidigits/pi-digits/pi-digits.exe`

(The neighboring binarytrees test works:
`~/core-win/coreclr/bin/tests/Windows_NT.x64.Debug/Tests/coreoverlay/corerun ~/core-win/coreclr/bin/tests/Windows_NT.x64.Debug/JIT/Performance/CodeQuality/BenchmarksGame/binarytrees/binarytrees/binarytrees.exe`)

The maybe-important bits of my env are:
```
COMPlus_LogLevel=9
COMPlus_StartupDelayMS=
SHELL=/bin/bash
COMPlus_LogPath=fusionlog.txt
COMPlus_LogEnable=1
COMPlus_LogToConsole=
USER=dagood
COMPLUS_ForceLog=1
CORE_ROOT=/Users/dagood/core-win/coreclr/bin/tests/Windows_NT.x64.Debug/Tests/Core_Root
PATH=/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/dagood/.dnx/bin:/Library/Frameworks/Mono.framework/Commands:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet/bin
PWD=/Users/dagood/core-win/coreclr/bin/tests/Windows_NT.x64.Debug/JIT/Performance/CodeQuality/BenchmarksGame/pidigits/pi-digits
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/dagood
COMPlus_LogToFile=0
COMPlus_ForceLog=1
...
```
(Note `CORE_ROOT` is set. I changed some other things to get at the fusion log but they don't affect success.)

With that, the output of the test is:
> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Numerics, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040 (FUSION_E_REF_DEF_MISMATCH))
> Abort trap: 6

The dll in `CORE_ROOT` is the requested version with the requested public key. It comes from the `System.Runtime.Numerics 4.0.1-rc2-23816` package specified in https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/config/benchmark/project.json.

However the one in the overlay directory (the same directory as `corerun`, `~/core-win/coreclr/bin/tests/Windows_NT.x64.Debug/Tests/coreoverlay/System.Runtime.Numerics.dll`) was actually built on my OSX corefx repo.

In fact, copying the dll from `CORE_ROOT` to the overlay dir allows the pi-digits test to run.

So, it seems that the test is (for some reason) incompatible with the dll being built on unix rather than from a package. If it should work with it, that should be fixed--but I have no idea what the loading issue is in the first place.

The other angle to solve it is that the dlls in `CORE_ROOT` should be used. This doesn't seem right to me (why are all those dlls in the overlay folder if not to be tested?) but this situation reminds me of https://github.com/dotnet/cli/issues/1663.

Does anyone know where to go from here?

**Comment by sejongoh** [comment] 2016-03-17 20:52
The problem above looks related to https://github.com/dotnet/coreclr/pull/3782.

**Comment by dagood** [comment] 2016-03-17 21:55
@sejongoh Thanks, I didn't see that logic in runtests. I'll see if that (or something like it) fixes this.

**Comment by dagood** [comment] 2016-03-18 22:34
@sejongoh Hmm, this dll doesn't exist in any subfolders so I don't think that's related.

The dll (in corefx) is in these places (`find bin/*.Debug -name System.Runtime.Numerics.dll`):
```
bin/AnyOS.AnyCPU.Debug/System.Runtime.Numerics/System.Runtime.Numerics.dll
bin/OSX.AnyCPU.Debug/System.Runtime.Numerics/System.Runtime.Numerics.dll
bin/OSX.AnyCPU.Debug/System.Runtime.Numerics.Tests/System.Runtime.Numerics.dll
```

I think it's intended that the corefx-built dll is being tested... but I don't know where to look next for why it's not able to load.

/cc @ericstj Do you know why the packaged dll would work and not the corefx-built one? Or what to try next?

**Comment by RussKeldorph** [comment] 2016-03-23 17:04
@sergiy-k pls close per our conversation.

**Comment by sergiy-k** [comment] 2016-03-23 17:44
This should be addressed by https://github.com/dotnet/coreclr/pull/3840

**Closed by sergiy-k** 2016-03-23 17:44 UTC
Labels: bug, CodeGen

**Comment by AndyAyersMS** [comment] 2016-04-14 23:40
@RussKeldorph @sergiy-k I don't understand why this was closed. Many of the tests are still excluded. If the underlying issues were fixed we should be running some of these tests now.

**Comment by sergiy-k** [comment] 2016-04-15 22:58
The excluded tests should be re-enabled.

The failures were caused by a problematic test case that was running in parallel with these tests. The problematic test case (which was added around March 9-10) was indefinitely allocating memory in a loop to create an OOM condition. This was causing other running in parallel tests to fail randomly.

**Comment by RussKeldorph** [comment] 2016-04-18 22:22
@AndyAyersMS I'm working on #4397 to reenable b14426 and pi-digits, but you write that "*Many* of the tests are still excluded."  Would just like to confirm: are there more I'm missing that are excluded via some means other than the .targets and .txt files immediately under the test folder?  I only found b14426 and pi-digits there, but I could easily have made a mistake.

**Comment by AndyAyersMS** [comment] 2016-04-18 23:02
First entry in this thread shows lots of tests failing and presumably also excluded, though I haven't double-checked to see if that's the case.

In general an exclusion mechanism w/o tagging is going to lead to lots of questions about which issues (if any) are tracking failures and resolutions. Tagging has its own set of problems, but at least when some issue is fixed we have some idea which tests should be likewise fixed....

**Comment by RussKeldorph** [comment] 2016-04-18 23:27
@AndyAyersMS Agreed the current exclusion mechanism is less than ideal, though at least it is "being worked on."  I can't find evidence the other tests listed above are disabled.  Spot checking http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_windows_nt/lastCompletedBuild/testReport/JIT/, they appear to be running, so I'll assume that's the case.
