### ISSUE TITLE
Sub-optimal codegen when using Sse.StaticCast<TFrom,TTo>() with non-VEX encoded HW intrinsics

### ISSUE THREAD

**Issue by voinokin** [dotnet/coreclr#18069] opened 2018-05-21 15:31 UTC
Below is the source code (basically this is an example of partial vector update code trimmed down for repro):

            // Setup constants
            Vector128<ushort> valuesIncrement = Sse2.SetAllVector128((ushort)0x0001U); // <== no. 1
            Vector128<ushort> opCookie = Sse.StaticCast<ulong, ushort>( //<== no. 2
                Sse2.SetVector128(
                    0x0001_0002_0003_0004UL,
                    0x0005_0006_0007_0008UL));

            // Setup initial condition
            Vector128<ushort> values = Sse2.SetVector128(
                (ushort)0x1111U, (ushort)0x2222U, (ushort)0x3333U, (ushort)0x4444U,
                (ushort)0x5555U, (ushort)0x6666U, (ushort)0x7777U, (ushort)0x8888U);

            // Simulate op
            Vector128<ushort> updateSelector = Sse2.SetAllVector128((ushort)0x0004U);
            Vector128<ushort> updateMask = Sse2.CompareEqual(updateSelector, opCookie);
            Vector128<ushort> newValues = Sse2.AddSaturate(values, valuesIncrement);

            // Generate codegen issue
            values =
                Sse.StaticCast<byte, ushort>(
                    Sse41.BlendVariable(
                        Sse.StaticCast<ushort, byte>(values),
                        Sse.StaticCast<ushort, byte>(newValues),
                        Sse.StaticCast<ushort, byte>(updateMask)));

            Console.WriteLine(values);

With  my i5-750 CPU (Nehalem uarch) which does not support VEX encoding, I've got the following asm code with .NET Core 2.1 RC1 JITter (look for the `PBLENDVB` instruction down below):

```
> 000007FE664F5D23  mov         ecx,1  
> 000007FE664F5D28  movd        xmm0,ecx  
> 000007FE664F5D2C  movaps      xmm1,xmm0  
> 000007FE664F5D2F  punpcklwd   xmm1,xmm0  
> 000007FE664F5D33  movaps      xmm0,xmm1  
> 000007FE664F5D36  pshufd      xmm0,xmm0,0  
>             Vector128<ushort> opCookie = Sse.StaticCast<ulong, ushort>(
>                 Sse2.SetVector128(
>                     0x0001_0002_0003_0004UL,
>                     0x0005_0006_0007_0008UL));
> 000007FE664F5D3B  mov         rcx,1000200030004h  
> 000007FE664F5D45  movq        xmm1,rcx  
> 000007FE664F5D4A  mov         rcx,5000600070008h  
> 000007FE664F5D54  movq        xmm2,rcx  
> 000007FE664F5D59  punpcklqdq  xmm2,xmm1  
> 000007FE664F5D5D  movaps      xmm1,xmm2  
> 
>             // Setup initial condition
>             Vector128<ushort> values = Sse2.SetVector128(
>                 (ushort)0x1111U, (ushort)0x2222U, (ushort)0x3333U, (ushort)0x4444U,
>                 (ushort)0x5555U, (ushort)0x6666U, (ushort)0x7777U, (ushort)0x8888U);
> 000007FE664F5D60  mov         ecx,8888h  
> 000007FE664F5D65  movd        xmm2,ecx  
> 000007FE664F5D69  mov         ecx,7777h  
> 000007FE664F5D6E  pinsrw      xmm2,ecx,1  
> 000007FE664F5D73  mov         ecx,6666h  
> 000007FE664F5D78  pinsrw      xmm2,ecx,2  
> 000007FE664F5D7D  mov         ecx,5555h  
> 000007FE664F5D82  pinsrw      xmm2,ecx,3  
> 000007FE664F5D87  mov         ecx,4444h  
> 000007FE664F5D8C  pinsrw      xmm2,ecx,4  
> 000007FE664F5D91  mov         ecx,3333h  
> 000007FE664F5D96  pinsrw      xmm2,ecx,5  
> 000007FE664F5D9B  mov         ecx,2222h  
> 000007FE664F5DA0  pinsrw      xmm2,ecx,6  
> 000007FE664F5DA5  mov         ecx,1111h  
> 000007FE664F5DAA  movaps      xmm6,xmm2  
> 000007FE664F5DAD  pinsrw      xmm6,ecx,7  
> 
>             // Simulate op
>             Vector128<ushort> updateSelector = Sse2.SetAllVector128((ushort)0x0004U);
> 000007FE664F5DB2  mov         ecx,4  
> 000007FE664F5DB7  movd        xmm2,ecx  
> 000007FE664F5DBB  movaps      xmm3,xmm2  
> 000007FE664F5DBE  punpcklwd   xmm3,xmm2  
> 000007FE664F5DC2  movaps      xmm2,xmm3  
> 000007FE664F5DC5  pshufd      xmm2,xmm2,0  
>             Vector128<ushort> updateMask = Sse2.CompareEqual(updateSelector, opCookie);
> 000007FE664F5DCA  pcmpeqw     xmm1,xmm2  
>             Vector128<ushort> newValues = Sse2.AddSaturate(values, valuesIncrement);
> 000007FE664F5DCE  paddusw     xmm0,xmm6  
> 
>             // Generate codegen issue
>             values =
>                 Sse.StaticCast<byte, ushort>(
>                     Sse41.BlendVariable(
>                         Sse.StaticCast<ushort, byte>(values),
>                         Sse.StaticCast<ushort, byte>(newValues),
>                         Sse.StaticCast<ushort, byte>(updateMask)));
> 000007FE664F5DD2  movups      xmmword ptr [rbp-4D0h],xmm0  
> 000007FE664F5DD9  movaps      xmm0,xmm1  
> 000007FE664F5DDC  movups      xmm1,xmmword ptr [rbp-4D0h]  
> 000007FE664F5DE3  movaps      xmm2,xmm6  
> 000007FE664F5DE6  pblendvb    xmm2,xmm1,xmm0  <===========================
> 000007FE664F5DEB  movaps      xmm6,xmm2  
> 
>             Console.WriteLine(values);
> 000007FE664F5DEE  mov         rcx,7FE664E6750h  
> 000007FE664F5DF8  call        000007FEC5FB1940  
> 000007FE664F5DFD  mov         rcx,rax  
> 000007FE664F5E00  movups      xmmword ptr [rcx+8],xmm6  
> 000007FE664F5E04  call        000007FE664F3088

```
There are lots of `MOVxPS` before `PBLENDVB` for which I can't see any purpose, some spilling the register's content on stack and then loading it back. `Sse41.BlendVariable()` is not the only HW intrinsic which displays the issue when input vectors are typecasted before being set as parameters, but it gives the worst case seen by me so far, esp. taking into account that the blend insn is not really fast, and there is no good general case alternative (the only viable one is a sequence of And + AndNot + Or). 
I have feeling that `Sse.StaticCast<TFrom,TTo>()` contributes a lot to presence of `MOVxPS`, whereas it is supposed to be just typecasting operation triggering something during compile time, but not at runtime. The `MOVxPS` insns do not always appear, looks like codegen optimizes some away, but it's hard to predict - it is common case to see ~30 such insns within the span of 85-90 SSE insns when my code is JITted, and it's obvious that at most half of them are really required. Although I know pre-VEX CPUs are old :-) to align to, it's obvious that there is codegen issue.

Getting back to the issue, it is interesting to note that if one would swap two first statements in the source code (marked as "line no. 1" and "line no. 2"), then the codegen is much cleaner:

```
>             Vector128<ushort> newValues = Sse2.AddSaturate(values, valuesIncrement);
> 000007FE64285DCE  paddusw     xmm1,xmm6  
> 
>             // Generate codegen issue
>             values =
>                 Sse.StaticCast<byte, ushort>(
>                     Sse41.BlendVariable(
>                         Sse.StaticCast<ushort, byte>(values),
>                         Sse.StaticCast<ushort, byte>(newValues),
>                         Sse.StaticCast<ushort, byte>(updateMask)));
> 000007FE64285DD2  movaps      xmm2,xmm6  
> 000007FE64285DD5  pblendvb    xmm2,xmm1,xmm0  
> 000007FE64285DDA  movaps      xmm6,xmm2  
> 
>             Console.WriteLine(values);
> 000007FE64285DDD  mov         rcx,7FE64276750h  
> 000007FE64285DE7  call        000007FEC3D41940  
> 000007FE64285DEC  mov         rcx,rax  
> 000007FE64285DEF  movups      xmmword ptr [rcx+8],xmm6  
> 000007FE64285DF3  call        000007FE64283088  
```

(Just checked with Haswell CPU - no major issues appear when VEX-encoded)

**Comment by mikedn** [comment] 2018-05-21 16:57
I played a bit with it and it seems that the issue is not related to `StaticCast`, I removed it during import and the generated code still has issues. This is more likely a variant of #18068, possibly exacerbated by the fact that blend has 3 operands and the last one is required to be in `xmm0`.

**Comment by voinokin** [comment] 2018-05-21 18:35
@mikedn  Thanks for the explanation regarding `xmm0` and `PBLENDVB` - I missed that in insn description.
Below is another piece of code I have to check whether it's smth with `StaticCast<,>()` or not:

```
        unsafe static ulong GetKeyPart(
            void* pKeyData, ulong ofst, ulong keyDataLength,
            Vector128<sbyte> cookie)
        {
            byte* pKeyPartData = (byte*)pKeyData + ofst;
            ofst -= keyDataLength;

            Vector128<ulong> keyDataU64 =
                Sse2.LoadScalarVector128((ulong*)pKeyPartData);

            Vector128<int> relativeOfstI32 =
                Sse.StaticCast<ulong, int>(Sse2.ConvertScalarToVector128UInt64(ofst));
            Vector128<sbyte> zeroesI8 =
                Sse2.SetZeroVector128<sbyte>();

            Vector128<short> relativeOfstI16 =                  // Non-negative (MSB=0) if input <keyPartsOfst> is at or past <keyDataLengths>
                Sse2.PackSignedSaturate(relativeOfstI32, Sse.StaticCast<sbyte, int>(zeroesI8));

            Vector128<sbyte> relativeOfstI8 =
                Sse2.PackSignedSaturate(relativeOfstI16, Sse.StaticCast<sbyte, short>(zeroesI8));

            Vector128<sbyte> positionsAdj =                     // Distribute [+127; -128] value calculated for each key to all key position bytes
                Ssse3.Shuffle(relativeOfstI8, zeroesI8);
            Vector128<sbyte> keyDataI8 =                        // Reverse order of bytes in the data read
                Ssse3.Shuffle(Sse.StaticCast<ulong, sbyte>(keyDataU64), cookie);

            positionsAdj =                                      // Non-negative values in each byte mask away key data bytes
                Sse2.AddSaturate(positionsAdj, cookie);

            Vector128<sbyte> mask =
                Sse2.CompareGreaterThan(zeroesI8, positionsAdj);

            return Sse2.ConvertToUInt64(Sse.StaticCast<sbyte, ulong>(Sse2.And(keyDataI8, mask)));
        }

...

            byte* pData = stackalloc byte[]
            {
                0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
                0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F,
            };

            Vector128<sbyte> cookie =
                Sse.StaticCast<ulong, sbyte>(Sse2.SetVector128(
                    0x00_01_02_03_04_05_06_07UL,
                    0x00_01_02_03_04_05_06_07UL)); // byte positions reverser

            ulong keyPart = GetKeyPart(pData, 1, 8, cookie);
            Console.WriteLine("{0:X16}", keyPart);
```
I've got the following asm code after `GetKeyPart()` has been JITted, note the `MOVAPS` when vector with zeroes is being typecasted (marked with arrow). 

```
            byte* pKeyPartData = (byte*)pKeyData + ofst;
000007FE776026C0  lea         rax,[rcx+rdx]  
            ofst -= keyDataLength;
000007FE776026C4  sub         rdx,r8  

            Vector128<ulong> keyDataU64 =
                Sse2.LoadScalarVector128((ulong*)pKeyPartData);
000007FE776026C7  movq        xmm0,mmword ptr [rax]  

            Vector128<int> relativeOfstI32 =
                Sse.StaticCast<ulong, int>(Sse2.ConvertScalarToVector128UInt64(ofst));
000007FE776026CB  movq        xmm1,rdx  
            Vector128<sbyte> zeroesI8 =
                Sse2.SetZeroVector128<sbyte>();
000007FE776026D0  pxor        xmm2,xmm2  

            Vector128<short> relativeOfstI16 =                  // Non-negative (MSB=0) if input <keyPartsOfst> is at or past <keyDataLengths>
                Sse2.PackSignedSaturate(relativeOfstI32, Sse.StaticCast<sbyte, int>(zeroesI8));
000007FE776026D4  movaps      xmm3,xmm2  <=========================
000007FE776026D7  packssdw    xmm1,xmm3  

            Vector128<sbyte> relativeOfstI8 =
                Sse2.PackSignedSaturate(relativeOfstI16, Sse.StaticCast<sbyte, short>(zeroesI8));
000007FE776026DB  movaps      xmm3,xmm2  <=========================
000007FE776026DE  packsswb    xmm1,xmm3  

            Vector128<sbyte> positionsAdj =                     // Distribute [+127; -128] value calculated for each key to all key position bytes
                Ssse3.Shuffle(relativeOfstI8, zeroesI8);
000007FE776026E2  pshufb      xmm1,xmm2  
            Vector128<sbyte> keyDataI8 =                        // Reverse order of bytes in the data read
                Ssse3.Shuffle(Sse.StaticCast<ulong, sbyte>(keyDataU64), cookie);
000007FE776026E7  movups      xmm3,xmmword ptr [r9]  
000007FE776026EB  pshufb      xmm0,xmm3  

            positionsAdj =                                      // Non-negative values in each byte mask away key data bytes
                Sse2.AddSaturate(positionsAdj, cookie);
000007FE776026F0  movups      xmm3,xmmword ptr [r9]  
000007FE776026F4  paddsb      xmm1,xmm3  

            Vector128<sbyte> mask =
                Sse2.CompareGreaterThan(zeroesI8, positionsAdj);
000007FE776026F8  pcmpgtb     xmm2,xmm1  

            return Sse2.ConvertToUInt64(Sse.StaticCast<sbyte, ulong>(Sse2.And(keyDataI8, mask)));
000007FE776026FC  pand        xmm0,xmm2  
000007FE77602700  movq        rax,xmm0  
000007FE77602705  ret  
```

Is it related to `StaticCast`, or this is some other issue?
Thanks.

**Comment by mikedn** [comment] 2018-05-21 19:03
> Is it related to StaticCast

Yep, it looks like. With it removed during IL import I get:
```asm
       488D0411             lea      rax, [rcx+rdx]
       492BD0               sub      rdx, r8
       660FEFC0             pxor     xmm0, xmm0
       66480F6ECA           movd     xmm1, rdx
       660F6BC8             packssdw  xmm1, xmm0
       660F63C8             packsswb  xmm1, xmm0
       660F3800C8           pshufb   xmm1, xmm0
       410F1011             movups   xmm2, xmmword ptr [r9]
       660FECCA             paddsb   xmm1, xmm2
       660F64C1             pcmpgtb  xmm0, xmm1
       F30F7E08             movq     xmm1, xmmword ptr [rax]
       410F1011             movups   xmm2, xmmword ptr [r9]
       660F3800CA           pshufb   xmm1, xmm2
       660FDBC8             pand     xmm1, xmm0
       66480F7EC8           movd     rax, xmm1
```

```

**Comment by tannergooding** [comment] 2018-06-23 16:02
Looks like there is still a remaining `StaticCast` issue:
```asm
movaps   xmm0, xmm7
movaps   xmm1, xmm6
pblendvb  xmm1, xmm8
```

Looking at the JIT dump now...

**Comment by tannergooding** [comment] 2018-06-23 16:02
Most of the remaining issues are with `SetAllVector128` and `SetVector128`

This:
```asm
movd     xmm0, xrcx
movaps   xmm1, xmm0
punpcklwd xmm1, xmm0
pshufd   xmm0, xmm1, 0
```
could be:
```asm
movd     xmm0, xrcx
punpcklwd xmm0, xmm0
pshufd   xmm0, xmm0, 0
```

Which matches the register assignment for VEX machines:
```asm
vmovd    xmm0, xrcx
vpunpcklwd xmm0, xmm0, xmm0
vpshufd  xmm0, xmm0, 0
```

Same for:
```asm
movd     xmm1, xrcx
movaps   xmm1, xmm1
punpcklwd xmm1, xmm1
```
could be:
```asm
```

Which matches:
```asm
vmovd    xmm2, xrcx
vpunpcklwd xmm2, xmm2, xmm2
vpshufd  xmm2, xmm2, 0
```

For both VEX and non-VEX, it doesn't realize that it can use a single register all the way through...
```asm
pinsrw   xmm1, xrcx, 6
mov      ecx, 0x1111
movaps   xmm6, xmm1
pinsrw   xmm6, xrcx, 7
```
and
```asm
vpinsrw  xmm2, xmm2, xrcx, 6
mov      ecx, 0x1111
vpinsrw  xmm6, xmm2, xrcx, 7
```

For VEX and non-VEX, It doesn't detect last use and doesn't reuse the register:
```asm
movaps   xmm7, xmm1
pcmpeqw  xmm7, xmm2
movaps   xmm8, xmm6
paddusw  xmm8, xmm0
```
Could be:
```asm
pcmpeqw  xmm1, xmm2
paddusw  xmm6, xmm0
```

And
```asm
vpcmpeqw xmm7, xmm2, xmm1
vpaddusw xmm8, xmm6, xmm0
```
could be:
```asm
vpcmpeqw xmm2, xmm2, xmm1
vpaddusw xmm6, xmm6, xmm0
```

**Comment by tannergooding** [comment] 2018-06-23 16:10
Ok, the issue here: https://github.com/dotnet/coreclr/issues/18069#issuecomment-399689033, isn't a static cast issue.

`BlendVariable` requires that `UpdateMask` live in XMM0 for non-VEX encoding (`movaps   xmm0, xmm7` is required). -- I wonder if it would be particularly hard to have the JIT understand this requirement, as an optimization (it only impacts older hardware without VEX-encoding support)

And the other (`movaps   xmm1, xmm6`) looks like a last use issue, similar to what I mentioned above.

**Comment by voinokin** [comment] 2018-06-23 17:40
@tannergooding Will `StaticCast<...>` pass thru "containment" mark obtained with load/store/partial reg use properly? Example code:

```
Vector128<uint> record0U32 = Sse.StaticCast<ulong, uint>(Sse2.LoadScalarVector128((ulong*)ptr1));
Vector128<uint> record1U32 = Sse.StaticCast<ulong, uint>(Sse2.LoadScalarVector128((ulong*)ptr2));
Vector128<ulong> records01U64 =
                Sse.StaticCast<uint, ulong>(Sse2.UnpackLow(record0U32, record1U32));
```

I would expect that in ideal world :-) `record1U32` will be treated as in-memory operand to `UnpackLow` (of course when `record1U32` is not used further).

**Comment by tannergooding** [comment] 2018-06-23 18:02
@voinokin, it is actually just folded away entirely in the importer, so no later stages (lowering, register allocation, codegen, emit, etc) see `StaticCast` at all.

It is effectively as if you had written:
`Vector128<uint> record0U32 = Sse2.LoadVector128((ulong*)ptr1);`

The code above *should* generate:
```asm
movups xmm, [ptr1]
punpckldq xmm, [ptr2]
```

**Comment by tannergooding** [comment] 2018-07-12 03:36
@voinokin, I'm going to close this as the original issue is fixed. Feel free to reopen/update if you feel otherwise.

**Closed by tannergooding** 2018-07-12 03:36 UTC
Labels: area-CodeGen, enhancement, optimization

**Comment by voinokin** [comment] 2018-07-12 05:11
Thank you!
I'll re-check my code with the first preview of 2.2 when it's available
