### ISSUE TITLE
[arm64] Test failed: System.Diagnostics.Tests.StackTraceTests.ToString_NullFrame_ThrowsNullReferenceException

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24108] opened 2019-04-19 01:17 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress1_tst/170/

**Failed tests:**
System.Diagnostics.Tests.StackTraceTests.ToString_NullFrame_ThrowsNullReferenceException

**Log:**
```
System.Diagnostics.Tests.StackTraceTests.ToString_NullFrame_ThrowsNullReferenceException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.NullReferenceException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1/_/fx/src/System.Diagnostics.StackTrace/tests/StackTraceTests.cs(324,0): at System.Diagnostics.Tests.StackTraceTests.ToString_NullFrame_ThrowsNullReferenceException()
```

**Comment by BruceForstall** [comment] 2019-04-19 16:32
Also fails in baseline:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/172/

@karelz Can you get someone to look at this?

**Comment by karelz** [comment] 2019-04-19 18:18
@BruceForstall is it urgent?
How often does it fail? Always? Sometimes? Rarely?

BTW: Here are [area owners](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas) if you need experts. Would be nice to clarify urgency / priority first though.

**Comment by BruceForstall** [comment] 2019-04-19 18:25
@karelz It's a regression in our outerloop CI testing, which leads to run failures. So yes, it is urgent. The immediately solution could be to just disable this assembly from testing.

This also fails on x64: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/836/consoleFull

So it appears to be all-platform.

And unfortunately, we have no mechanism for disabling x86/x64 outerloop corefx test failures in our CI. So that makes getting a fix even higher priority.

cc @sandreenko @RussKeldorph

**Comment by BruceForstall** [comment] 2019-04-19 18:28
Looks like the owners here are @wtgodbe, @krwq

**Comment by RussKeldorph** [comment] 2019-04-19 18:29
@wfurt

**Comment by wtgodbe** [comment] 2019-04-19 18:32
The test just changed in CoreFx 3 hours ago to assert that ToString() returns a newLine, rather than throwing an exception: https://github.com/dotnet/corefx/commit/8fa3e3c3624967a4049070791788f0602b2581e1#diff-c5d0955556fa8ba396168e66bd6ad18e.

**Comment by BruceForstall** [comment] 2019-04-19 18:53
Triggered new runs to verify fix (note that these jobs pick up live corefx bits):

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_flow/206/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/

**Comment by BruceForstall** [comment] 2019-04-19 21:31
Looks like it's passing now. Closing.

**Closed by BruceForstall** 2019-04-19 21:31 UTC
Labels: JitStress, arch-arm64, bug, test-corefx
