### ISSUE TITLE
Expose ICustomMarshaler

### ISSUE THREAD

**Issue by jazzdelightsme** [dotnet/coreclr#1767] opened 2015-10-14 21:47 UTC
The ICustomMarshaler machinery exists in mscorlib, but the actual interface has been marked internal. Let's make it public so that people can use it.

**Comment by joshfree** [comment] 2015-11-04 08:02
closing this out as a duplicate of https://github.com/dotnet/corefx/issues/1346

**Closed by joshfree** 2015-11-04 08:02 UTC
Labels: mscorlib
