### ISSUE TITLE
AssemblyLoadContext : issue with dynamic assemblies and custom ALC

### ISSUE THREAD

**Issue by davjohna** [dotnet/coreclr#9030] opened 2017-01-20 22:52 UTC
There appears to be a problem with using a custom AssemblyLoadContext combined with dynamic assemblies that have a dependency on a custom ALC-loaded assembly. This issue was tested and found in .NET Core 1.0.0, 1.0.3 (LTS), and 1.1.0. A good example is using the XmlSerializer, since it generates a dynamic assembly to serialize types.
 
Steps to reproduce:
 
1. Setup two projects: XmlTest, and BadAlc.
2. For XmlTest in Program.cs, use (https://gist.github.com/davjohna/4d143cf4d73a3830f77fdc3b3ba143b9).
3. In XmlTest for project.json, use (https://gist.github.com/davjohna/281bd75991cc5868253e683b0e8883b3).
4. In BadAlc, in Program.cs, use (https://gist.github.com/davjohna/32b4699e41ebaf931a97a0b92f40afef).
4. In BadAlc, for project.json, use (https://gist.github.com/davjohna/79bb5ce2745fc90eed94257c05c6268d).
5. Do a “dotnet publish” of XmlTest, and copy all output of the bin/Debug/netcoreapp1.0/publish directory to the directory of your choice.
6. In BadAlc Program.cs,  add the location of NETCore.App 1.0.3 to line 31, and the path where you saved the XmlTest publish artifacts to line 32.
7. Do a “dotnet run” in BadAlc.
 
You should see a stack trace like the one below:
 
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.MissingMethodException: Method not found: 'System.Xml.XmlReader System.Xml.Serialization.XmlSerializationReader.get_Reader()'.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPerson.InitIDs()
   at System.Xml.Serialization.TempAssembly.InvokeReader(XmlMapping mapping, XmlReader xmlReader, Object events, String encodingStyle)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, Object events)

**Comment by jkotas** [comment] 2017-01-21 00:18
cc @gkhanna79 @rahku

**Comment by gkhanna79** [comment] 2017-01-23 19:46
Why are you trying to load FX assemblies? They are automatically loaded/resolved for you if your Load implementation returns null.

**Comment by gokarnm** [comment] 2017-01-23 20:20
Hi @gkhanna79, the reason we are loading FX assemblies in the custom ALC, is for isolating the statics of a FX assembly in default ALC vs. statics of the same FX assembly in custom ALC. Without this, they would share the same statics. If the static is modified by code loaded in custom ALC it would have a side effect on code in default ALC and vice versa.

**Comment by gkhanna79** [comment] 2017-01-23 21:24
@gokarnm I get the statics/load context implication. Is your application dependent upon state of statics that are part of assemblies external to your application (i.e. SharedFX)? If so, can you please help me understand why is that the case?

**Comment by gkhanna79** [comment] 2017-01-23 21:25
Also, there were bunch of issues around dynamically emitted assemblies in 1.0.x that were fixed in 1.1.0. Can you please share details of the repro for 1.1.0 as that would be a better baseline for discussion?

**Comment by gokarnm** [comment] 2017-01-24 02:34
>I get the statics/load context implication.

@gkhanna79, returning null from custom ALC's Load method will cause the default ALC to resolve the assembly. This means that loaded assembly is associated with the default ALC, so the statics are not isolated. Is my understanding correct?


>Is your application dependent upon state of statics that are part of assemblies external to your application (i.e. SharedFX)? If so, can you please help me understand why is that the case?

We have a host which loads plugins. We need isolation of statics present in dependencies of host code and plugin code. E.g. If the host code sets a static property on a type in SharedFx (say some global settings), we want the plugin code to have independent copy of the static so that it's not affected by the host code. Basically we are accounting for any such API in CoreFx. I'll try to come up with a concrete example.


>Can you please share details of the repro for 1.1.0 as that would be a better baseline for discussion?

Actually I'm not able to repro this for 1.1.0 with the exact same ALC code, loading assemblies from framework dir from custom ALC throw up exceptions like following. 
`
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) ---> System.IO.FileLoadException: Native image cannot be loaded multiple times`

Though when I modified the ALC to return null when a DLL is not found in plugin dir (where XmlTest is published), the XmlSerializer.Deserialize call fails with the same MissingMethodException exception. I'll share the code for this soon.

**Comment by gkhanna79** [comment] 2017-01-24 06:00
> This means that loaded assembly is associated with the default ALC, so the statics are not isolated. Is my understanding correct?

The statics will live in Default Load context. If that is what you meant by the above statement, then yes, that is correct.

To workaround the 1.1.0 exception issue above about loading native images multiple times, can you please try creating a copy of SharedFX folder and make your custom ALC load from this location and share what happens?

**Comment by gokarnm** [comment] 2017-01-24 20:58
Hi @gkhanna79 , I tried the workaround of loading from a copy of SharedFX folder, the exception about loading native images multiple times goes away. Subsequently the XmlSerializer.Deserialize fails with a MissingMethodException. 

>Also, there were bunch of issues around dynamically emitted assemblies in 1.0.x that were fixed in 1.1.0

We develop on .NET Core 1.0 LTS (1.0.3) , I would appreciate if you could share the commits for these fixes on 1.1.0, I'll try to back port them to 1.0.3 and create a local build.

Steps to repro for 1.1.0

1. Setup two projects: XmlTest, and Alc.
1. For XmlTest project in Program.cs, use [this](https://gist.github.com/gokarnm/612888b3949080c397a72fa7d13e3ff6).
1. In XmlTest project for project.json, use [this](https://gist.github.com/gokarnm/e811a37a795d0727f831644ba895d3a9).
1. In Alc project, in Program.cs, use [this](https://gist.github.com/gokarnm/d358c5748f499f4cb4367561fe69c593).
1. In Alc project, for project.json, use [this](https://gist.github.com/gokarnm/bfff9d1378acf4f9635849276f8fdd63)
1. Do a “dotnet publish” of XmlTest project and use the publish directory path ({root}/bin/Debug/netcoreapp1.1/publish) here - [Alc Program.cs line 28](https://gist.github.com/gokarnm/d358c5748f499f4cb4367561fe69c593#file-alc-program-cs-L28).
1. Create a copy of SharedFX for 1.1.0 and use the directory path here [Alc Program.cs line 27](https://gist.github.com/gokarnm/d358c5748f499f4cb4367561fe69c593#file-alc-program-cs-L27)
1. Do a “dotnet run” for Alc project

I see the following exception

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.MissingMethodException: Method not found: 'System.Xml.XmlReader System.Xml.Serialization.XmlSerializationReader.get_Reader()'.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPerson.InitIDs()
   at System.Xml.Serialization.TempAssembly.InvokeReader(XmlMapping mapping, XmlReader xmlReader, Object events, String encodingStyle)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, Object events)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, Object events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at XmlTest.Program.Test() 
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Alc.Loader.Load() 
   at Alc.Program.Main(String[] args)

**Comment by gokarnm** [comment] 2017-01-31 00:25
Hi @gkhanna79, any updates on this? Could you confirm if this is a bug or I'm missing something in my code? Let me know if any more information is required for a repro.

**Comment by gkhanna79** [comment] 2017-02-01 06:54
I am still investigating and will share what I find.

**Comment by gkhanna79** [comment] 2017-02-03 23:44
@gokarnm Fix is in PR at https://github.com/dotnet/coreclr/pull/9324

**Comment by gkhanna79** [comment] 2017-02-03 23:45
Fix PR for 1.1.0 is at https://github.com/dotnet/coreclr/pull/9320. Confirmed that with this change, it works as expected.

**Comment by gokarnm** [comment] 2017-02-04 00:15
Thanks @gkhanna79 !! @davjohna and me will test the fix and get back to you.

>Also, there were bunch of issues around dynamically emitted assemblies in 1.0.x that were fixed in 1.1.0

We develop on .NET Core 1.0 LTS (1.0.3) , I would really appreciate if you could share the commits/PRs for these fixes on 1.1.0 if possible. I would like to back port these other fixes related to dynamically emitted assemblies to latest CoreCLR 1.0.x and create a local build.

**Closed** 2017-02-04 06:19 UTC
Labels: area-Assembly Loader
