### ISSUE TITLE
ReadyToRun: NullReferenceException in superlong tests

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3606] opened 2016-03-09 02:45 UTC
Tests:
JIT\Methodical\int64\superlong\_dbgsuperlong\_dbgsuperlong.cmd
JIT\Methodical\int64\superlong\_relsuperlong\_relsuperlong.cmd
JIT\Methodical\int64\superlong\_il_relsuperlong\_il_relsuperlong.cmd
JIT\Methodical\int64\superlong\_il_dbgsuperlong\_il_dbgsuperlong.cmd

Repro steps:
 Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
           at JitTest.superlong.add(superlong op1, superlong op2)
           at JitTest.superlong.Main()

**Comment by LLITCHEV** [comment] 2016-03-10 04:28
This look like a duplicate of issue #3613 .  At leas I see same stack traces and it is related to exception handling processing. If not, please reopen it.

**Closed by LLITCHEV** 2016-03-10 04:28 UTC
Labels: bug, CodeGen, ReadyToRun
