### ISSUE TITLE
[Windows/ARM32] Windows cross build for Windows/ARM32 fails with missing includes and libs

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#12902] opened 2017-07-19 16:49 UTC
Build command 'build all arm Release|Debug|Checked skiptests' fails with the following errors:

```
E:/src/ms/dotnet/coreclrarm/src/debug/ee/arm/dbghelpers.asm(5): fatal error C1083: Cannot open include file: 'ksarm.h': No such file or directory [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Re
lease\src\debug\ee\wks\cordbee_wks.vcxproj]
E:/src/ms/dotnet/coreclrarm/src/vm/arm/asmhelpers.asm(10): fatal error C1083: Cannot open include file: 'ksarm.h': No such file or directory [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Release
\src\vm\wks\cee_wks.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'version.lib' [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Release\src\ToolBox\superpmi\superpmi\superpmi.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'WtsApi32.lib' [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Release\src\dlls\dbgshim\dbgshim.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'version.lib' [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Release\src\dlls\mscordbi\mscordbi.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'dbghelp.lib' [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Release\src\ToolBox\SOS\Strike\sos.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'version.lib' [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Release\src\jit\standalone\clrjit.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'version.lib' [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Release\src\jit\protojit\protojit.vcxproj]
LINK : fatal error LNK1181: cannot open input file 'version.lib' [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Release\src\tools\crossgen\crossgen.vcxproj]
```

Build fails always when done from VS2017 v15.2 or earlier developer command prompt.
Build fails with above errors when done from VS2017 v15.3 preview 4 developer command prompt

System: Windows 10 Pro v1703, base lang pl_PL, using en-US
Installed VS2015, VS2017 and preview 4 VS2017 v15.3
Installed Windows Kits: 10150, 10240, 10586, 14393, 15063
CMAKE v 3.9.0
build done on master branch commit a14608efbad1bcb4e9d36a418e1e5ac267c083fb

**Comment by RussKeldorph** [comment] 2017-07-19 17:27
Yeah, sorry, this is a known issue being followed up on.

Workaround:
- Use Add/Remove Programs to uninstall Windows Software Development Kit - Windows 10.0.15063.xxx
- Reinstall above component via https://go.microsoft.com/fwlink/?linkid=851955.  Make sure ARM SDKs are selected (they should be by default)

**Comment by RussKeldorph** [comment] 2017-07-19 17:31
Sorry, I should clarify that this is caused by an unfortunate decision to exclude the ARM SDK components by default when VS installs the SDK.  This is supposed to be corrected at some point, but I'm not sure when.

The more serious issue (the one I was referring to above) is that you can't just use Add/Remove Programs to "Change" the SDK and add the missing ARM files.  You have to actually uninstall/reinstall.

**Comment by 4creators** [comment] 2017-07-19 19:03
@RussKeldorph  Thank you for info on workaround

With reinstalled Windows Kit 15063 build succeeds up to a point which is indicated below:

Build commnd: `e:\src\ms\dotnet\coreclrarm>build all arm Debug skiptests` 

```
  -- Install configuration: "Debug"
  -- Installing: e:/src/ms/dotnet/coreclrarm/bin/Product/Windows_NT.arm.Debug/inc/corerror.h
.....
  -- Installing: e:/src/ms/dotnet/coreclrarm/bin/Product/Windows_NT.arm.Debug/PDB/ilasm.pdb

Build succeeded.

LINK : warning LNK4266: missing load config symbol for image built with /GUARD [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Debug\src\dlls\clretwrc\clretwrc.vcxproj]
LINK : warning LNK4266: missing load config symbol for image built with /GUARD [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Debug\src\dlls\mscorrc\small\mscorrc.vcxproj]
LINK : warning LNK4266: missing load config symbol for image built with /GUARD [E:\src\ms\dotnet\coreclrarm\bin\obj\Windows_NT.arm.Debug\src\dlls\mscorrc\full\mscorrc.debug.vcxproj]
    3 Warning(s)
    0 Error(s)

Time Elapsed 00:12:23.62
Command execution succeeded.
BUILD: Commencing build of cross architecture native components for Windows_NT.arm.Debug
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26711.1
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
The input line is too long.
The syntax of the command is incorrect.
C:\Users\developer\Source>
```

The last line indicates that at the end I have landed in another directory. What is even worse command prompt is left with almost all locally set environment variables and cannot be used for any subsequent build (I have to restart it)
These commands work:
```
C:\Users\developer\Source>cd /d e:\src\ms\dotnet\coreclrarm

e:\src\ms\dotnet\coreclrarm>build -?
Starting Build at 20:49:00,03

Build the CoreCLR repo.

Usage:
    build.cmd [option1] [option2]
or:
    build.cmd all [option1] [option2] -- ...

....
```
And any other more complex commands always fail with exactly the same error: `The input line is too long. The syntax of the command is incorrect.`
```
e:\src\ms\dotnet\coreclrarm>build all x64 skiptests
Starting Build at 20:52:56,13
BUILD: Invoking: call "e:\src\ms\dotnet\coreclrarm\build.cmd" x64 Debug skiptests
Starting Build at 20:52:56,18
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\Tools\\VsDevCmd.bat"
The input line is too long.
The syntax of the command is incorrect.
e:\src\ms\dotnet\coreclrarm>
```
Any ideas on what is the source of error?

**Comment by RussKeldorph** [comment] 2017-07-19 21:01
@4creators I haven't seen that one before.  My first guess is that your root folder name (`e:\src\ms\dotnet\coreclrarm`) is too long and is causing some internal command to exceed some Windows' limit.  I would first try building from a shorter root, like e:\coreclr.  If that works, feel free to open an issue.  No guarantees it would get traction, but it should certainly be fixed if this short root limit only applies to ARM builds.

If that doesn't work, you might have luck setting `_echo=1` in the environment and see if you get more insight into which input line is too long.

**Comment by stephentoub** [comment] 2017-10-04 16:28
@RussKeldorph, it looks like this is hitting in CI now:
https://ci.dot.net/job/dotnet_coreclr/job/release_2.0.0/job/arm_cross_debug_windows_nt_prtest/430/consoleText
```
D:/j/workspace/arm_cross_deb---8bd6fb7e/src/debug/ee/arm/dbghelpers.asm(5): fatal error C1083: Cannot open include file: 'ksarm.h': No such file or directory [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\debug\ee\wks\cordbee_wks.vcxproj]
D:/j/workspace/arm_cross_deb---8bd6fb7e/src/vm/arm/asmhelpers.asm(10): fatal error C1083: Cannot open include file: 'ksarm.h': No such file or directory [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\vm\wks\cee_wks.vcxproj]
LINK : fatal error LNK1104: cannot open file 'WtsApi32.lib' [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\dlls\dbgshim\dbgshim.vcxproj]
LINK : fatal error LNK1104: cannot open file 'dbghelp.lib' [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\ToolBox\SOS\Strike\sos.vcxproj]
LINK : fatal error LNK1104: cannot open file 'version.lib' [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\ToolBox\superpmi\superpmi\superpmi.vcxproj]
LINK : fatal error LNK1104: cannot open file 'version.lib' [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\dlls\mscordbi\mscordbi.vcxproj]
LINK : fatal error LNK1104: cannot open file 'version.lib' [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\jit\standalone\clrjit.vcxproj]
LINK : fatal error LNK1104: cannot open file 'version.lib' [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\jit\protojit\protojit.vcxproj]
LINK : fatal error LNK1104: cannot open file 'version.lib' [D:\j\workspace\arm_cross_deb---8bd6fb7e\bin\obj\Windows_NT.arm.Debug\src\tools\crossgen\crossgen.vcxproj]
```

**Comment by RussKeldorph** [comment] 2017-10-04 17:02
@BruceForstall @jashook FYI

**Comment by BruceForstall** [comment] 2017-10-04 21:02
@mmitche you said this is fixed now?

**Comment by mmitche** [comment] 2017-10-04 21:04
@BruceForstall I think it might require this https://github.com/dotnet/core-setup/pull/3254

**Comment by BruceForstall** [comment] 2017-12-11 23:02
I don't believe this problem exists anymore

**Closed by BruceForstall** 2017-12-11 23:02 UTC
Labels: arch-arm32, area-Build, tracking-external-issue
