### ISSUE TITLE
[arm/windows] System.Tests.ArgIteratorTests.ArgIterator_Throws_PlatformNotSupportedException failed in arm_cross_checked_windows_nt_corefx_minopts_tst

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21022] opened 2018-11-15 08:29 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_minopts_tst/35/

**Failed log:**
```
System.Tests.ArgIteratorTests.ArgIterator_Throws_PlatformNotSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.ArgumentException): Handle is not initialized.
      ---- System.ArgumentException : Handle is not initialized.
      Stack Trace:
           at System.ArgIterator..ctor(IntPtr arglist)
           at System.ArgIterator..ctor(RuntimeArgumentHandle arglist)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Runtime\tests\System\ArgIteratorTests.netcoreapp.cs(16,0): at System.Tests.ArgIteratorTests.<>c.<ArgIterator_Throws_PlatformNotSupportedException>b__0_0()
        ----- Inner Stack Trace -----
           at System.ArgIterator..ctor(IntPtr arglist)
           at System.ArgIterator..ctor(RuntimeArgumentHandle arglist)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Runtime\tests\System\ArgIteratorTests.netcoreapp.cs(16,0): at System.Tests.ArgIteratorTests.<>c.<ArgIterator_Throws_PlatformNotSupportedException>b__0_0()
  Finished:    System.Runtime.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Tests  Total: 22944, Errors: 0, Failed: 1, Skipped: 14, Time: 125.312s
----- end  8:29:47.61 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment] 2018-11-29 01:30
Actually, it looks like the test is designed to handle the not supported case, but isn't.

**Comment by BruceForstall** [comment] 2018-11-29 01:35
@maryamariyan It looks like you added this test with https://github.com/dotnet/corefx/pull/33369 and updated with https://github.com/dotnet/corefx/pull/33503. This test is failing when run on Windows arm32. Can you please change the test so it passes (or is disabled)?

**Comment by maryamariyan** [comment] 2018-12-03 23:36
@jashook based on https://github.com/dotnet/corefx/pull/33369#issuecomment-437449515, this test expects PlatformNotSupportedException. 
Could you then modify it to throw PlatformNotSupportedException?

**Comment by BruceForstall** [comment] 2019-01-09 20:39
@maryamariyan @jashook Do you know where the incorrect exception originates?

@maryamariyan Are you suggesting that the JIT needs to change? Should the issue be assigned instead to @jashook?

**Comment by jashook** [comment] 2019-01-09 22:11
@BruceForstall this can be assigned to me.

**Comment by jashook** [comment] 2019-03-15 20:22
Related to #23034

**Comment by jashook** [comment] 2019-04-03 15:51
Duplicate of #23034

**Closed** 2019-04-03 15:51 UTC
Labels: arch-arm32, os-windows, test-corefx
