### ISSUE TITLE
Move AVX/AVX2 intrinsic tests to template

### ISSUE THREAD

**Issue by fiigii** [dotnet/coreclr#19825] opened 2018-09-04 22:03 UTC
I will move all AVX/AVX2 intrinsic tests to the template after implement the remaining AVX2 intrinsic in JIT.

**Comment by 4creators** [comment] 2018-09-05 13:53
It's dupe of #19246 and that issue is already assigned. If you want to take it over pls remove my assignment and close it.

**Comment by RussKeldorph** [comment] 2019-01-24 18:11
Closing assuming duplicate of #19246.

**Closed by RussKeldorph** 2019-01-24 18:11 UTC
Labels: area-CodeGen, test enhancement
