### ISSUE TITLE
Enable building mscorlib on Linux and Mac OS X

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#463] opened 2015-03-16 04:32 UTC
Right now, mscorlib can only be built on Windows. 

Note the mscorlib instructions used here: http://praeclarum.org/post/110552954728/building-and-running-nets-coreclr-on-os-x.

**Comment by kangaroo** [comment] 2015-03-19 02:26
Dupe of #170 ?

**Closed** 2015-03-19 06:27 UTC
