### ISSUE TITLE
Enable reflection emit to emit void M(TimeSpan t = default(TimeSpan))

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#5369] opened 2016-06-01 14:24 UTC
Currently, reflection emit cannot emit [this particular pattern](http://tryroslyn.azurewebsites.net/#f:>il/K4Zwlgdg5gBAygTxAFwKYFsDcAoADsAIwBswBjGUogQxBBgGEYBvbGNmfYsmANwHswAExgBZABQAVMOlRxcVCDGQwAvDEGoAZlWBFkk6bPkQAlCeat2AX2xWgA==). The [documentation](https://msdn.microsoft.com/en-us/library/system.reflection.emit.parameterbuilder.setconstant(v=vs.110).aspx) is consistent with that.

            var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("x"), AssemblyBuilderAccess.RunAndSave);
            var moduleBuilder = assemblyBuilder.DefineDynamicModule("x");
            var typeBuilder = moduleBuilder.DefineType("C", TypeAttributes.Class);
            var methodBuilder = typeBuilder.DefineMethod("M", MethodAttributes.Static, CallingConventions.Standard, typeof(void), new[] { typeof(TimeSpan) });

            var parameterBuilder = methodBuilder.DefineParameter(0, ParameterAttributes.HasDefault, "p");
            parameterBuilder.SetConstant(null);

> An unhandled exception of type 'System.ArgumentException' occurred in mscorlib.dll
> Additional information: Null is not a valid constant value for this type.

It would be useful if this could be done using reflection emit. To be clear: This is not a bug report but a feature request. Maybe all that needs to be done is relax arguments validation.

**Comment by swgillespie** [comment] 2016-06-01 18:59
Seems like a dupe of https://github.com/dotnet/coreclr/issues/5368.

**Comment by GSPP** [comment] 2016-06-01 20:47
Yes, a dupe. I thought I'd report this problem as a public service.

**Comment by GSPP** [comment] 2016-06-01 20:48
Amazingly, the issues were opened the same *minute*.

**Comment by swgillespie** [comment] 2016-06-02 17:31
@GSPP quite the coincidence! :smile:

**Closed by swgillespie** 2016-06-02 17:31 UTC
