### ISSUE TITLE
Return error union value from native side to .netcore on macOS x64

### ISSUE THREAD

**Issue by enginekit** [dotnet/coreclr#11989] opened 2017-05-30 20:48 UTC
"Strange return union value from native side back to .netcore"
---
Hello, 

I get a strange value (err) from a native c function (built on macOS 10.12.5, x64) .

When I return a union by value from native side, I get a strange value / err ? value.
 
This is not correct value as I expect.

(but When I return a sequential struct by value from native side,
 I get a correct value as expect on .net side.)

This is a complete (sample) code. 

1.  native side, OverlapAB.cpp , 
     I build it to a dylib with XCode 8.3.2 on my macOS 10.12.5, x64

```C++


    #include <cstdint>
    #define EXPORT __attribute__((visibility("default")))
    extern "C"{
    
    
       struct XY{
           int32_t x;
           int32_t y;
       };
       union OverlapAB{
            int32_t a;
            int32_t b;
       };
    
    
       EXPORT int32_t GetSizeOfInt(){
               return sizeof(int32_t);
        };
       EXPORT int32_t GetSizeXY(){
               return sizeof(XY);
       };
       EXPORT int32_t GetSizeOAB(){
               return sizeof(OverlapAB);
        } 
       //-------
    
       EXPORT XY Send_XY(XY* v){
              //this return correct value of v
             return *v;
        };
       EXPORT OverlapAB Send_OAB(OverlapAB* v){
             //this return incorrect value of v
            return *v;
        }
    }
```

2. managed side, Program.cs
   I build it with Visual Studio for macOS 7.0.1, .netcore , same machine as above
  
```C#
     using System;
     using System.Text;
     using System.Runtime.InteropServices;
     using System.Diagnostics;

     namespace TestSendData
     { 
	[StructLayout(LayoutKind.Sequential)]
	struct XY
	{
		public int x;
		public int y;
	}

	[StructLayout(LayoutKind.Explicit)]
	struct OverlapAB
	{
		[FieldOffset(0)]
		public int a;
		[FieldOffset(0)]
		public int b;
	}


	static class MyNativeMethods
	{
            const string LIBNAME="TestSendData";

	    [DllImport(LIBNAME, CallingConvention = CallingConvention.Cdecl)]
	    public static extern int GetSizeOfInt();
            [DllImport(LIBNAME, CallingConvention = CallingConvention.Cdecl)]
	    public static extern int GetSizeXY(); 
	    [DllImport(LIBNAME, CallingConvention = CallingConvention.Cdecl)]
	    public static extern int GetSizeOAB();
           
            //---------------------------------------------------
	    [DllImport(LIBNAME, CallingConvention = CallingConvention.Cdecl)]
	    public static unsafe extern OverlapAB Send_OAB(OverlapAB* p1); 

	    [DllImport(LIBNAME, CallingConvention = CallingConvention.Cdecl)]
	    public static unsafe extern XY Send_XY(XY* p1);
	}
     
	class Program
	{
	     static void Main(string[] args)
	     {
		 //1. .net pointer size
		 int sizeOfIntPtr = IntPtr.Size;  //8 on x64

		 //2. test native object size
		 int sizeOfInt32 = MyNativeMethods.GetSizeOfInt();    //4 on x64, pass
		 int sizeOfXY = MyNativeMethods.GetSizeXY();          //8 on x64, pass
		 int sizeOfOverlapAB = MyNativeMethods.GetSizeOAB();  //4 on x64, pass
		 //---
		 //3. send data XY
		 unsafe
		 {

                 //TEST CASE1: => PASS
		 XY myXY = new XY();
		myXY.x = 10;
		myXY.y = 20;
		XY ret_xy = MyNativeMethods.Send_XY(&myXY);
                //
                Debug.Assert(myXY.x == ret_xy.x); //pass
                Debug.Assert(myXY.y == ret_xy.y); //pass

                //---
                //TEST CASE2: => ERR
                OverlapAB oab = new OverlapAB();
                oab.a = 1;
                OverlapAB ret_oab = MyNativeMethods.Send_OAB(&oab);
                //
                Debug.Assert(ret_oab.a == oab.a); //err
                Debug.Assert(ret_oab.b == oab.b); //err
                //---
		}
	    }
	}
     }
```

(link to gist https://gist.github.com/enginekit/8fbf83c698e03e254e7aae3052ec92a5)

from above ...

**OverlapAB is a union value on native side. 
when I return it from native side I got an error value on .netcore side.**

**Comment by jkotas** [comment] 2017-05-30 23:38
This is duplicate of https://github.com/dotnet/coreclr/issues/4307

**Comment by enginekit** [comment] 2017-05-30 23:58
@jkotas ,Thank you,
I spent many hours for this bug :(

---

from  https://github.com/dotnet/coreclr/issues/4307#issuecomment-209143643
and https://github.com/dotnet/coreclr/issues/4307#issuecomment-209780419

for this time 
this mean that I must change my code (native part) 
by not send the union value back.

---

@jkotas ,

Should I left this issue open  for others ?

If you think It should be close => then please close this  

:)

**Comment by jkotas** [comment] 2017-05-31 00:15
> I spent many hours for this bug :(

Sorry about that. 

We do not keep duplicate issues open. I am going to close this one.

**Closed by jkotas** 2017-05-31 00:15 UTC
Labels: area-Interop
