### ISSUE TITLE
TimeZoneNotFoundException not exposed, yet thrown by public api

### ISSUE THREAD

**Issue by stevenscreek** [dotnet/coreclr#5226] opened 2016-05-25 21:15 UTC
TimeZoneInfo.FindSystemTimeZoneById throws TimeZoneNotFoundException in several cases.  However, as TimeZoneNotFoundException is not an exposed api point, this leaves callers without many alternatives other than simply catching Exception.

**Comment by adityamandaleeka** [comment] 2016-05-25 21:52
@eerhardt

**Comment by eerhardt** [comment] 2016-05-25 21:54
Looks like a dupe of https://github.com/dotnet/corefx/issues/7552

**Comment by adityamandaleeka** [comment] 2016-05-25 22:51
Yup. @stevenscreek thanks for reporting this. Since it's already being tracked in https://github.com/dotnet/corefx/issues/7552, I'm going to close this issue.

**Closed by adityamandaleeka** 2016-05-25 22:51 UTC

**Comment by stevenscreek** [comment] 2016-05-25 22:53
Thanks!  I looked here for dups, but next time I look in corefx too.

**Comment by eerhardt** [comment] 2016-05-26 02:04
> Thanks! I looked here for dups, but next time I'll look in corefx too.

I agree it is confusing.  Types that are in mscorlib kind of live in both repos.  The public contract is in corefx, and the implementation is in coreclr.

No worries about the dupe. Hopefully this bug gets fixed soon and people won't hit this anymore. :smile:
