### ISSUE TITLE
[RedHat.6.Amd64] Heap contamination detected

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#23580] opened 2019-03-29 23:47 UTC
I was trying to enable RedHat.6.Amd64.Open running in public CI and saw these failures with four tracing tests

**tracing.eventsource.eventsourcetrace**
```    tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_._eventsourcetrace_eventsourcetrace_eventsourcetrace_sh [FAIL]
      
      Assert failure(PID 2070 [0x00000816], Thread: 2070 [0x0816]): !"Heap contamination detected! HeapFree was called on a heap other than the one that memory was allocated from.\n" "Possible cause: you used new (executable) to allocate the memory, but didn't use DeleteExecutable() to free it."
          File: /__w/1/s/src/vm/hosting.cpp Line: 273
          Image: /home/helixbot/work/fb09a8e3-ecd2-450b-b501-a2bbf100bb83/Payload/corerun
      
      /home/helixbot/work/fb09a8e3-ecd2-450b-b501-a2bbf100bb83/Work/49b75c40-16b9-42b4-a418-6ca5ff4c8e64/Exec/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh: line 259:  2070 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      /n/nReturn code:      1/nRaw output file:      /home/helixbot/work/fb09a8e3-ecd2-450b-b501-a2bbf100bb83/Work/49b75c40-16b9-42b4-a418-6ca5ff4c8e64/Exec/Reports/tracing.eventsource/eventsourcetrace/eventsourcetrace/eventsourcetrace.output.txt/nRaw output:/nBEGIN EXECUTION
      /home/helixbot/work/fb09a8e3-ecd2-450b-b501-a2bbf100bb83/Payload/corerun eventsourcetrace.exe ''
      	Start: Enable tracing.
      	End: Enable tracing.
      
      	Start: Messaging.
      	End: Messaging.
      
      	Start: Disable tracing.
      	End: Disable tracing.
      
      	Start: Processing events from file.
      	SimpleEventSource
      	Microsoft-DotNETCore-EventPipe
      	Microsoft-Windows-DotNETRuntimeRundown
      	End: Processing events from file.
      
      	Processed 10000 events from EventSource
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      /nTo run the test:/n> set CORE_ROOT=/home/helixbot/work/fb09a8e3-ecd2-450b-b501-a2bbf100bb83/Payload/n> /home/helixbot/work/fb09a8e3-ecd2-450b-b501-a2bbf100bb83/Work/49b75c40-16b9-42b4-a418-6ca5ff4c8e64/Exec/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh/n
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/bin/tests/Linux.x64.Checked/TestWrappers/tracing.eventsource/tracing.eventsource.XUnitWrapper.cs(109,0): at tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_._eventsourcetrace_eventsourcetrace_eventsourcetrace_sh()
```

**tracing.tracevalidation.jittingstarted**
```
tracing_tracevalidation._jittingstarted_JittingStarted_JittingStarted_._jittingstarted_JittingStarted_JittingStarted_sh [FAIL]
      
      Assert failure(PID 4487 [0x00001187], Thread: 4502 [0x1196]): !"Heap contamination detected! HeapFree was called on a heap other than the one that memory was allocated from.\n" "Possible cause: you used new (executable) to allocate the memory, but didn't use DeleteExecutable() to free it."
          File: /__w/1/s/src/vm/hosting.cpp Line: 273
          Image: /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/corerun
      
      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/jittingstarted/JittingStarted/JittingStarted.sh: line 266:  4487 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      /n/nReturn code:      1/nRaw output file:      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/Reports/tracing.tracevalidation/jittingstarted/JittingStarted/JittingStarted.output.txt/nRaw output:/nBEGIN EXECUTION
      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/corerun JittingStarted.exe ''
      	Start: Enable tracing.
      	End: Enable tracing.
      
      	Start: Generate some events.
      	End: Generate some events.
      
      	Start: Disable tracing.
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      /nTo run the test:/n> set CORE_ROOT=/home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/n> /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/jittingstarted/JittingStarted/JittingStarted.sh/n
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/bin/tests/Linux.x64.Checked/TestWrappers/tracing.tracevalidation/tracing.tracevalidation.XUnitWrapper.cs(109,0): at tracing_tracevalidation._jittingstarted_JittingStarted_JittingStarted_._jittingstarted_JittingStarted_JittingStarted_sh()
```

**tracing.tracevalidation.rundown**
```
    tracing_tracevalidation._rundown_rundown_rundown_._rundown_rundown_rundown_sh [FAIL]
      
      Assert failure(PID 4480 [0x00001180], Thread: 4500 [0x1194]): !"Heap contamination detected! HeapFree was called on a heap other than the one that memory was allocated from.\n" "Possible cause: you used new (executable) to allocate the memory, but didn't use DeleteExecutable() to free it."
          File: /__w/1/s/src/vm/hosting.cpp Line: 273
          Image: /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/corerun
      
      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/rundown/rundown/rundown.sh: line 266:  4480 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      /n/nReturn code:      1/nRaw output file:      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/Reports/tracing.tracevalidation/rundown/rundown/rundown.output.txt/nRaw output:/nBEGIN EXECUTION
      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/corerun rundown.exe ''
      	Start: Enable tracing.
      	End: Enable tracing.
      
      	Start: Disable tracing.
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      /nTo run the test:/n> set CORE_ROOT=/home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/n> /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/rundown/rundown/rundown.sh/n
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/bin/tests/Linux.x64.Checked/TestWrappers/tracing.tracevalidation/tracing.tracevalidation.XUnitWrapper.cs(179,0): at tracing_tracevalidation._rundown_rundown_rundown_._rundown_rundown_rundown_sh()
```
**tracing.tracevalidation.tracelogging**
```
tracing_tracevalidation._tracelogging_tracelogging_tracelogging_._tracelogging_tracelogging_tracelogging_sh [FAIL]
      
      Assert failure(PID 4510 [0x0000119e], Thread: 4510 [0x119e]): !"Heap contamination detected! HeapFree was called on a heap other than the one that memory was allocated from.\n" "Possible cause: you used new (executable) to allocate the memory, but didn't use DeleteExecutable() to free it."
          File: /__w/1/s/src/vm/hosting.cpp Line: 273
          Image: /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/corerun
      
      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/tracelogging/tracelogging/tracelogging.sh: line 252:  4510 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      /n/nReturn code:      1/nRaw output file:      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/Reports/tracing.tracevalidation/tracelogging/tracelogging/tracelogging.output.txt/nRaw output:/nBEGIN EXECUTION
      /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/corerun tracelogging.exe ''
      Verifying Event: <Event MSec=    "95.9180" PID="4510" PName="Process(4510)" TID="4510" EventName="EmptyEvent" ProviderName="ManifestEventSource"/>
      Verifying Event: <Event MSec=    "99.1920" PID="4510" PName="Process(4510)" TID="4510" EventName="EmptyEvent" ProviderName="TraceLoggingEventSource"/>
      Verifying Event: <Event MSec=    "99.7850" PID="4510" PName="Process(4510)" TID="4510" EventName="IntStringEvent" ProviderName="ManifestEventSource" i="42" s="Hello World!"/>
      Verifying Event: <Event MSec=   "108.9810" PID="4510" PName="Process(4510)" TID="4510" EventName="IntStringEvent" ProviderName="TraceLoggingEventSource" i="42" s="Hello World!"/>
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      /nTo run the test:/n> set CORE_ROOT=/home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Payload/n> /home/helixbot/work/8cfdb446-1d72-4688-8925-656c33a90304/Work/9b6dbcf4-e56a-4b80-b9a0-ef37721af0ed/Exec/tracelogging/tracelogging/tracelogging.sh/n
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/bin/tests/Linux.x64.Checked/TestWrappers/tracing.tracevalidation/tracing.tracevalidation.XUnitWrapper.cs(249,0): at tracing_tracevalidation._tracelogging_tracelogging_tracelogging_._tracelogging_tracelogging_tracelogging_sh()
```

**Comment by tommcdon** [comment] 2019-04-01 16:59
@jorive can you confirm that https://github.com/dotnet/coreclr/pull/23448 should address this issue?

**Comment by jorive** [comment] 2019-04-01 23:46
@tommcdon Yes, I can confirm I fixed it with my PR.

**Comment by jashook** [comment] 2019-11-21 22:38
This issue looks like it was never actually resolved.

**Comment by jashook** [comment] 2019-11-21 22:41
https://github.com/dotnet/runtime/issues/168 has more information.

**Comment by jorive** [comment] 2019-11-21 23:05
@jashook The issue you are mentioning might be similar, but this issue was resolved.

**Comment by jashook** [comment] 2019-11-22 00:22
Closing based on feedback. Will still look into if these issues are the same.

**Closed by jashook** 2019-11-22 00:22 UTC
Labels: area-Tracing
