### ISSUE TITLE
Are we there yet?

### ISSUE THREAD

**Issue by OtherCrashOverride** [dotnet/coreclr#1264] opened 2015-07-20 16:17 UTC
This is a plea from a "community" member for someone to please answer:
1) Where are we at?
Is CoreCLR an alpha, a beta, a RC, is it released and nobody told us?  What information sources should we be following to be 'in the know'? 

2) Where are we going?
What still needs to be done? What are the goals and milestones left to accomplish?

3) When will we get there?
I held off asking this question figuring it was tied to secret schedules such as Win10 or Visual Studio 2015 release dates.  Both are public now.  Is there a reason we are not being told anything about CoreCLR?  Is this really a "when its released!" project?

It would be nice to have some kind of scheduled project updates:  Once a month? Every two weeks?

This is not some kids hobby project.  I find it hard to believe a major corporation operates in the same "in the dark" level the "community" is kept in.

This post is not a troll. Its not a flame. Its not meant to be directed personally at anybody.  Its not meant to hurt anyone's feelings.  Its about companies and individuals trying to make informed business decisions.

**Comment by sharwell** [comment] 2015-07-20 21:37
I'd like to see something regular like dotnet/roslyn#3927, which keeps the community informed regarding the short- and long-term planning of this project. I also think dates like feature freeze (or stabilization, or whatever Microsoft calls it) should be made available as early as possible since they affect bug reports and feature requests relating to localization and other matters.

**Comment by MgSam** [comment] 2015-07-20 21:39
:+1: Agree- communication needs to be better here. We can't even consider relying on this until it's RTM and there is no information on when that might be.

**Comment by masonwheeler** [comment] 2015-07-20 21:42
Agreed. Just for starters, the readme.md for the CoreCLR was last updated on June 10, well over a month ago.  Since then, we've had hundreds of commits including a few dozen pull requests added to the project, but no official indication that anything has changed or progressed in the "big picture."

**Comment by OtherCrashOverride** [comment] 2015-07-21 02:39
Here is a good example:

https://github.com/aspnet/Home/wiki/Roadmap

> we think it's important to be as open and transparent as possible about our plans so that our users can have the right expectations and create their plans accordingly.

**Comment by jkotas** [comment] 2015-07-21 04:18
The ASP.NET vNext is the ship vehicle for cross-plat https://github.com/dotnet/coreclr and https://github.com/dotnet/corefx for the current release, so the same overall schedule applies.

@sergiy-k Could you please tag issues that we believe are must-fix for the current release?

**Comment by jkotas** [comment] 2015-07-21 04:20
cc @richlander

**Comment by davidfowl** [comment] 2015-07-21 05:23
The ASP.NET 5 roadmap has been published here https://github.com/aspnet/Home/wiki/Roadmap

**Comment by shahid-pk** [comment] 2015-07-21 05:26
@davidfowl love it. Thanks :+1:

**Comment by OtherCrashOverride** [comment] 2015-07-21 05:28
Ok, we definitely have a communication issue.

> OtherCrashOverride commented 3 hours ago 

> Here is a good example:

>https://github.com/aspnet/Home/wiki/Roadmap

**Comment by shahid-pk** [comment] 2015-07-21 05:31
@OtherCrashOverride well that should be the roadmap for coreclr too. because asp.net 5 xplat will need it. But yea it needs documentation not everyone comes here daily like a few of us.

**Comment by kangaroo** [comment] 2015-07-21 07:13
Tag @richlander *cough* roadmap *cough*

**Comment by jakesays** [comment] 2015-07-21 23:50
Will coreclr always be tied to asp.net, or is this a one time thing? I ask because I would really prefer coreclr be separate from asp.net. (I have a sneaky suspicion asp.net is trying to take over the world.)

**Comment by davidfowl** [comment] 2015-07-22 00:47
It's tied currently because we're shipping an RC in November and the coreclr is a very large dependency. There's is currently no other short term shipping vehicle. We're not taking over the world just the server stack 😀

**Comment by jakesays** [comment] 2015-07-22 15:40
To some the server stack *is* our world (yes, we have no life.)

**Comment by davidfowl** [comment] 2015-07-22 18:03
Coreclr will always be open so it will absolutely be possible to build your own stack. But ASP.NET is the only server that Microsoft is shipping is .NET Core.

**Comment by OtherCrashOverride** [comment] 2015-07-24 21:52
So is the ARM port working? It seems to be implied by Microsoft that it is:
https://twitter.com/dotnet/status/624685337026019328

**Comment by masonwheeler** [comment] 2015-07-24 22:07
@OtherCrashOverride That was a partial port.  It's notably missing some important unwinding and JIT-related stuff, but it contains a good deal of imporant ARM32 functionality.

**Comment by borgdylan** [comment] 2015-07-25 10:36
Is the x86 port moving along? There is a lot of x64 stuff going on which would share a lot with x86 so I don't see why both both architectures can't be developed together.

**Comment by benpye** [comment] 2015-07-25 15:57
@borgdylan As I understand it there is no movement on the x86 front, the changes I have made for ARM will have some impact as the build scripts don't just assume everything is AMD64 now, and if I recall correctly I fixed some 64 bit assumptions. As with ARM I'm not sure on the state of RyuJIT on x86 though it looks like there is a high amount of code shared with AMD64 so it might work, more than ARM at any rate. The legacy JIT would work for bring up too, though as with the ARM port I doubt the JIT team would want to support it.

**Comment by borgdylan** [comment] 2015-07-25 17:29
Someone on the team had told me that the priority ordering was x64,x86,ARM. Yet they released the Win10 ARM port before x64 was even fully ready.

**Comment by benpye** [comment] 2015-07-25 17:31
The ARM Win 10 version uses jit32, as does the current x86 coreclr (used for core powershell and the like). Different JIT to this CoreCLR.

**Comment by borgdylan** [comment] 2015-07-25 17:35
I have tried to enable the 32bit Linux build of coreclr but I cannot make it work. The CMAKE files are complicated plus there are a lot of errors in the C/C++ files with regards to the PAL.

**Comment by benpye** [comment] 2015-07-25 17:42
You will need to port the PAL for x86, I think you may need to modify the assembly files as I think they make AMD64 assumptions currently, it should be similar for x86 though as they are similar platforms. For the other projects you would need to add another platform in the cmake files for x86, and include the x86 specific files there, in a lot of cases there are "xarch" files which are shared between AMD64 and x86. It won't necessarily be trivial to port to x86. I am curious as to what you have that requires x86 as I would of thought most hardware would be AMD64 anyway?

**Comment by borgdylan** [comment] 2015-07-25 18:02
Linux x86 is still more stable than amd64. I also wanted to try out an Intel Edison which is 32bit only by design. Also, 32 bit Linux with PAE on wastes less RAM as virtual memory pointers are 32bit with teh kernel keeping 36bit pointers to access up to 64GB of RAM (I only install 8GB).

**Comment by borgdylan** [comment] 2015-07-25 19:03
Porting of stuff like the JIT helpers is rather challenging...some registers are not accessible like R13 etc...
```
//
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
//
// ===========================================================================
// File: JITHelpers.CPP
// ===========================================================================

// This contains JITinterface routines that are specific to the
// AMD64 platform. They are modeled after the X86 specific routines
// found in JIThelp.asm


#include "common.h"
#include "jitinterface.h"
#include "eeconfig.h"
#include "excep.h"
#include "ecall.h"
#include "asmconstants.h"

EXTERN_C void JIT_TailCallHelperStub_ReturnAddress();

TailCallFrame * TailCallFrame::GetFrameFromContext(CONTEXT * pContext)
{
    _ASSERTE((void*)::GetIP(pContext) == JIT_TailCallHelperStub_ReturnAddress);
    return (TailCallFrame*)(pContext->R13 + sizeof(GSCookie));
}

// Assuming pContext is a plain generic call-site, adjust it to look like
// it called into TailCallHelperStub, and is at the point of the call.
TailCallFrame * TailCallFrame::AdjustContextForTailCallHelperStub(CONTEXT * pContext, size_t cbNewArgArea, Thread * pThread)
{
    TailCallFrame * pNewFrame = (TailCallFrame *)(GetSP(pContext) - sizeof(TailCallFrame));

    // R13 is the frame pointer (for popping the stack)
    pContext->R13 = (size_t)pNewFrame - sizeof(GSCookie);
    // R12 is the previous stack pointer, so we can determine if a return buffer from the
    // immediate caller (and thus being discarded via the tail call), or someplace else
    pContext->R12 = GetSP(pContext);
    // for the args and pushed return address of the 'call'
    SetSP(pContext, (size_t)pNewFrame - (cbNewArgArea + sizeof(void*) + sizeof(GSCookie)));

    // For popping the Frame, store the Thread
    pContext->R14 = (DWORD_PTR)pThread;
    // And the current head/top
    pContext->R15 = (DWORD_PTR)pThread->GetFrame(); // m_Next

    return (TailCallFrame *) pNewFrame;
}
```

**Comment by benpye** [comment] 2015-07-25 19:10
You needn't port those, you should be using the files in the i386 directory as they are already for the x86 target. You will need to port the .asm files to GNU assembler syntax.

**Comment by borgdylan** [comment] 2015-07-25 19:16
I see. I thought everything needed porting if the i386 directory did not have it.

**Comment by benpye** [comment] 2015-07-25 19:18
No some architectures have slightly different files, but they generally provide the same methods. You also do not need to worry about all the functions in the assembly files initially as quite a lot is behind features that we do not use with CoreCLR like COM interop.

**Comment by borgdylan** [comment] 2015-07-25 19:33
In the assembly code I did find the use of r8 which is not part of the x86 abi. The easy part is moving to the 32bit variant of the 64bit registers.

**Comment by benpye** [comment] 2015-07-25 19:35
In which file are you seeing that? The i386 files in the PAL should probably be under amd64, but it isn't too hard to rewrite that.

**Comment by borgdylan** [comment] 2015-07-25 19:48
externalmethodfixupthunk.S and getState.S

**Comment by benpye** [comment] 2015-07-25 19:58
Again, those are the AMD64 files, it's easier to translate these files https://github.com/dotnet/coreclr/tree/master/src/vm/i386 than to port the AMD64 files.

**Comment by borgdylan** [comment] 2015-07-25 20:09
So unixasmhelpers.S is the asmhelpers.asm fiel translated into GNU as format?

**Comment by benpye** [comment] 2015-07-25 20:12
Yeah, the .S files are GNU assembler format, and the .asm format are whatever the Microsoft assembler uses (arch specific it seems). The AMD64 files may be useful for reference in some areas.

**Comment by borgdylan** [comment] 2015-07-25 20:41
There are differences between the translated amd64 file and the original (different functions defined). I cannot find one of the unwinding functions for x86 in the original MASM32 files. I can conclude that the 32bit Linux port cannot be done by the community at this time.

**Comment by jakesays** [comment] 2015-07-25 23:15
@borgdylan I'm curious - why would the lack of that function preclude one from doing a 32bit port?

**Comment by kangaroo** [comment] 2015-07-26 00:00
@borgdylan I'm not sure why you'd conclude that?  I've reverse engineered several missing bits on the aarch64 side in a black box fashion.  Sure its work, but its certainly not impossible.

**Comment by jakesays** [comment] 2015-07-26 00:03
Yeah that's what I was thinking.

**Comment by jkotas** [comment] 2015-07-26 01:31
CLR worked on x86 unix systems before (Rotor and Silverlight). it should make the Linux x86 port easier than the Linux arm port.

The old Rotor code may be used as reference when in doubt. E.g. Here is what the translation of the x86 assembly files looked like in Rotor: https://github.com/lewischeng-ms/sscli/blob/master/clr/src/vm/i386/asmhelpers.asm vs. https://github.com/lewischeng-ms/sscli/blob/master/clr/src/vm/i386/asmhelpers.s

**Comment by jakesays** [comment] 2015-07-26 01:44
@jkotas how similar are rotor and coreclr?

**Comment by jkotas** [comment] 2015-07-26 01:54
Both are based on same codebase, but there is 10 years of active development between the two. A lot of things is very different, a lot of things is almost the same.

**Comment by borgdylan** [comment] 2015-07-26 07:22
@jakesays I concluded that as with missing information I cannot just make up a stream of instructions. Even if I do know a bit of x86 assembly, I have only done basic maths and function writing with it.

**Comment by borgdylan** [comment] 2015-07-26 07:44
@jkotas Is it the case that JIT64/RyuJit use helpers that JIT32 does not use and vice versa?

**Comment by jkotas** [comment] 2015-07-26 13:55
`StartUnwindingNativeFrames` was added in this commit https://github.com/dotnet/coreclr/commit/f8f42933a46499aab91207385fca088185075a01. It is implementation of native exception handling for Linux amd64.

You should not worry about assembly helpers that you do not know yet what to do about - just make  dummy implementation with `int3` to make things compile. Once you have things running and start hitting the unimplemented assembly helpers, go back and implement them.

**Comment by borgdylan** [comment] 2015-07-26 15:22
```int3```? By that you mean an interrupt (which would be int 0x80) or taking three integers?

**Comment by masonwheeler** [comment] 2015-07-26 15:27
`int 3` is an interrupt that raises a breakpoint.  It's very useful for debugging in certain situations.

**Comment by ayende** [comment] 2015-07-26 15:30
It is the original Debugger.Break() :-)

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by jakesays** [comment] 2015-07-26 19:07
@borgdylan Ok so what you probably should have said is that you cannot do the port. It's a big community full of very smart people.

**Comment by borgdylan** [comment] 2015-07-26 20:58
I cannot do it alone for sure. My knowledge assembly only extends to the FPU and some SSE. I might fill the void of no RyuJit32 with a 32bit vector library that uses SSE.

**Comment by richlander** [comment] 2015-07-26 21:06
Thanks for starting this thread. Sorry for being (a) so late on replying to it, and (b) leaving you in a situation roadmap-wise that you needed to post it. I totally get that your post is not a flame or anything negative. No worries there.

Both the ASP.NET and Roslyn teams have been doing a better job than us roadmap wise. You are right. We've been discussing that and we are going to fix it, very soon.

You are also correct that multiple releases are now out of the way, such as UWP and .NET 4.6. There actually wasn't ever anything 'secret' at play that caused us to not publish a roadmap. Those projects were, however, very distracting and that aspect has now diminished significantly. It's a poor excuse, but intended to provide some context.

> This is not some kids hobby project.

I love this line. T-shirts on the way ;) You are very much correct. @kangaroo has been pushing on me and others on this front for a while. Thanks for adding to that.

**Comment by benpye** [comment] 2015-07-26 21:20
Thanks @richlander for the update, it's good to know that we are going to know where this is going in the future. Also two more GitHub related questions than anything else, some people seem to be in the dotnet group, and those seem to get a "2 - In progress" tag on PRs, cosmetic but it's unclear what this means since PRs for those not in the dotnet group do not get the tag. Additionally, are issues still being assigned to the person to ask for questions or has that changed? I ask since most issues have nobody assigned.

**Comment by richlander** [comment] 2015-07-26 21:33
That's a good issue. I know about those tags, but I don't know why they are setup that way.

For starters, anyone can get added to one of the official dotnet foundation teams. the dotnet-community team is the one we use for that. FYI: It's not solely for external folks. We put arbitrary MSFT people there, too. Just tell me if you want to get added. Mail me (rlander@msft) or DM me on twitter (@runfaster2000).

The CoreFX team assigns issues in the way you mention. I don't personally like that setup. The other option, which is the one CoreCLR uses, is to not assign someone until an owner has been assigned.

**Comment by jakesays** [comment] 2015-07-26 21:56
@richlander Not too sure about this not being a kids hobby project. I feel like a kid in a candy store every time I jump in to the code :)

**Comment by richlander** [comment] 2015-07-27 01:44
@jakesays +1

**Comment by richlander** [comment] 2015-10-30 15:48
I never posted the link to the roadmap doc I put together: https://github.com/dotnet/core/blob/master/roadmap.md.

Major take away is that we're working towards and RC for November and then an RTM version in the first quarter of next year.

The big thing that we need to improve on is our API backlog. We need to add many APIs. So far, those have been added in a "just in time" fashion. We come upon a need for an API and then we add it. We now have a couple people - @martinwoodward and @bleroy - doing more long-term planning on which APIs and NuGet packages we need to support first. I'd love them to publish their lists.

I'm not sure that the runtime itself needs a ton more features to ship. I suspect that perf and reliability will be the main focuses. Debugging, too.

We have a very poor story for using CoreCLR when you are not using DNX. We hadn't forgotten about that. We know we need to address that before RTM.

Distribution is another issue. We've been talking about native package managers. This is another story that we'll need to solve between RC and RTM. NuGet package versioning is another issue that is somewhat related. It's packages!

There has been a lot of focus finishing up the cross-plat implementation for CoreFX. That's coming to a very solid milestone (yeah!) and will leave more time for taking care of more of the experience fundamentals.

**Comment by benpye** [comment] 2015-10-30 15:53
What's the story with other architectures, notably, x86 and ARM32 are on
the roadmap but are these Windows only for RC1 and RTM? As much as I'd love
to drive the ARM32 effort further I wonder where this ultimately fits in.

**Comment by jkotas** [comment] 2016-11-18 03:54
Tracked by number of more concrete issues.

**Closed by jkotas** 2016-11-18 03:54 UTC
Labels: documentation
