### ISSUE TITLE
segmentation fault in ARM emulator run

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#7729] opened 2016-10-19 20:15 UTC
```15:25:31                /bindings/tmp/arm32_ci_temp/coreclr/Windows_NT.x64.Debug/Tests/coreoverlay/corerun VectorReturn_ro.exe
15:25:31 
               ./VectorReturn_ro.sh: line 121: 19804 Segmentation fault      (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" VectorReturn_ro.exe $CLRTestExecutionArguments
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_emulator_cross_debug_ubuntu_prtest/1088/console

**Comment by jkotas** [comment] 2016-10-19 20:20
Duplicate of https://github.com/dotnet/coreclr/issues/6298

**Closed by jkotas** 2016-10-19 20:20 UTC
Labels: bug
