### ISSUE TITLE
StringBuilder.Append can fail mid-way

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#4509] opened 2016-04-22 13:44 UTC
static void StringBuilderTest3()
        {
            var sb = new StringBuilder(0, maxCapacity: 2);

            sb.Append(new string('x', 2));
            sb.Length--;

            try
            {
                sb.Append(new string('x', 2));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex); //Expected.
            }

            Console.WriteLine(sb.ToString()); //Prints "xx", should print "x".
        }

`Append` can fail mid-way and append a part of the argument.

**Comment by AlexGhiondea** [comment] 2016-10-25 17:31
I believe this is a duplicate of https://github.com/dotnet/coreclr/issues/4514. The root cause is that the `StringBuilder` first starts filling out the existing space in the current chunk before doing checks to see if it has enough room to write the rest.

**Closed by AlexGhiondea** 2016-10-25 17:31 UTC
Labels: mscorlib
