### ISSUE TITLE
Unhandled exception in 1.1.0

### ISSUE THREAD

**Issue by ChrisWarner-Sage** [dotnet/coreclr#8477] opened 2016-12-06 15:29 UTC
We have come across an issue that only presents itself in a particular situation in 1.1.0

The issue occurs when a redis distributed cache is configured, session is enabled and an x509 certificate store is opened. **This only happens when SSL is enabled for the redis cache connection.**

This issue does not occur in 1.0.1.

Each of the three parts can be enabled in isolation without issue.

The error that is raised is an unhandled exception within System.Private.CoreLib.ni.dll
_An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll_

I have replicated this issue in a sample application and submitted to a Github repo. 

https://github.com/ChrisWarner-Sage/ASPNETCORETEST

I have created two branches called:

1.0Working - this is a working implementation in 1.0.1

https://github.com/ChrisWarner-Sage/ASPNETCORETEST/tree/1.0Working

1.1NotWorking - this is the same application converted to 1.1.0

https://github.com/ChrisWarner-Sage/ASPNETCORETEST/tree/1.1NotWorking

Both of these applications are simple .NET MVC applications.

To replicate from scratch:

- Create a new MVC application for .net core in visual studio.

- Change the following lines to target the 1.1 framework
    - https://github.com/ChrisWarner-Sage/ASPNETCORETEST/blob/1.1NotWorking/global.json#L4
    - https://github.com/ChrisWarner-Sage/ASPNETCORETEST/blob/1.1NotWorking/src/AspNetCoreCertError/project.json#L4
    - https://github.com/ChrisWarner-Sage/ASPNETCORETEST/blob/1.1NotWorking/src/AspNetCoreCertError/project.json#L35

- Update the packages via the Nuget Package manager.

- Configure the RedisDistributedCache

    - https://github.com/ChrisWarner-Sage/ASPNETCORETEST/blob/1.1NotWorking/src/AspNetCoreCertError/Startup.cs#L30-L34

(This test configuration does not contain a credential for security, however the resulting exception will be caught and handled appropriately by the cache provider in the working example.)

- Configure the Session

    - https://github.com/ChrisWarner-Sage/ASPNETCORETEST/blob/1.1NotWorking/src/AspNetCoreCertError/Startup.cs#L36-L42

- Enable session for the application

     - https://github.com/ChrisWarner-Sage/ASPNETCORETEST/blob/1.1NotWorking/src/AspNetCoreCertError/Startup.cs#L64

- Within a controller action, open a valid x509 certificate store and search for a certificate.

    - https://github.com/ChrisWarner-Sage/ASPNETCORETEST/blob/1.1NotWorking/src/AspNetCoreCertError/Controllers/HomeController.cs#L14-L18

Any advice regarding this would be great as we are unable to upgrade our .NET core applications to 1.1.0 currently.

**Comment by janvorli** [comment] 2016-12-06 15:46
@bartonjs do you know who would be the right one to look into this issue on Windows?

**Comment by bartonjs** [comment] 2016-12-06 16:00
This is a duplicate of #8148.  That issue links to an issue in corefx that has a diagnostic step which has a benefit of being a temporary workaround.

**Closed by bartonjs** 2016-12-06 16:00 UTC
