### ISSUE TITLE
StringBuilder Capacity should remain less or equal to MaxCapacity when it gets full

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/coreclr#16977] opened 2018-03-15 23:24 UTC
When creating StringBuilder with a certain maxCapacity larger than capacity:

```
// We don't expect Capacity to become larger than MaxCapacity. 

var sb = new StringBuilder(capacity: 17, maxCapacity: 18);

sb.Append(new string('a', sb.MaxCapacity)); 
          // Capacity becomes 17 * 2 = 34

Assert.InRange(sb.Capacity, 0, sb.MaxCapacity); 
          // expected between (0 and 18), actual 34
```

Another side effect to this bug:
```
// We don't expect to be able to get Length to become larger than MaxCapacity. 

var sb = new StringBuilder(capacity: 17, maxCapacity: 18);

sb.Append(new string('a', sb.MaxCapacity)); 
          // Capacity becomes 17 * 2 = 34

sb.Append("a"); 
          // Does not throw

Assert.InRange(sb.Length, 0, sb.MaxCapacity); // fails
          // expected between (0 and 18), actual 19
```

We get correct behavior when capacity and maxCapacity are the same during initialization:
```var sb = new StringBuilder(capacity: 15, maxCapacity: 15);```

This issue happens in the ExpandByABlock method of StringBuilder and when we are trying to add another chunk to the StringBuilder

cc: @danmosemsft @jkotas

**Comment by maryamariyan** [comment] 2018-03-16 00:01
Another example:

```
var sb = new StringBuilder(capacity: 20, maxCapacity: 39);
sb.Append(new string('a', 21)); 
          // Capacity becomes 20 * 2 = 40

sb.Append(new string('a', 18)); 
          // Won't throw here but it would complain if we added string with length 19 or larger.

Assert.InRange(sb.Capacity, 0, sb.MaxCapacity); // fails. 
          // Range:  (0 - 39)
          // Actual: 40
```

**Comment by jkotas** [comment] 2018-03-16 01:18
Duplicate of https://github.com/dotnet/coreclr/issues/15061

**Closed** 2018-03-16 01:21 UTC
Labels: area-System.Runtime, bug
