### ISSUE TITLE
ILDASM - Wrong exit code

### ISSUE THREAD

**Issue by JoseTiagoCarvalho** [dotnet/coreclr#18885] opened 2018-07-12 14:40 UTC
I'm using ILDASM to inspect all files in a folder (project build output), and in somes cases i have configuration/text files. In those edge cases i caught a bug, although i received an exit code 0 the process output was "Image is either too small or contains an invalid byte offset or count.\n". According to the process output i was expecting to receive an exit 1.

I'm migrating to this version of ILDASM (before i was using https://docs.microsoft.com/en-us/dotnet/framework/tools/ildasm-exe-il-disassembler) because i couldn't run in Docker container with mono.

**Comment by AaronRobinsonMSFT** [comment] 2018-07-12 16:34
@jkotas What are your thoughts on changing ILDASM to return a non-zero code when an issue was detected?

**Comment by AaronRobinsonMSFT** [comment] 2018-07-12 16:44
@JoseTiagoCarvalho Any way you could provide a simple repro? Is there a file you could point at that demonstrates this behavior?

**Comment by JoseTiagoCarvalho** [comment] 2018-07-12 17:06
I think it shouldn't return an Exit code 0 (Success code) when it fails to execute the operation.

[CannotDisassemble.zip](https://github.com/dotnet/coreclr/files/2189520/CannotDisassemble.zip)

**Comment by AaronRobinsonMSFT** [comment] 2018-07-12 17:21
@JoseTiagoCarvalho Thanks! I have been able to reproduce this issue locally. It does seem like the .NET Framework version of this tool has the same behavior (i.e. returns 0). I think changing this is a reasonable suggestion. I do want to hear from @jkotas or perhaps @jeffschwMSFT on who the specific stakeholders for this tool are. If they are okay with it, I will change the behavior.

**Comment by AaronRobinsonMSFT** [comment] 2018-07-12 18:16
@RussKeldorph Any concerns with changing this behavior?

**Comment by RussKeldorph** [comment] 2018-07-12 18:40
@AaronRobinsonMSFT What should the definition of "success" be?  Like, how "valid" does a file have to be before ildasm returns success?  Can it have an invalid bit in a header somewhere and still have ildasm succeed?  What should happen when ildasm'ing a C++ all-native executable?  Right now I assume the border between failure and success is whether the file can be opened and read, which is easy to describe.  It sounds like we're proposing to move the definition of "success" to include constraints on the input file contents.  Those constraints should be clearly defined.

I should clarify that I'm not very familiar with this area.  If this is obviously just an inconsistency due to a missed case, then we should fix it.  If, however, there is clear, consistent design intent in ildasm, then I have some reservations.

**Comment by AaronRobinsonMSFT** [comment] 2018-07-12 23:09
@RussKeldorph all are good questions. Here is the current state. I can say that the coreclr version matches the Framework version with respect to return codes - so yay. Debugging through thus far it isn't obvious why the return value is `0` when the `/out=foo.il` flag is passed, but is `1` when it isn't passed.

@JoseTiagoCarvalho What platform are you running on and can you please provide all the arguments you are passing to the tool?

### FRAMEWORK
ildasm.exe ValidPE.exe & echo %ERRORLEVEL%
0

ildasm.exe ValidPE.exe /out=foo.il & echo %ERRORLEVEL%
0

ildasm.exe CannotDisassemble /out=foo.il & echo %ERRORLEVEL%
error : File 'CannotDisassemble' not found or not a PE file
0

ildasm.exe CannotDisassemble & echo %ERRORLEVEL%
1

### CORECLR
ildasm.exe ValidPE.exe & echo %ERRORLEVEL%
...
...
...
0

ildasm.exe ValidPE.exe /out=foo.il & echo %ERRORLEVEL%
0

ildasm.exe CannotDisassemble /out=foo.il & echo %ERRORLEVEL%

0

ildasm.exe CannotDisassemble & echo %ERRORLEVEL%

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.5.30319.0


1

**Comment by jkotas** [comment] 2018-07-13 06:48
> @jkotas What are your thoughts on changing ILDASM to return a non-zero code when an issue was detected?

It sounds fine to me.

> What should the definition of "success" be?

"success" = ildasm produced valid .il file, there were no image format errors.

**Comment by JoseTiagoCarvalho** [comment] 2018-07-13 09:36
@AaronRobinsonMSFT I'm running Ildasm from a c# app, running on platform x64 and framework netcoreapp2.0.

```csharp
var startInfo = new ProcessStartInfo("Tools/ildasm.exe", $@"/all /text ""{fileName}""") {
                WindowStyle = ProcessWindowStyle.Hidden,
               CreateNoWindow = true,
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true
};

using (var process = Process.Start(startInfo)) {
	var disassembleResult = process.StandardOutput.ReadToEnd();
	var errorOutput = process.StandardError.ReadToEnd();
	
	process.WaitForExit();
	
	var exitCode = process.ExitCode;
}
```

The command should be equivalent to `ildasm.exe /all /text CannotDisassemble & echo %ERRORLEVEL%`

[Tool.zip](https://github.com/dotnet/coreclr/files/2192115/Tool.zip)

**Comment by RussKeldorph** [comment] 2018-07-13 10:29
@AaronRobinsonMSFT Note that the DOS command
```
ildasm.exe ValidPE.exe & echo %ERRORLEVEL%
```
does not print the exit code of its `ildasm` invocation.  `%ERRORLEVEL%` is evaluated and replaced in the entire line (both sides of the `&`) before execution begins, so it prints the ambient exit code value prior to anything else on that line being executed.

When I run `ildasm` (both Core and .NETFx) I see the following:
```
>ildasm /text /all CannotDisassemble

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.6.1055.0
//  Copyright (c) Microsoft Corporation.  All rights reserved.

error : File 'CannotDisassemble' not found or not a PE file

>echo %errorlevel%
1
```

**Comment by JoseTiagoCarvalho** [comment] 2018-07-13 11:10
If i run the net Core version `dotnet ildasm CannotDisassemble & echo %errorlevel%`, i get the output:

```
Image is either too small or contains an invalid byte offset or count.
0
```

I have installed .NET Core 2.1 SDK (v2.1.302), and dotnet-ildasm version 0.9.2

**Comment by RussKeldorph** [comment] 2018-07-13 13:10
@JoseTiagoCarvalho `dotnet-ildasm` is not hosted at this repo.  I believe it comes from [here](https://www.nuget.org/packages/dotnet-ildasm/).  I suspect you want to close this issue and open a new one in that repo.

**Comment by JoseTiagoCarvalho** [comment] 2018-07-13 13:19
@RussKeldorph  Sorry, you are right. I though it was the same project site.

@AaronRobinsonMSFT @RussKeldorph Thanks for all the help anyway.

**Closed** 2018-07-13 13:20 UTC
Labels: area-CodeGen
