### ISSUE TITLE
[Linux] IdnMapping.GetAscii with already-decoded IDN throws ArgumentException on Linux 

### ISSUE THREAD

**Issue by snoozbuster** [dotnet/coreclr#12062] opened 2017-06-02 18:42 UTC
Compile and run the following `Program.cs` on a Unix system (I used the BSL subsystem, but I know it also happens with the official dotnet Docker image):

    using System;
    using System.Globalization;

    namespace ConsoleApplication
    {
        public class Program
        {
            public static void Main(string[] args)
            {
                Console.WriteLine(new IdnMapping().GetAscii("xn--6m8h26a.ws"));
            }
        }
    }

On Windows, this program outputs `xn--6m8h26a.ws`. On Linux, the following exception is thrown:

    Unhandled Exception: System.ArgumentException: Decoded string is not a valid IDN name.
    Parameter name: unicode
       at System.Globalization.IdnMapping.GetAsciiCore(Char* unicode, Int32 count)
       at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
       at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
       at System.Globalization.IdnMapping.GetAscii(String unicode)
       at ConsoleApplication.Program.Main(String[] args)

I have tried using .NET Core 1.0, 1.1.2, and 2.0 and the problem exists in all three versions.

**Comment by jkotas** [comment] 2017-06-02 19:21
cc @tarekgh

**Comment by tarekgh** [comment] 2017-06-02 21:50
I'll take a look

**Comment by tarekgh** [comment] 2017-06-03 00:44
@snoozbuster .Net core uses the underlying OS for the IDNA operations. in Linux case the ICU library will used. So it is expected you can find some differences when running on Windows than when running on Linux.

For the ACE label you reported **"xn--6m8h26a.ws"** it should be a valid ACE label and when convert it to Unicode it should be converted to the string **🏬🗺.ws** which is a couple of surrogate characters 0x1F3EC and 0x1F5FA in addition to ".ws"

Windows can convert this Unicode string to ASCII and vice versa. But ICU fail to do this conversion. 
When calling GetUnicode on **"xn--6m8h26a.ws"** ICU fail with the error 

```
UIDNA_ERROR_DISALLOWED A label or domain name contains disallowed characters.
```

If you call GetASCII on **"xn--6m8h26a.ws"** ICU fail with the error 

```
UIDNA_ERROR_INVALID_ACE_LABEL 

An ACE label does not contain a valid label string.

The label was successfully ACE (Punycode) decoded but the resulting string had severe validation errors. For example, it might contain characters that are not allowed in ACE labels, or it might not be normalized
```

This issue need to be reported to ICU. I'll try to do that and I am closing the issue here as the fix need to come from the OS.

Feel free to reply or reopen if you have more comments. Thanks.

**Closed by tarekgh** 2017-06-03 00:44 UTC
Labels: area-System.Globalization, bug, os-linux

**Comment by snoozbuster** [comment] 2017-06-03 02:27
@tarekgh Thank you for looking into it! If you manage to get a bug filed with ICU, can you link it here?

**Comment by ShawnSteele** [comment] 2017-06-05 18:27
This string is 🏬🗺.ws 

Strict IDNA2008 doesn't allow emoji characters like those, however UTS#46's compatibility processing mode for compatibility with IDNA2003 includes support for emoji.  That emoji support has been extended in the tables published by Unicode for new Unicode versions to include the newer emoji as well.

There is some debate within the standards bodies of whether or not the use of emoji is reasonable, so it is not surprising that different operating systems might handle these characters differently.

Microsoft has opted to be more permissive as many customers seem interested in using them.  Other platforms may make different choices.

**Comment by jefgen** [comment] 2017-06-05 20:19
It would seem that this is caused by using an older version of ICU. (It looks like Ubuntu 14.04 uses ICU version 52.1)

The second character, U+1F5FA "World Map" 🗺, was added in Unicode [version 7.0](http://www.unicode.org/charts/PDF/Unicode-7.0/U70-1F300.pdf) and ICU version 52.1 only supports Unicode version 6.3

I tested using ICU version **59.1**, and both functions (`uidna_nameToASCII` and `uidna_nameToUnicode`) *succeed* with the input string **"xn--6m8h26a.ws"**.

Neither method fails with the error(s) mentioned above, and both functions produce the expected output.

If possible, you might consider updating your version of ICU to 59.1 -- as that supports much more Emoji data and characters. 
(For more information, please visit the ICU site here: http://site.icu-project.org/download/59 )

**Comment by snoozbuster** [comment] 2017-06-05 20:35
I'm not sure that updating to version 59 is an option; it's unclear to me how deeply the library is ingrained into the kernel. We're using one of the official dotnet Docker images, it would be really cool if the team responsible for maintaining those would be able to look into updating these libraries on those images to help achieve parity with running dotnet core on Windows.

**Comment by tarekgh** [comment] 2017-06-05 20:42
CC @MichaelSimons to know if we can do something

**Comment by MichaelSimons** [comment] 2017-06-05 22:23
@tarekgh - The microsoft/dotnet Docker images contain the prereqs that are defined by the "shared framework".  For example 1.0.5 has the following dependencies - libc6 (>= 2.14), libcurl3 (>= 7.28.0), libgcc1 (>= 1:4.1.1), libgssapi-krb5-2 (>= 1.10+dfsg~), libicu52 (>= 52~m1-1~), liblldb-3.6, liblttng-ust0, libssl1.0.0 (>= 1.0.1), libstdc++6 (>= 4.8), libunwind8, libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4).  CoreCLR would need to take a dependency on a newer libICU version before we would update the official docker images.  Additionally I wonder if this would be considered a breaking change and would be skeptical of making this change outside of a major release.  @snoozbuster, I think your best option for now would be to install the newer version of libicu in your own Docker layer.

**Comment by tarekgh** [comment] 2017-06-05 22:40
@MichaelSimons coreclr define the minimum version of the ICU can work with and dynamically load it. so we cannot define the minimum dependency to ICU 59.1 because this would be very breaking change. In short, no change can be done in coreclr side. I thought we can have the docker image force latest ICU package but from what you said above I agree with you that @snoozbuster can just install the newer version of libicu in your own Docker layer

**Comment by snoozbuster** [comment] 2017-06-05 23:00
Given that .NET Core 2 is in preview right now, would it be unreasonable to suggest this dependency be updated for that release? it is a major release, after all.

In the meantime, we'll look into installing the newer version of ICU into our docker images. I was hoping I could convince you guys to do it, since the only version of libicu present in the Ubuntu repositories is 52.1 and I do loathe having to build libraries from source... ;P

Thanks for all your help anyways, guys. Keep up the good work!
