### ISSUE TITLE
Error compiling fresh F# project

### ISSUE THREAD

**Issue by ryanslade** [dotnet/coreclr#8226] opened 2016-11-21 16:32 UTC
I see the same issue in Linux or from the Docker container.

To reproduce:

```
docker run -it microsoft/dotnet:latest
root@5e24de8f4829:/# mkdir hwapp
root@5e24de8f4829:/# cd hwapp/
root@5e24de8f4829:/hwapp# dotnet new -l F#
Created new F# project in /hwapp.
root@5e24de8f4829:/hwapp# ls
Program.fs  project.json
root@5e24de8f4829:/hwapp# dotnet restore
log  : Restoring packages for /hwapp/project.json...
log  : Installing System.Security.Cryptography.Cng 4.2.0.
log  : Installing System.Security.Cryptography.Csp 4.0.0.
log  : Installing System.Globalization.Extensions 4.0.1.
log  : Installing System.Security.Cryptography.OpenSsl 4.0.0.
log  : Installing System.Diagnostics.DiagnosticSource 4.0.0.
log  : Installing runtime.native.System.Net.Http 4.0.1.
log  : Installing runtime.native.System.Security.Cryptography 4.0.0.
log  : Installing System.Threading.Tasks.Extensions 4.0.0.
log  : Installing Microsoft.FSharp.Core.netcore 1.0.0-alpha-160629.
log  : Installing System.Threading.ThreadPool 4.0.10.
log  : Installing runtime.native.System 4.0.0.
log  : Installing System.Threading.Tasks.Parallel 4.0.1.
log  : Installing System.Threading.Thread 4.0.0.
log  : Installing System.Runtime.Loader 4.0.0.
log  : Installing runtime.native.System.IO.Compression 4.1.0.
log  : Installing System.Reflection.TypeExtensions 4.1.0.
log  : Installing System.Reflection.Emit 4.0.1.
log  : Installing System.Buffers 4.0.0.
log  : Installing System.Net.WebHeaderCollection 4.0.1.
log  : Installing System.Linq.Expressions 4.1.0.
log  : Installing System.Security.Cryptography.X509Certificates 4.1.0.
log  : Installing System.Linq.Queryable 4.0.1.
log  : Installing System.Net.Http 4.1.0.
log  : Installing System.Runtime.InteropServices.RuntimeInformation 4.0.0.
log  : Installing System.Security.Cryptography.Algorithms 4.2.0.
log  : Installing NETStandard.Library 1.6.0.
log  : Installing System.Net.Requests 4.0.11.
log  : Installing System.Reflection.Emit.ILGeneration 4.0.1.
log  : Installing System.Reflection.Extensions 4.0.1.
log  : Installing System.ObjectModel 4.0.12.
log  : Installing System.Reflection.Emit.Lightweight 4.0.1.
log  : Installing System.Globalization.Calendars 4.0.1.
log  : Installing System.Net.Sockets 4.1.0.
log  : Installing Microsoft.Win32.Primitives 4.0.1.
log  : Installing System.IO.Compression.ZipFile 4.0.1.
log  : Installing System.IO.Compression 4.1.0.
log  : Installing System.Security.Cryptography.Primitives 4.0.0.
log  : Installing System.Threading.Timer 4.0.1.
log  : Installing System.Net.Primitives 4.0.11.
log  : Installing System.Security.Cryptography.Encoding 4.0.0.
log  : Restoring packages for tool 'dotnet-compile-fsc' in /hwapp/project.json...
log  : Installing NuGet.Configuration 3.5.0-beta2-1484.
log  : Installing NuGet.Protocol.Core.Types 3.5.0-beta2-1484.
log  : Installing Microsoft.NETCore.DotNetHost 1.0.1.
log  : Installing NuGet.Protocol.Core.v3 3.5.0-beta2-1484.
log  : Installing NuGet.Repositories 3.5.0-beta2-1484.
log  : Installing NuGet.LibraryModel 3.5.0-beta2-1484.
log  : Installing NuGet.Packaging.Core.Types 3.5.0-beta2-1484.
log  : Installing System.Globalization 4.0.0.
log  : Installing dotnet-compile-fsc 1.0.0-preview2-020000.
log  : Installing Microsoft.DotNet.Compiler.Common 1.0.0-preview2-003121.
log  : Installing Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121.
log  : Installing Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121.
log  : Installing Microsoft.NETCore.App 1.0.0.
log  : Installing Microsoft.FSharp.Compiler.netcore 1.0.0-alpha-160629.
log  : Installing System.Security.Principal.Windows 4.0.0.
log  : Installing System.Security.Principal 4.0.1.
log  : Installing Microsoft.DotNet.Files 1.0.0-preview2-003121.
log  : Installing System.Reflection.Metadata 1.3.0.
log  : Installing System.Security.Claims 4.0.1.
log  : Installing Microsoft.CSharp 4.0.1.
log  : Installing runtime.native.System.Net.Security 4.0.1.
log  : Installing System.Threading.Overlapped 4.0.1.
log  : Installing System.Runtime.Serialization.Primitives 4.1.1.
log  : Installing Microsoft.NETCore.Jit 1.0.2.
log  : Installing NuGet.RuntimeModel 3.5.0-beta2-1484.
log  : Installing Microsoft.NETCore.DotNetHostResolver 1.0.1.
log  : Installing Newtonsoft.Json 6.0.4.
log  : Installing Microsoft.Extensions.DependencyModel 1.0.0.
log  : Installing System.Dynamic.Runtime 4.0.11.
log  : Installing NuGet.Packaging 3.5.0-beta2-1484.
log  : Installing Newtonsoft.Json 9.0.1.
log  : Installing NuGet.Versioning 3.5.0-beta2-1484.
log  : Installing NuGet.Frameworks 3.5.0-beta2-1484.
log  : Installing System.Diagnostics.Process 4.1.0.
log  : Installing NuGet.ProjectModel 3.5.0-beta2-1484.
log  : Installing System.Reflection.DispatchProxy 4.0.1.
log  : Installing Microsoft.NETCore.DotNetHostPolicy 1.0.1.
log  : Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.2.
log  : Installing System.Resources.Reader 4.0.0.
log  : Installing NuGet.DependencyResolver.Core 3.5.0-beta2-1484.
log  : Installing System.Collections.Immutable 1.2.0.
log  : Installing System.IO.UnmanagedMemoryStream 4.0.1.
log  : Installing System.Numerics.Vectors 4.1.1.
log  : Installing Microsoft.Win32.Registry 4.0.0.
log  : Installing System.ComponentModel 4.0.1.
log  : Installing System.IO.MemoryMappedFiles 4.0.0.
log  : Installing System.IO.FileSystem.Watcher 4.0.0.
log  : Installing NuGet.Common 3.5.0-beta2-1484.
log  : Installing Microsoft.VisualBasic 10.0.1.
log  : Installing NuGet.Packaging.Core 3.5.0-beta2-1484.
log  : Installing System.Net.Security 4.0.0.
log  : Installing Microsoft.DotNet.InternalAbstractions 1.0.0.
log  : Installing Microsoft.DiaSymReader.PortablePdb 1.1.0.
log  : Installing System.Net.NameResolution 4.0.0.
log  : Installing System.Threading.Tasks.Dataflow 4.6.0.
log  : Installing System.Diagnostics.TraceSource 4.0.0.
log  : Installing Libuv 1.9.0.
log  : Installing System.Linq.Parallel 4.0.1.
log  : Installing System.ComponentModel.Annotations 4.1.0.
log  : Installing System.Reflection.Metadata 1.4.1-beta-24227-04.
log  : Installing Microsoft.DiaSymReader 1.0.8.
log  : Writing lock file to disk. Path: /hwapp/project.lock.json
log  : /hwapp/project.json
log  : Restore completed in 42169ms.
root@5e24de8f4829:/hwapp# dotnet run
Project hwapp (.NETCoreApp,Version=v1.1) will be compiled because expected outputs are missing
Compiling hwapp for .NETCoreApp,Version=v1.1
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
/usr/share/dotnet/dotnet compile-fsc @/hwapp/obj/Debug/netcoreapp1.1/dotnet-compile.rsp returned Exit Code 131

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.4282790
```

**Comment by jkotas** [comment] 2016-11-21 20:01
Duplicate of https://github.com/Microsoft/visualfsharp/issues/1791

**Closed by jkotas** 2016-11-21 20:01 UTC
