### ISSUE TITLE
DevDiv_278523 fails when run under MinOpts or Tiered compilation

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#13908] opened 2017-09-11 21:42 UTC
This test throws an InvalidProgramException compiling main if not run with normal JIT optimization flags. I encountered this while triaging issues that could show up when tiered jitting is enabled. The expectation for tiered compilation is that if the code compiles correctly with default optimizations on, it must also compile correctly when in TIER0 mode. In this case the test fails for both TIER0 and minopts.

Test output and repro info:

```
F:\github\coreclr\tests>set CORE_ROOT=F:\github\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
F:\github\coreclr\tests>set COMPLUS_JitMinOpts=1

F:\github\coreclr\tests>..\bin\tests\Windows_NT.x64.Release\JIT\Regression\JitBlue\DevDiv_278523\DevDiv_278523\DevDiv_278523.cmd
BEGIN EXECUTION
 "F:\github\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe" DevDiv_278523.exe

Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at C.Main()
Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED
```

To test with tiered jitting instead of minopts:

`F:\github\coreclr\tests>set COMPLUS_EXPERIMENTAL_TieredCompilation=1`

**Comment by noahfalk** [comment] 2017-09-11 21:46
@russellhadley - Can you help route?

#11476 - a different recent bug related to this test, @sandreenko @CarolEidt

**Comment by CarolEidt** [comment] 2017-09-12 00:19
> The expectation for tiered compilation is that if the code compiles correctly with default optimizations on, it must also compile correctly when in TIER0 mode. In this case the test fails for both TIER0 and minopts.

I'm not sure that's a realistic expectation, broadly speaking, for invalid programs, though certainly for the case of throwing `InvalidProgramException` we should, I assume, be able to detect the invalid program for minopts/TIER0 as well as the normal optimization path.

**Comment by sandreenko** [comment] 2017-09-12 00:58
Thanks for catching that.
Published the fix.

**Comment by noahfalk** [comment] 2017-09-12 01:40
> I'm not sure that's a realistic expectation, broadly speaking, for invalid programs

Not realistic as in occasionally we may find a thorny technical issue that prevents us from achieving it in a few rare corner cases, or it shouldn't even be the goal?

Any case where we can successfully compile in default optimization but fail to compile in Minopts/Tier0 is presumably both:
a) a case where the customer's app fails to run when they upgrade to a newer version of .Net Core
b) a case where the customer's app fails to run correctly when they try to build it in Debug.

**Comment by noahfalk** [comment] 2017-09-12 02:07
@sandreenko @CarolEidt - Is this unbalanced IL basically crazy for any real customer to have and thus not a case we need to worry about? I assume C# compiler would never generate such a thing but I imagine over the years you've gotten to know more obscure IL sequences that show up in real customer apps.
If a real customer showed up with this IL complaining that upgrading to a new version of .Net Core broke their app would we tell them "sorry the new version of .Net Core doesn't support your app"?

**Comment by sandreenko** [comment] 2017-09-12 06:55
There was no unbalanced IL in the original case.
Please review the fix.

**Comment by noahfalk** [comment] 2017-09-12 08:55
The fix seems fine to me assuming that we don't support this IL. It feels like you are implying the IL isn't supported, so apologies if I'm being pedantic but I wanted to get a clear call on that before saying OK on the fix. 

Saying that the unbalanced IL wasn't an intentional part of the original test is a somewhat different statement then saying it isn't supported.

**Comment by CarolEidt** [comment] 2017-09-12 15:21
> Not realistic as in occasionally we may find a thorny technical issue that prevents us from achieving it in a few rare corner cases, or it shouldn't even be the goal?

The former; I agree that it should be the goal, but I was just saying that, when presented with illegal/invalid IL, it is not always practical for the JIT to identify it, and if it doesn't, it is not necessarily the case that the behavior can be duplicated.

**Comment by CarolEidt** [comment] 2017-09-12 15:30
> The fix seems fine to me assuming that we don't support this IL.

Before we effectively dismiss the issue of inconsistent behavior by fixing this test case, I would like to understand why we can detect this as invalid IL in the non-optimizing case, but not when optimizing. I would think that, while the proposed fix is "correct", we should try to see if the JIT can detect the invalid IL in both cases.

> Saying that the unbalanced IL wasn't an intentional part of the original test is a somewhat different statement then saying it isn't supported.

@noahfalk - I agree with you. Unbalanced IL is invalid IL, so in that sense we don't support it. However, I don't know whether the JIT expects to always throw `InvalidProgramException` for such a program. If so, we should always do so. If not, we should determine whether the behavior can be made the same for both the optimized and non-optimized case.

So, my suggestion is:

1. Fix the test case to remove the unbalanced stack issue.
2. Add a test case with the "bad" version of the test, and fix the JIT to either always or never throw `InvalidProgramException ` for it. If that can't be done in a practical way, then close this issue as not fixable.

**Comment by AndyAyersMS** [comment] 2017-09-12 16:05
The jit very deliberately imports only "reachable" blocks when optimizing. What is considered reachable depends on the capabilities of the optimization code invoked during importation, and this changes over time as we add / improve / fix optimizations.

In minopts/debug modes the optimizations are (generally) not invoked and so a larger portion of the IL is considered reachable and is imported, so there is a chance the jit will discover invalid IL in minopts/debug but not when optimizing.

So I would say this behavior is by design and not a bug. 

For vaild/verifable IL it is a non-issue.

Changing the jit so all codegen modes import the same set of blocks would likely have a measurable impact on the TP of the jit when optimizing, and will likely pessimize CQ as well.

**Comment by CarolEidt** [comment] 2017-09-12 16:18
@AndyAyersMS - thanks, makes sense. Given that, I'm happy with fixing the test and closing this issue.

**Closed** 2017-09-12 20:11 UTC

**Comment by noahfalk** [comment] 2017-09-12 23:03
Agreed, thanks for the confirmation.
