### ISSUE TITLE
WebAssemberly

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/coreclr#13768] opened 2017-09-03 11:17 UTC
Please consider creating a build of the coreclr that targets the WebAssembly, I believe that .net in the browser has many benefits and could be a game changer. #blazor @SteveSandersonMS if/should the team not want the implement a WebAssembly build some guidance would be good in the form of a .net standard for targeting a web browser platform so the community could build something around .net core clr

**Comment by jkotas** [comment] 2017-09-04 23:40
Duplicate of #5303

cc @morganbr

**Closed by jkotas** 2017-09-04 23:40 UTC
