### ISSUE TITLE
dynamic keyword takes too much time.

### ISSUE THREAD

**Issue by sergign60** [dotnet/coreclr#18113] opened 2018-05-24 08:51 UTC
We found that ```dynamic``` keyword causes the significant delay at the first execution of a  method call. 
```
private static void Test2()
{
    dynamic dnClass = new Class1();
    for (int i = 0; i <= 5; i++)
    {
        try
        {
            Stopwatch sw = new Stopwatch();
            sw.Start();

            dnClass.Foo();

            sw.Stop();
            Log.Info("Sample", "Class1.Foo - " + sw.ElapsedMilliseconds.ToString() + "ms");
        }
        catch (MissingMethodException ex)
        {
            Console.WriteLine("Can't find Foo() - " + ex.ToString());
        }
    }
}
```
at the device with armel architecture we got the following result

Test2(57) > 1429ms
Test2(57) > 8ms
Test2(57) > 8ms
Test2(57) > 10ms
Test2(57) > 8ms
Test2(57) > 8ms

I added the simplest variant of this program (see attach) and got the following results on Ubuntu 16.04 x64 cpu MHz: 3801.226 with the latest verions of coreclr and corefx

Debug version
with ```dynamic``` 
```
Sample 4124 ms
Sample 17 ms
Sample 17 ms
Sample 17 ms
Sample 17 ms
Sample 17 ms
```
without ```dynamic```
```
Sample 39 ms
Sample 17 ms
Sample 17 ms
Sample 17 ms
Sample 18 ms
Sample 17 ms
```

Release version
with ```dynamic```
```
Sample 337 ms
Sample 2 ms
Sample 3 ms
Sample 2 ms
Sample 2 ms
Sample 2 ms
```
without ```dynamic```
```
Sample 3 ms
Sample 2 ms
Sample 2 ms
Sample 3 ms
Sample 3 ms
Sample 2 ms
```

[Program.cs.zip](https://github.com/dotnet/coreclr/files/2034454/Program.cs.zip)

**Comment by sergign60** [comment] 2018-05-24 08:52
@dotnet/arm32-contrib @janvorli

**Comment by mburbea** [comment] 2018-05-24 15:37
First debug is meaningless metric, and can be slower. 
Isn't this kind of by design? The IL to execute is being generated at runtime, and not on demand. Since the cost of a dynamic call site is likely only paid once its basically a non-issue. 

If you do require the performance back, you can code around it to not use dynamic.

**Comment by sergign60** [comment] 2018-05-24 15:56
@mburbea I don't quite agree with you. If we have a numerous using ```dynamic``` in a program, it could be significant losses in performance

**Comment by sergign60** [comment] 2018-05-25 08:38
@RussKeldorph We've re-checked it with Release version on the armel tizen device. The results are following
```
142ms
8ms
8ms
9ms
8ms
10ms
```
So this issue can be closed.

**Comment by sergign60** [comment] 2018-05-25 09:54
@jaredpar Could you point to those places in CoreCLR sources which can be the reason of so slow execution of the first call of a method for a variable with attribute ```dynamic```? Thanks in advance!

**Comment by mattwarren** [comment] 2018-05-25 11:28
I don't know if this is related to the CoreCLR sources, I'm pretty sure that `dynamic` support code lives in CoreFX. For instance, given this code:

``` csharp
  dynamic dnClass = new Class1();
  dnClass.Foo();
```

The IL below is produced, there's lots of overhead compared to a normal method call, although I believe that as much as possible is cached, so you only pay the *really large* cost on the first invocation. You can see [`Microsoft.CSharp.Runtime`](https://github.com/dotnet/corefx/tree/master/src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder) over in CoreFX.

```
IL_0000:  nop         
IL_0001:  newobj      UserQuery+Class1..ctor
IL_0006:  stloc.0     // dnClass
IL_0007:  ldsfld      UserQuery+<>o__0.<>p__0
IL_000C:  brfalse.s   IL_0010
IL_000E:  br.s        IL_0044
IL_0010:  ldc.i4      00 01 00 00 
IL_0015:  ldstr       "Foo"
IL_001A:  ldnull      
IL_001B:  ldtoken     UserQuery
IL_0020:  call        System.Type.GetTypeFromHandle
IL_0025:  ldc.i4.1    
IL_0026:  newarr      Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo
IL_002B:  dup         
IL_002C:  ldc.i4.0    
IL_002D:  ldc.i4.0    
IL_002E:  ldnull      
IL_002F:  call        Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create
IL_0034:  stelem.ref  
IL_0035:  call        Microsoft.CSharp.RuntimeBinder.Binder.InvokeMember
IL_003A:  call        System.Runtime.CompilerServices.CallSite<System.Action<System.Runtime.CompilerServices.CallSite,System.Object>>.Create
IL_003F:  stsfld      UserQuery+<>o__0.<>p__0
IL_0044:  ldsfld      UserQuery+<>o__0.<>p__0
IL_0049:  ldfld       System.Runtime.CompilerServices.CallSite<System.Action<System.Runtime.CompilerServices.CallSite,System.Object>>.Target
IL_004E:  ldsfld      UserQuery+<>o__0.<>p__0
IL_0053:  ldloc.0     // dnClass
IL_0054:  callvirt    System.Action<System.Runtime.CompilerServices.CallSite,System.Object>.Invoke
IL_0059:  nop         
IL_005A:  ret         
```

**Comment by kasper3** [comment] 2018-05-25 11:38
perhaps @VSadov and @JonHanna can also share some insights on optimization opportunities around dynamics/expandos?

**Comment by jkotas** [comment] 2018-05-25 14:18
The implementation of dynamic keyword lives under https://github.com/dotnet/corefx/tree/master/src/Microsoft.CSharp/src. It is a lot of code that needs to run for the first invocation of the dynamic keyword. It depends on https://github.com/dotnet/corefx/tree/master/src/System.Linq.Expressions that is even more complex code that needs to run.

You can experiment with defines in https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System.Linq.Expressions.csproj#L15. These defines control optimizations for throughput, but they are likely hurting startup. I do not expect it to make a huge difference though.

**Comment by JonHanna** [comment] 2018-05-30 10:18
Both MS.CSharp and S.L.Expressions has had a fair share of performance-related work done on it over the last couple of years, and I'm certainly keen to take advantage of any more opportunities found, but since there's caching involved as part of the consideration paid to performance in the very beginning I'd expect first execution to cost more than subsequent executions precisely because of that.

**Comment by RussKeldorph** [comment] 2018-05-30 17:17
Closing since it appears by design.  Feel free to open another issue if a specific performance opportunity is identified.

**Closed by RussKeldorph** 2018-05-30 17:17 UTC
Labels: tenet-performance

**Comment by VSadov** [comment] 2018-05-30 17:28
This is not the first bug that indirectly points that dynamic method compile is abnormally slow on ARM, especially in debug.

Perhaps that is something worth looking at?
