### ISSUE TITLE
System.PlatformNotSupportedException thrown running VB console app in .NET Core 3.0 Windows container

### ISSUE THREAD

**Issue by bwateratmsft** [dotnet/coreclr#26947] opened 2019-09-30 14:48 UTC
This issue was found recently by our CTI team.

It seems to only affect:
- VB app (we tried with Console apps)
- .NET Core 3.0 (did not repro with 2.2)
- Running in Windows container (we tried with -nanoserver-1903)

VB in Windows containers is a pretty corner scenario for us, but I'm not sure if this is indicative of another bigger problem.

Running the app--through VS, or directly on command line--results in this error:
`Unhandled exception. System.PlatformNotSupportedException: The system does not support the STA thread apartment.`

I ran with `COREHOST_TRACE=1`, there wasn't anything too interesting until the end:
```
launch host: C:\Program Files\dotnet\dotnet.exe, app: C:\app\ConsoleApp5.dll, argc: 0, args:

--- Begin breadcrumb write
Breadcrumb thread write callback...
Breadcrumbs will be written using a background thread.
Failed to leave breadcrumb, HRESULT: 0x80070003.
Failed to leave breadcrumb, HRESULT: 0x80070003.
Failed to leave breadcrumb, HRESULT: 0x80070003.
Failed to leave breadcrumb, HRESULT: 0x80070003.
--- End breadcrumb write

Unhandled exception. System.PlatformNotSupportedException: The system does not support the STA thread apartment.
```

I can certainly provide the full log if needed. I've not been able to get a call stack for that exception; doing a regular F5 debug detaches before anything happens (even with throw on exception), and the process exits with 0xe0434352.

The easiest repro is to create a VB .NET Core 3.0 console app in Visual Studio, and right-click project, Add > Docker Support, Windows containers.

**Comment by bwateratmsft** [comment] 2019-09-30 14:56
ConsoleApp5.vbproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ConsoleApp5</RootNamespace>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
  </ItemGroup>

</Project>
```

Program.vb:
```
Imports System

Module Program
    Sub Main(args As String())
        Console.WriteLine("Hello World!")
    End Sub
End Module
```

My Project\launchSettings.json:
```
{
  "profiles": {
    "ConsoleApp5": {
      "commandName": "Project"
    },
    "Docker": {
      "commandName": "Docker"
    }
  }
}
```

Dockerfile:
```
#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/runtime:3.0-nanoserver-1903 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-nanoserver-1903 AS build
WORKDIR /src
COPY ["ConsoleApp5/ConsoleApp5.vbproj", "ConsoleApp5/"]
RUN dotnet restore "ConsoleApp5/ConsoleApp5.vbproj"
COPY . .
WORKDIR "/src/ConsoleApp5"
RUN dotnet build "ConsoleApp5.vbproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConsoleApp5.vbproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConsoleApp5.dll"]
```

.dockerignore (one level up at solution directory):
```
**/.classpath
**/.dockerignore
**/.env
**/.git
**/.gitignore
**/.project
**/.settings
**/.toolstarget
**/.vs
**/.vscode
**/*.*proj.user
**/*.dbmdl
**/*.jfm
**/azds.yaml
**/bin
**/charts
**/docker-compose*
**/Dockerfile*
**/node_modules
**/npm-debug.log
**/obj
**/secrets.dev.yaml
**/values.dev.yaml
LICENSE
README.md
```

**Comment by MichalStrehovsky** [comment] 2019-09-30 15:14
Related to #21693. VB.NET secretly injects the `STAThreadAttribute` on the `Main()` method and CoreCLR fails while trying to respect that.

A workaround could be to place `<MTAThread>` on `Sub Main`.

I'm not sure if there's anything else we could do besides improving the exception message for this case. CoreCLR can't ignore the attribute and VB.NET can't stop emitting it due to compat.

**Comment by danmosemsft** [comment] 2019-09-30 15:49
@KathleenDollard @cston fyi, it seems VB apps won't run on Windows Nano Server. Don't know how interesting a scenario that is.

**Comment by bwateratmsft** [comment] 2019-09-30 15:53
Good to know, thanks @MichalStrehovsky. If it is intentional on the part of VB.NET then I'm not too concerned about it from our perspective; we don't have very high usage of Windows containers (< 25%), about 1/5 of that being .NET Framework, and I would guess the overwhelming majority of the other 4/5 is .NET Core C#, not VB.

**Comment by scyto** [comment] 2019-10-22 05:55
Crud, i just ran into this.

This was my first ever windows container, i got the app working on the dotnet core runtime linux amd64, then got it working on arm32v7 and arm32v8, thought i would get it on windows and publish a multi-arch, multiplatorm container on docker hub.  Oh well.

I am not the person who made the app, just making a container.
As such i can't get it converted to.NET Core C#

Could you suggest a better dotNet3 runtime docker container to pull?

**Comment by AaronRobinsonMSFT** [comment] 2020-01-15 17:37
Closing this issue for the following reasons:

1) VB.NET forces the STA for `Main` by default. [**By Design**]
1) Windows Nano Server doesn't support STA. [**By Design**]

End result is VB.NET by default isn't supported on Windows Nano Server.

Official workaround is https://github.com/dotnet/coreclr/issues/26947#issuecomment-536608907.

**Closed by AaronRobinsonMSFT** 2020-01-15 17:37 UTC
Labels: area-Interop, enhancement, question
