### ISSUE TITLE
[ARM/Linux] Miss casting void * value in IntPtr::ToInt64()

### ISSUE THREAD

**Issue by jyoungyun** [dotnet/coreclr#6854] opened 2016-08-23 06:00 UTC
This issue is related to `System.Diagnostics.Tests.ProcessModuleTests.TestModuleProperties` TC in CoreFX.
Test details:

```
   System.Diagnostics.Tests.ProcessModuleTests.TestModuleProperties [STARTING]
   System.Diagnostics.Tests.ProcessModuleTests.TestModuleProperties [FAIL]
      Assert+WrapperXunitException : File path: /home/jyoung/git/dotnet/corefx_upstream/src/System.Diagnostics.Process/tests/ProcessModuleTests.cs. Line: 25
      ---- Assert.InRange() Failure
      Range:  (0 - 9223372036854775807)
      Actual: -1403310080
      Stack Trace:
            at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
            at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
            at System.Diagnostics.Tests.ProcessModuleTests.TestModuleProperties()
         ----- Inner Stack Trace -----
            at Assert.InRange[T](T actual, T low, T high, String path, Int32 line)
```

In 32bit machine, the address can use the all 32bit including the signed bit(the 31th bit).
But this value currently is interpreted in negative value while converting long to void \* because the signed bit is true.

Here is the example code:

```
            long val = 2891657216;                                              
            unsafe {                                                               
                IntPtr val2 = new IntPtr((void *)val);                          
                Console.WriteLine("val {0} val2.ToInt64 {1}", val, val2.ToInt64());
            }  
```

And results:

```
val 2891657216 val2.ToInt64 -1403310080
```

2891657216 = AC5B3000
-1403310080 = FFFFFFFFAC5B3000

Just because the long value uses the signed bit in 32bit machine, it doesn't mean that the value is a negative. So ToInt64() function should return the original value without changing.

**Comment by jyoungyun** [comment] 2016-08-23 08:56
How can I substitute 32bit memory address to IntPtr ? Substitution is okay but there is no way to get the original value from IntPtr. ToInt64() makes the value to be negative value and ToInt32() can't support 64bit machine.

**Comment by hseok-oh** [comment] 2016-08-24 01:43
I cannot reproduce this issue in my environment.

Linux/ARM32 (hardfp)
CoreCLR: Release build -O3 (@a1ee7b80)
CoreFX: Release build -O3 (dotnet/corefx@0435efe)

**Comment by jkotas** [comment] 2016-08-24 03:13
The ProcessModule tests should be fixed to test for the full possible range:

`Assert.InRange(module.BaseAddress.ToInt64(), long.MinValue, long.MaxValue);`

**Comment by jkotas** [comment] 2018-03-02 01:11
Fixed by https://github.com/dotnet/corefx/pull/11086

**Closed by jkotas** 2018-03-02 01:11 UTC
Labels: arch-arm32, test bug
