### ISSUE TITLE
[arm32/Ubuntu] corefx test timeouts

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17754] opened 2018-04-24 17:31 UTC
The following tests time out (with 10 minute default timeout) in a corefx test run:

```
System.Collections.Tests
System.Transactions.Local.Tests
System.Xml.RW.XmlConvert.Tests
```

e.g.,

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/1/consoleText

**Comment by BruceForstall** [comment] 2018-04-24 19:02
When fixing this, update tests\arm\corefx_linux_test_exclusions.txt

**Comment by echesakovMSFT** [comment] 2018-04-26 22:10
Ran couple times `System.Collections.Tests` with JitStress=1 and the tests always pass. Seems that timeout 10m is too tight for this test assembly

```
ubuntu@tegra-ubuntu:~/echesakov/coreclr/_/fx/bin/tests/System.Collections.Tests/netcoreapp-Linux-Release-arm$ /home/ubuntu/echesakov/coreclr/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet xunit.console.netcore.exe System.Collections.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Collections.Tests
Discovered:  System.Collections.Tests
Starting:    System.Collections.Tests
Finished:    System.Collections.Tests

=== TEST EXECUTION SUMMARY ===
   System.Collections.Tests  Total: 29687, Errors: 0, Failed: 0, Skipped: 0, Time: 566.193s
```

**Comment by echesakovMSFT** [comment] 2018-04-28 00:09
`System.Transactions.Local.Tests` hangs intermittently during `System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync`:
```
ubuntu@tegra-ubuntu:~/echesakov/coreclr/_/fx/bin/tests/System.Transactions.Local.Tests/netcoreapp-Linux-Release-arm$ /home/ubuntu/echesakov/coreclr/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet  xunit.console.netcore.exe System.Transactions.Local.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -method System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync -showprogress
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Transactions.Local.Tests
Discovered:  System.Transactions.Local.Tests
Starting:    System.Transactions.Local.Tests
   System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync [STARTING]
```

Sometimes it passes the test though:
```
ubuntu@tegra-ubuntu:~/echesakov/coreclr/_/fx/bin/tests/System.Transactions.Local.Tests/netcoreapp-Linux-Release-arm$ /home/ubuntu/echesakov/coreclr/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet  xunit.console.netcore.exe System.Transactions.Local.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -method System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync -showprogress
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Transactions.Local.Tests
Discovered:  System.Transactions.Local.Tests
Starting:    System.Transactions.Local.Tests
   System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync [STARTING]
   System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync [FINISHED] Time: 0.8004862s
```

**Comment by echesakovMSFT** [comment] 2018-04-30 22:25
`System.Text.RegularExpressions.Tests` issue is also reproducible on Windows/arm (e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_minopts_tst/11/consoleText)
```
C:\Users\robox\j\workspace\arm_cross_che---37e2d920\_\fx\bin\tests\System.Text.RegularExpressions.Tests\netcoreapp-Windows_NT-Release-arm>set COMPlus_JITMinOpts=1 

C:\Users\robox\j\workspace\arm_cross_che---37e2d920\_\fx\bin\tests\System.Text.RegularExpressions.Tests\netcoreapp-Windows_NT-Release-arm>call C:\Users\robox\j\workspace\arm_cross_che---37e2d920\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe System.Text.RegularExpressions.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Text.RegularExpressions.Tests
Discovered:  System.Text.RegularExpressions.Tests
Starting:    System.Text.RegularExpressions.Tests
   System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix [FAIL]
      Timed out after 60000ms waiting for remote process 3748
      Expected: True
      Actual:   False
      Stack Trace:
         D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs(241,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing)
         D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs(228,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
         D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Text.RegularExpressions\tests\Regex.Match.Tests.cs(770,0): at System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix()
Finished:    System.Text.RegularExpressions.Tests
```

**Comment by echesakovMSFT** [comment] 2018-05-01 01:12
`System.Xml.RW.XmlConvert.Tests` took 856s and succeeded on my Ubuntu/arm device.
`System.Text.Encodings.Web.Tests` took 695s in baseline and 687s with `COMPlus_JITMinOpts=1` and also succeeded on my Ubuntu/arm machine.

I consider increasing timeout to 20min in `corefx/run-test.sh` and enable those test assemblies in #17836.

`System.Text.RegularExpressions.Tests` uses `RemoteInvoke` mechanism for running their test method in a separate process which has its own timeout [`RemoteExecutorTestBase.FailWaitTimeoutMilliseconds`](https://github.com/dotnet/corefx/blob/47679a89a844854563a8432b18b65bc4c163a37d/src/CoreFx.Private.TestUtilities/ref/CoreFx.Private.TestUtilities.cs#L129) (60000ms) which seems not enough for `System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix` test method.

**Comment by echesakovMSFT** [comment] 2018-05-02 00:42
I have opened an issue specific for `System.Transactions.Local.Tests` (#17858) since we have increased timeout and enabled back other tests from this issue in dotnet/corefx#29420 and #17836.

The issue with `System.Text.RegularExpressions.Tests` need to be resolved in corefx repo.

**Closed by echesakovMSFT** 2018-05-02 00:42 UTC
Labels: arch-arm32, bug, os-linux

**Comment by BruceForstall** [comment] 2018-07-13 22:31
@echesakovMSFT We still have this line in arm\corefx_test_exclusions.txt (for Windows):
```
System.Text.RegularExpressions.Tests # https://github.com/dotnet/coreclr/issues/17754 -- timeout -- JitMinOpts only
```

If the issue is really resolved, this should be removed.

However, I am seeing this same test time out when bringing up corefx testing for arm64 (also JitMinOpts only), so it seems it is not quite resolved.
