### ISSUE TITLE
Environment.TickCount slower on Linux than Windows Core

### ISSUE THREAD

**Issue by ianhays** [dotnet/coreclr#2257] opened 2015-12-07 20:30 UTC
Environment.TickCount is significantly slower for me on Linux than on Windows running on Core. The following console app:

```
class Program
{
    static void Main()
    {
        while (true)
        {
            Stopwatch timer = new Stopwatch();
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            int tar;
            timer.Start();
            for (int i = 0; i < 40000; i++)
            {
                tar = Environment.TickCount; tar = Environment.TickCount; tar = Environment.TickCount;
                tar = Environment.TickCount; tar = Environment.TickCount; tar = Environment.TickCount;
                tar = Environment.TickCount; tar = Environment.TickCount; tar = Environment.TickCount;
            }
            timer.Stop();
            Console.WriteLine(timer.Elapsed);
        }
    }
}
```

runs very fast on Windows 10 Core:
```
00:00:00.0009579
00:00:00.0009627
00:00:00.0009003
00:00:00.0008818
00:00:00.0009265
00:00:00.0009588
00:00:00.0009627
00:00:00.0008618
00:00:00.0008749
00:00:00.0008869
00:00:00.0008955
00:00:00.0009550
00:00:00.0009576
00:00:00.0008621
00:00:00.0008752
00:00:00.0009063
00:00:00.0009103
00:00:00.0009314
00:00:00.0009320
00:00:00.0009017
00:00:00.0009009
00:00:00.0009411
00:00:00.0009610
00:00:00.0009647
00:00:00.0008772
00:00:00.0009000
00:00:00.0009288
00:00:00.0009596
00:00:00.0009579
00:00:00.0009362
00:00:00.0009071
00:00:00.0009274
00:00:00.0009585
00:00:00.0009576
```

but significantly slower on Ubuntu 14.04 (running in a VM from the same Windows machine as above):
```
00:00:00.1984721
00:00:00.2079998
00:00:00.2026383
00:00:00.2145338
00:00:00.2387930
00:00:00.2003931
00:00:00.2382845
00:00:00.2030758
00:00:00.2024682
00:00:00.2017533
00:00:00.2362008
00:00:00.2008249
00:00:00.2379706
00:00:00.2021955
00:00:00.2010206
00:00:00.2210337
00:00:00.2168053
00:00:00.2374686
00:00:00.2016367
00:00:00.2016803
00:00:00.2012516
00:00:00.2384811
00:00:00.2012130
00:00:00.2384954
```

Related to https://github.com/dotnet/corefx/issues/3572.

**Comment by varocarbas** [comment] 2015-12-10 12:02
Accurately comparing the performance of two different computers running different OSs is not easy at all. But if you are additionally performing different actions, such a goal becomes almost impossible.

By quoting the official documentation (https://msdn.microsoft.com/en-us/library/system.environment.tickcount(v=vs.110).aspx), ```Environment.TickCount``` "gets the number of milliseconds elapsed since the system started". That is: the differences between both computers might be mostly conditioned by the fact that one of them (the Linux one) has been running during a much longer period of time. Your ```tar = Environment.TickCount;``` might be storing notably different values in both situations by provoking the appreciable time differences you are showing.

In any case, there might be other factors like how powerful the given computer is or even how efficiently the given OS performs certain actions. That's why your testing framework is not providing a clear enough picture about what is really happening. And in any case, just the fact of accessing the values of a variable like ```Environment.TickCount``` should be done almost immediately regardless of the conditions (i.e., no appreciable time delay should be provoked because of it).

**Comment by stephentoub** [comment] 2015-12-10 13:23
@varocarbas, the point of the issue is that we want developers to be able to expect that a particular workload on coreclr will have similar performance characteristics, regardless of the platform on which the code is running, which means that the consituent operations which make it up should ideally have simlar performance characteristics.  It's up to us as the implementers of that operation to implement the operation on each platform as best as possible on that platform.  In some cases there may be platform differences that make it impossible to get similar performance, but for something that's showing up as a 200x difference, that's absolutely worth investigating further.  It's certainly possible (likely) that there are differences between the setups impacting the results (e.g. one in a VM, one not), but @ianhays runs lots of benchmarks across Windows and Linux that are generally on-par with each other and that don't exhibit nearly this level of difference.  The point of an issue like this is that someone needs to go and spend some time looking into it further to understand whether there's a bug to be fixed, and if so, what is the fix.  For example, if as you propose the time taken to invoke Environment.TickCount is proportional to the up-time of the machine, that'd be a big problem that would need to be fixed (I don't believe that's the issue, though).

**Comment by varocarbas** [comment] 2015-12-10 13:30
@stephentoub  You cannot accurately measure performance by accounting for completely different situations. As said, the exact contents of the variables being tested might have a very different values (orders of magnitude). It would be like comparing the performance of a list with 10 values and an array with 1million and concluding that the list is faster.

Perhaps @ianhays has found something, but the proposed test doesn't provide any insights into the problem. Firstly, the exact same situation should be tested; and secondly, additionally issues like memory/hardware of the computers should be brought into account. Regarding the OS difference, you are right and this shouldn't be an issue.

**Comment by stephentoub** [comment] 2015-12-10 13:36
> As said, the exact contents of the variables being tested might have a very different values (orders of magnitude). It would be like comparing the performance of a list with 10 values and an array with 1million and concluding that the list is faster.

What variables / contents of those variables are you referring to here, and why do you believe their values are having orders of magnitude impact on this microbenchmark?  I don't see anything in this benchmark that's parallel to testing a list of 10 elements and an array of 1000 elements.

>  the proposed test doesn't provide any insights into the problem

That's not the purpose of the test; @ianhays is highlighting a difference in throughput that he's noticed, and it's up to whomever investigates the issue to dig in to understand what's causing the difference.

**Comment by varocarbas** [comment] 2015-12-10 13:40
@stephentoub I explained it in my first comment: ```Environment.TickCount``` refers to the number of milliseconds since the given computer was started. Imagine the quite likely situation of a recently-rebooted computer vs. a server which has been running for months.

**Comment by stephentoub** [comment] 2015-12-10 13:43
> Imagine the quite likely situation of a recently-rebooted computer vs. a server which has been running for months.

If that has any impact whatsoever on performance, that's a huge bug that would need to be fixed.  The value returned from TickCount should have little-to-no impact on the performance of TickCount.

**Comment by varocarbas** [comment] 2015-12-10 13:50
@stephentoub  No. You don't get the point. The testing framework consists in a loop doing the same actions 40000 times and measuring the time requirements. This action consists in assigning certain value to a variable 9 times. The problem is that this variable (```Environment.TickCount```) might differ notably from one computer to the other one. Although the assignation process is quite quick, when you assign a value 9*40000 times, every little counts. When we are talking about really big differences (and about what this would imply for memory/CPU), the shown times makes sense. It is not the same assigning 9*40000 times 10 than 100000. Does this fact explains the whole difference? No idea. But that's why my suggestion: when doing a performance comparison, make sure that the conditions are as similar as possible (not the case here). Additionally, blaming ```Environment.TickCount``` of the observe differences seems completely arbitrary.

**Comment by ayende** [comment] 2015-12-10 13:52
You seem to think that there is a difference in speed between:

    long tar = 1;

And

   long tar = 9223372036854775808;

Is that what you are saying?


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by varocarbas** [comment] 2015-12-10 13:54
@ayende When you do it 9x40000 times over and over, there is certainly an important memory/CPU difference.

**Comment by ayende** [comment] 2015-12-10 13:58
Um... what?

No, it isn't.

In both cases, the amount of work you do is exactly the same.

This is for int32, but the same principal holds:
Here is for 1:

[image: Inline image 1]

Here is for 2107583221 :

[image: Inline image 2]

In both cases, doing:

tar = val;

requires you to copy the same amount of bytes.



*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by varocarbas** [comment] 2015-12-10 14:12
@ayende Actually you are right. I let the basic ideas (make sure that the testing conditions are identical) kick in, so a big difference in the values (and a not-too-well-defined hardware conditions) and didn't think about the exact situation carefully. The type remain constant and so there is no appreciable difference on this front.

In any case, the proposed testing framework (the information provided) does seem enough to support what is claimed.

**Comment by varocarbas** [comment] 2015-12-10 14:53
After thinking a bit more about the issue of the notable differences in the size of the values, it might be the real problem here anyway (although not as directly as I firstly thought).

As clarified above, having bigger or small values (as far as all of them are ```int```) doesn't have any direct effect on the measurement process, because the resulting assignations are performed equally quickly. But this fact might certainly have an impact on all what is associated with calculating/storing the ```Environment.TickCount``` information (i.e., different methods/variables storing/calculating notably bigger values).

A new test under similar-enough conditions is certainly required to prove/dismiss the point. That is: equivalent hardware and equivalent Environment.TickCount (which also implies equivalent running time, another relevant issue when comparing performances).

**Comment by ayende** [comment] 2015-12-10 14:59
There is absolutely no way that TickCount is affected by the uptime of the
machine. That would be a horrible implementation

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by varocarbas** [comment] 2015-12-10 15:03
@ayende You corrected me first and not it is my turn :)

It is precisely defines the uptime of the given machine. As explained in my first comment and by quoting the official source (https://msdn.microsoft.com/en-us/library/system.environment.tickcount(v=vs.110).aspx), it "gets the number of milliseconds elapsed since the system started". You might be confusing ```Environment.TickCount``` with one of the tick-counting properties of the ```Stopwatch``` class.

**Comment by janvorli** [comment] 2015-12-10 15:15
@varocarbas This test doesn't measure the result from getting the TicksCount. It measures how long it takes to read the TickCount property. It is reading the property is not a simple variable read, it is a call to a Windows or Unix PAL function that asks the OS to get the number of ticks. So it does potentially a nontrivial amount of work to get it. 
The point of the measurement as I understand it was to provide a mean to figure out the difference and provide a mean of measurement that can be used while trying to optimize the ticks extraction.
From your posts, it seemed to me as if you think that the TicksCount is a plain variable, which is not the case.

**Comment by varocarbas** [comment] 2015-12-10 15:32
@janvorli I think that my last comment lets very clear my ideas on this front (please read it and don't assume that I think what I haven't said).

Seriously, the point is not too difficult: the proposed testing framework is unreliable. The behaviour which you want to test is irrelevant because your conclusions will be inaccurate anyway.

If you are not controlling all the issues which might affect the measurements (as I explained in some of my comments), you wouldn't be knowing what is causing the differences. This is what is called noise.

To prove that ```Environment.TickCount``` is slower on Linux than on Windows,  you would have to make sure that both machines are equally powerful and that they are accounting for similar ```Environment.TickCount``` values (i.e., the noise in the measuring process is as low as possible). Otherwise, you would be comparing apples with mangoes and your conclusions wouldn't be reliable.

**Comment by ayende** [comment] 2015-12-10 15:36
That isn't the case.
If I have a Toyota and a Ferari, and I compare their speed, I don't need to
have an exact match to know there is a problem if the Toyota can't get over
10 KPH while the Ferari does 400 KPH.


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment] 2015-12-10 15:38
@varocarbas

You seem to be missing the point, the _value_ of TickCount is obviously
related to the uptime, since it _is_ the uptime.
But the _time_ to actually _get_ the uptime is unrelated to the amount of
time the machine was up


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by varocarbas** [comment] 2015-12-10 15:46
@ayende "If I have a Toyota and a Ferari..." -> if you put both on the same road, you would have the same conditions and the Ferrari would certainly win (well... depending upon what Toyota/Ferrari are we talking about).
If you put the Toyota in a perfect road and the Ferrari in the sea; the Toyota would certainly be faster.

Sorry, but I will stop answering things which I don't consider that makes any sense (at all or for what is intended here). I don't want to offend anyone, but if I would like to talk about abstract/irrelevant issues, I would be chatting in LinkedIn.

I thought that the whole point of being here is actually changing things and actually wanting to make everything better (like StackOverflow, but with excellent resources); and I am starting to feel that this is not completely the case.

PS: BTW, you are showing a very honest and straightforward behaviour.

**Comment by shahid-pk** [comment] 2015-12-10 15:54
@varocarbas  making things better does not mean make it the way one want it to be. We are talking about making changes to a framework that could effect millions of users , so we should argue and counter arguments should be their. If things started to change based on a single person decisions the framework will become only suitable for that person.  This is an open source practice you bring in your changes/ideas and other developers scrutinize it for the sake of betterment.

**Comment by varocarbas** [comment] 2015-12-10 16:50
@shahid-pk Note that my comments have been provoked after having answered a relevant amount of claims in a quite short amount of time, whose only point seemed to be proving that all what I was saying was wrong (no matter what I was saying in that specific moment) by relying on mere repetitions/random arguments.

I understand that certain agreement is required. Although perhaps a more clearly-delimited request process might be better. For example: I don't want to get involved in random discussions with random people. I want to suggest an implementation and to provide all the (objective) information required. Have to wait for some days? No problem. Have to follow a very strict set of rules? No problem. My proposal is rejected? No problem (well... although I might not like it). Being forced to participate in chat where anyone can say anyhing at any point? I don't want that. There are plently of chats I might choose to go to.

Anyway... I am new here and even perhaps this community doesn't like me (and/or I like it); but lesson certainly learned for the future.

**Closed** 2015-12-10 19:19 UTC
Labels: performance
