### ISSUE TITLE
[arm64/linux] System.Net.HttpListener.Tests failed with System.ObjectDisposedException

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21676] opened 2018-12-26 02:32 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_tst/71/
**failed test:**
System.Net.HttpListener.Tests

**Failed log:**
```
~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_tst/_/fx/artifacts/bin/tests/System.Net.HttpListener.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_tst/_/fx/artifacts/bin/tests/System.Net.HttpListener.Tests/netcoreapp-Linux-Release-arm64
[37m  Discovering: System.Net.HttpListener.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Net.HttpListener.Tests (found 261 of 298 test cases)
[m[37m  Starting:    System.Net.HttpListener.Tests (parallel test collections = on, max threads = 46)
[m[33;1m    System.Net.Tests.HttpListenerAuthenticationTests.BasicAuthentication_RealmSet_SendsChallengeToClient [SKIP]
[m[37m      Condition(s) not met: "IsWindowsImplementation"
[m[33;1m    System.Net.Tests.HttpListenerAuthenticationTests.NoAuthentication_AuthenticationProvided_ReturnsForbiddenStatusCode [SKIP]
[m[37m      Condition(s) not met: "IsWindowsImplementation"
[m[33;1m    System.Net.Tests.HttpListenerAuthenticationTests.NoAuthenticationGetContextAsync_AuthenticationProvided_ReturnsForbiddenStatusCode [SKIP]
[m[37m      Condition(s) not met: "IsWindowsImplementation"
[m
Unhandled Exception: 
Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.BeginGetContext(AsyncCallback callback, Object state) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs:line 290
   at System.Net.ListenerAsyncResult.Complete(HttpListenerContext context, Boolean synch) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.HttpListener/src/System/Net/Managed/ListenerAsyncResult.Managed.cs:line 159
   at System.Net.HttpListener.RegisterContext(HttpListenerContext context) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs:line 224
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/Common/src/System/Net/LazyAsyncResult.cs:line 400
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/Common/src/System/Net/ContextAwareResult.cs:line 388
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/Common/src/System/Net/LazyAsyncResult.cs:line 354
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/BaseOverlappedAsyncResult.Unix.cs:line 29
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 485
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 870
   at System.Net.Sockets.SocketAsyncContext.ProcessAsyncReadOperation(ReadOperation op) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 1269
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.BeginGetContext(AsyncCallback callback, Object state) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs:line 290
   at System.Net.ListenerAsyncResult.Complete(HttpListenerContext context, Boolean synch) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.HttpListener/src/System/Net/Managed/ListenerAsyncResult.Managed.cs:line 159
   at System.Net.HttpListener.RegisterContext(HttpListenerContext context) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs:line 224
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/Common/src/System/Net/LazyAsyncResult.cs:line 400
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/Common/src/System/Net/ContextAwareResult.cs:line 388
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/Common/src/System/Net/LazyAsyncResult.cs:line 354
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/BaseOverlappedAsyncResult.Unix.cs:line 29
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 485
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 870
   at System.Net.Sockets.SocketAsyncContext.ProcessAsyncReadOperation(ReadOperation op) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 1269
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
./RunTests.sh: line 126:  6334 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.dll System.Net.HttpListener.Tests.dll -xml testResults.xml -nologo -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=IgnoreForCI -notrait category=failing -notrait category=Outerloop
~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_tst/_/fx/artifacts/bin/tests/System.Net.HttpListener.Tests/netcoreapp-Linux-Release-arm64
----- end 22:25:50 ----- exit code 134 ----------------------------------------------------------
```

**Comment by wfurt** [comment] 2019-01-17 23:15
This looks same as exception observed in https://github.com/dotnet/corefx/pull/34559

This was essentially race condition in tests. 
I could not reproduce this on my system:
```
  Finished:    System.Net.HttpListener.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.HttpListener.Tests  Total: 658, Errors: 0, Failed: 0, Skipped: 20, Time: 144.445s
~/github/wfurt-corefx-arm/artifacts/bin/tests/System.Net.HttpListener.Tests/netcoreapp-Linux-Debug-arm64
```

was this executed with some kind of stress condition?

**Comment by wfurt** [comment] 2019-04-03 17:58
This may be related to https://github.com/dotnet/corefx/issues/35191 
It seems like we give up on fixing this code. I don't think this should block.

cc: @karelz

**Comment by karelz** [comment] 2019-04-03 18:01
Agreed, closing as Won't Fix.

**Closed by karelz** 2019-04-03 18:01 UTC
Labels: arch-arm64, blocking-3.0-preview-5, os-linux, test-corefx
