### ISSUE TITLE
[Arm64] Improve continuous integration

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#9535] opened 2017-02-11 17:06 UTC
Crossgen failures have broken the tip several times in the last few months.  It seems CI should at a minimum include testing crossgen System.Private.Corelib.dll.

[Arm64/Windows] CI did not run any tests last I checked
[Arm64/Unix] does not have any continuous integration support

Can we start a discussion on what is preventing adding better continuous integration support?

Is most of the issue lack of Arm64 hardware (with sufficient performance)?

@dotnet/arm64-contrib

**Comment by RussKeldorph** [comment] 2017-02-12 00:56
Certain members of the Microsoft org are able to request Windows ARM64 jobs on any PR, and, as of recently, those same individuals get ARM64 badges in their own PRs by default.  The hope is that most of the people making changes likely to break ARM64 are on the list.  The policies around Windows ARM64 testing are related to information disclosure, not hardware availability.

There's nothing blocking us from adding ARM64/Unix systems in CI other than the time and effort required to set it up.  We tried to at least get Unix builds on PRs in the past, but it was far from trivial due to tool bugs.  As long as things have matured and it's not too hard to get an OS booted on the somewhat dated hardware we have in CI, it may be worth it at this point.

**Comment by jashook** [comment] 2017-02-15 17:08
@dotnet/arm64-contrib

**Comment by sdmaclea** [comment] 2017-04-03 16:13
@dotnet/arm64-contrib Windows Arm64 CI has been broken for over 2 weeks (#10326).  Most of the issues appear to be manually picking tests and corefx libraries.  This should be automated.

FWIW I have managed to automate this process in my internal CI for merge commits.  It is pretty straight forward and obvious

1. Use correct corefx version using dependencies.prop.  Build cross native and managed components for use in overlay
2. Use correct tests by using those built by x64_checked_windows_nt_pri1_bld of the same git version.

The only issues with this approach is that 

1. I am dependent on a passing x64_checked_windows_nt_pri1_bld of the same git version.
2. I am dependent on a corefx version which compiles

Pull requests would need a different approach

**Comment by jashook** [comment] 2017-04-03 18:11
@sdmaclea for historical reasons the arm64 Windows CI relies on a frozen set of test binaries. Now that we are past that stage, and corefx is fairly stable we can remove that dependency. The work to do so is not much and I have begun doing it while updating the test drop.

**Comment by sdmaclea** [comment] 2017-04-13 19:21
@RussKeldorph Since @BruceForstall has merged common arm32 and arm64 code, arm64 is at risk for regression with every arm32 change.  We now need to automatically trigger arm64 CI for every arm32 commit before it can be merged.

**Comment by RussKeldorph** [comment] 2017-04-13 19:35
@chrisboh FYI this is why I'm asking about the ARM64 box. :)

**Comment by mskvortsov** [comment] 2017-04-13 19:52
> arm64 is at risk for regression with every arm32 change

I'd like to mention that altjit arm32 itself is at risk for regression with every jit change.
cc @hqueue

**Comment by BruceForstall** [comment] 2017-04-13 20:54
fyi, arm64 JIT (altjit) builds on all x64 (Linux and Windows) builds, and arm32 JIT (altjit) builds on all x86 builds. So, we do have CI coverage for builds. And arm32 testing is in the CI. The only thing we're missing is automatic arm64 testing. I'll try to remember to trigger arm64 runs on all common code changes.

**Comment by jashook** [comment] 2017-05-25 19:45
@sdmaclea I am having trouble getting the cross build to work with our current documentation. Are you following any steps outside the current documentation for the ubuntu arm64 build?

**Comment by sdmaclea** [comment] 2017-05-25 20:30
@jashook 
+ I am running Ubuntu amd64 16.04.
+ First I make sure amd64 build works.  
    + https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md
    + I install clang3.8, llvm3.8, **clang, llvm (note duplicate packages),** 
    + I installed **.NET Core 1.1.2 dotnet framework**.  
    + I might have installled mono (probably not necessary).
+ arm64 packages..  
    + `sudo apt-get install qemu qemu-user-static binfmt-support debootstrap`
    + `sudo apt-get install binutils-aarch64-linux-gnu`
     + the list may be incomplete.???
+ ROOTFS, 
    + `sudo ROOTFS_DIR=$HOME/arm64-xenial-rootfs ./cross/build-rootfs.sh arm64 xenial no-lldb`
    + **no-lldb**
    + I have not built one in a while.  I target xenial 16.04
    + When I first build one there were issues around lldb, I do not include an lldb package because I have not been building SOS debugger.  I think this is the current default
    + I may have had to install a few packages which were missing from the ROOTFS.  Basically any libraries needed for cross compilation.  This is a subset of the packages needed to compile CoreCLR for amd64 on Linux.  Looks like the list is close to complete now, but might be missing uuid-dev
+ Cross compiling 
  + `ROOTFS_DIR=$HOME/arm64-xenial-rootfs ./build.sh debug clang3.8 arm64 cross skipnuget`
    + **skipnuget** 
    + **I do not use the `verbose` or `-rebuild` options**
```
   45 Warning(s)
    0 Error(s)

Time Elapsed 00:00:11.06
Command execution succeeded.
Command successfully completed.
Repo successfully built.
Product binaries are available at /home/vmjenkins/workspace/Dotnet/build_and_test/bin/Product/Linux.arm64.Checked
```

If you have error message, I might be better able to help.

I had previously dealt with transient errors during compilation with a retry(3) in my Jenkins build script.
```
          withEnv(['ROOTFS_DIR=/home/sdmaclea/arm64-xenial-rootfs/']) {
            retry(2) {
              sh script:"nice timeout 1200 ./build.sh ${BuildType} clang3.8 arm64 cross skipnuget"
            }
          }
```

**Comment by jashook** [comment] 2017-05-25 21:47
@sdmaclea thank you for the explanation. I have successfully built following these instructions, it looks like building to rootfs without specifying the xenial will cause problems.

**Comment by sdmaclea** [comment] 2017-06-16 18:21
@jashook Should this be closed because Ubuntu/Arm64 CI was added.  Should we wait till it is green?

**Comment by BruceForstall** [comment] 2018-07-27 21:34
We currently have no Linux/arm64 testing in our CI. We are still working on getting some Linux/arm64 hardware installed, at which point we hope to add that testing.

We have full Windows/arm64, Windows/arm32, and Ubuntu/arm32 in the CI.

**Comment by sdmaclea** [comment] 2018-08-03 21:12
@BruceForstall 

There are a few ARM/ARM64 cloud providers available.  I think Packet.Net might have something @vielmetti may be able to comment.  There is also this comment which which talks about a few other providers. https://github.com/coreos/etcd/issues/5054#issuecomment-407621353

**Comment by vielmetti** [comment] 2018-08-07 18:39
Thanks @sdmaclea . Packet has arm64 hardware in both its public cloud and also in a private cluster available for CI/CD and test and development use. Please see https://github.com/worksonarm/cluster or http://worksonarm.com and open up a Github issue in the cluster repo to request access to gear.

**Comment by BruceForstall** [comment] 2018-10-18 01:07
We now have full parity in our CI with Linux/arm64 compared to our other platforms. I'm going to close this issue.

**Closed by BruceForstall** 2018-10-18 01:07 UTC
Labels: Design Discussion, arch-arm64, area-Infrastructure, test bug
