### ISSUE TITLE
Test failed: JIT_jit64._mcc_interop_mcc_i00_mcc_i00_._mcc_interop_mcc_i00_mcc_i00_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25414] opened 2019-06-26 02:20 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-ci/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190625.38/workItem/JIT.jit64.mcc/analysis/xunit/JIT_jit64._mcc_interop_mcc_i00_mcc_i00_~2F_mcc_interop_mcc_i00_mcc_i00_cmd

**Failed tests:**
JIT_jit64._mcc_interop_mcc_i00_mcc_i00_._mcc_interop_mcc_i00_mcc_i00_cmd

**Log:**
```
Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\9cb78fb5-cc17-48b0-9382-3fe7f09f7a2a\\Exec\\JIT\\jit64\\Reports\\JIT.jit64\\mcc\\interop\\mcc_i00\\mcc_i00.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload\\corerun.exe\" mcc_i00.exe 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload
> C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\9cb78fb5-cc17-48b0-9382-3fe7f09f7a2a\\Exec\\JIT\\jit64\\mcc\\interop\\mcc_i00\\mcc_i00.cmd
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment] 2019-06-26 16:25
https://github.com/dotnet/coreclr/pull/25429?

**Comment by RussKeldorph** [comment] 2019-06-26 23:56
Assuming duplicate of #25376

**Closed by RussKeldorph** 2019-06-26 23:56 UTC
Labels: arch-arm32, os-windows
