### ISSUE TITLE
coreclr_initialize failed 0x80131500

### ISSUE THREAD

**Issue by vindicatorr** [dotnet/coreclr#4087] opened 2016-04-05 19:13 UTC
https://github.com/dotnet/roslyn/issues/10338
It was suggested I post the issue here as well.

Using Archlinux.
When roslyn build downloads prebuilt toolset, "make" immediately fails with "coreclr_initialize failed 0x80131500"

I had also built coreclr myself (native on arch, mscorlib on ubuntu), as well as corefx (native on arch, managed on ubuntu), then copied over the stuff in the downloaded prebuilt toolset dir for the roslyn source.
"make" would at least continue, but "0x80131500" would pop up at points during the build of roslyn.
The roslyn issue link will be MUCH more descriptive/accurate.

**Comment by gitblit** [comment] 2016-12-07 20:50
I experience this result running `dotnet new` on Fedora 25 using the 1.1.0 release.

> Failed to initialize CoreCLR, HRESULT: 0x80131500

Here is the [console output](https://github.com/dotnet/coreclr/files/637711/console.txt), if that helps.

**Comment by tuxdna** [comment] 2017-06-09 08:08
I am also observing the same issue on Fedora 25

```
$ dotnet new console app1
Failed to initialize CoreCLR, HRESULT: 0x80131500
```

**Comment by janvorli** [comment] 2017-06-09 08:17
This error code means a managed exception happened during the initialization. @tuxdna would you be willing to run it under strace (`strace -f dotnet new console app1 > log.txt 2>&1`) and share the resulting log via gist (https://gist.github.com/)?

**Comment by tuxdna** [comment] 2017-06-09 09:43
@janvorli Thanks for your quick response. Below is the the strace output:

[log.txt](https://github.com/dotnet/coreclr/files/1063618/log.txt)


Seems like there are a bunch of ENOENT entries. I am not sure which one is causing the failure though.

**Comment by tuxdna** [comment] 2017-06-09 09:51
@janvorli Also added the same logs in this gist, with steps to reproduce on Fedora 25 - https://gist.github.com/tuxdna/0ca17677eaa7c81f661b2122cdb050af

**Comment by janvorli** [comment] 2017-06-09 14:47
@tuxdna I can see what's causing the problem. The /opt/dotnet/shared/Microsoft.NETCore.App/1.1.2/System.Globalization.Native.so fails to load since it depends on ICU libraries version 56, but they are not present on your system. The package that you have downloaded was for Fedora 24 that has ICU version 56. We don't have a dotnet 1.1.2 version for Fedora 25 that uses a newer version of ICU.
The dotnet core 2.0.0 doesn't require specific version of ICU - it can work with any version higher than 50. If it is not a problem for you, you can try the newer version preview release which should be very stable and it is close to its final release.  The installation instructions for Fedora are here: https://www.microsoft.com/net/core/preview#linuxfedora

**Comment by tuxdna** [comment] 2017-06-09 15:37
@janvorli Thanks for your pointers.

I did setup 2.x preview as per your link. It works for me, thanks!

**Comment by jeffschwMSFT** [comment] 2019-11-12 17:06
Closing as this issue seems resolved

**Closed by jeffschwMSFT** 2019-11-12 17:06 UTC
