### ISSUE TITLE
[x64] Could not find/download: ".NET Core SDK" with version = 2.1.503

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24296] opened 2019-04-29 01:09 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/illink/job/x64_checked_windows_nt_illink/710/

**Log:**
```
Could not find/download: ".NET Core SDK" with version = 2.1.503
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core 
support
At D:\j\workspace\x64_checked_w---d3ca6d42\.dotnet\dotnet-install.ps1:585 
char:5
+     throw "Could not find/download: `"$assetName`" with version = 
$SpecificVersi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : OperationStopped: (Could not find/...ET Core sup 
   port:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find/download: ".NET Core SDK" with ve 
   rsion = 2.1.503
    Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core  
   support
 
ERROR: Could not install dotnet cli correctly. 
```

**Comment by avanderhoorn** [comment] 2019-05-01 02:53
I've hit this same issue... If i go to the url it tries first and paste it into chrome it downloads just fine. Debugging it a bit, it sees like `$Response = $HttpClient.GetAsync("${Uri}${FeedCredential}").Result` is returning null for some reason... No idea why as another college tried to run it on his machine and it worked just fine.

**Comment by janvorli** [comment] 2019-05-02 14:15
I've hit this issue in the past too and in that case, even the chrome could download it (I think it returned HTTP status 404, but I am not sure). So it looks like some intermittent issue with the content delivery system.

**Comment by RussKeldorph** [comment] 2019-05-22 17:23
Duplicate of dotnet/core-eng#5754

**Closed by RussKeldorph** 2019-05-22 17:23 UTC
Labels: arch-x64, area-Infrastructure
