### ISSUE TITLE
PEVerify Source?

### ISSUE THREAD

**Issue by matty-hall** [dotnet/coreclr#2527] opened 2016-01-05 08:02 UTC
Where on earth is the source to PEVerify? In reading the ECMA spec there are often times ambiguities in the language used and I find myself wanting to go look at how PEVerify handles a given construct.  I've search the tree, but the only references I've found seem to be in Validator.cpp, which is loading "peverify.dll" dynamically.  So, where the heck is its source!?

**Comment by karelz** [comment] 2017-05-14 19:31
@RussKeldorph do we have any official info about plans? Even if we don't know when the plans will be funded, it would be nice to paint the path forward (without any commitment to dates or if it ever happens).

See another question on [gitter](https://gitter.im/dotnet/coreclr?at=5918815783cb5db0732df7ad) about the same topic.

**Comment by jkotas** [comment] 2017-05-15 01:07
The plan is to build standalone IL verifier based on CoreRT. #295 has details. There is soon going to be  project readme in CoreRT master (https://github.com/dotnet/corert/pull/3611).

**Comment by karelz** [comment] 2017-05-15 07:16
Great, thanks for info! I wonder if we should just close this issue in that case as dupe of the CoreRT effort ..

**Closed** 2017-05-15 12:21 UTC
Labels: area-ILVerification, question
