### ISSUE TITLE
[arm64/linux] regressions/Dev11/154243/dynamicmethodliveness failed in arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21269] opened 2018-11-29 02:24 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/10/#showFailuresLink

**Failed tests:**
```
GC_Scenarios._GCSimulator_GCSimulator_360_GCSimulator_360_._GCSimulator_GCSimulator_360_GCSimulator_360_sh
GC_Scenarios._GCSimulator_GCSimulator_324_GCSimulator_324_._GCSimulator_GCSimulator_324_GCSimulator_324_sh
GC_Scenarios._GCSimulator_GCSimulator_201_GCSimulator_201_._GCSimulator_GCSimulator_201_GCSimulator_201_sh
JIT_CodeGenBringUpTests._Swap_ro_Swap_ro_._Swap_ro_Swap_ro_sh
JIT_CodeGenBringUpTests._DblSubConst_ro_DblSubConst_ro_._DblSubConst_ro_DblSubConst_ro_sh
JIT_Directed._coverage_importer_stfldstatic1_il_r_stfldstatic1_il_r_._coverage_importer_stfldstatic1_il_r_stfldstatic1_il_r_sh
JIT_HardwareIntrinsics._X86_Sse3_MoveHighAndDuplicate_ro_MoveHighAndDuplicate_ro_._X86_Sse3_MoveHighAndDuplicate_ro_MoveHighAndDuplicate_ro_sh
JIT_HardwareIntrinsics._X86_Sse_StoreAlignedNonTemporal_ro_StoreAlignedNonTemporal_ro_._X86_Sse_StoreAlignedNonTemporal_ro_StoreAlignedNonTemporal_ro_sh
JIT_IL_Conformance._Old_Conformance_Base_ble_r4_ble_r4_._Old_Conformance_Base_ble_r4_ble_r4_sh
JIT_jit64._opt_cse_fieldexpr1_fieldexpr1_._opt_cse_fieldexpr1_fieldexpr1_sh
JIT_opt._Inline_tests_Inline_Inline_._Inline_tests_Inline_Inline_sh
JIT_Regression._CLR_x86_JIT_V2_0_Beta2_b309555_b309555_b309555_._CLR_x86_JIT_V2_0_Beta2_b309555_b309555_b309555_sh
JIT_Regression._CLR_x86_JIT_V1_M10_b04306_b04306_b04306_._CLR_x86_JIT_V1_M10_b04306_b04306_b04306_sh
JIT_SIMD._VectorDiv_ro_VectorDiv_ro_._VectorDiv_ro_VectorDiv_ro_sh
```

**Some filed logs:**
```
GC_Scenarios._GCSimulator_GCSimulator_360_GCSimulator_360_._GCSimulator_GCSimulator_360_GCSimulator_360_sh [FAIL]
        Test Infrastructure Failure: System.ComponentModel.Win32Exception (12): Cannot allocate memory
           at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow) in /root/corefx-2230763/src/Common/src/Interop/Unix/System.Native/Interop.ForkAndExecProcess.cs:line 44
           at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /root/corefx-2230763/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 329
           at System.Diagnostics.Process.Start() in /root/corefx-2230763/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1216
           at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile) in /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/tests/src/Common/Coreclr.TestWrapper/CoreclrTestWrapperLib.cs:line 199
           at GC_Scenarios._GCSimulator_GCSimulator_360_GCSimulator_360_._GCSimulator_GCSimulator_360_GCSimulator_360_sh() in /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/GC.Scenarios/GC.Scenarios.XUnitWrapper.cs:line 22329
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/GC.Scenarios/GC.Scenarios.XUnitWrapper.cs(22369,0): at GC_Scenarios._GCSimulator_GCSimulator_360_GCSimulator_360_._GCSimulator_GCSimulator_360_GCSimulator_360_sh()
```
GC_Scenarios._GCSimulator_GCSimulator_324_GCSimulator_324_._GCSimulator_GCSimulator_324_GCSimulator_324_sh
```
GC_Scenarios._GCSimulator_GCSimulator_324_GCSimulator_324_._GCSimulator_GCSimulator_324_GCSimulator_324_sh [FAIL]
        /n/nReturn code:      139/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/bin/tests/Linux.arm64.Checked/GC/Scenarios/Reports/GC.Scenarios/GCSimulator/GCSimulator_324/GCSimulator_324.output.txt/nRaw output:/nTest Harness Exitcode is : 139
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/bin/tests/Linux.arm64.Checked/GC/Scenarios/GCSimulator/GCSimulator_324/GCSimulator_324.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/GC.Scenarios/GC.Scenarios.XUnitWrapper.cs(19569,0): at GC_Scenarios._GCSimulator_GCSimulator_324_GCSimulator_324_._GCSimulator_GCSimulator_324_GCSimulator_324_sh()
```

```
JIT_Directed._coverage_importer_stfldstatic1_il_r_stfldstatic1_il_r_._coverage_importer_stfldstatic1_il_r_stfldstatic1_il_r_sh [FAIL]
           at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow) in /root/corefx-2230763/src/Common/src/Interop/Unix/System.Native/Interop.ForkAndExecProcess.cs:line 44
           at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /root/corefx-2230763/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 329
           at System.Diagnostics.Process.Start() in /root/corefx-2230763/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1216
           at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile) in /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/tests/src/Common/Coreclr.TestWrapper/CoreclrTestWrapperLib.cs:line 199
           at JIT_Directed._coverage_importer_stfldstatic1_il_r_stfldstatic1_il_r_._coverage_importer_stfldstatic1_il_r_stfldstatic1_il_r_sh() in /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.Directed/JIT.Directed.XUnitWrapper.cs:line 10149
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.Directed/JIT.Directed.XUnitWrapper.cs(10189,0): at JIT_Directed._coverage_importer_stfldstatic1_il_r_stfldstatic1_il_r_._coverage_importer_stfldstatic1_il_r_stfldstatic1_il_r_sh()
```

```
JIT_opt._Inline_tests_Inline_Inline_._Inline_tests_Inline_Inline_sh [FAIL]
        /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/bin/tests/Linux.arm64.Checked/JIT/opt/Inline/tests/Inline/Inline.sh: fork: Cannot allocate memory
        /n/nReturn code:      254/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/bin/tests/Linux.arm64.Checked/JIT/opt/Reports/JIT.opt/Inline/tests/Inline/Inline.output.txt/nRaw output:/nBEGIN EXECUTION
        in takeLock
        Test Harness Exitcode is : 254
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/bin/tests/Linux.arm64.Checked/JIT/opt/Inline/tests/Inline/Inline.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.opt/JIT.opt.XUnitWrapper.cs(5499,0): at JIT_opt._Inline_tests_Inline_Inline_._Inline_tests_Inline_Inline_sh()
```

**Comment by CarolEidt** [comment] 2019-01-15 00:06
Of the most recent 3 runs, 2 are clean and the most recent (https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tiered_tst/18/) has three failures:
```
baseservices_exceptions._unittests_RecursiveThrowNew_RecursiveThrowNew_._unittests_RecursiveThrowNew_RecursiveThrowNew_sh
JIT_Directed._StructPromote_SP2c_SP2c_._StructPromote_SP2c_SP2c_sh
JIT_jit64._eh_Leaves_nonlocalexitfromnestedcatch_nonlocalexitfromnestedcatch_._eh_Leaves_nonlocalexitfromnestedcatch_nonlocalexitfromnestedcatch_sh
```
All of these also have Return code 137, which I believe is the kill status. Could this be time-out or out of memory?

**Comment by RussKeldorph** [comment] 2019-01-16 21:56
Assuming duplicate of #22010.  Feel free to re-open if not.

**Closed by RussKeldorph** 2019-01-16 21:56 UTC
Labels: arch-arm64, os-linux
