### ISSUE TITLE
ReadyToRun: 7 test failures under JIT\Regression\CLR-x86-JIT with C0000005 result

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3612] opened 2016-03-09 03:12 UTC
Tests:
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b13522\b13522\b13522.exe
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b53958\b53958\b53958.exe
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b57516\b57516\b57516.exe
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b65087\b65087\b65087.exe
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b12274\b12274\b12274.exe
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b43714\b43714\b43714.exe
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b35351\b35351\b35351.exe

Repro steps:
Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

Output for the first of these tests:

BEGIN EXECUTION
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image E:\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b13522\b13522\b13522.ni.exe generated successfully.
 "E:\coreclr\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" b13522.exe  
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED

**Comment by LLITCHEV** [comment] 2016-03-10 06:43
This seems to be a duplicate of #3613 .

**Closed by LLITCHEV** 2016-03-10 06:43 UTC
Labels: bug, CodeGen, ReadyToRun
