### ISSUE TITLE
Consider creating a constructor for Span<T> to accept an IntPtr instead of a void*

### ISSUE THREAD

**Issue by Dewera** [dotnet/coreclr#27478] opened 2019-10-27 12:08 UTC
Haven't looked into the inner workings of Span<T>, so I'm not entirely sure if this is possible, however, it would be a nice addition to be able to create a Span<T> over unmanaged memory referenced via an IntPtr (say for instance, allocated with Marshal.AllocHGlobal.) This would allow developers to keep a CLS compliant codebase and not have to compile under unsafe, just to call IntPtr.ToPointer().

**Comment by jkotas** [comment] 2019-10-27 12:42
We want operations with unmanaged pointers to be explicit operation with unmanaged pointers,. We are not using IntPtr to express pointers for new APIs. 

More discussion / duplicate of https://github.com/dotnet/corefx/issues/18946.

**Closed by jkotas** 2019-10-27 12:42 UTC
