### ISSUE TITLE
[Linux/arm64] R2R JitStressRegs0x80 multipleWRs Failure

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#20991] opened 2018-11-14 01:13 UTC
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x80_tst_prtest/2/
```
[/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x80_tst_prtest/bin/tests/Linux.arm64.Checked/GC/API/WeakReference/multipleWRs/multipleWRs.sh]: 

/n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x80_tst_prtest/bin/tests/Linux.arm64.Checked/GC/API/Reports/GC.API/WeakReference/multipleWRs/multipleWRs.output.txt/nRaw output:/nTest Harness Exitcode is : 137
/nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x80_tst_prtest/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x80_tst_prtest/bin/tests/Linux.arm64.Checked/GC/API/WeakReference/multipleWRs/multipleWRs.sh/n
Expected: True
Actual:   False


Return code:      137
Raw output file:      /home
obox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x80_tst_prtest/bin/tests/Linux.arm64.Checked/GC/API/Reports/GC.API/WeakReference/multipleWRs/multipleWRs.output.txt
Raw output:
Test Harness Exitcode is : 137

To run the test:
> set CORE_ROOT=/home
obox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x80_tst_prtest/bin/tests/Linux.arm64.Checked/Tests/Core_Root
> /home
obox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x80_tst_prtest/bin/tests/Linux.arm64.Checked/GC/API/WeakReference/multipleWRs/multipleWRs.sh

Expected: True
Actual:   False
```

**Comment by RussKeldorph** [comment] 2019-01-16 21:57
Assuming duplicate of #22010.  Feel free to re-open if not.

**Closed by RussKeldorph** 2019-01-16 21:57 UTC
Labels: JitStress, arch-arm64, area-ReadyToRun, os-linux
