### ISSUE TITLE
AccessViolation inside of StubHelpers::ProcessByrefValidationList

### ISSUE THREAD

**Issue by bthomp2420** [dotnet/coreclr#3111] opened 2016-02-10 02:04 UTC
We have run our internal tools with COMPlus_InteropValidatePinnedObjects enabled for quite some time in an attempt to catch some elusive managed heap corruption related crashes.  It turns out that when we updated all of our workstations to .NET 4.6.1 over the weekend (previously 4.5.2), we began hitting wide-spread crashes inside of the following stack:

clr! 	SVR::seg_mapping_table_segment_of
clr! 	SVR::gc_heap::find_segment
clr! 	SVR::GCHeap::NextObj
clr! 	StubHelpers::ValidateObjectInternal
clr! 	StubHelpers::ProcessByrefValidationList
clr! 	CNameSpace::GcStartWork
clr! 	SVR::gc_heap::garbage_collect
clr! 	SVR::gc_heap::gc_thread_function
clr! 	SVR::gc_heap::gc_thread_stub

Digging around in the reference source, I linked that call back to the COMPlus diagnostics flag that we had been setting.  The question was whether we caught a major regression in PInvoke (unlikely) or a major regression in the COMPlus option (much more likely).

Looking inside of StubHelpers the following stands out to me:
StubHelpers::ValidateByref() - locks while adding the entries and potentially growing the buffer
ProcessByrefValidationList() - does not hold the lock guarding the entries/index (thus potentially using memory that is reallocated by another thread in a PInvoke with a ByRef parameter)

I believe there may be a newly introduced race condition in this diagnostics mode related to the optimizations in the ServerGC (background GC and ByRef optimizations).

**Comment by bthomp2420** [comment] 2016-02-10 02:41
I also posted this issue to [MSDN](https://social.msdn.microsoft.com/Forums/vstudio/en-US/9ce8a36b-d23b-4f5f-bf51-59f921f069cf/complusinteropvalidatepinnedobjects-regression-in-net-461?forum=clr)

**Comment by jkotas** [comment] 2016-02-10 03:37
@Maoni0 Looks like a bug with seg_mapping_table_segment_of that was introduced not too long ago...

**Comment by bthomp2420** [comment] 2016-02-10 06:29
Note: I don't believe it is a bug with seg_mapping_table_segment_of since the same bug manifested with an exception from ValidateObject

COR_E_EXECUTIONENGINE -- `StubHelpers::ValidateObject'::`1'::catch$1()

**Comment by bthomp2420** [comment] 2016-02-10 16:37
Update: We have deployed a change to our internal tools that disables the COMPlus_InteropValidatePinnedObjects option and are no longer seeing wide-spread crashes across our tools. (confirming that .NET 4.6.1 currently has a bug related to that option when ServerGC is enabled... disabling ServerGC also seemed to work around the crash but I don't have 100% confirmation on that)

**Comment by Maoni0** [comment] 2016-02-10 19:41
This is not a bug in seg_mapping_table_segment_of, but most likely it's something that needs to be fixed in the verification code to accommodate the new way of finding segments. I already have a bug on this but haven't fixed yet since it's only in verification code. I will make a fix soon. Of course feel free to send me a (full memory) dump so I can verify for you that this is indeed what I am thinking of :)

**Comment by bthomp2420** [comment] 2016-02-10 19:45
Unfortunately, I don't believe I can provide a minidump at this time without reproducing the bug with a contrived bug repro case.  The main point I was attempting to make is that I believe that the individual threads completing a PInvoke are able to add pointers to values passed in by-ref in parallel with the background GC thread performing verification.

There is currently no thread safety in the background GC thread by means of critical section or lockless thread-safe storage that prevents the verification code from looping over memory that is being changed/reallocated by a separate thread completing a PInvoke with a by-ref parameter.

**Comment by bthomp2420** [comment] 2016-02-10 19:46
For example, the address of an object that was passed down to seg_mapping_table_segment_of was something like 0x0000000000003ffff or something in a clearly non-addressable memory range.

**Comment by Maoni0** [comment] 2016-02-10 19:57
It has nothing to do with background GC thread safety. the verification code should not pass addresses to seg_mapping_table_segment_of that are out of the range the table covers. They should be filtered first. You don't need to have background GC enabled to repro this. The callstack you showed above was not from a background GC thread.

**Comment by bthomp2420** [comment] 2016-02-10 23:00
I am certainly not an expert though in the coreclr so I'll leave it up to you...

It still very much looks to me to be a race condition between calls to ValidateByRef and ProcessByRefValidationList considering the repro rate of this is incredibly low and it appears in nearly 100% of the crashes that 1 thread is in the middle of processing the list while another thread is in the middle or at the end of a pInvoke stub.

We are out of the woods now with this issue by disabling the validation so it is no longer impacting us at this time.  If I have some time to try and produce a standalone repro of this issue, I will let you know if I am successful.

**Comment by bthomp2420** [comment] 2016-02-12 00:36
I believe i was able to repro the exact conditions and will hopefully be able to produce a simplified version of the crash.

**Comment by bthomp2420** [comment] 2016-02-12 03:48
Okay, I have been able to repro the issue with a simplified application.  I do concede that what I am observing in the debugger appears to indicate that the critical section that is being entered is also waiting on the GC so it isn't a race condition as it appeared to be.

The main factors that seemed to trigger this:
* Must be a pinvoke with a ByRef parameter
* Cannot use MarshalAs (had to modify the DllImport signature from pinvoke.net)
* Value passed in by reference needed to be a member variable of an object (cannot be stack variable)
* Must have the COMPlus option set in registry or environment (don't just launch from debugger)

Attaching a project that is able to consistently repro the issue along with a minidump (without heap).
[PInvokeVerifyByref.zip](https://github.com/dotnet/coreclr/files/127459/PInvokeVerifyByref.zip)
[PInvokeVerifyByref.dmp.zip](https://github.com/dotnet/coreclr/files/127468/PInvokeVerifyByref.dmp.zip)

**Comment by Maoni0** [comment] 2016-09-22 22:40
this should be fixed. I ran your repro and verified that it does not repro. I am closing the issue but if this still repros for you with the current build please reactivate.

**Closed by Maoni0** 2016-09-22 22:40 UTC
Labels: bug, GC
