### ISSUE TITLE
No profile data available for file "lsraxarch.cpp"

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#13642] opened 2017-08-28 23:30 UTC
I got the following error while building x64/Linux Release CLR:
```
[ 99%] Building CXX object src/jit/standalone/CMakeFiles/clrjit.dir/__/simd.cpp.o
error: no profile data available for file "lsraxarch.cpp" [-Werror,-Wprofile-instr-unprofiled]
1 error generated.
make[4]: *** [src/jit/standalone/CMakeFiles/clrjit.dir/__/lsraxarch.cpp.o] Error 1
```

This error does not appear when ``-nopgooptimize`` option is provided.

Is there any issues within published PGO data?

**Comment by jkotas** [comment] 2017-08-29 17:21
Duplicate of #13655

**Closed by jkotas** 2017-08-29 17:21 UTC
