### ISSUE TITLE
Regression in 2.1.300: AssemblyName parsing with unicode/emoji crashes

### ISSUE THREAD

**Issue by abock** [dotnet/coreclr#18269] opened 2018-06-03 23:43 UTC
I found a regression in 2.1.300 when trying to upgrade [Xamarin Workbooks](https://github.com/Microsoft/workbooks) to `netcoreapp2.1`.

It seems that maybe (at least based on the date of the commit) [that flat layout for `GetAssemblyName`](https://github.com/dotnet/coreclr/commit/77d4c11fcd67414d2195a63287e9c8e0b6f32958#diff-8b5c082f27b55aa1d4b297f3b78309d0) cannot handle sequences of unicode/emoji characters that we are using in our Roslyn-generated script submission assemblies that represent workbook cells.

Our script submission assemblies end up with assembly names of the form<sup>1</sup>

```
🐵🐻#2faeea4e-c41b-4d38-85ea-124b4197280d-0
```

The issue can be reproduced easily:

```csharp
new AssemblyName("🐵🐻#2faeea4e-c41b-4d38-85ea-124b4197280d-0");
```

Which now results in the exception:

```
Unhandled Exception: System.IO.FileLoadException: The given assembly name or codebase was
invalid. (Exception from HRESULT: 0x80131047)
  at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean raiseResolve
Event)
  at System.Reflection.AssemblyName..ctor(String assemblyName)
…
```

It may be important to note that each of the emoji here are four UTF-16 bytes (this is significant in our code for patching), and the exception only seems to occur when there are at least two emoji in a string that is more than >= 20 UTF-16 bytes.

## Simple Test Case

Run the follow program against `netcoreapp2.0` (2.1.4 in `global.json`) and `netcoreapp2.1` (2.1.300 in `global.json`).

```csharp
using System;
using System.Reflection;
using System.Text;

class Program
{
    static void Main(string[] args)
    {
        string str = null;
        for (int i = 0; i < 5; i++) {
            str += "🐻";
            Console.WriteLine ($"String:      {str} ({str.Length})");
            Console.WriteLine ($"UTF-16 Size: {Encoding.Unicode.GetByteCount(str)}");
            try {
                new AssemblyName (str);
                Console.WriteLine ("OK");
                Console.WriteLine ();
            } catch {
                Console.WriteLine ("FAIL");
                throw;
            }
        }
    }
}
```

### Output in 2.1.4 / `netcoreapp2.0`

```
String:      🐻 (2)
UTF-16 Size: 4
OK

String:      🐻🐻 (4)
UTF-16 Size: 8
OK

String:      🐻🐻🐻 (6)
UTF-16 Size: 12
OK

String:      🐻🐻🐻🐻 (8)
UTF-16 Size: 16
OK

String:      🐻🐻🐻🐻🐻 (10)
UTF-16 Size: 20
OK
```

### Output in 2.1.300 / `netcoreapp2.1`

```
String:      🐻 (2)
UTF-16 Size: 4
OK

String:      🐻🐻 (4)
UTF-16 Size: 8
OK

String:      🐻🐻🐻 (6)
UTF-16 Size: 12
OK

String:      🐻🐻🐻🐻 (8)
UTF-16 Size: 16
OK

String:      🐻🐻🐻🐻🐻 (10)
UTF-16 Size: 20
FAIL

Unhandled Exception: System.IO.FileLoadException: The given assembly name or codebase wasinvalid. (Exception from HRESULT: 0x80131047)
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean raiseResolveEvent)
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at Program.Main(String[] args) in /Users/aaron/Desktop/emoji/Program.cs:line 15
```

_1. If you're interested in _why_ we have assembly names with this particular sequence of emoji, feel free to ask!_

**Comment by jkotas** [comment] 2018-06-04 00:10
Likely introduced by https://github.com/dotnet/coreclr/pull/17302

cc @luqunl

**Comment by Aniel** [comment] 2018-06-04 16:14
@abock So why do you have this particular sequence of emoji in your assembly names?

**Comment by luqunl** [comment] 2018-06-04 17:14
@abock, @jkotas , do you know how to find this version 2.1.300? I tried to use 2.1 RTM which contains  #17302 and couldn't repro this issue.

**in project file, I added,**
_<RuntimeFrameworkVersion>2.1.0</RuntimeFrameworkVersion>_

**in windbg, coreclr shows:**

_ProductVersion:   4.6.26515.07 @BuiltBy: dlab-DDVSOWINAGE059 @Branch: release/2.1 @SrcCode: https://github.com/dotnet/coreclr/tree/d9d6f990a3737e221294b41a579afba0c4f7f9c4_

**Output:**
_String:      ?????????? (10)
UTF-16 Size: 20_
OK

**Comment by jkotas** [comment] 2018-06-04 17:40
@luqunl Are you running this on Linux? #17302 was Linux specific fix.

**Comment by luqunl** [comment] 2018-06-04 18:05
oop.. let me try to run it in Linux

**Comment by abock** [comment] 2018-06-04 18:10
I was on macOS 10.13.

**Comment by luqunl** [comment] 2018-06-05 00:28
Update: This regression isn't related to my change and it is caused by https://github.com/dotnet/coreclr/commit/eef4ca509b156597cea92d689672dacbac2cb7e1#diff-21977054d4f6caedbcc3080c4b5b5d39

**Comment by danmosemsft** [comment] 2018-06-05 02:42
@RussKeldorph runtime servicing candidate

**Comment by jkotas** [comment] 2018-06-05 14:23
Keep open for servicing consider

**Comment by danmosemsft** [comment] 2018-07-17 16:23
@luqunl @RussKeldorph this appears already fixed in https://github.com/dotnet/coreclr/pull/18309 so I am closing this.

**Closed by danmosemsft** 2018-07-17 16:23 UTC
Labels: Servicing-Consider-2.1.next, area-AssemblyLoader, bug
