### ISSUE TITLE
Disable CER feature as it is not used

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#7526] opened 2016-10-07 20:38 UTC
And can create issues like https://github.com/dotnet/coreclr/pull/7524/files.

We should see if we can get this done for 1.1.0 RTM.

CC @jkotas

**Comment by DemiMarie** [comment] 2016-10-11 07:28
It seems like this would impair the CLR's robustness under certain conditions.  Is there a reason that it is not worth it to fix these bugs?  Are CERs really only for being hosted under SQL Server?

**Comment by jkotas** [comment] 2016-10-11 11:44
CERs really only guarantee that there will be no spurious out of memory exception due to JIT compilation; and they require library writers to annotate their code. We have found that it is incredibly hard to library writers to annotate libraries with CER annotations correctly. We have not found how to do it well in scale with 100% correctness.

Alternative solution for CERs is full AOT compilation, such as what we are building in [CoreRT](github.com/dotnet/corert/) project. It also guarantees that there is no spurious out of memory exception due to JIT compilation (by design - because of there is not JIT at runtime); and it does not require library writers to provide any annotations. If somebody needs the kind of guarantees that are provided by CERs with .NET Core, our recommendation will be to use full AOT compilation.

**Comment by gkhanna79** [comment] 2016-10-25 16:31
This was optimistic for 1.1.0, so moving to 1.2.0.

@JohnChen0 We should look into cleaning it up for 1.2.0.

**Comment by JohnChen0** [comment] 2016-11-29 20:50
Fixed with PR #8218.

**Closed by JohnChen0** 2016-11-29 20:50 UTC
Labels: area-VM
