### ISSUE TITLE
Assert failure(PID 51988 [0x0000cb14], Thread: 14588 [0x38fc]): Postcondition failure: FAILED: UnsafeVerifyLookupAssembly(this, pSpec, pAssembly)

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/coreclr#7801] opened 2016-10-25 19:31 UTC
When running the System.Runtime.Tests from CoreFx on a Debug CoreCLR, you see this assert.

Assert failure(PID 51988 [0x0000cb14], Thread: 14588 [0x38fc]): Postcondition failure: FAILED: UnsafeVerifyLookupAssembly(this, pSpec, pAssembly)

  CORECLR! CHECK::Trigger + 0x26A (0x00007ffd`2bb4ce1a)
  CORECLR! AssemblySpecBindingCache::StoreAssembly + 0x57D (0x00007ffd`2c0e63fd)
  CORECLR! AppDomain::AddAssemblyToCache + 0x533 (0x00007ffd`2bf709f3)
  CORECLR! AppDomain::LoadDomainAssemblyInternal + 0xA6E (0x00007ffd`2bfa090e)
  CORECLR! AppDomain::LoadDomainAssembly + 0xE8 (0x00007ffd`2bf9fe38)
  CORECLR! AssemblySpec::LoadDomainAssembly + 0x8CB (0x00007ffd`2c0e26fb)
  CORECLR! AssemblySpec::LoadAssembly + 0x17B (0x00007ffd`2c0e14ab)
  CORECLR! AssemblyNative::Load + 0x8A5 (0x00007ffd`2c56f9a5)
  SYSTEM.PRIVATE.CORELIB.NI! <no symbol> + 0x0 (0x00007ffd`2b13aed4)
  SYSTEM.PRIVATE.CORELIB.NI! <no symbol> + 0x0 (0x00007ffd`2b13ad44)
      File: d:\code\github\coreclr\src\vm\assemblyspec.cpp Line: 2095
      Image: D:\code\gitHub\corefx\bin\tests\AnyOS.AnyCPU.Debug\System.Runtime.Tests\default.netcoreapp1.1\netcoreapp1.1\CoreRun.exe

**Comment by gkhanna79** [comment] 2016-10-25 20:18
@rahku Can you PTAL?

**Comment by danmosemsft** [comment] 2016-11-02 23:42
Dupe of https://github.com/dotnet/coreclr/issues/5721 (I get it also)

**Closed by danmosemsft** 2016-11-02 23:42 UTC
Labels: Assembly Loader, bug
