### ISSUE TITLE
String.StartsWith/EndsWith/IndexOf/LastIndexOf ignoring null characters on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#2051] opened 2015-11-15 13:18 UTC
For example, this:

``` C#
Console.WriteLine("abcte\0\0\0\0\0st".EndsWith("test"));
```

prints out true.

**Comment by AlexGhiondea** [comment] 2017-02-02 05:54
@tarekgh would you mind taking a look at this?

**Comment by tarekgh** [comment] 2017-02-02 16:23
I believe this is by design in Linux as Linux ignore the null characters. i.e. null characters has no weights for the string comparison. if someone want to to have accurate result should use ordinal comparisons and not linguistic comparison. I understand this is different than Windows but we already have some differences between Windows and Linux in this space.

**Comment by AlexGhiondea** [comment] 2017-02-02 18:17
Closing per @tarekgh's comments

**Comment by Jiayili1** [comment] 2017-02-24 06:54
Disabled test, reopen it.

**Comment by Jiayili1** [comment] 2017-02-27 01:43
https://github.com/dotnet/corefx/blob/master/src/System.Runtime/tests/System/StringTests.cs#L835

**Comment by tarekgh** [comment] 2017-02-27 16:59
@AlexGhiondea I have marked this as a test issue and moved it to the future. please change it back if you think otherwise.

**Comment by GrabYourPitchforks** [comment] 2020-01-29 02:50
@tarekgh Can this be closed? I confirmed that the null character is a weightless character in ICU.

```cpp
auto status = UErrorCode{};
UCollator* collator = ucol_open("", &status);

uint8_t sortKey[64];
auto result = ucol_getSortKey(
	collator,
	(UChar*)L"ab\0cd",
	5,
	sortKey,
	sizeof(sortKey));

result = ucol_getSortKey(
	collator,
	(UChar*)L"abcd",
	4,
	sortKey,
	sizeof(sortKey));
```

The two calls above will return the same value for `result` and will both populate `sortKey` with the same data. This indicates that per ICU the strings `"ab\0cd"` and `"abcd"` are equal.

**Comment by tarekgh** [comment] 2020-01-29 16:01
@GrabYourPitchforks I am closing it. I assume there is no test failing because of that today.

**Closed by tarekgh** 2020-01-29 16:01 UTC
Labels: area-System.Globalization, disabled-test, os-linux, test bug
