### ISSUE TITLE
Encoding.UTF8.GetString() when running in Docker is broken

### ISSUE THREAD

**Issue by ulfendk** [dotnet/coreclr#10898] opened 2017-04-11 19:37 UTC
With a fresh ASP .NET Core project created using `dotnet new mvc` and later opened in VS2017, from where I added Docker support (all packages are the latest - mostly v1.1.1).

Calling a RESTful endpoint which returns UTF-8, the following code works, when launched via IISExpress but not via Docker (the `docker-compose` project in VS2017).

It does not decode e.g. `ø` (195 184) correctly - instead it is decoded as `Ã¸`.

```csharp
using (var client = new HttpClient())
{
    var response = await client.GetAsync("...");
    byte[] bytes = await response.Content.ReadAsByteArrayAsync();
    string decodedString = Encoding.UTF8.GetString(bytes);
}
```

**Comment by danmosemsft** [comment] 2017-04-13 04:18
@tarekgh thoughts? 2.0?

**Comment by tarekgh** [comment] 2017-04-13 15:40
I don't think this is Encoding issue as it returns the correct results when using RESTfull. we have just one codebase so as long as the input is same we should get the same output. 


@ulfendk, could you please check the bytes returned from 

```C#
byte[] bytes = await response.Content.ReadAsByteArrayAsync();
```

and tell me if you are getting exactly same results when using RESTful or when using docker-compose?

**Comment by tarekgh** [comment] 2017-04-13 16:12
@ulfendk could you also share a sample Docker-compose project repro the issue?

**Comment by danmosemsft** [comment] 2017-04-13 17:41
@MichaelSimons you are famliar with our behavior in Docker. Any thoughts?

**Comment by MichaelSimons** [comment] 2017-04-13 19:18
I sent @tarekgh a test project that illustrates the issue.  I was not able to reproduce this will a simple .NET Core app inside the microsoft/dotnet:1.1-sdk image.

**Comment by tarekgh** [comment] 2017-04-13 22:12
Finally with the help with @MichaelSimons I am able to repro the issue. the Encoding is working fine. The problem is in VS how it display the string in the local/watch window. There is no real issue with the Encoding as the string decoded correctly. 

I am attaching the project here so VS team may be able to take a look.
[WebApplication1.zip](https://github.com/dotnet/coreclr/files/920997/WebApplication1.zip)

set a breaking point on the controller method handling the About and then look at the string returned from Encoding.UTF8.GetString

**Comment by tarekgh** [comment] 2017-04-13 22:25
I have reported the issue to VS here https://developercommunity.visualstudio.com/content/problem/44197/vs-display-string-incorrectly-in-the-localwatch-de.html 

I am closing the issue here. please let me know if you have any question

**Closed by tarekgh** 2017-04-13 22:25 UTC
Labels: area-System.Runtime
