### ISSUE TITLE
error CS0103: The name 'InnerExceptionCount' does not exist in the current context System.Exception {System.AggregateException}

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/coreclr#10557] opened 2017-03-29 15:34 UTC
I'm seeing this error when debugging an ASP.Net CORE app that is making some EF Core calls.

![image](https://cloud.githubusercontent.com/assets/14079228/24463061/ad4d8cbc-1473-11e7-85a1-cee8c291f35c.png)

**Comment by gkhanna79** [comment] 2017-03-30 02:30
@gregg-miskelly PTAL and route it.

**Comment by gregg-miskelly** [comment] 2017-03-30 03:10
This is a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/1006

**Closed by gregg-miskelly** 2017-03-30 03:10 UTC
Labels: FollowingUp
