### ISSUE TITLE
Using ThreadStatic buffers in Stream.Read and WriteByte

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#1494] opened 2015-09-04 18:06 UTC
At the moment, the default implementation of `ReadByte` [allocates a new buffer](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L739) every time it's called, which may not be immediately obvious to end users. Would it be possible to instead have a thread-static buffer that could be reused, like so

``` csharp
class Stream
{
    [ThreadStatic]
    static readonly byte[] s_oneByteBuffer = new byte[1];

    int ReadByte()
    {
        int r = Read(s_oneByteBuffer, 0, 1);
        if (r == 0) return -1;
        return s_oneByteBuffer[0];
    }
}
```

Same goes for `WriteByte`?

**Comment by antiufo** [comment] 2015-09-06 17:42
Wow, I always assumed that ReadByte was a fast, allocation-free method, while it's actually not.
What's worse is that some Stream implementations (eg. FileStream) override that method, while others don't (eg. NetworkStream).
I'd now feel a bit reluctant to write methods that use ReadByte on externally-provided Streams.
Can we get an allocation-free default implementation?

**Comment by mikedn** [comment] 2015-09-08 07:18
Do you have an actual example where your application's GC time is negatively impacted by that allocation? `ThreadStatic` fields are slow, slower than simply allocating the array. At least when tested in isolation, without any other code that also allocates memory, this version is slower.

The proper fix is for streams to override these methods. Even then, if you care about performance you'd avoid using these methods because no matter what you do you end up with more work per read/written byte.

**Comment by ayende** [comment] 2015-09-08 09:32
Consider something like Lucene.
It calls ReadByte millions of times. That can generate a lot of pressure.

In general, a lot of stuff inside Stream is done a default, not necessarily
optimized fashion.
It make it easy to implement, but can lead to inefficient usage.

For example:
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/Stream.cs#L218

Here we allocate an 80Kb(!) buffer, which make using CopyTo or CopyToAsync
really expensive. And there is no way to pass our own buffer.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by mikedn** [comment] 2015-09-08 10:07
> Consider something like Lucene. It calls ReadByte millions of times. That can generate a lot of pressure

Is there something that prevents Lucene from using Read instead of ReadByte? Reading one byte at a time is not exactly the most efficient way to do things and I would expect that code that's supposed to be efficient doesn't use ReadByte unless there's no other way. It's really a convenience feature and most of the time convenience and performance don't see eye to eye.

Besides, if Lucene uses ReadByte on file streams then this doesn't affect it as FileStream does override ReadByte. If other stream types do not override ReadByte then its those streams that should be fixed as doing so provides better performance.

**Comment by ayende** [comment] 2015-09-08 11:10
It is doing its own buffering (which is another issue, because then you
have many many buffers).
It uses 7 bits numbers, so reading one byte at a time makes a lot more
sense.
And the problem is that you don't _know_ that you have this problem,
because you don't need to implement ReadByte, it is done for you

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by mikedn** [comment] 2015-09-08 17:09
@ayende

> It is doing its own buffering (which is another issue, because then you have many many buffers).

I would guess that it doesn't do that by using ReadByte so it's unclear how is that related to this issue.

> It uses 7 bits numbers, so reading one byte at a time makes a lot more sense.

From a convenience point of view maybe, from a performance point of view never.

> And the problem is that you don't _know_ that you have this problem, because you don't need to implement ReadByte, it is done for you

As far as I'm concerned I know I don't have this problem because I don't use ReadByte in performance sensitive code. Of course, the same argument can be used to justify replacing the existing implementation with a potentially slower implementation but then the question is: what does this change actually improve?

@antiufo 

> What's worse is that some Stream implementations (eg. FileStream) override that method, while others don't (eg. NetworkStream).

It turns out that there's a good reason why NetworkStream doesn't override ReadByte - it doesn't do buffering like FileStream does and any Read call ends up doing a  Socket.Receive call. Incidentally this makes the proposed optimization interesting for NetworkStream because it avoids pinning a recently allocated object.

**Comment by kevingosse** [comment] 2017-09-15 06:58
I just got bitten by this. I replaced a stream in some code with a custom implementation, and multiplied the allocations per 6... Thankfully that was caught early on in performance tests.

I understand that it's just a small issue (because you just have to override the method, assuming you know it's not efficient), and that back at the time there was no convenient fix. But now that we have the `ArrayPool`, maybe we could use it there?

**Comment by mikedn** [comment] 2017-09-15 07:44
> I just got bitten by this. I replaced a stream in some code with a custom implementation, and multiplied the allocations per 6... Thankfully that was caught early on in performance tests.

The problem is not that you replaced the stream, the problem is that someone was using ReadByte in the first place.

> I understand that it's just a small issue (because you just have to override the method, assuming you know it's not efficient), and that back at the time there was no convenient fix. But now that we have the ArrayPool, maybe we could use it there?

It should probably be updated to call the `Read(Span<byte>)` overload with a span referencing a local byte. Either it may turn out that it's slower than just allocating an array so in scenarios where those allocations do not cause GC issues this may very well be a deoptimization.

**Closed** 2019-05-23 19:42 UTC
Labels: area-System.IO, enhancement
