### ISSUE TITLE
[x86] error MSB3030 in x86_checked_windows_nt_corefx_baseline

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23016] opened 2019-03-05 01:03 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/760/

**Log:**
```
error MSB3030: Could not copy the file "D:\j\workspace\x86_checked_w---fbe14ed2\_\fx\artifacts\ibc\optimization.windows_nt-x64.IBC.CoreFx\data\System.Runtime.InteropServices.RuntimeInformation\System.Runtime.InteropServices.RuntimeInformation.dll\System.Runtime.InteropServices.RuntimeInformation.dll" because it was not found. [D:\j\workspace\x86_checked_w---fbe14ed2\_\fx\src\System.Runtime.InteropServices.RuntimeInformation\src\System.Runtime.InteropServices.RuntimeInformation.csproj]
```

**Comment by BruceForstall** [comment] 2019-03-05 14:39
@danmosemsft Looks like a recent corefx build failure regression. Any ideas?

**Comment by danmosemsft** [comment] 2019-03-05 15:11
@adiaaida ?

**Comment by adiaaida** [comment] 2019-03-05 17:26
Looking into it. It looks like the arcade codeOptimization target is building the path to the dll/ibc file in an unexpected way.

**Comment by adiaaida** [comment] 2019-03-05 17:31
@tmat did we really intend the path to IBC data to be OptimizationDir\**\assemblyname.assemblyextension\*.ibc like we have here

https://github.com/dotnet/arcade/blob/2e59efaa4fc03429fa58e51363309e999c9440ef/src/Microsoft.DotNet.Arcade.Sdk/tools/OptimizationData.targets#L80

I was told it was just OptimizationDir\**\assemblyname\*.ibc. I can easily change the directory structure, I just want to make sure that we really want it that way.

@danmosemsft @BruceForstall We'll either want to change the arcade target or how we build the directory structure in the collection phase. Either change will probably come in tomorrow/next time Maestro updates the repo.

**Comment by BruceForstall** [comment] 2019-03-06 16:06
@adiaaida Any update on this?

**Comment by adiaaida** [comment] 2019-03-06 17:05
I was hoping to hear back from @tmat, but since he hasn't responded, I'll just update the package creation side.

**Comment by tmat** [comment] 2019-03-06 17:11
`OptimizationDir\**\assemblyname.assemblyextension\*.ibc` is how it's intended.

**Comment by adiaaida** [comment] 2019-03-06 17:35
Sounds good. I've got [this PR](https://dev.azure.com/dnceng/internal/_git/dotnet-optimization/pullrequest/588?_a=overview) out for the optimization repo change. Waiting for @brianrob to approve.

**Comment by adiaaida** [comment] 2019-03-06 17:37
I'll be honest, I'm also a little surprised we are seeing this here, as I didn't think these jobs pulled down IBCMerge in the first place. Without IBCMerge, the copy step shouldn't even be triggered, unless I'm missing something.

**Comment by adiaaida** [comment] 2019-03-06 18:32
Change has been checked in. Once the CI is done we will have new packages with the correct directory structure.

Put out https://github.com/dotnet/coreclr/pull/23063 to update coreclr code to match since we don't yet use arcade for this in coreclr yet.

**Comment by sandreenko** [comment] 2019-03-07 19:53
The last run of CoreFX Windows x86 failed (two hours ago), do we need something expect #23063 and #23076?

I still don't understand why we see:
`D:\j\workspace\x86_checked_w---fbe14ed2\_\fx\artifacts\ibc\optimization.windows_nt-x64.IBC.CoreFx\data\System.Runtime.InteropServices.RuntimeInformation\System.Runtime.InteropServices.RuntimeInformation.dll\System.Runtime.InteropServices.RuntimeInformation.dll was not found `

when above in the log we see how this file was created:
`  C:\Users\dotnet-bot\.nuget\packages\optimization.windows_nt-x64.ibc.corefx\99.99.99-master-20190227.1\data\System.Runtime.InteropServices.RuntimeInformation\System.Runtime.InteropServices.RuntimeInformation.dll (optimization.windows_nt-x64.IBC.CoreFx.99.99.99-master-20190227.1) -> D:\j\workspace\x86_checked_w---fbe14ed2\_\fx\artifacts\ibc\optimization.windows_nt-x64.IBC.CoreFx\data\System.Runtime.InteropServices.RuntimeInformation\System.Runtime.InteropServices.RuntimeInformation.dll\System.Runtime.InteropServices.RuntimeInformation.dll`

How does it disapear?

**Comment by adiaaida** [comment] 2019-03-07 21:50
The dependencies haven't been updated in corefx

**Comment by adiaaida** [comment] 2019-03-08 18:07
@sandreenko I'm very confused by this failure as well, because EnablePartialNgenOptimization should be false in this case, since it's not an official build and _LocateIbcMerge should set _RunIbcMerge to false. There is no way that these runs have access to IBCMerge, and the logs don't suggest that they've been pulled down, so none of the IBC handling code should be triggered. I would suggest that this is a bug in corefx, except they aren't seeing these kinds of failures in their builds. This does not appear to be a problem with the actual IBC data collection, though, so someone on the corefx side of things should probably take a look.

**Comment by BruceForstall** [comment] 2019-03-11 20:39
@adiaaida @danmosemsft @ericstj Our corefx test runs in coreclr CI are still all failing due to this problem. Is someone actively investigating this?

**Comment by ericstj** [comment] 2019-03-12 00:02
@adiaaida The way that the current arcade targets are set up is that they do everything short of running IBCMerge when its not available, just instead of running the command it will log a failure.  Observe the different conditions [here](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/OptimizationData.targets#L157-L163)

It looks to me like this build previously made it past the point of this failure: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/755/
So it isn't something specific to consuming the optimization data, but perhaps some other factor.

I noticed that there are other assemblies which build successfully and have IBC data.  I noticed that this particular assembly has a path that is 260 characters long: D:\j\workspace\x86_checked_w---fbe14ed2\_\fx\artifacts\ibc\optimization.windows_nt-x64.IBC.CoreFx\data\System.Runtime.InteropServices.RuntimeInformation\System.Runtime.InteropServices.RuntimeInformation.dll\System.Runtime.InteropServices.RuntimeInformation.dll

I suspect we're hitting max_path here.  If I contrast to the passing build, it only had a path that was 211 characters long.  The extra length came from the path changes @adiaaida made without undoing the workaround I put in place to make the package follow arcade's conventions.

Why not use a shallower path for corefx?   By choosing to use a path this deep you put yourself on the leading edge for max_path issues which I don't expect you care to troubleshoot.  Choose a path that equal-to-or-less than our CIs and official builds and you won't have to worry about it...

**Comment by ericstj** [comment] 2019-03-14 20:34
https://github.com/dotnet/corefx/pull/35997 should have fixed this.

**Comment by sandreenko** [comment] 2019-03-14 20:36
Fixed by https://github.com/dotnet/corefx/pull/35997. Thanks @ericstj, @adiaaida.

**Closed by sandreenko** 2019-03-14 20:36 UTC
Labels: arch-x86, os-windows, test-corefx

**Comment by BruceForstall** [comment] 2019-03-14 20:41
A job I kicked off with the fix (https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/801/) actually passed, so it looks like we're back in business.
