### ISSUE TITLE
x64 JIT stack-spilled call parameter lifetime bug

### ISSUE THREAD

**Issue by cosborne83** [dotnet/coreclr#19651] opened 2018-08-24 13:04 UTC
In the x64 JIT (FileVer output for clrjit.dll: `--a-- W32 DLL ENU 4.7.3130.0 shp 1,224,336 06-05-2018 clrjit.dll`), the GC info for stack-spilled method call parameters is incorrect (lifetime ends too early) when followed by a parameter that is the result of an inline array access when in debug mode.

Repro code:

    public void Repro(int p1, object p2, object p3, object p4, object[] p5)
    {
        // Incorrect GC Info generated for this call
        ReproHelper(p1, p2, p3, p4, p5[p1]);
    }

    public void ReproHelper(int p1, object p2, object p3, object p4, object p5)
    {
        Console.WriteLine(p1);
        Console.WriteLine(p2);
        Console.WriteLine(p3);
        Console.WriteLine(p4);
        Console.WriteLine(p5);
    }

The generated assembly for the call to `ReproHelper()` in the `Repro()` method with associated GC info is as follows:

    Untracked: +rbp+38 +rbp+30

    ...
    +28 488b4d30        mov     rcx,qword ptr [rbp+30h]
        +rcx
    +2c 48894c2420      mov     qword ptr [rsp+20h],rcx
        +sp+20
    +31 8b4d18          mov     ecx,dword ptr [rbp+18h]
        -rcx
    +34 488b5538        mov     rdx,qword ptr [rbp+38h]
        +rdx
    +38 483b4a08        cmp     rcx,qword ptr [rdx+8]
    +3c 7205            jb      +43
    +3e e85d1eaa5f      call    clr!JIT_RngChkFail
        -sp+20
    +43 488d54ca10      lea     rdx,[rdx+rcx*8+10h]
        -rdx +rdx(interior)
    +48 488b0a          mov     rcx,qword ptr [rdx]
        +rcx
    +4b 48894c2428      mov     qword ptr [rsp+28h],rcx
        +sp+28
    +50 488b4d10        mov     rcx,qword ptr [rbp+10h]
    +54 8b5518          mov     edx,dword ptr [rbp+18h]
        -rdx(interior)
    +57 4c8b4520        mov     r8,qword ptr [rbp+20h]
        +r8
    +5b 4c8b4d28        mov     r9,qword ptr [rbp+28h]
        +r9
    +5f e8b4f6ffff      call    ReproHelper(Int32, System.Object, System.Object, System.Object, System.Object)
        -sp+28 -r9 -r8 -rcx
    ...

Parameter 4 to `ReproHelper()` is loaded onto the stack at `+2c` and this stack entry is correctly marked as live in the GC info (`+sp+20`).

However after the array index range check is performed prior to loading parameter 5 onto the stack, parameter 4's stack entry is incorrectly marked as dead at `+43` (`-sp+20`).

If a GC occurs between this point, and the eventual call to `ReproHelper()` at `+5f`, and that GC results in the object being passed as parameter 4 being relocated, the stack entry at `rsp+20` will not be updated with the object's new address, and `ReproHelper()` will be passed an invalid object address for parameter 4.

**Comment by cosborne83** [comment] 2018-08-24 15:28
@jkotas Since this bug affects the JIT included in the main .NET Framework, does it need to be reported elsewhere (MS Developer Community?) also?

**Comment by briansull** [comment] 2018-08-30 20:38
THis issue is a duplicate of 
Fix GH Issue 16892 - GC hole due to GT_INDEX_ADDR #1692

**Comment by briansull** [comment] 2018-10-01 21:58
This is fixed in the next Desktop CLR 4.8

**Closed by briansull** 2018-10-01 21:58 UTC
Labels: area-CodeGen, bug
