### ISSUE TITLE
Multidimensional arrays of enums behaving unexpectedly in 32 bit JIT

### ISSUE THREAD

**Issue by jaredpar** [dotnet/coreclr#5017] opened 2016-05-17 17:03 UTC
Consider the following code:

``` csharp
class Program
{
    enum State : short { OK = 0, BUG = -1 }
    static void Main(string[] args)
    {
        var s = new State[1, 1];
        s[0, 0] = State.BUG;
        Test(s, State.BUG);
    }

    static void Test(State[,] s, State a)
    { 
        bool b = (a == s[0, 0]);
        Console.WriteLine(b);
    }
}
```

The expectation of this code is that it should print out `True` yet it prints out `False`.  The IL the compiler emits for this method appears to be correct and is the same in Roslyn and pre-Roslyn compilers:

``` il
IL_0000: nop
IL_0001: ldarg.1
IL_0002: ldarg.0
IL_0003: ldc.i4.0
IL_0004: ldc.i4.0
IL_0005: call instance valuetype ConsoleApplication68.Program/State valuetype ConsoleApplication68.Program/State[0..., 0...]::Get(int32, int32)
IL_000a: ceq
IL_000c: stloc.0
IL_000d: ldloc.0
IL_000e: call void [mscorlib]System.Console::WriteLine(bool)
IL_0013: nop
IL_0014: ret
```

Further experimentation hints that this is a 32 bit JIT issue.  The bug does not repro under RyuJIT (debug or release) or 32 JIT release mode.  

Other interesting items of note.  Storing the value into a temp yields the expected result of `True`:

``` csharp
    static void Test(State[,] s, State a)
    {
        State temp = s[0, 0];
        bool b = (a == temp);
        Console.WriteLine(b);  // True
    }
```

Additionally using `int` as the base type of the enum instead of `short` also yields `True`.  

``` csharp
enum State : int { ... } 
``` 

Couple of notes:

- The `Test` method doesn't need to exist.  The comparison can be done inline in `Main`.  Having it as a separate method just isolated the IL in question. 
- I dug through the CLI spec a bit looking for clarification on the expected behavior here and wasn't able to find anything definitive.  It's possible I just passed it.

**Comment by mikedn** [comment] 2016-05-17 19:16
Looks like a duplicate of #4805

**Comment by RussKeldorph** [comment] 2016-05-18 14:15
@mikedn I concur.  @rahku, yours to close.

**Comment by rahku** [comment] 2016-05-19 00:58
yes this is same as #4805. This has been fixed in .net core. Will be fixed in next update for desktop .net.

**Closed by rahku** 2016-05-19 00:58 UTC
Labels: VM
