### ISSUE TITLE
GcStress: Failure in _relrotarg_valref Linux

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2761] opened 2016-01-21 00:32 UTC
This failure is not 100% deterministic, but fails 90% of the time under GcStress, always passes without GcStress.

```
corerun JIT/Methodical/explicit/rotate/_relrotarg_valref/_relrotarg_valref.exe
left weight do not match.

Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at Rotate.App.Node.rotateTree(Weight& leftWeight, Weight& rightWeight)
   at Rotate.App.Main()
/home/swaroops/bin/runn: line 3: 18235 Aborted                 (core dumped) 
```
```
Returns134
```

Repro steps are:
* cp \scratch2\scratch\swaroops\coredistools\libcoredistools.so somewhere
* export LD_LIBRARY_PATH=somewhere
* export COMPlus_GCStress=0xC
* Run the above test

**Comment by sivarv** [comment] 2016-01-21 18:38
This test is calling GC.Collect() explicitly and then makes a couple of checks.  Throws an exception if any of the checks fail.  Needs investigation.

**Comment by swaroop-sridhar** [comment] 2016-01-25 21:17
Similar failure in JIT/Methodical/explicit/rotate/_dbgrotarg_valref/_dbgrotarg_valref

```

FAILED   - JIT/Methodical/explicit/rotate/_dbgrotarg_valref/_dbgrotarg_valref.sh
               BEGIN EXECUTION
               /home/swaroops/test/Tests/coreoverlay/corerun _dbgrotarg_valref.exe
               right weight do not match.
               
               Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
                  at Rotate.App.Node.rotateTree(Weight& leftWeight, Weight& rightWeight)
                  at Rotate.App.Main()
               ./_dbgrotarg_valref.sh: line 55: 18889 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" _dbgrotarg_valref.exe $CLRTestExecutionArguments $Host_Args
               Expected: 100
               Actual: 134
               END EXECUTION – FAILED
```

**Comment by sivarv** [comment] 2016-01-27 23:54
This is a duplicate of issue #2763

**Closed by sivarv** 2016-01-27 23:54 UTC
Labels: bug, CodeGen, GCStress, Linux, non-deterministic
