### ISSUE TITLE
Test failed: JIT_Methodical._Coverage_arglist_pos_arglist_pos_._Coverage_arglist_pos_arglist_pos_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25417] opened 2019-06-26 02:28 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-ci/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190625.38/workItem/JIT.Methodical.a-dA-D/analysis/xunit/JIT_Methodical._Coverage_arglist_pos_arglist_pos_~2F_Coverage_arglist_pos_arglist_pos_cmd

**Failed tests**
JIT_Methodical._Coverage_arglist_pos_arglist_pos_._Coverage_arglist_pos_arglist_pos_cmd

**Log:**
```
Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\d28c28d5-869b-4265-a869-520341503029\\Exec\\JIT\\Methodical\\Reports\\JIT.Methodical\\Coverage\\arglist_pos\\arglist_pos.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload\\corerun.exe\" arglist_pos.exe 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload
> C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\d28c28d5-869b-4265-a869-520341503029\\Exec\\JIT\\Methodical\\Coverage\\arglist_pos\\arglist_pos.cmd
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment] 2019-06-26 16:28
https://github.com/dotnet/coreclr/pull/25429

**Comment by RussKeldorph** [comment] 2019-06-26 23:57
Assuming duplicate of #25376

**Closed by RussKeldorph** 2019-06-26 23:57 UTC
Labels: arch-arm32, os-windows
