### ISSUE TITLE
Some BenchmarksGame tests timing out in CI in release/1.1.0 branch

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#14191] opened 2017-09-26 16:04 UTC
See https://github.com/dotnet/coreclr/pull/14094#issuecomment-331007243 and https://github.com/dotnet/coreclr/pull/14094#issuecomment-331568436 -- these timeouts did not repro for me locally, hence this issue to investigate and I'll check the tests in with exclusions

**Comment by AndyAyersMS** [comment] 2018-01-24 01:29
@jorive is this still an issue? Seems like we probably don't care all that much even if so?

**Comment by jorive** [comment] 2018-01-30 23:49
@JosephTremoulet Did you check why these benchmarks were timing out in the lab machines?

**Comment by JosephTremoulet** [comment] 2018-01-31 17:28
No, I have not investigated these on lab machines.

**Comment by AndyAyersMS** [comment] 2018-03-19 16:21
@jorive I'll look at this if you can get me access to the perf HW.

**Comment by jorive** [comment] 2018-03-19 16:32
@AndyAyersMS done

**Comment by AndyAyersMS** [comment] 2018-03-19 20:25
The timeouts were seen for x86 ryujit (which is not the default x86 jit in 1.1) for reverse-complement-6 and for fasta-1.

**Comment by AndyAyersMS** [comment] 2018-03-20 00:52
Also this is for a checked 1.1 build, which requires VS2015. To get past build errors you need to port the fix from #7201.

**Comment by AndyAyersMS** [comment] 2018-03-20 02:03
I can't reproduce these issues on the lab HW. 

Both release and checked x86 seem to run fairly quickly whether run under the perf harness or run as standalone tests.

I'm not sure fixing this is all that important at this point. We are only making minimal changes to 1.1 and it's unlikely that enabling either of these tests adds much value. So I would suggest we just close this out.

@jorive any objections?

**Comment by jorive** [comment] 2018-03-21 01:54
@AndyAyersMS I would close it as no repro. We can always open a new issue with more details if we encounter a new problem.

**Comment by AndyAyersMS** [comment] 2018-03-21 01:56
Sounds good. Closing.

**Closed by AndyAyersMS** 2018-03-21 01:56 UTC
Labels: area-CodeGen, test bug
