### ISSUE TITLE
.Net Core and Native dll's always throw BadImageFormat

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#18447] opened 2018-06-13 03:16 UTC
@SharperC commented on [Sun Jun 10 2018](https://github.com/dotnet/core/issues/1678)

# BadImageFormatException, everytime...

After a LOT of times trying to load native code or rather call a native method using `DllImport`, I'm reporting this as a issue, because it seems like there is no solution.

## So what did I try?

First of all, I tried the way it works with .Net Framework, what of course didn't work.
I searched in the Internet for solutions but i only found the same problems with "could work" solutions. For example compiling the .Net Core application and the native libary in 64 bit (what i did).
I also tried a non .Net c++ compiler (MinGW) and the default Visual Studio c++ compiler.
Both give the same `BadImageFormat` Exception.

### The c# part
```cs
[DllImport(@"testlib.dll", EntryPoint = "test")]
static extern int Test();

static void Main(string[] args)
{
    Console.WriteLine(Test());
    Console.ReadLine();
}
```

### The c++ part
```cpp
#define EXTERN extern "C" __declspec(dllexport)

EXTERN int test()
{
    return 1234;
}
```

I also tried it on Linux using the g++ compiler, for some reason it worked on Linux.

Thanks for taking the time to read.

---

@markusschaber commented on [Mon Jun 11 2018](https://github.com/dotnet/core/issues/1678#issuecomment-396199666)

In my experience, the main reason for this exception is when you try to load a 32-bit DLL into a 64 Bit process, or the other way round.

Mismatch between x86/ARM is also possible, in theory. :-)

Note that sometimes, .NET core on Windows runs in an unexpected CPU architecture, as some tools (e. G. Visual Studio, xUnit etc.) tend to ignore the target CPU architecture defined in the project, and just run the code in the first installation they find in PATH, so if both 32 and 64 bit runtimes or SDKs are installed, it's random which one you get.

We had to change the order of entries in PATH environment variable to run our code with x86, as the native DLL we depend on is not (yet) 64 bit.

---

@dasMulli commented on [Mon Jun 11 2018](https://github.com/dotnet/core/issues/1678#issuecomment-396203170)

for `dotnet` it will use the version of `dotnet.exe` that's in the path - either the 32bit or 64bit `dotnet.exe` host.
There will be some changes that will allow patching the csproj to allow `dotnet run` to switch architectures (when launching a sub-process) but until then, it's a bit of a pain - https://github.com/dotnet/sdk/issues/1905

---

@SharperC commented on [Mon Jun 11 2018](https://github.com/dotnet/core/issues/1678#issuecomment-396254074)

@markusschaber I know that you mean, but i tried both using a 32bit and a 64bit for c++ and dotnet, and yes a already noticed that dotnet tends to totaly ignore if you set the assembly in vs to 32 bit

**Comment by jkotas** [comment] 2018-06-13 14:01
Duplicate of https://github.com/dotnet/coreclr/issues/11298 ?

**Comment by jeffschwMSFT** [comment] 2018-06-13 15:44
@SharperC this does seem like a mixmatch of 32bit and 64bit, though it also seems like you tried all the combinations.  Are you still not able to get this scenario to work?

**Comment by SharperC** [comment] 2018-06-13 23:17
Yes i tried all the combinations and none of the work.

**Comment by jeffschwMSFT** [comment] 2018-06-13 23:20
Can you share out a directory with the necessary build steps?  This is a fundamental building block for .NET Core, so I suspect there is something subtle going on with the steps.  It looks like you started with VS on Windows, can you share that out?

**Comment by SharperC** [comment] 2018-06-13 23:21
You mean like the exact steps i did, and/or the solution folder?

**Comment by SharperC** [comment] 2018-06-13 23:50
Here we go https://github.com/SharperC/NativeTest

**Comment by jeffschwMSFT** [comment] 2018-06-14 00:13
Good news I see the same badimageexception that you are seeing.  I need to take a deeper look, I anticipate knowing more tomorrow.

**Comment by gfoidl** [comment] 2018-06-14 07:39
@SharperC you hard-coded the path to the DLL in https://github.com/SharperC/NativeTest/blob/510932693e2a5a07ef399777a7d6e8b615dd4eab/NativeTest/Program.cs#L8
So you'll always pick the Debug/x86 DLL, because the build output for x64 is in `$(SolutionDir)\x64\$(Configuration)`.

**Comment by SharperC** [comment] 2018-06-14 07:51
Well yeah i hard coded the path to it for this example, normaly I don't to that. I also forgot to set the Native libary to 64x

**Comment by gfoidl** [comment] 2018-06-14 08:09
With your project I can reproduce the failure -- reason is commented above.
I sent https://github.com/SharperC/NativeTest/pull/1 that fixes the problem, because it pickes the matching DLL.

**Comment by SharperC** [comment] 2018-06-14 10:01
Ok thank you, I'm not quite sure what i did wrong last time because i did copy the x64 dll, nvm.

**Comment by jeffschwMSFT** [comment] 2018-06-14 15:57
Thanks @gfoidl for taking a look.  @SharperC looks like this issue has been resolved.

**Closed by jeffschwMSFT** 2018-06-14 15:57 UTC
Labels: area-AssemblyLoader, question

**Comment by danmosemsft** [comment] 2018-06-15 05:41
Maybe this exception could be improved to indicate the bitness  mismatch when that is the case, to help troubleshooting this case in future.

**Comment by jeffschwMSFT** [comment] 2018-06-15 17:54
#11298 is tracking that potential improvement

**Comment by WaqarAzeem** [comment] 2019-02-12 15:02
I created two project

1. ASP.NET Core Web Application | Core 2.2
2. ASP.NET Web Application (.NET Framework) | .Net 4.6.1

In my test controller, I used an exported function from a 32-bit unmanaged DLL, using [DllImport("Testing.DLL")]
Copy that 32-bit native DLL file in both the project folders
Run as “Any CPU” on my Windows 64-bit Windows 10

Only the project created in Core 2.2 crashed with following exception

```
[
  {
    "errorCode": -1001,
    "errorString": "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)",
    "exception": {
      "ClassName": "System.BadImageFormatException",
      "Message": "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)",
      "Data": null,
      "InnerException": null,
      "HelpURL": null,
      "StackTraceString": "   at WebApplication1.DCCAPI.BUICExit()\r\n   at WebApplication1.Controllers.TS240Controller.BUICInit() in C:\\Users\\Waqar Azeem\\source\\repos\\WebApplication1\\WebApplication1\\Controllers\\TS240Controller.cs:line 71",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": null,
      "HResult": -2147024885,
      "Source": "WebApplication1",
      "WatsonBuckets": null,
      "BadImageFormat_FileName": null,
      "BadImageFormat_FusionLog": null
    }
  }
]
```
