### ISSUE TITLE
Update `microsoft.netcore.ilasm` to be a self-contained package

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#18892] opened 2018-07-12 20:49 UTC
Currently, `microsoft.netcore.ilasm` has a dependency on `microsoft.netcore.runtime.coreclr` which makes restoring/consuming the package a multi-step process.

You have to restore the rid-specific version of each package, and then combine the bits from each in a new location before you can invoke `ilasm`.

Updating the `microsoft.netcore.ilasm` package to be self-contained, such that it can be invoked directly (from the RID specific version of the package) would make it significantly easier to consume.

**Comment by tannergooding** [comment] 2018-07-12 20:49
This would, specifically, make the ILProj SDK simpler: https://github.com/dotnet/arcade/pull/317

CC. @weshaggard

**Comment by weshaggard** [comment] 2018-07-12 21:23
@RussKeldorph do you have any issues with this?

**Comment by RussKeldorph** [comment] 2018-07-12 21:55
@weshaggard Sounds fine me, but I doubt I appreciate the implications well enough to have an opinion.  Are there any downsides besides breaking someone that may already be using this?

/cc @MichalStrehovsky

**Comment by tannergooding** [comment] 2018-07-12 22:07
The nuget packages will be bigger, for one.

**Comment by MichalStrehovsky** [comment] 2018-07-13 09:17
> /cc @MichalStrehovsky

We already have #15059 tracking this. Would be nice to do something about it.

**Comment by jkotas** [comment] 2018-07-17 19:22
Duplicate of #15059

**Closed by jkotas** 2018-07-17 19:22 UTC
