### ISSUE TITLE
Test failure: PayloadGroup0/Regressions_common._date_date_/_date_date_cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#24212] opened 2019-04-24 05:39 UTC
The test **Regressions_common._date_date_/_date_date_cmd**  has failed.

Failure Message:
```
Return code:      1
Raw output file:      D:\\dotnetbuild\\work\\ec86d468-4df4-4316-b64b-835ee5cb2152\\Work\\5371208b-3eec-4267-842f-75246cfeab5c\\Exec\\Regressions\\common\\Reports\\Regressions.common\\date\\date.output.txt
Raw output:
BEGIN EXECUTION
 \"D:\\dotnetbuild\\work\\ec86d468-4df4-4316-b64b-835ee5cb2152\\Payload\\corerun.exe\" date.exe 
Beginning test case DateTime at 4/23/2019 7:13:05 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: DateTime.Parse(January 02/35)
1/2/2035 12:00:00 AM

Ending test case at 4/23/2019 7:13:05 PM
FAIL
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\\dotnetbuild\\work\\ec86d468-4df4-4316-b64b-835ee5cb2152\\Payload
> D:\\dotnetbuild\\work\\ec86d468-4df4-4316-b64b-835ee5cb2152\\Work\\5371208b-3eec-4267-842f-75246cfeab5c\\Exec\\Regressions\\common\\date\\date.cmd
Expected: True
Actual:   False
```
Stack Trace:
```
 at Regressions_common._date_date_._date_date_cmd() in F:\workspace\_work\1\s\bin\tests\Windows_NT.arm.Release\TestWrappers\Regressions.common\Regressions.common.XUnitWrapper.cs:line 474
```

Details:
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190423.74/workItem/PayloadGroup0/analysis/xunit/Regressions_common._date_date_~2F_date_date_cmd

**Comment by RussKeldorph** [comment] 2019-04-25 17:15
Year is parsed as 2035 instead of 1935.  Happens intermittently, but always on machine DDARM64-035.  @MattGal, this machine is mentioned by @danmosemsft in dotnet/core-eng#6040, but it's not clear it is one of the ones being re-imaged.

Jobs
| where Source contains("dotnet/coreclr")
| where Source contains("official")
| join kind=inner TestResults on JobId
| where Method contains ("_date_")
| where Result == "Fail"
| where Started > make_datetime(2019,1,1)
| join kind=inner WorkItems on WorkItemId
| project Build, MachineName, Properties, Message

@tarekgh FYI I think this is a bad machine, but if you know something about Windows configuration that might explain this, please let us know.

**Comment by MattGal** [comment] 2019-04-25 17:17
Wow, I have no idea what could cause that specific behavior but it's definitely one of the 6 machines that got reimaged recently; @ilyas1974 FYI.  I'll take a quick look at the machine to see if I see anything interesting.

**Comment by tarekgh** [comment] 2019-04-25 17:36
The date parsing depends on something called (2 digits year max value)[https://docs.microsoft.com/en-us/dotnet/api/system.globalization.calendar.twodigityearmax?view=netframework-4.8]. This value picked up from the OS. I think recently Windows changed this value which make 35 be parsed to 2035 instead of 1935. The test/apps should be fixed according to that.

**Comment by MattGal** [comment] 2019-04-25 17:39
Thanks! I couldn't find anything interesting about the machine but the reason it's different is what you'd expect; it's running a newer version of Windows.

**Comment by tarekgh** [comment] 2019-04-25 17:56
I am wondering why we have such tests at all in coreclr. We already have many tests for the date parsing in corefx and I believe corefx tests already part of the CI.

**Comment by RussKeldorph** [comment] 2019-04-25 18:15
@tarekgh Thanks.  So you recommend we delete this test in favor of corefx testing?

**Comment by tarekgh** [comment] 2019-04-25 19:04
@RussKeldorph yes, we already have a coverage in corefx. I am seeing this test exist in 2 places too:

https://github.com/dotnet/coreclr/blob/4eb3f3184c2c8c2c47b054dca984354f659d013f/tests/src/Regressions/common/date.cs
https://github.com/dotnet/coreclr/blob/4eb3f3184c2c8c2c47b054dca984354f659d013f/tests/src/Regressions/coreclr/0069/date.cs

**Comment by RussKeldorph** [comment] 2019-04-25 20:19
@tarekgh Good catch.  Thanks!  #24255

**Closed** 2019-04-25 23:34 UTC
Labels: test bug
