### ISSUE TITLE
Math.Ceiling on Windows x64 handles inputs in the form of `-0.xxxxxxxxx` differently

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#10287] opened 2017-03-19 02:32 UTC
`Math.Ceiling` on Linux, Mac, and x86 Windows all return `-0.0` for inputs in the form of `-0.xxxxxxxxx`. However, x64 Windows currently returns +0.0.

The IEEE nor the C11 spec directly specifies how -0.xxxx should be handled. However, the handling of these values should be consistent across all platforms. The IEEE spec does indirectly specify the handling of rounding towards negative zero, and it seems to match the behavior Linux, Mac, and x86 Windows are doing.

**Comment by tannergooding** [comment] 2017-03-19 02:36
It should also be noted that the handling of `MathF.Ceiling` is the opposite. On all platforms, `-0.0f` returns `-0.0f`, but `-0.xxxxxxxxxf` returns `+0.0f`.

**Comment by gkhanna79** [comment] 2017-03-21 04:54
CC @danmosemsft

**Comment by danmosemsft** [comment] 2017-03-28 04:15
@tannergooding marked as future because I'm assuming this isn't a regression.

**Comment by danmosemsft** [comment] 2017-06-19 03:58
When fixing this please reenable all the corefx tests marked https://github.com/dotnet/coreclr/issues/10287

**Comment by tannergooding** [comment] 2018-08-29 01:28
This was a bug with the `/fp:fast` implementation, I am logging internal bugs to track this.

**Closed** 2018-09-05 16:02 UTC
Labels: FollowingUp, area-System.Runtime, bug
