### ISSUE TITLE
System.Environment.OSVersion fails on Mac OS X

### ISSUE THREAD

**Issue by cnblogs-dudu** [dotnet/coreclr#275] opened 2015-02-15 15:32 UTC
When running the following sample console app by corerun, 
```csharp
using System;

internal class Program
{
    private static void Main(string[] args)
    {       
        Console.WriteLine(Environment.OSVersion);  
    }   
}
```
There are following failures.
```
Compiling  181 System.Runtime.CompilerServices.JitHelpers::UnsafeCastToStackPointer, 
IL size = 25, hsh=0x99a90445
Assert failure (unable to format)
/git/dotnet/coreclr/src/vm/stackwalktypes.h
SPOffset >= pUnwindInfo->RSPOffsetFromUnwindInfo
**** MessageBox invoked, title 'Assert failure (unable to format)' ****
  SPOffset >= pUnwindInfo->RSPOffsetFromUnwindInfo
********

Assert failure (unable to format)
/git/dotnet/coreclr/src/vm/stackwalktypes.h
FitsIn<DWORD>(pUnwindInfo->RBPOffset + (SPOffset - pUnwindInfo->RSPOffsetFromUnwindInfo))
**** MessageBox invoked, title 'Assert failure (unable to format)' ****
  FitsIn<DWORD>(pUnwindInfo->RBPOffset + (SPOffset - pUnwindInfo->RSPOffsetFromUnwindInfo))
********
```
When running the same console app by mono, it gets the following result without any failure.
```
Unix 14.1.0.0
```

**Comment by jkotas** [comment] 2015-02-15 16:37
This is duplicate of #147 
cc @weshaggard

**Closed by jkotas** 2015-02-15 16:37 UTC
