### ISSUE TITLE
Ready to Run Unix explicit tailcalls not supported.

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#5416] opened 2016-06-02 17:13 UTC
Several tests fail with the following under [r2r jit stress](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/release_1.0.0/job/x64_checked_ubuntu_r2r_jitstress2_tst/1/testReport/).

JIT/IL_Conformance/Old/objectmodel/castclass/castclass.sh

```
               BEGIN EXECUTION
               in takeLock
               /mnt/j/workspace/dotnet_coreclr/release_1.0.0/x64_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/crossgen /Platform_Assemblies_Paths /mnt/j/workspace/dotnet_coreclr/release_1.0.0/x64_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay:/mnt/j/workspace/dotnet_coreclr/release_1.0.0/x64_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Windows_NT.x64.Checked/JIT/IL_Conformance/Old/objectmodel/castclass castclass.exe
               Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
               Copyright (c) Microsoft Corporation.  All rights reserved.
               
               ReadyToRun: Explicit tailcalls not supported
               Native image /mnt/j/workspace/dotnet_coreclr/release_1.0.0/x64_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Windows_NT.x64.Checked/JIT/IL_Conformance/Old/objectmodel/castclass/castclass.exe.ni.exe generated successfully.
               in ReleaseLock
               /mnt/j/workspace/dotnet_coreclr/release_1.0.0/x64_checked_ubuntu_r2r_jitstress2_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun castclass.exe
               terminate called after throwing an instance of 'PAL_SEHException'
               ./castclass.sh: line 106:  6918 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" castclass.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

**Comment by RussKeldorph** [comment] 2016-06-02 17:18
@jashook I believe you can close this as a duplicate of #4971.

**Closed** 2016-06-02 17:22 UTC
Labels: ReadyToRun
