### ISSUE TITLE
Unloadable Assembly Produced for structs containing struct of T, even when T avoids circularity

### ISSUE THREAD

**Issue by drunkcod** [dotnet/coreclr#23845] opened 2019-04-09 18:27 UTC
It was proposed that this issue might better fit here (although it affects both core and desktop fx), original is found at: https://github.com/dotnet/roslyn/issues/34865

**Steps to Reproduce**:
1. Compile and run the following:
```csharp
using System;

namespace StructuralMadness
{
	class Program
	{
		public static void Main()
		{
			Console.WriteLine(new MyThing());
		}

		struct IdOf<T> { }

		struct MyThing
		{
			public IdOf<MyThing> Id;
		}
	}
}
```
**Expected Behavior**:
Print: StructuralMadness.Program+MyThing
**Actual Behavior**:
Crashes with:
```
Unhandled Exception: System.TypeLoadException: Could not load type 'StructuralMadness.Program+MyThing' from assembly 'ConsoleApp3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at StructuralMadness.Program.Main()
```

Substituting either of the "struct" for class avoids the issue. 
I'm assuming somewhere there's a problem in assuming the size of "T" needs to be fully resolved before instantiation.

**Comment by jkotas** [comment] 2019-04-10 04:16
Looks like a duplicate of https://github.com/dotnet/coreclr/issues/20220

**Comment by sergiy-k** [comment] 2019-06-05 22:26
I'm closing this issues as a duplicate of https://github.com/dotnet/coreclr/issues/20220 and https://github.com/dotnet/coreclr/issues/7957

**Closed by sergiy-k** 2019-06-05 22:26 UTC
Labels: area-TypeSystem
