### ISSUE TITLE
Monitor.Enter failures

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3937] opened 2016-03-25 23:15 UTC
Repro steps:

1) Build.cmd Release x86 skiptests
2) Download the latest build of runtimes.Win7-x86.Microsoft.NETCore.Runtime.CoreCLR packageand replace the contents of bin\product\WindowsNT.x86_Release with the package contents.
2) tests\buildtest.cmd Release x86 priority 1
3) tests\runtest.cmd x86Release

 baseservices._threading_generics_Monitor_TryEnter03_TryEnter03_._threading_generics_Monitor_TryEnter03_TryEnter03_cmd
cmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\generics\Monitor\TryEnter03\TryEnter03.cmd Timed Out\r\n\n\nReturn code:      -100\nRaw output file:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Reports\baseservices\threading\generics\Monitor\TryEnter03\TryEnter03.output.txt\nRaw output:\nBEGIN EXECUTION\r\n "C:\Github\gkhanna79\coreclr\tests\..\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\corerun.exe" TryEnter03.exe  \r\nTest Passed\r\nExpected: 100\r\nActual: 100\r\nEND EXECUTION - PASSED\r\nPASSED\r\ncmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\generics\Monitor\TryEnter03\TryEnter03.cmd Timed Out\r\nTest Harness Exitcode is : -100\r\n\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\generics\Monitor\TryEnter03\TryEnter03.cmd\n\r\nExpected: True\r\nActual:   False
   at baseservices._threading_generics_Monitor_TryEnter03_TryEnter03_._threading_generics_Monitor_TryEnter03_TryEnter03_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x86_Release\baseservices\baseservices.XUnitWrapper.cs:line 12801
957.3588604s ✘  baseservices._threading_generics_Monitor_TryEnter06_TryEnter06_._threading_generics_Monitor_TryEnter06_TryEnter06_cmd
cmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\generics\Monitor\TryEnter06\TryEnter06.cmd Timed Out\r\n\n\nReturn code:      -100\nRaw output file:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Reports\baseservices\threading\generics\Monitor\TryEnter06\TryEnter06.output.txt\nRaw output:\nBEGIN EXECUTION\r\n "C:\Github\gkhanna79\coreclr\tests\..\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\corerun.exe" TryEnter06.exe  \r\nTest Passed\r\nExpected: 100\r\nActual: 100\r\nEND EXECUTION - PASSED\r\nPASSED\r\ncmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\generics\Monitor\TryEnter06\TryEnter06.cmd Timed Out\r\nTest Harness Exitcode is : -100\r\n\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\baseservices\threading\generics\Monitor\TryEnter06\TryEnter06.cmd\n\r\nExpected: True\r\nActual:   False
   at baseservices._threading_generics_Monitor_TryEnter06_TryEnter06_._threading_generics_Monitor_TryEnter06_TryEnter06_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x86_Release\baseservices\baseservices.XUnitWrapper.cs:line 13008

**Comment by adityamandaleeka** [comment] 2016-05-05 22:22
I'm not able to reproduce this issue (or #3938) locally, but it appears based on the logs you pasted that the tests are passing, albeit not within the timeout period.

The spew from the test infrastructure is pretty confusing here, since the output from the wrapper lib and the batch file for the test are all together, and sometimes contradict. The wrapper says there's a failure (because of the timeout), but the test output says 'END EXECUTION - PASSED'.

Turns out we wait for some timeout period for the process to exit, then we wait for another timeout period for the output of the process to be written to the output file. Effectively, this means the output file reflects the output of the test if it's given double the timeout period to run.

**Comment by adityamandaleeka** [comment] 2016-06-02 20:55
Closing this and #3938. If they occur in the future, please look into whether the problem mentioned in the comment above is the reason.

**Closed by adityamandaleeka** 2016-06-02 20:55 UTC
Labels: bug, Test-Issue, Threading, x86
