### ISSUE TITLE
coreclr hangs inside futex on arm32 linux running hello world

### ISSUE THREAD

**Issue by hgroover1** [dotnet/coreclr#24038] opened 2019-04-16 20:29 UTC
I am running a kernel.org 4.14.77 Linux kernel with additions from the Digi-Linux repo for iMX6. I am running on a dual-core system. I am able to run through the entire ltp (Linux Test Project) suite and this system is otherwise working and stable.

First unusual event: I build a Hello, World dotnet program on a Raspberry Pi (running Raspbian Stretch) and copy the resulting files to the target system, then after changing to the deployment directory run
COREHOST_TRACE=1 ./Hello
The last several lines of text I see are
Processing native/culture for deps entry [runtime.linux-arm.Microsoft.NETCore.Do
tNetHostPolicy, 2.2.0, runtimes/linux-arm/native/libhostpolicy.so]              
  Considering entry [runtime.linux-arm.Microsoft.NETCore.DotNetHostPolicy/2.2.0/
runtimes/linux-arm/native/libhostpolicy.so], probe dir [], probe fx level:0, ent
ry fx level:0                                                                   
    Local path query exists /opt/talos-service/libhostpolicy.so                 
    Probed deps dir and matched '/opt/talos-service/libhostpolicy.so'           
Processing native/culture for deps entry [runtime.linux-arm.Microsoft.NETCore.Do
tNetHostResolver, 2.2.0, runtimes/linux-arm/native/libhostfxr.so]               
  Considering entry [runtime.linux-arm.Microsoft.NETCore.DotNetHostResolver/2.2.
0/runtimes/linux-arm/native/libhostfxr.so], probe dir [], probe fx level:0, entr
y fx level:0                                                                    
    Local path query exists /opt/talos-service/libhostfxr.so                    
    Probed deps dir and matched '/opt/talos-service/libhostfxr.so'              
The resolved JIT path is '/opt/talos-service/libclrjit.so'                      
CoreCLR path = '/opt/talos-service/libcoreclr.so', CoreCLR dir = '/opt/talos-ser
vice/' 
                                                                         
At this point the application is unresponsive and has to be killed using SIGKILL (kill -9).
Using strace shows that it is waiting inside a futex call. The app consists of a print statement which has not yet occurred. The futex is being invoked from within the pthread library.

I have run dotnet applications on the same machine with a different Linux version and the identical build and deployment procedure. This Hello program runs on the Raspberry Pi running a nearly identical kernel version. What I am trying to do is gain better insight into what is failing. I have increased systemwide file handles to 100000 and I am running as root.

The next steps for me appear to be rebuilding coreclr as a debug build so I might get additional insight into the failure. Any suggestions on debugging or building components in debug mode would be helpful. Any suggestions on where to start looking at the source corresponding to these last messages would be helpful.

I have been using the release builds of dotnet and coreclr until this point.

**Comment by janvorli** [comment] 2019-04-16 22:43
For instructions on how to cross build coreclr, see https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md. I would not recommend building on the target device as it would take ages to complete.
By deafult, build.sh produces debug build. (you can add `release` option to get release build or you can add `debug` option to be explicit if you want).
I would recommend building the debug binaries from the same commit hash that the binaries you are currently using were built from. That way, it is guaranteed that the binaries will work with the rest of the binaries that were not built from coreclr.
You can get the commit hash using `strings libcoreclr.so | grep "@(#)"`. The commit hash is at the end of the dumped string. Then use `git checkout the_commit_hash_you've_found` and then build. Copy all files from bin/Product/Linux.arm.Debug to the location where you have the libcoreclr.so.

**Comment by jkotas** [comment] 2019-04-17 04:03
This may be same problem as https://github.com/dotnet/coreclr/issues/19025. You can try to rename liblttng-ust to something else and check whether the problem goes away.

**Comment by RussKeldorph** [comment] 2019-04-17 19:51
Assuming duplicate of #19025.

**Closed by RussKeldorph** 2019-04-17 19:51 UTC
