### ISSUE TITLE
[x64] Assertion failed '!s_pagePool.isPoolPage(page)'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18966] opened 2018-07-17 18:57 UTC
From x64 corefx JitStressRegs=0x1000 run: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs0x1000/462/consoleText

```
  Assert failure(PID 6016 [0x00001780], Thread: 6216 [0x1848]): Assertion failed '!s_pagePool.isPoolPage(page)' in 'System.Data.SqlClient.SqlClientDiagnosticListenerExtensions:WriteConnectionOpenError(ref,struct,ref,ref,ref)' (IL size 46)
  
      File: d:\j\workspace\x64_checked_w---5e38e6b2\src\jit\alloc.cpp Line: 301
      Image: D:\j\workspace\x64_checked_w---5e38e6b2\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x64\dotnet.exe
```

**Comment by BruceForstall** [comment] 2018-07-17 18:57
@dotnet/jit-contrib

**Comment by mikedn** [comment] 2018-07-17 19:00
Duplicate of #18777

**Closed** 2018-07-17 19:12 UTC
Labels: area-CodeGen, bug
