### ISSUE TITLE
[arm] Assert failure: currentProcessCpuCount == g_processAffinitySet.Count()

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24994] opened 2019-06-06 02:07 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-all-testing/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190528.79/workItem/JIT/analysis/xunit/JIT_Performance._CodeQuality_V8_Crypto_Crypto_Crypto_~2F_CodeQuality_V8_Crypto_Crypto_Crypto_sh

**Failed tests:**
/ssd/dotnetbuild/work/2367ed72-8b8b-452b-9f40-22f574dfbfd6/Work/db8a41c0-d1d0-4153-8818-f8e9ff222f23/Exec/JIT/Performance/CodeQuality/V8/Crypto/Crypto/Crypto.sh

**Log:**
```
Assert failure(PID 5981 [0x0000175d], Thread: 5981 [0x175d]): currentProcessCpuCount == g_processAffinitySet.Count()
    File: /__w/4/s/src/vm/gcenv.os.cpp Line: 113
    Image: /ssd/dotnetbuild/work/2367ed72-8b8b-452b-9f40-22f574dfbfd6/Payload/corerun

/ssd/dotnetbuild/work/2367ed72-8b8b-452b-9f40-22f574dfbfd6/Work/db8a41c0-d1d0-4153-8818-f8e9ff222f23/Exec/JIT/Performance/CodeQuality/V8/Crypto/Crypto/Crypto.sh: line 252:  5981 Aborted                 $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"

Return code:      1
Raw output file:      /ssd/dotnetbuild/work/2367ed72-8b8b-452b-9f40-22f574dfbfd6/Work/db8a41c0-d1d0-4153-8818-f8e9ff222f23/Exec/JIT/Performance/Reports/JIT.Performance/CodeQuality/V8/Crypto/Crypto/Crypto.output.txt
Raw output:
BEGIN EXECUTION
/ssd/dotnetbuild/work/2367ed72-8b8b-452b-9f40-22f574dfbfd6/Payload/corerun Crypto.exe ''
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/ssd/dotnetbuild/work/2367ed72-8b8b-452b-9f40-22f574dfbfd6/Payload
> /ssd/dotnetbuild/work/2367ed72-8b8b-452b-9f40-22f574dfbfd6/Work/db8a41c0-d1d0-4153-8818-f8e9ff222f23/Exec/JIT/Performance/CodeQuality/V8/Crypto/Crypto/Crypto.sh
Expected: True
Actual:   False
```

**Comment by jkotas** [comment] 2019-06-06 06:32
Duplicate of #24050

**Closed by jkotas** 2019-06-06 06:32 UTC
Labels: arch-arm32, os-linux
