### ISSUE TITLE
ToolsError build failures in 'official/dotnet/coreclr/refs/heads/master' - '20190317.71'

### ISSUE THREAD

**Issue by robertborr** [dotnet/coreclr#23322] opened 2019-03-18 20:56 UTC
@dotnet-mc-bot commented on [Sun Mar 17 2019](https://github.com/dotnet/core-eng/issues/5539)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=126150
  - **Agent:** a0000JX
  - **Error log:** /__w/2/s/tests/dir.traversal.targets(0,0): error : (No message specified) [/__w/2/s/tests/src/dirs.proj]...

@robertborr

---

@robertborr commented on [Mon Mar 18 2019](https://github.com/dotnet/core-eng/issues/5539#issuecomment-474096542)

ERROR: An error occurred in /__w/2/s/.dotnet/dotnet msbuild /nologo /verbosity:minimal /clp:Summary /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount /__w/2/s/tests/build.proj /flp:Verbosity=normal;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Release.log;Append=true /flp1:WarningsOnly;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Release.wrn;Append=true /flp2:ErrorsOnly;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Release.err;Append=true /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:__BuildArch=x64 /p:__BuildType=Release /p:__BuildOS=Linux /p:CLRTestPriorityToBuild=1. Check logs under /__w/2/s.
2019-03-17T13:16:00.4856444Z Failed to build Managed tests build (build tests).

---

@robertborr commented on [Mon Mar 18 2019](https://github.com/dotnet/core-eng/issues/5539#issuecomment-474096829)

Build FAILED.

/__w/2/s/tests/dir.traversal.targets(25,5): error : (No message specified) [/__w/2/s/tests/src/dirs.proj]
/__w/2/s/tests/dir.traversal.targets(25,5): error : (No message specified) [/__w/2/s/tests/build.proj]

---

@robertborr commented on [Mon Mar 18 2019](https://github.com/dotnet/core-eng/issues/5539#issuecomment-474097316)

windows;
Build FAILED.

C:\Users\vsagent\.nuget\packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19162.7\tools\azure-pipelines\AzurePipelines.MultiQueue.targets(39,5): error : Test run 2819846 has one or more failing tests. [F:\vsagent\4\s\tests\helixpublishwitharcade.proj]
    0 Warning(s)

**Comment by RussKeldorph** [comment] 2019-03-19 22:31
Duplicate of #23330

**Closed by RussKeldorph** 2019-03-19 22:31 UTC
