### ISSUE TITLE
Test failure: tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_/_eventsourcetrace_eventsourcetrace_eventsourcetrace_cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#24851] opened 2019-05-30 06:56 UTC
The test `tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_/_eventsourcetrace_eventsourcetrace_eventsourcetrace_cmd` has failed.

Failure Message:
```
Internal CLR error. (0x80131506)\r
   at System.Diagnostics.Tracing.EventPipe.Disable()\r
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)\r
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)\r
   at Tracing.Tests.Common.TraceControl.Disable()\r
   at Tracing.Tests.EventSourceTrace.Main(System.String[])\r
\r
Return code:      1\r
Raw output file:      C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Work\\ed226a49-4ace-4bc5-a8cb-c7f068fc5d65\\Exec\\tracing\\eventsource\\Reports\\tracing.eventsource\\eventsourcetrace\\eventsourcetrace\\eventsourcetrace.output.txt\r
Raw output:\r
BEGIN EXECUTION\r
        1 file(s) copied.\r
\" C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Payload\\crossgen.exe\"  /Platform_Assemblies_Paths C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Payload;C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Work\\ed226a49-4ace-4bc5-a8cb-c7f068fc5d65\\Exec\\tracing\\eventsource\\eventsourcetrace\\eventsourcetrace\\IL;C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Work\\ed226a49-4ace-4bc5-a8cb-c7f068fc5d65\\Exec\\tracing\\eventsource\\eventsourcetrace\\eventsourcetrace /in eventsourcetrace.org /out eventsourcetrace.exe\r
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0\r
Copyright (c) Microsoft Corporation.  All rights reserved.\r
\r
Native image eventsourcetrace.exe generated successfully.\r
 \"C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Payload\\corerun.exe\" eventsourcetrace.exe \r
\tStart: Enable tracing.\r
\tEnd: Enable tracing.\r
\r
\tStart: Messaging.\r
\tEnd: Messaging.\r
\r
\tStart: Disable tracing.\r
Expected: 100\r
Actual: -1073741819\r
END EXECUTION - FAILED\r
FAILED\r
Test Harness Exitcode is : 1\r
To run the test:\r
> set CORE_ROOT=C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Payload\r
> C:\\dotnetbuild\\work\\2ce71b63-3ca8-41a6-879c-d253aeed7a53\\Work\\ed226a49-4ace-4bc5-a8cb-c7f068fc5d65\\Exec\\tracing\\eventsource\\eventsourcetrace\\eventsourcetrace\\eventsourcetrace.cmd\r
Expected: True\r
Actual:   False
```

Stack Trace:
```
   at tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_._eventsourcetrace_eventsourcetrace_eventsourcetrace_cmd() in F:\workspace\_work\1\s\bin\tests\Windows_NT.x86.Release\TestWrappers\tracing.eventsource\tracing.eventsource.XUnitWrapper.cs:line 126
```

Build : Master - 20190529.4 (Ready-To-Run Tests)
Failing configurations:
- Windows.7.Amd64
  - x86
  - x64

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fr2r~2Fcli~2F/build/20190529.4/workItem/PayloadGroup0/analysis/xunit/tracing_eventsource._eventsourcetrace_eventsourcetrace_eventsourcetrace_~2F_eventsourcetrace_eventsourcetrace_eventsourcetrace_cmd

**Comment by hoyosjs** [comment] 2019-05-31 18:46
Dupe of #24839

**Closed by hoyosjs** 2019-05-31 18:47 UTC
Labels: EventPipe, area-Tracing, blocking-3.0-preview6, blocking-official-build
