### ISSUE TITLE
[Question] Summary Tags and Intellisense

### ISSUE THREAD

**Issue by orthros** [dotnet/coreclr#10570] opened 2017-03-29 21:44 UTC
Greetings Devs,

This is hopefully a straightforward question surrounding Intellisense.

I see for some classes like [EventSourceException](https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/Diagnostics/Eventing/EventSourceException.cs#L33-L36), the class and its members follow the standard `<summary>`  tag while others like [DateTime](https://github.com/dotnet/coreclr/blob/68f72dd2587c3365a9fe74d1991f93612c3bc62a/src/mscorlib/src/System/DateTime.cs#L138-L148) do not, despite the Intellisense showing up in Visual Studio 
![image](https://cloud.githubusercontent.com/assets/7820716/24477932/8adbff80-149e-11e7-9885-ddd8e067e9b4.png)

Are we able to contribute to this documentation, and if so where should we go?

Thanks.

**Comment by jkotas** [comment] 2017-03-29 22:45
@karelz Do you happen to know the answer to this? I remember it has been asked before - it would be nice to capture the answer in the corefx docs.

**Comment by karelz** [comment] 2017-03-30 01:17
Dupe of https://github.com/dotnet/corefx/issues/230 - I'll ping that thread where we are.

How to update docs is planned for new contributor guide: https://github.com/dotnet/corefx/issues/17534#issuecomment-289318071, just no time to get to it :(

**Closed by karelz** 2017-03-30 01:17 UTC
Labels: documentation
