### ISSUE TITLE
Test failed: GC_API._NoGCRegion_NoGC_NoGC_._NoGCRegion_NoGC_NoGC_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25921] opened 2019-07-29 01:32 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190728.1/workItem/PayloadGroup0/analysis/xunit/GC_API._NoGCRegion_NoGC_NoGC_~2F_NoGCRegion_NoGC_NoGC_cmd

**Failed tests:**
GC_API._NoGCRegion_NoGC_NoGC_._NoGCRegion_NoGC_NoGC_cmd

**Log:**
```
Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\60895ced-77d4-4682-b9e9-ff6a1b0d4d04\\Work\\322b9fee-2fee-4bb5-88fd-c814de3e5c54\\Exec\\GC\\API\\Reports\\GC.API\\NoGCRegion\\NoGC\\NoGC.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\60895ced-77d4-4682-b9e9-ff6a1b0d4d04\\Payload\\corerun.exe\" NoGC.exe 
Workstation on 64-bit with 2 procs
=====allocating 100mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 100 MB
100 MB SUCCEEDED, did 1 gen2 GCs
before GC: 40, after GC: 40
ended no gc region
current GC count: 81

=====allocating 100mb allowing full blocking GC first Succeeded=====
=====allocating 200mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 121, after GC: 121
ended no gc region
current GC count: 161

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 200mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 202, after GC: 202
ended no gc region
current GC count: 242

=====allocating 200mb disallowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
By Design: 400 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see \"Latency Modes\" in http://go.microsoft.com/fwlink/?LinkId=522706 (Parameter 'totalSize')
current GC count: 321

=====allocating 400mb allowing full blocking GC first Succeeded=====
=====allocating 400mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
By Design: 400 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see \"Latency Modes\" in http://go.microsoft.com/fwlink/?LinkId=522706 (Parameter 'totalSize')
current GC count: 403

=====allocating 400mb disallowing full blocking GC first Succeeded=====
=====allocating 100mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 100 MB
100 MB SUCCEEDED, did 1 gen2 GCs
before GC: 445, after GC: 445
ended no gc region
current GC count: 487

=====allocating 100mb allowing full blocking GC first Succeeded=====
=====allocating 200mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 530, after GC: 531
We did GCs in no gc mode!!!
ended no gc region
End NoGC region: 200 MB InvalidOperationException Garbage collection was induced in NoGCRegion mode
current GC count: 571

=====allocating 200mb allowing full blocking GC first Failed=====
=====allocating 200mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 613, after GC: 632
We did GCs in no gc mode!!!
ended no gc region
End NoGC region: 200 MB InvalidOperationException Garbage collection was induced in NoGCRegion mode
current GC count: 672

=====allocating 200mb disallowing full blocking GC first Failed=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 714, after GC: 719
We did GCs in no gc mode!!!
ended no gc region
End NoGC region: 400 MB InvalidOperationException Garbage collection was induced in NoGCRegion mode
current GC count: 759

=====allocating 400mb allowing full blocking GC first Failed=====
=====allocating 400mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 801, after GC: 835
We did GCs in no gc mode!!!
ended no gc region
End NoGC region: 400 MB InvalidOperationException Garbage collection was induced in NoGCRegion mode
current GC count: 874

=====allocating 400mb disallowing full blocking GC first Failed=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 916, after GC: 917
We did GCs in no gc mode!!!
ended no gc region
End NoGC region: 400 MB InvalidOperationException Garbage collection was induced in NoGCRegion mode
current GC count: 957

=====allocating 400mb allowing full blocking GC first Failed=====
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\60895ced-77d4-4682-b9e9-ff6a1b0d4d04\\Payload
> C:\\dotnetbuild\\work\\60895ced-77d4-4682-b9e9-ff6a1b0d4d04\\Work\\322b9fee-2fee-4bb5-88fd-c814de3e5c54\\Exec\\GC\\API\\NoGCRegion\\NoGC\\NoGC.cmd
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment] 2019-07-31 17:42
@Maoni0

**Comment by Maoni0** [comment] 2019-07-31 20:05
was this test run with other tests running at the same time? it failed because there were GCs induced which suggests other tests running at the same time were inducing GCs.

**Comment by BruceForstall** [comment] 2019-07-31 20:15
@Maoni0 This is a standard test run (with some JIT stress modes enabled), which means it is run under the normal harness, which does run tests concurrently.

**Comment by Maoni0** [comment] 2019-07-31 20:18
this test is marked as not stress compatible though:

<GCStressIncompatible>true</GCStressIncompatible>

so it shouldn't be run concurrently with other tests.

**Comment by BruceForstall** [comment] 2019-07-31 20:29
There's no GCStress here. And that switch just skips the test if the `COMPlus_GCStress` variable is set.

**Comment by Maoni0** [comment] 2019-07-31 20:32
as I understand, this GCStressIncompatible is merely a way to say "don't run this test with other tests concurrently". if that's not the right way to express that, do you know what the right way is?

**Comment by BruceForstall** [comment] 2019-07-31 21:28
@echesakovMSFT @jashook @RussKeldorph Do you know if there's a way to mark a test "don't run this test with other tests concurrently" as @Maoni0 wants?

**Comment by jashook** [comment] 2019-07-31 21:38
We do not have any way of doing this today to my knowledge.

**Comment by Maoni0** [comment] 2019-07-31 22:20
is it possible to add that? some GC tests by design cannot be run with other tests.

**Comment by RussKeldorph** [comment] 2019-07-31 22:57
@Maoni0 Yes, it's possible, but you'd need to drive the necessary feature work.  You might need to move this test into its own test job separate from the others to avoid killing efficiency across the board.  I'd hope test harness, e.g. xUnit, changes aren't required, but I'm not sure.

/cc @sandreenko, since he was recently looking at possible solutions to problems caused by test parallelism.

**Comment by VincentBu** [comment] 2019-08-05 01:51
The test also failed in coreclr-r2r-extra: 
https://mc.dot.net/#/user/coreclr-r2r-extra/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fr2r~2Fcli~2F/20190803.1/workItem/PayloadGroup0/analysis/xunit/GC_API._NoGCRegion_NoGC_NoGC_~2F_NoGCRegion_NoGC_NoGC_cmd

**Comment by sergiy-k** [comment] 2019-08-23 01:26
Hi @VSadov, would it make sense to move this test into one of the categories that you are adding?

**Comment by jashook** [comment] 2019-08-23 01:32
Closing this as this was done recently https://github.com/dotnet/coreclr/pull/26236

**Closed by jashook** 2019-08-23 01:32 UTC
Labels: arch-x64, area-GC, os-windows

**Comment by VSadov** [comment] 2019-08-23 19:15
Yes, this falls into "long running GC" category. 
The test was marked as such in https://github.com/dotnet/coreclr/pull/26236
