### ISSUE TITLE
Assertion when coregen-ing Microsoft.CodeAnalysis.CSharp.dll on Linux

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2510] opened 2016-01-03 23:11 UTC
A failure in the Jit code. Happens with no stress modes or special flags - just debug build of the CoreCLR. Assertion failure in lsra.cpp, line 2330.
Command to get it:
crossgen /App_Paths . /Platform_Assemblies_Paths . /MissingDependenciesOK  ./Microsoft.CodeAnalysis.CSharp.dll

Also happens for System.Collection.Immutable.dll.

Stress modes or other flags make no difference for this assert. Running with JITMinOpts set runs clean with no assert.

Exact assertion failure:
Assert failure(PID 49645 [0x0000c1ed], Thread: 49645 [0xc1ed]): Assertion failed '!foundDiff' in 'Node[__Canon,AliasAndUsingDirective][System.__Canon,Microsoft.CodeAnalysis.CSharp.AliasAndUsingDirective]:Search(ref,ref):ref:this' (IL size 61)

    File: /home/lubo/SVS/src/jit/lsra.cpp Line: 2330
    Image: /home/lubo/coreclr-tests/Windows_NT.x64.Debug/Tests/coreoverlay/crossgen

Aborted (core dumped)

**Comment by sivarv** [comment] 2016-01-04 23:58
This is a duplicate of issue #2349 . Marking this one as closed by pasting repro steps to that issue.

**Closed by sivarv** 2016-01-04 23:58 UTC
Labels: bug, CodeGen, CrossGen/NGEN

**Comment by LLITCHEV** [comment] 2016-02-16 21:34
Still happens with the latest sources (as of 2/13/2016). Happens for System.Collections.Immutable.dll.

**Comment by LLITCHEV** [comment] 2016-02-18 22:24
Seems to pass. The failure I was observing was because the loader was picking up a crossgen from an old DNX installation instead the one from the current folder.
