### ISSUE TITLE
Add support for ARMv6

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#14932] opened 2017-11-08 17:57 UTC
@ivpadim commented on [Tue Nov 07 2017](https://github.com/dotnet/core/issues/1066)

# Include support for ARMv6

This was mentioned a while ago (issue [667](https://github.com/dotnet/core/issues/667)).
Is there a plan to support ARMv6? 
The only option right now is to install mono which works ok.

**Comment by shaggygi** [comment] 2017-11-09 00:58
Referencing https://github.com/dotnet/coreclr/issues/10605

**Comment by jkotas** [comment] 2017-11-09 01:05
Duplicate of #10605

**Closed by jkotas** 2017-11-09 01:05 UTC
