### ISSUE TITLE
Assert in JIT using the checked build Crossgen.exe

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#12093] opened 2017-06-05 20:26 UTC
Assert failure(PID 43448 [0x0000a9b8], Thread: 60444 [0xec1c]): Assertion failed '((regMask & emitThisGCrefRegs) && (ins == INS_add)) || ((regMask & emitThisByrefRegs) && (ins == INS_add || ins == INS_sub))' in 'Microsoft.AspNetCore.Server.Kestrel.Internal.System.Text.Encodings.Web.Utf8.UrlEncoder:DecodeCore(byref,byref,struct):bool' (IL size 457)

Repro: Enlist in the dev branch of JitBench

.\crossgen  /Platform_Assemblies_Paths . Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll

**Comment by briansull** [comment] 2017-06-07 22:36
This is related to Span

**Comment by briansull** [comment] 2017-07-12 21:32
```
Generating: N171 (  2,  3) [000582] ------------      t582 = *  CAST      long <- int REG rcx <l:$501, c:$500>
							V11 in reg r13 is becoming dead  [000537]
							Live regs: 0000A020 {rbp r13 r15} => 00008020 {rbp r15}
							Live vars: {V03 V11 V18} => {V03 V18}
IN001b:        movsxd   rcx, r13d
                                                             /--*  t579   byref  
                                                             +--*  t582   long   
Generating: N173 (  6,  6) [000584] ------------      t584 = *  ADD       byref  REG rcx <l:$1d0, c:$1cf>
							V18 in reg rbp is becoming dead  [000579]
							Live regs: 00008020 {rbp r15} => 00008000 {r15}
							Live vars: {V03 V18} => {V03}
							Byref regs: 00000020 {rbp} => 00000000 {}
IN001c:        add      rcx, rbp
							Byref regs: 00000000 {} => 00000002 {rcx}
                                                             /--*  t584   byref  
Generating: N175 ( 10,  9) [000544] DA----------             *  STORE_LCL_VAR byref  V16 tmp2         d:3 rcx REG rcx
```

**Comment by briansull** [comment] 2017-08-23 22:10
@russellhadley 
Should repro with SuperPMI data

**Comment by AndyAyersMS** [comment] 2017-10-13 15:58
@briansull is this still relevant?

**Comment by AndyAyersMS** [comment] 2018-12-13 22:11
See also #19257

**Comment by AndyAyersMS** [comment] 2019-02-07 04:49
Jit issue. We should look at this for 3.0.

**Comment by AndyAyersMS** [comment] 2019-02-11 19:53
Will investigate.

**Comment by AndyAyersMS** [comment] 2019-02-12 01:43
This bug is ancient, and recent asp.net doesn't seem to have a method like that anymore. Am going to close this.

**Comment by janvorli** [comment] 2019-09-20 16:17
I can now consistently reproduce this assert when running new crossgen2 on System.Private.CoreLib.dll, so I am reopening the issue.
Here are the repro steps on Windows:
* build.cmd
* .dotnet\dotnet.exe .\bin\Product\Windows_NT.x64.Debug\crossgen2\crossgen2.dll .\bin\Product\Windows_NT.x64.Debug\System.Private.CoreLib.dll -o:.\bin\Product\Windows_NT.x64.Debug\System.Private.CoreLib2.dll --targetarch=x64 -O

So it has become an urgent problem, since we need to be able to run crossgen2 on the System.Private.CoreLib.dll.

**Comment by janvorli** [comment] 2019-09-20 17:56
FYI: @dotnet/crossgen-contrib

**Comment by cshung** [comment] 2019-09-20 20:18
I was looking into it for a few days now. It looks like we have two sources of truth about which register contains GC references. The instruction description contains a copy `id->idGCRef()`, and the emitter contains a copy `emitter->emitThisGcRef`, and the two copies are not synchronized.

I still need more time to investigate this.

**Comment by cshung** [comment] 2019-09-24 17:53
In this comment, I would like to write about my findings on this issue. This is currently a work-in-progress and is by-no-means complete.

The comment is divided into three parts:

1. Repro Steps
2. Analysis 
3. Next steps

# Repro Steps
To make investigation easy, I have created a branch [here](https://github.com/cshung/coreclr/tree/dev/andrewau/gc-info-bug-investigation).

The branch has a script named `cpaot.cmd` which simply invoke `crossgen2.exe` using `cpaot.rsp` with the right flags on to reproduce the bug. The JIT is hardcoded to do a full JIT dump for the faulty method, and crossgen2 is instructed to skip everything but the faulty method.

The resulting process can be debugged using [Time Travel Tracing](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview), which make debugging a lot easier.

# Analysis

Here is the assertion:

```
IN001e: 000077 4863C0               movsxd   rax, eax
C:\Dev\coreclr\src\jit\emitxarch.cpp:11529
Assertion failed '((regMask & emitThisGCrefRegs) && (ins == INS_add)) || ((regMask & emitThisByrefRegs) && (ins == INS_add || ins == INS_sub))' in 'System.Globalization.CharUnicodeInfo:InternalGetCategoryValue(int,int):ubyte' (IL size 152)
```

The obvious thing to do is to inspect [`emitxarch.cpp`](https://github.com/cshung/coreclr/blob/64dd59db80b17495da50f7c850530a0792e680d8/src/jit/emitxarch.cpp#L11529) on the associated lines, and I did. The code is generating an ADD instruction and it asserts that one of the registers should either be a GC ref or a GC byref as indicated on `this->emitThisGCrefRegs` or `this->emitThisByrefRegs`.

A [few lines above](https://github.com/cshung/coreclr/blob/64dd59db80b17495da50f7c850530a0792e680d8/src/jit/emitxarch.cpp#L11520) tell us why we had this assertion. The instruction description id has the GC ref set. So we knew this instruction should be operating on a byref.

Next, we need to read the JIT dump. Notice that `IN001e` was the last instruction printed, meaning `IN001f` is most likely to be the instruction that caused the assertion. There is only one occurence of `IN001f`, and here it is:

```
Generating: N175 (  4,  5) [000064] ------------        t64 = *  ADD       byref  REG rax <l:$383, c:$382>
							V44 in reg rdx is becoming dead  [000063]
							Live regs: 000000C4 {rdx rsi rdi} => 000000C0 {rsi rdi}
							Live vars: {V00 V01 V44} => {V00 V01}
							Byref regs: 00000004 {rdx} => 00000000 {}
IN001f:        add      rax, rdx
							Byref regs: 00000000 {} => 00000001 {rax}
```

Already we are seeing something interesting going on here. `rdx` should be a byref before we generate `IN001f`. But the assert says it wasn't. (In fact, at the time of assertion, `this->emitThisByrefRegs` is 0). There must be something wrong with keeping that variable up to date.

Tracing further backward in the JIT dump, we see that `rdx` was introduced by `IN0016` as follow (with a few more subsequent lines captured for further discussion):

```
Generating: N123 (  3, 10) [000242] ------------       t242 =    CNS_INT(h) long   0x420318 static Fseq[7802354AE39660744010DD869AC44C40E9E989E7] REG rdx $204
IN0016:        lea      rdx, [(reloc 0x420318)]
                                                              /--*  t242   long   
Generating: N125 (  6, 12) [000312] DA--G-------              *  STORE_LCL_VAR long   V22 tmp16        d:1 rdx REG rdx
							V22 in reg rdx is becoming live  [000312]
							Live regs: 000000C1 {rax rsi rdi} => 000000C5 {rax rdx rsi rdi}
							Live vars: {V00 V01 V02} => {V00 V01 V02 V22}
genIPmappingAdd: ignoring duplicate IL offset 0x31
Generating: N127 (???,???) [000622] ------------                 IL_OFFSET void   IL offset: 0x31 REG NA
Generating: N129 (  1,  1) [000317] ------------       t317 =    LCL_VAR   byref  V22 tmp16        u:1 rdx (last use) REG rdx $204
                                                              /--*  t317   byref  
Generating: N131 (  1,  3) [000288] DA----------              *  STORE_LCL_VAR byref  V46 tmp40        d:1 rdx REG rdx
							V22 in reg rdx is becoming dead  [000317]
							Live regs: 000000C5 {rax rdx rsi rdi} => 000000C1 {rax rsi rdi}
							Live vars: {V00 V01 V02 V22} => {V00 V01 V02}
							V46 in reg rdx is becoming live  [000288]
							Live regs: 000000C1 {rax rsi rdi} => 000000C5 {rax rdx rsi rdi}
							Live vars: {V00 V01 V02} => {V00 V01 V02 V46}
							Byref regs: 00000000 {} => 00000004 {rdx}
genIPmappingAdd: ignoring duplicate IL offset 0x31
Generating: N133 (???,???) [000623] ------------                 IL_OFFSET void   IL offset: 0x31 REG NA
```

`IN0016` was generated by the instruction description created from `t242`. The `id->_idGCref` state is computed in the following stack.

```
 # Child-SP          RetAddr           Call Site
00 000000fb`d2b7bab0 00007ffe`eb409b11 clrjitilc!emitter::instrDesc::idGCref+0x4e [C:\Dev\coreclr\src\jit\emit.h @ 964] 
01 000000fb`d2b7bae0 00007ffe`eb6be07a clrjitilc!emitter::emitAllocAnyInstr+0x331 [C:\Dev\coreclr\src\jit\emit.cpp @ 1361] 
02 000000fb`d2b7bb20 00007ffe`eb6d6477 clrjitilc!emitter::emitAllocInstrAmd+0x4a [C:\Dev\coreclr\src\jit\emit.h @ 1914] 
03 000000fb`d2b7bb50 00007ffe`eb6ce94e clrjitilc!emitter::emitNewInstrAmd+0x57 [C:\Dev\coreclr\src\jit\emitxarch.cpp @ 2461] 
04 000000fb`d2b7bba0 00007ffe`eb6bba47 clrjitilc!emitter::emitIns_R_AI+0xfe [C:\Dev\coreclr\src\jit\emitxarch.cpp @ 5258] 
05 000000fb`d2b7bc10 00007ffe`eb6ba807 clrjitilc!CodeGen::instGen_Set_Reg_To_Imm+0x127 [C:\Dev\coreclr\src\jit\codegenxarch.cpp @ 485] 
06 000000fb`d2b7bc60 00007ffe`eb6b04b5 clrjitilc!CodeGen::genSetRegToConst+0xe7 [C:\Dev\coreclr\src\jit\codegenxarch.cpp @ 520] 
07 000000fb`d2b7bce0 00007ffe`eb3d0c2a clrjitilc!CodeGen::genCodeForTreeNode+0x2b5 [C:\Dev\coreclr\src\jit\codegenxarch.cpp @ 1650] 
```

Frame 7 is taking the `gtType` of the tree, passing it as `targetType`. Frame 6 would have turn the `newSize` to have the `EA_BYREF_FLG` if the target type were `TYP_BYREF`. But the target type was `TYP_LONG`, so no conversion happened there. The `size` (which really is a `emitAttr`) is passed to frame 1 and eventually leads to `GCT_NONE`.

The fact that `id->_idGCref` is `GCT_NONE` caused us to miss the opportunity to change the `this->emitThisByrefRegs`. It could have been updated if `id->_idGCref` was set properly. 

Note that while `t317` has the right `byref` type, it does not generate an instruction, and thus have no chance to fix the `this->emitThisByrefRegs`.

To probe further upstream, we look at `t242`. There are 35 occurrence of `t242` in the JIT dump, the first one indicate where does it comes from. It is the used to compute the first argument to ``System.ReadOnlySpan`1..ctor``. 

```
In Compiler::impImportCall: opcode is newobj, kind=0, callRetType is void, structSize is 0


               [000253] I-CXG-------              *  CALL r2r_ind void   System.ReadOnlySpan`1..ctor (exactContextHnd=0x0000000000420029)
               [000252] ------------ this in rcx  +--*  ADDR      byref 
               [000251] ------------              |  \--*  LCL_VAR   struct V19 tmp13        
               [000246] --CXG------- arg1         +--*  COMMA     long  
               [000245] --CXG-------              |  +--*  CALL help r2r_ind byref  HELPER.CORINFO_HELP_READYTORUN_STATIC_BASE
               [000242] ------------              |  \--*  CNS_INT(h) long   0x420318 static Fseq[7802354AE39660744010DD869AC44C40E9E989E7]
               [000247] ------------ arg2         \--*  CNS_INT   int    0x1740
```

`t317` was introduced slightly later, it is meant to be the inlinee return expression:

```
    Inlinee Return expression (before normalization)  =>
               [000317] ------------              *  LCL_VAR   byref  V22 tmp16        
```

The type of the local helped us here, now we know it is byref, but it isn't useful for the emitter since it doesn't generate an instruction.

# Next Steps
Apparently, the code in `genSetRegToConst` knew `targetType` could be `TYP_BYREF`. In my opinion, we should think about how to gear the code towards that code path. To show that this strategy would work, I experimented with this hack:

```
--- a/src/jit/emit.cpp
+++ b/src/jit/emit.cpp
@@ -1348,7 +1348,7 @@ void* emitter::emitAllocAnyInstr(size_t sz, emitAttr opsz)
         id->idGCref(GCT_GCREF);
         id->idOpSize(EA_PTRSIZE);
     }
-    else if (EA_IS_BYREF(opsz))
+    else if (EA_IS_BYREF(opsz) || emitInsCount == 0X16)
     {
         /* A special value indicates a Byref pointer value */
```

This is a total hack - I just wanted to see what would happen. The compilation of that single method passed. Apparently the hack is no good for any other thing so I didn't even bother.

The is already a very long comment, and I will stop here. Next step, I will try to see if I can track down the construction of `t242` and see why the `gtType` is not `TYP_BYREF`.

**Comment by AndyAyersMS** [comment] 2019-09-24 18:15
This is a known issue, see #22558 

There is no easy fix.

We may be able to do something targeted for this case, but it would need to happen early on, in the importer or the inliner.

**Comment by briansull** [comment] 2019-09-24 18:30
Issue #22558 is about BuildTools

**Comment by AndyAyersMS** [comment] 2019-09-24 18:43
Try #22838

**Comment by danmosemsft** [comment] 2019-09-26 17:09
@cshung I set milestone 3.0.x simply because it can't be 3.0 any more. If this isn't something we'd service for please set a different milestone.

**Comment by AndyAyersMS** [comment] 2019-09-26 17:13
Crossgen2 is not a 3.x thing, seems like this should be 5.x or future.

**Comment by MichalStrehovsky** [comment] 2019-10-02 12:35
The reason why crossgen2 was hitting this but not crossgen was a bug in crossgen2 that I'm fixing in #26987. This could still be a RyuJIT bug (the difference was about whether we reported a containing type of a RVA-static field as being pre-initialized), but it can't be hit with crossgen2 anymore either.

**Comment by BruceForstall** [comment] 2019-12-12 23:03
Given that this is no longer impacting (and already tracked with #22838), I'm closing this.

**Closed by BruceForstall** 2019-12-12 23:03 UTC
Labels: area-CodeGen, bug
