### ISSUE TITLE
[ARM32] Legacy vs. Ryu performance

### ISSUE THREAD

**Issue by mskvortsov** [dotnet/coreclr#12971] opened 2017-07-21 12:50 UTC
There is a slight regression of 4% on average in terms of code size between old and new backends, as measured on `JIT/Performance/CodeQuality` tests (S.P.C.dll methods were accounted too).

Sometimes the difference is quite large, for example test case `JIT/Performance/CodeQuality/SciMark`, method `SciMark2.SparseCompRow:matmult`:

- 492 bytes when compiled by Legacy,
- 692 bytes when compiled by Ryu.

Full disasm output:
[SciMark2.SparseCompRow:matmult.legacy.txt](https://gist.githubusercontent.com/mskvortsov/08adaa2b5693d15a3a8279742732ffc1/raw/0b1b56535598db91281e55684ab78333a764ad6d/SciMark2.SparseCompRow:matmult.legacy.txt)
[SciMark2.SparseCompRow:matmult.ryu.txt](https://gist.githubusercontent.com/mskvortsov/08adaa2b5693d15a3a8279742732ffc1/raw/0b1b56535598db91281e55684ab78333a764ad6d/SciMark2.SparseCompRow:matmult.ryu.txt)

One of the most significant issues seems to be the register allocator tends to allocate higher numbered registers which prevents to emit more compact Thumb-1 16-bit instruction forms.
Legacy:
```
G_M5155_IG14:
0000A0  2301           movs    r3, 1

G_M5155_IG15:
0000A2  2E00           cmp     r6, 0
0000A4  D101           bne     SHORT G_M5155_IG16
0000A6  2100           movs    r1, 0
0000A8  E000           b       SHORT G_M5155_IG17

G_M5155_IG16:
0000AA  2101           movs    r1, 1

G_M5155_IG17:
0000AC  400B           ands    r3, r1
0000AE  D030           beq     SHORT G_M5155_IG28

G_M5155_IG18:
0000B0  2A00           cmp     r2, 0
0000B2  DA01           bge     SHORT G_M5155_IG19
0000B4  2300           movs    r3, 0
0000B6  E000           b       SHORT G_M5155_IG20

G_M5155_IG19:
0000B8  2301           movs    r3, 1

G_M5155_IG20:
0000BA  2D00           cmp     r5, 0
0000BC  DA01           bge     SHORT G_M5155_IG21
0000BE  2100           movs    r1, 0
0000C0  E000           b       SHORT G_M5155_IG22

G_M5155_IG21:
0000C2  2101           movs    r1, 1
```
Ryu:
```
G_M5155_IG14:
0000BA  F04F 0901      mov     r9, 1

G_M5155_IG15:
0000BE  2900           cmp     r1, 0
0000C0  D102           bne     SHORT G_M5155_IG16
0000C2  F04F 0C00      mov     r12, 0
0000C6  E001           b       SHORT G_M5155_IG17

G_M5155_IG16:
0000C8  F04F 0C01      mov     r12, 1

G_M5155_IG17:
0000CC  EA19 0C0C      ands    r12, r9, r12
0000D0  F1BC 0F00      cmp     r12, 0
0000D4  D053           beq     SHORT G_M5155_IG30

G_M5155_IG18:
0000D6  F1BE 0F00      cmp     lr, 0
0000DA  DA02           bge     SHORT G_M5155_IG19
0000DC  F04F 0C00      mov     r12, 0
0000E0  E001           b       SHORT G_M5155_IG20

G_M5155_IG19:
0000E2  F04F 0C01      mov     r12, 1

G_M5155_IG20:
0000E6  F1B8 0F00      cmp     r8, 0
0000EA  DA02           bge     SHORT G_M5155_IG21
0000EC  F04F 0900      mov     r9, 0
0000F0  E001           b       SHORT G_M5155_IG22

G_M5155_IG21:
0000F2  F04F 0901      mov     r9, 1
```

cc @dotnet/arm32-contrib 

category:cq
theme:register-allocator
skill-level:expert
cost:large

**Comment by mikedn** [comment] 2017-07-21 13:10
> One of the most significant issues seems to be the register allocator tends to allocate higher numbered registers which prevents to emit more compact Thumb-1 16-bit instruction forms.

Related issue: #11349

x64 has the same problem, registers r8-r15 require a REX prefix that adds one byte to the instruction encoding.

**Comment by RussKeldorph** [comment] 2017-07-21 15:19
@dotnet/jit-contrib

**Comment by BruceForstall** [comment] 2017-07-24 16:04
cc @dotnet/arm32-contrib

**Comment by mskvortsov** [comment] 2017-07-27 13:25
Top 20 code size regressions in JIT/Performance/CodeQuality methods by difference in byte count:
```
 diff   old   new method                                                                                                test
----------------------------------------------------------------------------------------------------------------------------------------------------------
+3146 13560 16706 Product:CreateLists()                                                                                 Linq/Linq
 +548  2624  3172 ByteMark:read_comfile(ref)                                                                            Bytemark/Bytemark
 +522  2784  3306 LUDecomp:ludcmp(ref,int,ref,byref):int                                                                Bytemark/Bytemark
 +510  2590  3100 Benchstone.BenchI.MulMatrix:Inner(ref,ref,ref)                                                        BenchI/MulMatrix/MulMatrix
 +392  1848  2240 AssignJagged:second_assignments(ref,ref)                                                              Bytemark/Bytemark
 +338  2334  2672 Neural:read_data_file():this                                                                          Bytemark/Bytemark
 +314  1670  1984 NeuralJagged:read_data_file():this                                                                    Bytemark/Bytemark
 +310  1616  1926 Camera:Create(struct,struct):ref                                                                      SIMD/RayTracer/RayTracer
 +266  3120  3386 ByteMark:ExecuteCore(ref):int:this                                                                    Bytemark/Bytemark
 +244   768  1012 NeuralJagged:.cctor()                                                                                 Bytemark/Bytemark
 +224  1394  1618 V8.Crypto.RSAKey:generate(int,ref):this                                                               V8/Crypto/Crypto
 +220  2066  2286 AssignRect:second_assignments(ref,ref)                                                                Bytemark/Bytemark
 +216  1564  1780 V8.Crypto.BigInteger:modInverse(ref):ref:this                                                         V8/Crypto/Crypto
 +212  1360  1572 V8.Crypto.BigInteger:modPow(ref,ref):ref:this                                                         V8/Crypto/Crypto
 +210  1570  1780 Benchstone.BenchF.Whetsto:Bench():bool                                                                BenchF/Whetsto/Whetsto
 +200   492   692 SciMark2.SparseCompRow:matmult(ref,ref,ref,ref,ref,int)                                               SciMark/SciMark
 +192  1034  1226 SciMark2.LU:factor(ref,ref):int                                                                       SciMark/SciMark
 +186  1470  1656 Algorithms.FractalRenderer:SelectRender(ref,ref,bool,bool,bool,bool,bool):ref                         SIMD/ConsoleMandel/ConsoleMandel
 +186  1434  1620 V8.Crypto.BigInteger:divRemTo(ref,ref,ref):this                                                       V8/Crypto/Crypto
 +184   748   932 EMFloatClass:DoEmFloatIteration(ref,ref,ref,int,int):long                                             Bytemark/Bytemark
```
Full dataset is at [cq-codesize-by-diff.txt](https://gist.github.com/mskvortsov/1d8d5f08ec8da4fe180172fc6f10c180/raw/a1946d8b069973723327bb56228ce192101a7cdb/cq-codesize-by-diff.txt) (entries with a difference of less than 16 bytes are filtered out).

Top 20 code size regressions in JIT/Performance/CodeQuality methods by percentage:
```
      %   old   new method                                                                                                test
-----------------------------------------------------------------------------------------------------------------------------------
 +76.92    26    46 ByteMark:TicksToSecs(long):int                                                                        Bytemark/Bytemark
 +40.65   492   692 SciMark2.SparseCompRow:matmult(ref,ref,ref,ref,ref,int)                                               SciMark/SciMark
 +38.46    52    72 SciMark2.Random:.ctor(int):this                                                                       SciMark/SciMark
 +37.50   336   462 Benchstone.BenchF.BenchMk2:Bench():bool                                                               BenchF/BenchMk2/BenchMk2
 +36.00   200   272 BenchmarksGame.pidigits:extract_digit(int):int:this                                                   BenchmarksGame/pidigits/pi-digits
 +35.90    78   106 V8.Richards.Scheduler:queue(ref):ref:this                                                             V8/Richards/Richards
 +33.33   402   536 BenchmarksGame.pidigits:next_term(int):this                                                           BenchmarksGame/pidigits/pi-digits
 +32.02   356   470 V8.Crypto.Support:Setup()                                                                             V8/Crypto/Crypto
 +31.77   768  1012 NeuralJagged:.cctor()                                                                                 Bytemark/Bytemark
 +31.49   362   476 Benchstone.BenchF.BenchMrk:Bench():bool                                                               BenchF/BenchMrk/BenchMrk
 +29.87   308   400 BenchmarksGame.pidigits:eliminate_digit(int):this                                                     BenchmarksGame/pidigits/pi-digits
 +29.28   362   468 SeekUnroll:ManualTimerLoop(byref,byref)                                                               SIMD/SeekUnroll/SeekUnroll
 +29.25   506   654 V8.Crypto.BigInteger:subTo(ref,ref):this                                                              V8/Crypto/Crypto
 +28.57    70    90 <>c__DisplayClass12_0:<FillAllSpan>b__0(int):this                                                     Span/SpanBench
 +28.57    70    90 <>c__DisplayClass16_0:<FillAllReverseSpan>b__0(int):this                                              Span/SpanBench
 +27.35   234   298 SeekUnroll:InnerLoop(byref,byref)                                                                     SIMD/SeekUnroll/SeekUnroll
 +27.27    88   112 Benchstone.BenchI.EightQueens:.cctor()                                                                BenchI/8Queens/8Queens
 +27.03    74    94 <>c__DisplayClass4_0:<Ref>b__0(int):ubyte:this                                                        Span/Indexer
 +27.03    74    94 <>c__DisplayClass6_0:<Fixed1>b__0(int):ubyte:this                                                     Span/Indexer
 +27.03    74    94 <>c__DisplayClass8_0:<Fixed2>b__0(int):ubyte:this                                                     Span/Indexer
```
Full dataset is at [cq-codesize-by-percentage.txt](https://gist.github.com/mskvortsov/1d8d5f08ec8da4fe180172fc6f10c180/raw/a1946d8b069973723327bb56228ce192101a7cdb/cq-codesize-by-percentage.txt) (entries with a difference of less than 16 bytes are filtered out).

**Comment by mskvortsov** [comment] 2017-07-27 13:40
Top 50 regressions in System.Private.CoreLib.dll methods by byte count:
```
 diff   old   new method
--------------------------------------------------------------------------------------------------------------------------
+1374  4558  5932 System.Globalization.TimeSpanParse:ProcessTerminal_HMS_F_D(byref,int,byref):bool
+1116  4428  5544 System.Globalization.TimeSpanParse:ProcessTerminal_HM_S_D(byref,int,byref):bool
 +896  7550  8446 System.DefaultBinder:BindToMethod(int,ref,byref,ref,ref,ref,byref):ref:this
 +770  2718  3488 System.DateTimeFormat:FormatCustomized(struct,ref,ref,struct):ref
 +700  2740  3440 System.Diagnostics.Tracing.EventProvider:WriteEvent(byref,int,int,int,ref):bool:this
 +578  1782  2360 System.Text.UTF8Encoding:GetBytes(int,int,int,int,ref):int:this
 +526  1420  1946 System.TimeZoneInfo:GetIsDaylightSavingsFromUtc(struct,int,struct,ref,struct,byref,ref):bool
 +466  2202  2668 System.Text.UnicodeEncoding:GetChars(int,int,int,int,ref):int:this
 +436  2020  2456 System.Globalization.TimeSpanParse:TryParseByFormat(ref,ref,int,byref):bool
 +430  1946  2376 System.Text.UnicodeEncoding:GetBytes(int,int,int,int,ref):int:this
 +420  1808  2228 System.Text.UTF8Encoding:GetChars(int,int,int,int,ref):int:this
 +406  3350  3756 System.Diagnostics.Tracing.EventSource:CreateManifestAndDescriptors(ref,ref,ref,int):ref
 +388  5618  6006 System.Globalization.CalendricalCalculationsHelper:SumLongSequenceOfPeriodicTerms(double):double
 +362  1174  1536 System.Number:ParseNumber(byref,int,byref,ref,ref,bool):bool
 +344  1194  1538 System.Text.StringBuilder:AppendFormatHelper(ref,ref,struct):ref:this
 +336   946  1282 System.Type:FindMembers(int,int,ref,ref):ref:this
 +332  2042  2374 System.Globalization.TimeSpanFormat:FormatCustomized(struct,ref,ref):ref
 +310  1286  1596 System.Text.UnicodeEncoding:GetByteCount(int,int,ref):int:this
 +296   978  1274 System.Reflection.AssemblyName:EscapeString(ref,int,int,ref,byref,bool,char,char,char):ref
 +284  1342  1626 System.Text.UnicodeEncoding:GetCharCount(int,int,ref):int:this
 +282  3602  3884 System.Reflection.Emit.CustomAttributeBuilder:InitCustomAttributeBuilder(ref,ref,ref,ref,ref,ref):this
 +262  1208  1470 System.Text.ASCIIEncoding:GetBytes(int,int,int,int,ref):int:this
 +242  1378  1620 System.Reflection.CustomAttributeData:.ctor(ref,struct):this
 +236  1220  1456 System.Text.UTF8Encoding:GetByteCount(int,int,ref):int:this
 +226   424   650 System.TimeZoneInfo:CompareAdjustmentRuleToDateTime(ref,ref,struct,struct,bool):int:this
 +226   700   926 System.TimeZoneInfo:GetIsDaylightSavings(struct,ref,struct,int):bool
 +210  3382  3592 System.RuntimeType:InvokeMember(ref,int,ref,ref,ref,ref,ref,ref):ref:this
 +210   734   944 System.TimeZoneInfo:GetAdjustmentRules():ref:this
 +204  1090  1294 System.Text.UTF32Encoding:GetChars(int,int,int,int,ref):int:this
 +202  1228  1430 System.DefaultBinder:SelectMethod(int,ref,ref,ref):ref:this
 +202  3996  4198 System.DateTimeParse:ParseByFormat(byref,byref,byref,ref,byref):bool
 +198  1200  1398 System.Text.UTF7Encoding:GetBytes(int,int,int,int,ref):int:this
 +192  1960  2152 System.Globalization.IdnMapping:PunycodeEncode(ref):ref
 +184  1350  1534 System.Threading.ReaderWriterLockSlim:TryEnterReadLockCore(struct):bool:this
 +182   768   950 System.DefaultBinder:FindMostSpecific(ref,ref,ref,ref,ref,ref,ref,ref):int
 +180   526   706 System.Reflection.CustomAttributeData:get_NamedArguments():ref:this
 +178  1138  1316 System.Reflection.CustomAttributeTypedArgument:ToString(bool):ref:this
 +178  1194  1372 System.Text.Latin1Encoding:GetBytes(int,int,int,int,ref):int:this
 +168   566   734 System.CurrentSystemTimeZone:GetUtcOffsetFromUniversalTime(struct,byref):long:this
 +162   656   818 System.DateTimeFormat:FormatCustomizedTimeZone(struct,struct,ref,int,bool,ref)
 +162   614   776 System.Globalization.DateTimeFormatInfo:Tokenize(int,byref,byref,byref):bool:this
 +158   528   686 System.TimeZoneInfo:GetUtcOffsetFromUtc(struct,ref,byref,byref):struct
 +158  1034  1192 System.Text.UTF32Encoding:GetBytes(int,int,int,int,ref):int:this
 +156   732   888 System.TimeZoneInfo:ConvertTime(struct,ref,ref,int,ref):struct
 +150   728   878 System.Reflection.CustomAttributeTypedArgument:.ctor(ref,struct):this
 +148   728   876 System.Globalization.TimeSpanParse:ProcessTerminal_DHMSF(byref,int,byref):bool
 +148   702   850 System.Reflection.Associates:AssignAssociates(struct,int,ref,ref,byref,byref,byref,byref,byref,byref,byref,byref)
 +146  1526  1672 System.DefaultBinder:SelectProperty(int,ref,ref,ref,ref):ref:this
 +144   636   780 System.TimeZoneInfo:GetIsAmbiguousTime(struct,ref,struct):bool
 +144   636   780 System.TimeZoneInfo:GetIsInvalidTime(struct,ref,struct):bool
```
Here is the full data: [spc-codesize-by-diff.txt](https://gist.github.com/mskvortsov/1d8d5f08ec8da4fe180172fc6f10c180/raw/a1946d8b069973723327bb56228ce192101a7cdb/spc-codesize-by-diff.txt) and [spc-codesize-by-percentage.txt](https://gist.github.com/mskvortsov/1d8d5f08ec8da4fe180172fc6f10c180/raw/a1946d8b069973723327bb56228ce192101a7cdb/spc-codesize-by-percentage.txt) (entries with a difference of less than 16 bytes are filtered out).
The total size of S.P.C.ni.dll grew from 13766656 bytes to 13774848, i.e. insignificantly.

**Comment by mskvortsov** [comment] 2017-07-27 16:04
Just for reference, here is full disasm output from crossgen'ing SPC.dll:
[System.Private.CoreLib.old.disasm.gz](https://gist.github.com/mskvortsov/ae5bdca8083fe8e3300f3fbed467badb/raw/1b3885369b195954fc9d07bf5909f65128f05ce1/System.Private.CoreLib.old.disasm.gz)
[System.Private.CoreLib.new.disasm.gz](https://gist.github.com/mskvortsov/ae5bdca8083fe8e3300f3fbed467badb/raw/1b3885369b195954fc9d07bf5909f65128f05ce1/System.Private.CoreLib.new.disasm.gz)

SPC.dll version is of CoreCLR commit `102bea2e12`, the same as the data above was collected on.

Note that currently there are some failures in the new backend, so the "old" disasm contains 24156 methods, and the "new" one contains 24154, all except these two:
```
System.Math:Clamp(double,double,double):double
ResourceEnumerator:get_Entry():struct:this
```

**Comment by mskvortsov** [comment] 2017-07-28 09:31
Method `System.Globalization.CultureData:.ctor():this`, Legacy (on the left) emits 56 bytes, Ryu emits 100 bytes:
```
G_M759_IG01:                                  G_M759_IG01:                               
000000  B508           push    {r3,lr}        000000  B508           push    {r3,lr}     
                                                                                         
G_M759_IG02:                                  G_M759_IG02:                               
000002  F04F 33FF      mov     r3, -1         000002  F04F 33FF      mov     r3, -1      
000006  F8C0 30C0      str     r3, [r0+192]   000006  F8C0 30C0      str     r3, [r0+192]
00000A  F8C0 30C4      str     r3, [r0+196]   00000A  F04F 33FF      mov     r3, -1      
00000E  F8C0 30D0      str     r3, [r0+208]   00000E  F8C0 30C4      str     r3, [r0+196]
000012  F8C0 30D4      str     r3, [r0+212]   000012  F04F 33FF      mov     r3, -1      
000016  F8C0 30E4      str     r3, [r0+228]   000016  F8C0 30D0      str     r3, [r0+208]
00001A  F8C0 30E8      str     r3, [r0+232]   00001A  F04F 33FF      mov     r3, -1      
00001E  F8C0 30EC      str     r3, [r0+236]   00001E  F8C0 30D4      str     r3, [r0+212]
000022  F8C0 30F0      str     r3, [r0+240]   000022  F04F 33FF      mov     r3, -1      
000026  F8C0 30F4      str     r3, [r0+244]   000026  F8C0 30E4      str     r3, [r0+228]
00002A  F8C0 30F8      str     r3, [r0+248]   00002A  F04F 33FF      mov     r3, -1      
00002E  F8C0 30FC      str     r3, [r0+252]   00002E  F8C0 30E8      str     r3, [r0+232]
000032  F8C0 3100      str     r3, [r0+256]   000032  F04F 33FF      mov     r3, -1      
                                              000036  F8C0 30EC      str     r3, [r0+236]
G_M759_IG03:                                  00003A  F04F 33FF      mov     r3, -1      
000036  BD08           pop     {r3,pc}        00003E  F8C0 30F0      str     r3, [r0+240]
                                              000042  F04F 33FF      mov     r3, -1      
                                              000046  F8C0 30F4      str     r3, [r0+244]
                                              00004A  F04F 33FF      mov     r3, -1      
                                              00004E  F8C0 30F8      str     r3, [r0+248]
                                              000052  F04F 33FF      mov     r3, -1      
                                              000056  F8C0 30FC      str     r3, [r0+252]
                                              00005A  F04F 33FF      mov     r3, -1      
                                              00005E  F8C0 3100      str     r3, [r0+256]
                                                                                         
                                              G_M759_IG03:                               
                                              000062  BD08           pop     {r3,pc}     
```
IR contains a row of the following fragments, all exactly the same except lea offset:
```
Generating: N003 (  6,  8) [000005] -------------                IL_OFFSET void   IL offset: 0x0 REG NA
Generating: N005 (  1,  1) [000001] -------------        t1 =    LCL_VAR   ref    V00 this         u:2 r0 REG r0 $80
                                                              ┌──▌  t1     ref    
Generating: N007 (???,???) [000104] -c-----------      t104 = ▌  LEA(b+192) byref  REG NA
Generating: N009 (  1,  3) [000002] -------------        t2 =    CNS_INT   int    -1 REG r3 $41
IN0001:             mov     r3, -1
                                                              ┌──▌  t104   byref  
                                                              ├──▌  t2     int    
Generating: N011 (???,???) [000092] -A-XG--------             ▌  STOREIND  int    REG NA
IN0002:             str     r3, [r0+192]
```
I guess a solution, considering linearity of the LIR, would be to pull all the identical CNS_INTs into a new lclvar.

**Comment by mskvortsov** [comment] 2017-07-28 10:58
Here is a vivid example of inefficient long/struct handling, it is quite common across the regression list:
```csharp
public static TimeSpan FromTicks(long value)
{
    return new TimeSpan(value);
}
```
Legacy vs. Ryu:
```
G_M11629_IG01:                              G_M11629_IG01:                              
000000  B508           push    {r3,lr}      000000  B500           push    {lr}         
                                            000002  B085           sub     sp, 20       
G_M11629_IG02:                              000004  9202           str     r2, [sp+0x08]
000002  6002           str     r2, [r0]     000006  9303           str     r3, [sp+0x0c]
000004  6043           str     r3, [r0+4]                                               
                                            G_M11629_IG02:                              
G_M11629_IG03:                              000008  9B02           ldr     r3, [sp+0x08]
000006  BD08           pop     {r3,pc}      00000A  9A03           ldr     r2, [sp+0x0c]
                                            00000C  9300           str     r3, [sp]     
                                            00000E  9201           str     r2, [sp+0x04]
                                            000010  4603           mov     r3, r0       
                                            000012  9A00           ldr     r2, [sp]     
                                            000014  601A           str     r2, [r3]     
                                            000016  9A01           ldr     r2, [sp+0x04]
                                            000018  605A           str     r2, [r3+4]   
                                                                                        
                                            G_M11629_IG03:                              
                                            00001A  B005           add     sp, 20       
                                            00001C  BD00           pop     {pc}
```

**Comment by mskvortsov** [comment] 2017-08-22 18:37
The running time data for `JIT/Performance/CodeQuality` tests except `Burgers` and `Spanbench` (each test was launched 7 times):
```
                         |       legacy time, s        |         ryu time, s
          test    avg %  |    min    max    avg     sd |    min    max    avg     sd
-------------------------+-----------------------------+----------------------------
         Adams    +1.66  |   3.60   3.62   3.61  0.006 |   3.66   3.69   3.67  0.009
      BenchMk2   -20.83  |   6.51   6.59   6.53  0.027 |   5.15   5.17   5.17  0.007
      BenchMrk   -21.13  |   6.52   6.60   6.53  0.028 |   5.14   5.16   5.15  0.005
        Bisect    +0.10  |   9.83   9.85   9.84  0.007 |   9.85   9.85   9.85  0.000
         DMath    +1.54  |  18.15  18.17  18.16  0.009 |  18.44  18.46  18.44  0.007
           FFT    +0.74  |   5.37   5.38   5.37  0.005 |   5.41   5.42   5.41  0.004
        InProd    +1.23  | 133.73 133.86 133.78  0.048 | 135.04 136.23 135.43  0.353
         InvMt    +7.14  |   0.56   0.57   0.56  0.005 |   0.60   0.61   0.60  0.005
        LLoops    -4.17  |  14.35  14.48  14.40  0.043 |  13.76  13.83  13.80  0.021
        Lorenz    -2.45  |   3.67   3.69   3.68  0.007 |   3.58   3.60   3.59  0.007
       MatInv4    +5.17  |   0.58   0.58   0.58  0.000 |   0.61   0.61   0.61  0.000
         NewtE    +1.12  |  15.15  15.19  15.17  0.012 |  15.33  15.34  15.34  0.005
         NewtR    +3.93  |   5.60   5.60   5.60  0.000 |   5.81   5.84   5.82  0.009
        Regula    +1.26  |   4.75   4.76   4.76  0.005 |   4.81   4.83   4.82  0.006
        Romber    +1.37  |   3.64   3.69   3.65  0.017 |   3.69   3.72   3.70  0.010
        Secant    +2.67  |   2.24   2.26   2.25  0.005 |   2.31   2.31   2.31  0.000
        Simpsn   -36.99  |   7.11   7.12   7.11  0.005 |   4.48   4.49   4.48  0.004
         SqMtx    +5.30  |   7.73   7.74   7.73  0.005 |   8.14   8.15   8.14  0.005
          Trap   -10.95  |   4.92   4.95   4.93  0.008 |   4.38   4.40   4.39  0.005
       Whetsto    -0.70  |  11.46  11.48  11.47  0.009 |  11.38  11.39  11.39  0.004
       8Queens    +9.65  |   3.11   3.12   3.11  0.004 |   3.40   3.43   3.41  0.009
     Ackermann    +0.31  |   6.43   6.44   6.44  0.005 |   6.46   6.46   6.46  0.000
     AddArray2    +2.40  |  10.40  10.48  10.43  0.028 |  10.66  10.73  10.68  0.023
      AddArray    +2.03  |   5.88   5.91   5.90  0.010 |   6.01   6.04   6.02  0.011
        Array1    +3.58  |   4.74   4.76   4.75  0.007 |   4.91   4.93   4.92  0.006
        Array2    +8.33  |   7.80   7.80   7.80  0.000 |   8.45   8.46   8.45  0.005
        BenchE    +3.55  |   6.47   6.48   6.47  0.004 |   6.69   6.72   6.70  0.008
   BubbleSort2    +3.14  |   5.10   5.11   5.10  0.005 |   5.26   5.26   5.26  0.000
    BubbleSort    -5.48  |   5.82   5.90   5.84  0.026 |   5.52   5.54   5.52  0.007
        CSieve   +11.85  |   8.51   8.53   8.52  0.005 |   9.52   9.53   9.53  0.005
           Fib    +0.72  |   8.36   8.37   8.36  0.005 |   8.42   8.43   8.42  0.005
      HeapSort    +8.68  |   3.79   3.82   3.80  0.010 |   4.13   4.14   4.13  0.005
      IniArray    +3.03  |   1.32   1.32   1.32  0.000 |   1.36   1.36   1.36  0.000
    LogicArray    +1.56  |   5.11   5.13   5.12  0.007 |   5.19   5.20   5.20  0.005
      Midpoint    +5.36  |  11.13  11.25  11.19  0.041 |  11.77  11.82  11.79  0.018
     MulMatrix    +7.05  |   8.06   8.09   8.08  0.013 |   8.63   8.67   8.65  0.012
    NDhrystone    +0.19  |  15.64  16.16  15.89  0.181 |  15.60  16.51  15.92  0.308
     Permutate    +4.80  |   7.91   7.93   7.92  0.009 |   8.30   8.31   8.30  0.005
            Pi    +1.16  |  12.76  13.00  12.90  0.085 |  13.00  13.14  13.05  0.045
        Puzzle    -1.86  |   4.85   4.86   4.85  0.005 |   4.76   4.78   4.76  0.007
     QuickSort    +3.61  |   5.26   5.27   5.27  0.005 |   5.45   5.47   5.46  0.009
    TreeInsert    -4.34  |   5.53   5.54   5.53  0.004 |   5.28   5.30   5.29  0.009
      TreeSort    +2.39  |  10.41  10.51  10.47  0.034 |  10.64  10.90  10.72  0.085
    XposMatrix    +4.50  |   8.06   8.30   8.23  0.095 |   8.58   8.68   8.60  0.035
  binarytrees3    +0.43  |  13.88  13.99  13.93  0.043 |  13.93  14.03  13.99  0.029
   binarytrees    -0.56  |  15.84  16.38  15.94  0.182 |  15.71  16.23  15.85  0.166
         fasta    +7.69  |   0.65   0.65   0.65  0.000 |   0.69   0.70   0.70  0.004
    fastaredux    +7.58  |   0.66   0.66   0.66  0.000 |   0.71   0.71   0.71  0.000
  k-nucleotide    +6.86  |   4.79   4.87   4.81  0.024 |   5.10   5.19   5.14  0.033
         nbody    +7.35  |   1.35   1.37   1.36  0.007 |   1.45   1.46   1.46  0.005
     pi-digits   +10.96  |   1.46   1.47   1.46  0.004 |   1.61   1.62   1.62  0.004
      regexdna    +9.24  |  25.94  26.74  26.31  0.268 |  28.44  29.35  28.74  0.317
       revcomp   +13.20  |   8.40   8.44   8.41  0.013 |   9.51   9.54   9.52  0.010
  spectralnorm    +7.41  |   1.35   1.35   1.35  0.000 |   1.45   1.45   1.45  0.000
      Bytemark    +0.48  |  96.14  96.81  96.57  0.246 |  96.37  97.49  97.03  0.351
   FractalPerf   +15.17  |   8.23   8.25   8.24  0.007 |   9.49   9.49   9.49  0.000
InlineGCStruct    -5.41  |  23.64  23.67  23.65  0.009 |  22.36  22.40  22.37  0.014
 NoThrowInline    +6.25  |   0.48   0.48   0.48  0.000 |   0.51   0.52   0.51  0.005
          Linq   +12.37  | 116.96 117.37 117.17  0.136 | 131.37 132.02 131.66  0.233
     Functions    +0.52  |  38.24  38.32  38.27  0.024 |  38.45  38.49  38.47  0.013
      CscBench    +6.53  |  51.46  53.85  52.53  1.121 |  53.86  56.92  55.96  1.157
       SciMark    +1.04  |  28.88  28.93  28.90  0.017 |  29.15  29.24  29.20  0.029
   Deserialize    +4.64  |  78.49  78.88  78.69  0.133 |  81.58  83.14  82.34  0.494
     Serialize    +2.68  | 103.51 105.69 104.37  0.706 | 106.47 107.68 107.17  0.380
 ConsoleMandel    +9.63  |   1.35   1.35   1.35  0.000 |   1.47   1.49   1.48  0.009
     RayTracer   +51.34  |   3.35   3.43   3.37  0.026 |   5.08   5.15   5.10  0.024
    SeekUnroll   +14.66  |   2.64   2.69   2.66  0.015 |   3.03   3.06   3.05  0.009
       Indexer    +7.66  |   2.34   2.36   2.35  0.009 |   2.52   2.55   2.53  0.009
        Crypto    +7.50  |   1.99   2.01   2.00  0.007 |   2.15   2.17   2.15  0.007
      Richards    +8.63  |   1.96   1.98   1.97  0.007 |   2.13   2.15   2.14  0.006
```

**Comment by BruceForstall** [comment] 2018-02-08 00:06
We are shipping RyuJIT/arm32 for 2.1, but haven't done any more CQ/throughput work than is shown here, and that's been a while. We should do at least some investigations.

**Comment by alpencolt** [comment] 2018-02-08 09:39
We've measured launch time on Tizen/armel platform for `crossgen` compiled applications. There is no regression for simple apps. I will share more detailed info soon.
But we haven't measured throughput and  Code Quality.

**Comment by BruceForstall** [comment] 2019-01-09 23:17
There's some useful data here. However, Legacy back-end is long since gone. If we spend time on performance for arm32, we would more likely use a usual approach of finding hot spots, current assembly analysis, comparing to x86/x64 runs, etc. So I'm going to close this issue.

**Closed by BruceForstall** 2019-01-09 23:17 UTC
Labels: arch-arm32, arch-x64, area-CodeGen, enhancement, optimization, tenet-performance
