### ISSUE TITLE
DllImport in bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by AnthonyLloyd** [dotnet/coreclr#6875] opened 2016-08-23 21:43 UTC
Hi,

I'm trying to call a native so file located with the dotnet core dll. I've tried with or without lib in the call and all I ever get is the following. Is a local so file possible and is bash on Windows supported?

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'Native.so': The specified module could not be found.

Any pointer to documentation on this would be great.

Thanks

**Comment by jasonwilliams200OK** [comment] 2016-08-23 23:21
> is bash on Windows supported?

Yes: the released preview 2 version of CLI for Ubuntu works on BoUoW, but has some port binding issues when running web server on top of it, see: https://github.com/dotnet/cli/issues/3999. Not sure about P/Invoke issues.

You can probably use something like `strace corerun MyConsoleAppWithDllImportStuff.exe` to figure out what the underlying issue is. Is the Native.so even present on the disk where it is looking for? Is it some permission issue? Is your code working on Ubuntu proper, but only failing on BoUoW? etc. If the issue is hard to be spotted, you can share the strace logs via https://gist.github.com/ etc. (as usually they are too large for the github comment box).

**Comment by AnthonyLloyd** [comment] 2016-08-31 20:31
Thanks good idea. I get the following. Putting a copy of the so file there doesn't even work:

open("/usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0/libSystem.Native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0/libSystem.Native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libSystem.Native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libSystem.Native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/libSystem.Native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/libSystem.Native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

**Comment by AnthonyLloyd** [comment] 2016-08-31 21:41
Thanks good idea. I've put the so and dependent so file in /usr/lib. It still gives the same error but I can't see anything wrong in the strace. 

https://gist.github.com/AnthonyLloyd/92cc56b1e35ba6e2f53a92ff97427503

**Comment by jasonwilliams200OK** [comment] 2016-08-31 22:06
It seems like that might be due to some crucial lib is missing on the system.

```sh
# there are many
access(...) = -1 ENOENT (No such file or directory)
open(...) = -1 ENOENT (No such file or directory)
stat(...) = -1 ENOENT (No such file or directory)
lstat(...) = -1 ENOENT (No such file or directory)
# etc. then it crashes
exit_group(134) = ?
```

would need to narrow down which one of these might be causing the fatality.

BTW, do you run into same crash if you try your app on some other machine, VM or some CI server? Maybe fireup a docker or [Vagrant](http://vagrantup.com) to quickly test / rule out whether the problem is only with one particular system or everywhere?

**Comment by yizhang82** [comment] 2017-04-22 23:47
@ AnthonyLloyd it's been a few months so I'm closing this now. Feel free to re-open this if you are still running into issues (or open a new one). Thanks!

**Closed by yizhang82** 2017-04-22 23:47 UTC
Labels: area-Interop, question
