### ISSUE TITLE
PLINQ test hit SEHException on Ubuntu ARM64

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#24956] opened 2019-06-04 19:59 UTC
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38211~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190604.1/workItem/System.Linq.Parallel.Tests/wilogs
```
  Discovering: System.Linq.Parallel.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Linq.Parallel.Tests (found 320 of 1188 test cases)
  Starting:    System.Linq.Parallel.Tests (parallel test collections = on, max threads = 46)
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Linq.Parallel.Lookup`2+<GetEnumerator>d__10[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Collections.Generic.IEnumerator<System.Linq.IGrouping<TKey,TElement>>.get_Current()
   at System.Collections.Generic.LargeArrayBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddRange(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Collections.Generic.EnumerableHelpers.ToArray[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Xunit.Assert.All[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Action`1<System.__Canon>)
   at System.Linq.Parallel.Tests.ToLookupTests.ToLookup(Int32)
   at System.Linq.Parallel.Tests.ToLookupTests.ToLookup_Longrunning()
```

**Comment by RussKeldorph** [comment] 2019-06-05 16:19
@stephentoub Does this repro consistently?

Related to #24028?

@vsadov @janvorli @sergiy-k

**Comment by stephentoub** [comment] 2019-06-05 16:21
@RussKeldorph, no, I only saw it once, in CI.  Given it's on ARM64 and that there's nothing in this code that should be producing SEHExceptions, it seemed like something runtime related.

**Comment by VSadov** [comment] 2019-06-05 16:27
Yes, could be #24028.

**Comment by RussKeldorph** [comment] 2019-06-05 16:28
@stephentoub Thanks.  I wasn't questioning your hunch that it's runtime.  Just wanted to know whether it's intermittent, which makes it more likely to be related to #24028.  It's odd that the win-arm64 run failed at the same time, but as that's a timeout it might be something else and a coincidence.

**Comment by stephentoub** [comment] 2019-06-05 16:29
Yup, thanks, @RussKeldorph, was just elaborating :)  Certainly looks like it could be the same thing.

**Comment by VSadov** [comment] 2019-06-06 18:40
`System.Linq.Parallel.Lookup` does not seem to have much related to concurrency. I cannot see `Interlocked` used either.

It is still possible that the failure is related. I am pretty sure `Parallel` uses `Interlocked`.
However in #24028 the crash comes from interlocked operation itself, so this could be something else. 

Hard to tell for sure with just one hit. We should not consider this a dupe for now.

**Comment by stephentoub** [comment] 2019-06-06 19:23
>  System.Linq.Parallel.Lookup does not seem to have much related to concurrency

The exception here, at least according to the call stack, is coming from `System.Linq.Parallel.Lookup`2+<GetEnumerator>d__10[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Collections.Generic.IEnumerator<System.Linq.IGrouping<TKey,TElement>>.get_Current()`, which not only doesn't have much related to concurrency, it doesn't have much of anything at all... it's just the compiler-generated Current for an iterator, e.g. decompiled:
```C#
IGrouping<TKey, TElement> IEnumerator<IGrouping<TKey, TElement>>.Current =>
    this.<>2__current;
```

**Comment by VSadov** [comment] 2019-06-06 19:30
There is a remote possibility that the root cause for #24028 (which we do not know yet) causes heap corruptions and thus may result in this kind of failure.
It may be something different entirely. 
We only suspect #24028 because it is the same exception on Linux ARM64 and `Parallel` certainly uses `Interlocked`.

**Comment by VSadov** [comment] 2019-06-25 17:53
We have not seen this test fail for long while. It is likely a dupe of https://github.com/dotnet/coreclr/issues/24028

**Closed** 2019-06-26 03:14 UTC
Labels: arch-arm64
