### ISSUE TITLE
Test failed: System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests.ThrowAfterAsyncComplete

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25143] opened 2019-06-13 01:32 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190611.2/workItem/System.ComponentModel.EventBasedAsync.Tests/analysis/xunit/System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests~2FThrowAfterAsyncComplete

**Failed tests:**
System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests.ThrowAfterAsyncComplete

**Log:**
```
 at System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests.TestAsyncOperation.Wait() in /_/src/System.ComponentModel.EventBasedAsync/tests/AsyncOperationTests.cs:line 154
   at System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests.<>c.<ThrowAfterAsyncComplete>b__2_0() in /_/src/System.ComponentModel.EventBasedAsync/tests/AsyncOperationTests.cs:line 39
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2453
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2432
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 289
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 314
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2393
--- End of stack trace from previous location where exception was thrown ---
   at System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests.ThrowAfterAsyncComplete() in /_/src/System.ComponentModel.EventBasedAsync/tests/AsyncOperationTests.cs:line 34
```

**Comment by BruceForstall** [comment] 2019-06-13 15:39
Looks like `COMPlus_TailcallStress=1`

**Comment by CarolEidt** [comment] 2019-06-26 00:11
I'm closing this, as it failed only once, has run numerous times since without failing, and I can't reproduce it.

**Closed by CarolEidt** 2019-06-26 00:11 UTC
Labels: arch-x64, area-CodeGen, os-linux, test-corefx
