### ISSUE TITLE
[Watson] Reliability crash in coreclr.dll!ClassLoader::AddAvailableClassHaveLock

### ISSUE THREAD

**Issue by leculver** [dotnet/coreclr#15330] opened 2017-12-01 19:47 UTC
There is a crash accounting for 69.5% of our external failures in this callstack:
```
coreclr!NgenHashTable_EEClassHashTable,EEClassHashEntry,4_::FindPersistedEntryByHash
coreclr!EEClassHashTable::FindItem
coreclr!ClassLoader::AddAvailableClassHaveLock
coreclr!ClassLoader::AddAvailableClassDontHaveLock
coreclr!Assembly::AddType
coreclr!Module::NotifyProfilerLoadFinished
coreclr!DomainFile::PostLoadLibrary
coreclr!DomainFile::DoIncrementalLoad
coreclr!AppDomain::TryIncrementalLoad
coreclr!AppDomain::LoadDomainFile
coreclr!AppDomain::LoadDomainAssemblyInternal
coreclr!AppDomain::LoadDomainAssembly
coreclr!Module::LoadAssembly
```

Despite the blamed symbol in the title, I suspect we have an issue where NGEN hashtable is corrupted.  We've seen concurrency issues here before (and recently).  It's also possible that the image was corrupted on disk, so it will be difficult to figure out which case is the root cause.

Here is a link to the watson bucket (with heap dumps):  https://watson/Failure?FailureSearchText=53b8f2f3-edc4-ff73-1e50-1c25893a644b

Desktop CLR seems to have the same issue, tracked by this bucket:  https://watson/Failure?FailureSearchText=d42d1953-5930-bb15-0c3c-3784ac216487

**Comment by sergiy-k** [comment] 2018-03-28 18:59
Hi @leculver, the CoreCLR link does not seem to work any longer. Could you please double check whether this issue still shows up in Watson reports for CoreCLR and update the link? Thank you!

**Comment by jkotas** [comment] 2019-11-03 00:51
Likely duplicate of #26870

**Closed by jkotas** 2019-11-03 00:51 UTC
Labels: area-CrossGen/NGEN, reliability
