### ISSUE TITLE
Native runtime crashes on linux/mac in native delegate

### ISSUE THREAD

**Issue by mattleibow** [dotnet/coreclr#25629] opened 2019-07-10 16:56 UTC
Exceptions in managed code running from a native delegate causes the app to crash - even if the original method is in a try/catch block. It runs fine on Windows with both .NET Core and .NET Framework and macOS/Linux with mono.

```csharp
// the managed call
static void Main() {
    add(a, b, AddImplementation);
}

// interop code
public delegate int adder_proc(int a, int b);

[DllImport("libnativelibrary")]
public static extern int add(int a, int b, adder_proc adder);

// the managed callback
public static int AddImplementation(int a, int b) {
    throw new Exception("You asked for an exception, here it is.");
}
```

I have created a sample app here: https://github.com/mattleibow/NetCoreExceptionsTest
The code file is here: https://github.com/mattleibow/NetCoreExceptionsTest/blob/master/source/Program.cs
DevOps CI here: https://dev.azure.com/mattleibow/OpenSource/_build/results?buildId=149

Expected output:
```
2 + 4 = 6
2 + 4 = You asked for an exception, here it is.
2 + 4 = 6
```

Actual output:

```
2 + 4 = 6

Unhandled Exception: System.Exception: You asked for an exception, here it is.
   at managedapp.Program.AddImplementation(Int32 a, Int32 b) in /home/vsts/work/1/s/source/Program.cs:line 48
   at managedapp.Program.add(Int32 a, Int32 b, adder_proc adder)
   at managedapp.Program.Main(String[] args) in /home/vsts/work/1/s/source/Program.cs:line 24
```

**Comment by jkoritzinsky** [comment] 2019-07-10 17:24
I believe that this is currently expected behavior. Throwing exceptions across the native-managed boundary in .NET Core is unsupported on non-Windows platforms.

cc: @janvorli

**Comment by janvorli** [comment] 2019-07-10 17:52
> Throwing exceptions across the native-managed boundary in .NET Core is unsupported on non-Windows platforms.

Correct. There is no way to know how to correctly propagate the exception through the non-managed layer. The code that called the managed callback can be anything - C, C++, Python, etc.

**Comment by mattleibow** [comment] 2019-07-11 07:07
Ah, that is not so nice. Is there some special cases for Windows? Also, mono works, so is there a way to use their logic, or is that too different?
I updated the repo with a mono repro which works: https://dev.azure.com/mattleibow/OpenSource/_build/results?buildId=150

**Comment by rolfbjarne** [comment] 2019-07-11 08:15
> mono works

No it doesn't, it's depending on undefined behavior, so it just looks like it works.

mono does not know how to unwind native frames, which means that they're just skipped over during exception handling. This means that if the native code in the middle does anything remotely more complex than nothing at all, you're pretty much guaranteed to have at the very least memory leaks. If there are any locks/mutexes, you'll deadlock (if you're lucky).

If you're not so lucky, you'll spend days debugging apparently impossible behavior, when a simple crash would have made the problem clear within seconds.

IMO this "feature" is a bug in mono, and should be removed there, not implemented elsewhere.

**Comment by janvorli** [comment] 2019-07-11 08:57
These are exactly the reasons why we have decided to report the exception as unhandled.
On Windows the exception propagation works over the boundary in case the non-mananged code is compiled with a compiler that uses Windows SEH (structured exception handling) as a basis for its exception handling, like Visual C or C++. In other cases, the same bad things as @rolfbjarne has described can happen. In fact, even with C, if you have locks taken in the codepath that calls the managed callback, you can still get deadlocks. To be precise, the same would happen with C++ if the code would just take a lock without a mechanism that would unlock it during exception unwinding.

**Comment by jaykrell** [comment] 2019-07-11 09:04
The C code should use `__try` / `__finally` to interoperate with exceptions.

**Comment by jaykrell** [comment] 2019-07-11 09:17
And the C++ code destructors.
And Posix C should use pthread_cleanup_push / pthread_cleanup_pop. Probably nobody does.
CLR should stand some chance of interoperating with C++ destructors, on all platforms.

**Comment by janvorli** [comment] 2019-07-12 21:21
I am closing this issue as the behavior is by design

**Closed by janvorli** 2019-07-12 21:21 UTC
Labels: area-ExceptionHandling
