### ISSUE TITLE
Improve build reliability

### ISSUE THREAD

**Issue by chcosta** [dotnet/coreclr#1810] opened 2015-10-20 18:24 UTC
Our internal (VSO) CoreCLR builds fail intermittently (1 - 2 times a week) due to network issues.  We should look to add some retry logic to improve reliability and prevent the weekly build breaks we are seeing in our official builds.

Here is one example failure...
2015-10-20T17:41:22.355Z: Successfully installed 'Microsoft.Build.Mono.Debug 14.1.0.0-prerelease'.
2015-10-20T17:41:24.449Z:   Restoring build tools...
2015-10-20T17:41:44.799Z:   Read in 3027 resources from '/root/coreclr/src/mscorlib/src/mscorlib.txt'
2015-10-20T17:41:44.818Z:   Writing resource file...  Done.
2015-10-20T17:42:01.995Z:   mscorlib -> /root/coreclr/bin/obj/Linux.x64.Release/mscorlib.dll
2015-10-20T17:43:57.127Z: EXEC : error : ConnectFailure (interrupted)[39m[22m [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T17:43:57.134Z: EXEC : error : ConnectFailure (interrupted)[39m[22m [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T17:43:57.134Z: EXEC : error : ConnectFailure (interrupted)[39m[22m [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T17:43:57.134Z: EXEC : error : ConnectFailure (interrupted)[39m[22m [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T17:43:57.135Z: EXEC : error : ConnectFailure (interrupted)[39m[22m [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T17:43:57.135Z: EXEC : error : ConnectFailure (interrupted)[39m[22m [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T17:43:57.137Z: EXEC : error : SendFailure (Error writing headers)[39m[22m [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T17:47:01.180Z: /root/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/toolruntime.targets(32,5): error MSB3073: The command ""/root/coreclr/packages/dnx-mono.1.0.0-beta5-12101/bin/dnu" restore --packages "/root/coreclr/packages/" "/root/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/tool-runtime/project.json"" exited with code -1. [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T17:47:01.338Z: Failed to build mscorlib.

Here is another...
2015-10-20T03:17:21.545Z: Successfully installed 'Microsoft.Build.Mono.Debug 14.1.0.0-prerelease'.
2015-10-20T03:17:23.219Z:   Restoring build tools...
2015-10-20T03:17:40.001Z:   Read in 3027 resources from '/root/coreclr/src/mscorlib/src/mscorlib.txt'
2015-10-20T03:17:40.027Z:   Writing resource file...  Done.
2015-10-20T03:17:51.595Z:   mscorlib -> /root/coreclr/bin/obj/Linux.x64.Release/mscorlib.dll
2015-10-20T03:23:52.050Z:   [1m[31mError: DownloadPackageAsync: https://www.myget.org/F/dotnet-core/api/v2/package/System.Security.Claims/4.0.1-beta-23328
2015-10-20T03:23:52.050Z:     A task was canceled.[39m[22m
2015-10-20T03:23:52.163Z: /root/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/toolruntime.targets(32,5): error MSB3073: The command ""/root/coreclr/packages/dnx-mono.1.0.0-beta5-12101/bin/dnu" restore --packages "/root/coreclr/packages/" "/root/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/tool-runtime/project.json"" exited with code 1. [/root/coreclr/src/mscorlib/mscorlib.csproj]
2015-10-20T03:23:52.297Z: Failed to build mscorlib.

**Comment by chcosta** [comment] 2015-10-20 18:24
cc @joshfree

**Comment by weshaggard** [comment] 2015-10-21 04:40
cc @dagood something to consider along with your package feed work.

**Comment by joshfree** [comment] 2015-10-21 17:17
@dagood similarly package publishing to myget needs to be validated and break the release build when packages fail to publish.

**Comment by dagood** [comment] 2015-10-21 20:15
@weshaggard Yeah, I think it would make sense to introduce at least some simple retries while modifying restore code. I'll track that.

@joshfree Definitely, I'm working towards that now. (I saw your note in the other thread too, just didn't get a chance to respond until now.) The issue right now is that the build has no knowledge of its packages being published: they're picked up by a run on VSO scheduled to run after the build is "normally" complete. This has been causing a problems with the delayed builds we've been seeing a lot of lately. The reason this isn't a simple move is that we don't have a way to keep the API keys secret in the daily builds like we can in VSO builds, but we're working on that.

**Comment by jasonwilliams200OK** [comment] 2015-10-25 15:12
> error : SendFailure (Error writing headers)

For me, on FreeBSD, this is usually fixed by running ` mozroots --import --machine --sync` and invoking build script as `TZ=UTC MONO_THREADS_PER_CPU=50 ./build.sh`

---

@ellismg, @davidfowl  I am getting a similar error on FreeBSD. When running `./build.sh`, it builds coreclr and chokes on `dnu restore` on building mscorlib. Following are the simplified steps to repro:

```csh
git clone https://github.com/dotnet/coreclr; cd coreclr
# no issue
curl -sSL --create-dirs -o packages/NuGet.exe https://api.nuget.org/downloads/nuget.exe
# no issue
mono packages/NuGet.exe install Microsoft.Build.Mono.Debug -Version 14.1.0.0-prerelease -source https://www.myget.org/F/dotnet-buildtools/ -OutputDirectory packages
# no issue so far
mono packages/Microsoft.Build.Mono.Debug.14.1.0.0-prerelease/lib/MSBuild.exe /nologo build.proj /verbosity:minimal "/fileloggerparameters:Verbosity=normal;LogFile=MSCorLib_Debug.log" /t:Build /p:__BuildOS=FreeBSD /p:__BuildArch=x64 /p:__BuildType=Debug /p:__IntermediatesDir=bin/obj/FreeBSD.x64.Debug /p:UseRoslynCompiler=true /p:BuildNugetPackage=false /p:ToolNugetRuntimeId=ubuntu.14.04-x64
# error!
```

Error:

>
  Restoring build tools...
  Read in 3027 resources from '/root/coreclr/src/mscorlib/src/mscorlib.txt'
  Writing resource file...  Done.
  mscorlib -> /root/coreclr/bin/obj/FreeBSD.x64.Debug/mscorlib.dll
  /tmp/tmp72a67f0e4cd948099e7e8b789212b223.exec.cmd: /root/coreclr/packages/dnx-mono.1.0.0-beta5-12101/bin/dnu: not found
/root/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/toolruntime.targets(32,5): error MSB3073: The command ""/root/coreclr/packages/dnx-mono.1.0.0-beta5-12101/bin/dnu" restore --packages "/root/coreclr/packages/" "/root/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/tool-runtime/project.json"" exited with code 127. [/root/coreclr/src/mscorlib/mscorlib.csproj]

Also see the output of [MSCorLib_Debug.log](https://gist.github.com/jasonwilliams200OK/d65fb1a836a1b13974ed).

Note that yesterday it was building just fine on another FreeBSD instance (which I disposed). I am not sure what to make of it. Is it some network connectivity issue?

/cc @akoeplinger

**Comment by ellismg** [comment] 2015-10-26 04:48
FWIW, the easiest way to make this more reliable is to not build mscorlib.dll in VSO when running cross-plat.  There are switches to build.sh to skip mscorlib builds.  The internal TFS builds should build all the managed code (including mscorlib) for the targets platforms.

The next best thing is to get mono out of the build path, so we don't have to deal with workarounds like `MONO_THREADS_PER_CPU` and runtime breaks are actually actionable by the team.

@jasonwilliams200OK It's possible your failure is happening because `root/coreclr/packages/dnx-mono.1.0.0-beta5-12101/bin/dnu` doesn't exist.  Maybe the package we were trying to restore is no longer present.

Can you confirm?

**Comment by jasonwilliams200OK** [comment] 2015-10-26 05:36
@ellismg, I can confirm that `/root/coreclr/packages/dnx-mono.1.0.0-beta5-12101/bin/dnu` exists and it gets restored everytime. That directory has 20 items in total (including dnu and dnx)
The error I am getting "not found", which is not very self-explanatory. If we try to execute `dnu` without mono prefix (the last command in my [steps to repro](https://github.com/dotnet/coreclr/issues/1810#issuecomment-150933998) above), it says `Command not found`, which makes sense as dnu is not executable on its own. If the path doesn't exists, then the error is `No such file or directory`.

**Comment by ellismg** [comment] 2015-10-26 05:58
@jasonwilliams200OK dnu is a shell script.  I think the problem is that the old version does not do the /usr/bin/env bash thing and instead the shell script just has `#!/bin/bash`.

Can you edit your local copy to have the correct shebang for your platform and see if that helps?  If so, we should just move to a newer dnx stack that has the fix you guys made.

**Comment by ellismg** [comment] 2015-10-26 09:58
Even if dnu starts to work, you'll probably fail a little later.  We are going to restore a CoreCLR based runtime to run BclRewriter on and that's going to be a Ubuntu version.  You'll need to build all the native code (for CoreFX and CoreCLR) copy it into a directory and then set BUILDTOOLS_OVERRIDE_RUNTIME to point at that directory.  Look at how toolruntime.targets in buildtools works.

Let me know if that addresses your issues.  If it's still busted I can spin up a FreeBSD VM again and poke around.

**Comment by jasonwilliams200OK** [comment] 2015-10-27 18:24
@ellismg, you are right we are still getting dnu beta5, should it be upgraded to latest beta8? 
Changing the shebang fixed that issue. As you suspected, I am getting other errors like:

(snip from `/root/coreclr/MSCorLib_Debug.log`)
```csh
...
...
 Error: FindPackagesById: System.Runtime (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.Collections (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.Collections (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.Diagnostics.Debug (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.Diagnostics.Debug (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.IO (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.IO (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.Runtime.Extensions (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.Runtime.Extensions (TaskId:37)
   A task was canceled. (TaskId:37)
 Error: FindPackagesById: System.Runtime.InteropServices (TaskId:37)
   A task was canceled. (TaskId:37)...
...
```

Also, I tried many times and everytime I execute command, it fails on fetching different packages. 

When you said:

> You'll need to build all the native code (for CoreFX and CoreCLR) copy it into a directory and then set BUILDTOOLS_OVERRIDE_RUNTIME to point at that directory. 

Does it mean I need to add the folder containing CoreCLR and CoreFX source directories like `setenv BUILDTOOLS_OVERRIDE_RUNTIME /root` (as I have them at `/root/coreclr` and `/root/corefx`) or should i collect all the binaries to a separate folder from both repos and set that to `BUILDTOOLS_OVERRIDE_RUNTIME`?

**Comment by chcosta** [comment] 2015-10-27 18:48
per @ellismg suggestion, adding "skipmscorlib" has allowed our builds to bypass the mono dependency and circumvent this flakey piece of the build.  This is probably not an ideal solution for everyone, but is adequate for my needs.

**Comment by jasonwilliams200OK** [comment] 2015-10-27 19:11
@chcosta, I agree. The point being, CI build for CoreCLR also skips the mscorlib. The full workaround is to build the mscorlib for linux/osx or freebsd on windows machine and rest of native binaries on target. But at some point we should also assure that mscorlib is build-able on target and hook it with CI so the feature don't broken / forgotten in any environment. :)

**Comment by ellismg** [comment] 2015-10-27 20:00
> But at some point we should also assure that mscorlib is build-able on target and hook it with CI so the feature don't broken / forgotten in any environment. :)

My general feeling is that we will not be putting anything into CI that requires us to run managed code on top of Mono.  When we can run all of our tools on top of CoreCLR we can look into have CI build managed code on the target platforms.  Until then, my general observation (something that the Roslyn folks have also seen) is that Mono introduces enough flakiness that we don't want to have it on our main build path.

@jasonwilliams200OK I have not seen this sort of stuff before.  If the `MONO_THREADS_PER_CPU` workaround doesn't work, I'm not sure I have much insight.  Maybe moving to a beta8 build would help.  FWIW, I don't hit these locally and I have MONO_THREADS_PER_CPU set to 2000.

**Comment by jasonwilliams200OK** [comment] 2015-10-27 20:18
@ellismg, sorry I was testing it without setting `MONO_THREADS_PER_CPU` set in Parallels (as I was running bare mono commands for building mscorlib and not `./build.sh` which sets it to 2000). 

Now that I have set it, it succeeds pulling the packages but fails with `BclRewriter`:

```
  /tmp/tmp1e925f2608b04feb879df45d27cd69e2.exec.cmd: bin/obj/FreeBSD.x64.Debug/ToolRuntime/corerun: Exec format error (T
askId:42)
/root/coreclr/src/mscorlib/Tools/BclRewriter/BclRewriter.targets(27,5): error MSB3073: The command ""bin/obj/FreeBSD.x64
.Debug/ToolRuntime/corerun" "/root/coreclr/packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00105/lib/BclRewriter.
exe" -in:"/root/coreclr/bin/obj/FreeBSD.x64.Debug/mscorlib.dll" -out:"/root/coreclr/bin/obj/FreeBSD.x64.Debug/BclRewrite
r/mscorlib.dll" -include:"/root/coreclr/src/mscorlib/model.xml" -platform:unix -architecture:amd64 -flavor:chk -define:"
CODE_ANALYSIS;DBG;_DEBUG;_LOGGING;DEBUG;TRACE;WIN64;AMD64;;NEW_EXPERIMENTAL_ASYNC_IO;_USE_NLS_PLUS_TABLE;RESOURCE_SATELL
ITE_CONFIG;INSIDE_CLR;CODE_ANALYSIS_BASELINE;FEATURE_APPDOMAIN_RESOURCE_MONITORING;FEATURE_ARRAYSTUB_AS_IL;FEATURE_STUBS
_AS_IL;FEATURE_ASCII;FEATURE_BCL_FORMATTING;FEATURE_COLLECTIBLE_TYPES;FEATURE_CORECLR;FEATURE_COREFX_GLOBALIZATION;FEATU
RE_CORESYSTEM;FEATURE_CORRUPTING_EXCEPTIONS;FEATURE_ENCODINGNLS;FEATURE_EXCEPTIONDISPATCHINFO;FEATURE_FRAMEWORK_INTERNAL
;FEATURE_HOST_ASSEMBLY_RESOLVER;FEATURE_HOSTED_BINDER;FEATURE_LATIN1;FEATURE_LEGACYNETCF;FEATURE_LEGACYNETCFFAS;FEATURE_
LOADER_OPTIMIZATION;FEATURE_MANAGED_ETW_CHANNELS;FEATURE_MAIN_CLR_MODULE_USES_CORE_NAME;FEATURE_NORM_IDNA_ONLY;FEATURE_P
AL;FEATURE_RANDOMIZED_STRING_HASHING;FEATURE_STRONGNAME_MIGRATION;FEATURE_SYNTHETIC_CULTURES;FEATURE_UTF32;FEATURE_UTF7;
FEATURE_VERSIONING;FEATURE_WINDOWSPHONE;FEATURE_WINMD_RESILIENT;FEATURE_MULTICOREJIT;FEATURE_USE_ASM_GC_WRITE_BARRIERS;F
EATURE_SYMDIFF;FEATURE_READYTORUN;PLATFORM_UNIX" -keepTempFiles+" exited with code 126. [/root/coreclr/src/mscorlib/msco
rlib.csproj]
```

Can you please assist what exact steps to take to override using `BUILDTOOLS_OVERRIDE_RUNTIME`?

**Comment by ellismg** [comment] 2015-10-27 20:50
@jasonwilliams200OK You should collect all the native binaries produced by the CoreCLR and CoreFX build processes and put them in `BUILDTOOLS_OVERRIDE_RUNTIME` this includes corerun + all the .so files generated by both sets of native builds.

**Comment by ellismg** [comment] 2015-10-29 07:27
@chcosta has addressed the internal causes of this (e.g. trying to build mscorlib.dll on Mono) so I'm going to close this up.  @jasonwilliams200OK If you have problems with the tool runtime stuff on freebsd, please feel free to open up another issue so we can continue to discuss.

**Closed by ellismg** 2015-10-29 07:27 UTC
Labels: infrastructure

**Comment by jasonwilliams200OK** [comment] 2015-10-30 11:20
@ellismg, sure. I have tried BUTILDTOOLS_OVERRIDE_RUNTIME, but it is failing. It was a busy week, I will try to gather steps to repro and if something unusual crop up will open another issue.
Thanks for your suggestions and improving the overall build experience!  :+1:
