### ISSUE TITLE
Locks slow on Linux with lots of threads

### ISSUE THREAD

**Issue by jskeet** [dotnet/coreclr#11979] opened 2017-05-30 16:27 UTC
A failing unit test as part of a separate project led me to investigate some odd performance characteristics. At first glance - and I'm not an expert on this - it looks like locks are really expensive on Linux when there are lots of threads trying to acquire the same lock.

I've put together a small test app to demonstrate this. No extra dependencies required - just `dotnet new console` (with netcoreapp1.1) and then edit `Program.cs`:

```csharp
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading;

class Program
{
    static long counter = 0;
    
    static void Main(string[] args)
    {
        int threadCount = int.Parse(args[0]);
        long totalWork = long.Parse(args[1]);
        int incrementsPerIteration = int.Parse(args[2]);
        
        int iterationsPerThread = (int) (totalWork / (incrementsPerIteration * threadCount));
        
        object monitor = new object();
        Run(monitor, 1, 1);
        counter = 0;
        
        var threads = Enumerable
            .Range(0, threadCount)
            .Select(_ => new Thread(() => Run(monitor, iterationsPerThread, incrementsPerIteration)))
            .ToList();
        
        var stopwatch = Stopwatch.StartNew();
        threads.ForEach(t => t.Start());
        threads.ForEach(t => t.Join());
        stopwatch.Stop();
        
        Console.WriteLine($"Threads: {threadCount}");
        Console.WriteLine($"Elapsed time: {stopwatch.Elapsed.TotalSeconds:0.00}");
    }
    
    static void Run(object monitor, int iterations, int increments)
    {
        for (int i = 0; i < iterations; i++)
        {
            lock (monitor)
            {
                for (int j = 0; j < increments; j++)
                {
                    counter++;
                }
            }
        }
    }
}
```

**Windows machine dotnet --info:**

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Linux machine dotnet --info:**

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

The Windows machine and Linux machine below have identical CPUs (Core i5 IIRC; I can go into more details if necessary). But as the number of threads goes up, the Windows timing stays roughly constant, but the Linux timing gets much, much worse.

**Windows results**

```text
dotnet run 10 1000000000 100
Threads: 10
Elapsed time: 10.89

dotnet run 20 1000000000 100
Threads: 20
Elapsed time: 10.86

dotnet run 30 1000000000 100
Threads: 30
Elapsed time: 10.90

dotnet run 40 1000000000 100
Threads: 40
Elapsed time: 10.86

dotnet run 50 1000000000 100
Threads: 50
Elapsed time: 10.85
```

**Linux results (same inputs)**

```text
dotnet run 10 1000000000 100
Threads: 10
Elapsed time: 17.05

dotnet run 20 1000000000 100
Threads: 20
Elapsed time: 40.21

dotnet run 30 1000000000 100
Threads: 30
Elapsed time: 113.84

dotnet run 40 1000000000 100
... didn't complete after a long time. Killed to avoid generating pointless heat
```

I realize this is a very unscientific test - proper diagnostics would be rather more nuanced. But it seems like enough of an alarm bell to be worth raising for smarter people to look closely.

I have no idea whether this is an inherent Linux issue, or a CoreCLR implementation issue.
I haven't yet tried with the .NET Core 2.0 preview, and would *rather* not, but could do so if necessary.

**Comment by stephentoub** [comment] 2017-05-30 16:33
cc: @kouvel

**Comment by danmosemsft** [comment] 2017-06-07 04:29
@jskeet if you're offering to try 2.0, that would be great.

**Comment by danmosemsft** [comment] 2017-06-07 04:29
...because if it is a 2.0 issue is may be more urgent.

**Comment by jskeet** [comment] 2017-06-07 05:18
Righto - I'll see if I can give that a whirl today.

**Comment by jskeet** [comment] 2017-06-07 07:49
Just noticed I wasn't running the Release build in the original repo - when I do, the times are faster (on Linux anyway) but the same general pattern emerges. Now installing 2.0 preview 1...

**Comment by jskeet** [comment] 2017-06-07 07:55
Okay, confirmed it still seems to be a problem under 2.0 preview 1. Running with -c Release:

10 threads: 3.42s  
20 threads: 6.10s
30 threads: 17.89s

**Comment by kouvel** [comment] 2017-06-27 20:38
I believe it's running into a lock convoy problem. Spinners are not able to take the lock while there are waiting threads, and a waiting thread is not able to wake up before a significant delay due to spinners hoarding the CPU.

This works on Windows because when a waiting thread is signaled to wake up, I believe it also gives that thread a priority boost. As such, it's able to wake up asap and acquire the lock.

**Comment by kouvel** [comment] 2017-06-27 20:45
Potential fixes:
- Allow spinners to preempt waiters and acquire the lock. This creates a potential problem of starving waiters.
- Limit the number of spinning threads to leave room for a waiter to wake up
- Or perhaps a combination of the two

**Comment by stephentoub** [comment] 2017-06-27 20:47
> Potential fixes

What kind of backoff scheme is currently being employed in the spinning?  Is there also opportunity to improve there, or do we believe that's currently optimal?

**Comment by kouvel** [comment] 2017-06-27 20:53
Another potential fix: There is only pause (YieldProcessor) but no Sleep(0)/SwitchToThread in the spin loop. That may also fix the issue.

**Comment by stephentoub** [comment] 2017-06-27 20:54
> There is only pause (YieldProcessor) but no Sleep(0)/SwitchToThread in the spin loop

That's what I was asking about in a backoff scheme :wink:

**Comment by kouvel** [comment] 2017-06-27 20:56
Ah ok. The spin loop is here:
https://github.com/dotnet/coreclr/blob/master/src/vm/syncblk.inl#L122

Where initial is 50 and the backoff factor is 3. The max is calculated here based on the number of processors:
https://github.com/dotnet/coreclr/blob/master/src/vm/syncblk.h#L165

I think the spinning is excessive as well.

**Comment by kouvel** [comment] 2017-06-27 21:19
Actually it does a second spin loop in AwareLock::Contention and does a SwitchToThread there but I don't think it would be done frequently enough due to the excessive spinning in EnterObjMonitorHelperSpin

**Comment by kouvel** [comment] 2017-06-28 04:11
I have dug a little deeper and I believe I have found the root cause. Some facts:
- In the example given, with a design where there is no spinning and when there is a waiter, a waiter must acquire the lock, there is a deterministic lock convoy. Every release of the lock requires that a waiter acquire it, and the context switching kills the perf.
- This situation is occurring on Windows and Linux
- However, Windows' priority boost for released threads allows a waiter to get a lock sooner, and release another waiter sooner, etc., eventually removing all waiters. So on Windows, the lock convoy is fixing itself due to scheduling heuristics in Windows. Given enough waiters, theoretically, this would be an issue on Windows as well.
- On Linux, once the lock convoy begins, there is no end to it

As such, I believe the only solution to this is the first one I suggested above:
- Allow spinners to preempt waiters and acquire the lock. This creates a potential problem of starving waiters

Some data:
- Reducing spinning actually makes the issue worse, because it increases the frequency with which threads become waiters, which initiates the lock convoy
- Adding SwitchToThread/Sleep(0) helps only to the extent that it delays the thread becoming a waiter (but it should be done anyway)

@jkotas, @stephentoub, @vancem, what are your thoughts on this? Is there anything else I should test to see if I'm missing something?

**Comment by kouvel** [comment] 2017-06-28 04:11
Forgot to mention, scheduling behavior/heuristics can affect the frequency of occurrence

**Comment by kouvel** [comment] 2017-06-28 04:14
Also I should add, regarding the solution comment:
> This creates a potential problem of starving waiters

In typical non-buggy scenarios, the starvation should resolve itself. If threads get permamently starved leading to a deadlock (even without the OS's help to resolve the starvation), I believe the main issue there would be in the program's code.

**Comment by vancem** [comment] 2017-06-29 00:59
> @jkotas, @stephentoub, @vancem, what are your thoughts on this? Is there anything else I should test to see if I'm missing something?

I have a few comments/observations

1.  I realize that historically we have had significant problem with respect to lock performance (in particular spinning WAY too long)< and I would like to take this issue as an opportunity for me to do some inventory and figure out exactly what we do now, and whether we believe it is a good idea or now (historically we were much too risk-averse to entertain changing anything).   Let me review the code and maybe do some experiments (maybe make some perf tests) and get back to you.   The rest of this is my general observations.
2. I DON'T view the scenario as a primary scenario to tune for.   This test shows what happens when MANY threads all beat on a single lock (and do nothing outside the lock).   Frankly, when any lock has a persistent queue of waiters on it, you are ALREADY have a perf problem (you have a hot lock and you have a scalability problem to fix).     Thus we are only making a very bad problem just a bad problem, which is a secondary scenario.   
3. HOWEVER the SPINNING is a real problem because it is STARVING real work from happening, and creates a 'Meltdown' issue (the more contention there is, the more inefficient you are which makes the problem worse).   This can lead to VERY bad behavior (we have seen this in real scenarios and it is not pretty).    Notice that if there was NO spinning, there would have been no problem above because N-1 threads would be waiting and one thread would always be making progress (which is the best you can do).  
4. Generally speaking, an ideal algorithm for locks is to be completely unfair in small time scales (a thread that has the processor should have preference to getting the lock, since its cache lines are 'hot'), but fair at long time intervals (e.g. 1 - 10 msec), to avoid starvation (e.g. if a waiter has been waiting more than 1msec, then it should get priority).   
5. Spinning should be kept well in check.    It should be on the order of the cost of context switching out and back (which is the cost of the context switch (call it 3K instrs ~= 1usec), and some estimate of cost of 'warming up the cache again',  guessing about < 30 k instructions ~= 10usec).   
6.  Note that you should to NO spinning if the likely wait time is > context switch cost.  Interestingly you CAN come up with a  very good estimate of whether this is true or not by looking at what you did before (if you had to wait previously odd are you will this time, and so you should dispense with spinning).  
7. If you do NO spinning, it is not that bad (you pay the context switch cost, but that is bounded and not huge).  

Arguably, WE should not be doing the spinning, WE call a OS lock and that lock should be the thing that figures out this out for everyone.   We should not have to do things 'on top' of the OS lock.  

Anyway, the idea of being unfair at small time scales (which is what Windows priority boost does), and/or not spinning much (which avoids the meltdown), should solve things.   Let me look at the code before I make a more specific recommendation. however.

**Comment by kouvel** [comment] 2017-06-29 05:23
Thanks for taking a look @vancem.

It looks like the monitor is being fair at even the small time scales sometimes and this example demonstrates that well. The duration for which the monitor is held is very short, so ideally, the releaser should be able to release and reacquire the lock multiple times until its time slice runs out. But when there is a waiter every time the lock is released, the releaser in this implementation is forced to yield the lock to a different thread every time. Effectively, much more time is spent context switching than running the program code since the cost of a context switch is significantly greater than the amount of work done inside the lock.

I agree this may not be a case to tune for, but it shouldn't be broken either, and this could appear broken to users, as the time taken does not scale well or reliably, and the occurrence is sudden and could be unpredictable.

> Arguably, WE should not be doing the spinning, WE call a OS lock and that lock should be the thing that figures out this out for everyone. We should not have to do things 'on top' of the OS lock.

Would the p/invoke cost be prohibitive? I was guessing the reason for operating on top of the OS was to avoid the p/invoke for better performance.

**Comment by jskeet** [comment] 2017-06-29 05:47
Just to address the "this isn't the primary scenario to tune for" aspect - I completely agree. We actually discovered this in a stress test to check that the code which *was* inside the lock behaved correctly in extreme scenarios. It was only annoying because our Linux CI failed. I'm completely fine with a solution which isn't optimal for this case :)

**Comment by vancem** [comment] 2017-06-29 21:18
@kouvel.   I have reviewed the code a bit, and I need to review if things are different in CoreRT.    There are some obvious simplifications (for example, we spin in assembly code, then spin again in the AwareLock code),  I also do enough experimentation to confirm that the following changes would be good.  In particular:

1. The lock should start out with no spinning, monitor how long the wait time was (forming an average) and only do spinning if the expected wait time is 'short enough'.
2. The threshold for 'short enough' (that is the spin time), should not depend on the number of processors (or only grow slowly with the number of processors (e.g. logarithmic).
3. Allow 'stealing' the lock (unfairness) without blocking as long as the wait time in the queue is under a threshold (basically a machine quantum ~ 10msec).   
4. If stealing is not allowed (because of fairness) go directly to blocking (today we spin, which is POINTLESS).  

Let me look at this over the next few days.  

However it occurs to me that if we JUST did (4) above it would mitigate this immediate issue (in this scenario there are always waiters, and if we do no spinning.  Now we would still have the convoy (because it is fair), but the time should NOT grow with the number of threads (because having more threads does not change what happens on each 'lock' cycle, just the length of the queue (thus thread latency suffers, but not throughput))

Or you would just wait for what I would consider something closer to the 'final' answer and beat on that.  In particular I would like to get rid of l the spinning happening in assembly code (so we only do the spinning one place (in the C++ code).

**Comment by jkotas** [comment] 2017-06-29 21:22
>  get rid of l the spinning happening in assembly code

Note that this is only a problem on Windows. The assembly code does not exist on Linux - we have just the C++ there.

**Comment by kouvel** [comment] 2017-09-14 17:37
Closing in favor of https://github.com/dotnet/coreclr/issues/13978

**Closed by kouvel** 2017-09-14 17:37 UTC
Labels: area-System.Threading, tenet-performance
