### ISSUE TITLE
TypeLoadException .net core 2.0 

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/coreclr#16211] opened 2018-02-05 17:42 UTC
_From @nim on February 3, 2018 12:32_

I have Exception than i try use this struct

```
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    struct LinkStruct
    {
        public LinkStruct? Chield { get; set; } 
    }
```

_Copied from original issue: aspnet/Mvc#7327_

**Comment by jkotas** [comment] 2018-02-05 18:03
Duplicate of https://github.com/dotnet/coreclr/issues/16188

**Closed by jkotas** 2018-02-05 18:03 UTC
