### ISSUE TITLE
dotnet publish for standalone console app generating wrong filename on OSX

### ISSUE THREAD

**Issue by bruce31** [dotnet/coreclr#13199] opened 2017-08-03 16:46 UTC
```
dotnet publish -c Release -r osx.10.12-x64 -o publish
```
for a console app CIBuild.RunTests.csproj generated an 'exec' file named CIBuild.RunTests.RunTests which did not work with the CIBuild.RunTests.dll created at the same time.
```
dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by bruce31** [comment] 2017-08-03 17:10
Quick repo steps
```
mkdir App.Subapp
cd App.Subapp/
dotnet new console
dotnet publish -c Release -r osx.10.12-x64 -o publish
ls -l publish/App.Subapp*
-rwxrw-rw-  1 user1  staff  123596  3 Aug 17:49 publish/App.Subapp.Subapp
-rw-r--r--  1 user1  staff   21101  3 Aug 17:49 publish/App.Subapp.deps.json
-rw-r--r--  1 user1  staff    4096  3 Aug 17:49 publish/App.Subapp.dll
-rw-r--r--  1 user1  staff     444  3 Aug 17:49 publish/App.Subapp.pdb
-rw-r--r--  1 user1  staff      26  3 Aug 17:49 publish/App.Subapp.runtimeconfig.json

publish/App.Subapp.Subapp 
The managed DLL bound to this executable: 'App.Subapp.dll', did not match own name 'App.Subapp.Subapp.dll'.
A fatal error was encountered. This executable was not bound to load a managed DLL.
```

**Comment by jkotas** [comment] 2017-08-08 03:43
Thanks for reporting the bug. This is duplicate of https://github.com/dotnet/sdk/issues/1396 that is fixed in latest builds.

**Closed by jkotas** 2017-08-08 03:43 UTC
