### ISSUE TITLE
BinaryCompatibility type returning the wrong values

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#7892] opened 2016-10-30 11:45 UTC
When corefx upgraded to a newer coreclr in https://github.com/dotnet/corefx/pull/12836, some async-related tests started breaking.  It appears to be due to System.Runtime.Versioning.BinaryCompatibility.TargetsAtLeast_Desktop_V4_5 now returning false, which has the effect of reverting several fixes made in coreclr years ago.

**Comment by jkotas** [comment] 2016-10-30 15:29
Looks like regression introduced by https://github.com/dotnet/coreclr/pull/5708

**Comment by stephentoub** [comment] 2016-10-30 22:01
> Looks like regression introduced by #5708

Yup. With this program:
```C#
using System;
using System.Reflection;

class Test
{
    public static void Main()
    {
        foreach (var pi in typeof(object).Assembly.GetType("System.Runtime.Versioning.BinaryCompatibility").GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static))
        {
            Console.WriteLine(pi.Name + ": " + pi.GetValue(null, null));
        }
    }
}
```
if I run this against what's in master, I get:
```
TargetsAtLeast_Desktop_V4_5: False
TargetsAtLeast_Desktop_V4_5_1: False
AppWasBuiltForFramework: Unspecified
AppWasBuiltForVersion: 0
```
If I then revert https://github.com/dotnet/coreclr/commit/0e4869a6930cfb6278b51130bbccfc323ef61053 and run again, I get:
```
TargetsAtLeast_Desktop_V4_5: True
TargetsAtLeast_Desktop_V4_5_1: True
AppWasBuiltForFramework: NetFramework
AppWasBuiltForVersion: 50000
```
so that commit does appear to be the cause.

**Comment by AlexGhiondea** [comment] 2016-10-30 23:05
Indeed. The commit also defaults the tfm to unspecified instead of netframework and version 50000.

I can change the behavior for the BinaryCompatibility class to default to 50000.

Should we consider changing the quirks behavior to use AppContext?

**Comment by jkotas** [comment] 2016-10-31 00:15
The `BinaryCompatibility` quirks should be deleted (once the github / TFS mirror is turned off).

**Comment by Jiayili1** [comment] 2017-02-24 07:02
Disabled test, reopen it.

**Comment by AlexGhiondea** [comment] 2017-03-06 05:31
@Jiayili1 I am not sure what test you are referring to.

**Comment by jkotas** [comment] 2017-03-06 05:39
@AlexGhiondea https://github.com/dotnet/corefx/blob/b57805bd336892e707bf5238e86e31aef98e4bce/src/System.Threading.Tasks/tests/TaskFactory/TaskFactory_FromAsyncTests.cs#L563

**Comment by AlexGhiondea** [comment] 2017-03-07 09:28
Thanks for the link @jkotas -- I didn't realize we added a test for this. I will submit a PR to re-enable this.

**Comment by alexperovich** [comment] 2017-04-07 00:03
@AlexGhiondea it looks like the test was re-enabled. Can we close this?

**Comment by AlexGhiondea** [comment] 2017-04-12 20:36
Yup.

**Closed by AlexGhiondea** 2017-04-12 20:36 UTC
Labels: area-System.Threading, bug, disabled-test
