### ISSUE TITLE
Windows update corrupts struct construction in .Net 4.x

### ISSUE THREAD

**Issue by pavrosa** [dotnet/coreclr#14007] opened 2017-09-15 07:27 UTC
Since the installed of a Windows update on 14.9.2017 we have problems creating certain structs in our release builds - see relevant issue reported on [stackoverflow](https://stackoverflow.com/questions/46223714/windows-update-corrupts-struct-construction-in-net-4-x)

**Comment by benaadams** [comment] 2017-09-15 10:18
Occurs in x64 Release mode 

C:\Windows\Microsoft.NET\Framework64\v4.0.30319\corjit.dll, dated 9/6/17, 9:23AM CDT, version 4.7.2110.0.

After update [.NET Framework September 2017 Security and Quality Rollup](https://blogs.msdn.microsoft.com/dotnet/2017/09/12/net-framework-september-2017-security-and-quality-rollup/)


cc @dotnet/jit-contrib

**Comment by benaadams** [comment] 2017-09-15 10:28
From SO question
```csharp
class Program
{
    static void Main(string[] args)
    {
        DateTime start1 = new DateTime(1990, 1, 1, 6, 0, 0);
        DateTime end1 = new DateTime(2000, 1, 1, 6, 0, 0);
        var r2 = new DateTimeRange(start1, end1);
        var r3 = new Range<DateTime>(r2.From, r2.To);
        Console.WriteLine($"Wrong start: {r3.From}, correct start: {start1}");
        Console.ReadLine();
    }
}

public struct DateTimeRange 
{
    private Range<DateTime> m_range;

    public DateTimeRange(DateTime from, DateTime to)
    {
        m_range = new Range<DateTime>(from, to);
    }


    public DateTime From
    {
        get { return m_range.From; }
    }

    public DateTime To
    {
        get { return m_range.To; }
    }
}

public struct Range<T> where T : struct
{
    private T m_from;
    private T m_to;


    public Range(T from, T to)
    {
        m_from = from;
        m_to = to;
    }


    public T From
    {
        get { return m_from; }
    }

    public T To
    {
        get { return m_to; }
    }
}
```
Outputs 
```
Wrong start: 01-Jan-2000 6:00:00 AM, correct start: 01-Jan-1990 6:00:00 AM
```
Expected
```
Wrong start: 01-Jan-1990 6:00:00 AM, correct start: 01-Jan-1990 6:00:00 AM
```

**Comment by mikedn** [comment] 2017-09-15 18:02
I can't reproduce this with the current CoreCLR build or the released 2.0 build.

**Comment by benaadams** [comment] 2017-09-15 18:23
Thought couldn't recreate this however can. Has to be x64 on full framework

C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll `4.7.2552.0` is fine
(Win10 Version 1703 OS Build 16281.1000)

> Wrong start: 01-Jan-90 6:00:00 AM, correct start: 01-Jan-90 6:00:00 AM

C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll `4.7.2110.0` has the issue 
(Win10 Version 1703 OS Build 15063.608)

> Wrong start: 01-Jan-00 6:00:00 AM, correct start: 01-Jan-90 6:00:00 AM

Assuming version is clrjit is the info required; so I assume whatever it is has been fixed - however is present in a current version of Windows

**Comment by benaadams** [comment] 2017-09-15 18:41
That version of clrjit does look like ti comes from the 
.NET Framework September 2017 Security and Quality Rollup
`"Clrjit.dll","4.7.2110.0","1,129,112","01-Sep-2017","05:56","x64",`

**Comment by briansull** [comment] 2017-09-15 22:56
This issue is fixed and the Windows Patch for RS2 (build 1703) went out this week on Tuesday
Other versions of Window 10 already had the fix, just RS2 (build 1703) was still waiting for this.

You can install the patch here:

http://www.catalog.update.microsoft.com/Search.aspx?q=KB4038788

I selected:

2017-09 Cumulative Update for Windows 10 Version 1703 for x64-based Systems (KB4038788)

It may tell you that you already have the patch, if so you may need to restart you machine in order for the necessary files to be updated:

Afterwards you should have version 2110 of the clrjit.dll:

C:\Windows\Microsoft.NET\Framework\v4.0.30319>filever clrjit.dll
--a-- W32i   DLL ENU      4.7.2110.0 shp    522,904 09-01-2017 clrjit.dll

**Comment by briansull** [comment] 2017-09-15 23:02
Note that the failure case prints:
("Wrong start: 1.1.2000...").

**Comment by benaadams** [comment] 2017-09-15 23:03
> Note that the failure case prints:

Depends on locale

**Comment by briansull** [comment] 2017-09-15 23:09
Actually I take it back this patch doesn't contain the fix:

**Comment by benaadams** [comment] 2017-09-15 23:10
😢

**Comment by pavrosa** [comment] 2017-10-13 15:32
Does anybody have an idea how to escalate the problem? It's almost a month and it seams there is no activity. At the moment we live without updates, but...

**Comment by AndyAyersMS** [comment] 2017-10-13 16:07
@briansull can you update with latest status? Do we have a servicing fix for this in the works?

**Comment by briansull** [comment] 2017-10-13 18:37
The fix for this is in our upcoming release of .NET 4.7.1 

It will be in the Windows 10 Fall Creators Update that is schedule to be available this month.
We should also have a standalone update to .NET  4.7.1 available later on this month. (this update is expected to launch on October 17, 2017)

Currently a pre-release of .NET 4.7.1 is available here:
https://blogs.msdn.microsoft.com/dotnet/2017/08/07/welcome-to-the-net-framework-4-7-1-early-access/

**Comment by jkotas** [comment] 2017-10-27 13:31
Fixed in https://blogs.msdn.microsoft.com/dotnet/2017/10/17/announcing-the-net-framework-4-7-1/

**Closed by jkotas** 2017-10-27 13:31 UTC
