### ISSUE TITLE
RUNREADYTORUNCOMPILER : warning : Could not load type 'Microsoft.CodeAnalysis.CSharp.CodeGen.LocalDefUseSpan' from assembly 'Microsoft.CodeAnalysis.CSharp

### ISSUE THREAD

**Issue by wieslawsoltes** [dotnet/coreclr#24566] opened 2019-05-14 07:07 UTC
When using:
```
<PublishReadyToRun>True</PublishReadyToRun>
```
I get warnings:
```
RUNREADYTORUNCOMPILER : warning : Could not load type 'Microsoft.CodeAnalysis.CSharp.CodeGen.LocalDefUseSpan' from assembly 'Microsoft.CodeAnalysis.CSharp, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. while resolving 0x68000b72 - InvalidToken. [d:\a\1\s\src\Draw2D\Draw2D.csproj]
RUNREADYTORUNCOMPILER : warning : Could not load type 'Microsoft.CodeAnalysis.CSharp.CodeGen.LocalDefUseSpan' from assembly 'Microsoft.CodeAnalysis.CSharp, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. while resolving 0x68000b73 - InvalidToken. [d:\a\1\s\src\Draw2D\Draw2D.csproj]
```
.NET Core version:
```
3.0.100-preview5-011568
```
publish command:
```
dotnet publish ./src/Draw2D/Draw2D.csproj -f netcoreapp3.0 -c Release -r win7-x64 -o Draw2D_netcoreapp3.0_win7-x64
```

build log:
https://dev.azure.com/wieslawsoltes/GitHub/_build/results?buildId=1761&view=logs&jobId=275f1d19-1bd8-5591-b06b-07d489ea915a&taskId=37ff9366-b26f-54de-6861-3886e8f3e5fc&lineStart=37&lineEnd=38&colStart=1&colEnd=1

**Comment by wieslawsoltes** [comment] 2019-05-14 07:58
More errors from different app:
[log.txt](https://github.com/dotnet/coreclr/files/3176466/log.txt)

**Comment by jkotas** [comment] 2019-05-14 13:25
cc @fadimounir

**Comment by fadimounir** [comment] 2019-05-15 23:20
This is a bug in the IBC data in Microsoft.CodeAnalysis.CSharp.dll. We're trying to load a type with token 0x68000b72, with the following signature:
3c 	ELEMENT_TYPE_NATIVE_ARRAY_TEMPLATE_ZAPSIG
1d 	ELEMENT_TYPE_SZARRAY
12 	ELEMENT_TYPE_CLASS
92 	-> compressed token 0x2000497 (typedef for Microsoft.CodeAnalysis.CSharp.CodeGen.LocalDefUseSpan)

The problem is that LocalDefUseSpan is a struct, not a class, so the 3rd byte in the signature should have been 0x11 not 0x12 (ELEMENT_TYPE_VALUETYPE).

Did LocalDefUseSpan change to become a struct recently?

The IBC data attached to the assembly is probably out of date. 

@jaredpar Assigning this to you for further investigations. Crossgen is emitting a warning correctly here.

**Comment by jaredpar** [comment] 2019-05-15 23:22
@fadimounir not sure what investigation there is to be done here. We're using standard ibc tooling here and it's producing these assemblies. Shouldn't this be looked into by IBC team? @davidwrighton, @briansull

**Comment by jkotas** [comment] 2019-05-15 23:25
`LocalDefUseSpan` was class, and then it was changed to struct in https://github.com/dotnet/roslyn/pull/9250/files#diff-11f2c296a05a1c82a51bd46d735306ebL270

The IBC data was likely collected before this change, and then applied after this change. Seeing these type of warnings is not unusual with incremental IBC.

**Comment by fadimounir** [comment] 2019-05-15 23:25
> not sure what investigation there is to be done here

If the LocalDefUseSpan type was a class and recently changed to become a struct, and the IBC data was not regenerated and attached to the assembly, then we can just easily regenerate the data I believe. 

If the IBC data is up to date, then it might be a bug with the IBC tooling and we can have someone from the IBC team take a look.

**Comment by fadimounir** [comment] 2019-05-15 23:26
@jkotas is there a way to patch the existing IBC data with correct signatures that reflect these updates?

**Comment by jkotas** [comment] 2019-05-15 23:29
> @jkotas is there a way to patch the existing IBC data with correct signatures that reflect these updates?

I am pretty sure that the latest `Microsoft.CodeAnalysis.CSharp` NuGet package is not going to have this problem anymore.

The real question here is whether these warnings caused by incremental IBC are "by design" or whether we want to do something about them.

**Comment by fadimounir** [comment] 2019-05-15 23:46
> or print these warnings in verbose crossgen mode only

We can do that for IBC related typeloader failures, unless we want to catch these issues. It's hard to think that we'll ever effectively run crossgen in verbose mode to catch such issues, but I do agree that it could be nice to hide IBC related warnings.
I'll work on that change.

**Closed** 2019-05-16 14:19 UTC
Labels: area-ReadyToRun

**Comment by briansull** [comment] 2019-05-16 17:18
Such warning are by design and are there to help a user understand that certain types or methods are out dated in the incremental IBC data.
