### ISSUE TITLE
Assembly.Load does not find assembly in the application base directory

### ISSUE THREAD

**Issue by slozier** [dotnet/coreclr#11498] opened 2017-05-10 19:21 UTC
I tried the following:
```
Debug.Assert(File.Exists(Path.Combine(AppDomain.CurrentDomain.Base​Directory, "test2.dll")));
Assembly.Load("test2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");
```
which results in a `FileNotFoundException`. Works fine with .NET Framework.

All the documentation I'm finding relates to the .NET Framework and says that Assembly.Load will do probing in the application base directory if it fails to find the assembly elsewhere. If .NET Core is supposed to behave differently is there some documentation outlining the differences?

I guess as a workaround I could use `AssemblyResolve` and implement the probing myself?

**Comment by gkhanna79** [comment] 2017-05-11 15:23
> I guess as a workaround I could use AssemblyResolve and implement the probing myself?

Yes, this is by design for .NET Core.  https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md talks about how assembly loading works in .NET Core.

**Comment by karelz** [comment] 2017-05-18 00:54
@gkhanna79 if it is by design, can we close it?

**Comment by slozier** [comment] 2017-05-18 02:03
Seems like a bit of an odd design choice. Makes it hard to use the Assembly.Load* methods on existing assemblies. For example I have A.dll which references B.dll. I place both files in the application folder and use Assembly.LoadFrom to load A. I then use a bit of reflection to invoke a method on A which uses something in B and I end up with a `TargetInvocationException`. It works fine with the .NET Framework and .NET Core 1.0 (doesn't work with 1.1 and 2.0).

I managed to work around it with `AssemblyResolve` but it seems like it's something that should just work out of the box.

**Comment by gkhanna79** [comment] 2017-05-18 02:31
The assembly binding behavior is, by design, distinctly different between Desktop and .NET Core. In 1.0, it happened to work due to a bug in the host that was fixed in 1.1.

Assembly.LoadFrom is a .NET Framework API that has been supported in 2.0 and for it, we emulate the desktop behavior.

**Closed** 2017-10-25 03:58 UTC
Labels: area-Assembly Loader

**Comment by jkotas** [comment] 2017-10-25 04:02
Also see https://github.com/dotnet/core-setup/pull/2717#issuecomment-310539999

**Comment by ankgupta067** [comment] 2018-04-05 11:35
@jkotas 
how do we specify entry in runtimeconfig.json something like this, cant find an article hence posting here 
"runtimeOptions": {
    "Microsoft.NETCore.DotNetHostPolicy.SetAppPaths" : true,
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }

**Comment by b8adamson** [comment] 2019-01-16 19:53
FWIW This is the runtimeconfig.json that works for me:

{
  "runtimeOptions": {
    "tfm": "netcoreapp2.2",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.2.0"
    },
    "configProperties": {
      "Microsoft.NETCore.DotNetHostPolicy.SetAppPaths": true
    }
  }

As best I can tell it gets used by the default dotnet.exe host here:
https://github.com/dotnet/core-setup/blob/be4e2eb3709ab5b307ff581f222fd2a4c7a2dc94/src/corehost/cli/hostpolicy.cpp#L182
