### ISSUE TITLE
New tests failing on Ubuntu Linux, but passing on Windows and OS X.

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#3235] opened 2016-02-18 19:59 UTC
The following new tests fail on Unbuntu Linux, but pass on Windows and OS X:

```
JIT/jit64/localloc/eh/eh01_dynamic/eh01_dynamic.sh
JIT/jit64/localloc/eh/eh01_large/eh01_large.sh
JIT/jit64/localloc/eh/eh01_small/eh01_small.sh
JIT/jit64/localloc/eh/eh02_dynamic/eh02_dynamic.sh
JIT/jit64/localloc/eh/eh02_large/eh02_large.sh
JIT/jit64/localloc/eh/eh02_small/eh02_small.sh
JIT/jit64/localloc/ehverify/eh09_dynamic/eh09_dynamic.sh
JIT/jit64/localloc/ehverify/eh09_large/eh09_large.sh
JIT/jit64/localloc/ehverify/eh09_small/eh09_small.sh
JIT/jit64/localloc/unwind/unwind01_dynamic/unwind01_dynamic.sh
JIT/jit64/localloc/unwind/unwind01_large/unwind01_large.sh
JIT/jit64/localloc/unwind/unwind01_small/unwind01_small.sh
JIT/jit64/localloc/unwind/unwind02_dynamic/unwind02_dynamic.sh
JIT/jit64/localloc/unwind/unwind02_large/unwind02_large.sh
JIT/jit64/localloc/unwind/unwind02_small/unwind02_small.sh
JIT/jit64/localloc/unwind/unwind03_dynamic/unwind03_dynamic.sh
JIT/jit64/localloc/unwind/unwind03_large/unwind03_large.sh
JIT/jit64/localloc/unwind/unwind03_small/unwind03_small.sh
JIT/Regression/Dev11/External/dev11_145295/CSharpPart/CSharpPart.sh
JIT/Methodical/localloc/call/call01_small/call01_small.sh
```

They have been added to the non-Windows failure list.

**Comment by RussKeldorph** [comment] 2016-02-19 16:43
@sivarv Could you work your triage magic on these as well?

**Comment by sivarv** [comment] 2016-02-19 23:50
@richardlford so far i have tried to repro the following test failures and i couldn't repro against latest git bits as of now.  

JIT/jit64/localloc/unwind/unwind01_dynamic/unwind01_dynamic.sh
JIT/Regression/Dev11/External/dev11_145295/CSharpPart/CSharpPart.sh
JIT/Methodical/localloc/call/call01_small/call01_small.sh

I am running checked tests against debug CoreCLR product bits.  Please let me know whether the failure is against debug/checked/release version of the test binary and what is the failure that was observed?  Could you repro these failures locally or have test binaries that I could use to repro the failures?

**Comment by sivarv** [comment] 2016-02-22 21:31
I have manually run all of these tests and they have passed on Ubuntu.  These tests depend on common.dll and on Ubuntu that tests are not finding it and failing with FileNotFoundException.  This seems like a test build or infra issue.

Marking it as test issue and assigning it back to @richardlford

**Comment by BruceForstall** [comment] 2016-05-12 23:11
Looks like perhaps a casing issue in the test:
```
diff --git a/tests/src/JIT/jit64/localloc/common/common.il b/tests/src/JIT/jit64/localloc/common/common.il
index 9b65bcf..90f513f 100644
--- a/tests/src/JIT/jit64/localloc/common/common.il
+++ b/tests/src/JIT/jit64/localloc/common/common.il
@@ -13,12 +13,12 @@
 .assembly extern mscorlib
 {
 }
-.assembly Common
+.assembly common
 {
   .hash algorithm 0x00008004
   .ver 0:0:0:0
 }
-.module Common.dll
+.module common.dll
 .custom instance void [mscorlib]System.Security.UnverifiableCodeAttribute::.ctor() = ( 01 00 00 00 )
 .imagebase 0x00400000
 .subsystem 0x00000003
```

**Closed** 2016-05-15 04:23 UTC
Labels: 2 - In Progress, CodeGen, Test-Issue
