### ISSUE TITLE
[Question] How to debug deadlock in Task?

### ISSUE THREAD

**Issue by sillyousu** [dotnet/coreclr#13764] opened 2017-09-02 11:20 UTC
Are there any tools/runtime infrastructure for debugging deadlock and Task hang?

```csharp
using System;
using System.Threading.Tasks;
using System.Threading;

namespace Deadlock
{
    class Program
    {
        static void Main(string[] args)
        {
            SemaphoreSlim semaphore1 = new SemaphoreSlim(0);
            SemaphoreSlim semaphore2 = new SemaphoreSlim(0);


            var t1 = Task.Run(async () =>
            {
                await semaphore1.WaitAsync();
                semaphore2.Release();
            });


            var t2 = Task.Run(async () =>
            {
                await semaphore2.WaitAsync();
                semaphore1.Release();
            });

            Task.WaitAll(t1, t2);
        }
    }
}
```

**Comment by kevingosse** [comment] 2017-09-02 17:46
You can attach a debugger, break the execution, and inspect the callstacks (the "parallel stacks" window of Visual Studio is especially useful for that). Or do you mean an automated way?

**Comment by sillyousu** [comment] 2017-09-02 18:30
hello @kevingosse , thank you for reply. 

1. In VS 2017 "parallel stacks" shows "No tasks to display" in **task mode**.  Do I miss something?
2. It's not good to pause a running process in production for long time. Can I just print all threads/tasks call stack (like java/golang)?

**Comment by kevingosse** [comment] 2017-09-02 21:41
> In VS 2017 "parallel stacks" shows "No tasks to display" in task mode. Do I miss something?

I'm not sure. I always use the "thread" view.

> It's not good to pause a running process in production for long time. Can I just print all threads/tasks call stack (like java/golang)?

Once your threads are deadlocked, you'll need to restart the server anyway. If you can't afford to take the server offline long enough to investigate, you can work on a memory dump. There are many tools that allow you to take memory dumps (including the Windows task manager), but I'd personally recommend Procdump from Sysinternals. 

After you've confirmed that your process is deadlocked, just run: 

> procdump -ma 9999 -o C:\temp\dump.dmp

Just replace 9999 by the pid and "dump.dmp" by the desired file name.

When you have the memory dump, you can open it directly in Visual Studio, and inspect the stacktraces to your heart content (just drag the file on Visual Studio, then select "Debug with Managed Only". Make sure the symbol sources are properly configured, there's plenty of resources out there to explain how to do that).

**Comment by sillyousu** [comment] 2017-09-03 07:52
@kevingosse 

>In VS 2017 "parallel stacks" shows "No tasks to display" in task mode. Do I miss something?
>I'm not sure. I always use the "thread" view.

thread view doesn't provide too much useful information in this case.
I can see main thread's callstack. But deadlock is inside those two missing tasks. 

**memory dump** is exactly what I eager to.  Sadly, our team mostly work on MacOS. And our software needs run on Linux. Is there any procdump alternative for MacOS/Linux? 

The [createdump](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md) seems like an alternative to procdump in Unix, though I don't figure out how to create a dump for a live process.

with `createdump  3790`, I got:
```
 Writing minidump with heap to file /tmp/coredump.3790
ReadMemory(0x7fff5007b000, 40) ehdr FAILED
```

**Comment by janvorli** [comment] 2017-09-05 14:53
@mikem8361 can the createdump be used externally on a running process like @sillyousu described above or is it only intended to capture dumps during crash when the createdump is launched by the coreclr PAL?

**Comment by mikem8361** [comment] 2017-09-05 17:16
Createdump should be able to capture dumps on a running process, but it hasn’t been tested in that mode a lot.  The createdump failure is probably fixed in master and in 2.0.2 (the next service release).

@sillyousu if you added “--diag” to the command line and redirect the console (both stdout and stderr) to a file, I can better diagnose the problem.  I’ll also try something similar to your scenario locally.

**Comment by sillyousu** [comment] 2017-09-05 17:56
```
➜  Deadlock dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

```
Linux localhost.localdomain 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
ps -ef|grep dotnet
sandbox  27290 27238  2 01:46 pts/1    00:00:02 dotnet run
sandbox  27364 27290  0 01:47 pts/1    00:00:00 dotnet exec /home/sandbox/supei/Deadlock/bin/Debug/netcoreapp2.0/Deadlock.dll
```


[createdump_27364.txt](https://github.com/dotnet/coreclr/files/1278383/createdump_27364.txt)
[createdump_27290.txt](https://github.com/dotnet/coreclr/files/1278384/createdump_27290.txt)

@mikem8361

**Comment by mikem8361** [comment] 2017-09-05 21:49
Here is a version of createdump that may fix you problem. Could you try it? It would need to be copied to /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0 (the directory on my Ubuntu machine). You should probably mv the original to another file.  

[createdump.zip](https://github.com/dotnet/coreclr/files/1279034/createdump.zip)

**Comment by sillyousu** [comment] 2017-09-06 02:11
>Here is a version of createdump that may fix your problem. Could you try it?
sure.


the new output here:

```
md5sum
7465ad4c22e1d5ac591e7479431d70b7  /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0/createdump
```

```
ps -ef|grep dotnet
sandbox  29583 29478  0 10:01 pts/2    00:00:03 dotnet run
sandbox  29656 29583  0 10:01 pts/2    00:00:00 dotnet exec /home/sandbox/Deadlock/bin/Debug/netcoreapp2.0/Deadlock.dll
```

```
/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0/createdump -d 29656 1>createdump_29656.txt
ReadMemory(0x7ffc29ece000, 40) ehdr FAILED
```
[createdump_29656.txt](https://github.com/dotnet/coreclr/files/1279525/createdump_29656.txt)


```
 /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0/createdump -d 29583 1>createdump_29583.txt
ReadMemory(0x7ffddf6bb000, 40) ehdr FAILED
```
[createdump_29583.txt](https://github.com/dotnet/coreclr/files/1279526/createdump_29583.txt)

**Comment by mikem8361** [comment] 2017-09-06 05:13
Is there anyway you can zip up your Deadlock.dll and any assemblies needed and attach it here? It would be simpler for me to debug this locally.

**Comment by sillyousu** [comment] 2017-09-06 05:45
[Deadlock.zip](https://github.com/dotnet/coreclr/files/1279913/Deadlock.zip)


```
├── Deadlock.csproj
├── Program.cs
├── bin
│   └── Debug
│       └── netcoreapp2.0
│           ├── Deadlock.deps.json
│           ├── Deadlock.dll
│           ├── Deadlock.pdb
│           ├── Deadlock.runtimeconfig.dev.json
│           └── Deadlock.runtimeconfig.json
└── obj
    ├── Deadlock.csproj.nuget.cache
    ├── Deadlock.csproj.nuget.g.props
    ├── Deadlock.csproj.nuget.g.targets
    ├── Debug
    │   └── netcoreapp2.0
    │       ├── Deadlock.AssemblyInfo.cs
    │       ├── Deadlock.AssemblyInfoInputs.cache
    │       ├── Deadlock.csproj.CoreCompileInputs.cache
    │       ├── Deadlock.csproj.FileListAbsolute.txt
    │       ├── Deadlock.dll
    │       └── Deadlock.pdb
    └── project.assets.json`
```

**Comment by sillyousu** [comment] 2017-09-06 06:42
BTW createdump in 2.0.0-preview2-006494 work perfectly. 
```
.NET Command Line Tools (2.0.0-preview2-006494)

Product Information:
 Version:            2.0.0-preview2-006494
 Commit SHA-1 hash:  3725fef54f

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /opt/dotnet/sdk/2.0.0-preview2-006494/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by mikem8361** [comment] 2017-09-06 22:17
I can't repro your problem with your program running on Ubuntu 14.04.  I'll try on my Centos VM.  

Not sure why an older version (preview2) of createdump/runtime would work.

**Comment by mikem8361** [comment] 2017-09-09 00:24
When you get a chance, could you try this version?  It fixes it locally for me on my Centos VM.

[createdump.zip](https://github.com/dotnet/coreclr/files/1289412/createdump.zip)

**Comment by sillyousu** [comment] 2017-09-09 06:26
>When you get a chance, could you try this version? It fixes it locally for me on my Centos VM.

I can confirm that it works on our Centos VM.
Thank you.

**Comment by mikem8361** [comment] 2017-09-12 19:41
Should be fixed now in master.

**Closed by mikem8361** 2017-09-12 19:41 UTC
Labels: area-Diagnostics
