### ISSUE TITLE
double.Parse(double.MinValue.ToString()) and double.Parse(double.MaxValue.ToString()) throw an System.OverflowException

### ISSUE THREAD

**Issue by qaqz111** [dotnet/coreclr#13615] opened 2017-08-27 06:01 UTC
```C#
double.Parse(double.MinValue.ToString());
//or
double.Parse("-1.79769313486232E+308");

//and

double.Parse(double.MaxValue.ToString());
//or
double.Parse("1.79769313486232E+308");
```
These codes will throw a System.OverflowException which says "the value is too big or too small as double", while float with float.MaxValue and float.MinValue does not.

**Comment by danmosemsft** [comment] 2017-08-27 19:54
Same in desktop. Maybe @tannergooding knows.

**Comment by qaqz111** [comment] 2017-08-27 20:02
I've found an old related issue, looks like it's been noticed and scheduled.
- Convert.ChangeType throws exception when converting Double.MaxValue #5989

**Comment by tannergooding** [comment] 2017-08-28 16:24
@danmosemsft, there are multiple bugs tracking in accuracies with the `double.Parse()` and `double.ToString()` methods.

If you want to round-trip, you must use `double.ToString("G17")` (`R` has its own bugs and does not ensure round-tripping will work).

There are some active PRs that fix some issues and some discussions on what to do about `R` (its been broken for a very long time, so the discussions are around whether taking the break is worthwhile).

I'll see if I can find the related PRs/issues and tag them here in a bit.

**Comment by mazong1123** [comment] 2017-08-31 03:40
@tannergooding  I think it's easy for me to find these PRs and issues :)

Overflow for MaxValue: https://github.com/dotnet/coreclr/issues/5989

PR and issues related to "R":
https://github.com/dotnet/coreclr/pull/13140
https://github.com/dotnet/coreclr/issues/13106
https://github.com/dotnet/coreclr/issues/10651#issuecomment-315667429

**Comment by mazong1123** [comment] 2017-08-31 03:45
We'd better handle the edge cases(MaxValue/MinValue) inside parse instead of asking user to use round-trip specifier.

**Comment by tannergooding** [comment] 2017-08-31 17:38
@mazong1123, thanks. This completely slipped my radar.

We should probably just start this by moving to the Roslyn `RealParser` (https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/RealParser.cs) which has been confirmed to be precise/valid according to the IEEE spec.

**Comment by mazong1123** [comment] 2017-09-01 04:43
@tannergooding my understanding is [this `ToString` implementation](https://github.com/dotnet/coreclr/pull/12894) is following IEEE spec, so now we just need to re-write the parsing part. Is that correct?

Do we plan to implement `RealParser` in native part of coreclr or totally rewrite the whole tostring/parsing logic in managed code (I saw this is our eventually goal here: https://github.com/dotnet/coreclr/issues/10390#issuecomment-289457558)?

**Comment by tannergooding** [comment] 2017-09-01 04:55
Yes, I believe  [this `ToString` implementation](https://github.com/dotnet/coreclr/pull/12894) implementation is compliant, although it might be worthwhile to run the `RandomRealParserTests.sln` suite the compiler has to help validate that.

> Do we plan to implement RealParser in native part of coreclr...

Writing it in managed is the better long term goal (IMO), but it probably depends on the perf numbers as well. The current `RealParser` implementation, while in managed, looks like it incurs several heap allocations and isn't very well optimized for speed.

**Comment by jkotas** [comment] 2017-09-01 05:02
> Writing it in managed is the better long term goal

Yes, we want to have all parsing and formatting in C#. See #13544.

> The current `RealParser` implementation, while in managed

Agree.

**Comment by mazong1123** [comment] 2017-09-01 05:54
> Yes, we want to have all parsing and formatting in C#. See #13544.
@jkotas seems like @stephentoub has already started working on this issue (if not I can help working on it).

I think we can re-write `ToString()` in managed code as well after https://github.com/dotnet/coreclr/pull/12894 merged.

**Comment by tannergooding** [comment] 2017-09-01 06:59
@mazong1123, based on the comments, it needs to be run manually. It sounds like it runs a lot of validation and could take some time to complete.

**Comment by tannergooding** [comment] 2019-02-01 20:21
Now that #22040 is merged, for .NET Core 3.0, ToString(), ToString("G"), ToString("R"), double.ToString("G17"), and float.ToString("G9") should now always produce a string that will roundtrip to the original value..

I will keep this open until an explicit testcase for `double.MinValue` and `double.MaxValue`.

**Closed** 2019-02-04 23:53 UTC
Labels: area-System.Runtime, bug
