### ISSUE TITLE
#enhancement fullnameof and other

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/coreclr#23968] opened 2019-04-13 17:21 UTC
Hi!
There is a very convenient operator - nameof.
He cuts all after the last point.
But sometimes it is useful to display the full name.
* fullnameof
    ```csharp
   fullnameof (NameSpace.Class.Property)
   fullnameof (ObjectName.Property)
   ```

**Comment by jkotas** [comment] 2019-04-13 19:00
Duplicate of https://github.com/dotnet/csharplang/issues/2154

**Closed by jkotas** 2019-04-13 19:00 UTC
