### ISSUE TITLE
Test failed: JIT_Regression._CLR_x86_JIT_V1_M09_5_PDC_b16423_b16423_b16423_._CLR_x86_JIT_V1_M09_5_PDC_b16423_b16423_b16423_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25418] opened 2019-06-26 02:31 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-ci/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190625.38/workItem/JIT.Regression.CLR-x86-JIT.V1-M09-M11/analysis/xunit/JIT_Regression._CLR_x86_JIT_V1_M09_5_PDC_b16423_b16423_b16423_~2F_CLR_x86_JIT_V1_M09_5_PDC_b16423_b16423_b16423_cmd

**Failed tests:**
JIT_Regression._CLR_x86_JIT_V1_M09_5_PDC_b16423_b16423_b16423_._CLR_x86_JIT_V1_M09_5_PDC_b16423_b16423_b16423_cmd

**Log:**
```
Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\4b26e8e6-dedb-48a6-9521-a9f0761f593d\\Exec\\JIT\\Regression\\Reports\\JIT.Regression\\CLR-x86-JIT\\V1-M09.5-PDC\\b16423\\b16423\\b16423.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload\\corerun.exe\" b16423.exe 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload
> C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\4b26e8e6-dedb-48a6-9521-a9f0761f593d\\Exec\\JIT\\Regression\\CLR-x86-JIT\\V1-M09.5-PDC\\b16423\\b16423\\b16423.cmd
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment] 2019-06-26 16:28
https://github.com/dotnet/coreclr/pull/25429

**Comment by RussKeldorph** [comment] 2019-06-26 23:57
Assuming duplicate of #25376

**Closed by RussKeldorph** 2019-06-26 23:57 UTC
Labels: arch-arm32, os-windows
