### ISSUE TITLE
ReadyToRun: System.OverflowException in 3 tests under JIT\Regression\CLR-x86-JIT

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3611] opened 2016-03-09 03:02 UTC
Tests:
JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b223936\b223936\b223936.exe
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b31273\b31273\b31273.exe
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b68028\b68028\b68028.exe

Repro steps:
 Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
 E:\coreclr>build checked skiptests
 E:\coreclr>tests\buildtest.cmd checked crossgen
 E:\coreclr>tests\runtest.cmd checked

Output for the first of these tests:
BEGIN EXECUTION
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image E:\coreclr\bin\tests\Windows_NT.x64.Checked\JIT\Regression\CLR-x86-JIT\V1.2-Beta1\b223936\b223936\ILGEN_0xca498c54.ni.exe generated successfully.
 "E:\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" b223936.exe

Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at ILGEN_0xca498c54.Method_0x570110b9(Double Arg_0x0, Single Arg_0x1, UInt32 Arg_0x2, SByte Arg_0x3, SByte Arg_0x4, Int64 Arg_0x5, UInt16 Arg_0x6, Int64 Arg_0x7, UInt64 Arg_0x8, SByte Arg_0x9, SByte Arg_0xa, SByte Arg_0xb, Single Arg_0xc, SByte Arg_0xd)
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED

**Comment by LLITCHEV** [comment] 2016-03-10 06:33
This looks like a duplicate of issue #3613

**Closed by LLITCHEV** 2016-03-10 06:33 UTC
Labels: bug, CodeGen, ReadyToRun
