### ISSUE TITLE
[Perf][x86 & x64] Investigate performance regression in SpectralNorm_3

### ISSUE THREAD

**Issue by nategraf** [dotnet/coreclr#16615] opened 2018-02-27 01:36 UTC
There appears a 25% performance regression in release/2.1 as compared 7f14336

A possible cause for this regression has yet be found

**Comment by AndyAyersMS** [comment] 2018-03-02 19:45
I'll investigate.

**Comment by AndyAyersMS** [comment] 2018-03-02 20:54
Locally when I run this master/2.1 is considerably faster than 2.0 (~350 vs ~610). Raw numbers are nothing like what benchview sees (~2500 for 2.0, ~3200 for master/2.1). But this test is multithreaded (creating 100 tasks by default) and so absolute perf will be very machine dependent.

Looking at the benchview history for master we see the same stable perf level since October 2017 (test was introduced in September 2017 but can't quite see back that far). And 2.0 has always been around ~2500 right from the introduction of the test.

So if this is a regression whatever introduced it happened sometime between roughly April 2017 (when we branched for 2.0) and October 2017 when we already see master slower.

Or perhaps there is something different about how we are making measurements for 2.0 from master/2.1 in a way that critically effects this test but not most other tests. IIRC the "stability prefix" we use for actual measurements may involve setting thread affinity and that might have a dramatic distorting effect on multithreaded tests like this one.

Need to do some more digging.

**Comment by AndyAyersMS** [comment] 2018-03-04 20:00
Hmm, can't repro the local numbers above. Think I was looking at the wrong results files. 

Trying to be careful this time: locally master/2.1 and 2.0 look comparable, both around 880ms. The stability prefix does not seem to have any effect on either set of runs.

Run commands from automation seem comparable. But results are quite different, both in absolute time and also comparative times.

[2.0](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.1/job/perf_perflab_Windows_NT_x64_full_opt_ryujit/lastSuccessfulBuild/consoleFull)
```
START "CORECLR_PERF_RUN" /B /WAIT /HIGH /AFFINITY 0x2
corerun.exe PerfHarness.dll "C:\J\w\perf_perflab_---9e4a1ef8\sandbox\spectralnorm-3.exe"
--perf:runid "Perf-Off" --perf:collect stopwatch
```

[2.1](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.1/job/perf_perflab_Windows_NT_x64_full_opt_ryujit/13/consoleFull)
```
START "CORECLR_PERF_RUN" /B /WAIT /HIGH /AFFINITY 0x2
C:\j\w\perf_perflab_---0a4d2934\bin\sandbox\corerun.exe PerfHarness.dll C:\j\w\perf_perflab_
  ---0a4d2934\bin\sandbox\spectralnorm-3.exe 
--perf:outputdir C:\j\w\perf_perflab_
  ---0a4d2934\bin\sandbox_logs\Microbenchmarks\Off\spectralnorm-3 
--perf:runid Perf-Off --perf:collect stopwatch
```

So I can't yet explain why automation is so much slower than a local run, or why it sees 2.1 as so much slower than 2.0.

Am going to rerun on a machine with fewer cores. That might change the absolute times, but it is harder to imagine it would change the relative times.

**Comment by AndyAyersMS** [comment] 2018-03-04 21:13
Similar results on my laptop (2 physical cores, 4 with HT), both run in around 1060ms, affinity has no real impact, fairly low spread in results.

If we look at raw CI perf runs there's not much results spread either, despite the small number of iterations. So the runs on the perf machines are self-consistent and not very noisy.


[2.0](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.0.0/job/perf_perflab_Windows_NT_x64/756/artifact/Perf-Off-spectralnorm-3.log/*view*/):
```
 Test Name                              | Metric   | Iterations |  AVERAGE | STDEV.S |      MIN |      MAX
:-------------------------------------- |:-------- |:----------:| --------:| -------:| --------:| --------:
 BenchmarksGame.SpectralNorm_3.RunBench | Duration |     4      | 2603.707 |   9.222 | 2592.974 | 2612.897
```
And as I noted above the historical 2.0 results show it has more or less always run at this speed (ignoring some occasional glitches):

![image](https://user-images.githubusercontent.com/10121823/36950512-bfebdeb6-1fab-11e8-95ee-79dbe9cf9f79.png)

[2.1](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.1/job/perf_perflab_Windows_NT_x64_full_opt_ryujit/lastSuccessfulBuild/artifact/bin/sandbox_logs/Microbenchmarks/Off/spectralnorm-3/Perf-Off-spectralnorm-3.log/*view*/):
```
 spectralnorm-3.exe                     | Metric   | Unit | Iterations |  Average | STDEV.S |      Min |      Max
:-------------------------------------- |:-------- |:----:|:----------:| --------:| -------:| --------:| --------:
 BenchmarksGame.SpectralNorm_3.RunBench | Duration | msec |     4      | 3253.389 |   9.614 | 3244.267 | 3264.946
```
And likewise the master/2.1 results have always more or less run at the same speed (note we run perf tests in master much more frequently than on release branches, so we have a lot of data):

![image](https://user-images.githubusercontent.com/10121823/36950544-49fe6b8c-1fac-11e8-93b3-b5fe4d27dea7.png)

Unfortunately the official CI perf runs with HW perf counter data don't seem comparable; likely we did work during the 2.1 cycle to reduce overhead and so it makes the 2.1 vs 2.0 measurements here incomparable.

So I think the next step here is to get access to the actual perf HW and see if we can repro these results running manually; if so we can get some profiles and figure out what is going on.

@nategraf @jorive can you help with this?

**Comment by jorive** [comment] 2018-03-05 19:39
@AndyAyersMS Please let me know if you need me to reserve a machine in the lab for investigation.

**Comment by AndyAyersMS** [comment] 2018-03-05 19:51
Yes, I need access to a lab machine.

**Comment by AndyAyersMS** [comment] 2018-03-06 21:21
Did some runs on the perf lab HW, and I can repro the regression there. It is tied to the stability prefix, in particular to setting thread affinity:

 spectralnorm-3                         | Metric   | Unit | Iterations | Average | STDEV.S |     Min |     Max
:-------------------------------------- |:-------- |:----:|:----------:| -------:| -------:| -------:| -------:
 2.0 no prefix | Duration | msec |     16     | 639.894 |   4.617 | 637.742 | 656.926
 2.1 no prefix | Duration | msec |     15     | 667.185 |   6.502 | 661.895 | 687.407
 2.0 with prefix | Duration | msec |    4      | 2599.272 |  11.594 | 2586.324 | 2610.575
 2.1 with prefix | Duration | msec |    4      | 3248.472 |   8.076 | 3239.435 | 3259.090

I don't know yet why this only happens on the perf machines and what is different in 2.1 than in 2.0. But it is likely not a jit regression.

I played around a bit with varying the affinity mask for the 2.1 perf runs. Can't really explain these results either. More cores is generally better, but not in any simple fashion.

Perf lab machine is a i7-4790 (1 socket, 4 cores, 8 cpus) running Win16 server. My laptop processor has same physical configuration but is running Win 10 and doesn't show this behavior.

So this could be an OS thing or the way the Server OS interacts with the task scheduler?

@stephentoub any ideas on what to look at here? Did we change something about how tasks are distributed in 2.1 vs 2.0, and/or made the behavior more OS version dependent? 

Note [this benchmark](https://github.com/dotnet/coreclr/blob/master/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm/spectralnorm-3.cs) fires up 100 tasks then waits for them one by one in the order they were created. Seems like a wait all would be more appropriate and waiting serially like this might explain the odd behavior below...?

 Affinity mask                           |  Average | STDEV.S |      Min |      Max
:-------------------------------------- | --------:| -------:| --------:| --------:
 0x1                                     | 3248.244 |   8.379 | 3241.980 | 3260.136
 0x2 (stability prefix)                                     | 3250.356 |   9.840 | 3241.167 | 3261.601
 0x4                                     | 3245.788 |   9.951 | 3236.338 | 3257.570
 0x3                                     | 2592.315 |  57.257 | 2545.437 | 2672.468
 0x6                                     | 1807.702 | 250.600 | 1627.199 | 2298.042
 0x7                                     | 1801.594 |  13.978 | 1779.896 | 1821.446
 0xE                                     | 1749.836 |  12.811 | 1731.187 | 1766.686
 0xF                                     | 1483.385 | 370.838 | 1325.545 | 2319.622
 0xAA                                    | 915.915 | 253.019 | 805.230 | 1660.661
 0xEE                                    | 854.612 | 162.752 | 791.240 | 1367.983
 0xEF                                    | 839.430 | 158.993 | 771.751 | 1340.725
 0xFE                                    | 945.872 | 280.420 | 817.504 | 1785.285
 0xFF                                    | 639.217 |   0.666 | 637.626 | 640.427

**Comment by stephentoub** [comment] 2018-03-06 21:29
> @stephentoub Stephen Toub FTE any ideas on what to look at here? Did we change something about how tasks are distributed in 2.1 vs 2.0, and/or made the behavior more OS version dependent?

Not to my knowledge, though there have been some changes related to spinning, which maybe could impact this? cc: @kouvel

**Comment by AndyAyersMS** [comment] 2018-03-06 22:28
A crude linear model for an 8 CPU machine would look something like the following (with N ~ 370, K ~ 270, fitting to the endpoints):

Cpus | Predicted  | Observed     |  Model 
 ---: | ---:        | ---:         | ----:
1    | 8N + K     |   3250       |  3250
2    | 4N + K     |   1800, 2590  |  1750
3    | 3N + K     |   1800, 1740      |  1380
4-7  | 2N + K     |    915, 1480  |  1010
8    | 1N + K     |    640       |   640

So it is in the ballpark...

**Comment by AndyAyersMS** [comment] 2018-03-06 23:23
Also work is divided up into 8 chunks, but the last chunk gets all the leftovers too. So for the default length 100 we have 7 tasks each running 12 iterations, and one task running 16. So for cases where number of tasks is not divisible by number of available CPUs we would expect ~33% variance as the overall time depends on when the longer task is run. And we sort of see that above.

Official benchmark games run rules start with length 5550 so the task size discrepancy is less there.

**Comment by AndyAyersMS** [comment] 2018-03-07 00:28
Did some profiling and verified we are indeed running on just one CPU in both cases.

And it does indeed look like the spin wait cost is higher in master/2.1 than in 2.0. Again this is taken from the odd case where we've affinitized down to one CPU -- not sure it is interesting in general.

I will look at the non-affinitized case next as it still seems to run a bit slower than it did in 2.0.

2.0 profile (with /affinity 0x2):
![image](https://user-images.githubusercontent.com/10121823/37066433-3e320fb6-215a-11e8-8d13-017cdf185015.png)

2.1/master profile (with /affinity 0x2):
![image](https://user-images.githubusercontent.com/10121823/37066450-4f64c30a-215a-11e8-9348-77a8747d36dd.png)

@jorive as we discussed privately we should stop setting CPU affinity for the various benchmarks that run on multiple CPUs. I'll open an issue for you on this soon with a list of the tests to exclude.

**Comment by kouvel** [comment] 2018-03-07 09:31
Most of the ThreadNative::SpinWait time seems to come from Barrier.DiscontinuousWait -> ManualResetEventSlim.Wait. The spin strategy used there (SpinWait struct's spin strategy) has changed in multiple ways, including to normalize the delay per spin iteration to the delay on Skylake processors (which significantly increased the pause instruction's delay), to change the back-off scheme, and to cap the delay to a max.

According to profiles with and without affinitizing the test seems to spend a significant amount of time spinning.

On pre-Skylake processors, the first few iterations of a spin-wait would be longer than before, and subsequent iterations would be shorter to much shorter than before. In this particular case, the test seems to synchronize threads on a barrier very frequently, and the spin-wait likely succeeds within those first few iterations, which have a longer delay now. As a result, this is taking longer on pre-Skylake processors.

On Skylake processors, the first few iterations would be shorter than before due to spin strategy changes, so the time spent in ThreadNative::SpinWait is less and the test runs faster.

The changes above are by design and the behavior seen here is also in line with expectations.

**Comment by kouvel** [comment] 2018-03-07 09:38
Affinity is/was not taken into account for spinning in most places in coreclr/corefx, only the logical processor count. It would probably only matter for when the process is affinitized to one CPU, but I'm not sure if that is a common scenario.

**Comment by kouvel** [comment] 2018-03-07 09:40
On my pre-Skylake machine the non-affinitized case seems to run about the same speed as before, if not slightly faster. Still I'm not sure this is an interesting test for validating the spin strategy used.

**Comment by stephentoub** [comment] 2018-03-07 13:31
> Affinity is/was not taken into account for spinning in most places in coreclr/corefx, only the logical processor count

Maybe we should consider doing that?  I realize affinity can change, but I would speculate that the most common uses of process affinity would be setting it once at the beginning of the process.  And if the whole process is affinitized to a single core, we should likely significantly dial back the amount of spinning done, if not remove remove it entirely.

**Comment by kouvel** [comment] 2018-03-07 19:49
That sounds reasonable to me, filed https://github.com/dotnet/coreclr/issues/16807

**Comment by AndyAyersMS** [comment] 2018-03-07 20:19
I think we understand what's going on and have opened the relevant issues, so I'm going to close this.

**Closed by AndyAyersMS** 2018-03-07 20:19 UTC
Labels: area-Benchmarks, tenet-performance
