### ISSUE TITLE
The type initializer threw AccessViolationException

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2433] opened 2015-12-20 18:42 UTC
For a debug win64 test job, an error message like this

```
Unhandled Exception: System.TypeInitializationException: 
The type initializer for <some type> threw an exception. ---> 
System.AccessViolationException: Attempted to read or write protected memory. 
This is often an indication that other memory is corrupt.
```

is given when the following tests fail:

```
JIT\Directed\intrinsic\interlocked\rva_rvastatic1\rva_rvastatic1.cmd
JIT\Directed\intrinsic\interlocked\rva_rvastatic2\rva_rvastatic2.cmd
JIT\Directed\intrinsic\interlocked\rva_rvastatic3\rva_rvastatic3.cmd
JIT\Directed\intrinsic\interlocked\rva_rvastatic4\rva_rvastatic4.cmd
JIT\Methodical\cctor\misc\global_il_d\global_il_d.cmd
JIT\Methodical\cctor\misc\global_il_r\global_il_r.cmd
```

**Comment by sejongoh** [comment] 2016-01-12 01:32
This issue looks a duplicate of #2451.

**Comment by sivarv** [comment] 2016-01-13 05:14
Marking it as test issue and moving to 'rtm' since this is a duplicate of #2451

**Comment by RussKeldorph** [comment] 2016-04-10 11:38
Updated #2451's file list.  Closing this one as dup.

**Closed by RussKeldorph** 2016-04-10 11:38 UTC
Labels: bug, CodeGen, Test-Issue
