### ISSUE TITLE
Zero allocation Span to Decimal?

### ISSUE THREAD

**Issue by mikernet** [dotnet/coreclr#26753] opened 2019-09-17 19:02 UTC
`Decimal` is the only data type that I need to perform allocations to serialize to/from `Span<T>`:

```c#
// allocates unnecessary array
int[] bits = { reader.ReadInt32(), reader.ReadInt32(), reader.ReadInt32(), reader.ReadInt32() };
value = new decimal(bits);
```
```c#
// allocates unnecessary array
int[] bits = decimal.GetBits(value);

writer.WriteInt32(bits[0]);
writer.WriteInt32(bits[1]);
writer.WriteInt32(bits[2]);
writer.WriteInt32(bits[3]);
```

I see that there is [this `ToDecimal(ReadOnlySpan<byte>)` method](https://github.com/dotnet/coreclr/blob/812f5b7bda9163ae848171d7db9e4a3691d55f06/src/System.Private.CoreLib/shared/System/Decimal.cs#L549) which would help but it is internal, as are the other interesting zero allocation methods :(

Is there really no method exposed for allocation free `decimal` serialization or am I just missing something?

**Comment by jkotas** [comment] 2019-09-17 19:51
Duplicate of https://github.com/dotnet/corefx/issues/35877

**Closed by jkotas** 2019-09-17 19:51 UTC
Labels: area-System.Memory
