### ISSUE TITLE
Assembly.GetTypes() will crash if referencing assembly is not found

### ISSUE THREAD

**Issue by bagzli** [dotnet/coreclr#14682] opened 2017-10-24 23:13 UTC
Please consider the following:

I have three dlls:

- Common.dll
- Error.dll
- Email.dll

Email.dll References Common.dll (1.0.0)
Error.dll References Common.dll (1.0.2)

For argument sake, we will say there are no code differences between these 2 versions. Also, the assembly version and assembly file version is 1.0.0.0 in both versions of Common.dll

The main project that calls both Email and Error dll has a function that loops through assemblies and gets its types for whatever the reason. The main project also will grab the latest dll of Common which is 1.0.2 and thus Error.dll will work.

Now if I call the following it will crash because it could not find Common.dll (1.0.0):
```
var assembly = AppDomain.CurrentDomain.Load("Email.dll")
assembly.GetTypes().Where(t => t.GetCustomAttributes(typeof(SomeAttribute), true).Any());
foreach (var entityType in entityTypes)
{
    //some logic
}
```

Is this a known issue? Is there a workaround for this?

**Comment by jkotas** [comment] 2017-10-25 03:29
Can you provide a project with a simple repro of the problem? You are most likely trying to load multiple copies of the same assembly into the default context - it does not work by design.

**Comment by bagzli** [comment] 2017-10-25 22:01
I'll try to find some time this weekend to make a sample repo.

**Comment by jkotas** [comment] 2017-12-02 05:34
No repro instructions - closing. Please reactive if it is still a problem.

**Closed by jkotas** 2017-12-02 05:34 UTC
Labels: area-AssemblyLoader, question
