### ISSUE TITLE
[x64] Test failed: JIT_Methodical._tailcall__il_reldeep_virt__il_reldeep_virt_._tailcall__il_reldeep_virt__il_reldeep_virt_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22342] opened 2019-02-01 01:27 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_centos7.1_r2r_jitforcerelocs_tst/171/

**Failed tests:**
`JIT_Methodical._tailcall__il_reldeep_virt__il_reldeep_virt_._tailcall__il_reldeep_virt__il_reldeep_virt_sh`

**Log:**
```
JIT_Methodical._tailcall__il_reldeep_virt__il_reldeep_virt_._tailcall__il_reldeep_virt__il_reldeep_virt_sh [FAIL]
        Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
           at JitTest.TestClass.Method1()
           at JitTest.TestClass.Method0()
           at JitTest.TestClass.Main()
        /mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/JIT/Methodical/tailcall/_il_reldeep_virt/_il_reldeep_virt.sh: line 244: 94280 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
        /n/nReturn code:      1/nRaw output file:      /mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/JIT/Methodical/Reports/JIT.Methodical/tailcall/_il_reldeep_virt/_il_reldeep_virt.output.txt/nRaw output:/nBEGIN EXECUTION
        in takeLock
        /mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root:/mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/JIT/Methodical/tailcall/_il_reldeep_virt/IL:/mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/JIT/Methodical/tailcall/_il_reldeep_virt /in _il_reldeep_virt.org /out _il_reldeep_virt.exe
        Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
        Copyright (c) Microsoft Corporation.  All rights reserved.
        
        Native image _il_reldeep_virt.exe generated successfully.
        in ReleaseLock
        in takeLock
        /mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun _il_reldeep_virt.exe
        in ReleaseLock
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/n> /mnt/resource/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_centos7.1_r2r_jitforcerelocs_tst/bin/tests/Linux.x64.Checked/JIT/Methodical/tailcall/_il_reldeep_virt/_il_reldeep_virt.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/resource/j/workspace/dotnet_coreclr/master/checked_centos7.1/bin/tests/Linux.x64.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs(124849,0): at JIT_Methodical._tailcall__il_reldeep_virt__il_reldeep_virt_._tailcall__il_reldeep_virt__il_reldeep_virt_sh()
```

**Comment by BruceForstall** [comment] 2019-02-06 02:12
Also fails on Ubuntu:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_r2r_jitforcerelocs_flow/236/

Maybe the commonality is Linux, x64, Checked, Ready2Run, with `COMPlus_ForceRelocs=1`

**Comment by BruceForstall** [comment] 2019-02-06 02:12
@sergiy-k Could you have someone look at this?

**Comment by sergiy-k** [comment] 2019-04-25 20:20
@BruceForstall, I assume this fails in the ReadyToRun config only, right? @fadimounir, could you please take a look?

**Comment by BruceForstall** [comment] 2019-04-26 21:15
> @BruceForstall, I assume this fails in the ReadyToRun config only, right?

Probably, although it's worth trying variations to verify this.

**Comment by fadimounir** [comment] 2019-06-17 18:31
@BruceForstall this is a JIT bug triggered with complus_forcerelocs=1. You can repro without R2R. I'm assigning it to you. I don't know if this repros on Windows.

The problem is with the following callstack:
`
        Child SP               IP Call Site
00007FFFFFFFD238 0000000EB84E47BB JitTest.TestClass.Method1()
00007FFFFFFFD240 0000000EB84E4654 JitTest.TestClass.Method0()
00007FFFFFFFD250 0000000EB84E4570 JitTest.TestClass.Main()
00007FFFFFFFD740 00007ffff612f993 [GCFrame: 00007fffffffd740]
00007FFFFFFFDFE8 00007ffff612f993 [GCFrame: 00007fffffffdfe8]
`
The disasm at Method1 is the following:

->  0xeb84e47bb: jmp    qword ptr [rip - 0x56d]

RIP = 0x0000000eb84e47bb

And here's the memory dump at rip-0x56d:
`
(lldb) me r/8xg 0x0000000eb84e47bb-0x56d
0xeb84e424e: 0xb848e0ff0000000e 0x0000002c4d4fbc30
0xeb84e425e: 0x000000000000e0ff 0x0000000000000000
0xeb84e426e: 0x0000000000000000 0x0000000000000000
0xeb84e427e: 0x0000000000000000 0x0000000000000000
`
Of course 0xb848e0ff0000000e is invalid and causes the AV.

I'm reassigning this bug to you for further investigations from the JIT side.

**Comment by BruceForstall** [comment] 2019-06-17 20:57
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment] 2019-06-18 00:43
I can repro (on Ubuntu x64), will debug:
```
andy@ANDYA16:~/bugs/22342$ ~/repos/coreclr/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun deep_virt.ni.exe
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at JitTest.TestClass.Method1()
   at JitTest.TestClass.Method0()
   at JitTest.TestClass.Main()
Aborted (core dumped)
```

**Comment by AndyAyersMS** [comment] 2019-06-18 01:13
`COMPlus_ForceRelocs` is something of an odd duck ... it forces the jit to jit every method twice. 

Reproing the failure requires tiered compilation to be enabled, and while the first jit request comes through at Tier0, the "redo" request (after the fake jump stub overflow failure that `COMPlus_ForceRelocs=1` causes) comes through as a normal (full opt) jit request. So I wonder if perhaps some part of the tiering mechanism is not properly cleaned up  once we back out of the first jit result.

**Comment by AndyAyersMS** [comment] 2019-06-18 22:00
Looked at this some more and think tiering is likely just an indirect contributor. `Method1` ends with a `jmp` to `Method2`, and when tiering is enabled, this jump is indirect through some address `p`. And  `ForceRelocs=1' ensures that `p` is too far from the jump instruction to fit into a 32 bit displacement.

So when both are enabled, the jit ends up asking to help reach `p`, and the runtime, and the runtime creates a jump stub at some near-enought address `q`, and the jit emits a jump indirect through `q`. But this doesn't work as `q` points at code, not data.

We don't see this problem for calls as the indirection is expanded earlier during lower, loading the value into a register and using register indirect for the call.

For jumps we defer this sort of processing until epilog codegen time.

**Comment by AndyAyersMS** [comment] 2019-06-19 08:38
FWIW this fails on windows x64 too (w/o R2R, just needs TC an force relocs). Same issue: we can't rely on a jump stub to get us to an out of range indirection cell.

**Closed** 2019-06-20 19:04 UTC
Labels: arch-x64, area-CodeGen, os-linux
