### ISSUE TITLE
Integration, corefx Linq Expression failure -- Linux

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#2315] opened 2015-12-11 21:54 UTC
Segmentation fault occurs in dynamic method created from corefx System.Linq.Expressions tests.

**Comment by stephentoub** [comment] 2015-12-11 22:02
Thanks. Can you share more details?  Which test is causing the failure?  Do you have a stack trace from the seg fault?  Etc.

**Comment by jashook** [comment] 2015-12-12 00:41
The two methods that fail are: CompileInterpretCrossCheck_Call and CompileInterpretCrossCheck_MemberAccess.  These are both apart of System.Linq.Expressions.Test.

The exact result of the failure is a segmentation fault to do a null reference check. The test will fail with a thrown null reference exception. These tests pass without the integration, however, fail with the new code generation.

Will include a managed stack trace soon. Note that these tests will only repro these failures on Linux.

**Comment by jashook** [comment] 2015-12-12 01:09
Managed Stack Trace:

00007FFFE950A200 00007FFF7CD1C715 DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure)
00007FFFE950A210 00007FFF7D0F38F7 Tests.Expressions.InterpreterTests.Verify(System.Linq.Expressions.Expression)
00007FFFE950A330 00007FFF7CCFDA57 Tests.Expressions.InterpreterTests.CompileInterpretCrossCheck_MemberAccess()
00007FFFE950AC18 00007FFFF5FAC97F [DebuggerU2MCatchHandlerFrame: 00007fffe950ac18] 
00007FFFE950B468 00007FFFF5FAC97F [HelperMethodFrame_PROTECTOBJ: 00007fffe950b468] System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
00007FFFE950B5F0 00007FFF7C540D35 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
00007FFFE950B640 00007FFF7C550F59 System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
00007FFFE950B670 00007FFF7CCFD390 Xunit.Sdk.TestInvoker`1[[System.__Canon, mscorlib]].CallTestMethod(System.Object)
00007FFFE950B680 00007FFF7CCFD0E0 Xunit.Sdk.TestInvoker`1+<>c__DisplayClass46_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, mscorlib]].MoveNext()
00007FFFE950B6E0 00007FFF7CCFCA7A DomainBoundILStubClass.IL_STUB_InstantiatingStub()
00007FFFE950B6F0 00007FFF7CCFC9C8 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Xunit.Sdk.TestInvoker`1+<>c__DisplayClass46_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, mscorlib]], xunit.execution.dotnet]](<<InvokeTestMethodAsync>b__1>d<System.__Canon> ByRef)
00007FFFE950B740 00007FFF7CCFC8FD Xunit.Sdk.TestInvoker`1+<>c__DisplayClass46_1[[System.__Canon, mscorlib]].<InvokeTestMethodAsync>b__1()
00007FFFE950B7D0 00007FFF7CCFC287 Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4.MoveNext()

**Comment by LLITCHEV** [comment] 2015-12-17 04:31
@VSadov As we discussed this seems to be a bug in the interpreter. It seems the error is due to the fact that in case of a Call with a null target the interpreter still makes a call in the reflection call logic, which throws a System.Reflection.TargetException.
In this particular case the error is:
   Tests.Expressions.InterpreterTests.CompileInterpretCrossCheck_MemberAccess [FAIL]
      System.Exception : Error for expression '(.Default(Tests.Expressions.Members)).H':
      
      Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: typeof(System.Reflection.TargetException)
      Actual:   typeof(System.NullReferenceException)
The code that causes this is in corefx\src\System.Linq.Expressions\tests\Catalog\ExpressionCatalog.MemberAccess.cs
Around line 38 - yield return Expression.MakeMemberAccess(Expression.Default(typeof(Members)), member);

The default value for class Members is null, so a NullReferenceException is expected and thrown by the jitted code. The interpreter however makes a call in the reflection engine and gets System.Reflection.TargetException: Non-static method requires a target - this is gotten when the target of an instance call is null. As we discussed the interpreter in case of a null target instance call is not supposed to call into the reflection engine, but to throw NullReferenceException. It turns out that there were fixes made to do that and this is another case of the problem - either a place in the code that has not been fixed to throw NullReferenceException or a bad caching state.

**Comment by VSadov** [comment] 2015-12-17 22:17
@LLITCHEV - well, if it is a Linux only failure, then it cannot be in interpreter, since interpreter does not do anything conditionally on platform.
There is still a possibility of running old binary without this fixed. Can that be confirmed?

**Comment by VSadov** [comment] 2015-12-17 22:36
In current sources InvokeInstance helper contains the following sequence:
```C#
            try
            {
                NullCheck(instance);
                return _target.Invoke(instance, args);
            }
            catch (TargetInvocationException e)
            {
                throw ExceptionHelpers.UpdateForRethrow(e.InnerException);
            }
```

where NullCheck is:

```C#
        // throws NRE when o is null
        protected static void NullCheck(object o)
        {
            if (o == null)
            {
                o.GetType();
            }
        }
```

If the System.Linq.Expression that you run with, has the above code, then it could be an issue with the JIT.

@jashook @LLITCHEV  - could someone take a look at the code that is running?
Is there a NullCheck before   calling into MethodBase.Invoke  ?

**Comment by LLITCHEV** [comment] 2015-12-18 18:16
I tracked the issue down (there are actually two things).
1. The earlyprop optimizer (new code that came with the FI/RI) there was no proper handling of null values. It was fixed at some point and not included in the FI/RI. @BruceForstall did mop FI earlier this week and that fixed the CompileInterpretCrossCheck_MemberAccess failure.
2. The CompileInterpretCrossCheck_Call failure is due to adding functionality (again new functionality) to covert some special calls to intrinsics for the purposes of the optimizers, so they can be better optimized. Such call is object.GetType(). The interpreter's NullCheck method calls exactly that - o.GetType() to verify if the target for a non static call is null. The new intrinsic was marked as no-side-effect and the result is not used the optimizer decided to eliminate the call altogether.

I am in the process of testing a fix which I will PR shortly.

**Comment by LLITCHEV** [comment] 2016-01-04 04:29
This should have been fixed with PR https://github.com/dotnet/coreclr/pull/2461

**Comment by LLITCHEV** [comment] 2016-01-04 04:30
@jashook Could you please reenable the disabled Linq.Expressions tests. Thanks!

**Comment by jashook** [comment] 2016-01-04 15:40
PR out with corefx https://github.com/dotnet/corefx/pull/5166

**Closed** 2016-01-04 21:32 UTC
Labels: bug, CodeGen
