### ISSUE TITLE
Environment.ProcessorCount returns 1 instead of correct value on Linux

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#24686] opened 2019-05-21 15:40 UTC
@JMan7777 reported this in https://github.com/dotnet/core/issues/2714.

> At first Environment.ProcessorCount returns the correct value, and then later it returns 1.

@JMan7777 provided a test project to reproduce the issue: https://github.com/dotnet/core/files/3193555/Test.zip. The issue was reported when running on Docker, but it also occurs on plain Linux.

stracing the application shows `sched_getaffinity` returns a single cpu when calling `Environment.ProcessorCount`. This is happens after some threads have set their affinity to a specific processor.

It seems that either `sched_getaffinity(0` is returning the value for the current thread (and not the process), or we are changing the affinity of the process pid (main thread). 

This probably regressed in https://github.com/dotnet/coreclr/pull/23824 (v3.0.0-preview5-27622-75).

CC @janvorli @karelz

**Comment by janvorli** [comment] 2019-05-21 16:07
This is really strange. We only set affinity for GC threads and no user code should ever run on those. So even if the `sched_getaffinity(0, ...)` was returning affinity of the current thread, it should still not be influenced. And we set the affinity using `pthread_setaffinity_np(pthread_self(), ...)`, so again, we should not be accidentally setting it for other threads.
Let me look into it.

**Comment by janvorli** [comment] 2019-05-22 01:49
The issue is caused by a bug that will be fixed by the pending #24706.

**Comment by janvorli** [comment] 2019-05-22 03:35
The #24706 is in, the issue should be fixed

**Closed by janvorli** 2019-05-22 03:35 UTC
Labels: area-PAL

**Comment by JMan7777** [comment] 2019-05-22 03:56
@janvorli 
Thx, will it be part of .net core 3.0 preview 6 ?

**Comment by tmds** [comment] 2019-05-22 07:11
> Thx, will it be part of .net core 3.0 preview 6 ?

Probably, or preview 7 if it isn't in 6.

@janvorli looking at the fix, it is not clear how it was causing the issue. If the affinity of the current thread (a GC thread) was changed, how does that affect the affinity of the process?

**Comment by janvorli** [comment] 2019-05-22 14:50
@tmds actually, it seems that the sched_setaffinity with PID 0 really returns the affinity of the current thread. I know that sometimes the linux doc mixes threads and processes due to the historical reasons and it seems this is one of the places where the doc says "current process" but it really means current thread.
I will create another PR to change that back to using current process id, but it should not cause trouble with my change anymore, as we now really don't call the sched_setaffinity for other than GC threads and those ones don't execute user code. Before my fix, GC was calling the sched_setaffinity for rebalancing user threads, which I wasn't aware of.

**Comment by janvorli** [comment] 2019-05-22 15:09
I think it should be in Preview 6.

**Comment by tmds** [comment] 2019-05-28 11:47
> I will create another PR to change that back to using current process id

I've created https://github.com/dotnet/coreclr/pull/24802 for this.

> Before my fix, GC was calling the sched_setaffinity for rebalancing user threads, which I wasn't aware of.

Aha. Thank you for clarifying.
