### ISSUE TITLE
System.OutOfMemoryException - Windows Service Stops!

### ISSUE THREAD

**Issue by kudlatiger** [dotnet/coreclr#23832] opened 2019-04-09 09:18 UTC
**Application Error:**
```
Faulting application name: MyService.WindowsService.exe, version: 1.0.19092.2, time stamp: 0x5ca328e2
Faulting module name: clrjit.dll, version: 4.7.3260.0, time stamp: 0x5bb7bb2d
Exception code: 0xc0000005
Fault offset: 0x00004a00
Faulting process id: 0x1c8c
Faulting application start time: 0x01d4ee42fa584c7d
Faulting application path: C:\MyService\WindowsService\1.0.19092.2_1\WindowsService.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
Report Id: a4f89c01-ef37-41f5-abdf-d2c8c43d72d1
Faulting package full name: 
```

**.Net Runtime:**
```
Application: MyService.WindowsService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Threading.Monitor.ObjPulseAll(System.Object)
   at System.Threading.Monitor.PulseAll(System.Object)
   at Serilog.Sinks.PeriodicBatching.PortableTimer+<OnTick>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Application Error:**
```
Faulting application name: MyService.WindowsService.exe, version: 1.0.19092.2, time stamp: 0x5ca328e2
Faulting module name: clrjit.dll, version: 4.7.3260.0, time stamp: 0x5bb7bb2d
Exception code: 0xc0000005
Fault offset: 0x00004a00
Faulting process id: 0x15e8
Faulting application start time: 0x01d4edcca1fc92f8
Faulting application path: C:\Service\WindowsService\1.0.19092.2_1\MyService.WindowsService.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
Report Id: b4f4f164-bdbd-4ed8-a076-b27fbda45927
Faulting package full name:
``` 

**.Net Runtime:**
```
Application: MyService.WindowsService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
```

**Comment by AndyAyersMS** [comment] 2019-04-09 18:43
@kudlatiger this looks like an issue with .Net Framework, and this repo is for .Net Core. While they are similar they are not the same.

Per the readme for [dotnet/core](https://github.com/dotnet/core) can you report this via the [VS Developer Community Portal](https://developercommunity.visualstudio.com/)?

Also when you do that, we'll need more details to help figure things out:
* is this a regression, and if so, what has changed since this last worked?
* can you provide a dump file, stack trace, or similar?

**Comment by AndyAyersMS** [comment] 2019-05-20 15:53
@kudlatiger any update on this?

**Comment by AndyAyersMS** [comment] 2019-06-20 18:16
@kudlatiger I'm going to close this one. Please open an issue on the community portal if you can.

**Closed by AndyAyersMS** 2019-06-20 18:16 UTC
