### ISSUE TITLE
Can't built on Ubuntu 14.04 

### ISSUE THREAD

**Issue by xplicit** [dotnet/coreclr#33] opened 2015-02-03 21:05 UTC
ubuntu 14.04 64bit

    cmake --version
    cmake version 2.8.12.2

    ./build.sh

    Executing make
    Linking CXX static library libCoreClrPal.a
    Error running link command: No such file or directory
    make[2]: *** [src/pal/src/libCoreClrPal.a] Error 2
    make[1]: *** [src/pal/src/CMakeFiles/CoreClrPal.dir/all] Error 2
    make: *** [all] Error 2
    Failed to build coreclr components.

On the file system I see directory `binaries/CMake/src/pal/src/CMakeFiles/CoreClrPal.dir`, but don't see the file `all` inside it.

**Comment by AlexGhiondea** [comment] 2015-02-03 21:08
@mmitche - could you take a look?

**Comment by SirCmpwn** [comment] 2015-02-03 21:17
I am able to reproduce this on Arch Linux. The last few lines of the build are:

    Building ASM object src/vm/wks/CMakeFiles/cee_wks.dir/__/amd64/theprestubamd64.S.o
    clang: warning: argument unused during compilation: '-nostdinc++'
    clang: warning: argument unused during compilation: '-nostdinc++'
    [ 20%] Building ASM object src/vm/wks/CMakeFiles/cee_wks.dir/__/amd64/virtualcallstubamd64.S.o
    clang: warning: argument unused during compilation: '-nostdinc++'
    Linking CXX static library libcee_wks.a
    Error running link command: No such file or directory
    src/vm/wks/CMakeFiles/cee_wks.dir/build.make:5596: recipe for target 'src/vm/wks/libcee_wks.a' failed
    make[2]: *** [src/vm/wks/libcee_wks.a] Error 2
    CMakeFiles/Makefile2:56373: recipe for target 'src/vm/wks/CMakeFiles/cee_wks.dir/all' failed
    make[1]: *** [src/vm/wks/CMakeFiles/cee_wks.dir/all] Error 2
    Makefile:107: recipe for target 'all' failed
    make: *** [all] Error 2
    Failed to build coreclr components.

**Comment by lukehoban** [comment] 2015-02-03 21:21
I ran into the same problem, running `build.sh VERBOSE=1` showed that the problem was with `CMAKE_AR` not being set correctly.

```
Linking CXX static library libCoreClrPal.a
cd /home/lukeh/coreclr2/binaries/CMake/src/pal/src && /usr/bin/cmake -P CMakeFiles/CoreClrPal.dir/cmake_clean_target.cmake
cd /home/lukeh/coreclr2/binaries/CMake/src/pal/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/CoreClrPal.dir/link.txt --verbose=1
CMAKE_AR-NOTFOUND cr libCoreClrPal.a  CMakeFiles/CoreClrPal.dir/arch/i386/context.cpp.o CMakeFiles/CoreClrPal.dir/arch/i386/processor.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/file.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/filecrt.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/finite.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/lstr.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/malloc.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/mbstring.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/misc.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/misctls.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/path.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/printf.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/printfcpp.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/silent_printf.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/string.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/stringtls.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/thread.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/wchar.cpp.o CMakeFiles/CoreClrPal.dir/cruntime/wchartls.cpp.o CMakeFiles/CoreClrPal.dir/debug/debug.cpp.o CMakeFiles/CoreClrPal.dir/exception/console.cpp.o CMakeFiles/CoreClrPal.dir/exception/seh.cpp.o CMakeFiles/CoreClrPal.dir/exception/signal.cpp.o CMakeFiles/CoreClrPal.dir/file/directory.cpp.o CMakeFiles/CoreClrPal.dir/file/disk.cpp.o CMakeFiles/CoreClrPal.dir/file/file.cpp.o CMakeFiles/CoreClrPal.dir/file/filetime.cpp.o CMakeFiles/CoreClrPal.dir/file/find.cpp.o CMakeFiles/CoreClrPal.dir/file/path.cpp.o CMakeFiles/CoreClrPal.dir/file/shmfilelockmgr.cpp.o CMakeFiles/CoreClrPal.dir/handlemgr/handleapi.cpp.o CMakeFiles/CoreClrPal.dir/handlemgr/handlemgr.cpp.o CMakeFiles/CoreClrPal.dir/init/pal.cpp.o CMakeFiles/CoreClrPal.dir/init/sxs.cpp.o CMakeFiles/CoreClrPal.dir/loader/module.cpp.o CMakeFiles/CoreClrPal.dir/loader/modulename.cpp.o CMakeFiles/CoreClrPal.dir/locale/unicode.cpp.o CMakeFiles/CoreClrPal.dir/locale/unicode_data.cpp.o CMakeFiles/CoreClrPal.dir/locale/utf8.cpp.o CMakeFiles/CoreClrPal.dir/map/common.cpp.o CMakeFiles/CoreClrPal.dir/map/map.cpp.o CMakeFiles/CoreClrPal.dir/map/virtual.cpp.o CMakeFiles/CoreClrPal.dir/memory/heap.cpp.o CMakeFiles/CoreClrPal.dir/memory/local.cpp.o CMakeFiles/CoreClrPal.dir/misc/dbgmsg.cpp.o CMakeFiles/CoreClrPal.dir/misc/environ.cpp.o CMakeFiles/CoreClrPal.dir/misc/error.cpp.o CMakeFiles/CoreClrPal.dir/misc/fmtmessage.cpp.o CMakeFiles/CoreClrPal.dir/misc/interlock.cpp.o CMakeFiles/CoreClrPal.dir/misc/miscpalapi.cpp.o CMakeFiles/CoreClrPal.dir/misc/strutil.cpp.o CMakeFiles/CoreClrPal.dir/misc/sysinfo.cpp.o CMakeFiles/CoreClrPal.dir/misc/time.cpp.o CMakeFiles/CoreClrPal.dir/misc/utils.cpp.o CMakeFiles/CoreClrPal.dir/misc/version.cpp.o CMakeFiles/CoreClrPal.dir/objmgr/palobjbase.cpp.o CMakeFiles/CoreClrPal.dir/objmgr/shmobject.cpp.o CMakeFiles/CoreClrPal.dir/objmgr/shmobjectmanager.cpp.o CMakeFiles/CoreClrPal.dir/safecrt/makepath_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/memcpy_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/memmove_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/mbusafecrt.c.o CMakeFiles/CoreClrPal.dir/safecrt/safecrt_input_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/safecrt_output_l.c.o CMakeFiles/CoreClrPal.dir/safecrt/safecrt_output_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/safecrt_winput_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/safecrt_woutput_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/splitpath_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/sprintf.c.o CMakeFiles/CoreClrPal.dir/safecrt/sscanf.c.o CMakeFiles/CoreClrPal.dir/safecrt/strcat_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/strcpy_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/strlen_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/strncat_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/strncpy_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/strtok_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/swprintf.c.o CMakeFiles/CoreClrPal.dir/safecrt/vsprintf.c.o CMakeFiles/CoreClrPal.dir/safecrt/vswprint.c.o CMakeFiles/CoreClrPal.dir/safecrt/wcscat_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/wcscpy_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/wcslen_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/wcsncat_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/wcsncpy_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/wcstok_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/wmakepath_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/wsplitpath_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/xtoa_s.c.o CMakeFiles/CoreClrPal.dir/safecrt/xtow_s.c.o CMakeFiles/CoreClrPal.dir/shmemory/shmemory.cpp.o CMakeFiles/CoreClrPal.dir/sync/cs.cpp.o CMakeFiles/CoreClrPal.dir/synchobj/event.cpp.o CMakeFiles/CoreClrPal.dir/synchobj/semaphore.cpp.o CMakeFiles/CoreClrPal.dir/synchobj/mutex.cpp.o CMakeFiles/CoreClrPal.dir/synchmgr/synchcontrollers.cpp.o CMakeFiles/CoreClrPal.dir/synchmgr/synchmanager.cpp.o CMakeFiles/CoreClrPal.dir/synchmgr/wait.cpp.o CMakeFiles/CoreClrPal.dir/thread/process.cpp.o CMakeFiles/CoreClrPal.dir/thread/thread.cpp.o CMakeFiles/CoreClrPal.dir/thread/threadsusp.cpp.o CMakeFiles/CoreClrPal.dir/thread/tls.cpp.o
Error running link command: No such file or directory
make[2]: *** [src/pal/src/libCoreClrPal.a] Error 2
```

I was able to work around this by patching `binaries/CMake/CMakeFiles/2.8.12.2/CMakeCXXCompiler.cmake` to set CMAKE_AR to `/usr/bin/llvm-ar`, but not sure what the correct fix is for this.

**Comment by gkhanna79** [comment] 2015-02-03 21:27
Hi xplicit and SirCmpwn, 

Thank you for reporting this issue. We will look into this as we continue to bring up our Linux implementation that will have full fidelity build and validation support, including having identified such platform version specific issues and addressing them. 

Currently, we are building the product and infrastructure against a specific Ubuntu build where we have not run into this problem, so its great you brought it to our notice :)

@janvorli - FYI.

**Comment by lukehoban** [comment] 2015-02-03 21:28
@gkhanna79 - Which Ubuntu build are you testing on currently?

**Comment by SirCmpwn** [comment] 2015-02-03 21:30
I was able to fix this problem properly. I shall submit a pull request shortly.

**Comment by LouisStAmour** [comment] 2015-02-03 21:31
Good to see a potential fix. My suggestion would have been: does it work if `ar` is on your `PATH`?

**Comment by SirCmpwn** [comment] 2015-02-03 21:32
No, both `ar` and `llvm-ar` are in my `PATH` to no avail.

**Comment by xplicit** [comment] 2015-02-03 21:40
@lukehoban thanks for pointing that out, I've workarounded it by installing cmake 3.1.1 from ppa on my ubuntu 14.04

   apt-add-repository ppa:george-edison55/cmake-3.x trusty main -y
   apt-get update -qq
   apt-get install cmake

**Comment by SirCmpwn** [comment] 2015-02-03 21:41
For what it's worth, I'm running cmake 3.1.1 here.

**Comment by xplicit** [comment] 2015-02-03 21:42
@gkhanna79 which ubuntu version do you use?

**Comment by janvorli** [comment] 2015-02-03 21:43
We used to have the problem with the llvm-ar not being found by the cmake at the beginning, but it was mitigated by adding the -D_CMAKE_TOOLCHAIN_SUFFIX=-3.5 option to the cmake command line. 
The problem was that there was no llvm-ar, but only llvm-ar-3.5 installed after we've installed LLVM package on the Ubuntu 14.04 that we use for our development.
Btw, are you using the gen-buildsys-clang.sh to run cmake?

**Comment by xyziemba** [comment] 2015-02-03 21:46
@SirCmpwn What llvm version and clang version are getting picked up when you build? I can repro this with llvm/clang 3.4, but it appears resolved in 3.5.

@janvorli @gkhanna79 @jkotas What llvm/clang version(s) are supported?

**Comment by SirCmpwn** [comment] 2015-02-03 21:47
sircmpwn@makase ~> clang --version
    clang version 3.5.1 (tags/RELEASE_351/final)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    sircmpwn@makase ~> llvm-ar --version
    LLVM (http://llvm.org/):
      LLVM version 3.5.1
      Optimized build.
      Built Jan 14 2015 (03:18:15).
      Default target: x86_64-unknown-linux-gnu
      Host CPU: core-avx2
    sircmpwn@makase ~> cmake --version
    cmake version 3.1.1

    CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by janvorli** [comment] 2015-02-03 21:49
@xyziemba LLVM / clang 3.5 are currently the only supported one

**Closed** 2015-02-03 23:19 UTC

**Comment by xplicit** [comment] 2015-02-03 23:36
Just FYI. I was able to compile without errors before the patch using this commands on fresh Ubuntu 14.04, but there were not binaries in Product directory.

    sudo apt-get install git cmake clang-3.5 make llvm-3.5 gcc
    git clone https://github.com/dotnet/coreclr
    cd coreclr
    ./build.sh

**Comment by SirCmpwn** [comment] 2015-02-03 23:40
I encountered the same issue and went searching for them. I found corerun at `./binaries/CMake/src/coreclr/hosts/unixcorerun/corerun`, but running it with a simple example gave:

    sircmpwn@makase ~/s/coreclr master> cat test.cs
    class Program
    {
        static void Main()
        {
            System.Console.WriteLine("Hello world!");
        }
    }
    sircmpwn@makase ~/s/coreclr master> mcs test.cs
    sircmpwn@makase ~/s/coreclr master> mono test.exe
    Hello world!
    sircmpwn@makase ~/s/coreclr master> ./binaries/CMake/src/coreclr/hosts/unixcorerun/corerun -c binaries/CMake/src/dlls/mscoree/coreclr/ test.exe
    dlopen failed to open the libcoreclr.so with error /home/sircmpwn/sources/coreclr/binaries/CMake/src/dlls/mscoree/coreclr/libcoreclr.so: undefined symbol: CHAIN_SUCCESS_COUNTER

At this point I presumed I'd just run into expected bugs and figured I'd investigate more later.

**Comment by shahid-pk** [comment] 2015-02-04 08:22
@SirCmpwn 

I went a little further i copied, corerun , libcoreclr.so , libmscordaccore.so to a directery than compiled test.cs to test.exe using mcs and issued this
**./corerun -c ./ test.exe**
I got this error
**ExecuteAssembly failed - status: 0x80004005**
