### ISSUE TITLE
Profiler doesn't receive ThreadCreated/ThreadAssignedToOSThread callbacks for finalizer thread in .NET Standard 2.0

### ISSUE THREAD

**Issue by ww898** [dotnet/coreclr#13499] opened 2017-08-21 08:57 UTC
Under .NET 4.7 I got `ThreadCreated`/`ThreadAssignedToOSThread` notification about two threads before `Enter3` was called: main and finalizer. However, under .NET Standard 2.0 I got only one thread notification: about main thread. So, when `Enter3` called the finalizer thread TLS wasn't properly initialized.

My sample:
```
using System;
using System.IO;

namespace Sample
{
    class Program
    {
        static void Main(string[] args)
        {
            for (var n = 64; n-- > 0;)
                File.OpenRead("<path to existing file>");
            Console.WriteLine("I'm working...");
            for (var n = 4; n-- > 0;)
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }
        }
    }
}

```
I execute the repro sample with following flags set:
`COR_PRF_MONITOR_THREADS`
`COR_PRF_MONITOR_MODULE_LOADS`
`COR_PRF_USE_PROFILE_IMAGES`
`COR_PRF_MONITOR_SUSPENDS`
`COR_PRF_MONITOR_ENTERLEAVE`
`COR_PRF_MONITOR_EXCEPTIONS`
`COR_PRF_MONITOR_CODE_TRANSITIONS`

Environment variables:
 `COMPlus_ReadyToRun=0`

Profiler log:
```
...
00004504 1 0000020C49286D70 BPProf::ThreadCreated tid=0000020C49286D70
00004504 1 0000020C49286D70 BPProf::ThreadAssignedToOSThread tid=0000020C49286D70 ostid=00004504
; got the Enter3 call from finalizer thread here
```
**No `ThreadCreated`/`ThreadAssignedToOSThread` notification for thread 0x1628!**

State on got the `Enter3` call from finalizer thread:
```
0:004> .loadby sos coreclr
0:004> !threads
ThreadCount:      2
UnstartedThread:  0
BackgroundThread: 1
PendingThread:    0
DeadThread:       0
Hosted Runtime:   no
                                                                                                        Lock  
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   4    1 1628 0000020c45f5a780    21220 Cooperative 0000000000000000:0000000000000000 0000020c45f55da0 0     Ukn (Finalizer) 
   0    2 4504 0000020c49286d70    20020 Preemptive  0000000000000000:0000000000000000 0000020c45f55da0 0     Ukn 
0:004> !dumpstack
OS Thread Id: 0x1628 (4)
Current frame: JetBrains_Profiler_Windows_Core!BaseThread::GetCSE + 0xb [c:\work\dotnet-products\profiler\kernel\windows\native\solution\core\src\profilers\basethread.h:48]
Child-SP         RetAddr          Caller, Callee
000000b22a57f230 00007ffdc329740a JetBrains_Profiler_Windows_Core!PerformanceTracingProfiler::Rdtsc_fast_enter + 0x5a [c:\work\dotnet-products\profiler\kernel\windows\native\solution\core\src\bridges\host\info\meter_kind_ids.inc:3], calling JetBrains_Profiler_Windows_Core!BaseThread::GetCSE [c:\work\dotnet-products\profiler\kernel\windows\native\solution\core\src\profilers\basethread.h:46]
000000b22a57f390 00007ff7324c002e 00007ff7324c002e
000000b22a57f400 00007ffd72cd935d (MethodDesc 00007ffd72d49738 + 0x1d System.IO.FileStream.Finalize()), calling 00007ff7324c0000
000000b22a57f430 00007ffdd2762ca6 coreclr!FastCallFinalizeWorker + 0x6
000000b22a57f460 00007ffdd263e228 coreclr!MethodTable::CallFinalizer + 0x94, calling coreclr!ETW::GCLog::SendFinalizeObjectEvent + 0x78
000000b22a57f4b0 00007ffdd263e17c coreclr!CallFinalizer + 0x48, calling coreclr!MethodTable::CallFinalizer
000000b22a57f4f0 00007ffdd263e0e8 coreclr!FinalizerThread::DoOneFinalization + 0x9c, calling coreclr!CallFinalizer
000000b22a57f500 00007ffdd263d7b8 coreclr!CLREventBase::Wait + 0x34, calling KERNEL32!WaitForSingleObjectEx
000000b22a57f530 00007ffe15f648c6 KERNELBASE!SetThreadPriority + 0x66, calling ntdll!TpCaptureCaller
000000b22a57f560 00007ffdd263d6dd coreclr!CLREventBase::WaitEx + 0x45, calling coreclr!CLREventBase::Wait + 0x14
000000b22a57f570 00007ffdd26ad5a6 coreclr!GCCoop::GCCoop + 0xe, calling coreclr!GetThread
000000b22a57f580 00007ffdd266c41f coreclr!WKS::CFinalize::GetNextFinalizableObject + 0x33, calling coreclr!WKS::CFinalize::IsSegEmpty
000000b22a57f5b0 00007ffdd263dfe9 coreclr!FinalizerThread::FinalizeAllObjects + 0x89, calling coreclr!FinalizerThread::DoOneFinalization
000000b22a57f5f0 00007ffdd263d8ca coreclr!FinalizerThread::FinalizerThreadWorker + 0xca, calling coreclr!FinalizerThread::FinalizeAllObjects
000000b22a57f650 00007ffdd26ac7eb coreclr!UnManagedPerAppDomainTPCount::UnManagedPerAppDomainTPCount + 0x2cb
000000b22a57f690 00007ffdd26ac706 coreclr!UnManagedPerAppDomainTPCount::UnManagedPerAppDomainTPCount + 0x1e6, calling coreclr!UnManagedPerAppDomainTPCount::UnManagedPerAppDomainTPCount + 0x288
000000b22a57f6d0 00007ffdd267b149 coreclr!EEHeapAllocInProcessHeap + 0x29, calling ntdll!RtlAllocateHeap
000000b22a57f720 00007ffdd26b6353 coreclr!Thread::SetDebugCantStop + 0x2b, calling coreclr!ClrFlsIncrementValue
000000b22a57f750 00007ffdd26d58f4 coreclr!ThreadSuspend::UnlockThreadStore + 0x50, calling coreclr!Thread::SetDebugCantStop
000000b22a57f780 00007ffdd263d9fc coreclr!ThreadStore::TransferStartedThread + 0x88, calling coreclr!ThreadStore::CheckForEEShutdown
000000b22a57f7c0 00007ffdd26b85d3 coreclr!Thread::HasStarted + 0x107, calling coreclr!CLRException::HandlerState::CleanupTry
000000b22a57f7d0 00007ffdd2748261 coreclr!ClrFlsIncrementValue + 0x29
000000b22a57f7f0 00007ffdd26ac618 coreclr!UnManagedPerAppDomainTPCount::UnManagedPerAppDomainTPCount + 0xf8, calling coreclr!UnManagedPerAppDomainTPCount::UnManagedPerAppDomainTPCount + 0x164
000000b22a57f800 00007ffdd26b6353 coreclr!Thread::SetDebugCantStop + 0x2b, calling coreclr!ClrFlsIncrementValue
000000b22a57f8a0 00007ffdd263cbec coreclr!FinalizerThread::FinalizerThreadStart + 0x9c, calling coreclr!UnManagedPerAppDomainTPCount::UnManagedPerAppDomainTPCount + 0x44
000000b22a57f900 00007ffdd2656b57 coreclr!operator delete + 0x33
000000b22a57f940 00007ffdd265f8eb coreclr!Thread::intermediateThreadProc + 0x8b
000000b22a57f9c0 00007ffdd265f8c6 coreclr!Thread::intermediateThreadProc + 0x66, calling coreclr!_chkstk
000000b22a57fa00 00007ffe17ab2774 KERNEL32!BaseThreadInitThunk + 0x14, calling ntdll!LdrpDispatchUserCallTarget
000000b22a57fa30 00007ffe19750d51 ntdll!RtlUserThreadStart + 0x21, calling ntdll!LdrpDispatchUserCallTarget
```

P.S. JetBrains issue with more WinDbg details: [DTRC-24895](https://youtrack.jetbrains.com/issue/DTRC-24895)

**Comment by jkotas** [comment] 2017-08-21 14:33
@davmason @noahfalk

**Comment by noahfalk** [comment] 2017-08-22 21:31
Thanks for the report @ww898, we'll investigate this and get back to you.

**Comment by sywhang** [comment] 2017-08-31 20:14
Hi @ww898, 
Could you please check out the latest master branch and see if this problem still exists? 
If so, please let us know, thanks.

**Comment by sywhang** [comment] 2017-09-10 03:42
Closing the issue as it appears to be resolved. If the problem seems to still persist, feel free to reopen.

**Comment by redknightlois** [comment] 2017-09-11 16:53
@jkotas any ETA on when this will be included in a 2.0 service release? Not being able to profile with Tracing for call counts is quite an issue for us.

**Comment by jkotas** [comment] 2017-09-11 17:19
Reactivating for porting the fix to .NET Core 2.0.x servicing.

**Comment by noahfalk** [comment] 2017-09-11 20:26
@redknightlois - I don't have objection to getting this in 2.0 servicing, but I wanted to confirm this is the issue that is blocking you from getting call counts and not some other issue that we should be looking at? This issue only affects thread create notifications whereas for call counts I'd expect you'd care about ELT or rejit to instrument individual call bodies.

**Comment by redknightlois** [comment] 2017-09-11 22:35
@noahfalk, dotTrace is a critical part of our perf suite because it allows us to do fine-tuning without the analysis overhead that WPA introduces; we only use WPA when scenario is too big for VTune and dotTrace is not enough to give us enough information. 

We are certainly not doing call-count profiling lately because of this and I witness more than a few ```dotTrace is broken yet again``` in our slack channel, so I suppose Jetbrains guys are not fond of the issue either. I was looking into very deep things last 2 weeks so I didn't care, when I finally did care I filed a bug for dotTrace and got redirected here :)

**Comment by redknightlois** [comment] 2017-09-11 22:45
@jkotas Probably it would be a good idea (if viable) to add a test to avoid a regression for this one.

**Comment by noahfalk** [comment] 2017-09-11 23:31
@redknightlois - ah I misunderstood. I incorrectly thought you also developed a diagnostics tool that used these APIs, but as I now understand it you are @ww898's customer. Thanks for the info, I'll coordinate with @sywhang to get this in the servicing branch. In the meantime the fix is in the development branch if you'd like to try it out. Although it seems reasonably likely that we fixed the bug as reported here, its always possible that the repro here doesn't cover everything necessary to make your end-to-end scenario work. If you try it out and find anything else that needs to be looked at we can coordinate with JetBrains to do so.

**Comment by sywhang** [comment] 2017-09-11 23:35
@noahfalk FYI I already made a PR to get this in the 2.0.0/release servicing branch and sent out request to get it approved earlier this morning.

**Closed** 2017-09-29 22:50 UTC
Labels: area-Diagnostics
