### ISSUE TITLE
Nested methods

### ISSUE THREAD

**Issue by RassulYunussov** [dotnet/coreclr#14446] opened 2017-10-12 08:26 UTC
I try to create a nested method inside of another nested method and get a strange error:
` error MSB6006: "/usr/local/share/dotnet/sdk/2.0.0/Roslyn/RunCsc.sh" exited with code 134.`

Here is my code:
```C#
static void QuickSort(int [] src)
    	{
			qs(0,src.Length-1);

			
			
    		void qs(int left,int right)
    		{
				int index = partition(left,right);
				if(index<right)
					qs(index,right);
				if(left<index-1)
					qs(left,index-1);
				void swap(ref int lv,ref int rv)
				{
					int temp = lv;
					lv = rv;
					rv = temp;
				}
				int partition(int ll, int rr)
				{

					int i = ll, j = rr;
					int pivot = src[(ll + rr) / 2];
					while (i <= j) 
					{
							while (src[i] < pivot)
								i++;
							while (src[j] > pivot)
								j--;
							if (i <= j) {
								swap(ref src[i++],ref src[j--]);
							}
					}
					return i;
				}	
    		}
    	}
```

**Comment by svick** [comment] 2017-10-12 11:27
This looks like duplicate of https://github.com/dotnet/roslyn/issues/19033, which is already fixed in Roslyn master.

Indeed, as expected for that issue, [your code throws `KeyNotFoundException` on the release version of Roslyn](https://sharplab.io/#v2:CYLg1APgAgzABFATHAwnA3gWAFBQIwBsCALHAIoCuAlgMYDWAygPYBOALgBRUB2bcA2gF04AZxY0AlDjgy4ASCzY5ygI4iOABgA0YmgDoAMgFNuAczYALALR4JAbhw5lcp8umzlUUmq684AGyMAMzYtHj4WKlMLNilsWXkFV2VwuB5gIwAPOABeOAAHAEN2KjYqJm4OQJCtSOjYhyVnKiDfDMyAHjqYuOdVdXSs2qiexr6WquC2DsHMm16+n2rQ2fmx5y9RAHdC/I4WYLS/fwA3WsPUlhOF5UU+uVS2IwBbfNyAk/XnU/err+Uru8nq9/gBfZIPPxFEplCq+Pj+fxaI4RFg3JLYCGQvhUd6I5EAK1+LH+2IKVBOTD4eV0/Cq/jgYDgLDRcAA9HBEIJSVsLFRAnAuHAOnkCRI4Fi7vc5Lz+UZBbSqMIOuTKbEsc0wGBScpZQKOLSCcIAHyqqnovoEqxWHUPIKC3EiuBijAa5QiHZ7A72xVawTnH3ifhWqyCexu8FNZyR+5QADsaTBLniHjkkYSaZwoKAA), but [compiles fine on latest Roslyn from master](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABAzAAmwCZ8BhfAbwFgAobARgDZCAWfARQFcBLAYwGsAygHsEMABTcAdjHwBtALr4oCXgEpa+LfgCQ1GjsMBHKOIAMSFbwB0AGThSA5jAAWAWnpqA3LVqGdfoaa2obYbCaSMvgANnAAZjBI0rII3I4uMBo02rp6gYbJ+NIocAAe+AC8+AAOEGLcMNzCUuKxCUip6Zk+Bv7ccZElpQA8nRlZ/samxWUdaeM9k/2t8TDDM6UeE5MRbYkbW4v+YcoA7hDV4gjxRVHRAG4dN4UI99uG+pM6hfBg1ZUxe5HfwPAGvYGGV4A37VCEAX3y3yitXqjWakVk0WiSFuKQQ7zyNERSNk3ABWJxACswQgISSatx7sJZFUrHJWtF8Oh8Ah8fgAPT4IgKOmnFzcWL4ST4YZVSlqfDEz5fHRiiVwKVs7hKYYMpmZYl9dDoOmGNWS8RsylKAB8euZBMmlLcblN3ziUrJsvw8sohsMUHOl2uHq1xoUT1DqjkzrcCm8/oRvX8Sa+2AA7EV4QFsiEdEmcvnaHCgA==).

**Closed** 2017-10-12 17:18 UTC
