### ISSUE TITLE
Free object immediately rather then using GC when object is null or goes out of scope

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/coreclr#4150] opened 2016-04-07 19:58 UTC
I wrote a simple program that allocated a large number of objects, put them in a container, uses them (never passed to another function), then sets them all to null. The container goes out of scope after the function exits.

Looking at perfmon I see the %Time in GC is very high. The working set grows quite larger. My conclusion is that all these objects are being garbage collected through the normal garbage collection path, even though it's clear, upon setting them to null that they can be freed immediately.

My suggestion is that the JIT compiler determine which objects can short-cut the GC process then destroy them immediately. This will significantly reduce the workload on the GC, improving performance and lower the memory utilization of nearly all programs.

**Comment by swgillespie** [comment] 2016-04-07 20:58
Thanks for the report! The topic of escape analysis in the JIT has been brought up before: see https://github.com/dotnet/coreclr/issues/1784 for some discussion on that. That particular discussion relates to allocating classes on the stack, but in general the compiler would have to prove that the pointers you put into your container don't escape and that the container itself doesn't escape in order for this to be sound. If you have a real-world workload that you think would benefit from this analysis, you could post it in that thread.

Closing as a duplicate of the linked issue - feel free to join the discussion there!

**Closed by swgillespie** 2016-04-07 20:58 UTC
