### ISSUE TITLE
Crossgen fails on System.Collections.Immutable -23604, blocking crossgen of Roslyn

### ISSUE THREAD

**Issue by agocke** [dotnet/coreclr#2256] opened 2015-12-07 19:11 UTC
```
$ ./crossgen.exe -Trusted_Platform_Assemblies "C:\Users\angocke\code\roslyn\Open\Binaries\Debug\csccore" System.Collections.Immutable.dll
Microsoft (R) CoreCLR Native Image Generator - Version 4.6.23603.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Error: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Error compiling System.Collections.Immutable.dll: Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
Error: compilation failed for "System.Collections.Immutable.dll" (0x80131621)
```

It looks like System.Collections.Immutable (1.1.38) does reference System.Runtime (4.0.0), but the version of System.Runtime for -23604 is 4.0.21.

/cc @janvorli

**Comment by janvorli** [comment] 2015-12-07 19:41
@stephentoub Do you have any idea what could be the problem here?

**Comment by stephentoub** [comment] 2015-12-07 22:39
@ellismg may know.  I remember at one point we were hitting similar issues sporadically in our corefx CI, and it IIRC had something to do with an infrastructure race around which version of System.Runtime.dll got deployed.

**Comment by ellismg** [comment] 2015-12-07 23:04
We were hitting an inverse problem, I think, which was we were deploying an older version of System.Runtime.dll (4.0.0.0) to places that wanted the newer (4.0.20.0) version.

I thought the run-time would allow the newer version of the assembly to satisfy the requirements for the  4.0.0.0 version.

I assume this is on Windows?  One possibility would be debug the issue.  Since I don't think it will log such that `fuslogvwr` can pick stuff up, I've had luck in the pass using windbg and breaking on C++ Exceptions.  I believe that the code will throw some C++ Exceptions before they get wrapped up into managed exceptions and re-thrown.

**Comment by agocke** [comment] 2015-12-09 22:27
Any updates on this? Crossgen issues block us from upgrading to newer runtime versions :)

**Comment by ellismg** [comment] 2015-12-09 22:31
Can you share out instructions on actually reproducing this (e.g. getting the collection of binaries together)?  I'm not sure how much progress can be made just looking at the log file, unfortunately.

**Comment by agocke** [comment] 2015-12-09 22:33
@ellismg Sure. Let me make a minimal repro using `dotnet cli`.

**Comment by sergiy-k** [comment] 2015-12-10 19:44
cc: @gkhanna79

**Comment by gkhanna79** [comment] 2015-12-10 19:49
There has not been any crossgen change to result in this break. Have we confirmed that TPA path contains System.Runtime.Dll for the intended (or higher) version?

Also, can you repro this on Windows?

CC @JohnChen0

**Comment by agocke** [comment] 2015-12-10 22:08
I've done some more experimentation and found the initial problem, I think -- I was using `-Trusted_Platform_Assemblies "C:\Users\angocke\code\roslyn\Open\Binaries\Debug\csccore"`

but it seems the correct line is `-Platform_Assemblies_Paths ...`

This seems to have solved the issue on Windows, currently testing on Linux. I'm still a bit confused about the difference between these options. What is it that they're supposed to do?

**Comment by gkhanna79** [comment] 2015-12-10 22:15
-TPA expects absolute path to the exact binary delimited by semi-colon.

-PAP expects semicolon delimited absolute folder paths, whose contents will be treated as TPA assemblies.

Sounds like you were specifiying the folder with the wrong (-TPA) option.

**Comment by agocke** [comment] 2015-12-10 22:49
But the difference in treatment of the assemblies is identical?

This seems confusing to me, since both things are TPA. Should the options be called something like Trusted_Platform_Assemblies and Trusted_Platform_Path?

Also, the PAP option specifies:

```
Platform_Assemblies_Paths
                         - List of paths containing target platform assemblies
```

Which only mentions "platform" assemblies. Shouldn't it say Trusted Platform or similar?

**Comment by agocke** [comment] 2015-12-10 22:53
Also, is there documentation for what a Trusted Platform Assembly is? Sorry, I'm very clueless on this topic. :)

**Comment by gkhanna79** [comment] 2015-12-10 22:53
Agreed that the naming is not the most obvious. That said, Platform_Assemblies_PAths are used to construct the TPA by the host. Thus, in the end, the treatment of the assemblies is the same.

As a side note, TPA is a runtime (CoreCLR) concept but P_A_P is simply host artifact.

**Comment by agocke** [comment] 2015-12-11 00:31
Looks like I'm still hitting an issue on Linux. I've created a repro here: https://github.com/agocke/Repro2256

You should be able to just clone it on an ubuntu machine, run

`dotnet restore`
`dotnet publish`

copy crossgen from the -23604 runtime into the bin/debug/dnxcore50/ubuntu.14.04-x64 directory and run crossgen. I get the following output:

```
$ ./crossgen -Platform_Assemblies_Paths $(pwd) System.Collections.Immutable.dll 
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Error compiling System.Collections.Immutable.dll: 0x80131F06
Error: compilation failed for "System.Collections.Immutable.dll" (0x80131f06)
```

**Comment by gkhanna79** [comment] 2015-12-11 16:01
@agocke To confirm, using the same steps, as above, you dont run into the issue on Windows?

**Comment by gkhanna79** [comment] 2015-12-11 16:02
Also, does the {pwd} above contain coreclr and mscorlib.ni.dll? if not, then they should be.

**Comment by agocke** [comment] 2015-12-11 18:35
@gkhanna79 Yes, this appears to pass on Windows. The output directory seems to contain coreclr (libcoreclr.so, libryujit.so, etc.) and mscorlib.dll.

**Comment by agocke** [comment] 2015-12-11 18:35
Note, no mscorlib.ni.dll, just mscorlib.dll.

**Comment by agocke** [comment] 2015-12-11 18:36
On Windows it does contain mscorlib.ni.dll, however.

**Comment by gkhanna79** [comment] 2015-12-11 22:20
@agocke to compile NI image for an assembly, NI image of mscorlib needs to be generated first. The failure hresult confirms this to be the cause as well:

> <HRESULT NumericValue="0x80131f06">
	<SymbolicName>NGEN_E_SYS_ASM_NI_MISSING</SymbolicName>
	<Message>"NGen cannot proceed because Mscorlib.dll does not have a native image"</Message>
	<Comment>Compiling any assembly other than mscorlib in the absence of mscorlib.ni.dll is not allowed.</Comment>
</HRESULT>

dotnet compile infrastructure does not carry mscorlib.ni.dll by default since mscorlib.dll is not built on Linux/Mac yet (it is copied from from  a Windows box). This will be fixed once MSBuild runs on Linux/Mac over CoreCLR.

That said, you can attempt to crossgen mscorlib manually on a Linux box but that will fail due to https://github.com/dotnet/coreclr/issues/2314

CC @ellismg

**Comment by agocke** [comment] 2015-12-11 22:30
So were we previously packaging the windows version in with the Linux runtime? Crossgen on Linux was working back to -23504 or so.

**Comment by gkhanna79** [comment] 2015-12-11 22:44
We always package the mscorlib for Linux, built on Windows, and attempt to crossgen it. Only when mscorlib.ni.dll is present can one generate NI for other binaries.

due to the associated issue (dating back 11/20), crossgen of mscorlib.dll broke. And since mscorlib.ni.dll didnt exist, there is inability to generate any other NI.

**Comment by agocke** [comment] 2015-12-11 23:48
@gkhanna79 Got it, then I guess this issue is a dup of #2314

**Comment by gkhanna79** [comment] 2016-01-08 16:22
@agocke I am closing this since #2314 is closed. Reopen if the issue persists.

**Closed** 2016-01-08 16:22 UTC
Labels: bug, CrossGen/NGEN
