### ISSUE TITLE
Test failure in r2rdump test

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19011] opened 2018-07-19 00:58 UTC
Test failure in x64 Checked Windows with `COMPlus_TailCallStress=1`.

I realize this is a new test. It may be it fails in more configurations, or it may be that I got (un)lucky to see a failed job that happened to pick up the new test, and that failed job was a particular JIT stress mode.

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_tailcallstress/470/consoleFull

```
15:51:17   BEGIN EXECUTION
15:51:17         ..\..\..\..\..\..\tests\src\readytorun\r2rdump\files\Windows_NT.x64.Checked\GcInfoTransitions.xml
15:51:17         ..\..\..\..\..\..\tests\src\readytorun\r2rdump\files\Windows_NT.x64.Checked\GenericFunctions.xml
15:51:17         ..\..\..\..\..\..\tests\src\readytorun\r2rdump\files\Windows_NT.x64.Checked\HelloWorld.xml
15:51:17         ..\..\..\..\..\..\tests\src\readytorun\r2rdump\files\Windows_NT.x64.Checked\MultipleRuntimeFunctions.xml
15:51:17                 4 file(s) copied.
15:51:17         Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
15:51:17         Copyright (c) Microsoft Corporation.  All rights reserved.
15:51:17         
15:51:17         Native image HelloWorld.ni.dll generated successfully.
15:51:17         Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
15:51:17         Copyright (c) Microsoft Corporation.  All rights reserved.
15:51:17         
15:51:17         Native image GcInfoTransitions.ni.dll generated successfully.
15:51:17         Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
15:51:17         Copyright (c) Microsoft Corporation.  All rights reserved.
15:51:17         
15:51:17         Native image GenericFunctions.ni.dll generated successfully.
15:51:17         Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
15:51:17         Copyright (c) Microsoft Corporation.  All rights reserved.
15:51:17         
15:51:17         Native image MultipleRuntimeFunctions.ni.dll generated successfully.
15:51:17          "D:\j\workspace\x64_checked_w---c5ba3367\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" R2RDumpTest.exe 
15:51:17         Starting the test
15:51:17         Expected:
15:51:17         	R2RDump.Sections.SectionREADYTORUN_SECTION_IMPORT_SECTIONS.Contents.R2RImportSection4120.Entries.ImportSectionEntry10262.SignatureSample.: FQQQAQICAn4=
15:51:17         Test:
15:51:17         	R2RDump.Sections.SectionREADYTORUN_SECTION_IMPORT_SECTIONS.Contents.R2RImportSection4120.Entries.ImportSectionEntry10262.SignatureSample.: FQQQAQICAmY=
15:51:17         
15:51:17         Expected:
15:51:17         	R2RDump.Sections.SectionREADYTORUN_SECTION_IMPORT_SECTIONS.Contents.ImportSectionEntry10262.SignatureSample.: FQQQAQICAn4=
15:51:17         Test:
15:51:17         	R2RDump.Sections.SectionREADYTORUN_SECTION_IMPORT_SECTIONS.Contents.ImportSectionEntry10262.SignatureSample.: FQQQAQICAmY=
15:51:17         
15:51:17         Expected:
15:51:17         	R2RDump.Sections.SectionREADYTORUN_SECTION_DEBUG_INFO.R2RSectionREADYTORUN_SECTION_DEBUG_INFO.Size.: 31
15:51:17         Test:
15:51:17         	R2RDump.Sections.SectionREADYTORUN_SECTION_DEBUG_INFO.R2RSectionREADYTORUN_SECTION_DEBUG_INFO.Size.: 26
15:51:17         
15:51:17         Expected:
15:51:17         	R2RDump.Sections.SectionREADYTORUN_SECTION_INLINING_INFO.R2RSectionREADYTORUN_SECTION_INLINING_INFO.RelativeVirtualAddress.: 10296
15:51:17         Test:
15:51:17         	R2RDump.Sections.SectionREADYTORUN_SECTION_INLINING_INFO.R2RSectionREADYTORUN_SECTION_INLINING_INFO.RelativeVirtualAddress.: 10292
15:51:17         
15:51:17         
15:51:17         
15:51:17         
15:51:17         
15:51:17         Expected: 100
15:51:17         Actual: -532462766
15:51:17         END EXECUTION - FAILED
15:51:17         FAILED
15:51:17         Test Harness Exitcode is : 1
15:51:17         
15:51:17   To run the test:
15:51:17   > set CORE_ROOT=D:\j\workspace\x64_checked_w---c5ba3367\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
15:51:17   > D:\j\workspace\x64_checked_w---c5ba3367\bin\tests\Windows_NT.x64.Checked\readytorun\r2rdump\R2RDumpTest\R2RDumpTest.cmd
15:51:17   
15:51:17         Expected: True
15:51:17         Actual:   False
15:51:17           D:\j\workspace\x64_checked_w---c5ba3367\bin\tests\Windows_NT.x64.Checked\TestWrappers\readytorun.r2rdump\readytorun.r2rdump.XUnitWrapper.cs(107,0): at readytorun_r2rdump._R2RDumpTest_R2RDumpTest_._R2RDumpTest_R2RDumpTest_cmd()
```

**Comment by nattress** [comment] 2018-07-19 01:20
@acmyu It looks like the test is sensitive to changes in the runtime affecting the output ready-to-run image layout. In this case, a stress mode affects the size of the jitted code throwing off what the test expects to see. We should test r2rdump against pre-made ready-to-run binaries so their layout is exactly the same each time. That way test failures should all be caused by changes to r2rdump itself.

**Comment by BruceForstall** [comment] 2018-07-19 07:32
@nattress It sounds from what you say that every JIT stress mode is likely to cause this test to fail. If that's so, I would suggest disabling the test ASAP until such time as all the stress legs can pass.

An alternative that *might* work, temporarily, is to mark the test `<JitOptimizationSensitive>true</JitOptimizationSensitive>`.

**Comment by BruceForstall** [comment] 2018-07-19 18:06
I added `<JitOptimizationSensitive>true</JitOptimizationSensitive>` to the test build project with https://github.com/dotnet/coreclr/pull/19032. Please remove this when the test is fixed to work for all stress configurations.

**Comment by zamont** [comment] 2018-08-08 21:09
Closing this issue as #19155 was merged.

**Closed by zamont** 2018-08-08 21:09 UTC
Labels: arch-x64, os-windows
