### ISSUE TITLE
Expression is evaluated as true where it should be false

### ISSUE THREAD

**Issue by anass-b** [dotnet/coreclr#8958] opened 2017-01-16 02:03 UTC
Hello,

As the screenshot shows bellow, the expression `myVariable == true` is evaluated as `true` where it should normally be `false`.

![screenshot](https://cloud.githubusercontent.com/assets/8070594/21968575/47389342-db96-11e6-94b8-3f16c869d7ca.png)

If `MyMethodAsync()` is not async and returns void, the expression evaluates to `false` as expected.

Is this a normal thing that can happen when using async/await ?

I tried to look around in places like stackoverflow.com to see if someone had the same issue like me or if this issue is known or normal, but I couldn't find anything, that's why I had a last resort to open an issue here.

Here is my dotnet version:
```
> dotnet --version
1.0.0-preview2-1-003177
```
My project uses `xproject/project.json`, and `net461` as a target Framework.

Thanks.

**Comment by mikedn** [comment] 2017-01-16 07:29
I tried a few things but I wasn't able to reproduce this. Perhaps you can put together a self-contained project that exhibits this problem?

Note that if this is indeed a bug then it could be a bug in either the JIT compiler or in the C# compiler (Roslyn).

**Comment by Ravenheart** [comment] 2017-01-16 11:49
I've had this happen when the project is run in Release mode with the debugger attached. The actual code that is being run is correct, just stepping into it with the debugger visualizes wrong in VS.

**Comment by anass-b** [comment] 2017-01-16 22:53
@mikedn I would like to create a self-contained project that reproduces the issue, hope I can get some free time soon to do that.
@Ravenheart In my case it happens even in debug mode, and the content of the `if {}` block runs regardless of whether the debugger is attached or not.

**Comment by anass-b** [comment] 2017-01-16 23:53
@mikedn I could make a self-contained project that reproduces the issue.
Here is the line of code that matches the issue I mentioned: https://github.com/anass-b/ReproduceExpressionBug/blob/master/ReproduceExpressionBug/Library.cs#L27, you can step in with the debugger until that line to see the problem.

**Comment by anass-b** [comment] 2017-01-21 17:45
any updates on this issue ?

**Comment by mikedn** [comment] 2017-01-21 18:13
Sorry, I missed your previous post. I tried now your project and I see that the debugger steps into the if statement but the code isn't actually executed, that exception isn't actually thrown and test passes as expected. Is that what you are seeing?

**Comment by anass-b** [comment] 2017-01-21 18:17
That's true, my sample project can reproduce just the part where the debugger steps in to the wrong place, but the exception isn't executed. On the other side, in my real project, the exception is executed and the test fails. This is something I couldn't build a sample project that can reproduce it.

**Comment by jnm2** [comment] 2017-01-21 18:36
@anass-b Does this repro running VS in safe mode? I ask because this week I was using NCrunch to debug a test and I was stepping through `var x = Method();` and witnessing the fact that `x` did not end up set to the return value from `Method`. It turned out that NCrunch was modifying the IL in order to calculate the line-by-line coverage markers and was literally glitching in a way that changed the meaning of the program from what the source code said.

**Comment by mikedn** [comment] 2017-01-21 19:26
> On the other side, in my real project, the exception is executed and the test fails. This is something I couldn't build a sample project that can reproduce it.

Hmm, maybe there are different bugs.

In your repro I suspect that the problem is bad debugging information produced by the C# compiler. The IL of that `if` statement is:
```
L_008f: ldarg.0 
L_0090: ldfld bool ReproduceExpressionBug.Library/<MyMethod1Async>d__2::<shouldBeFalse>5__1
L_0095: stloc.s flag2
L_0097: ldloc.s flag2
L_0099: brfalse.s L_00a2
L_009b: nop 
L_009c: newobj instance void [mscorlib]System.Exception::.ctor()
L_00a1: throw 
L_00a2: leave.s L_00be
```
And the PDB seems to contain these sequence points (according to Pdb2Xml):
```xml
<entry offset="0x8f" startLine="27" startColumn="13" endLine="27" endColumn="39" document="2" />
<entry offset="0x97" hidden="true" document="2" />
<entry offset="0x9b" startLine="28" startColumn="13" endLine="28" endColumn="14" document="2" />
<entry offset="0x9c" startLine="29" startColumn="17" endLine="29" endColumn="39" document="2" />
<entry offset="0xa4" hidden="true" document="2" />
```
Line 27 contains the `if` statement and it's mapped to offset 0x8f which seems OK. But then offset 0x97 is also part of the `if` statement but it is marked as hidden even though it should also be mapped to line 27.

That said, even if the debug info is incorrect the behavior of the code should not be affected. If you have code that actually throws then the code generated by the C# and/or JIT compilers is probably incorrect. I suppose it could be possible that the same bug which causes weird debug info to be generated can also lead to incorrect code being generated. But without repro that's just a wild guess.

**Comment by anass-b** [comment] 2017-01-21 19:37
@mikedn That makes a lot of sense.

The sample project is an exact mirror of the buggy part in the actual project, so I'm wondering how we can reproduce the code generation issue.

@jnm2 my VS is vanilla, it has no extensions installed besides the ones from Microsoft that belongs to VS itself, so I don't think there is an extension that changes the IL. I anyways run `devenv.exe /SafeMode` but that didn't change anything.

**Comment by mikedn** [comment] 2017-01-21 19:40
Here's a simpler repro, when dealing with potential compiler bugs it's best to keep things as simple as possible:
```C#
using System;
using System.Threading.Tasks;

class Program
{
    static void Main() => TestAsync().Wait();

    static async Task TestAsync()
    {
        int nonZero = await FalseAsync();

        // The problem is that the debugger steps into the body of the if below but it should not.
        if (nonZero == 0)
        {
            throw new Exception();
        }
    }

    static async Task<int> FalseAsync() => await Task.FromResult(42);
}
```
I can reproduce the issue compiling with either VS2015 or VS2017 and running with any of the available JITs (JIT32, JIT64, RyuJIT).

**Comment by anass-b** [comment] 2017-01-21 19:44
@mikedn Great, now we are sure this is a bug in Roslyn and/or the JIT compiler.

**Comment by mikedn** [comment] 2017-01-21 19:51
Well, if a compile the code with the old C# compiler (pre-Roslyn) then debugger stepping works fine. I suppose that there's a good chance that the problem is in the Roslyn compiler.

> The sample project is an exact mirror of the buggy part in the actual project, so I'm wondering how we can reproduce the code generation issue.

Have you checked if the value is indeed `false` in the actual project? Maybe there's another issue and you end up with `true` unexpectedly. Try logging the value to the console or something to be sure.

**Comment by anass-b** [comment] 2017-01-21 20:03
> Have you checked if the value is indeed false in the actual project? Maybe there's another issue and you end up with true unexpectedly. Try logging the value to the console or something to be sure.

In the actual project, the value is every time false.

It's a boolean variable which is initialized with `false`, the value is then fetched from the database using dapper, after logging the variable's value, it shows false, when looking on the database with SSMS, the field is false before and after the debugging session and there is nobody touching that field, it's an isolated unit test. So we can be sure that the variable is all the time false.

**Comment by mikedn** [comment] 2017-01-21 20:06
Can you run the actual code in debugger, stop at the `if` statement and post some disassembly code from VS's disassembly view?

**Comment by anass-b** [comment] 2017-01-21 20:15
![screenshot0](https://cloud.githubusercontent.com/assets/8070594/22177481/ae9d898e-e01e-11e6-9b4b-942da6bd7de1.png)

![screenshot1](https://cloud.githubusercontent.com/assets/8070594/22177466/6ba7b726-e01e-11e6-9ea1-65850daa0eed.png)

**Comment by mikedn** [comment] 2017-01-21 20:48
Well, this looks correct. You have `cmp dword ptr [ebp-50], 0` and `je 0a2b573` which means `jump if equals 0`. That is, if not isDeleted then jump over exception throwing code.

The value at [ebp-50] can be traced back through a long stream of copies to `call 717C0EA0` which is likely the call to `TaskAwaiter<bool>.GetResult()`.

In general, the code looks pretty much identical to the code your repro generates so I'm running out of ideas.

**Comment by anass-b** [comment] 2017-01-21 20:56
What is even more weird is: when in debugging mode and while the debugging cursor stands in the line `throw new ServiceException();`, I press F10 it quits the current method, so far so good, while on the parent method, the execution continues line by line like no exception was thrown, at some point the code will start running slow until the test crashes/fails with "ServiceException was thrown".

When running in Release mode, the test runs quick, and fails immediately "ServiceException was thrown".

This tells us that in both debug and release, the exception is thrown anyways, this is proven by your simplified repro code.

**Comment by mikedn** [comment] 2017-01-21 21:00
Let's try one more thing: when in disassembly step until those cmp/je instructions and then look in the Registers window (see the Debug\Windows menu) to see what value EAX register has.

**Comment by anass-b** [comment] 2017-01-21 21:23
I made a small screen capture of the debugging session starting from the if: [debug.zip](https://github.com/dotnet/coreclr/files/721485/debug.zip)

**Comment by anass-b** [comment] 2017-01-21 21:34
it's very odd that it jumps from `0A845437  mov         dword ptr [ebp-50h],eax` to `0A84545E  nop` without going through `0A84543A  cmp         dword ptr [ebp-50h],0` and `0A84543E  je          0A84545E`

**Comment by mikedn** [comment] 2017-01-22 07:08
> I made a small screen capture of the debugging session starting from the if: debug.zip

Thanks! You can see that the EAX register really contains 0 so the `je` should be executed and thus an exception should not be thrown. I'm not sure what else we can try.

> it's very odd that after 0A845437 mov dword ptr [ebp-50h],eax it jumps to 0A84545E nop without going through 0A84543A cmp dword ptr [ebp-50h],0 and 0A84543E je 0A84545E

Yes, that's a symptom of bad source code stepping, it also affects disassembly stepping.

**Comment by miloush** [comment] 2017-01-22 17:20
Hmm... I think this might be happening to me too...

![untitled](https://cloud.githubusercontent.com/assets/10546952/22184226/800d9c92-e0c5-11e6-9d3b-4a87601c6842.png)

it gets to the last `mov` before `je`:
```
➧ 015FA2AD  mov         dword ptr [ebp-58h],eax  

EAX = 00000000 EBX = 0113F4FC ECX = 068A6B70 
EDX = 00000000 ESI = 068A6AC8 EDI = 0113F03C 
EIP = 015FA2AD ESP = 0113EFAC EBP = 0113F048 EFL = 00000246 

0x0113EFF0 = 00000000 
```
and the next step jumps to `nop` after the condition body rather than entering it.

Note I am running on full .NET Framework 4.5, debug configuration. This code is in a library referenced by a console app.

**Comment by miloush** [comment] 2017-01-22 17:37
Or maybe not. My problem was probably just bad source stepping. When I tried to rebuild, the library code got a lock and a star as if the file was not saved. Saving did not do anything. Closing the file asked me whether to save the file and when I said yes, nothing happened. Checking out the file manually did nothing. I have restarted VS which allowed me to save the file and now it steps as expected. So it looks like it compiled something else then it was showing during debugging.

**Comment by anass-b** [comment] 2017-01-22 17:55
@miloush I tried the Re-Save/Rebuild/Restart VS procedure but I didn't help solve the issue for me. Could you try that with the snippet of code provided by @mikedn:
```c#
using System;
using System.Threading.Tasks;

class Program
{
    static void Main() { TestAsync().Wait(); }

    static async Task TestAsync()
    {
        int nonZero = await FalseAsync();

        // The problem is that the debugger steps into the body of the if below but it should not.
        if (nonZero == 0)
        {
            throw new Exception();
        }
    }

    static async Task<int> FalseAsync() { return await Task.FromResult(42); }
}
```

**Comment by miloush** [comment] 2017-01-22 18:10
Yes I can reproduce that, I think there is a couple of different issues here
- debugger not showing what it is debugging - even when the condition is true, it jumps on `mov`
- the jump location is interpreted as inside the if body; that is incorrect - for example if you add Console.WriteLine after the if, it steps as expected
- your 'real' code actually executing what it shouldn't, for which we don't have a repro

**Comment by anass-b** [comment] 2017-01-22 18:48
I could finally make a reproduction code that shows that the program actually runs within the `if` block and executes the exception, you can find the code [here](https://github.com/anass-b/ReproduceExpressionBug2/blob/master/UnitTest1.cs#L40).
I wrote some comments in the code that explains what happens, but in short; calling the problematic method a second time will make the exception throw and the test to fail.

**Comment by mikedn** [comment] 2017-01-22 19:03
Hmm, I tried your project but I don't see anything wrong with it. There's no exception thrown and the assert fires accordingly because `exceptionCaught` is false.

**Comment by anass-b** [comment] 2017-01-22 19:04
@mikedn did the test pass or fail in your case ?

**Comment by mikedn** [comment] 2017-01-22 19:12
It failed.

**Comment by anass-b** [comment] 2017-01-22 19:14
You're right, the example still doesn't prove that the exception was thrown, in my actual project, the unit test fails with "ServiceException thrown". This is something I will try to get it happen in the repro code.

**Comment by anass-b** [comment] 2017-01-23 01:46
After a lot of digging, I found out that the bad source code stepping confused me into believing that the `if` content was executing and the exception was thrown, but it's not.
It was really hard to find this out because of the large code base I had to deal with, in an environment where you have bad source code stepping info and you cannot trust the debugger.

So I settle down with the same conclusion as @mikedn, that is, the tooling generates bad source code stepping.

**Comment by anass-b** [comment] 2017-01-25 12:32
Any updates on this issue ?
Maybe someone has an idea about a workaround ? or using Visual Studio 2013 is the only way at the moment ?

**Comment by anass-b** [comment] 2017-01-25 14:57
Here are some findings that can maybe help:

In the following code:
```c#
using System;
using System.Threading.Tasks;

class Program
{
    static void Main() { TestAsync().Wait(); }

    static async Task TestAsync()
    {
        int nonZero = await FalseAsync();

        // The problem is that the debugger steps into the body of the if below but it should not.
        if (nonZero == 0)
        {
            throw new Exception();
        }
    }

    static async Task<int> FalseAsync() { return await Task.FromResult(42); }
}
```
1) Replacing the line `throw new Exception();` with anything, let's say with `Console.WriteLine("test");` will fix the issue.
2) Adding any line of code after the `if` like this:
```c#
if (nonZero == 0)
{
    throw new Exception();
}
Console.WriteLine("test");
```
or even this:
```c#
if (nonZero == 0)
{
    throw new Exception();
}
else
{
}
```
will also fix the issue.

**Comment by mikedn** [comment] 2017-01-25 18:04
Probably you should open an issue in the Roslyn repository. Though I'm not sure what's wrong with the debug information (if anything) the fact that it works fine with the old C# compiler seem to indicate that the Roslyn compiler is the source of the problem.

**Comment by anass-b** [comment] 2017-01-25 19:07
Done: https://github.com/dotnet/roslyn/issues/16747.

**Closed** 2017-01-25 21:19 UTC
