### ISSUE TITLE
createdump cored when dumping the running program with dotnet core 2.2

### ISSUE THREAD

**Issue by skybook888** [dotnet/coreclr#21522] opened 2018-12-13 05:51 UTC
dumping current process with
“/usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.0/createdump -u $pid”
output：
```
Writing full dump to file core.mini.11457
Segmentation fault
```
lldb with the coredump file：
backtrace
```
* thread #1: tid = 0, 0x00007ff78094f89a libmscordaccore.so`??? + 362, name = 'createdump', stop reason = signal SIGSEGV
    frame #0: 0x00007ff78094f89a libmscordaccore.so`??? + 362
    frame #1: 0x00007ff78094f9cd libmscordaccore.so`??? + 189
    frame #2: 0x000000000040d244 createdump`CrashInfo::EnumerateManagedModules(IXCLRDataProcess*) + 260
    frame #3: 0x000000000040c19d createdump`CrashInfo::EnumerateMemoryRegionsWithDAC(_MINIDUMP_TYPE) + 269
    frame #4: 0x000000000040adf7 createdump`CrashInfo::GatherCrashInfo(_MINIDUMP_TYPE) + 663
    frame #5: 0x000000000040a093 createdump`CreateDumpCommon(char const*, _MINIDUMP_TYPE, CrashInfo*) + 179
    frame #6: 0x0000000000409bbe createdump`main + 606
    frame #7: 0x00007ff77fc6c830 libc.so.6`__libc_start_main + 240
    frame #8: 0x0000000000409899 createdump`_start + 41
(lldb)
```
dotnet info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
### In container
same program dumped in container
```
* thread #1: tid = 188, 0x00007ff24d09bc43 libmscordaccore.so`ClrDataAccess::EnumWksGlobalMemoryRegions(CLRDataEnumMemoryFlags) [inlined] __DPtr<dac_heap_segment> Dereference<dac_heap_segment>(ptr=<unavailable>) + 15 at request_common.h:26, name = 'createdump', stop reason = signal SIGSEGV
  * frame #0: 0x00007ff24d09bc43 libmscordaccore.so`ClrDataAccess::EnumWksGlobalMemoryRegions(CLRDataEnumMemoryFlags) [inlined] __DPtr<dac_heap_segment> Dereference<dac_heap_segment>(ptr=<unavailable>) + 15 at request_common.h:26
    frame #1: 0x00007ff24d09bc34 libmscordaccore.so`ClrDataAccess::EnumWksGlobalMemoryRegions(this=<unavailable>, flags=<unavailable>) + 68 at request.cpp:3808
    frame #2: 0x00007ff24d06a557 libmscordaccore.so`ClrDataAccess::EnumMemCLRHeapCrticalStatic(this=0x0000000000cd17b0, flags=CLRDATA_ENUM_MEM_HEAP) + 391 at enummem.cpp:170
    frame #3: 0x00007ff24d06f9ae libmscordaccore.so`ClrDataAccess::EnumMemoryRegionsWorkerHeap(this=0x0000000000cd17b0, flags=CLRDATA_ENUM_MEM_HEAP) + 270 at enummem.cpp:350
    frame #4: 0x00007ff24d0774ce libmscordaccore.so`ClrDataAccess::EnumMemoryRegionsWrapper(this=0x0000000000cd17b0, flags=CLRDATA_ENUM_MEM_HEAP) + 126
at enummem.cpp:1851
    frame #5: 0x00007ff24d077739 libmscordaccore.so`ClrDataAccess::EnumMemoryRegions(this=0x0000000000cd17b0, callback=<unavailable>, miniDumpFlags=512, flags=<unavailable>) + 233 at enummem.cpp:1939
    frame #6: 0x000000000040c16b createdump`CrashInfo::EnumerateMemoryRegionsWithDAC(this=0x0000000000c6d4c0, minidumpType=MiniDumpWithPrivateReadWriteMemory) + 219 at crashinfo.cpp:643
    frame #7: 0x000000000040adf7 createdump`CrashInfo::GatherCrashInfo(this=<unavailable>, minidumpType=<unavailable>) + 663 at crashinfo.cpp:209
    frame #8: 0x000000000040a093 createdump`CreateDumpCommon(dumpPathTemplate="core.mini.%d", minidumpType=MiniDumpWithPrivateReadWriteMemory, crashInfo=0x0000000000c6d4c0) + 179 at createdump.cpp:47
    frame #9: 0x0000000000409bbe createdump`main(argc=<unavailable>, argv=<unavailable>) + 606 at main.cpp:81
    frame #10: 0x00007ff24c3f62e1 libc.so.6`__libc_start_main + 241
    frame #11: 0x0000000000409899 createdump`_start + 41
```
dotnet info in container
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    51868761f2

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.100/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by jkotas** [comment] 2018-12-13 11:48
Duplicate of #21484

cc @mikem8361

**Closed by jkotas** 2018-12-13 11:48 UTC
