### ISSUE TITLE
corefx System.Globalization.Tests broken by recent change

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#22719] opened 2019-02-20 19:03 UTC
PR #22582 broke some System.Globalization.Tests so we need to disable them and wait until they are fixed on CoreFX side and we get the updated CoreFX here.

@hughbe please revert test exclusions and close this issue once it is fixed and changes are propagated.

cc @tarekgh

**Comment by jkotas** [comment] 2019-02-20 19:12
Is this fixed by https://github.com/dotnet/coreclr/pull/22717 ?

**Comment by sandreenko** [comment] 2019-02-20 19:12
[Failure example in ci ](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_corefx_jitstress2_tst/54/console).

It will be excluded in coreclr\tests\arm(64)\corefx_(linux\windows)_test_exclusions.txt.

**Comment by sandreenko** [comment] 2019-02-20 19:18
From @tarekgh https://github.com/dotnet/coreclr/pull/22582#issuecomment-463462089:

> Some of tests failed because of the change of the exception parameter which we renamed m_type to value. the change make sense but we'll need to disable the test temporary here and go and fix it in corefx

It describes the issue that we hit ([Example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst_prtest/41/consoleFull#20443403902d31e50d-1517-49fc-92b3-2ca637122019)).

I think #22717 fixed another issue.

**Comment by tarekgh** [comment] 2019-02-20 23:13
I am confused now, would the tests usually be excluded using corefx.issues.json? or would be excluded in corefx_(linux\windows)_test_exclusions.txt? or both? 

that is really very hard to manage.

I hope @ViktorHofer changes will address all of this.

**Comment by sandreenko** [comment] 2019-02-20 23:24
> that is really very hard to manage.

Yes.

> I am confused now, would the tests usually be excluded using corefx.issues.json? or would be excluded in corefx_(linux\windows)_test_exclusions.txt? or both?

I think the best available description is this comment https://github.com/dotnet/coreclr/pull/22358#issuecomment-460403667 from @jkotas :

> There are two different systems to run CoreFX tests in CoreCLR CI:
> (1) A system that uses the fixed test snapshot. It is what the CoreFX legs that are on by default in CoreCLR CI use.
> (2) A system that builds a live copy of CoreFX and then runs the tests. This system suffers from multiple sources of flakiness (e.g. #22344 (comment)). This system is used for optional JIT stress mode legs. This is the system that is being updated in this PR.
> The plan how to move this forward and unify these systems is being discussed in dotnet/corefx#34957 (comment)

the first uses corefx.issues.json, the second uses special files for arm/arm64 (other platform failures can't be excluded there). I do not have full information to explain why it was done that way. I believe there is a problem that XUnit is a managed application and it is hard to apply COMPLUS_stress_modes only for tests, but not for XUnit with the (1) approach.

**Comment by tarekgh** [comment] 2019-02-20 23:28
> the second uses special files for arm/arm64 (other platform failures can't be excluded there).

I think all tests excluded in corefx.issues.json should be excluded in all platforms runs too and then corefx_(linux\windows)_test_exclusions.txt should exclude the platform specific tests. Looks COMPLUS_stress_modes runs is not looking at corefx.issues.json at all.

**Comment by sandreenko** [comment] 2019-02-20 23:30
cc @jashook

**Comment by jkotas** [comment] 2019-02-20 23:35
> I do not have full information to explain why it was done that way

The system (2) is the older system. The system (1) was invented to address the reliability problems of system (2).

> I think all tests excluded in corefx.issues.json should be excluded in all platforms runs too

That may help with the flakiness a bit, but it won't make the CoreFX legs reliable. The real fix to make the CoreFX legs reliable is to get rid of the system (2) and switch all runs to be on system (1).

**Comment by jashook** [comment] 2019-02-21 18:08
>That may help with the flakiness a bit, but it won't make the CoreFX legs reliable. The real fix to make the CoreFX legs reliable is to get rid of the system (2) and switch all runs to be on system (1).

Correct. I do not know where this work is entirely; however, I believe @mikem8361 has been/was the last to work on some of this work.

**Comment by mikem8361** [comment] 2019-02-21 18:12
Yes, I'm working on the corefx tests in coreclr, but I'm still weeks away from it being finished.

**Comment by jkotas** [comment] 2019-05-08 05:23
Duplicate of https://github.com/dotnet/coreclr/issues/19690

**Closed by jkotas** 2019-05-08 05:23 UTC
Labels: area-Meta, disabled-test, test bug, test-corefx
