### ISSUE TITLE
tracing.eventsource/eventpipeandetw is flaky when running on Helix: Values for 'EventPipeEvent2Count' are not equal!

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#22045] opened 2019-01-17 22:26 UTC
This test has failed several times when AzDO/Helix were used for test running. 

**An example of failure**
```
C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Work\13ea449a-0878-4109-93d7-47090419bb17\Exec>type C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Work\13ea449a-0878-4109-93d7-47090419bb17\Unzip\SetStressModes_no_tiered_compilation.cmd 

@echo off

set COMPlus_TieredCompilation=0



C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Work\13ea449a-0878-4109-93d7-47090419bb17\Exec>C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Payload\CoreRun.exe C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Payload\xunit.console.dll tracing.eventsource.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -notrait category=outerloop -notrait category=failing 

xUnit.net Console Runner v2.4.1 (32-bit .NET Core 4.6.27317.0)

  Discovering: tracing.eventsource.XUnitWrapper
  Discovered:  tracing.eventsource.XUnitWrapper
  Starting:    tracing.eventsource.XUnitWrapper
   tracing_eventsource._eventpipeandetw_eventpipeandetw_eventpipeandetw_._eventpipeandetw_eventpipeandetw_eventpipeandetw_cmd [FAIL]
      
Unhandled Exception: System.Exception: Values for 'EventPipeEvent2Count' are not equal! Left='0' Right='1'

         at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right)
         at Tracing.Tests.EventPipeAndEtw.RoundOne(String[] args)
         at Tracing.Tests.EventPipeAndEtw.Main(String[] args)

Return code:      1
Raw output file:      C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Work\13ea449a-0878-4109-93d7-47090419bb17\Exec\Reports\tracing.eventsource\eventpipeandetw\eventpipeandetw\eventpipeandetw.output.txt
Raw output:
BEGIN EXECUTION

       "C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Payload\corerun.exe" eventpipeandetw.exe 
      	Start: Enable EventPipe.
      	End: Enable EventPipe.


      	Start: Enable ETW.
      	End: Enable ETW.

      	Start: Write events.
      	End: Writing events.

      	Start: Disable ETW.
      	End: Disable ETW.


      	Start: Write events.
      	End: Writing events.

      	Start: Disable EventPipe.
      	End: Disable EventPipe.

      	Start: Processing events from EventPipe file.
      
	EventPipe Results:
      		Event1Count: 2
      		Event2Count: 0
      		Event3Count: 2

      	End: Processing events from EventPipe file.

      	Start: Processing events from ETW file.

      
	ETW Results:
      		Event1Count: 0
      		Event2Count: 0
      		Event3Count: 0


      Expected: 100
      Actual: -532462766
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      
To run the test:
> set CORE_ROOT=C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Payload
> C:\dotnetbuild\work\8881aef7-7d29-487d-b02d-603e7570e29c\Work\13ea449a-0878-4109-93d7-47090419bb17\Exec\eventpipeandetw\eventpipeandetw\eventpipeandetw.cmd

      Expected: True
      Actual:   False
      Stack Trace:
        F:\vsagent\6\s\bin\tests\Windows_NT.x86.Checked\TestWrappers\tracing.eventsource\tracing.eventsource.XUnitWrapper.cs(109,0): at tracing_eventsource._eventpipeandetw_eventpipeandetw_eventpipeandetw_._eventpipeandetw_eventpipeandetw_eventpipeandetw_cmd()

  Finished:    tracing.eventsource.XUnitWrapper

=== TEST EXECUTION SUMMARY ===

   tracing.eventsource.XUnitWrapper  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 38.642s
```

**Comment by echesakovMSFT** [comment] 2019-01-17 22:44
@RussKeldorph Can you please identify the owners of the test? I tend to agree that the test should disabled before enabling AzDO-as-CI. Otherwise, it's going to produce false positives test failures.

**Comment by RussKeldorph** [comment] 2019-01-17 22:58
@noahfalk @jorive @vancem

**Comment by vancem** [comment] 2019-01-18 16:23
@echesakovMSFT  can you give us some idea how often the test fails?   (is it over half or more like 1%).   That will help us understand how we have to attack the problem.

Ultimately we will need a way of reproducting the problem.   If it fails rarely the easiest way to do this is to add additional logging to gather information on what is going wrong, but keep the test in place and monitor it closely).

But we should only do that if the simpler appraoch of simply running this test alot in a loop fails to reproduce the produce the problem. 

@jorive do you have time to look at this?

The source code for the test is in coreclr repo at src\tracing\eventsource\eventpipeandetw\EventPipeAndEtw.cs

**Comment by jorive** [comment] 2019-01-18 17:40
@vancem sure, I can take a look.
@echesakovMSFT could you please provide me repro steps?

**Comment by echesakovMSFT** [comment] 2019-01-18 18:17
@vancem
I would estimate the failure rate as about 1 out of 16. It fails on Windows_NT x86 and x64.

@jorive To repro the issue I would start with the exactly same commamd we run in CI:
```
%CORE_ROOT%\CoreRun.exe %CORE_ROOT%\xunit.console.dll D:\coreclr\bin\tests\Windows_NT.x64.Checked\tracing\eventsource\tracing.eventsource.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -notrait category=outerloop -notrait category=failing 
```

where CORE_ROOT is D:\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root assuming you cloned coreclr in D:\coreclr

**Comment by sdmaclea** [comment] 2019-02-26 00:55
Is there any reason we can't disable this why we triage root cause?

**Comment by jorive** [comment] 2019-02-27 21:48
Closed by https://github.com/dotnet/coreclr/pull/22870

**Closed by jorive** 2019-02-27 21:48 UTC
Labels: arch-x64, arch-x86, area-Tracing, os-windows
