### ISSUE TITLE
[RyuJIT/arm32][JITMinOpts=1] Test runtime failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#14860] opened 2017-11-03 22:40 UTC
The following tests fail with `COMPlus_JITMinOpts=1` on Windows arm32.

```
GC\LargeMemory\Allocation\finalizertest\finalizertest.cmd
JIT\IL_Conformance\Old\Conformance_Base\ldc_add_ovf_u4\ldc_add_ovf_u4.cmd
```

CI job:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_minopts_prtest/7/consoleText

Results:
```
Running: C:\brucefo\Windows_NT.arm.Release.2017-11-03\GC\LargeMemory\Allocation\finalizertest\finalizertest.cmd -coreroot c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-03
BEGIN EXECUTION
 "c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-03\corerun.exe" finalizertest.exe 2048
0 2147483648
allocateInFinalizerTest failed
OOM
Large Memory Machine required
Test failed
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Running: C:\brucefo\Windows_NT.arm.Release.2017-11-03\JIT\IL_Conformance\Old\Conformance_Base\ldc_add_ovf_u4\ldc_add_ovf_u4.cmd -coreroot c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-03
BEGIN EXECUTION
 "c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-03\corerun.exe" ldc_add_ovf_u4.exe
Expected: 100
Actual: 101
END EXECUTION - FAILED
```

It also looks like
```
GC\Regressions\dev10bugs\536168\536168\536168.cmd 
```
fails, because it hangs. It also hangs without `COMPlus_JITMinOpts=1`.

**Comment by rartemev** [comment] 2017-11-10 21:02
Cannot reproduce failures.

```
C:\Users\rartemev\Desktop\tests>echo %COMPlus_JITMinOpts%
1
C:\Users\rartemev\Desktop\tests>issue_14860\536168\536168.cmd -coreroot C:\Users\rartemev\Desktop\tests\Core_Root -debug C:\DebuggersWoa\windbg.exe

C:\Users\rartemev\Desktop\tests>issue_14860\536168\536168.cmd -coreroot C:\Users\rartemev\Desktop\tests\Core_Root
BEGIN EXECUTION
 "C:\Users\rartemev\Desktop\tests\Core_Root\corerun.exe" 536168.exe

Unhandled Exception: OutOfMemoryException.
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED

C:\Users\rartemev\Desktop\tests>issue_14860\finalizertest\finalizertest.cmd -coreroot C:\Users\rartemev\Desktop\tests\Core_Root
BEGIN EXECUTION
 "C:\Users\rartemev\Desktop\tests\Core_Root\corerun.exe" finalizertest.exe 2048
allocateInFinalizerTest passed
ressurectionTest passed
Test passed
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED

C:\Users\rartemev\Desktop\tests>issue_14860\ldc_add_ovf_u4\ldc_add_ovf_u4.cmd -coreroot C:\Users\rartemev\Desktop\tests\Core_Root
BEGIN EXECUTION
 "C:\Users\rartemev\Desktop\tests\Core_Root\corerun.exe" ldc_add_ovf_u4.exe
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
```
`GC\Regressions\dev10bugs\536168\536168\536168.cmd` fails because of enormous size of used memory (5 TB) and it allocates it concurrently with GC work, so I think such failure is logical on machines with small amount of memory.  

`C:\Users\rartemev\Desktop\tests\Core_Root` is Checked arm32 build.

**Comment by BruceForstall** [comment] 2017-11-10 22:04
Can we mark 536168 in such a way that it doesn't run on arm32, if memory is an issue?

E.g., it is already marked `<GCStressIncompatible>true</GCStressIncompatible>`.

@swgillespie ?

**Comment by swgillespie** [comment] 2017-11-10 22:06
@BruceForstall you can add it to https://github.com/dotnet/coreclr/blob/master/tests/testsUnsupportedOnARM32.txt , seems to be what people do when this occurs

**Comment by rartemev** [comment] 2017-11-16 21:56
Since both finalizertest & ldc_add_ovf_u4 have passed I close this issue.

**Comment by BruceForstall** [comment] 2017-11-22 02:06
These are failing again.

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_minopts_tst_prtest/8/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/

Tests:
```
CoreMangLib\cti\system\math\MathSign5\MathSign5.cmd
GC\LargeMemory\Allocation\finalizertest\finalizertest.cmd
JIT\IL_Conformance\Old\Conformance_Base\ldc_add_ovf_u4\ldc_add_ovf_u4.cmd
```

I repro'ed locally with Checked ARM Windows against Release built tests.

Output:
```
BEGIN EXECUTION
 "c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-11\corerun.exe" MathSign5.exe
Beginning test case Testing System.Math.Sign(System.Int64). at 11/21/2017 5:58:23 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

[Positive]
Beginning scenario: PosTest1: Verify Int64.MaxValue is a positive number.
Beginning scenario: PosTest2: Verify Int64.MinValue is a negative number.
Beginning scenario: PosTest3: Verify the return value should be 1 when the Int64 is positive.
Beginning scenario: PosTest4: Verify the return value should be -1 when the Int64 is negative.
Beginning scenario: PosTest5: Verify the return value should be 0 when the Int64 is zero.
ERROR!!!-P05.1: The return value is not -1 when the Int64 is negative!

Ending test case at 11/21/2017 5:58:23 PM
FAIL
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Running: C:\brucefo\Windows_NT.arm.Release.2017-11-11\GC\LargeMemory\Allocation\finalizertest\finalizertest.cmd -coreroot c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-11
BEGIN EXECUTION
 "c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-11\corerun.exe" finalizertest.exe 2048
0 2147483648
allocateInFinalizerTest failed
OOM
Large Memory Machine required
Test failed
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Running: C:\brucefo\Windows_NT.arm.Release.2017-11-11\JIT\IL_Conformance\Old\Conformance_Base\ldc_add_ovf_u4\ldc_add_ovf_u4.cmd -coreroot c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-11
BEGIN EXECUTION
 "c:\brucefo\core_root\Windows_NT.arm.Checked.2017-11-11\corerun.exe" ldc_add_ovf_u4.exe
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
PASS: 0, FAIL: 3, TOTAL: 3
Failures:
C:\brucefo\Windows_NT.arm.Release.2017-11-11\CoreMangLib\cti\system\math\MathSign5\MathSign5.cmd
C:\brucefo\Windows_NT.arm.Release.2017-11-11\GC\LargeMemory\Allocation\finalizertest\finalizertest.cmd
C:\brucefo\Windows_NT.arm.Release.2017-11-11\JIT\IL_Conformance\Old\Conformance_Base\ldc_add_ovf_u4\ldc_add_ovf_u4.cmd
```

(repro'ed as of git commit 30d20fd832b4dba9e6d5f9c77f88d8b3ccd1066e, 11/21/2017 14:44)

**Comment by BruceForstall** [comment] 2017-11-22 02:06
@rartemev If you aren't planning to look at these, please unassign yourself.

**Comment by BruceForstall** [comment] 2017-12-08 16:53
Current failures:
```
Tests.lst=finalizertest.cmd_2841, , , Smrt00000001, , # GC\LargeMemory\Allocation\finalizertest\finalizertest.cmd  CATS: EXPECTED_PASS;Pri1
Tests.lst=ldc_add_ovf_u4.cmd_8693, , , Smrt00000001, , # JIT\IL_Conformance\Old\Conformance_Base\ldc_add_ovf_u4\ldc_add_ovf_u4.cmd  CATS: EXPECTED_PASS
Tests.lst=CompareExchangeTString.cmd_9382, , , Smrt00000001, , # baseservices\threading\interlocked\compareexchange\CompareExchangeTString\CompareExchangeTString.cmd  CATS: EXPECTED_PASS;Pri1
```
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_minopts_tst_prtest/12/artifact/bin/tests/Windows_NT.arm.Checked/Smarty.run.0/Smarty.0.fail.smrt/*view*/

**Comment by BruceForstall** [comment] 2017-12-11 18:42
Still not fully fixed.

**Closed** 2017-12-12 05:51 UTC
Labels: arch-arm32, area-CodeGen, bug
