### ISSUE TITLE
ildasm/ilasm fail to re-build the base System assembly (System.Private.CoreLib,  System.Runtime or netstandard)

### ISSUE THREAD

**Issue by dseefeld** [dotnet/coreclr#20262] opened 2018-10-04 16:35 UTC
Repro steps:
```
ildasm System.Runtime.dll -all -out=System.Runtime.il
ilasm System.Runtime.il -dll -quiet -nologo -output=new/System.Runtime.dll
```

Expected result:
- new dll builds without errors.

Actual result:
```
System.Runtime.il(578) : warning : Reference to undeclared extern assembly 'mscorlib'. Attempting autodetect
System.Runtime.il(4202) : warning : Non-sealed value class, made sealed
error : Invalid Get method of property 'Chars'
Could not create output file, error code=0x80004005
```

**Comment by jkotas** [comment] 2018-10-04 16:39
The problem is here: https://github.com/dotnet/coreclr/blob/master/src/ilasm/asmman.cpp#L251

The fix should be to:
- Add all known possible system module names to the above
    and/or
- Produce `.mscorlib` directive in ildasm when the assembly being disassembled is system module.

**Comment by RussKeldorph** [comment] 2018-10-04 17:56
@jkotas Is there something intrinsic about a "system" module that ildasm can recognize, or would we have to hard code the list of known possible names there as well?

**Comment by jkotas** [comment] 2018-10-04 19:09
> something intrinsic about a "system" module that ildasm can recognize

Mark it with `.mscorlib` if the assembly has no references. It is what Roslyn does: https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Binding.cs#L938

**Comment by dseefeld** [comment] 2019-07-11 20:52
Any updates on a fix for this?

**Comment by dseefeld** [comment] 2019-07-25 15:58
This issue is preventing source-build from getting to zero-prebuilts.  We need to include these assemblies as prebuilts, since they can't be round-tripped with ildsam/ilasm.

**Comment by briansull** [comment] 2019-07-25 18:44
Investigating.

I note that currently  System.Runtime.dll roundtrips just fine, but I do see the behavior describe here for  System.Private.Corelib.dll:

**Comment by briansull** [comment] 2019-07-25 20:31
d:\fxkit\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root>ildasm.exe System.Private.CoreLib.dll -all -out=System.Private.CoreLib.il

d:\fxkit\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root>ilasm System.Private.CoreLib.il -dll -quiet -nologo -output=new\System.Private.CoreLib.dll
System.Private.CoreLib.il(27462) : warning : Reference to undeclared extern assembly 'System.Private.Corelib'. Attempting autodetect
System.Private.CoreLib.il(62364) : warning : Non-sealed value class, made sealed
error : Invalid Get method of property 'Chars'
Could not create output file, error code=0x80004005

***** FAILURE *****

**Comment by jeffschwMSFT** [comment] 2019-08-15 15:50
Closing with #25926 and #25988

**Closed by jeffschwMSFT** 2019-08-15 15:50 UTC
Labels: area-ILTools, bug
