### ISSUE TITLE
Dictionary should tell which key is not found in dictionary.

### ISSUE THREAD

**Issue by fuszenecker** [dotnet/coreclr#2265] opened 2015-12-08 09:33 UTC
The error message "The given key was not present in the dictionary." should be a bit more informative, it could also tell which key is not found in the dictionary.

**Comment by i3arnon** [comment] 2015-12-08 09:58
See https://github.com/dotnet/corefx/issues/1187

**Comment by joshfree** [comment] 2016-01-07 23:19
Hi @fuszenecker,
I'm closing this out as a duplicate of https://github.com/dotnet/corefx/issues/1187.  Thank you

**Closed by joshfree** 2016-01-07 23:19 UTC
Labels: mscorlib, suggestion
