### ISSUE TITLE
ProfilerAPI: RequestReJit hang when Microsoft.NET.Sdk.Web used

### ISSUE THREAD

**Issue by iskiselev** [dotnet/coreclr#25934] opened 2019-07-30 05:16 UTC
When profiler calls RequestReJit, if Microsoft.NET.Sdk.Web for instrumented project, application main thread hangs. .Net even will not call GetReJITParameters callback.

Issue is reproducible on .Net Core 3 Preview 7, windows x64.
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

I've prepared repro: https://github.com/iskiselev/ProfilerReJitHang (see readme.md for instructions).
Issue is not reproducible when "Microsoft.NET.Sdk" is used. It is not reproducible on .NET Core 2.x also.

**Comment by hoyosjs** [comment] 2019-07-30 18:15
@davmason 

cc @dotnet/dotnet-diag

**Comment by tommcdon** [comment] 2019-07-30 18:15
@davmason

**Comment by davmason** [comment] 2019-07-30 19:00
Thanks for the repro @iskiselev. I'll take a look and see what's happening.

**Comment by davmason** [comment] 2019-07-30 21:48
@iskiselev are you only seeing this while debugging? When I run your repro under the VS debugger it fails in the way you describe because edit and continue is enabled and ReJIT is not supported when EnC is enabled. If I turn off EnC in VS (Debug Menu->Options->General->Uncheck Enable Edit and Continue) it works as expected.

In general profiling while debugging is dangerous. Our official stance is that it is unsupported, but we have made certain scenarios work (i.e. making managed breakpoints work in profiler modified functions).

**Comment by iskiselev** [comment] 2019-07-30 22:37
@davmason, I've just checked it - the issue is reproducible only under VS debug. It is non-critical (or even non-issue) in that case. Thank you!

**Comment by davmason** [comment] 2019-07-30 23:55
Thanks for confirming. Closing this issue since it is expected behavior.

**Closed by davmason** 2019-07-30 23:55 UTC
Labels: area-Diagnostics
