### ISSUE TITLE
TailcallVerifyWithPrefix test has assertion failure on Windows 64

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2329] opened 2015-12-14 20:02 UTC
The JIT\opt\Tailcall\TailcallVerifyWithPrefix\TailcallVerifyWithPrefix.cmd test
fails with this message:

```
 Assert failure(PID 54344 [0x0000d448], Thread: 61376 [0xefc0]): 
    Assertion failed 'nextStmtExpr->gtOper == GT_RETURN' 
   in 'TailcallVerify.Condition2:Caller1()' (IL size 55)
	        
   File: coreclr\src\jit\morph.cpp Line: 6671
   Image: coreclr\bin\tests\Windows_NT.x64.debug\Tests\Core_Root\CoreRun.exe
```

**Comment by sivarv** [comment] 2016-01-05 00:19
This looks to be a duplicate of issue #2353 opened on Linux.

**Comment by sivarv** [comment] 2016-01-08 03:09
I could not repro the assert failure on windows x64 using debug/checked bits.

Further I have noticed from TailcallVerifyWithPrefix.ilproj file that it is getting always compiled with 
<Optimize>False</Optimize>

This would mean that ilasm would generate an assembly with debuggable attribute that turns off jit optimizations.  But for this to pass, it should always be compiled with Optimize = True.

I have manually ildasm'ed the original binary and ilass'ed it using /DEBUG=OPT and the resulting binary has the same result as running on desktop CLR (both against RyuJIT and Legacy Jit64). The test still return 101 as exit status with one of the test cases (Condition18.Test1) failing.  It is expected, even on desktop against Legacy JIT that particular test case fails and the entire test exits with 101.  

Please enable this test after addressing the above.  For now marking it as test issue.

**Comment by RussKeldorph** [comment] 2016-05-09 17:08
Windows_NT.x64.Checked: I can reproduce the assertion when ilasm'd without /DEBUG=OPT as it is being built currently.  @sivarv, could you take a look again at severity of this?
```
Executing Condition2.Test1  - Caller: Arguments: None - ReturnType: void; Callee: Arguments: 0 - ReturnType: Int32

Assert failure(PID 12312 [0x00003018], Thread: 21000 [0x5208]): Assertion failed 'nextStmtExpr->gtOper == GT_RETURN' in 'TailcallVerify.Condition2:Caller1()' (IL size 55)

    File: c:\git\coreclr\src\jit\morph.cpp Line: 7112
    Image: C:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 1
```
If/when fixed, my proposal would be to create a separate regression test to reproduce the assertion failure, and then clean up TailcallVerifyWithPrefix.  Obviously, as @sivarv notes above, it needs to build with /DEBUG=OPT to have any hope of passing.  It may also make sense to break it up into its constituent cases.  I uploaded a table summarizing how the earlier test harness treated the individual cases inside the test.  The variety of exclusions/incompatibilities across the suite suggests this test should be broken up.

https://gist.github.com/RussKeldorph/e3245ea8511025bcd51795fd1260c40e#file-tailcallverifywithprefix-csv

**Comment by LLITCHEV** [comment] 2016-05-09 17:56
Assigning to me per @RussKeldorph request to investigate the assert.

**Closed** 2016-05-20 02:13 UTC
Labels: 2 - In Progress, CodeGen, Test-Issue
