### ISSUE TITLE
Jit out empty finally/using

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#7056] opened 2016-09-05 20:29 UTC
Common example is `foreach`
```csharp
foreach (var item in col)
{
    // ...
}
```
Becomes something like
```csharp
var enumerator = col.GetEnumerator();
try
{
    while (enumerator.MoveNext())
    {
        var item = enumerator.Current;
        // ...
    }
}
finally
{
    enumerator.Dispose();
}
```
Usually Dispose is an empty function; but a function that uses `foreach` will be discounted for inlining due to `[FAILED: has exception handling] `

It would be helpful if the Dispose was detected as empty (inlined), then the finally block detected as empty, then the whole try/finally removed.

**Comment by mikedn** [comment] 2016-09-05 21:42
Looks like a duplicate of #1505

**Comment by benaadams** [comment] 2016-09-05 21:58
Does indeed :)

**Comment by pgavlin** [comment] 2016-09-07 16:03
Yup. Closing as such.

**Closed by pgavlin** 2016-09-07 16:03 UTC
Labels: CodeGen
