### ISSUE TITLE
Fix threading/Sleep/test1/paltest_sleep_test1

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#10222] opened 2017-03-16 02:40 UTC
Flaky, failing about 10% of the time on Sierra.  Disabled in #10221

**Comment by mmitche** [comment] 2017-03-16 02:40
FYI @jkotas

**Comment by kouvel** [comment] 2017-03-18 05:25
Considering this a duplicate of #8321, noted the disabled test in that issue

**Comment by kouvel** [comment] 2017-03-18 05:25
#10261 is similar

**Closed by kouvel** 2017-03-18 05:25 UTC
Labels: area-PAL
