### ISSUE TITLE
crossgen error

### ISSUE THREAD

**Issue by cocotr** [dotnet/coreclr#8792] opened 2017-01-03 23:45 UTC
When I am trying to crossgen on Windows or Linux I am always getting similar error:

Error: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
Error compiling ConsoleApp5.dll: Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
Error: compilation failed for "ConsoleApp5.dll" (0x80131621)

**Comment by jkotas** [comment] 2017-01-04 00:42
Duplicate of https://github.com/dotnet/coreclr/issues/8749

**Closed by jkotas** 2017-01-04 00:42 UTC
