### ISSUE TITLE
baseservices_threading._threadstatic_ThreadStatic03_ThreadStatic03_._threadstatic_ThreadStatic03_ThreadStatic03 failed in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#10673] opened 2017-04-03 22:07 UTC
https://github.com/dotnet/coreclr/pull/10667

```
D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs(26077): error : baseservices_threading._threadstatic_ThreadStatic03_ThreadStatic03_._threadstatic_ThreadStatic03_ThreadStatic03_cmd [FAIL] [D:\j\workspace\x64_release_w---0575cb46\tests\runtest.proj]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\Reports\baseservices.threading\threadstatic\ThreadStatic03\ThreadStatic03.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x64_release_w---0575cb46\tests\..\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe" ThreadStatic03.exe 
        Expected: 100
        Actual: -1073740791
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
  > D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\baseservices\threading\threadstatic\ThreadStatic03\ThreadStatic03.cmd
  
        Expected: True
        Actual:   False
          D:\j\workspace\x64_release_w---0575cb46\bin\tests\Windows_NT.x64.Release\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs(26077,0): at baseservices_threading._threadstatic_ThreadStatic03_ThreadStatic03_._threadstatic_ThreadStatic03_ThreadStatic03_cmd()
```

**Comment by janvorli** [comment] 2017-04-04 08:13
The exit code means a buffer overrun.

**Comment by gkhanna79** [comment] 2017-04-12 20:30
@kouvel PTAL

**Comment by kouvel** [comment] 2017-04-28 17:12
Not able to repro this after many runs. The issue is probably not even related to this test. Closing for now.

**Closed by kouvel** 2017-04-28 17:12 UTC
Labels: area-System.Threading, bug
