### ISSUE TITLE
GC\Scenarios\DoublinkList\dlstack occasionally failing with RyuJIT/x86

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#6553] opened 2016-08-01 16:46 UTC
For example:
- http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x86_ryujit_checked_windows_nt_prtest/2587/console
- http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x86_ryujit_checked_windows_nt_prtest/2590/consoleFull#-21135842918bb52e59-de52-4f1c-b131-470db4c594cd

cc @jashook @adiaaida

**Comment by adiaaida** [comment] 2016-08-01 16:51
I think this is a timeout issue.

**Comment by swgillespie** [comment] 2016-08-01 16:57
hmm, it looks like this test failed due to a failure to finalize 9 test objects. Does this happen regularly?

**Comment by adiaaida** [comment] 2016-08-01 17:26
Not locally, but on PR, I've seen it happen quite a few times.

**Comment by RussKeldorph** [comment] 2016-08-02 14:59
@pgavlin Any reason to suspect CodeGen?

**Comment by RussKeldorph** [comment] 2016-08-03 14:48
Mentioning #6574 here in case they happen to be related.  They certainly might not be, but the two test failures have enough superficially in common that I think it's worth noting.

**Comment by swgillespie** [comment] 2016-08-04 17:37
@RussKeldorph do I need to do anything other than `build.cmd x86 Checked` to build in an x86/ryujit configuration, so I can reproduce this?

**Comment by adiaaida** [comment] 2016-08-04 17:44
@swgillespie Not for building. Just make sure you set complus_altjit=* and complus_altjitname=protojit.dll

**Comment by swgillespie** [comment] 2016-08-04 17:45
@adiaaida thanks!

**Comment by jkotas** [comment] 2016-08-24 17:49
Another: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x86_ryujit_checked_windows_nt_prtest/3306/

**Comment by jkotas** [comment] 2016-08-24 17:53
I am disabling the test to improve CI stability: https://github.com/dotnet/coreclr/pull/6895

**Comment by BruceForstall** [comment] 2016-08-30 00:26
@swgillespie Are you still investigating this failure? What is the next step?

All the CI links for the failure are gone, so I can't see what the failures are (if there's any interesting information there anyway).

I can't get this to repro on my machine. Any chance it's been "fixed"? Seems hard to believe it would time out, since the test runs in ~1 second.

**Comment by swgillespie** [comment] 2016-08-30 00:30
@BruceForstall apologies, I've been out the past week and it's on my list of things to do. The failures were all indicating that not all of the test objects have been finalized, in the same manner as https://github.com/dotnet/coreclr/issues/4093 and https://github.com/dotnet/coreclr/issues/6574 . I suspect that all of these have a common cause, although I have no evidence other than the presentation and I also have been unable to reproduce the issues.

The only hint that I have is that it only seems to occur on checked builds, and only on Ubuntu/x64 and Windows/x86 RyuJIT.

**Comment by BruceForstall** [comment] 2016-09-06 17:25
@swgillespie any luck on this one yet?

**Comment by swgillespie** [comment] 2016-09-06 17:30
@BruceForstall still nothing, I've been unable to reproduce this issue or any other one of this sort. I spoke to Maoni about this and she would not be opposed to disabling this test and other flaky finalizer tests, since they have very little value and don't add any additional coverage that's not covered elsewhere.

I'm thinking that I will disable this test across all platforms and not just this one.

**Comment by BruceForstall** [comment] 2016-09-06 17:37
I would support that. I guess you need to decide if they should be disabled or simply deleted altogether.

fwiw, I'm trying to make RyuJIT/x86 "clean", by having no test exclusions specific to RyuJIT/x86, which is why I've been asking about this.

**Comment by swgillespie** [comment] 2016-09-06 17:49
I suppose the only considerations re: deletion would be whether or not we're concerned with keeping our internal and external tests in sync, which (at least for the GC tests) doesn't seem like something we're concerned about.

**Comment by jkotas** [comment] 2016-09-06 18:08
Do we understand why are these tests failing intermittently? Why is the intermittent failure not a product bug?

If these tests are bad and flaky by construction, delete them. Otherwise, find and fix the intermittent bug that they are hitting.

**Comment by jkotas** [comment] 2016-09-06 18:11
E.g. if you are not able to reproduce the failure on your machine, add more logging to the tests so that you can get better idea on why they are failing next time we see the failure

**Comment by swgillespie** [comment] 2016-09-06 18:17
@jkotas The failure is the test failing to finalize some nodes in a linked list, and it only happens on checked builds. As for why it happens, there aren't many clues - ideally I'd like to inspect the state of the finalizer queue when the test fails but I don't think that's something I can log from managed code. 

Now that we can get limited crash dumps from Ubuntu, it may be useful to temporarily make the test crash on failure in the hopes of getting a dump that we can inspect.

**Comment by BruceForstall** [comment] 2016-09-23 19:38
@swgillespie Any update on this?

**Comment by swgillespie** [comment] 2016-09-23 22:34
@BruceForstall No update from last time, I haven't had much time to look into this. I've allocated time on Monday to look into this and the other finalizer issues and I won't stop until I have an answer. I'll keep you updated with what I find.

**Comment by BruceForstall** [comment] 2016-09-29 20:47
This is no longer considered an x86 issues, so I removed those tags.

**Comment by swgillespie** [comment] 2017-04-21 18:18
Closing in favor of https://github.com/dotnet/coreclr/issues/4093, which tracks this particular issue.

**Closed by swgillespie** 2017-04-21 18:18 UTC
Labels: area-GC, bug
