### ISSUE TITLE
Test failed: System.IO.AsWinRTStreamTests.TestRead_MemoryStream_None

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#27518] opened 2019-10-29 02:13 UTC
**Job:**
[coreclr-corefx-jitstressregs #20191028.1 Run Test Pri1 CoreFX Windows_NT x64 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=404253)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/26390fc6-69ce-44a9-888c-8178ee69d4b9/workitems/System.Runtime.WindowsRuntime.Tests/console

**OS & Arch:**
windows x64

**Mode:**
COMPlus_JitStressRegs=0x80
COMPlus_TieredCompilation=0

**Note:**
This failure **doesn't repro** on our windows x64 machine.

**Log:**
```
C:\dotnetbuild\work\26390fc6-69ce-44a9-888c-8178ee69d4b9\Work\804cee4b-2133-4af8-ba6a-1fbc62789215\Exec>"C:\dotnetbuild\work\26390fc6-69ce-44a9-888c-8178ee69d4b9\Payload\dotnet.exe" exec --runtimeconfig System.Runtime.WindowsRuntime.Tests.runtimeconfig.json xunit.console.dll System.Runtime.WindowsRuntime.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\26390fc6-69ce-44a9-888c-8178ee69d4b9\Payload\CoreFX.issues.rsp 
  Discovering: System.Runtime.WindowsRuntime.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.WindowsRuntime.Tests (found 117 of 120 test cases)
  Starting:    System.Runtime.WindowsRuntime.Tests (parallel test collections = on, max threads = 2)
    System.IO.CreateSafeFileHandleTests.FromStorageFolder_SurfaceNotFoundException [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.CreateSafeFileHandleTests.FromStorageFolder_Basic [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.CreateSafeFileHandleTests.FromStorageFile_FileStream [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.CreateSafeFileHandleTests.FromStorageFile_Basic [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.CreateSafeFileHandleTests.FromStorageFolder_FileStream [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.CreateSafeFileHandleTests.FromStorageFolder_SurfaceIOException [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.CreateSafeFileHandleTests.FromStorageFile_SurfaceIOException [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.AsWinRTStreamTests.TestRead_MemoryStream_None [FAIL]
      Completion callback specified to ReadAsync callback must be invoked
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.WindowsRuntime/tests/System/IO/AsWinRTStreamTests.cs(256,0): at System.IO.AsWinRTStreamTests.DoTestRead(Func`1 createStreamFunc, InputStreamOptions inputStreamOptions, Boolean mustInvokeProgressHandler, Boolean completesSynchronously)
        /_/src/System.Runtime.WindowsRuntime/tests/System/IO/AsWinRTStreamTests.cs(144,0): at System.IO.AsWinRTStreamTests.TestRead_MemoryStream_None()
  Finished:    System.Runtime.WindowsRuntime.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.WindowsRuntime.Tests  Total: 274, Errors: 0, Failed: 1, Skipped: 7, Time: 13.963s
exit code 1
```

**Comment by jkotas** [comment] 2019-10-29 17:35
Duplicate of https://github.com/dotnet/corefx/issues/40348

**Closed by jkotas** 2019-10-29 17:35 UTC
Labels: arch-x64, os-windows, test-corefx
