### ISSUE TITLE
Dotnet crashing on CentOS 7.3 (maybe a JIT bug?)

### ISSUE THREAD

**Issue by jrockwood** [dotnet/coreclr#24425] opened 2019-05-06 21:43 UTC
I apologize in advance for logging this somewhat vague bug...

I'm a developer at Tableau Software and I recently upgraded our custom Saltarelle compiler (used to be Script#, which compiles C# to JavaScript) to use .NET Standard/Core instead of basing it off of the .NET Framework so that we can build on Linux. Previously we were using XBuild and Mono on our Linux builds. Everything has been working for weeks with the new dotnet-based Saltarelle compiler on all of our build machines (Windows and Linux) except for one set of machines that we have, where it fails every time. All of these machines are using CentOS 7.3 and the other machines where the build works are based on CentOS 7.5. I was able to recreate a vanilla CentOS 7.3 machine and can reproduce the build failures. When I upgrade that same machine to CentOS 7.5, the errors go away.

The build fails differently every time, but it always inevitably fails. We have about 160 projects in a solution and we're using `dotnet msbuild` to do the build. It will fail in different projects every time it's run, so it's definitely not an issue with our code (since a project will build successfully one time and fail another). One other interesting thing to note... if you keep running the build as an incremental build, it will eventually succeed. Sometimes it takes 2-3 times, other times it will succeed after 10+ attempts.

Since this is intermittent, I thought I'd try turning off parallel builds (passing in the `/m:1` switch) so that only one project is built at a time. But that seems to have no effect and things still fail (they just fail more slowly now :).

From the stack traces that I've been able to look at in lldb, there seems to be a pattern of a segmentation fault in the jitter. Here are a couple of stack traces for an example:

```
(lldb) target create --core "/data/core-dumps/core.dotnet.66894.tsperf-d358.perf.dev.tsi.lan.1557166562"
Core file '/data/core-dumps/core.dotnet.66894.1557166562' (x86_64) was loaded.
(lldb) command source -s 0 '/home/tsi/builder/commands.txt'
Executing commands in '/home/tsi/builder/commands.txt'.
(lldb) plugin load /data/<redacted-path-to-dotnet>/Microsoft.NETCore.App/2.2.2/libsosplugin.so
(lldb) pe
There is no current managed exception on this thread
(lldb) clrthreads
ThreadCount:      31
UnstartedThread:  0
BackgroundThread: 30
PendingThread:    0
DeadThread:       0
Hosted Runtime:   no
                                                                                                        Lock
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
  36    1 1054e 00000000021F5C20  2020020 Preemptive  00007FF4545F5490:00007FF4545F6E98 00000000021F1A50 0     Ukn
   4    2 10559 0000000002272360    21220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Finalizer)
  27    3 1055a 00007FF44C0009F0  1020220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  31    4 1055b 00007FF4440009F0    20220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn
  30    5 1055d 000000000235CA60  2021220 Preemptive  00007FF45476E598:00007FF45476F020 00000000021F1A50 0     Ukn
   2    6 1055e 00007FF448004C00  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  21    7 10560 00007FF43C0012A0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  20    8 10562 00007FF43C007CD0    21220 Preemptive  00007FF4545F0F28:00007FF4545F2E98 00000000021F1A50 0     Ukn
  22    9 10563 00007FF434001340  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
   8   10 10564 000000000229E1E0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
   7   11 10565 00007FF42C0012A0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  33   12 10566 00007FF4300012A0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
   3   13 107a8 00007FF424003B50  2021220 Preemptive  00007FF45464C7A0:00007FF45464D0D8 00000000021F1A50 0     Ukn
   9   14 10847 00007FF4280012F0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  32   15 10859 00007FF4280031A0  3021220 Preemptive  00007FF4545FBD00:00007FF4545FCE98 00000000021F1A50 0     Ukn (Threadpool Worker)
  17   16 1085a 00007FF434003630  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  25   17 1086c 00007FF424005A90  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  35   18 1086d 00007FF4340054F0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
   6   19 1087a 00007FF42C0037A0  1021220 Preemptive  00007FF454671458:00007FF454672098 00000000021F1A50 0     Ukn (Threadpool Worker)
  23   20 10880 00007FF40C0012A0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  11   21 1089e 00007FF40C003150  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  24   22 1089f 00007FF430003560  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  10   23 108fe 00007FF410001340  1021220 Preemptive  00007FF4545F78D0:00007FF4545F8E98 00000000021F1A50 0     Ukn (Threadpool Worker)
  13   24 10900 00007FF4000012F0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  14   25 1091a 00007FF42C005680  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
   5   26 1091c 00007FF4080012F0  1021220 Preemptive  00007FF4545F9E78:00007FF4545FAE98 00000000021F1A50 0     Ukn (Threadpool Worker)
  18   27 10920 00007FF4340073A0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  12   28 10922 00007FF4180014E0  1021220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  19   29 10923 00007FF3D80009F0  1020220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn (Threadpool Worker)
  34   30 10b0f 00007FF448016C00    21220 Preemptive  0000000000000000:0000000000000000 00000000021F1A50 0     Ukn
   1   31 10b29 00007FF41C0A3140    21220 Preemptive  00007FF454769AF8:00007FF45476B020 00000000021F1A50 0     Ukn
(lldb) clrstack
OS Thread Id: 0x10b29 (1)
        Child SP               IP Call Site
00007FF3E2FFBB10 00007ff4ef4fd688 [PrestubMethodFrame: 00007ff3e2ffbb10] DynamicClass.Go2
00007FF3E2FFCC90 00007ff4ef4fd688 [GCFrame: 00007ff3e2ffcc90]
00007FF3E2FFCD50 00007ff4ef4fd688 [DebuggerU2MCatchHandlerFrame: 00007ff3e2ffcd50]
(lldb) thread list
Process 66894 stopped
* thread #1: tid = 68393, 0x00007ff4ef4fd688 libclrjit.so`SsaBuilder::RenameVariables(JitHashTable<BasicBlock*, JitPtrKeyFuncs<BasicBlock>,
JitHashTable<BasicBlock*, JitPtrKeyFuncs<BasicBlock>, bool, CompAllocator, JitHashTableBehavior>*, CompAllocator, JitHashTableBehavior>*, Ss
aRenameState*) + 1944, name = 'dotnet', stop reason = signal SIGSEGV
  thread #2: tid = 66910, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #3: tid = 67496, 0x00007ff4f52a76d5 libpthread.so.0`__pthread_cond_wait + 197, stop reason = signal SIGSEGV
  thread #4: tid = 66905, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #5: tid = 67868, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #6: tid = 67706, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #7: tid = 66917, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #8: tid = 66916, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #9: tid = 67655, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #10: tid = 67838, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #11: tid = 67742, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #12: tid = 67874, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #13: tid = 67840, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #14: tid = 67866, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #15: tid = 66902, 0x00007ff4f47a6e2d libc.so.6`__GI___poll + 45, stop reason = signal SIGSEGV
  thread #16: tid = 66903, 0x00007ff4f52aac3d libpthread.so.0`__libc_open + 45, stop reason = signal SIGSEGV
  thread #17: tid = 67674, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #18: tid = 67872, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #19: tid = 67875, 0x00007ff4f52a76d5 libpthread.so.0`__pthread_cond_wait + 197, stop reason = signal SIGSEGV
  thread #20: tid = 66914, 0x00007ff4f47b1d43 libc.so.6`__GI_epoll_wait + 51, stop reason = signal SIGSEGV
  thread #21: tid = 66912, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #22: tid = 66915, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #23: tid = 67712, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #24: tid = 67743, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #25: tid = 67692, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #26: tid = 66901, 0x00007ff4f47abc29 libc.so.6`syscall + 25, stop reason = signal SIGSEGV
  thread #27: tid = 66906, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #28: tid = 66900, 0x00007ff4f47abc29 libc.so.6`syscall + 25, stop reason = signal SIGSEGV
  thread #29: tid = 66904, 0x00007ff4f52a76d5 libpthread.so.0`__pthread_cond_wait + 197, stop reason = signal SIGSEGV
  thread #30: tid = 66909, 0x00007ff4f52a76d5 libpthread.so.0`__pthread_cond_wait + 197, stop reason = signal SIGSEGV
  thread #31: tid = 66907, 0x00007ff4f52aa49d libpthread.so.0`__libc_read + 45, stop reason = signal SIGSEGV
  thread #32: tid = 67673, 0x00007ff4f52a76d5 libpthread.so.0`__pthread_cond_wait + 197, stop reason = signal SIGSEGV
  thread #33: tid = 66918, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #34: tid = 68367, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #35: tid = 67693, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #36: tid = 66894, 0x00007ff4f52a76d5 libpthread.so.0`__pthread_cond_wait + 197, stop reason = signal SIGSEGV
  thread #37: tid = 67486, 0x00007ff4f52a7a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
```

Here's another one:

```
(lldb) target create --core "/data/core-dumps/core.dotnet.91043.tsperf-d358.perf.dev.tsi.lan.1557168855"
Core file '/data/core-dumps/core.dotnet.91043.tsperf-d358.perf.dev.tsi.lan.1557168855' (x86_64) was loaded.
(lldb) command source -s 0 '/home/tsi/builder/commands.txt'
Executing commands in '/home/tsi/builder/commands.txt'.
(lldb) plugin load /data/p4/near/workgroup/vqlweb/build/dotnet/shared/Microsoft.NETCore.App/2.2.2/libsosplugin.so
(lldb) pe
There is no current managed exception on this thread
(lldb) clrthreads
ThreadCount:      15
UnstartedThread:  0
BackgroundThread: 14
PendingThread:    0
DeadThread:       0
Hosted Runtime:   no
                                                                                                        Lock
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   4    1 163a3 00000000009F7BA0    20020 Preemptive  00007F3E5039EF88:00007F3E5039EFD0 00000000009E4B20 0     Ukn
  15    2 163be 0000000000A18A80    21220 Preemptive  0000000000000000:0000000000000000 00000000009E4B20 0     Ukn (Finalizer)
  18    3 163c6 00007F3E480009F0  1020220 Preemptive  0000000000000000:0000000000000000 00000000009E4B20 0     Ukn (Threadpool Worker)
   6    4 163cb 0000000000A342D0  1021220 Preemptive  00007F3E502832F8:00007F3E50284FD0 00000000009E4B20 0     Ukn (Threadpool Worker)
  13    5 163cd 00007F3E400012A0  1021220 Preemptive  00007F3E50285418:00007F3E50286FD0 00000000009E4B20 0     Ukn (Threadpool Worker)
   5    6 163ce 00007F3E40003130  1021220 Preemptive  00007F3E502872F0:00007F3E50288FD0 00000000009E4B20 0     Ukn (Threadpool Worker)
  10    7 163cf 00007F3E380012A0  1021220 Preemptive  00007F3E50289428:00007F3E5028AFD0 00000000009E4B20 0     Ukn (Threadpool Worker)
  14    8 163d0 00007F3E3C0012A0  1021220 Preemptive  00007F3E5028B2E8:00007F3E5028CFD0 00000000009E4B20 0     Ukn (Threadpool Worker)
   2    9 163d1 00007F3E300012A0  1021220 Preemptive  00007F3E504E3F68:00007F3E504E4FD0 00000000009E4B20 0     Ukn (Threadpool Worker)
  16   10 163d2 00007F3E340012A0  1021220 Preemptive  00007F3E5028F218:00007F3E50290FD0 00000000009E4B20 0     Ukn (Threadpool Worker)
  21   11 163d3 00007F3E280012A0  1021220 Preemptive  00007F3E5037D510:00007F3E5037F2C0 00000000009E4B20 0     Ukn (Threadpool Worker)
   9   12 166cd 00007F3E300031C0  1021220 Preemptive  0000000000000000:0000000000000000 00000000009E4B20 0     Ukn (Threadpool Worker)
  20   13 166cc 00007F3E38003180  1021220 Preemptive  0000000000000000:0000000000000000 00000000009E4B20 0     Ukn (Threadpool Worker)
  11   14 166ce 00007F3E34003130  1021220 Preemptive  00007F3E5038F310:00007F3E50390FD0 00000000009E4B20 0     Ukn (Threadpool Worker)
   1   15 166cf 00007F3E28003180  1021220 Preemptive  00007F3E5038EB58:00007F3E5038EFD0 00000000009E4B20 0     Ukn (Threadpool Worker)
(lldb) clrstack
OS Thread Id: 0x166cf (1)
        Child SP               IP Call Site
00007F3E4D512210 00007f3eed56db69 [PrestubMethodFrame: 00007f3e4d512210] /data/p4/near/workgroup/vqlweb/build/saltarelle/Cli/Microsoft.CodeA
nalysis.CSharp.dll!Unknown
00007F3E4D512380 00007F3E7A150A87 /data/p4/near/workgroup/vqlweb/build/saltarelle/Cli/Microsoft.CodeAnalysis.CSharp.dll!Unknown
00007F3E4D512430 00007F3E79FC7AAA /data/p4/near/workgroup/vqlweb/build/saltarelle/Cli/Microsoft.CodeAnalysis.CSharp.dll!Unknown
00007F3E4D512460 00007F3E79FC7887 /data/p4/near/workgroup/vqlweb/build/saltarelle/Cli/Microsoft.CodeAnalysis.CSharp.dll!Unknown
00007F3E4D512490 00007F3E79FC734A /data/p4/near/workgroup/vqlweb/build/saltarelle/Cli/Microsoft.CodeAnalysis.CSharp.dll!Unknown
00007F3E4D512570 00007F3E79FC4FE9 /data/p4/near/workgroup/vqlweb/build/saltarelle/Cli/Microsoft.CodeAnalysis.CSharp.dll!Unknown
00007F3E4D5125C0 00007F3E79FB099E /data/p4/near/workgroup/vqlweb/build/saltarelle/Cli/Microsoft.CodeAnalysis.CSharp.dll!Unknown
00007F3E4D512690 00007F3E79FAD017 /data/p4/near/workgroup/vqlweb/build/saltarelle/Cli/Microsoft.CodeAnalysis.CSharp.dll!Unknown
00007F3E4D512CB0 00007f3e79a60060 [DebuggerU2MCatchHandlerFrame: 00007f3e4d512cb0]
(lldb) thread list
Process 91043 stopped
* thread #1: tid = 91855, 0x00007f3eed56db69 libclrjit.so`LinearScan::processBlockStartLocations(BasicBlock*, bool) + 105, name = 'dotnet',
stop reason = signal SIGSEGV
  thread #2: tid = 91089, 0x00007f3ef1cbc9d0 libcoreclr.so`COMDelegate::IsDelegate(MethodTable*), stop reason = signal SIGSEGV
  thread #3: tid = 91064, 0x00007f3ef2874c29 libc.so.6`syscall + 25, stop reason = signal SIGSEGV
  thread #4: tid = 91043, 0x00007f3ef33706d5 libpthread.so.0`__pthread_cond_wait + 197, stop reason = signal SIGSEGV
  thread #5: tid = 91086, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #6: tid = 91083, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #7: tid = 91065, 0x00007f3ef2874c29 libc.so.6`syscall + 25, stop reason = signal SIGSEGV
  thread #8: tid = 91066, 0x00007f3ef286fe2d libc.so.6`__GI___poll + 45, stop reason = signal SIGSEGV
  thread #9: tid = 91853, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #10: tid = 91087, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #11: tid = 91854, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #12: tid = 91068, 0x00007f3ef3373c3d libpthread.so.0`__libc_open + 45, stop reason = signal SIGSEGV
  thread #13: tid = 91085, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #14: tid = 91088, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #15: tid = 91070, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #16: tid = 91090, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #17: tid = 91084, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #18: tid = 91078, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #19: tid = 91069, 0x00007f3ef33706d5 libpthread.so.0`__pthread_cond_wait + 197, stop reason = signal SIGSEGV
  thread #20: tid = 91852, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
  thread #21: tid = 91091, 0x00007f3ef3370a82 libpthread.so.0`__pthread_cond_timedwait + 306, stop reason = signal SIGSEGV
```

My guess: wrong version of some system library? I've verified that I have all of the prerequisites.

I've attached two core dumps, both of which show different stack traces than the ones shown here. If you need more, I've got a bunch. Also, if you're interested you can just drive over to our Kirkland office from your Redmond office and I can show you repros in person. I'll even buy you lunch if you want. :)

* [core.dotnet.66894.1557166562.zip](https://github.com/dotnet/coreclr/files/3149892/core.dotnet.66894.1557166562.zip)
* [core.dotnet.98404.1556062980.zip](https://github.com/dotnet/coreclr/files/3149920/core.dotnet.98404.1556062980.zip)

**Comment by jrockwood** [comment] 2019-05-07 18:56
Could this potentially be the same root issue as this: https://github.com/dotnet/coreclr/issues/6283?

**Comment by RussKeldorph** [comment] 2019-05-08 19:35
@jrockwood #6283 sounds extremely likely since the kernel issues was fixed in RHEL 7.4.

@janvorli @sergiy-k @adityam

**Comment by jrockwood** [comment] 2019-05-08 20:21
Yeah, from what I've seen it's probably the same issue. It might be worthwhile adding a statement to the Wiki page or documentation somewhere that CentOS 7.3 is NOT supported because of the kernel bug. Unless there's something you can do in dotnet that gets around this kernel issue?

**Comment by jrockwood** [comment] 2019-05-08 20:22
Oh, and by the way, I verified that my issue goes away when upgrading to CentOS 7.4.

**Comment by RussKeldorph** [comment] 2019-05-08 20:33
@richlander @leecow Thoughts on the CentOS/RHEL 7.3 (and presumably earlier) warning?

**Comment by janvorli** [comment] 2019-05-09 09:09
I believe there was a way to workaround that issue by disabling transparent huge pages. It can be done using:
```
echo never > /sys/kernel/mm/transparent_hugepage/enabled
```

**Comment by leecow** [comment] 2019-05-10 15:42
Was the kernel bug a regression? We've been testing and running on RHEL/CentOS 7.3 for quite some time. Regardless, it seems like some sort of warning/note would be good. @RussKeldorph, did you have thoughts on where this might go?

**Comment by RussKeldorph** [comment] 2019-05-10 18:07
@leecow I don't know when the bug was introduced or fixed in the Linux kernel or how that window overlaps with RHEL releases other than it was fixed in 7.4.  It's a timing issue that is difficult to repro in most scenarios, so it's not surprising that it has gone largely unnoticed; there may be scenarios where it is never encountered even without the workaround applied.

> did you have thoughts on where this might go?

Nope.  I was hoping you or @richlander did if you agreed it was worth noting.

**Comment by jrockwood** [comment] 2019-05-14 00:47
By the way, I verified that the workaround with disabling transparent huge pages does indeed fix the issue. Thanks for all of the help!

**Comment by RussKeldorph** [comment] 2019-06-03 15:48
@richlander @leecow @janvorli Ping.  Is it reasonable to just leave this issue and #6283 as landmarks for others to discover this issue, or should we note it along with @janvorli's workaround formally somewhere?

**Comment by RussKeldorph** [comment] 2019-06-14 17:38
Assuming that it is reasonable to leave this issue as documentation.

**Closed by RussKeldorph** 2019-06-14 17:38 UTC
