### ISSUE TITLE
[arm64] Test failed: baseservices_threading._generics_TimerCallback_thread03_thread03_._generics_TimerCallback_thread03_thread03_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22366] opened 2019-02-02 01:15 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_ubuntu16.04_r2r_tst/23/

**Failed tests:**
baseservices_threading._generics_TimerCallback_thread03_thread03_._generics_TimerCallback_thread03_thread03_sh

**Log:**
```
baseservices_threading._generics_TimerCallback_thread03_thread03_._generics_TimerCallback_thread03_thread03_sh [FAIL]
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04/bin/tests/Linux.arm64.Release/TestWrappers/baseservices.threading/baseservices.threading.XUnitWrapper.cs(7739,0): at baseservices_threading._generics_TimerCallback_thread03_thread03_._generics_TimerCallback_thread03_thread03_sh()
```

**Comment by BruceForstall** [comment] 2019-02-03 03:39
Maybe this is a more full log:
```
22:50:36         /n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/baseservices/threading/Reports/baseservices.threading/generics/TimerCallback/thread03/thread03.output.txt/nRaw output:/nTest Harness Exitcode is : 137
22:50:36         /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/baseservices/threading/generics/TimerCallback/thread03/thread03.sh/n
22:50:36         Expected: True
22:50:36         Actual:   False
22:50:36 
      baseservices_threading._generics_TimerCallback_thread03_thread03_._generics_TimerCallback_thread03_thread03_sh [FAIL]
22:50:36         Stack Trace:
22:50:36           /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04/bin/tests/Linux.arm64.Release/TestWrappers/baseservices.threading/baseservices.threading.XUnitWrapper.cs(7739,0): at baseservices_threading._generics_TimerCallback_thread03_thread03_._generics_TimerCallback_thread03_thread03_sh()
22:50:36 EXEC : dlopen failed to open the libcoreclr.so with error librt.so.1: failed to map segment from shared object [/home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/tests/runtest.proj]
```


The "dlopen" failure is interesting.

**Comment by RussKeldorph** [comment] 2019-04-02 23:28
Didn't repro in https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_ubuntu16.04_r2r_tst/30/

**Comment by VSadov** [comment] 2019-04-03 17:29
I am re-running the test in a loop in two sessions on the same machine. Let's see if there are any repros.

**Comment by VSadov** [comment] 2019-04-03 22:03
The test was re-running for hours without a single repro. Closing.

**Comment by RussKeldorph** [comment] 2019-04-03 22:45
@VSadov Note that the job is r2r (ReadyToRun).  Did you make sure the framework assemblies and test were crossgened when you were trying to repro?

**Comment by VSadov** [comment] 2019-04-03 22:47
Hmm, I did not notice that. Will have to reopen then.

**Comment by RussKeldorph** [comment] 2019-04-03 22:50
@VSadov Check the build log for the sequence of commands used to repro.  It's not pretty right now, but runtest.py should have the logic to get the framework crossgen'd, and setting `RunCrossGen` in the environment should get the test itself crossgen'd.

**Comment by VSadov** [comment] 2019-04-03 23:46
re-running with a crossgenned version.

**Comment by VSadov** [comment] 2019-04-04 00:35
passed 5000x2 times.

**Closed by VSadov** 2019-04-04 00:35 UTC
Labels: arch-arm64, blocking-3.0-preview-5, os-linux

**Comment by VSadov** [comment] 2019-04-04 00:42
Return code:      137    points that it was likely caused by OOM. 
And most likely it is due too many tests running in a too small environment at once, especially if some perform crossgen. 
There is an issues for that - https://github.com/dotnet/coreclr/issues/22010

Still wanted to be sure it is not a separate bug or a test issue. - Just in case since this involves threading and some such tests did have problems in the past.
