### ISSUE TITLE
UnmanagedMemoryStream on 32bit Linux

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#11199] opened 2017-04-25 07:51 UTC
In UnmanagedMemoryStream, besides of Initialize , `Position` can be set to `Int32_MaxValue`.
```
stream.Position = int.MaxValue;
```
[corefx:UmsWrite.cs#L115](https://github.com/dotnet/corefx/blob/master/src/System.IO.UnmanagedMemoryStream/tests/UmsWrite.cs#L115)

In Linux, user allocated memory address can be up to 0xBFFFFFFF while Win32 0x7FFFFFFF (as far as I know). So, wrap around check in `Position` can happen with normal case.
```
if (value > (long) Int32.MaxValue || _mem + value < _mem)
```
[UnmanagedMemoryStream.cs#L305](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/UnmanagedMemoryStream.cs#L305)

As of result, somethimes, unit test fails,
```
   System.IO.Tests.UmsWriteTests.CannotWriteWithOverflow [FAIL]
      System.ArgumentOutOfRangeException : Stream length must be non-negative and less than 2^31 - 1 - origin.
      Parameter name: value
      Stack Trace:
            at System.IO.UnmanagedMemoryStream.set_Position(Int64 value)
            at System.IO.Tests.UmsWriteTests.CannotWriteWithOverflow()
```

**Comment by seanshpark** [comment] 2017-04-25 08:09
@jkotas , could you please give some advice on how to solve this issue?

**Comment by mikedn** [comment] 2017-04-25 08:14
> In Linux, user allocated memory address can be up to 0xBFFFFFFF while Win32 0x7FFFFFFF (as far as I know).

By default 32 bit Windows reserves 2GB for user mode but it is possible to configure it (and the application) to reserve 3GB for user mode. Also, 32 bit processes running on 64 bit Windows can get up to 4GB of user mode address space.

If the test passes on Windows it's because we're lucky or because the .NET Core host process isn't large address aware.

**Comment by seanshpark** [comment] 2017-04-25 08:17
@mikedn , thank you. I've found this; https://msdn.microsoft.com/en-us/library/windows/desktop/aa366912(v=vs.85).aspx . I think it's `Windows with 4GT`

**Comment by mikedn** [comment] 2017-04-25 08:28
Yes, Windows with 4GT also known as 3GB from the old boot.ini option. See also [memory limits](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366778(v=vs.85).aspx#memory_limits) where it states that 32 bit apps running on 64 bit Windows can get 4GB of user address space if the  IMAGE_FILE_LARGE_ADDRESS_AWARE flag is set in the executable header.

**Comment by jkotas** [comment] 2017-04-25 15:45
Right, this is problem on both Windows and Unix. It relatively rare to hit it on Windows because of it requires the large address space to be enabled and memory to be allocated at high address.

The implementation and tests should be fixed to be compatible with 4GB address space on 32-bit platforms. It should be pretty straightforward.

**Comment by seanshpark** [comment] 2017-04-26 02:12
@jkotas , thank you. thank you for the comment. I'll get to this when I figure out how to solve. If anyone gets it before me, it's fine.

**Comment by gkhanna79** [comment] 2017-04-26 05:15
CC @danmosemsft

**Comment by danmosemsft** [comment] 2017-04-26 15:53
Clearing milestone so @ianhays can triage this.

**Comment by ianhays** [comment] 2017-04-26 18:44
> Clearing milestone so @ianhays can triage this.

> I'll get to this when I figure out how to solve. 

>It should be pretty straightforward.

Don't we just want to increase the min value that the wraparound check considers to be invalid i.e. from Int32.MaxValue to uint.MaxValue?

Unless we have some way of detecting the real max address to use instead?

**Comment by danmosemsft** [comment] 2017-05-03 05:29
Putting in 2.0 for now as test is failing.

**Comment by gkhanna79** [comment] 2017-05-03 13:31
@jkotas Is the right fix to mark the host with LARGEADDRESSAWARE?

**Comment by jkotas** [comment] 2017-05-03 14:51
This bug only repos on 32-bit Unix or on 32-bit Windows in LARGEADDRESSAWARE process.

Marking the dotnet host LARGEADDRESSAWARE is not going to fix this bug. Quite the opposite - it will make this bug repro even on Windows with the dotnet host. Marking the dotnet host LARGEADDRESSAWARE maybe still a good idea but it is orthogonal to this issue.

**Comment by ianhays** [comment] 2017-05-03 20:07
@jkotas am I oversimplifying the issue in my assumed solution above?

**Comment by jkotas** [comment] 2017-05-03 21:45
> wraparound check considers to be invalid i.e. from Int32.MaxValue to uint.MaxValue?

@ianhays I believe that removing the offending BIT64-specific wraparound check would be more consistent with the rest of the implementation . It does not seem to be protecting against anything interesting. For example, Seek lets you go as much as you want beyond end of the stream without any 32-bit wraparound check and the rest of the implementation deals with the situation fine.

However, there seems to be other places with wrong wraparound checks: UnmanagedMemStreamMaxLength:long is compared with Int64.MaxValue in several places. The result of this comparison will always be false that does not seem to be what was intended. For example, you can set UnmanagedMemoryStream to report negative position on x64:

```
static void Main()
{
     byte p;
     var ums = new UnmanagedMemoryStream(&p, 1);
     ums.PositionPointer = (byte*)UInt64.MaxValue;
     Console.WriteLine(ums.Position.ToString()); // Position is negative?!?!
}
```

Other places in the implementation protect against negative position.

**Comment by ianhays** [comment] 2017-05-03 21:57
>I believe that removing the offending **BIT64-specific** wraparound check would be more consistent with the rest of the implementation

[! BIT64-specific, yes?](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/UnmanagedMemoryStream.cs#L305)

> The result of this comparison will always be false that does not seem to be what was intended. For example, you can set UnmanagedMemoryStream to report negative position on x64:

Ah yeah, [it converts the value to an int64 before checking that it is less than or equal to int64.maxvalue](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IO/UnmanagedMemoryStream.cs#L339), which it must always be.

**Comment by jkotas** [comment] 2017-05-03 22:07
> ! BIT64-specific, yes?

Right.

**Closed** 2017-05-04 22:01 UTC
Labels: area-System.IO, bug
