### ISSUE TITLE
TimeZoneId not consistent across operating systems

### ISSUE THREAD

**Issue by Bhaal22** [dotnet/coreclr#13008] opened 2017-07-24 20:24 UTC
- 2.0.0-preview2-006497

This fragment works perfectly on Windows operating Systems
```
using System;

namespace tz
{
    class Program
    {
        static void Main(string[] args)
        {
            var timeZoneId = "Eastern Standard Time";
            TimeZoneInfo timezoneinfo1 = TimeZoneInfo.FindSystemTimeZoneById(timeZoneId);
            var display = timezoneinfo1.DisplayName;

            Console.WriteLine(display);
        }
    }
}
```

And fail on my linux operating system:

```
john@kona$ dotnet run

Unhandled Exception: System.TimeZoneNotFoundException: The time zone ID 'Eastern Standard Time' was not found on the local computer. ---> System.IO.FileNotFoundException: Could not find file '/usr/share/zoneinfo/Eastern Standard Time'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytes(String path)
   at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(String id, TimeZoneInfo& value, Exception& e)
   --- End of inner exception stack trace ---
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at tz.Program.Main(String[] args) in /tmp/tz/Program.cs:line 10
```

To Fix it:
```
var timeZoneId = "EST";
```

And of course, this version fails on windows.
It looks like we cannot really have portable code accross operating systems for the TimeZoneIds

**Comment by tarekgh** [comment] 2017-07-24 23:27
Duplicate of https://github.com/dotnet/corefx/issues/2538

We are tracking this in the future work.

**Closed by tarekgh** 2017-07-24 23:27 UTC
Labels: area-System.Globalization

**Comment by Bhaal22** [comment] 2017-07-25 09:11
Thank you @tarekgh

**Comment by mj1856** [comment] 2017-07-26 19:01
@Bhaal22 - as a workaround, consider my [https://github.com/mj1856/TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter) library.  It's tiny, and will handle the conversions for you.  Thanks.
