### ISSUE TITLE
Some managed tests failing with "terminate called without an active exception" message

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#631] opened 2015-04-03 13:50 UTC
@janvorli is investigating; it seems as though exceptions on secondary threads aren't getting caught and dumped by the runtime.  This currently happens with the System.Numerics.Vectors.Tests project.

**Comment by janvorli** [comment] 2015-04-08 10:16
I've looked more into the issue. The problem is different from what it seemed from the first look. The real issue is that `HandleHardwareException` doesn't actually throw an exception, but it calls directly the `DispatchManagedException`. In case the exception propagation crosses managed to native boundary, the exception dispatching code uses `throw;` to unwind the native frames. But in this particular case, there was no exception thrown and so the rethrow aborts.
The fix is to add try / catch to the HandleHardwareException that throws the PAL_SEHException that it got as a parameter, catches it right away and then calls the `DispatchManagedException` from the catch handler.

**Comment by janvorli** [comment] 2015-04-09 00:24
Fixed by #663

**Closed by janvorli** 2015-04-09 00:24 UTC
Labels: bug, Linux
