### ISSUE TITLE
Optimize Span.Copy and Span.TryCopyTo

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#15076] opened 2017-11-17 18:01 UTC
From https://github.com/dotnet/coreclr/pull/15069#discussion_r151746531 :

ReadOnlySpan.TryCopyTo is ~9.9%, but the Buffer.Memmove it's using for the actual copy is ~3.9%, so there's 6% in there that going to something other than the actual copy (the trace shows ~2.6% in the ReadOnlySpan.TryCopyTo body and ~3.4% in the Span.CopyTo body that TryCopyTo calls). If we're looking to optimize for such percentages, I'd prefer to see us start by looking at making TryCopyTo faster, as that'll accrue to many other scenarios.

**Comment by jkotas** [comment] 2017-11-17 18:03
cc @ahsonkhan @KrzysztofCwalina

**Comment by GrabYourPitchforks** [comment] 2018-01-18 22:23
My current thinking is to make an API `Buffer.Memmove(ref byte dest, ref byte src, nuint len)` that's a sister to `Buffer.Memmove(byte* dest, byte* src, nuint len)`. This moves the pinning logic (and the associated stack setup overhead) from the caller to the p/invoke itself, so it effectively defers this logic until it's absolutely necessary.

Initial testing is promising. It appears to result in +65% throughput for small spans (< 64 bytes or so), with diminishing returns for longer spans. Even for 200-byte spans or so it's still around a +15% improvement. (The baseline is the existing `Span.TryCopyTo` code.)

**Comment by stephentoub** [comment] 2018-01-19 17:31
> My current thinking is to make an API Buffer.Memmove(ref byte dest, ref byte src, nuint len)

We could do that with little risk for fast span just by having this be an internal API, right?

**Comment by GrabYourPitchforks** [comment] 2018-01-19 19:19
Yes; however, this optimization uses the same `ByReference<T>` trick under the covers described [here](https://github.com/dotnet/corefx/pull/26381#issuecomment-358852586). And as [Jan points out](https://github.com/dotnet/corefx/pull/26381#issuecomment-358854710), this isn't really the scenario `ByReference<T>` was intended for, so there's some nervousness as to whether it's reliable enough for this.

I expect to have perf numbers within an hour or so.

**Comment by GrabYourPitchforks** [comment] 2018-01-20 02:18
Test application below. My build issues are now fixed and results are coming in.

```csharp
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

class Program
{
    static void Main(string[] args)
    {
        const int ITER_COUNT = 250_000_000;

        Span<byte> src = GetArray<byte>(64);
        Span<byte> dest = new byte[32 * 1024];

        Stopwatch sw = new Stopwatch();
        while (true)
        {
            sw.Restart();
            for (int i = 0; i < ITER_COUNT; i++)
            {
                // Codegen may inline the TryCopyTo method, but manual inspection
                // shows it's not "cheating" e.g. by only comparing the source and
                // destination lengths once then skipping the comparison on
                // subsequent loop iterations.
                if (!src.TryCopyTo(dest))
                {
                    return;
                }
            }

            // Console.WriteLine(sw.Elapsed);
            // Console.WriteLine is currently misbehaving on my build, so this is a workaround.

            foreach (var ch in sw.ElapsedMilliseconds.ToString())
            {
                Console.Write(ch);
            }
            Console.Write('\r');
            Console.Write('\n');
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static T[] GetArray<T>(int len)
    {
        return new T[len];
    }
}
```

**Comment by GrabYourPitchforks** [comment] 2018-01-20 03:02
Perf measurements below. These measurements are for `Span<T>.TryCopyTo`, but similar measurements were found for `ReadOnlySpan<T>.TryCopyTo`.

Before and after times are in milliseconds and are for 250 million iterations of the inner test loop as described earlier. Test machine is Win10 x64 FCU. _Before_ is the average time taken for each test battery co complete before the code in the PR is applied; _After_ the code in the PR is applied. _Difference_ is the percentage difference in time taken (lower is better). _Throughput_ is the reciprocol of the difference and is the percentage improvement in calls per second (higher is better).

||Before (ms)|After (ms)|Difference|Throughput|
|---|---|---|---|---|
|4-byte span|1,823.94|1,138.45|-38%|+60%|
|64-byte span|1,789.90|1,038.81|-42%|+72%|
|256-byte span|4,406.38|3,722.88|-16%|+18%|
|64-object span|4,944.33|4,288.00|-13%|+15%|

Due to the way _Memmove_'s checks are ordered copying smaller-byte spans may be slightly slower than copying longer-byte spans, and this is reflected in the above tests. (I'm not considering changing this behavior as part of this investigation.)

As expected, the proposed changes show significant gains for smaller blittable spans with diminishing returns for longer blittable spans or spans of non-blittable types.

**Closed** 2018-01-27 06:38 UTC
Labels: area-System.Memory, enhancement, tenet-performance, up-for-grabs
