### ISSUE TITLE
[Arm64] DevDiv_359736 test failures: No Exception thrown

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10111] opened 2017-03-11 01:07 UTC
Tests

<pre>
jit\Regression\JitBlue\DevDiv_359736\DevDiv_359736_do\DevDiv_359736_do.cmd
JIT\Regression\JitBlue\DevDiv_359736\DevDiv_359736_ro\DevDiv_359736_ro.cmd
</pre>

Expected Output:

<pre>
BEGIN EXECUTION
 "C:\Users\DDJOIN\proyectos\febrero-2-2017\pruevas\tests2\Core_Root\corerun.exe" DevDiv_359736_do.exe
FAILED: No exception thrown
Expected: 100
Actual: -1
END EXECUTION - FAILED
FAILED
</pre>
category:correctness
theme:cse
skill-level:intermediate
cost:small

**Comment by mikedn** [comment] 2017-03-11 07:14
Likely a duplicate of #8648

**Comment by BruceForstall** [comment] 2018-06-09 01:32
These tests still fail.

**Comment by BruceForstall** [comment] 2018-10-09 21:10
@briansull Should this be fixed now? If so, can you submit a PR that removes
```
<ExcludeList Include="$(XunitTestBinBase)/JIT/Regression/JitBlue/DevDiv_359736/**">
    <Issue>8648</Issue>
</ExcludeList>
```
from issues.targets?

(and close this issue)

**Comment by briansull** [comment] 2018-10-10 22:36
I verified that these tests now pass on Arm64 hardware

**Comment by briansull** [comment] 2018-10-10 22:37
Test has been Enabled with #20347

**Closed** 2018-10-10 22:37 UTC
Labels: arch-arm64, area-CodeGen, bug
