### ISSUE TITLE
[JitStressRegs=1] Attempt to access destroyed handle. && *(_UNCHECKED_OBJECTREF *)handle != DEBUG_DestroyedHandleValue

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2671] opened 2016-01-14 23:15 UTC
**System.Net.Sockets.APMServer.Tests** fails on Linux with COMPlus_JitStressRegs=1

**Configurations**

Linux
Coreclr checked build
Corefx release build

**Assertion details**

Pass without COMPlus_JitStressRegs=1

Assert failure(PID 7264 [0x00001c60], Thread: 7458 [0x1d22]): "Attempt to access destroyed handle." && *(_UNCHECKED_OBJECTREF *)handle != DEBUG_DestroyedHandleValue
    File: /home/sejooh/workspaces/origin/coreclr/src/gc/handletable.h Line: 195
    Image: /home/sejooh/workspaces/origin/corefx/bin/tests/Linux.AnyCPU.Release/System.Net.Sockets.APMServer.Tests/dnxcore50/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 7264, Thread 7458/0x1d22)' ****
  "Attempt to access destroyed handle." && *(_UNCHECKED_OBJECTREF *)handle != DEBUG_DestroyedHandleValue

**Comment by sejongoh** [comment] 2016-01-14 23:17
I synced to the following commits:

Coreclr: 761fa468d2fb09d00044fa1848b884b657191876  (Wed Jan 13 18:15:58 2016 -0500)
Corefx: 0824d9745687271503f7538d16f44f17f5ef5f18 (Tue Jan 12 14:49:52 2016 -0800)

**Comment by hoyMS** [comment] 2016-01-19 22:34
COMPlus_JitStress=2

**Comment by hoyMS** [comment] 2016-01-19 22:57
This is duplicate of  #2380 .

**Closed by hoyMS** 2016-01-19 22:57 UTC
Labels: bug, CodeGen, Linux
