### ISSUE TITLE
Truncation during `stloc` also affects duplicated value

### ISSUE THREAD

**Issue by dgrunwald** [dotnet/coreclr#14784] opened 2017-11-01 00:31 UTC
IL code ([full program](https://gist.github.com/dgrunwald/b0ca8412cd0ce4ebd1ad202427886129)):

```
  .method public static void InlineAssignByte()
  {
    .locals init (
      int8 local
    )
    ldstr "InlineAssignByte: WriteLine(local = {0})"
    ldc.i4 300
    dup
    stloc.0
    box int32
    call void [mscorlib]System.Console::WriteLine(string, object)
    ldstr "InlineAssignByte: local is {0}"
    ldloc.0
    box int32
    call void [mscorlib]System.Console::WriteLine(string, object)
    ret
  }
```

With `COMPLUS_useLegacyJit=1`, I get the output I expect:
```
InlineAssignByte: WriteLine(local = 300)
InlineAssignByte: local is 44
```

Output with RyuJit:
```
InlineAssignByte: WriteLine(local = 44)
InlineAssignByte: local is 44
```

Somehow the implicit truncation in the `stloc` got moved in front of the `dup`???

Context: I found this while trying to write a failing testcase for ILSpy, which incorrectly(?) transforms the above IL into:
```
public static void InlineAssignByte()
{
	sbyte b;
	Console.WriteLine("InlineAssignByte: WriteLine(local = {0})", (int)(b = (sbyte)300));
	Console.WriteLine("InlineAssignByte: local is {0}", (int)b);
}
```
Looks like RyuJit has a similar bug?

**Comment by mikedn** [comment] 2017-11-01 05:34
> Output with RyuJit:
InlineAssignByte: WriteLine(local = 44)
InlineAssignByte: local is 44

I'm unable to reproduce this with the current RyuJIT build. However, I did get this result when running the exe using .NET 4.7.1 x86. The generated code is:
```asm
00000000  push        ebp 
00000001  mov         ebp,esp 
00000003  mov         ecx,6CB61974h 
00000008  call        FE332C8C 
0000000d  mov         edx,eax 
0000000f  mov         ecx,dword ptr ds:[060622ECh] 
00000015  mov         dword ptr [edx+4],2Ch 
0000001c  call        67CA63F4 
00000021  mov         ecx,6CB61974h 
00000026  call        FE332C8C 
0000002b  mov         edx,eax 
0000002d  mov         ecx,dword ptr ds:[060622F0h] 
00000033  mov         dword ptr [edx+4],2Ch 
0000003a  call        67CA63F4 
0000003f  pop         ebp 
00000040  ret 
```

**Comment by mikedn** [comment] 2017-11-01 05:56
It's possible that this was fixed in #9959 by @AndyAyersMS

**Comment by AndyAyersMS** [comment] 2017-11-01 17:32
Interesting. `dup` has been something of a troublemaker lately.

@dgrunwald thanks for running across these, and please keep them coming.

Jit32 has the same kind of `dup` handling that RyuJit had before my change, so not surprising that it has this bug.

RyuJit fixes should be there in Core2.0 and Desktop 4.7.1.

**Comment by mikedn** [comment] 2017-11-01 17:45
Perhaps a test should be added for this?

**Comment by AndyAyersMS** [comment] 2017-11-01 19:40
@dgrunwald any objections to me adding this as test?

**Comment by dgrunwald** [comment] 2017-11-01 19:42
@AndyAyersMS No objections.

**Comment by RussKeldorph** [comment] 2017-11-16 01:31
Can this be closed since it doesn't repro in .NET Core?

**Closed** 2017-11-16 18:15 UTC
Labels: area-CodeGen, bug
