### ISSUE TITLE
Silent Build failure in x86 test test build

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#6784] opened 2016-08-18 02:30 UTC
So far this is not impacting the test run. The error is like
 in 
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x86_lb_checked_windows_nt_prtest/3043/consoleFull

```
RUNTEST: Invoking msbuild
18:43:24   
18:43:24   Errors in D:\j\workspace\x86_lb_checke---9877589b\tests\\..\bin\tests\tempRestoreProject\project.json
18:43:24       Package xunit.runner.msbuild 2.1.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package xunit.runner.msbuild 2.1.0 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
18:43:24       One or more packages are incompatible with .NETFramework,Version=v4.5.
18:43:25   Desktop.Coreclr.TestWrapper -> D:\j\workspace\x86_lb_checke---9877589b\bin\tests\Windows_NT.x86.Checked\Common\Desktop.Coreclr.TestWrapper\Desktop.Coreclr.TestWrapper\Coreclr.TestWrapper.dll
```

**Comment by ramarag** [comment] 2016-08-18 02:32
@dagood  can you take a look at it ?

**Comment by dagood** [comment] 2016-08-18 14:38
As long as this is silent, it's working as intended. (An incompatibility error doesn't prevent things from using the package.) This error has failed CI at least a few times recently, though, tracked by https://github.com/dotnet/coreclr/issues/6716. I'll quickly see if it's feasible to do a simple upgrade to fix this, and if it doesn't seem to work (and I don't submit a PR) I'll update on #6716.

/cc @jasonwilliams200OK

**Comment by gkhanna79** [comment] 2017-04-26 17:42
@dagood Should this move to Future if not actionable for 2.0?

**Comment by dagood** [comment] 2017-05-02 22:48
The fix for https://github.com/dotnet/coreclr/issues/6716 (https://github.com/dotnet/coreclr/pull/6791) made this silent error stop happening. I also don't see it in recent CI logs. Closing as resolved.

**Closed by dagood** 2017-05-02 22:48 UTC
Labels: area-Build, test bug
