### ISSUE TITLE
[Linux/arm32/arm64] gcServer+heapverify1 GC/Scenarios/Dynamo/dynamo fails

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17129] opened 2018-03-22 18:37 UTC
`GC/Scenarios/Dynamo/dynamo/dynamo.sh` fails with configuration gcServer_heapverify1

```
corerun dynamo.exe 1000 40 191919
 
Total amount of RandomNode Memory: 
12487500
 
Running Finalize Test...
 
Deleting Node:
0
Deleting Node:
19
The registered number: 50
The analyzed number: 44
The registered number and analyzed number are not equal

Test Failed with seed: 191919
Expected: 100
Actual: 1
```

@dotnet/arm64-contrib @Maoni0 @sywhang @swgillespie FYI

**Comment by Maoni0** [comment] 2018-03-22 23:11
@sywhang could you please take a look?

**Comment by sywhang** [comment] 2018-03-22 23:15
I've been trying to get a repro  on this but can't really get any repro. @sdmaclea  Is there any other envvars you set other than gcServer_heapverify?

**Comment by sdmaclea** [comment] 2018-03-22 23:19
My apologies, I add COMPlus_GCgen0size=0x100000 to all my GCServer runs during CI.  
```
export COMPlus_HeapVerify=1
export COMPlus_gcServer=1
export COMPlus_GCgen0size=0x100000
```

This occurs during CI, so many other jobs are running.  Perhaps the OOM is cause by another test?

**Comment by sdmaclea** [comment] 2018-03-22 23:20
It did occur two nights in a row in my internal CI

**Comment by sdmaclea** [comment] 2018-03-22 23:21
Is there a set of GC jobs which should only be run sequentially?

**Comment by sywhang** [comment] 2018-03-23 17:14
I have set the environment variables the way you set it, but I can't reproduce this behavior.
```
➜  coreclr git:(master) export COMPlus_GCgen0size=0x100000
➜  coreclr git:(master) export COMPlus_gcServer=1         
➜  coreclr git:(master) export COMPlus_HeapVerify=1       
➜  coreclr git:(master) bash /home/suwhang/repos/coreclr/bin/tests/Linux.x64.Debug/GC/Scenarios/Dynamo/dynamo/dynamo.sh -coreroot=/home/suwhang/repos/coreclr/bin/tests/Linux.x64.Debug/Tests/Core_Root
BEGIN EXECUTION
/home/suwhang/repos/coreclr3/bin/tests/Linux.x64.Debug/Tests/Core_Root/corerun dynamo.exe 1000 40 191919
 
Total amount of RandomNode Memory: 
12487500
 
Running Finalize Test...
 
Deleting Node:
0
Deleting Node:
19
Deleting Node:
10
Deleting Node:
4

Test Passed with seed: 191919
Expected: 100
Actual: 100
END EXECUTION - PASSED
```

However, I only have tried this on Linux on x64, so perhaps this is an ARM64 specific issue... I don't think it has to do with running tests sequentially either because I ran this test on its own like shown above. I'll see if I can get my hands on any ARM64 machines.

**Comment by janvorli** [comment] 2019-01-08 10:02
I've just seen the same failure in PR on ARM32:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/8956/
```
23:39:02         /n/nReturn code:      1/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/GC/Scenarios/Reports/GC.Scenarios/Dynamo/dynamo/dynamo.output.txt/nRaw output:/nBEGIN EXECUTION
23:39:02         /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun dynamo.exe 1000 40 191919
23:39:02 
23:39:02         Total amount of RandomNode Memory: 
23:39:02         12487500
23:39:02          
23:39:02         Running Finalize Test...
23:39:02          
23:39:02         Deleting Node:
23:39:03         0
23:39:03         Deleting Node:
23:39:03         19
23:39:03         Deleting Node:
23:39:03         10
23:39:03         The registered number: 50
23:39:03         The analyzed number: 35
23:39:03         The registered number and analyzed number are not equal
23:39:03         
23:39:03         Test Failed with seed: 191919
23:39:03         Expected: 100
23:39:03         Actual: 1
23:39:03         END EXECUTION - FAILED
23:39:03         Test Harness Exitcode is : 1
```

**Comment by BruceForstall** [comment] 2019-01-08 17:50
@Maoni0 Looks like this GC failure has happened several times recently, on Ubuntu arm32

**Comment by Maoni0** [comment] 2019-01-08 20:47
is arm32 the only arch we've seen this failure on? if so could I please get an arm32 machine to debug on?

**Comment by sdmaclea** [comment] 2019-01-08 20:49
This bug was reported because a year ago it was happening on linux-arm64 too.

**Comment by Maoni0** [comment] 2019-01-08 20:52
@sdmaclea understood. I am more interested in what it's been reproing on lately and the most often on. are you seeing it repro on arm64 currently?

**Comment by sdmaclea** [comment] 2019-01-08 20:55
@Maoni0 I haven't run arm64 since I started at MS.

**Comment by AndyAyersMS** [comment] 2019-01-09 00:41
Another instance here: https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_tst_prtest/7396/

**Comment by echesakovMSFT** [comment] 2019-01-09 23:17
Failed in https://github.com/dotnet/coreclr/pull/21816 as well

**Comment by Maoni0** [comment] 2019-01-10 00:16
the earliest I can look at this is about a week from now. for the time being can we just disable this test. this is highly unlikely due to GC anyway; most likely due to the timing of lifetime reporting and the test isn't robust enough to accommodate it.

**Comment by RussKeldorph** [comment] 2019-01-10 21:35
This is causing a number of spurious CI failures.  @Maoni0 can you disable this test in the interim or get someone to?

/cc @vancem

**Comment by vancem** [comment] 2019-01-10 21:43
Just FYI, the spurious failure rate is substantial (e.g. ~ 50%).  

@MattGal said that he would pull one of the machines on which it failed out of rotation so it could be investigated.    He can add the information here.

**Comment by Maoni0** [comment] 2019-04-03 21:02
I'm gonna close this - this is a very low value test and I don't think it was likely due to the GC.

**Closed by Maoni0** 2019-04-03 21:02 UTC
Labels: arch-arm32, arch-arm64, area-GC, blocking-3.0-preview-5

**Comment by BruceForstall** [comment] 2019-04-03 21:11
@Maoni0 The test is disabled for all Linux/arm32/arm64 runs, but enabled elsewhere. Is that how you would like to leave it? It wasn't clear to me from your comment above if perhaps you thought it should be deleted for all platforms.

**Comment by Maoni0** [comment] 2019-04-03 21:17
@BruceForstall I would not be opposed to disabling/deleting it everywhere.
