### ISSUE TITLE
Support for ASP.Net core functionality in UWP project

### ISSUE THREAD

**Issue by wind-rider** [dotnet/coreclr#13146] opened 2017-08-01 16:28 UTC
I would like to host an ASP.Net core server in a UWP project, more specifically - I would like to host a REST service in a Background App on Windows IoT Core.

This would give 2 benefits:

- allows hardware to be disclosed as a REST service
- allows a website or REST service to be managed by the operating system on Windows IoT core (so that you can start / stop it like any other app)

I'm not sure whether this is the right repo since it relates to both ASP.Net Core and UWP.

**Comment by jkotas** [comment] 2017-08-02 09:41
This belongs to ASP.NET repos. https://github.com/aspnet/Home/issues/1531 is duplicate of this issue.

cc @davidfowl @DamianEdwards

**Closed by jkotas** 2017-08-02 09:41 UTC

**Comment by wind-rider** [comment] 2017-08-02 10:45
@jkotas I don't think that https://github.com/aspnet/Home/issues/1531 is a 1:1 duplicate. My question was broader - to allow an ASP.Net Core webserver to be hosted in UWP apps. The Windows IoT Core usecase is an example of what you could do with that.

Other usecases could be to temporarily run a website when running an UWP app, e.g. to upload photos from a phone to use in that app.

**Comment by los93sol** [comment] 2018-06-16 17:55
@wind-rider, this is possible and I have a working example of it in my GitHub

**Comment by wind-rider** [comment] 2018-06-16 18:59
Sounds good! Thank you for pointing me at it, I’ll have a look

________________________________

**Comment by wind-rider** [comment] 2018-06-16 19:00
Would still be nice if this would be officially supported by Microsoft though

________________________________

**Comment by los93sol** [comment] 2018-06-16 19:59
I fully agree, I had to get deep into the weeds to get it to work

**Comment by litehead** [comment] 2019-06-06 12:26
I tried solution from @los93sol recently but it only worked in Debug mode. In release there are some unresolved DllImports which most likely prevents web server from running correctly
