### ISSUE TITLE
Assembly.Load does not work in custom load context

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#22812] opened 2019-02-23 09:24 UTC
I have 2 applications, ConsoleApp25 and ConsoleApp1. ConsoleApp1 is the plugin loaded into ConsoleApp25. If ConsoleApp1 calls Assembly.Load, we never seem to call back into the custom load context, it just fails (likely because it's trying to use the default). I expect Assembly.Load to be equivalent to  `AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly()).LoadFromAssemblyName` but it looks like that's not the case.

**ConsoleApp25**

```C#
using System;
using System.IO;
using System.Reflection;
using System.Runtime.Loader;

namespace ConsoleApp25
{
    public class Program
    {
        static void Main(string[] args)
        {
            var context = new AppLoadContext(@"..\..\..\..\ConsoleApp1\bin\Debug\netcoreapp3.0\ConsoleApp1.dll");
            var asm = context.LoadFromAssemblyName(new AssemblyName("ConsoleApp1"));

            var executeMethodInfo = asm.GetType("ConsoleApp1.Program").GetMethod("Execute", BindingFlags.Public | BindingFlags.Static);
            var execute = (Action)Delegate.CreateDelegate(typeof(Action), executeMethodInfo);

            execute();
        }
    }

    internal class AppLoadContext : AssemblyLoadContext
    {
        private readonly AssemblyDependencyResolver _resolver;

        public AppLoadContext(string path) :
            base(isCollectible: true)
        {
            _resolver = new AssemblyDependencyResolver(path);
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            var path = _resolver.ResolveAssemblyToPath(assemblyName);
            if (path != null)
            {
                return LoadFromAssemblyPath(path);
            }

            return null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            var path = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            if (path != null)
            {
                return LoadUnmanagedDllFromPath(path);
            }

            return IntPtr.Zero;
        }
    }
}
```

**ConsoleApp1**

```C#
using System;
using System.Reflection;
using System.Runtime.Loader;

namespace ConsoleApp1
{
    public class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        public static void Execute()
        {
            var assemblyName = new AssemblyName("ConsoleApp1");
            var context1 = AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly());
            var context2 = AssemblyLoadContext.GetLoadContext(typeof(Program).Assembly);
            var asm = context1.LoadFromAssemblyName(assemblyName);
            asm = context2.LoadFromAssemblyName(assemblyName);

            // BOOM
            asm = Assembly.Load(assemblyName);
        }
    }
}
```
cc @jkotas @vitek-karas

**Comment by jkotas** [comment] 2019-02-23 09:54
It works fine if you make the context non-collectible. It looks like a dup of the bug being fixed by https://github.com/dotnet/coreclr/pull/22494.

cc @janvorli

**Comment by sdmaclea** [comment] 2019-04-03 21:50
This is a duplicate of #22494

**Closed by sdmaclea** 2019-04-03 21:50 UTC
Labels: area-AssemblyLoader, bug
