### ISSUE TITLE
Misc build failures in 'official/dotnet/coreclr/refs/heads/master' - '20190312.71'

### ISSUE THREAD

**Issue by robertborr** [dotnet/coreclr#23211] opened 2019-03-12 18:13 UTC
@dotnet-mc-bot commented on [Tue Mar 12 2019](https://github.com/dotnet/core-eng/issues/5473)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=121718
  - **Agent:** a0000JD
  - **Error log:** ERROR: An error occurred in /__w/2/s/.dotnet/dotnet msbuild /nologo /verbosity:minimal /clp:Summary /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount /__w/2/s/tes...

@robertborr

---

@robertborr commented on [Tue Mar 12 2019](https://github.com/dotnet/core-eng/issues/5473#issuecomment-472079397)

2019-03-12T14:03:50.4637915Z ERROR: An error occurred in /__w/2/s/.dotnet/dotnet msbuild /nologo /verbosity:minimal /clp:Summary /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount /__w/2/s/tests/build.proj /flp:Verbosity=normal;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Release.log;Append=true /flp1:WarningsOnly;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Release.wrn;Append=true /flp2:ErrorsOnly;LogFile=/__w/2/s/bin/Logs/Tests_Managed.Linux.x64.Release.err;Append=true /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:__BuildArch=x64 /p:__BuildType=Release /p:__BuildOS=Linux /p:CLRTestPriorityToBuild=1. Check logs under /__w/2/s.

---

@robertborr commented on [Tue Mar 12 2019](https://github.com/dotnet/core-eng/issues/5473#issuecomment-472091307)

after examining the artifact logs, it appears that the build crashed. The err log is empty.

---

@robertborr commented on [Tue Mar 12 2019](https://github.com/dotnet/core-eng/issues/5473#issuecomment-472120180)

classifying as sourcecode

**Comment by RussKeldorph** [comment] 2019-03-20 17:16
Duplicate of #23224.

**Closed by RussKeldorph** 2019-03-20 17:16 UTC
