### ISSUE TITLE
[Windows/arm] PMI assertions in System.Memory.dll: idxLastRegDesc > 0

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#24701] opened 2019-05-21 22:59 UTC
All the assertions in the same location **src\vm\arm\stubs.cpp Line: 1832** https://github.com/dotnet/coreclr/blob/2b4b230cdf44d0c25df004660f18c4290e9deb72/src/vm/arm/stubs.cpp#L1817-L1834

```
PREPALL type# 32 method# 253 System.Buffers.ReadOnlySequence`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::Slice

Assert failure(PID 14092 [0x0000370c], Thread: 3664 [0x0e50]): idxLastRegDesc > 0

<no module>! <no symbol> + 0x0 (0x00000000)
    File: D:\git\coreclr1\src\vm\arm\stubs.cpp Line: 1832
    Image: C:\echesako\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

```
PREPALL type# 32 method# 256 System.Buffers.ReadOnlySequence`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::GetPosition

Assert failure(PID 13332 [0x00003414], Thread: 2020 [0x07e4]): idxLastRegDesc > 0

<no module>! <no symbol> + 0x0 (0x00000000)
    File: D:\git\coreclr1\src\vm\arm\stubs.cpp Line: 1832
    Image: C:\echesako\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

```
PREPALL type# 32 method# 264 System.Buffers.ReadOnlySequence`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::Seek

Assert failure(PID 7660 [0x00001dec], Thread: 2312 [0x0908]): idxLastRegDesc > 0

<no module>! <no symbol> + 0x0 (0x00000000)
    File: D:\git\coreclr1\src\vm\arm\stubs.cpp Line: 1832
    Image: C:\echesako\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

Reproduces on top of eb95382ef607afb7def0656168a6a6507b45f254

**Comment by echesakovMSFT** [comment] 2019-05-21 22:59
@dotnet/jit-contrib

**Comment by RussKeldorph** [comment] 2019-07-02 20:28
@CarolEidt Could you look into this?  If the fix isn't obvious, you can ask @sergiy-k's team for help, but please set them up with the repro if it requires PMI.

**Comment by CarolEidt** [comment] 2019-07-02 20:53
@echesakovMSFT - just to confirm - this is running pmi on arm32/windows, correct? Do I cross-build pmi?

**Comment by CarolEidt** [comment] 2019-07-02 22:43
@echesakovMSFT - nevermind. I realized that pmi is managed, so no need for a special build. I'm now able to reproduce the assert.

**Comment by RussKeldorph** [comment] 2019-07-03 17:25
@sergiy-k Could you take this?  If it turns out to be codegen, feel free to send it back.

**Comment by sergiy-k** [comment] 2019-07-03 17:28
@fadimounir, could you please take a look? @RussKeldorph can give you access to an arm machine if you need it.

**Comment by RussKeldorph** [comment] 2019-07-03 17:30
@CarolEidt Could you add more detailed repro instructions for non-JIT team members?

**Comment by CarolEidt** [comment] 2019-07-03 17:47
- Build coreclr for arm windows and copy the tests directory to the arm machine.
- Clone jitutils (https://github.com/dotnet/jitutils) and build, then simply copy the bin folder to the arm machine.
- Run the following:
```
<path-to-core_root>\CoreRun.exe <path-to-pmi-bin>\pmi.dll prepone <path-to-core_root\System.Memory.dll 225
```
Sometimes the indices to the methods can change, so if the above doesn't produce the assert, you can change the `prepone` to `prepall` and leave off the index at the end. Then, you'll see a mssage like this:
```
PREPONE type# 34 method# 225 System.Buffers.ReadOnlySequence`1[[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]::Seek

Assert failure(PID 17376 [0x000043e0], Thread: 14468 [0x3884]): idxLastRegDesc > 0

<no module>! <no symbol> + 0x0 (0x00000000)
    File: f:\git3\coreclr\src\vm\arm\stubs.cpp Line: 1832
    Image: C:\cteidt3\coreclr\bin\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```
Which will show you the `method#` to use in a subsequent run.

Let me know if any of that isn't clear.

**Comment by CarolEidt** [comment] 2019-07-03 19:08
I'm not at all familiar with this code, but after the pass where it constructs `rgArgDescs`, there are 3 entries, so after this line:
```
        DWORD idxLastRegDesc = min(3, cArgDescriptors - 1);
```
`idxLastRegDesc` is 2. However, they all have `m_fDstIsReg` set to `false`, hence we hit the assert here:
```
        // Adjust that count to match reality.
        while (!rgArgDescs[idxLastRegDesc].m_fDstIsReg)
        {
            _ASSERTE(idxLastRegDesc > 0);
            idxLastRegDesc--;
        }
```
I didn't get further than that.

**Comment by fadimounir** [comment] 2019-07-03 19:20
Thanks @CarolEidt. I was able to repro this, and the new method index is 171 now.

@RussKeldorph This looks like a codegen issue when generating the instantiating stub on arm. Should someone on the JIT team take a look, or would you like me to dig deeper? (currently not familiar with this code at the moment).

**Comment by CarolEidt** [comment] 2019-07-03 19:26
While it's possible that this is a codegen issue, it would be surprising, since it's asserting in code that, AFAICT, is not executing any JIT'd code, and all the information about signatures appears to be coming from the type system.

**Comment by fadimounir** [comment] 2019-07-03 20:30
Ok there might be a confusion on my side here. The code that's asserting generates an assembly stub, so i considered this to be "codegen" even though it's not part of the jit itself.
Let me dig deeper then, so figure out what's going on here.

**Comment by CarolEidt** [comment] 2019-07-03 21:16
@fadimounir - looking at this just a little further, I suspect that the problem may be that the method uses all four argument registers for:
- the this pointer
- the return buffer
- the first parameter, which is `long` (so takes two registers)

I *think* that `StubLinkerCPU::ThumbEmitCallWithGenericInstantiationParameter()` is attempting to insert an argument after the this pointer and the return buffer. However, doing so bumps the `long` parameter out of the registers (since it must be in an even/odd pair).
It may be that this method is not expecting this insertion to cause a hole in the argument registers.

**Comment by fadimounir** [comment] 2019-07-03 21:22
@CarolEidt Thanks for the analysis. It does sound like it yes. So far from debugging this, it looks like the first real argument for the function (the long parameter) is moved to the stack. I would expect this to take r2+r3.
I'll debug the signature walking and see what's getting inserted

**Comment by CarolEidt** [comment] 2019-07-03 21:25
I think it's right for the long parameter to be moved to the stack, since it was originally being passed in r2+r3 (r0 is 'this' and r1 is the return buffer).

**Comment by fadimounir** [comment] 2019-07-03 21:25
Ah! Forgot there was a new hidden instantiation parameter.

**Comment by fadimounir** [comment] 2019-07-03 21:28
Wait... That sounds incorrect. This is an instance method, and shouldn't need an instantiation argument... Shouldn't it be:
- this pointer in r0
- return buffer pointer in r1
- first parameter in r2 + r3
- second parameter on stack?

**Comment by CarolEidt** [comment] 2019-07-03 21:35
I don't understand the situations in which an instantiation argument needs to be inserted. However, it seems that this method should only be called in the case where such an argument is needed.

**Comment by fadimounir** [comment] 2019-07-03 22:17
Ok I found what the issue is. The instantiation stub making logic assumes at least one parameter will be in a register when invoking the instantiating stub's target, but that's not always the case. In the case of this particular method, here's how the registers will be used:
- r0 = thisptr
- r1 = retbuffer ptr
- r2 = inserted instantiation argument by the instantiating stub.
- r3 = unused
- stack[0] + stack[1] = first parameter (long)
- stack[2] = second parameter.

I'll send a PR for review

**Closed** 2019-07-05 04:49 UTC
Labels: arch-arm32, os-windows
