### ISSUE TITLE
[Question] How to get coreclr version from application

### ISSUE THREAD

**Issue by dopare** [dotnet/coreclr#8815] opened 2017-01-05 05:35 UTC
I have a sample [application](https://github.com/dopare/dotnet-core-nightly) based on latest project system and `coreclr` and it uses `Environment.Version`.
Turns out that `Environment.Version` is [hardcoded](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Environment.cs#L582).
How can my application fetch `coreclr` version?
Thank you

**Comment by gkhanna79** [comment] 2017-01-29 06:52
Why do you need version of CoreCLR @dopare instead of, say, version of .NET Core FX your application is running against?

**Comment by dopare** [comment] 2017-01-29 16:41
And what is the version of .NET Core FX ?
Do you mean package version of `Microsoft.NETCore.App` ?

**Comment by jnm2** [comment] 2017-01-30 14:04
The obvious reason to want this that I see is diagnostic logging.

**Comment by gkhanna79** [comment] 2017-01-30 16:38
Yes, the version of Microsoft.NEtCore.App is the more meaningful version that should be used (for logging or identification purposes).

CoreCLR is just one of the binaries comprising .NETCore and is an implementation detail. Version of Microsoft.NETCore.App is intended to, by design, abstract it away.

**Comment by dopare** [comment] 2017-01-30 19:09
Is there any easy way to get `Microsoft.NEtCore.App` version instead of iterating on `DependencyContext.Default.RuntimeLibraries` to find it ?

**Comment by gkhanna79** [comment] 2017-01-30 19:11
I am not aware of such an API yet. @AlexGhiondea do you know?

**Comment by AlexGhiondea** [comment] 2017-02-02 05:26
I don't know of one either :(.

**Comment by jkotas** [comment] 2019-02-16 06:33
Duplicate of https://github.com/dotnet/corefx/issues/35361

**Closed by jkotas** 2019-02-16 06:33 UTC
Labels: question
