### ISSUE TITLE
Ryujit TakesRexWPrefix on AMD64 returns wrong value

### ISSUE THREAD

**Issue by helloguo** [dotnet/coreclr#9705] opened 2017-02-21 22:40 UTC
The function TakesRexWPrefix located at https://github.com/dotnet/coreclr/blob/59392bbb5b4eacd30f2ecbebc65b71dd95a5819a/src/jit/emitxarch.cpp#L210 returns false if "EA_SIZE(attr) != EA_8BYTE". However, for AVX instructions whose size is not EA_8BYTE and need WPrefix, it should return true.

@fiigii PTAL

**Comment by fiigii** [comment] 2017-02-23 22:43
This is not a bug or issue. So far, RyuJIT only needs to add specific Rex.W (or Vex.W) flags to certain scalar SSE/AVX instructions, whose oprand's size are always 8 byte (even though oprands are in xmm/ymm registers). In the future, if anyone want to add a SSE/AVX SIMD instruction that requires Rex.W/Vex.W (i.e. VPSRLVD/VPSRLVQ), he/she just needs to write `if (theIns) return true` at the beginning of `TakesRexWPrefix` (at least before `if (EA_SIZE(attr) != EA_8BYTE)`).

@sivarv Do you think we should add a comment to remind developers who want to use these SIMD instructions? And please close this issue.

**Comment by RussKeldorph** [comment] 2017-03-07 00:42
@BruceForstall Is this worth addressing with a comment or interface change now, or should we wait until it proves to be a problem?

**Comment by BruceForstall** [comment] 2017-03-07 00:56
@RussKeldorph Doesn't seem worth addressing/commenting now.

**Closed** 2017-03-07 00:56 UTC
Labels: area-CodeGen
