### ISSUE TITLE
3 tests failed with return code 137 in CI job arm64_cross_release_ubuntu16.04_r2r_tst

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20517] opened 2018-10-22 08:00 UTC
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_ubuntu16.04_r2r_tst/6/

failed log:
```
/n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/JIT/opt/Reports/JIT.opt/Devirtualization/overload/overload.output.txt/nRaw output:/nTest Harness Exitcode is : 137
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/JIT/opt/Devirtualization/overload/overload.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04/bin/tests/Linux.arm64.Release/TestWrappers/JIT.opt/JIT.opt.XUnitWrapper.cs(2489,0): at JIT_opt._Devirtualization_overload_overload_._Devirtualization_overload_overload_sh()
      **JIT_opt._Devirtualization_overload_overload_._Devirtualization_overload_overload_sh [FAIL]**
    Finished:    JIT.SIMD.XUnitWrapper
      **JIT_HardwareIntrinsics._X86_Sse_Store_r_Store_r_._X86_Sse_Store_r_Store_r_sh [FAIL]**
        /n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/X86/Sse/Store_r/Store_r.output.txt/nRaw output:/nTest Harness Exitcode is : 137
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/JIT/HardwareIntrinsics/X86/Sse/Store_r/Store_r.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04/bin/tests/Linux.arm64.Release/TestWrappers/JIT.HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.cs(13479,0): at JIT_HardwareIntrinsics._X86_Sse_Store_r_Store_r_._X86_Sse_Store_r_Store_r_sh()
      **JIT_HardwareIntrinsics._X86_General_VectorUnused_r_VectorUnused_r_._X86_General_VectorUnused_r_VectorUnused_r_sh [FAIL]**
        /n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/X86/General/VectorUnused_r/VectorUnused_r.output.txt/nRaw output:/nTest Harness Exitcode is : 137
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04_r2r_tst/bin/tests/Linux.arm64.Release/JIT/HardwareIntrinsics/X86/General/VectorUnused_r/VectorUnused_r.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_release_ubuntu16.04/bin/tests/Linux.arm64.Release/TestWrappers/JIT.HardwareIntrinsics/JIT.HardwareIntrinsics.XUnitWrapper.cs(7949,0): at JIT_HardwareIntrinsics._X86_General_VectorUnused_r_VectorUnused_r_._X86_General_VectorUnused_r_VectorUnused_r_sh()
```

**Comment by shimingsg** [comment] 2018-10-23 06:58
similar failures in job https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitstressregs0x10_tst/6/consoleText

**Comment by RussKeldorph** [comment] 2019-01-16 21:57
Assuming duplicate of #22010.  Feel free to re-open if not.

**Closed by RussKeldorph** 2019-01-16 21:57 UTC
Labels: arch-arm64, os-linux
