### ISSUE TITLE
GcStress: Linux: Failure in _relgc_nested

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2847] opened 2016-01-25 21:20 UTC
```
FAILED   - JIT/Methodical/VT/etc/_relgc_nested/_relgc_nested.sh
               BEGIN EXECUTION
               /home/swaroops/test/Tests/coreoverlay/corerun _relgc_nested.exe
               
               Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
                  at JitTest.Test.Main()
               ./_relgc_nested.sh: line 55:  8257 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" _relgc_nested.exe $CLRTestExecutionArguments $Host_Args
               Expected: 100
               Actual: 134
               END EXECUTION – FAILED
```

**Comment by sivarv** [comment] 2016-01-29 03:19
mkrefany/refanyval test case.  Fix that correctly classifies TypedReference should fix this.

**Comment by sivarv** [comment] 2016-01-29 04:22
This is a duplicate of #2764

**Closed by sivarv** 2016-01-29 04:22 UTC
Labels: bug, CodeGen, GCStress, Linux
