### ISSUE TITLE
Improve SIMD register allocator for HW intrinsics, avoid unnecessary movaps between SIMD registers

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#16803] opened 2018-03-07 17:10 UTC
During implementation of Sse2.SetAllVector128 we have been hitting both by implementing intrinsic in importer and in managed code (i) unnecessary XMM register allocation issues and (ii) unnecessary value copying between XMM registers what seems to be associated with the first problem.

An example below shows optimal codegen followed by actual codegen:

```assembly
// SetAllVector128 for byte
00007FF7911C1012  movsx       eax,byte ptr [valueSt (07FF7911C3034h)]  
00007FF7911C1019  movd        xmm0,eax  
00007FF7911C101D  punpcklbw   xmm0,xmm0  
00007FF7911C1021  punpcklwd   xmm0,xmm0  
00007FF7911C1025  pshufd      xmm0,xmm0,0

// Actual codegen
       480FBECE             movsx    rcx, sil
       660F6EC1             movd     xmm0, xrcx
       0F28C8               movaps   xmm1, xmm0
       660F60C8             punpcklbw xmm1, xmm0
       0F28C1               movaps   xmm0, xmm1
       0F28C8               movaps   xmm1, xmm0
       660F61C8             punpcklwd xmm1, xmm0
       660F70C900           pshufd   xmm1, xmm1, 0
```

In the above example usage of XMM1 register is unnecessary and results in multiple `movaps xmmX, xmmX` operations.

For discussion see #16797 and #16758

**Comment by tannergooding** [comment] 2018-03-07 17:19
This is a more general issue and not one that impacts only HWIntrinsics.

This type of instruction sequence is basically a no-op:
```asm
0F28C1               movaps   xmm0, xmm1
0F28C8               movaps   xmm1, xmm0
```

This type of instruction sequence is bad because its using unneeded registers (we only need rcx and xmm0):
```asm
660F6EC1             movd     xmm0, rcx
0F28C8               movaps   xmm1, xmm0
660F60C8             punpcklbw xmm1, xmm0
```

This type of instruction sequence is bad (and represents the issue for non-SIMD registers) because its using unneeded registers (we only need rsi and xmm0):
```asm
480FBECE             movsx    rcx, sil
660F6EC1             movd     xmm0, rcx
```

**Comment by tannergooding** [comment] 2018-03-07 17:19
FYI. @CarolEidt, @fiigii

**Comment by CarolEidt** [comment] 2018-03-07 17:26
Please provide a specific use case, i.e. code, so that there is something actionable and measurable. That will greatly increase the likelihood that this will get some attention.

**Comment by mikedn** [comment] 2018-03-07 17:40
At least some of this stuff is likely caused by RMW/delay free not accounting for the case of a `binop(x, x)` where `x` is last use. It gets marked as delay free so the destination register will inevitably be different.

**Comment by 4creators** [comment] 2018-03-07 17:57
> Please provide a specific use case, i.e. code, so that there is something actionable and measurable

The above disasm is generated for managed implementation of helper intrinsic:

```C#
        /// <summary>
        /// __m128i _mm_set1_epi8 (char a)
        ///   HELPER
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector128<byte> SetAllVector128(byte value)
        {
            Vector128<byte> vector1 = Sse.StaticCast<uint, byte>(ConvertScalarToVector128UInt32(value));
            Vector128<ushort> vector2 = Sse.StaticCast<byte, ushort>(UnpackLow(vector1, vector1));
            return Sse.StaticCast<uint, byte>(Shuffle(Sse.StaticCast<ushort, uint>(UnpackLow(vector2, vector2)), 0));
        }
```

But it is present in the following helper overloads of `SetAllVector128` as well:

```C#
        /// <summary>
        /// __m128i _mm_set1_epi16 (short a)
        ///   HELPER
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector128<short> SetAllVector128(short value)
        {
            Vector128<short> vector = Sse.StaticCast<int, short>(ConvertScalarToVector128Int32(value));
            return Sse.StaticCast<int, short>(Shuffle(Sse.StaticCast<short, int>(UnpackLow(vector, vector)), (byte)0));
        }
        /// <summary>
        /// __m128i _mm_set1_epi16 (short a)
        ///   HELPER
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector128<ushort> SetAllVector128(ushort value)
        {
            Vector128<ushort> vector = Sse.StaticCast<uint, ushort>(ConvertScalarToVector128UInt32(value));
            return Sse.StaticCast<uint, ushort>(Shuffle(Sse.StaticCast<ushort,uint>(UnpackLow(vector, vector)), (byte)0));
        }

        /// <summary>
        /// __m128i _mm_set1_epi64x (long long a)
        ///   HELPER
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector128<long> SetAllVector128(long value)
        {
            Vector128<long> vector = ConvertScalarToVector128Int64(value);
            return UnpackLow(vector, vector);
        }
        /// <summary>
        /// __m128i _mm_set1_epi64x (long long a)
        ///   HELPER
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector128<ulong> SetAllVector128(ulong value)
        {
            Vector128<ulong> vector = ConvertScalarToVector128UInt64(value);
            return UnpackLow(vector, vector);
        }
        /// <summary>
        /// __m128d _mm_set1_pd (double a)
        ///   HELPER
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector128<double> SetAllVector128(double value)
        {
            Vector128<int> vector = Sse.StaticCast<double, int>(SetScalarVector128(value));
            return Sse.StaticCast<int, double>(Shuffle(vector, (byte)68));
        }
```

In the case of `public static Vector128<long> SetAllVector128(long value)` and `ulong` overload the codegen is optimal in the case we use `Shuffle` overload which takes one `Vector128` argument but has unneeded register allocations when the same argument `Vector128` is passed twice to `UnpackLow`.

```assembly
       66480F6EC6           movd     xmm0, rsi
       0F28C8               movaps   xmm1, xmm0
       660F6CC8             punpcklqdq xmm1, xmm0


       660F6EC6             movd     xmm0, xrsi
       660F70C044           pshufd   xmm0, xmm0, 68
```
Obviouly there should be `movq` not `movd` but it is our implementation bug.

**Comment by mikedn** [comment] 2018-03-07 18:15
> At least some of this stuff is likely caused by RMW/delay free not accounting for the case of a binop(x, x) where x is last use. It gets marked as delay free so the destination register will inevitably be different.

Yet `x + x` where `x` is `int` works fine and generate something like `add edx, edx`. So this may be a intrinsic specific issue that a more general LSRA issue.

**Comment by tannergooding** [comment] 2018-03-07 18:24
`x + x` also works fine. I would guess that this is something to do with the fact that `Vector128<T>` is a struct. There are already known inefficiencies around structs being eagerly copied when they don't need to be.

I am building locally to try and confirm, or see if I can glean any info from the dumps.

**Comment by mikedn** [comment] 2018-03-07 18:30
At the point where this matters this aren't structs so this has nothing to do with that. It's just that the proper setup for RMW is a bit more complex and BuildHWIntrinsic doesn't get it quite right it seems.

**Comment by tannergooding** [comment] 2018-03-07 18:36
Looks like, for starters, we aren't going down the `isRMWRegOper` path here:  https://github.com/dotnet/coreclr/blob/master/src/jit/lsraxarch.cpp#L590 (implementation is here: https://github.com/dotnet/coreclr/blob/master/src/jit/lsraxarch.cpp#L799)

**Comment by mikedn** [comment] 2018-03-07 18:40
Well, you probably can't go down that path because it won't work well for intrinsics that claim to be binary when they really aren't. It's likely that the logic will need to be reproduced in BuildHWIntrinsic. The trouble is that the existing logic relies on addition on being commutative and this information is not available for intrinsics...

**Comment by tannergooding** [comment] 2018-03-07 18:45
>  this information is not available for intrinsics...

We actually have all the information in the lookup table, we just don't appear to be setting that information in the tree.

So we should be able to either look it up, or set the tree node (I would imagine the latter may be better).

> Well, you probably can't go down that path because it won't work well for intrinsics that claim to be binary when they really aren't.

It seems that this is already setup to handle that scenario (at least for OperIsBinary, when it is really Ternary or more). `GT_HWIntrinsic` also isn't the only binary node where `op2` can be null (however, it is the only one where `op1` can also be null).

**Comment by mikedn** [comment] 2018-03-07 18:51
> Looks like, for starters, we aren't going down the isRMWRegOper path here:

**Comment by 4creators** [comment] 2018-03-07 18:56
> With some hacks I made it generate

Can you share?

**Comment by mikedn** [comment] 2018-03-07 18:59
> Can you share?

It's not useful beyond my little experiment, I simply made sure that delay free isn't set on op2.

**Comment by CarolEidt** [comment] 2018-03-07 19:01
FWIW, the handling of RMW operators is going to change with future iterations of #16517 (follow-on PRs), so I wouldn't invest *too* heavily in the current structure. That said, it would seem that one should be able to change `isRMWRegOper` in a fairly straightforward way to special-case the HW intrinsics and rely on their table info.

**Comment by tannergooding** [comment] 2018-03-07 19:16
> in a fairly straightforward way to special-case the HW intrinsics and rely on their table info.

I am actually testing this right now. There are only minimal changes required to get this working with `isRMWRegOper` and `OperIsCommutative` (GTK_COMMUTE), as well as `canBeContained` (GTK_NOCONTAIN).

**Comment by tannergooding** [comment] 2018-03-07 20:20
See https://github.com/dotnet/coreclr/pull/16808, which makes codegen is much better for many of the intrinsics

**Closed** 2018-03-08 16:35 UTC
Labels: area-CodeGen, enhancement, optimization, tenet-performance
