### ISSUE TITLE
Pri-1 builds all failing

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#22995] opened 2019-03-04 16:16 UTC
It appears https://github.com/dotnet/coreclr/pull/22885 has broken all pri-1 builds, with errors like:

```
error : Unexpected test count. Expected > 9000, found 3145.
```

It appears pri-1 builds are only doing pri-0 test builds.

(note, this error was introduced specifically to find problems like this)

e.g.,
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt/6682/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/checked_windows_nt/11480/

**Comment by echesakovMSFT** [comment] 2019-03-04 17:34
This doesn't block official builds and AzDO CI so removing the label - only Jenkins Pri1 tests are affected.

I think it's related to how we build the tests in Jenkins - instead of calling build.cmd then build-test.cmd we have only one call to build.cmd so suspect the priority hasn't been passed properly

**Comment by echesakovMSFT** [comment] 2019-03-04 18:36
The issue is introduced in #21608 in line #232 of build.cmd.

All the Windows Pri1 Jenkins jobs has been running Pri0 tests since that change got merged. For example,  https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt/6611/consoleFull from February 14.

Actually, the change in #22885 helped to expose that original issue.

**The problem explanation:**
Before #21608 build.cmd was calling build-test.cmd with -priority=*n* argument. After that change this call has been transformed to
```
BUILD: call D:\j\workspace\arm64_cross_c---0aaef436\build-test.cmd arm64 Checked  /p:CLRTestPriorityToBuild=1
```
effectively ignoring test priority passed to build.cmd.

As a remedy I suggest:
1) change Jenkins netci.groovy to be running build.cmd then build-test.cmd (the same way we run in AzDO and official build)
2) figure out the original problem in build.cmd

Eventually, we should get rid of build-test.cmd logic inside of build.cmd.

**Closed** 2019-03-05 00:42 UTC
Labels: area-Infrastructure, blocking-clean-ci, bug
