### ISSUE TITLE
ReadyToRun: Assertion failed 'nextLinearNode != nullptr' when crossgen-ing 3 tests

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#3618] opened 2016-03-09 03:27 UTC
Tests:
JIT\Directed\StrAccess\straccess2_cs_ro\straccess2_cs_ro.exe
JIT\Directed\StrAccess\straccess2_cs_do\straccess2_cs_do.exe
JIT\Regression\CLR-x86-JIT\V1.1-M1-Beta1\b140711\b140711\b140711.exe

Repro steps:
 Git commit hash:  c89bf3f  

E:\coreclr>rd /s/q E:\coreclr\bin\tests
E:\coreclr>build checked skiptests
E:\coreclr>tests\buildtest.cmd checked crossgen
E:\coreclr>tests\runtest.cmd checked

Asserts for each of the tests:

Assert failure(PID 29884 [0x000074bc], Thread: 20784 [0x5130]): Assertion failed 'nextLinearNode != nullptr' in 'StrAccess2:Main():int' (IL size 5521)
Assert failure(PID 35636 [0x00008b34], Thread: 33968 [0x84b0]): Assertion failed 'nextLinearNode != nullptr' in 'BadMath:Main(ref):int' (IL size 703)
Assert failure(PID 27240 [0x00006a68], Thread: 21208 [0x52d8]): Assertion failed 'nextLinearNode != nullptr' in 'StrAccess2:Main():int' (IL size 5533)
            File: e:\coreclr\src\jit\rationalize.cpp Line: 407
            Image: E:\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\crossgen.exe

**Comment by erozenfeld** [comment] 2016-03-10 18:10
@LLITCHEV I believe the failure was masked by my change 8e069ce739232b43085e530556bf6b02832d8b5b Please use  c89bf3f   to repro.

**Comment by LLITCHEV** [comment] 2016-03-10 23:36
Just a bit more information on this issue...
This is strictly a ReadyToRun issue.
When jitting for normal run the code looks like:
fgInsertEmbeddedFormTemp created store :
N006 (  3, 10) [005175] ------------                /--*  const(h)  long   0x80d76929d0 static Fseq[str2darr] $2d4
N007 (  5, 12) [004357] ----G-------             /--*  indir     ref    $782
     (  6, 13) [011633] DA--G-------             *  st.lclVar ref    V375 rat1        
Results of lowering ArrElem:
     (  1,  1) [011636] ------------                   /--*  const     long   0
     (  3,  2) [011634] ------------                   |  /--*  lclVar    ref    V375 rat1        
N008 (  1,  1) [004365] ------------                   |  +--*  const     int    0 $40
     (  5,  4) [011637] ---X--------                   +--*  arrMDIdx[i, ] int   
     (  3,  2) [011638] ------------                   +--*  lclVar    ref    V375 rat1        
     (  9,  7) [011639] ---X--------                /--*  arrMDOffs[i, ] long  
     (  3,  2) [011640] ------------                |  /--*  lclVar    ref    V375 rat1        
N009 (  1,  1) [004366] ------------                |  +--*  const     int    0 $40
     (  5,  4) [011641] ---X--------                +--*  arrMDIdx[*,j] int   
     (  3,  2) [011642] ------------                +--*  lclVar    ref    V375 rat1        
     ( 17, 13) [011643] ---X--------             /--*  arrMDOffs[*,j] long  
     (  3,  2) [011644] ------------             +--*  lclVar    ref    V375 rat1        
     ( 21, 16) [011645] ---X----R---             *  lea(b+(i*8)+32) byref 

Resulting statement:
     ( 25, 19) [010339] ------------             *  stmtExpr  void  (embedded) (IL 0x1CF...  ???)
     (  1,  1) [011636] ------------             |              /--*  const     long   0
     (  3,  2) [011634] ------------             |              |  /--*  lclVar    ref    V375 rat1        
N008 (  1,  1) [004365] ------------             |              |  +--*  const     int    0 $40
     (  5,  4) [011637] ---X--------             |              +--*  arrMDIdx[i, ] int   
     (  3,  2) [011638] ------------             |              +--*  lclVar    ref    V375 rat1        
     (  9,  7) [011639] ---X--------             |           /--*  arrMDOffs[i, ] long  
     (  3,  2) [011640] ------------             |           |  /--*  lclVar    ref    V375 rat1        
N009 (  1,  1) [004366] ------------             |           |  +--*  const     int    0 $40
     (  5,  4) [011641] ---X--------             |           +--*  arrMDIdx[*,j] int   
     (  3,  2) [011642] ------------             |           +--*  lclVar    ref    V375 rat1        
     ( 17, 13) [011643] ---X--------             |        /--*  arrMDOffs[*,j] long  
     (  3,  2) [011644] ------------             |        +--*  lclVar    ref    V375 rat1        
     ( 21, 16) [011645] ---X----R---             |     /--*  lea(b+(i*8)+32) byref 
N011 ( 24, 18) [004368] --CXG-------             |  /--*  indir     ref    $783
N013 ( 25, 19) [005157] DACXG-------             \--*  st.lclVar ref    V86 tmp68        d:3

When running crossgen for ReadyToRun it looks liek:
fgInsertEmbeddedFormTemp created store :
N001 (  3, 10) [009980] ------------                         /--*  const(h)  long   0x5318763f90 ftn REG NA
N002 (  5, 12) [009981] ------------ control expr         /--*  indir     long  
N006 ( 14,  5) [003617] H-C-G-------                   /--*  call help byref  HELPER.CORINFO_HELP_READYTORUN_STATIC_BASE $7c2
     ( 15,  6) [009982] --C-G-------                /--*  lea(b+8)  byref 
N009 ( 18,  8) [003620] --CXG-------             /--*  indir     ref    <l:$78d, c:$78c>
     ( 19,  9) [009984] DACXG-------             *  st.lclVar ref    V347 rat1        
Results of lowering ArrElem:
     (  1,  1) [009987] ------------                   /--*  const     long   0
     (  3,  2) [009985] ------------                   |  /--*  lclVar    ref    V347 rat1        
N010 (  1,  1) [003621] ------------                   |  +--*  const     int    0 $40
     (  5,  4) [009988] ---X--------                   +--*  arrMDIdx[i, ] int   
     (  3,  2) [009989] ------------                   +--*  lclVar    ref    V347 rat1        
     (  9,  7) [009990] ---X--------                /--*  arrMDOffs[i, ] long  
     (  3,  2) [009991] ------------                |  /--*  lclVar    ref    V347 rat1        
N011 (  1,  1) [003622] ------------                |  +--*  const     int    0 $40
     (  5,  4) [009992] ---X--------                +--*  arrMDIdx[*,j] int   
     (  3,  2) [009993] ------------                +--*  lclVar    ref    V347 rat1        
     ( 17, 13) [009994] ---X--------             /--*  arrMDOffs[*,j] long  
     (  3,  2) [009995] ------------             +--*  lclVar    ref    V347 rat1        
     ( 21, 16) [009996] ---X----R---             *  lea(b+(i*8)+32) byref 

Resulting statement:
     ( 25, 19) [008682] ------------             *  stmtExpr  void  (embedded) (IL 0x1CF...  ???)
N006 ( 14,  5) [003617] H-C-G-------             |           ?--*  call help byref  HELPER.CORINFO_HELP_READYTORUN_STATIC_BASE $7c2
     ( 15,  6) [009982] --C-G-------             |        ?--*  lea(b+8)  byref 
N009 ( 18,  8) [003620] --CXG-------             |     ?--*  indir     ref    <l:$78d, c:$78c>
     ( 19,  9) [009984] DACXG-------             |     ?--*  st.lclVar ref    V347 rat1        
     (  1,  1) [009987] ------------             |     /--*  const     long   0
     (  3,  2) [009985] ------------             |     |  /--*  lclVar    ref    V347 rat1        
N010 (  1,  1) [003621] ------------             |     |  +--*  const     int    0 $40
     (  5,  4) [009988] ---X--------             |     +--*  arrMDIdx[i, ] int   
     (  3,  2) [009989] ------------             |     +--*  lclVar    ref    V347 rat1        
     (  9,  7) [009990] ---X--------             |  /--*  arrMDOffs[i, ] long  
     (  3,  2) [009991] ------------             |  |  /--*  lclVar    ref    V347 rat1        
N011 (  1,  1) [003622] ------------             |  |  +--*  const     int    0 $40
     (  5,  4) [009992] ---X--------             |  +--*  arrMDIdx[*,j] int   
     (  3,  2) [009993] ------------             |  +--*  lclVar    ref    V347 rat1        
     ( 17, 13) [009994] ---X--------             /--*  arrMDOffs[*,j] long  
     (  3,  2) [009995] ------------             +--*  lclVar    ref    V347 rat1

**Comment by LLITCHEV** [comment] 2016-03-29 22:00
Looked into this and after talking @jkotas it will be hard to justify fixing this for RC2 release.
The failing case is prevented in the current code base by VN fixes. Also if going back to the commit # that reproduces the error, in release build we just fail in the crossgenning the method. The .ni. image is still created with the IL and the VM falls over to jitting.

**Comment by LLITCHEV** [comment] 2016-04-12 17:41
Fixed by #4085.

**Closed by LLITCHEV** 2016-04-12 17:41 UTC
Labels: bug, CodeGen, ReadyToRun
