### ISSUE TITLE
[Linux] Segfault when AssemblyBuilder.DefineDynamicAssembly and PerfMap

### ISSUE THREAD

**Issue by klesta490** [dotnet/coreclr#26883] opened 2019-09-25 14:15 UTC
Hi!
When I build app with final **.NET Core v3.0.0** and run it with
`COMPlus_PerfMapEnabled=1`

```
static void Main(string[] args)
{
     AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Sth.dll"), AssemblyBuilderAccess.RunAndCollect);
}
```

I get instantly **Segmentation faul**t.

It seems it is working fine on Preview9 (I was not testing any other versions).

It migh be related to [Link](https://github.com/dotnet/coreclr/issues/26830) 

Fun fact,
with `COMPlus_PerfMapEnabled=1`  
I get segfault for 

`dotnet new console`
`dotnet tool install -g dotnet-sos`   
That makes it real fun to diagnose.

Maybe this stack trace helps
```
frame #0: 0x00007f5a43d32caa libcoreclr.so`PerfInfo::LogImage(PEFile, char16_t) + 90
frame #1: 0x00007f5a43d31e57 libcoreclr.so`PerfMap::LogImage(PEFile*) + 279
frame #2: 0x00007f5a43e6c56a libcoreclr.so`Assembly::CreateDynamic(AppDomain, CreateDynamicAssemblyArgs) + 2538
frame #3: 0x00007f5a43ec052a libcoreclr.so`AppDomainNative::CreateDynamicAssembly(AssemblyNameBaseObject, StackCrawlMark, int) + 234
```
Of course I can disable it, but this prevents me from profiling apps :-(

**Comment by karelz** [comment] 2019-09-25 19:37
@janvorli @jkotas any thoughts?
@klesta490 does it happen on more than 1 machine? This is highly suspicious.

**Comment by karelz** [comment] 2019-09-25 19:38
Cc @noahfalk

**Comment by jkotas** [comment] 2019-09-25 20:51
> @jkotas any thoughts?

Plain vanilla bug in the PerfMap implementation.

>  does it happen on more than 1 machine? This is highly suspicious

It is 100% repro.

**Comment by jkotas** [comment] 2019-09-25 20:59
Likely introduced by https://github.com/dotnet/coreclr/pull/26403

cc @brianrob

**Comment by danmosemsft** [comment] 2019-09-25 21:16
I set 3.0.x so it doesn't get lost, feel free to change.

**Comment by brianrob** [comment] 2019-09-26 00:31
Yup, this was caused by #26403.  I am working on a fix.

**Comment by danmosemsft** [comment] 2019-09-26 17:08
cc @jeffschwMSFT for shiproom.

**Comment by jkotas** [comment] 2019-09-26 22:22
@brianrob Could you please prepare PR to back port this?

**Comment by jeffschwMSFT** [comment] 2019-09-26 22:36
@brianrob we should consider this for 3.0.x servicing.  Can you create a cheery picked PR against the release/3.0 and mark with label:ask-mode.  We can then have it reviewed/approved by tactics.

cc @MeiChin-Tsai

**Comment by brianrob** [comment] 2019-09-26 22:52
Yup, I'm already doing that.  Didn't mean to use the magic word to get GitHub to close this.  Will post the PR shortly.

**Comment by brianrob** [comment] 2019-09-26 22:54
@jeffschwMSFT, I've posted #26910 and marked it with label:ask-mode.

**Comment by klesta490** [comment] 2019-10-08 06:57
Is there any WA? I don't want to rebuild all images back to Preview9 :-/

**Comment by jeffschwMSFT** [comment] 2019-10-08 15:36
The servicing fix is currently slated for 3.0.2.  +@brianrob on any potential workarounds.

**Comment by brianrob** [comment] 2019-10-08 20:48
Unfortunately, I'm not aware of any workaround, short of not generating any dynamic assemblies.

**Comment by sdmaclea** [comment] 2019-10-17 18:45
@brianrob Can this be closed?

**Comment by brianrob** [comment] 2019-10-17 19:04
Yes, this has now been merged for 3.0.2.

**Closed by brianrob** 2019-10-17 19:04 UTC
Labels: area-Tracing

**Comment by TheAngryByrd** [comment] 2019-11-12 21:15
Any idea when 3.0.2 will be released?

**Comment by jeffschwMSFT** [comment] 2019-11-12 21:53
cc @leecow

**Comment by leecow** [comment] 2019-11-13 00:35
3.0.2 will be out January.

**Comment by baronfel** [comment] 2019-11-19 22:10
Bit of clarification, this looks like it's part of the newly-release 3.0.1 Runtime as described here: https://github.com/dotnet/coreclr/pull/26910 and here: https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=milestone%3A3.0.1+label%3Aservicing-approved+sort%3Aupdated-desc

Thanks for the work, y'all!
