### ISSUE TITLE
Cannot access fields/properties using dynamic from nested classes/structs

### ISSUE THREAD

**Issue by ppekrol** [dotnet/coreclr#13226] opened 2017-08-04 11:37 UTC
Hi,

I've created `netcoreapp2.0` with following code:

```
    public class Program
    {
        public class Container<T>
        {
            public struct ExceptionStruct
            {
                public string Id;
            }

            public class ExceptionClass
            {
                public string Id;
            }
        }

        public struct ValidStruct
        {
            public string Id;
        }

        public class ValidClass
        {
            public string Id;
        }

        public static void Main(string[] args)
        {
            var validStructs = new List<dynamic>();
            var validClasses = new List<dynamic>();
            var exceptionStructs = new List<dynamic>();
            var exceptionClasses = new List<dynamic>();

            for (var i = 0; i < 100; i++)
            {
                validStructs.Add(new ValidStruct { Id = i.ToString() });
                validClasses.Add(new ValidClass { Id = i.ToString() });
                exceptionStructs.Add(new Container<object>.ExceptionStruct { Id = i.ToString() });
                exceptionClasses.Add(new Container<object>.ExceptionClass { Id = i.ToString() });
            }

            Console.WriteLine($"Checking {nameof(ValidStruct)}");
            foreach (var item in validStructs)
            {
                var id = item.Id;
                if (string.IsNullOrEmpty(id))
                    throw new InvalidOperationException("Should not happen!");
            }

            Console.WriteLine($"Checking {nameof(ValidClass)}");
            foreach (var item in validClasses)
            {
                var id = item.Id;
                if (string.IsNullOrEmpty(id))
                    throw new InvalidOperationException("Should not happen!");
            }

            Console.WriteLine($"Checking {nameof(Container<object>.ExceptionStruct)}");
            foreach (var item in exceptionStructs)
            {
                var id = item.Id;
                if (string.IsNullOrEmpty(id))
                    throw new InvalidOperationException("Should not happen!");
            }

            Console.WriteLine($"Checking {nameof(Container<object>.ExceptionClass)}");
            foreach (var item in exceptionClasses)
            {
                var id = item.Id;
                if (string.IsNullOrEmpty(id))
                    throw new InvalidOperationException("Should not happen!");
            }
        }
    }
```

It works properly when changing back to `netcoreapp1.1` but on `2.0` I'm getting:

```
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpGetMemberBinder.FallbackGetMember(DynamicMetaObject target, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObject.BindGetMember(GetMemberBinder binder)
   at System.Dynamic.GetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ConsoleApp4.Program.Main(String[] args) in C:\workspaces\Temp\ConsoleApp4\ConsoleApp4\Program.cs:line 65
```

It looks like a bug or I'm doing something wrong?

`dotnet --info` yields:
```
.NET Command Line Tools (2.1.0-preview1-007002)

Product Information:
 Version:            2.1.0-preview1-007002
 Commit SHA-1 hash:  5d282e73b1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-007002\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by jkotas** [comment] 2017-08-04 15:57
This is duplicate of https://github.com/dotnet/corefx/issues/21689

cc @VSadov

**Closed by jkotas** 2017-08-04 15:57 UTC
