### ISSUE TITLE
AssemblyLoadContext.GetAssemblyName throws MissingMethodException for native assemblies

### ISSUE THREAD

**Issue by kichalla** [dotnet/coreclr#11585] opened 2017-05-13 00:26 UTC
**Repro**
- dotnet new console
- Update the Program.cs to be like the following and change the `path` in the code to a native dll. In my case I was able to repro with `sqlclient.sni` assembly below:
```c#
using System;
using System.IO;
using System.Runtime.Loader;

namespace repro
{
    class Program
    {
        static void Main(string[] args)
        {
            var path = @"C:\Users\kichalla\.nuget\packages\runtime.win-x64.runtime.native.system.data.sqlclient.sni\4.4.0-preview2-25312-01\runtimes\win-x64\native\sni.dll";

            try
            {
                var assemblyName = AssemblyLoadContext.GetAssemblyName(path);
                Console.WriteLine(assemblyName);
            }
            catch (FileNotFoundException)
            {
            }
            catch (BadImageFormatException)
            {
            }
            catch (FileLoadException)
            {
            }
        }
    }
}
```
- dotnet restore
- dotnet run
  You should see an exception like the following:
```
Unhandled Exception: System.MissingMethodException: .ctor ---> System.MissingMethodException: .ctor
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at repro.Program.Main(String[] args)
```

**Expected:**
Any of the above exceptions in catch blocks

**Actual**
MissingMethodException

**dotnet -info**
```
.NET Command Line Tools (2.0.0-preview2-006065)

Product Information:
 Version:            2.0.0-preview2-006065
 Commit SHA-1 hash:  7f50f322d5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\.dotnet\x64\sdk\2.0.0-preview2-006065\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25309-07
  Build    : 41f5fc94eedc889f086800c23f35bf14a8c75a9f
```

cc @dougbu

**Comment by jkotas** [comment] 2017-05-13 03:05
Duplicate of https://github.com/dotnet/coreclr/issues/11499. Already fixed.

**Closed by jkotas** 2017-05-13 03:05 UTC
