### ISSUE TITLE
RyuJIT/x86: JitStressRegs=8 CoreFx: System.Text.Tests.EncodingTest.TestRoundtrippingSpecificCodepageEncoding(encodingName: \"GB18030\", bytes: [129, 48, 137, 55, 129, ...], expected: \"├₧├ƒ├á├í├ó├ú\") [FAIL]

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8287] opened 2016-11-23 21:52 UTC
Commits:
9a29a6e868f4abd8b733891faa0b3f3209853248
dotnet/corefx@0d623b5b5e110a336eb743b6d9066f336a5177b4

Repro:
coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x64.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Text.Encoding.CodePages.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=8
RunTests.cmd c:\git\corefx\packages
```
**Output**
```
Using c:\git\coref2\packages as folder for resolving package dependencies.
Executing in C:\git\coref2\bin\tests\AnyOS.AnyCPU.Release\System.Text.Encoding.CodePages.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 13:49:43.77
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Text.Encoding.CodePages.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Text.Encoding.CodePages.Tests
Discovered:  System.Text.Encoding.CodePages.Tests
Starting:    System.Text.Encoding.CodePages.Tests
   System.Text.Tests.EncodingTest.TestRoundtrippingSpecificCodepageEncoding(encodingName: \"GB18030\", bytes: [129, 48, 137, 55, 129, ...], expected: \"├₧├ƒ├á├í├ó├ú\") [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [129, 48, 137, 55, 129, ...]
      Actual:   Byte[] [129, 48, 137, 55, 129, ...]
      Stack Trace:
            at System.Text.Tests.EncodingTest.TestRoundtrippingSpecificCodepageEncoding(String encodingName, Byte[] bytes, String expected)
Finished:    System.Text.Encoding.CodePages.Tests

=== TEST EXECUTION SUMMARY ===
   System.Text.Encoding.CodePages.Tests  Total: 740, Errors: 0, Failed: 1, Skipped: 0, Time: 62.105s
Finished running tests.  End time=13:50:55.83, Exit code = 1
```

**Comment by RussKeldorph** [comment] 2016-11-23 23:26
@dotnet/jit-contrib

**Comment by pgavlin** [comment] 2016-11-29 20:19
@RussKeldorph: the CoreCLR commit you've referenced above does not seem to exist:

```
>git checkout dbf8ce1173faf78b176771946b0bca9f9863bc9b
fatal: reference is not a tree: dbf8ce1173faf78b176771946b0bca9f9863bc9b

>git show dbf8ce1173faf78b176771946b0bca9f9863bc9b
fatal: bad object dbf8ce1173faf78b176771946b0bca9f9863bc9b
```

**Comment by RussKeldorph** [comment] 2016-11-29 20:44
@pgavlin Confirmed I'm a Git n00b.  Updated with closest likely commit.

**Comment by pgavlin** [comment] 2016-11-29 21:51
I can repro this using the CoreFX commit mentioned in the description and the latest bits from CoreCLR.

**Comment by pgavlin** [comment] 2016-11-29 22:37
The problematic method is `System.Text.GB18030Encoding:GetBytes(int,int,int,int,ref):int:this`.

In this case, LRSA decides to unspill a local that is assigned to a register that contains a live value:

```
1982.#880  I261  Def    Alloc esi  |     |     |     |V7  a|---- |---- |I261a|V13 a|
1985.#881  I261  Use *  Copy  ecx  |     |I261a|     |V7  a|---- |---- |I261a|V13 a|
1985.#882  V53   Use *  ReLod NA   |     |I261a|     |V7  a|---- |---- |I261a|V13 a|
                        Alloc ecx  |     |V53 a|     |V7  a|---- |---- |I261a|V13 a|
```

Here, `I261` is the result of a right shift. At location 1985, it is copied into `ecx` s.t. it is in a byte-addressable register that will be used as the source operand to a byte-sized indirect store. There is also a use of `V53` at location 1985, but this value has been spilled and must be reloaded. Unfortunately, the reload overwrites the value of `ecx`, resulting in bad codegen:

```
Generating: N1985 (???,???) [002090] -A-XG---R---             *  storeIndir byte   REG NA
IN01af:        mov      ecx, esi
IN01b0:        mov      ecx, dword ptr [V53 ebp-58H]
							V53 in reg ecx is becoming live  [001359]
							Live regs: 00000088 {ebx edi} => 0000008A {ecx ebx edi}
							V53 in reg ecx is becoming dead  [001359]
							Live regs: 0000008A {ecx ebx edi} => 00000088 {ebx edi}
							Live vars: {V00 V03 V05 V06 V07 V13 V53} => {V00 V03 V05 V06 V07 V13}
IN01b1:        mov      byte  ptr [ecx], cl
```

@sivarv @CarolEidt PTAL.

**Comment by pgavlin** [comment] 2016-11-29 22:40
There is another issue of interest here in that `Lowering::TreeNodeInfoInitCheckByteable` is over-constraining the address operand to indirect stores to byte-addressable registers. This is not necessary, and should be fixed. Although fixing the over-constraint may keep this specific issue from occurring, I do not believe that this is the root cause.

**Comment by sivarv** [comment] 2016-11-29 22:43
I am assigning this to myself.

**Closed** 2016-12-09 19:30 UTC
Labels: area-CodeGen, bug, JitStress, x86
