### ISSUE TITLE
BuildNumberMajor is incorrect for managed build libraries

### ISSUE THREAD

**Issue by gregolsky** [dotnet/coreclr#13395] opened 2017-08-16 12:12 UTC
We've recently migrated our app to .netcore 2.0 and discovered that when published our application no longer works - exiting with an error on almost all platforms we support (runtimes we built for were `win7-x64`, `ubuntu.16.04-x64`, `ubuntu.14.04-x64`):
```
Failed to initialize CoreCLR, HRESULT: 0x80004005
```

`linux-arm` worked fine.

We've been migrating the app in a branch before 2.0 was out officially using preview build: `dotnet-sdk-2.0.1-servicing-006924-win-x64.exe`, under which it all worked fine.
I attach ProcessMonitor output for a failing windows build, a strace log for failing ubuntu version of it and a windows run with set `$env:COREHOST_TRACE=1`: https://gist.github.com/gregolsky/754e5df1337aa83237ca2f02bfd764c8

We determined it works fine when publishing for this set of runtimes: `win-x64`, `ubuntu-x64` and `linux-arm` and we started using it as a workaround for this issue.

**Comment by janvorli** [comment] 2017-08-16 13:32
Can you please try to target linux-x64 instead of ubuntu-x64? In 2.0, we've made the runtime portable so that you don't need to target specific Linux distros. It should work on all supported distros that have glibc >= 2.12 (and on majority of others that are not officially supported too).

**Comment by janvorli** [comment] 2017-08-16 14:50
@weshaggard - I assume targeting distro specific rids should still work, right?

**Comment by weshaggard** [comment] 2017-08-16 17:40
Yes targeting distro specific rids should still work assuming that Microsoft.NETCore.Platforms is pulled in with the RID graph (https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json).

**Comment by weshaggard** [comment] 2017-08-16 17:41
@gregolsky can you post your project.assets.json file from your restore somewhere so we can look at what it contains?

**Comment by gregolsky** [comment] 2017-08-16 19:03
@weshaggard Here you go https://gist.githubusercontent.com/gregolsky/754e5df1337aa83237ca2f02bfd764c8/raw/dd1d121a16c00df26f052538c8039e22197a60ca/project.assets.json

Let me know, if I can help you with anything else.

**Comment by weshaggard** [comment] 2017-08-17 22:23
The asset file looks correct to me and I wasn't able to get a local repo. I could run an application that build with `win-x64` or `win7-x64`. Can you share with me the commands you are running? Are you publishing self-contained? Are you deploying the application to another machine? If so does it have the matching framework?

**Comment by gregolsky** [comment] 2017-08-18 07:31
> Are you publishing self-contained?
Yes.

>  Are you deploying the application to another machine?
No.

Here are the commands:
https://gist.github.com/gregolsky/63ce0bc146689800d8f4ce1d2f77cf4c

**Comment by weshaggard** [comment] 2017-08-18 17:26
cc @ericstj 

Thanks for the pointer I didn't realize you were building a open repo otherwise I would have just done that to repo.

I was able to follow the same steps as in your gist and repro the issue. The problem is not with the RID graph exactly it is caused by an interesting mix of dependencies and a bug in our file versioning. The primary problem is caused by the following conflict resolution:

```
Encountered conflict between 'CopyLocal:C:\Users\wesh\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.0\runtimes\win-x64\native\System.Private.CoreLib.dll' and 'CopyLocal:C:\Users\wesh\.nuget\packages\runtime.win7-x64.microsoft.netcore.runtime.coreclr\1.0.2\runtimes\win7-x64\lib\netstandard1.0\System.Private.CoreLib.dll'.  Choosing 'CopyLocal:C:\Users\wesh\.nuget\packages\runtime.win7-x64.microsoft.netcore.runtime.coreclr\1.0.2\runtimes\win7-x64\lib\netstandard1.0\System.Private.CoreLib.dll' because file version '4.6.24214.1' is greater than '4.6.1.0'.
```

With .NET Core 2.0 we flattened our package graph so we don't directly have a reference to Microsoft.NETCore.Runtime.CoreCLR package any longer but one of your dependencies (Lambda2Js -> Microsoft.NETCore.Portable.Compatibility -> Microsoft.NETCore.Runtime.CoreCLR 1.0.2) pulls in the 1.0.2 version of Microsoft.NETCore.Runtime.CoreCLR package which has the conflict with some files that are now in the runtime.win-x64.microsoft.netcore.app package and the older one ended up winning the conflict because of a bug in our file versioning (System.Private.CoreLib should not have a version of 4.6.1.0). 

The bug is caused by this line https://github.com/dotnet/coreclr/blob/master/dir.props#L149 which we should remove so the correct BuildNumberMajor gets plumbed through our targets. What I cannot track down yet is why we haven't found this issue yet or what triggered that to recently take affect. I will keep hunting.

The reason that switching to "win-x64" worked is because the older 1.0.2 package didn't have assets for that RID, it used win7-x64 as its RID, and so they weren't brought into the picture. 

@gregolsky there are a couple possible workarounds until we can fix this:

1. You can switch the the portable RID's (win-x64, linux-x64, etc) which is the model we are moving towards. 
2. You can directly reference the 2.0.0 version of Microsoft.NETCore.Runtime.CoreCLR package to upgrade the 1.0.2 reference you are getting pulled in and everything will work as expected.

**Comment by weshaggard** [comment] 2017-08-18 17:27
Re-titled and assigned to you @wtgodbe to get the file versioning issue fixed.

**Comment by gregolsky** [comment] 2017-08-18 19:53
Thanks a lot for looking into this. We already changed our runtime targets to `win-x64` and `ubuntu-x64` (may look into changing that to `linux-x64` as Jan pointed out) as you recommended and it worked like a charm.

**Comment by wtgodbe** [comment] 2017-08-24 18:52
Resolved by https://github.com/dotnet/coreclr/pull/13533

**Closed by wtgodbe** 2017-08-24 18:52 UTC

**Comment by Chida82** [comment] 2018-08-20 13:33
I think that the problem is in new net core 2.1 version.When I publish with Runtime ubuntu.16.04-x64 i have this error "Failed to initialize CoreCLR, HRESULT: 0x80004005".
I think the problem is about System.Private.CoreLib.dll. If I change manually only this dll with the linux-x64 dll, it works.

dotnet --info
.NET Core SDK (reflecting any global.json):
Version: 2.1.400
Commit: 8642e60a0f

Runtime Environment:
OS Name: Windows
OS Version: 10.0.17134
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
Version: 2.1.2
Commit: 811c3ce6c0

.NET Core SDKs installed:
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

This is strace

lstat("/home", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
28622 lstat("/home/privateName", {st_mode=S_IFDIR|0755, st_size=20480, ...}) = 0
28622 lstat("/home/privateName/test", {st_mode=S_IFDIR|0775, st_size=24576, ...}) = 0
28622 stat("/home/privateName/test/System.Private.CoreLib.dll", {st_mode=S_IFREG|0664, st_size=2177536, ...}) = 0
28622 open("/home/privateName/test/System.Private.CoreLib.dll", O_RDONLY) = 10
28622 fcntl(10, F_SETFD, FD_CLOEXEC) = 0
28622 fstat(10, {st_mode=S_IFREG|0664, st_size=2177536, ...}) = 0
28622 fcntl(10, F_DUPFD_CLOEXEC, 0) = 11
28622 fstat(11, {st_mode=S_IFREG|0664, st_size=2177536, ...}) = 0
28622 mmap(NULL, 2177536, PROT_READ, MAP_SHARED, 11, 0) = 0x7f29147e9000
28622 mprotect(0x7f289f260000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f250000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f256000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f590000, 192512, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5c0000, 12288, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5c3000, 12288, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f257000, 12288, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f25a000, 12288, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5c6000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5c7000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5c8000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5c9000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5ca000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5cb000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5cc000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5cd000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5ce000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5cf000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5d0000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5d1000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5d2000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f263000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5d3000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5e0000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5e0000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
28622 mprotect(0x7f289f5d4000, 8192, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f660000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f661000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5e1000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5e1000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
28622 mprotect(0x7f289f5d6000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f662000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f663000, 4096, PROT_READ|PROT_WRITE) = 0
28622 mprotect(0x7f289f5d7000, 4096, PROT_READ|PROT_WRITE) = 0
28622 write(2, "Failed to initialize CoreCLR, HR"..., 49) = 49
28622 write(2, "\n", 1) = 1
28630 futex(0xe7b7a4, FUTEX_WAIT_BITSET_PRIVATE, 1, {1565364, 237259000}, ffffffff <unfinished ...>
28622 brk(0xec1000) = 0xec1000
28622 munmap(0x7f2919638000, 2807904) = 0
28622 munmap(0x7f29198e6000, 2783048) = 0
28622 unlink("/tmp/clr-debug-pipe-28622-156536208-in") = 0
28622 unlink("/tmp/clr-debug-pipe-28622-156536208-out") = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
28622 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
28622 exit_group(-2147450743) = ?
28629 +++ exited with 137 +++

The version of System.Private.CoreLib.dll 4.6.24214.01. Commit Hash: abbb8f685929c7aeaa087dae46fedc1bc2af4b17

Can help me? Are there other solution more then "linux-x64" or "ubuntu-x64"?
Thanks
