### ISSUE TITLE
error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by v-haren** [dotnet/coreclr#22264] opened 2019-01-29 07:44 UTC
Failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x86_min_opt_ryujit/1161/

Failed log: 
C:\J\w\perf_perflab_---ce30617b\tests\src\runincontext\runincontext.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
C:\J\w\perf_perflab_---ce30617b\tests\dir.traversal.targets(25,5): error : (No message specified) [C:\J\w\perf_perflab_---ce30617b\tests\src\dirs.proj]
C:\J\w\perf_perflab_---ce30617b\tests\dir.traversal.targets(25,5): error : (No message specified) [C:\J\w\perf_perflab_---ce30617b\tests\build.proj]
    28 Warning(s)
    3 Error(s)

Time Elapsed 00:04:46.71
BUILDTEST: Error: build failed. Refer to the build log files for details:
    C:\J\w\perf_perflab_---ce30617b\bin\Logs\Tests_Managed_Windows_NT__x86__Release.log
    C:\J\w\perf_perflab_---ce30617b\bin\Logs\Tests_Managed_Windows_NT__x86__Release.wrn
    C:\J\w\perf_perflab_---ce30617b\bin\Logs\Tests_Managed_Windows_NT__x86__Release.err
Build step 'Execute Windows batch command' marked build as failure
[Current build status] check if current [FAILURE] is worse or equals then [FAILURE] and better or equals then [SUCCESS]
Run condition [Current build status] enabling perform for step [[Archive the artifacts]]
Archiving artifacts
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] MSBuild Error from category Build
[BFA] Done. 3s
[WS-CLEANUP] Deleting project workspace...Cannot delete workspace :remote file operation failed: C:\J\w\perf_perflab_---ce30617b at hudson.remoting.Channel@7acc45e9:JNLP4-connect connection from 131.107.147.193/131.107.147.193:56964: java.io.IOException: Unable to delete 'C:\J\w\perf_perflab_---ce30617b\Tools\net46\roslyn\tools\Microsoft.DiaSymReader.Native.amd64.dll'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
ERROR: Step �Delete workspace when build is done� failed: Cannot delete workspace: remote file operation failed: C:\J\w\perf_perflab_---ce30617b at hudson.remoting.Channel@7acc45e9:JNLP4-connect connection from 131.107.147.193/131.107.147.193:56964: java.io.IOException: Unable to delete 'C:\J\w\perf_perflab_---ce30617b\Tools\net46\roslyn\tools\Microsoft.DiaSymReader.Native.amd64.dll'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Finished: FAILURE

**Comment by RussKeldorph** [comment] 2019-02-25 18:18
Duplicate of #22179

**Closed by RussKeldorph** 2019-02-25 18:18 UTC
Labels: area-Infrastructure
