### ISSUE TITLE
[arm64] Test failed: JIT_HardwareIntrinsics._X86_Sse2_LoadAlignedVector128_r_LoadAlignedVector128_r_._X86_Sse2_LoadAlignedVector128_r_LoadAlignedVector128_r_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22000] opened 2019-01-16 01:53 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tst/21/

**Failed  tests:**
JIT_HardwareIntrinsics._X86_Sse2_LoadAlignedVector128_r_LoadAlignedVector128_r_._X86_Sse2_LoadAlignedVector128_r_LoadAlignedVector128_r_sh
GC_Scenarios._GCSimulator_GCSimulator_83_GCSimulator_83_._GCSimulator_GCSimulator_83_GCSimulator_83_sh

**Log:**
```
JIT_HardwareIntrinsics._X86_Sse2_LoadAlignedVector128_r_LoadAlignedVector128_r_._X86_Sse2_LoadAlignedVector128_r_LoadAlignedVector128_r_sh [FAIL]
        /n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitstress1_tst/bin/tests/Linux.arm64.Checked/JIT/HardwareIntrinsics/Reports/JIT.HardwareIntrinsics/X86/Sse2/LoadAlignedVector128_r/LoadAlignedVector128_r.output.txt/nRaw output:/nTest Harness Exitcode is : 137
```

**Comment by RussKeldorph** [comment] 2019-01-16 21:56
Assuming duplicate of #22010.  Feel free to re-open if not.

**Closed by RussKeldorph** 2019-01-16 21:56 UTC
Labels: JitStress, arch-arm64, area-CodeGen
