### ISSUE TITLE
[ARM32] Detection of race conditions

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#15394] opened 2017-12-06 16:35 UTC
There are several bugs related to multi threading (#12421, #13651, some our proprietary code also failed in this field).
@dotnet/arm32-contrib have you tried to use some tool like [ThreadSanitizer](https://a.llvm.org/docs/ThreadSanitizer.html) from clang for ARM platfrom?

**Comment by BruceForstall** [comment] 2017-12-06 16:44
@alpencolt I'm not aware of Microsoft using such tools (fyi, we haven't tested ARM on Linux much).

Maybe @sdmaclea on arm64 has looked into this?

also, cc @janvorli

**Comment by sdmaclea** [comment] 2017-12-06 17:03
I have not tried thread sanitizer on ARM64.

ARM64 has a few intermittent GC issues which are occasionally exposed during gcStress testing.  I have not had the time to track them down yet.  

For ARM32, I would make 100% sure GC stress is perfect for all tests.  Run tests dozens of times.  Investigate and root cause every failure..

**Comment by BruceForstall** [comment] 2017-12-06 17:21
I agree about making sure GC stress is clean.

@alpencolt Are you talking about RyuJIT/arm32 or LEGACY_BACKEND?

For RyuJIT, we have issues tracking GCStress=4 and GCStress=C:

https://github.com/dotnet/coreclr/issues/14383
https://github.com/dotnet/coreclr/issues/14856

For LEGACY_BACKEND, there are a number of issues regarding GCStress that have never been investigated (in favor of focusing on RyuJIT):

https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aarch-arm32+label%3A%22Legacy+Backend%22+gcstress+

**Comment by alpencolt** [comment] 2017-12-07 16:22
@sdmaclea  @BruceForstall thank you for response.
The issue is on LEGACY_BACKEND. But it looks multi-threaded issues (e.g. #12421) has the same behavior on both backends.

**Comment by BruceForstall** [comment] 2018-04-24 23:50
fyi, arm GCStress is almost clean now on both Ubuntu and Windows. There are still a few "random" failures that look like GCStress infrastructure issues, but no known JIT bugs.

**Comment by BruceForstall** [comment] 2019-01-09 21:00
@alpencolt Can we close this issue now? It doesn't seem like there's any value to keep it open.

**Comment by jeffschwMSFT** [comment] 2019-08-22 18:09
Closing per Bruce's comment.  We can reopen a new issue as necessary.

**Closed by jeffschwMSFT** 2019-08-22 18:09 UTC
Labels: arch-arm32, test enhancement
