### ISSUE TITLE
Build tests fails with CS0006.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#23496] opened 2019-03-27 19:13 UTC
It started to fail in all ci Build tests jobs after #23471. But the changes in #23471 look unrelated.

Error log:
```
F:\workspace\_work\1\s\tests\scripts\scripts.csproj : warning NU1603: scripts depends on Microsoft.DotNet.BuildTools.TestSuite (>= 1.0.0-prerelease-00629-04) but Microsoft.DotNet.BuildTools.TestSuite 1.0.0-prerelease-00629-04 was not found. An approximate best match of Microsoft.DotNet.BuildTools.TestSuite 1.0.0-prerelease-00704-04 was resolved. [F:\workspace\_work\1\s\tests\build.proj]
F:\workspace\_work\1\s\tests\src\Common\test_runtime\test_runtime.csproj : warning NU1603: cijobs 0.0.1.2 depends on Microsoft.DotNet.Cli.Utils (>= 1.0.0-dev-1457) but Microsoft.DotNet.Cli.Utils 1.0.0-dev-1457 was not found. An approximate best match of Microsoft.DotNet.Cli.Utils 1.0.0-preview1-002702 was resolved. [F:\workspace\_work\1\s\tests\build.proj]
F:\workspace\_work\1\s\Tools\packageresolve.targets(93,5): warning : The project 'F:\workspace\_work\1\s\tests\src\Common\CoreCLRTestLibrary\CoreCLRTestLibrary.csproj' was referenced more than once in the ProjectReferencesCreatingPackages property. Ignoring all but the first. [F:\workspace\_work\1\s\tests\src\Interop\IJW\ManagedCallingNative\ManagedCallingNative.csproj]
F:\workspace\_work\1\s\Tools\packageresolve.targets(93,5): warning : The project 'F:\workspace\_work\1\s\tests\src\Common\CoreCLRTestLibrary\CoreCLRTestLibrary.csproj' was referenced more than once in the ProjectReferencesCreatingPackages property. Ignoring all but the first. [F:\workspace\_work\1\s\tests\src\Interop\IJW\NativeCallingManaged\NativeCallingManaged.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\COM\Activator\Activator.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\ICastable\Castable.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\ExecInDefAppDom\ExecInDefAppDom.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\IJW\LoadIjwFromModuleHandle\LoadIjwFromModuleHandle.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\NativeCallable\NativeCallableTest.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\NativeLibraryResolveCallback\CallbackTests.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\NativeLibraryResolveEvent\ResolveEventTests.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\NativeLibraryResolveEvent\TestAsm\TestAsm.csproj]
CSC : error CS0006: Metadata file 'F:\workspace\_work\1\s\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.dll' could not be found [F:\workspace\_work\1\s\tests\src\Interop\PInvoke\CustomMarshalers\CustomMarshalersTest.csproj]
F:\workspace\_work\1\s\tests\dir.traversal.targets(25,5): error : (No message specified) [F:\workspace\_work\1\s\tests\src\dirs.proj]
F:\workspace\_work\1\s\tests\dir.traversal.targets(25,5): error : (No message specified) [F:\workspace\_work\1\s\tests\build.proj]
    4 Warning(s)
```

[Example](https://dev.azure.com/dnceng/public/_build/results?buildId=135078&view=logs)

@echesakovMSFT and @sbomer are investigating this issue.

cc @dotnet/jit-contrib

**Comment by sbomer** [comment] 2019-03-27 20:41
It seems like the way pipeline artifacts are downloaded has changed with the newest azure-pipelines agent. They are now placed into a subdirectory of the target path, like this: `targetPath/artifactName`.
I suspect the behavior was changed by https://github.com/Microsoft/azure-pipelines-agent/pull/2125/files, which looks like it was part of the recently released agent (https://github.com/Microsoft/azure-pipelines-agent/commit/dbf1bace18ec00c02f8e8fe2cfbdbd746ec01c4a). @TingluoHuang can you confirm?

Unfortunately, the documentation for the similar tasks (Publish/Download Build Artifacts: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops) suggest they don't upload subdirectories, so I don't think we can use these as a drop-in replacement.

**Comment by TingluoHuang** [comment] 2019-03-27 20:48
ACK.

**Comment by sbomer** [comment] 2019-03-27 20:48
The behavior I expect (and what our builds were relying on) is for this job to pass (https://github.com/dotnet/coreclr/pull/23499/files#diff-fec826feae04e51c0d94076385408bdcR7):
```
  - script: |
          mkdir $(Build.SourcesDirectory)/artifactDir
          echo hi > $(Build.SourcesDirectory)/artifactDir/test.txt
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: myartifact
      targetPath: $(Build.SourcesDirectory)/artifactDir
  - script: |
          rm $(Build.SourcesDirectory)/artifactDir/test.txt
          rmdir $(Build.SourcesDirectory)/artifactDir
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: myartifact
      targetPath: $(Build.SourcesDirectory)/artifactDir
  - script: |
          ls $(Build.SourcesDirectory)
          cat $(Build.SourcesDirectory)/artifactDir/test.txt
```
but it fails (https://dev.azure.com/dnceng/public/_build/results?buildId=135397) with
```
cat: /Users/vsts/agent/2.149.1/work/1/s/artifactDir/test.txt: No such file or directory
```

**Comment by TingluoHuang** [comment] 2019-03-27 21:15
the agent release has been reverted.

**Comment by sbomer** [comment] 2019-03-27 22:18
Seems like that has fixed it. Thank you!

**Comment by sbomer** [comment] 2019-03-27 22:21
From discussion with @TingluoHuang, it sounds like the bug should get fixed before the next agent rollout, and we don't need to do anything on our end (other than re-queueing builds). Thank you for getting the agent update reverted so quickly!

**Comment by echesakovMSFT** [comment] 2019-03-27 22:34
@sbomer Thank you for investigating this!

**Comment by sbomer** [comment] 2019-03-27 22:39
Thank you @echesakov and @sandreenko as well for investigating together!

**Comment by echesakovMSFT** [comment] 2019-03-27 23:05
@TingluoHuang Is it expected to see such errors after the changes rollback?
```

Job issues
·
1 error
No agent found in pool Hosted macOS which satisfies the specified demands: Agent.Version -gtVersion 2.149.1
```

https://dev.azure.com/dnceng/public/_build/results?buildId=135092

**Comment by echesakovMSFT** [comment] 2019-03-27 23:05
Reported by @sdmaclea in https://github.com/dotnet/core-eng/issues/5701#issuecomment-477379225

**Comment by sdmaclea** [comment] 2019-03-27 23:09
Since we are reporting.  I am seeing this too when re-running all test runs.
```
Artifact testbuild_Linux_musl_arm64_checked_innerloop_Logs already exists for build 135092.
```

**Comment by TingluoHuang** [comment] 2019-03-28 00:46
@echesakovMSFT yes, that is the side effect of the roll back, builds that queued right before i roll back the agent might hit that error, since when it actually tries to run, the agent with that version is gone.

**Comment by echesakovMSFT** [comment] 2019-03-29 19:17
The issue is resolved with the agent changes rollback.

**Closed by echesakovMSFT** 2019-03-29 19:17 UTC
Labels: area-Build, blocking-clean-ci
