### ISSUE TITLE
DateTime.ToString("zzz") on a DateTime with DateTimeKind.Utc returns 0 instead of the correct UTC offset.

### ISSUE THREAD

**Issue by billwert** [dotnet/coreclr#11119] opened 2017-04-21 00:07 UTC
Consider this code:
```csharp
var mytime = new System.DateTime(2017, 4, 20, 16, 48, 37, DateTimeKind.Utc);
string actual = mytime.ToString("zzz");
string expected = "-07:00";
temp = (actual == expected);
Console.WriteLine($"actual: {actual} expected: {expected} result: {actual == expected}");
```

On Mono and Desktop, this prints:
```actual: -07:00 expected: -07:00 result: True```

On CoreCLR, you get:
```actual: +00:00 expected: -07:00 result: False```

A similar result happens for ```ToString("%z")``` and ```ToString("zz")```.

The [documentation](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx#Anchor_39) states that the ```z``` modifiers should print the local machine's offset from UTC. (It does also state this isn't recommended for DateTime objects but it should still work.)

**Comment by danmosemsft** [comment] 2017-04-21 15:00
@tarekgh could you please take a look? this has shown up running actual customer code.

**Comment by tarekgh** [comment] 2017-04-21 15:23
I'll take a look

**Comment by tarekgh** [comment] 2017-04-21 17:24
The behavior of the Desktop/Mono is really a bad hack and doesn't make sense. I understand the doc mentioned the results bu the actual definition of the 'z' format is 

"zzz"	Hours and minutes offset from UTC.
https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx

Which is getting the offset from UTC of the passed datetime. while the passed dateTime is in UTC, the offset should be zero as coreclr is doing. 

Also in desktop if you run the code specified up, it will break under the debugger telling the user call is really wrong. look at the link http://stackoverflow.com/questions/28582774/datetimeinvalidlocalformat-occurred as example of people complaining about that. 

and if you look at the comment in the code

```C#
                } else if (dateTime.Kind == DateTimeKind.Utc) {
#if FEATURE_CORECLR
                    offset = TimeSpan.Zero;
#else // FEATURE_CORECLR
                    // This code path points to a bug in user code. It would make sense to return a 0 offset in this case.
                    // However, because it was only possible to detect this in Whidbey, there is user code that takes a 
                    // dependency on being serialize a UTC DateTime using the 'z' format, and it will work almost all the
                    // time if it is offset by an incorrect conversion to local time when parsed. Therefore, we need to 
                    // explicitly emit the local time offset, which we can do by removing the UTC flag.
                    InvalidFormatForUtc(format, dateTime);
                    dateTime = DateTime.SpecifyKind(dateTime, DateTimeKind.Local);
                    offset = TimeZoneInfo.GetLocalUtcOffset(dateTime, TimeZoneInfoOptions.NoThrowOnInvalidTime);
#endif // FEATURE_CORECLR
                } else {
```

so we are admitting the behavior of the desktop is wrong but we kept it for the sake of app compat. 

I'll close this issue as by design as I don't think we need to carry the wrong behavior even if it is not compatible with the desktop. please feel free to comment or reopen if you disagree. Thanks.

**Comment by tarekgh** [comment] 2017-04-21 17:29
Add one more useful link 
https://msdn.microsoft.com/en-us/library/ms172213(v=vs.110).aspx

**Comment by billwert** [comment] 2017-04-21 17:58
@tarekgh @danmosemsft @terrajobst My understanding is that we want .NET Core to be compatible with Desktop so that apps don't break moving to .NET Core. How does this line up in that perspective?

**Comment by danmosemsft** [comment] 2017-04-21 18:02
Ugh, another difficult call. Here's the MDA that fires:
https://msdn.microsoft.com/en-us/library/ms172213(v=vs.110).aspx

**Comment by tarekgh** [comment] 2017-04-21 18:04
We are expecting some behavior difference in some cases. I don't think we need to carry this bad behavior in coreclr.

**Comment by danmosemsft** [comment] 2017-04-21 18:10
> My understanding is that we want .NET Core to be compatible with Desktop so that apps don't break moving to .NET Core.

This is correct in the vast majority of cases but it's not a goal to be compatible to the extent that we must be strictly bug compatible. You have one datapoint, but this is also such a clear bug there is even an MDA for it, that has been flagging it for desktop code. Presumably there is also code that does not break (even improves) with this change. In the customer code you ran that hit this, did it malfunction after this point?

cc @terrajobst

**Comment by terrajobst** [comment] 2017-04-21 18:23
> My understanding is that we want .NET Core to be compatible with Desktop so that apps don't break moving to .NET Core. How does this line up in that perspective?

We also said we're not shooting for bug-by-bug compatibility. If the original behavior is a bug, we'll take the opportunity to fix it in .NET Core.

**Comment by billwert** [comment] 2017-04-21 18:52
Cool, thanks. It is useful to have these conversations.

> We also said we're not shooting for bug-to-bug compatibility. If the original behavior is a bug, we'll take the opportunity to fix it in .NET Core.

I agree that's where we started with .NET Core. Is that where we are today given that NS2.0 is implying some level of compatibility? Historically we fix bugs because we have strong reasons to; in a compatible release we would shy away from a behavior change like this without direct customer feedback to guide us. One useful outcome here is we'll have a good set of principles around how to think about changes like this.

**Comment by terrajobst** [comment] 2017-04-21 19:44
> I agree that's where we started with .NET Core

Sorry, I should have been clearer. That was the statement that was made after the compat push with .NET Standard 2.0.

**Comment by tarekgh** [comment] 2017-04-24 16:22
@billwert do you agree keeping the current behavior in coreclr or you still think we have to apply desktop behavior?

**Comment by danmosemsft** [comment] 2017-04-24 22:23
@billwert and I talked at length offline: I believe we are comfortable with leaving this as-is given it was sufficiently broken for us to write an MDA and document the pitfall. Before I close though @stephentoub do you have any reservations?

**Comment by stephentoub** [comment] 2017-04-25 12:55
Sounds good to leave it as-is.

**Closed by stephentoub** 2017-04-25 12:55 UTC
Labels: area-System.Globalization, bug
