### ISSUE TITLE
Crossgen unable to compile mscorlib.dll on Linux due to assert in JIT

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/coreclr#1884] opened 2015-10-28 15:42 UTC
After creating a debug build on Linux, running "./crossgen mscorlib.dll" in bin/Product/Linux.x64.Debug directory results in the following assert failure:

Assert failure(PID 41883 [0x0000a39b], Thread: 41883 [0xa39b]): Assertion failed 'callerArgNum < comp->info.compArgsCount' in 'System.Array:BinarySearch(ref,int,int,struct,ref):int' (IL size 119)

    File: /home/john/coreclr/src/jit/lower.cpp Line: 1910
    Image: /home/john/coreclr/bin/Product/Linux.x64.Debug/crossgen

This error first occurred with commit c96f748 on Oct 20.

**Comment by cmckinsey** [comment] 2015-10-28 20:35
@LLITCHEV PTAL.

**Comment by LLITCHEV** [comment] 2015-10-29 22:58
This is a System V struct passing tail call issue. Testing a fix.

**Comment by joshfree** [comment] 2015-11-02 18:10
@JohnChen0 can you verify the fix and close out this bug?  (I take it from https://github.com/dotnet/coreclr/issues/1923 that verification has already happened - can you confirm?)

**Comment by JohnChen0** [comment] 2015-11-02 22:39
Verified that the issue is fixed.

**Comment by kouvel** [comment] 2015-12-16 19:15
I'm seeing the same assert on the latest state of master as of this morning, when running crossgen on mscorlib.dll on Linux.

Assert failure(PID 62821 [0x0000f565], Thread: 62821 [0xf565]): Assertion failed 'callerArgNum < comp->info.compArgsCount' in 'System.Array:BinarySearch(ref,int,int,struct,ref):int' (IL size 119)

    File: /home/kouvel/e/clr/coreclr/src/jit/lower.cpp Line: 1967
    Image: /home/kouvel/e/clr/coreclr/bin/Product/Linux.x64.Debug/crossgen

The release build seems to work.

**Comment by LLITCHEV** [comment] 2015-12-16 20:54
This is most likely due to the FI of the 4.6.1 changes - potentially a bad merge. Will take a look.

**Comment by LLITCHEV** [comment] 2015-12-17 20:33
@kouvel As expected this regression was due to a bad conflict resolution from the RI/FI of the 4.6.1 changes. It is fixed with PR https://github.com/dotnet/coreclr/pull/2375
Please verify it works and close the issue.

**Comment by kouvel** [comment] 2016-01-05 18:48
Verified fixed, thanks!

**Closed by kouvel** 2016-01-05 18:48 UTC
Labels: bug, CodeGen
