### ISSUE TITLE
How can I pin `ref T` in class constructor and unpin it in Dispose?

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/coreclr#19880] opened 2018-09-10 02:31 UTC
How can I pin `ref T` in class constructor and unpin it in Dispose? (Repeat my question https://github.com/dotnet/corefx/issues/32155 here.)

**Comment by jkotas** [comment] 2018-09-10 04:13
Duplicate of dotnet/corefx#32155

**Closed by jkotas** 2018-09-10 04:13 UTC
