### ISSUE TITLE
JIT should emit "movbe" instead of "mov / bswap" on compatible hardware

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/coreclr#26735] opened 2019-09-16 19:01 UTC
In https://github.com/dotnet/coreclr/pull/18398, JIT got support for the `bswap` intrinsic. There's a comment in that issue that it would also be nice if the JIT could fold a "read-then-bswap" or a "bswap-then-write" instruction pair into a single `movbe` instruction on supported platforms. For certain application code which performs such reads and writes with high frequency, it can result in significant codegen savings. See in particular the codegen at https://github.com/dotnet/coreclr/issues/26729#issuecomment-531862356, where each "mov / bswap" pair could be a single "movbe".

There are a few ways to go about this. We could add a `movbe` intrinsic and have callers (like `BinaryPrimitives`) special-case that intrinsic if it is available. Though it'd probably be more convenient to leave all of the call sites unchanged and instead to have the JIT special-case these instruction pairs.

This could end up being particularly helpful for writes, as it could end up saving not just codegen size, but also the total number of allocated registers. Consider the following.

```cs
int i = GetInt();
BinaryPrimitives.WriteBigEndian(theSpan, i);
// keep using 'i' here
```

Since the `bswap` instruction mutates its register, the JIT currently needs to make a temporary copy of the value if _i_ is intended to be used elsewhere in the method.

```asm
mov eax, ebx  ; ebx = 'i', eax = copy of 'i'
bswap eax  ; eax = swapped(i)
mov dword ptr [rcx], eax  ; theSpan[0] = swapped(i)
````

All three of those instructions could be folded into a single `movbe` with no temporary registers required.

One complication is that there's no 16-bit `bswap` (it's instead a 16-bit `rol`), but there _is_ a 16-bit `movbe`, so the JIT would likely need to special-case that particular pattern.

category:cq
theme:intrinsics
skill-level:expert
cost:medium

**Comment by BruceForstall** [comment] 2019-09-18 17:13
cc @dotnet/jit-contrib

**Comment by jkotas** [comment] 2020-01-28 00:43
Duplicate of https://github.com/dotnet/runtime/issues/953

**Closed by jkotas** 2020-01-28 00:43 UTC
Labels: area-CodeGen, optimization
