### ISSUE TITLE
Invalid program crashes 32bit RyuJIT in Lowering::IsBinOpInRMWStoreInd

### ISSUE THREAD

**Issue by pentp** [dotnet/coreclr#13476] opened 2017-08-18 22:03 UTC
The following (invalid) program (when compiled in debug mode) crashes x86 RyuJIT. x64 and x86 with optimizations enabled (release mode) are not affected by this minimal repro, but a similar larger invalid method crashed in x86 release mode also (in `Lowering::LowerCompare`).
```C#
using System;
using System.Reflection.Emit;

class Program
{
	static void Main()
	{
		var dm = new DynamicMethod("test", typeof(void), null, typeof(Program) /*owner is required*/);
		var il = dm.GetILGenerator();
		il.DeclareLocal(typeof(int));
		il.Emit(OpCodes.Ldloc_0);
		il.Emit(OpCodes.Ldc_I4_1);
		il.Emit(OpCodes.Conv_I8); // source of trouble (removing this removes the crash)
		il.Emit(OpCodes.Add); // this looks invalid (int32 + int64), but should not crash JIT
		il.Emit(OpCodes.Stloc_0);
		il.Emit(OpCodes.Ret);
		var action = (Action)dm.CreateDelegate(typeof(Action));
		action();
	}
}

**Comment by mikedn** [comment] 2017-08-18 22:26
> but should not crash JIT

Hmm, sort of. The verifier must prevent invalid IL from being compiled but the verifier is disabled in CoreCLR and so invalid IL may result in "undefined behavior".

In checked JIT builds there's an importer asserts that fires when compiling such code:
https://github.com/dotnet/coreclr/blob/3ef633afa13a4dc1c4119489f14f77807d5daa28/src/jit/importer.cpp#L10268-L10277

Maybe this should be a "noway" assert.

**Comment by BruceForstall** [comment] 2017-08-18 23:11
@dotnet/jit-contrib

**Comment by mikedn** [comment] 2017-08-19 05:39
Looks like JIT32 compiles this code without problems. It generates:
```asm
0000001c 33 D2                xor         edx,edx 
0000001e 89 55 FC             mov         dword ptr [ebp-4],edx 
00000021 B8 01 00 00 00       mov         eax,1 
00000026 99                   cdq 
00000027 01 45 FC             add         dword ptr [ebp-4],eax 
```
It widens the i4 constant to i8 but then emits a i4 add instruction.

But if you change the code to store the result in a i8 lclvar then the following code is generated:
```asm
00000015 C7 45 F0 00 00 00 00 mov         dword ptr [ebp-10h],0 
0000001c C7 45 F4 00 00 00 00 mov         dword ptr [ebp-0Ch],0 
00000023 33 D2                xor         edx,edx 
00000025 89 55 F8             mov         dword ptr [ebp-8],edx 
00000028 8B 45 F8             mov         eax,dword ptr [ebp-8] 
0000002b 8B 55 FC             mov         edx,dword ptr [ebp-4] 
0000002e B9 01 00 00 00       mov         ecx,1 
00000033 8B D9                mov         ebx,ecx 
00000035 C1 FB 1F             sar         ebx,1Fh 
00000038 03 C1                add         eax,ecx 
0000003a 13 D3                adc         edx,ebx 
0000003c 89 45 F0             mov         dword ptr [ebp-10h],eax 
0000003f 89 55 F4             mov         dword ptr [ebp-0Ch],edx 
```
This looks strange, loc0 is 32 bit and it is initialized as such. But then a i8 is loaded from it and likely garbage is read from [ebp-4]. So it would seem that JIT32 too doesn't handle with kind of invalid IL correctly ("correct" meaning either rejecting the code or automatically widening i4 to i8 when needed).

**Comment by sandreenko** [comment] 2018-03-12 22:47
I checked that debug/checked ji32 also hits this assert in the importer;
Changing assert  to `noway_assert` doesn't change the behavior, it passes release without any messages and fails in checked/debug.
And because invalid IL may result in "undefined behavior" I close this issue as "not a bug".

Thanks @mikedn for the analysis.

**Closed by sandreenko** 2018-03-12 22:47 UTC
Labels: area-CodeGen, bug
