### ISSUE TITLE
Feature request: Escape analysis

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/coreclr#6738] opened 2016-08-13 18:16 UTC
This is a feature request for escape analysis.  HotSpot has it, and it makes a big difference (20% IIRC) to performance.

**Comment by swgillespie** [comment] 2016-08-15 18:49
There's an existing discussion about escape analysis here: https://github.com/dotnet/coreclr/issues/1784 - feel free to join the discussion there. Closing this as a duplicate of that issue.

**Closed by swgillespie** 2016-08-15 18:49 UTC
