### ISSUE TITLE
Possible JIT optimization bug related to value types >= 12 byte

### ISSUE THREAD

**Issue by 0x53A** [dotnet/coreclr#11090] opened 2017-04-19 23:34 UTC
ref https://github.com/Microsoft/visualfsharp/issues/2885

cc @dsyme , @blumu

We have an assembly, where the value of the ``System.Diagnostics.Debuggable`` attribute changes behaviour. The assembly was compiled with the F# compiler from VS 2017.

__INCORRECT:__

Console output:
> (1, 2, 3)-(1, 2, 3)-Foo-Foo2
> (1, 2, 3)-(5, 6, 7)-Foo-Foo2

Debuggable Flag:
``[assembly: Debuggable(DebuggableAttribute.DebuggingModes.DisableOptimizations)]``

__CORRECT:__

Console output:
> (1, 2, 3)-(5, 6, 7)-Foo-Foo2
> (1, 2, 3)-(5, 6, 7)-Foo-Foo2

Debuggable Flag:
``[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations)]``

------------------

As you can see from the console output, the first parameter is duplicated, and the second one ignored.

----------------------------

It seems to also be related to the size of the value type, as you can see in the comments in the attached code, it works with a value type < 12 byte and fails with a value type >= 12 byte.

(The original bugreport was with a Guid = 16 byte)

__Code:__

```F#

// 4 byte
// this passes
//let guid1 = 1
//let guid2 = 2

// 8 byte
// this passes
//let guid1 = struct (1,2)
//let guid2 = struct (5,6)

// 9 byte (but probably aligned to 12 byte)
// this fails
//let guid1 = struct (1,2,3uy)
//let guid2 = struct (5,6,7uy)

// 12 byte
// this fails
let guid1 = struct (1,2,3)
let guid2 = struct (5,6,7)

// 16 byte
// this fails
//let guid1 = struct (1,2,3,4)
//let guid2 = struct (5,6,7,8)

// 16 byte
// this fails
//let guid1 = System.Guid.NewGuid()
//let guid2 = System.Guid.NewGuid()

[<EntryPoint>]
let main _ =

    // If you take this `aux` function out of main, it does not repro anymore!
    let aux f = Printf.kprintf id f

    let x = aux "%A-%A-%s-%s" guid1 guid2 "Foo" "Foo2"
    let y = Printf.kprintf id "%A-%A-%s-%s" guid1 guid2 "Foo" "Foo2"

    System.Console.WriteLine(x)
    System.Console.WriteLine(y)

    if x <> y then
        failwith "What's going on, F#?"
    0
```

In the linked bugreport there are also two assemblies (and the disassembled IL) if you don't want to compile it yourself.

To repro you can create a new F# console project and switch from AnyCpu to x64. Debug configuration will work / Release will hit the bug.

### Impact:

In my humble opinion, this is an obscure but critical bug, because it silently corrupts data. If it would at least crash, then the user could realize that something went wrong somewhere.

### Version information:

__My OS:__
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393
```

__Original Bugreport:__

> Related information

> Operating system: Win 10, Win 2008 R2
> Branch: Official build of F# 4.1
> .NET Runtime: 4.5.2

**Comment by pgavlin** [comment] 2017-04-20 00:37
cc @dotnet/jit-contrib

**Comment by JosephTremoulet** [comment] 2017-04-21 18:30
This repros against net462, but not netcore.  I'm working on narrowing down what the issue is and whether it's specifcally been fixed in core vs just failing to repro...

**Comment by JosephTremoulet** [comment] 2017-04-25 00:28
This is an instance of #5164, which was fixed in coreclr master in #5394 (and ported to coreclr release/1.0.0 in #5422).  It is available in desktop starting with 4.7.

**Comment by RussKeldorph** [comment] 2017-04-26 20:17
@JosephTremoulet Thanks.  Closing since long-fixed in .NET Core.

**Closed by RussKeldorph** 2017-04-26 20:17 UTC
Labels: area-CodeGen, bug

**Comment by blumu** [comment] 2017-04-27 06:54
Note: The CLR bug is fixed only in .NET Core and .NET Framework 4.7 (released just 20 days ago). Unfortunately .NET Framework 4.7 is available only for Windows 10 Creators Update at the moment. So for most people the best workaround so far is to build in debug mode or in 32 bit (target either x86 or select `Prefer 32 bits` option in the F# project properties).
