### ISSUE TITLE
[JitStressRegs=3] System.Runtime.Tests crashes (Segmentation Fault)

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2681] opened 2016-01-15 08:13 UTC
**System.Runtime.Tests** crashes on Linux with COMPlus_JitStressRegs=3

**Configurations**

Linux
Coreclr checked build
Corefx release build
Commits
  Coreclr: 761fa468d2fb09d00044fa1848b884b657191876  (Wed Jan 13 18:15:58 2016 -0500)
  Corefx: 0824d9745687271503f7538d16f44f17f5ef5f18 (Tue Jan 12 14:49:52 2016 -0800)

**Assertion details**

Pass without COMPlus_JitStressRegs=3

```
corefx/bin/tests/Linux.AnyCPU.Release/System.Runtime.Tests/dnxcore50$ COMPlus_JitStressRegs=3 ./corerun xunit.console.netcore.exe System.Runtime.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests
Segmentation fault (core dumped)
```

**Comment by janvorli** [comment] 2016-01-15 12:52
Out of curiosity, I have taken a quick look at this issue and I can see that it is the same issue as #2380.
There is the same corruption of an address - the 32 low bits are replaced by the same value as in the other issue (the address becomes 0x7fff0000001b).
@LLITCHEV I am assigning this to you since you have the other issue on your plate.

**Comment by LLITCHEV** [comment] 2016-01-15 20:08
This is a duplicate of issue #2380 . Closing it as such.

**Closed by LLITCHEV** 2016-01-15 20:08 UTC
Labels: bug, CodeGen, Linux
