### ISSUE TITLE
broken arm ubuntu build from the recent update

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#23268] opened 2019-03-15 00:05 UTC
https://github.com/dotnet/coreclr/pull/23249  broke arm32 Ubuntu Jenkins testing (at least), see example [here](https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_crossgen_comparison_prtest).

@AaronRobinsonMSFT could you please fix it and explain why you merged PR with failed jobs?

cc @dotnet/arm32-contrib

**Comment by AaronRobinsonMSFT** [comment] 2019-03-15 00:11
The logs didn't indicate any build breaks, from what I saw they were related to non-relevant tests under  `src/tests/Regression`. I will look at what is happening here. Sorry.

**Comment by AaronRobinsonMSFT** [comment] 2019-03-15 02:05
>explain why you merged PR with failed jobs?

@sandreenko This was a mistake on my part for sure. The reason I merged was because of the consistently unreliable legs for some runs. See the number of times I needed to restart the legs for the revert https://github.com/dotnet/coreclr/pull/23269. There are so many false negative in these legs and "just rerun it" isn't really a good solution because it breeds a sense of unreliability. I also find it ironic that as soon as I started the PR with the fix, 2 crossgen runs failed within 5 minutes which were because of flaky infrastructure. I should have done more to investigate the failing runs, but the vast majority of the time it is because of flakiness in the system - that is why I merged the PR.

cc @RussKeldorph

**Comment by AaronRobinsonMSFT** [comment] 2019-03-15 04:18
Bah. Both my run as well as @jkoritzinsky's run has failures that appear to be unrelated to either change. I observe in the Azure pipline that both build for ARM on Windows and Linux. Both runs seemed to fail for macOS, but of course pass on rerun. The Jenkins runs seem to have no obvious reason for failure, especially since the Azure piplines pass. All that being said, I don't really know what to trust since both PRs have various levels of "pass". Once I get green from Azure pipline, I am going to check in and ignore the Jenkins runs because if I don't I think I will be here all night.

**Closed** 2019-03-15 05:24 UTC
Labels: arch-arm32, blocking-clean-ci, os-linux

**Comment by sandreenko** [comment] 2019-03-15 05:28
> @sandreenko This was a mistake on my part for sure. The reason I merged was because of the consistently unreliable legs for some runs. See the number of times I needed to restart the legs for the revert #23269. There are so many false negative in these legs and "just rerun it" isn't really a good solution because it breeds a sense of unreliability. I also find it ironic that as soon as I started the PR with the fix, 2 ARM runs failed within 5 minutes which were because of flaky infrastructure. I should have done more to investigate the failing runs, but the vast majority of the time it is because of flakiness in the system - that is why I merged the PR.

Yes, the current level of flakiness is awful 😢 . And ADO/Helix do not look like a silver bullet (especially after yesterday outage).

We still are trying to keep both system as green as possible, we ignore issues like: 
"Jenkins java closed conenction", but we try to take care of build and test failures with exclusion lists etc. However, for me it looks like it  gets harder each day, or maybe the last week was just very unlucky.


Thanks again for the fast fix.
