### ISSUE TITLE
Performance regression: two test cases of BinaryFormatter benchmarks

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/coreclr#25837] opened 2019-07-23 15:46 UTC
`BinaryFormatter` has improved in most of the scenarios but regressed in two.

```cmd
git clone https://github.com/dotnet/performance.git
cd performance
# if you don't have cli installed and want python script to download the latest cli for you
py .\scripts\benchmarks_ci.py -f netcoreapp2.2 netcoreapp3.0 --filter MicroBenchmarks.Serializers.Binary_FromStream*.BinaryFormatter* --join
# if you do
dotnet run -p .\src\benchmarks\micro\MicroBenchmarks.csproj -c Release -f netcoreapp2.2 --runtimes netcoreapp2.2 netcoreapp3.0 --filter MicroBenchmarks.Serializers.Binary_FromStream*.BinaryFormatter* --join
```

<details>

# Legend

* Statistical Test threshold: 5%, the noise filter: 0.3 ns
* Base is Median Base in ns
* Diff is Median Diff in ns

## MicroBenchmarks.Serializers.Binary_FromStream&lt;LoginViewModel&gt;.BinaryFormatter_

| conclusion |    Base |    Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | -------:| -------:| ---------:| -------- | -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Slower     | 3548.53 | 4241.57 |      0.84 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     | 3079.77 | 3532.44 |      0.87 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     | 6342.32 | 7924.98 |      0.80 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Slower     | 6128.08 | 8837.79 |      0.69 | several? | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Slower     | 4305.37 | 6670.36 |      0.65 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     | 3549.49 | 4219.47 |      0.84 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     | 2841.94 | 3569.24 |      0.80 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     | 4546.40 | 6214.64 |      0.73 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     | 3011.19 | 3439.31 |      0.88 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_FromStream&lt;Location&gt;.BinaryFormatter_

| conclusion |     Base |     Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | --------:| --------:| ---------:| --------:| -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Slower     |  6131.38 |  7115.85 |      0.86 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Same       |  5593.56 |  5880.08 |      0.95 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     | 10708.39 | 12367.90 |      0.87 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Slower     | 11267.39 | 13310.33 |      0.85 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Slower     |  7591.76 |  9466.51 |      0.80 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     |  6662.21 |  7086.75 |      0.94 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     |  5132.20 |  5557.92 |      0.92 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     |  8012.29 | 10781.54 |      0.74 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Same       |  5795.25 |  5910.92 |      0.98 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_FromStream&lt;IndexViewModel&gt;.BinaryFormatter_

| conclusion |     Base |     Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | --------:| --------:| ---------:| --------:| -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Same       | 32326.37 | 30719.73 |      1.05 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 28843.04 | 25224.19 |      1.14 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 56921.92 | 52475.32 |      1.08 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Same       | 57364.72 | 55731.01 |      1.03 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Same       | 40690.16 | 38777.48 |      1.05 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 34836.52 | 31085.96 |      1.12 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 27378.10 | 23658.07 |      1.16 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Same       | 44323.58 | 44974.90 |      0.99 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Same       | 28319.35 | 27182.62 |      1.04 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_ToStream&lt;Location&gt;.BinaryFormatter_

| conclusion |     Base |    Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | --------:| -------:| ---------:| -------- | -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Faster     |  5981.25 | 4691.99 |      1.27 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  5355.47 | 4169.72 |      1.28 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  9990.04 | 8079.11 |      1.24 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 10648.28 | 8291.15 |      1.28 | bimodal  | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     |  7140.79 | 5481.69 |      1.30 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  6121.40 | 5006.43 |      1.22 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  4691.03 | 3832.92 |      1.22 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Slower     |  7539.89 | 8192.40 |      0.92 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  5924.26 | 4552.19 |      1.30 | several? | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_ToStream&lt;LoginViewModel&gt;.BinaryFormatter_

| conclusion |    Base |    Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | -------:| -------:| ---------:| --------:| -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Faster     | 3249.93 | 2819.38 |      1.15 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 2776.90 | 2181.50 |      1.27 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 5767.36 | 4870.26 |      1.18 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 5860.24 | 4860.64 |      1.21 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 3930.25 | 2980.33 |      1.32 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 3306.81 | 2643.11 |      1.25 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 2622.29 | 1984.60 |      1.32 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 4264.51 | 4026.68 |      1.06 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 3043.79 | 2284.15 |      1.33 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_FromStream&lt;MyEventsListerViewModel&gt;.BinaryFormatter_

| conclusion |      Base |      Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | ---------:| ---------:| ---------:| --------:| -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Faster     | 104340.79 |  83891.19 |      1.24 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  90547.18 |  70333.26 |      1.29 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 183045.12 | 143473.27 |      1.28 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 173128.15 | 143093.05 |      1.21 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 137817.60 | 100173.88 |      1.38 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 105701.91 |  85966.28 |      1.23 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  80692.21 |  67042.49 |      1.20 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 139392.19 | 120719.45 |      1.15 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  89304.74 |  75531.70 |      1.18 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## System.Runtime.Serialization.Formatters.Tests.Perf_BinaryFormatter.DeserializeLargeList

| conclusion |         Base |         Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | ------------:| ------------:| ---------:| -------- | -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Faster     | 202982766.00 | 159668607.00 |      1.27 | several? | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 184741650.00 | 156320650.00 |      1.18 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 297074117.00 | 194326216.00 |      1.53 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 290627800.00 | 197671850.00 |      1.47 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 242895447.50 | 214820810.50 |      1.13 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 222741200.00 | 201951700.00 |      1.10 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 172635700.00 | 135831700.00 |      1.27 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 262203700.00 | 209753200.00 |      1.25 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Same       | 190299850.00 | 182242400.00 |      1.04 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_ToStream&lt;MyEventsListerViewModel&gt;.BinaryFormatter_

| conclusion |      Base |     Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | ---------:| --------:| ---------:| --------:| -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Faster     |  64644.79 | 52837.18 |      1.22 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  53535.29 | 42299.86 |      1.27 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 111901.06 | 82705.45 |      1.35 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 111071.20 | 83905.16 |      1.32 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     |  77499.61 | 58559.45 |      1.32 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  63404.85 | 50716.59 |      1.25 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  50603.05 | 40169.60 |      1.26 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  83344.00 | 71767.05 |      1.16 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     |  56755.24 | 46159.18 |      1.23 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_ToStream&lt;IndexViewModel&gt;.BinaryFormatter_

| conclusion |     Base |     Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | --------:| --------:| ---------:| --------:| -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Faster     | 21801.99 | 16622.85 |      1.31 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 19557.50 | 14987.94 |      1.30 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 38396.41 | 28393.31 |      1.35 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 42607.93 | 28710.15 |      1.48 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 28165.96 | 20103.48 |      1.40 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 22150.30 | 17510.06 |      1.27 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 17875.66 | 13764.04 |      1.30 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Same       | 28832.35 | 27407.53 |      1.05 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 20056.61 | 15977.80 |      1.26 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_FromStream&lt;CollectionsOfPrimitives&gt;.BinaryFormatter_

| conclusion |       Base |       Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | ----------:| ----------:| ---------:| -------- | -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Faster     | 1650543.04 | 1161440.68 |      1.42 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 1419407.84 | 1059746.27 |      1.34 | bimodal  | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 2652768.90 | 1931720.97 |      1.37 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 2618710.68 | 2021254.46 |      1.30 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 1979070.23 | 1504357.39 |      1.32 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 1769528.92 | 1386562.16 |      1.28 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 1355441.67 | 1022412.77 |      1.33 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 2491686.92 | 1955284.29 |      1.27 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 1480342.61 | 1169370.22 |      1.27 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

## MicroBenchmarks.Serializers.Binary_ToStream&lt;CollectionsOfPrimitives&gt;.BinaryFormatter_

| conclusion |       Base |       Diff | Base/Diff | Modality | Operating System     | Arch  | Processor Name                              | Base Runtime    | Diff Runtime                     |
| ---------- | ----------:| ----------:| ---------:| --------:| -------------------- | ----- | ------------------------------------------- | --------------- | --------------------------------- |
| Faster     | 1611539.80 | 1183061.01 |      1.36 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 1413580.65 | 1026612.16 |      1.38 |          | Windows 10.0.18362   | 64bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 2688871.92 | 1990456.73 |      1.35 |          | ubuntu 16.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 2755601.77 | 2014770.18 |      1.37 |          | ubuntu 18.04         | 64bit | Intel Xeon CPU E5-2673 v4 2.30GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-01|
| Faster     | 2299114.63 | 1416916.61 |      1.62 |          | macOS Mojave 10.14.5 | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 1708361.00 | 1242298.40 |      1.38 |          | Windows 10.0.18362   | 64bit | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 1285881.44 |  905778.80 |      1.42 |          | Windows 10.0.18362   | 64bit | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)  | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 2162959.26 | 1636955.31 |      1.32 |          | Windows 10.0.18362   | 64bit | AMD Ryzen 7 1800X                           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|
| Faster     | 1453559.01 | 1078030.42 |      1.35 |          | Windows 10.0.18362   | 32bit | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 2.2.6 | .NET Core 3.0.0-preview8-27919-09|

</details>

/cc @danmosemsft @billwert @DrewScoggins

**Comment by danmosemsft** [comment] 2019-07-23 15:54
https://github.com/dotnet/corefx/commit/190132d89e47d2623372485b207f4371e05529e1 is the only change in this period to BinaryFormatter itself.

cc @ViktorHofer @Anipik

**Comment by ViktorHofer** [comment] 2019-07-26 08:30
@Anipik can you please take a look? IIRC you run benchmarks when you made the change to ConcurrentDictionary.

**Comment by Anipik** [comment] 2019-07-26 15:08
This change was made in dec 2017 and went into netcoreapp2.1 in may 2018.

The regression results that posted are between netcoreapp2.2 and netcoreapp3.0. so i dont think this change is causing this regression

**Comment by ViktorHofer** [comment] 2019-07-26 15:09
OK thanks for checking!

**Comment by danmosemsft** [comment] 2019-08-02 20:42
Possibly related to SerializationGuard? The callstack would show.
https://github.com/dotnet/corefx/pull/34834
https://github.com/dotnet/corefx/issues/36723

**Comment by adamsitnik** [comment] 2019-08-26 13:20
This issue is caused by the `SerializationGuard`:

![obraz](https://user-images.githubusercontent.com/6011991/63693246-d7aec600-c813-11e9-8775-867fa46761f4.png)

The 20% is spent in:

https://github.com/dotnet/coreclr/blob/9bd2787a9dd2aa4d2b7d4f72afebc3dbe896e896/src/vm/comsynchronizable.cpp#L1432-L1434

@bartonjs @GrabYourPitchforks please excuse me if this question is stupid, but is this possible to call a native CoreCLR method using a managed reflection API?

Or this check tries to make sure nobody is using reflection to call: https://github.com/dotnet/coreclr/blob/52651008a5fb72eb678467cd2eb42aac4e5334e8/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs#L322-L323

If so, it there any cheaper way for prohibiting that?

**Comment by bartonjs** [comment] 2019-08-26 13:37
> If so, it there any cheaper way for prohibiting that?

Not securely, no.

Since use of BinaryFormatter is discouraged, the numbers are barely in the microsecond range, and it's a security feature closing as intentional.

**Closed by bartonjs** 2019-08-26 13:37 UTC
Labels: area-System.Runtime, tenet-performance
