### ISSUE TITLE
Hung .NET Core console app - F5 launch from VS 

### ISSUE THREAD

**Issue by AArnott** [dotnet/coreclr#18680] opened 2018-06-27 23:42 UTC
A .NET Core 2.1 console app hung (right after I pressed Ctrl+C which the console app handles) and inspection suggests the code required to exit the app never executed because the method could not be JITted.

[Dump file](https://microsoft-my.sharepoint.com/:u:/p/andarno/Eahy34c1IvpOgtMkgCPvKQAB2QNonNUbsvL3LcORNs62BQ?e=iA5Cop)

```
#  8  Id: 3fb4.63ac Suspend: 0 Teb: 00000075`fbb6a000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 00000075`fcdfd428 00007ffa`16c89252 ntdll!NtWaitForSingleObject+0x14
01 00000075`fcdfd430 00007ff9`944d7778 KERNELBASE!WaitForSingleObjectEx+0xa2
02 (Inline Function) --------`-------- coreclr!CLREventWaitHelper2+0x6 [e:\a\_work\31\s\src\vm\synch.cpp @ 385] 
03 00000075`fcdfd4d0 00007ff9`9472765d coreclr!CLREventWaitHelper+0x20 [e:\a\_work\31\s\src\vm\synch.cpp @ 411] 
04 (Inline Function) --------`-------- coreclr!CLREventBase::WaitEx+0x12 [e:\a\_work\31\s\src\vm\synch.cpp @ 483] 
05 (Inline Function) --------`-------- coreclr!CLREventBase::Wait+0x12 [e:\a\_work\31\s\src\vm\synch.cpp @ 426] 
06 00000075`fcdfd530 00007ff9`946547c0 coreclr!Thread::WaitSuspendEventsHelper+0xa9 [e:\a\_work\31\s\src\vm\threadsuspend.cpp @ 5954] 
07 (Inline Function) --------`-------- coreclr!Thread::WaitSuspendEvents+0x8 [e:\a\_work\31\s\src\vm\threadsuspend.cpp @ 5991] 
08 00000075`fcdfd5f0 00007ff9`944e1e81 coreclr!Thread::RareEnablePreemptiveGC+0x172bd0 [e:\a\_work\31\s\src\vm\threadsuspend.cpp @ 3514] 
09 (Inline Function) --------`-------- coreclr!Thread::EnablePreemptiveGC+0x126 [e:\a\_work\31\s\src\vm\threads.h @ 2163] 
0a 00000075`fcdfd630 00007ff9`94519191 coreclr!Thread::RareDisablePreemptiveGC+0x215 [e:\a\_work\31\s\src\vm\threadsuspend.cpp @ 3036] 
0b (Inline Function) --------`-------- coreclr!Thread::DisablePreemptiveGC+0x5b [e:\a\_work\31\s\src\vm\threads.h @ 2107] 
0c (Inline Function) --------`-------- coreclr!GCHolderBase::PopInternal+0x6c [e:\a\_work\31\s\src\vm\threads.h @ 5949] 
0d (Inline Function) --------`-------- coreclr!GCPreemp::{dtor}+0x6c [e:\a\_work\31\s\src\vm\threads.h @ 6307] 
0e 00000075`fcdfd680 00007ff9`94517e12 coreclr!invokeCompileMethod+0x18d [e:\a\_work\31\s\src\vm\jitinterface.cpp @ 12263] 
0f 00000075`fcdfd710 00007ff9`944ed178 coreclr!CallCompileMethodWithSEHWrapper+0x52 [e:\a\_work\31\s\src\vm\jitinterface.cpp @ 12306] 
10 00000075`fcdfd7a0 00007ff9`94596272 coreclr!UnsafeJitFunction+0x4e8 [e:\a\_work\31\s\src\vm\jitinterface.cpp @ 12803] 
11 00000075`fcdfdd70 00007ff9`946ae8fd coreclr!MethodDesc::JitCompileCodeLocked+0x1fe [e:\a\_work\31\s\src\vm\prestub.cpp @ 841] 
12 00000075`fcdfdf10 00007ff9`945966ee coreclr!MethodDesc::JitCompileCodeLockedEventWrapper+0x118b39 [e:\a\_work\31\s\src\vm\prestub.cpp @ 716] 
13 00000075`fcdfe030 00007ff9`945956e8 coreclr!MethodDesc::JitCompileCode+0x36e [e:\a\_work\31\s\src\vm\prestub.cpp @ 636] 
14 (Inline Function) --------`-------- coreclr!MethodDesc::PrepareILBasedCode+0x13a [e:\a\_work\31\s\src\vm\prestub.cpp @ 310] 
15 (Inline Function) --------`-------- coreclr!MethodDesc::PrepareCode+0x13a [e:\a\_work\31\s\src\vm\prestub.cpp @ 292] 
16 (Inline Function) --------`-------- coreclr!MethodDesc::PrepareInitialCode+0x163 [e:\a\_work\31\s\src\vm\prestub.cpp @ 248] 
17 00000075`fcdfe130 00007ff9`9450ba1a coreclr!MethodDesc::DoPrestub+0x5b8 [e:\a\_work\31\s\src\vm\prestub.cpp @ 1812] 
18 00000075`fcdfe280 00007ff9`9461e955 coreclr!PreStubWorker+0x37a [e:\a\_work\31\s\src\vm\prestub.cpp @ 1548] 
19 00000075`fcdfe510 00007ff9`34b70e7a coreclr!ThePreStub+0x55 [E:\A\_work\31\s\src\vm\amd64\ThePreStubAMD64.asm @ 22] 
1a 00000075`fcdfe5c0 00007ff9`8bfbcb39 StreamJsonRpc!StreamJsonRpc.HeaderDelimitedMessageHandler+<ReadCoreAsync>d__20.MoveNext()+0x33a*** WARNING: Unable to verify checksum for StreamJsonRpc.dll
 [D:\git\streamjsonrpc\src\StreamJsonRpc\HeaderDelimitedMessageHandler.cs @ 111] 
1b 00000075`fcdfe880 00007ff9`8c236340 System_Private_CoreLib!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x89
1c 00000075`fcdfe900 00007ff9`8c0d7c80 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].MoveNext()+0xa0
1d 00000075`fcdfe970 00007ff9`8c0a4579 System_Private_CoreLib!System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)+0x140
1e 00000075`fcdfea00 00007ff9`8c0707a4 System_Private_CoreLib!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)+0x79
1f 00000075`fcdfea60 00007ff9`8c0d5d0d System_Private_CoreLib!System.Threading.Tasks.Task.RunContinuations(System.Object)+0x184
20 00000075`fcdfeb30 00007ff9`8c0b2df9 System_Private_CoreLib!System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+0x2c5fd
21 00000075`fcdfeb70 00007ff9`8c18fc23 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib]].SetExistingTaskResult(Int32)+0xffffffff`fffda7a9
22 00000075`fcdfebb0 00007ff9`34b7235b System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()+0x43
23 00000075`fcdfebf0 00007ff9`8bfbcb39 StreamJsonRpc!StreamJsonRpc.ReadBufferingStream+<FillBufferAsync>d__27.MoveNext()+0x3ab [D:\git\streamjsonrpc\src\StreamJsonRpc\Reflection\MethodSignature.cs @ 39] 
24 00000075`fcdfece0 00007ff9`8c239200 System_Private_CoreLib!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x89
25 00000075`fcdfed60 00007ff9`8c0d7c80 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].MoveNext()+0x2f60
26 00000075`fcdfedd0 00007ff9`8c0a4579 System_Private_CoreLib!System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)+0x140
27 00000075`fcdfee60 00007ff9`8c0707a4 System_Private_CoreLib!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)+0x79
28 00000075`fcdfeec0 00007ff9`8c076c44 System_Private_CoreLib!System.Threading.Tasks.Task.RunContinuations(System.Object)+0x184
29 00000075`fcdfef90 00007ff9`8c0d7d14 System_Private_CoreLib!System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+0xffffffff`fffcd534
2a 00000075`fcdfefd0 00007ff9`8c0d7e92 System_Private_CoreLib!System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].Complete(System.__Canon, System.Func`3<System.__Canon,System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.IAsyncResult, Boolean)+0xffffffff`ffe99854
2b 00000075`fcdff010 00007ff9`8bfbcb39 System_Private_CoreLib!System.Threading.Tasks.TaskFactory`1+FromAsyncTrimPromise`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].CompleteFromAsyncResult(System.IAsyncResult)+0xffffffff`ffe998a2
2c 00000075`fcdff070 00007ff9`8c0707ff System_Private_CoreLib!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x89
2d 00000075`fcdff0f0 00007ff9`8c06f52e System_Private_CoreLib!System.Threading.Tasks.Task.RunContinuations(System.Object)+0x1df
2e 00000075`fcdff1c0 00007ff9`8c0a66ac System_Private_CoreLib!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)+0x1be
2f 00000075`fcdff260 00007ff9`9461f3b3 System_Private_CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()+0x19c
30 00000075`fcdff300 00007ff9`94589e41 coreclr!CallDescrWorkerInternal+0x83 [E:\A\_work\31\s\src\vm\amd64\CallDescrWorkerAMD64.asm @ 101] 
31 (Inline Function) --------`-------- coreclr!CallDescrWorkerWithHandler+0x53 [e:\a\_work\31\s\src\vm\callhelpers.cpp @ 78] 
32 00000075`fcdff340 00007ff9`9458933f coreclr!MethodDescCallSite::CallTargetWorker+0x2b5 [e:\a\_work\31\s\src\vm\callhelpers.cpp @ 628] 
33 (Inline Function) --------`-------- coreclr!MethodDescCallSite::Call_RetBool+0x15 [e:\a\_work\31\s\src\vm\callhelpers.h @ 433] 
34 00000075`fcdff490 00007ff9`945a37f6 coreclr!QueueUserWorkItemManagedCallback+0x7f [e:\a\_work\31\s\src\vm\comthreadpool.cpp @ 451] 
35 00000075`fcdff580 00007ff9`945a3652 coreclr!ManagedThreadBase_DispatchInner+0x5a [e:\a\_work\31\s\src\vm\threads.cpp @ 8852] 
36 00000075`fcdff5c0 00007ff9`945a3551 coreclr!ManagedThreadBase_DispatchMiddle+0x76 [e:\a\_work\31\s\src\vm\threads.cpp @ 8901] 
37 00000075`fcdff6c0 00007ff9`945a2e10 coreclr!ManagedThreadBase_DispatchOuter+0x91 [e:\a\_work\31\s\src\vm\threads.cpp @ 9140] 
38 (Inline Function) --------`-------- coreclr!ManagedThreadBase_FullTransitionWithAD+0x56 [e:\a\_work\31\s\src\vm\threads.cpp @ 9199] 
39 (Inline Function) --------`-------- coreclr!ManagedThreadBase::ThreadPool+0x56 [e:\a\_work\31\s\src\vm\threads.cpp @ 9241] 
3a 00000075`fcdff730 00007ff9`945a2695 coreclr!ManagedPerAppDomainTPCount::DispatchWorkItem+0xe0 [e:\a\_work\31\s\src\vm\threadpoolrequest.cpp @ 757] 
3b (Inline Function) --------`-------- coreclr!ThreadpoolMgr::ExecuteWorkRequest+0x47 [e:\a\_work\31\s\src\vm\win32threadpool.cpp @ 1560] 
3c 00000075`fcdff890 00007ff9`944d3678 coreclr!ThreadpoolMgr::WorkerThreadStart+0x1d5 [e:\a\_work\31\s\src\vm\win32threadpool.cpp @ 2024] 
3d 00000075`fcdffa90 00007ffa`197a3034 coreclr!Thread::intermediateThreadProc+0x88 [e:\a\_work\31\s\src\vm\threads.cpp @ 2255] 
3e 00000075`fcdffc50 00007ffa`19e01431 kernel32!BaseThreadInitThunk+0x14
3f 00000075`fcdffc80 00000000`00000000 ntdll!RtlUserThreadStart+0x21

   9  Id: 3fb4.b958 Suspend: 0 Teb: 00000075`fbb6c000 Unfrozen
 # Child-SP          RetAddr           Call Site
00 00000075`fcf7b8f8 00007ffa`19dadc63 ntdll!NtWaitForAlertByThreadId+0x14
01 00000075`fcf7b900 00007ffa`19dada64 ntdll!RtlpWaitOnAddressWithTimeout+0x43
02 00000075`fcf7b930 00007ffa`19da83e7 ntdll!RtlpWaitOnCriticalSection+0x164
03 00000075`fcf7b9e0 00007ffa`19da8300 ntdll!RtlpEnterCriticalSectionContended+0xd7
04 00000075`fcf7ba10 00007ff9`944e19b3 ntdll!RtlEnterCriticalSection+0x40
05 (Inline Function) --------`-------- coreclr!UnsafeEnterCriticalSection+0x9 [e:\a\_work\31\s\src\inc\unsafe.h @ 19] 
06 00000075`fcf7ba40 00007ff9`94518fad coreclr!CrstBase::Enter+0x67 [e:\a\_work\31\s\src\vm\crst.cpp @ 319] 
07 00000075`fcf7ba80 00007ff9`948eb919 coreclr!Debugger::DoNotCallDirectlyPrivateLock+0x39 [e:\a\_work\31\s\src\debug\ee\debugger.cpp @ 365] 
08 (Inline Function) --------`-------- coreclr!Debugger::AcquireDebuggerLock+0x5 [e:\a\_work\31\s\src\debug\ee\debugger.h @ 2313] 
09 (Inline Function) --------`-------- coreclr!FunctionBase<Debugger *,&Debugger::AcquireDebuggerLock,&Debugger::ReleaseDebuggerLock,2>::DoAcquire+0x5 [e:\a\_work\31\s\src\inc\holder.h @ 750] 
0a (Inline Function) --------`-------- coreclr!BaseHolder<Debugger *,FunctionBase<Debugger *,&Debugger::AcquireDebuggerLock,&Debugger::ReleaseDebuggerLock,2>,0,&CompareDefault<Debugger *>,2>::Acquire+0xd [e:\a\_work\31\s\src\inc\holder.h @ 296] 
0b 00000075`fcf7bab0 00007ff9`948ea26b coreclr!Debugger::LockForEventSending+0x25 [e:\a\_work\31\s\src\debug\ee\debugger.cpp @ 6467] 
0c 00000075`fcf7bae0 00007ff9`947b09cb coreclr!Debugger::LoadClass+0x7b [e:\a\_work\31\s\src\debug\ee\debugger.cpp @ 10210] 
0d 00000075`fcf7bb50 00007ff9`9466df7b coreclr!TypeHandle::NotifyDebuggerLoad+0x127 [e:\a\_work\31\s\src\vm\class.cpp @ 1539] 
0e 00000075`fcf7bb90 00007ff9`94508622 coreclr!ClassLoader::LoadTypeHandleForTypeKey_Body+0x16876b [e:\a\_work\31\s\src\vm\clsload.cpp @ 4325] 
0f 00000075`fcf7c7e0 00007ff9`9458ae5b coreclr!ClassLoader::LoadTypeHandleForTypeKey+0x9e [e:\a\_work\31\s\src\vm\clsload.cpp @ 4044] 
10 00000075`fcf7c870 00007ff9`9458d912 coreclr!ClassLoader::LoadTypeDefThrowing+0x24b [e:\a\_work\31\s\src\vm\clsload.cpp @ 2887] 
11 00000075`fcf7ca40 00007ff9`9458c6ae coreclr!ClassLoader::LoadTypeDefOrRefThrowing+0x442 [e:\a\_work\31\s\src\vm\clsload.cpp @ 3065] 
12 00000075`fcf7cb90 00007ff9`9452470c coreclr!SigPointer::GetTypeHandleThrowing+0x79e [e:\a\_work\31\s\src\vm\siginfo.cpp @ 1507] 
13 00000075`fcf7cf00 00007ff9`bfb18a5c coreclr!CEEInfo::getArgClass+0x1bc [e:\a\_work\31\s\src\vm\jitinterface.cpp @ 9688] 
14 00000075`fcf7d0d0 00007ff9`bfb1a2d0 clrjit!Compiler::lvaInitTypeRef+0x3ac [e:\a\_work\31\s\src\jit\lclvars.cpp @ 262] 
15 00000075`fcf7d170 00007ff9`bfb1a703 clrjit!Compiler::compCompileHelper+0x1d0 [e:\a\_work\31\s\src\jit\compiler.cpp @ 6116] 
16 00000075`fcf7d220 00007ff9`bfb09347 clrjit!Compiler::compCompile+0x253 [e:\a\_work\31\s\src\jit\compiler.cpp @ 5599] 
17 00000075`fcf7d2e0 00007ff9`bfb09d62 clrjit!jitNativeCode+0x267 [e:\a\_work\31\s\src\jit\compiler.cpp @ 6908] 
18 00000075`fcf7d4a0 00007ff9`945190e9 clrjit!CILJit::compileMethod+0xa2 [e:\a\_work\31\s\src\jit\ee_il_dll.cpp @ 303] 
19 (Inline Function) --------`-------- coreclr!invokeCompileMethodHelper+0x6b [e:\a\_work\31\s\src\vm\jitinterface.cpp @ 12187] 
1a 00000075`fcf7d510 00007ff9`94517e12 coreclr!invokeCompileMethod+0xe5 [e:\a\_work\31\s\src\vm\jitinterface.cpp @ 12254] 
1b 00000075`fcf7d5a0 00007ff9`944ed178 coreclr!CallCompileMethodWithSEHWrapper+0x52 [e:\a\_work\31\s\src\vm\jitinterface.cpp @ 12306] 
1c 00000075`fcf7d630 00007ff9`94596272 coreclr!UnsafeJitFunction+0x4e8 [e:\a\_work\31\s\src\vm\jitinterface.cpp @ 12803] 
1d 00000075`fcf7dc00 00007ff9`946ae8fd coreclr!MethodDesc::JitCompileCodeLocked+0x1fe [e:\a\_work\31\s\src\vm\prestub.cpp @ 841] 
1e 00000075`fcf7dda0 00007ff9`945966ee coreclr!MethodDesc::JitCompileCodeLockedEventWrapper+0x118b39 [e:\a\_work\31\s\src\vm\prestub.cpp @ 716] 
1f 00000075`fcf7dec0 00007ff9`945956e8 coreclr!MethodDesc::JitCompileCode+0x36e [e:\a\_work\31\s\src\vm\prestub.cpp @ 636] 
20 (Inline Function) --------`-------- coreclr!MethodDesc::PrepareILBasedCode+0x13a [e:\a\_work\31\s\src\vm\prestub.cpp @ 310] 
21 (Inline Function) --------`-------- coreclr!MethodDesc::PrepareCode+0x13a [e:\a\_work\31\s\src\vm\prestub.cpp @ 292] 
22 (Inline Function) --------`-------- coreclr!MethodDesc::PrepareInitialCode+0x163 [e:\a\_work\31\s\src\vm\prestub.cpp @ 248] 
23 00000075`fcf7dfc0 00007ff9`9450ba1a coreclr!MethodDesc::DoPrestub+0x5b8 [e:\a\_work\31\s\src\vm\prestub.cpp @ 1812] 
24 00000075`fcf7e110 00007ff9`9461e955 coreclr!PreStubWorker+0x37a [e:\a\_work\31\s\src\vm\prestub.cpp @ 1548] 
25 00000075`fcf7e3a0 00007ff9`8c0c1d25 coreclr!ThePreStub+0x55 [E:\A\_work\31\s\src\vm\amd64\ThePreStubAMD64.asm @ 22] 
26 00000075`fcf7e450 00007ff9`8c0958e0 System_Private_CoreLib!System.Threading.CancellationTokenSource.InternalRegister(System.Action`1<System.Object>, System.Object, System.Threading.SynchronizationContext, System.Threading.ExecutionContext)+0x2c5
27 00000075`fcf7e4e0 00007ff9`8c095813 System_Private_CoreLib!System.Threading.CancellationToken.Register(System.Action`1<System.Object>, System.Object, Boolean, Boolean)+0x90
28 00000075`fcf7e550 00007ff9`34b75ae1 System_Private_CoreLib!System.Threading.CancellationToken.Register(System.Action`1<System.Object>, System.Object, Boolean)+0x23
29 00000075`fcf7e590 00007ff9`8bfbcb39 StreamJsonRpc!StreamJsonRpc.JsonRpc+<InvokeCoreAsync>d__89`1[[System.__Canon, System.Private.CoreLib]].MoveNext()+0xdd1 [D:\git\streamjsonrpc\src\StreamJsonRpc\JsonRpc.cs @ 948] 
2a 00000075`fcf7e950 00007ff9`8c236340 System_Private_CoreLib!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x89
2b 00000075`fcf7e9d0 00007ff9`8c0d7c80 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].MoveNext()+0xa0
2c 00000075`fcf7ea40 00007ff9`8c0a4579 System_Private_CoreLib!System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)+0x140
2d 00000075`fcf7ead0 00007ff9`8c0707a4 System_Private_CoreLib!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)+0x79
2e 00000075`fcf7eb30 00007ff9`8c0d5d0d System_Private_CoreLib!System.Threading.Tasks.Task.RunContinuations(System.Object)+0x184
2f 00000075`fcf7ec00 00007ff9`8c0b2df9 System_Private_CoreLib!System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+0x2c5fd
30 00000075`fcf7ec40 00007ff9`8c18fc23 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib]].SetExistingTaskResult(Int32)+0xffffffff`fffda7a9
31 00000075`fcf7ec80 00007ff9`34ba7792 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()+0x43
32 00000075`fcf7ecc0 00007ff9`8bfbcb39 StreamJsonRpc!StreamJsonRpc.DelimitedMessageHandler+<WriteAsync>d__23.MoveNext()+0x742 [D:\git\streamjsonrpc\src\StreamJsonRpc\HeaderDelimitedMessageHandler.cs @ 93] 
33 00000075`fcf7eea0 00007ff9`8c239200 System_Private_CoreLib!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x89
34 00000075`fcf7ef20 00007ff9`8c0d7c80 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].MoveNext()+0x2f60
35 00000075`fcf7ef90 00007ff9`8c0a4579 System_Private_CoreLib!System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)+0x140
36 00000075`fcf7f020 00007ff9`8c0707a4 System_Private_CoreLib!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)+0x79
37 00000075`fcf7f080 00007ff9`8c06f52e System_Private_CoreLib!System.Threading.Tasks.Task.RunContinuations(System.Object)+0x184
38 00000075`fcf7f150 00007ff9`8c0a66ac System_Private_CoreLib!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)+0x1be
39 00000075`fcf7f1f0 00007ff9`9461f3b3 System_Private_CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()+0x19c
3a 00000075`fcf7f290 00007ff9`94589e41 coreclr!CallDescrWorkerInternal+0x83 [E:\A\_work\31\s\src\vm\amd64\CallDescrWorkerAMD64.asm @ 101] 
3b (Inline Function) --------`-------- coreclr!CallDescrWorkerWithHandler+0x53 [e:\a\_work\31\s\src\vm\callhelpers.cpp @ 78] 
3c 00000075`fcf7f2d0 00007ff9`9458933f coreclr!MethodDescCallSite::CallTargetWorker+0x2b5 [e:\a\_work\31\s\src\vm\callhelpers.cpp @ 628] 
3d (Inline Function) --------`-------- coreclr!MethodDescCallSite::Call_RetBool+0x15 [e:\a\_work\31\s\src\vm\callhelpers.h @ 433] 
3e 00000075`fcf7f420 00007ff9`945a37f6 coreclr!QueueUserWorkItemManagedCallback+0x7f [e:\a\_work\31\s\src\vm\comthreadpool.cpp @ 451] 
3f 00000075`fcf7f510 00007ff9`945a3652 coreclr!ManagedThreadBase_DispatchInner+0x5a [e:\a\_work\31\s\src\vm\threads.cpp @ 8852] 
40 00000075`fcf7f550 00007ff9`945a3551 coreclr!ManagedThreadBase_DispatchMiddle+0x76 [e:\a\_work\31\s\src\vm\threads.cpp @ 8901] 
41 00000075`fcf7f650 00007ff9`945a2e10 coreclr!ManagedThreadBase_DispatchOuter+0x91 [e:\a\_work\31\s\src\vm\threads.cpp @ 9140] 
42 (Inline Function) --------`-------- coreclr!ManagedThreadBase_FullTransitionWithAD+0x56 [e:\a\_work\31\s\src\vm\threads.cpp @ 9199] 
43 (Inline Function) --------`-------- coreclr!ManagedThreadBase::ThreadPool+0x56 [e:\a\_work\31\s\src\vm\threads.cpp @ 9241] 
44 00000075`fcf7f6c0 00007ff9`945a2695 coreclr!ManagedPerAppDomainTPCount::DispatchWorkItem+0xe0 [e:\a\_work\31\s\src\vm\threadpoolrequest.cpp @ 757] 
45 (Inline Function) --------`-------- coreclr!ThreadpoolMgr::ExecuteWorkRequest+0x47 [e:\a\_work\31\s\src\vm\win32threadpool.cpp @ 1560] 
46 00000075`fcf7f820 00007ff9`944d3678 coreclr!ThreadpoolMgr::WorkerThreadStart+0x1d5 [e:\a\_work\31\s\src\vm\win32threadpool.cpp @ 2024] 
47 00000075`fcf7fa20 00007ffa`197a3034 coreclr!Thread::intermediateThreadProc+0x88 [e:\a\_work\31\s\src\vm\threads.cpp @ 2255] 
48 00000075`fcf7fc60 00007ffa`19e01431 kernel32!BaseThreadInitThunk+0x14
49 00000075`fcf7fc90 00000000`00000000 ntdll!RtlUserThreadStart+0x21
```

**Comment by jkotas** [comment] 2018-06-28 03:43
@AArnott Was the app being debugged when this happened? The dump suggests that it is stuck because of it is waiting for debugger to respond.

**Comment by AArnott** [comment] 2018-06-28 13:48
Yes, it was an F5 launch from VS. When I hit Ctrl+C in the app, it froze instead of canceling and exiting. So I then hit Break in VS and took a dump from which I got these callstacks.

**Comment by mikem8361** [comment] 2019-02-22 22:51
Is this still a problem? This issue is over 7 months old.

**Comment by AArnott** [comment] 2019-02-23 03:26
It didn't repro when I just tried it.

**Comment by tommcdon** [comment] 2019-02-25 19:03
Visual Studio has fixed issues related to hangs while running under the debugger - specifically func-eval expressions that hang due to assembly loads.  Please let us know if this issue still reproduces with the latest Visual Studio 2019 preview builds.  Closing this issue for now since it seems to be over 7 months old and we are unble to repro the problem.

**Closed by tommcdon** 2019-02-25 19:03 UTC
Labels: area-Diagnostics, bug, reliability
