### ISSUE TITLE
SIGABRT_System.ExecutionEngineException_System.Diagnostics.Tracing.Tests.dll!BasicEventSourceTests.EventTestHarness+<>c__DisplayClass0_0.<RunTests>b__0

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#5906] opened 2016-06-21 22:23 UTC
**The notes in this dump refer to the ubuntu 14.04 core dump available at: http://dotnetrp.azurewebsites.net/dumpling/download/1443**

    LAST_EXCEPTION:
    Exception object: 00007fc52bfff1e0
    Exception type:   System.ExecutionEngineException
    Message:          <none>
    InnerException:   <none>
    StackTrace (generated):
    <none>
    StackTraceString: <none>
    HResult: 80131506
    
    STOP_REASON:
    SIGABRT

    FAULT_SYMBOL:
    System.Diagnostics.Tracing.Tests.dll!BasicEventSourceTests.EventTestHarness+<>c__DisplayClass0_0.<RunTests>b__0
    
    FAILURE_HASH:
    SIGABRT_System.ExecutionEngineException_System.Diagnostics.Tracing.Tests.dll!BasicEventSourceTests.EventTestHarness+<>c__DisplayClass0_0.<RunTests>b__0

    FAULT_STACK:
    libc.so.6!__bsd_signal
    libc.so.6!__bsd_signal
    xunit.assert.dll!Xunit.Assert.Equal(System.String, System.String, Boolean, Boolean, Boolean)
    System.Diagnostics.Tracing.Tests.dll!BasicEventSourceTests.EventTestHarness+<>c__DisplayClass0_0.<RunTests>b__0(BasicEventSourceTests.Event)
    System.Private.CoreLib.ni.dll!System.Diagnostics.Tracing.EventSource.WriteStringToAllListeners(System.String, System.String)
    System.Private.CoreLib.ni.dll!System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage(System.String, Boolean)
    System.Private.CoreLib.ni.dll!System.Diagnostics.Tracing.EventSource.DoCommand(System.Diagnostics.Tracing.EventCommandEventArgs)
    System.Private.CoreLib.ni.dll!System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized()
    System.Private.CoreLib.ni.dll!System.Diagnostics.Tracing.EventSource.DoCommand(System.Diagnostics.Tracing.EventCommandEventArgs)
    System.Private.CoreLib.ni.dll!System.Diagnostics.Tracing.EventSource.Initialize(System.Guid, System.String, System.String[])
    System.Private.CoreLib.ni.dll!System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings, System.String[])
    System.Diagnostics.Tracing.Tests.dll!BasicEventSourceTests.EventTestHarness.RunTests(System.Collections.Generic.List`1<BasicEventSourceTests.SubTest>, BasicEventSourceTests.Listener, System.Diagnostics.Tracing.EventSource, BasicEventSourceTests.FilteringOptions)
    System.Diagnostics.Tracing.Tests.dll!BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent(BasicEventSourceTests.Listener, Boolean)
    rtm-pass1_001B.exe!stress.generated.UnitTests.UT1()
    stress.execution.dll!stress.execution.UnitTest.Execute()
    stress.execution.dll!stress.execution.DedicatedThreadWorkerStrategy.RunWorker(stress.execution.ITestPattern, System.Threading.CancellationToken)
    stress.execution.dll!stress.execution.DedicatedThreadWorkerStrategy+<>c__DisplayClass1_0.<SpawnWorker>b__0()
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.Execute()
    System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
    System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.ExecuteEntry(Boolean)
    System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

    LAST_EXCEPTION_TYPE:
    System.ExecutionEngineException

    FAULT_THREAD:
    thread #1: tid = 43399, 0x00007fc5cb593c37 libc.so.6`__bsd_signal + 4 at sigset.h:117, name = 'corerun', stop reason = signal SIGABRT

**Comment by adityamandaleeka** [comment] 2016-06-22 00:46
It looks like the stack above isn't really the interesting one. The interesting one is below. Based on what it shows, it looks like this is another OOM issue. We try to allocate an array of marks in `grow_mark_stack` and that allocation fails, so we call `EEPOLICY_HANDLE_FATAL_ERROR`.

Based on the dump, it looks like the GC heap size is 6.5 GB. Unfortunately, DumpHeap fails because the data structures apparently aren't in a valid state for traversal in this dump.

```
thread #1: tid = 0, 0x00007fc5cb593c37 libc.so.6`signal + 71, name = 'corerun', stop reason = signal SIGABRT
  * frame #0: 0x00007fc5cb593c37 libc.so.6`signal + 71
    frame #1: 0x00007fc5cae36d83 libcoreclr.so`SafeExitProcess(unsigned int, int, ShutdownCompleteAction) + 531
    frame #2: 0x00007fc5cae38271 libcoreclr.so`EEPolicy::HandleFatalError(unsigned int, unsigned long, char16_t const*, _EXCEPTION_POINTERS*) + 593
    frame #3: 0x00007fc5cafc2817 libcoreclr.so`WKS::gc_heap::enque_pinned_plug(unsigned char*, int, unsigned char*) + 663
    frame #4: 0x00007fc5cafbbb55 libcoreclr.so`WKS::gc_heap::plan_phase(int) + 6309
    frame #5: 0x00007fc5cafb757e libcoreclr.so`WKS::gc_heap::gc1() + 558
    frame #6: 0x00007fc5cafc1230 libcoreclr.so`WKS::gc_heap::garbage_collect(int) + 2320
    frame #7: 0x00007fc5cafb43bb libcoreclr.so`WKS::GCHeap::GarbageCollectGeneration(unsigned int, WKS::gc_reason) + 747
    frame #8: 0x00007fc5cafb491f libcoreclr.so`WKS::gc_heap::allocate_small(int, unsigned long, alloc_context*, int) + 959
    frame #9: 0x00007fc5cafb5e1a libcoreclr.so`WKS::gc_heap::try_allocate_more_space(alloc_context*, unsigned long, int) + 586
    frame #10: 0x00007fc5cafd7e4d libcoreclr.so`WKS::GCHeap::Alloc(alloc_context*, unsigned long, unsigned int) + 141
    frame #11: 0x00007fc5cae4a6de libcoreclr.so`AllocateObject(MethodTable*) + 174
    frame #12: 0x00007fc5cae5e583 libcoreclr.so`JIT_New(CORINFO_CLASS_STRUCT_*) + 339
    frame #13: 0x00007fc551b57469
    frame #14: 0x00007fc551ea37a9
    frame #15: 0x00007fc5516a6df3
    frame #16: 0x00007fc5516aa838
    frame #17: 0x00007fc5516a7a1c
    frame #18: 0x00007fc5516a5a14
    frame #19: 0x00007fc5516a478f
    frame #20: 0x00007fc551e9edb5
    frame #21: 0x00007fc551e9e723
    frame #22: 0x00007fc551e97492
    frame #23: 0x00007fc551b36c08
    frame #24: 0x00007fc551b36a3e
    frame #25: 0x00007fc551b369ac
    frame #26: 0x00007fc5516aea06
    frame #27: 0x00007fc55164f691
    frame #28: 0x00007fc5516aefc1
    frame #29: 0x00007fc5516aed28
    frame #30: 0x00007fc55164f691
    frame #31: 0x00007fc5caefbec7 libcoreclr.so`CallDescrWorkerInternal + 124
    frame #32: 0x00007fc5cae15aee libcoreclr.so`MethodDescCallSite::CallTargetWorker(unsigned long const*) + 862
    frame #33: 0x00007fc5cae20a8a libcoreclr.so`ThreadNative::KickOffThread_Worker(void*) + 474
    frame #34: 0x00007fc5cade60ee libcoreclr.so`ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) + 430
    frame #35: 0x00007fc5cade6846 libcoreclr.so`ManagedThreadBase::KickOff(ADID, void (*)(void*), void*) + 70
    frame #36: 0x00007fc5cae20c9b libcoreclr.so`ThreadNative::KickOffThread(void*) + 331
    frame #37: 0x00007fc5cb17f129 libcoreclr.so`CorUnix::CPalThread::ThreadEntry(void*) + 297
    frame #38: 0x00007fc5cc14a184 libpthread.so.0`start_thread + 196
```

**Comment by swgillespie** [comment] 2016-06-22 02:11
@adityamandaleeka This is unfortunately a known issue - I created a TFS issue tracking it a few months ago so perhaps we might want to create an issue on GitHub too.

**Comment by adityamandaleeka** [comment] 2016-06-22 02:57
Thanks @swgillespie. To be clear, the known issue you mentioned is the fact that we give up and abort in the GC code when the allocation fails, right?

I guess that leaves the question of what's eating up all the memory. I've been running the stress mix from the zip file @schaabs linked above, and it pretty quickly had almost 2 gigs in its resident set. I probed the heap a few times and it looks like we're hanging on to tons of objects of type `System.Diagnostics.Tracing.EventDispatcher`. 

I don't know enough about these tests to know exactly why this is happening, but perhaps this is another case of tests not playing nice when run under stress. From looking at the code for these tests in CoreFX, it appears that BasicEventSourceTest/TestsWriteEvent adds a bunch of 'subtests' to a list and runs them all with an event handler hooked up to listener events.

@davmason @stephentoub Do you have any thoughts about why this might be happening?

**Comment by davmason** [comment] 2016-06-22 03:29
EventDispatchers are created for each EventSource/EventListener pairing, so if we have tons of them around then that means that there are tons of EventSources and EventListeners being kept around. 

I don't know about how the EventSource tests are being run in the stress harness, but taking a brief look at our tests it looks like we never call Dispose() on the listeners we create. So, assuming the stress harness repeatedly calls our test we would create EventListeners and never get rid of them.

This is probably the EventSource tests not playing well with Stress. The fix is easy, assuming my mental debugging found the right issue.

**Comment by davmason** [comment] 2016-06-22 04:06
I made github/corefx#9591 to dispose EventListeners in the EventSource tests. It's probably the cause of this, and even if it's not it's good practice to have the tests do the right thing.

**Comment by swgillespie** [comment] 2016-06-22 17:10
> To be clear, the known issue you mentioned is the fact that we give up and abort in the GC code when the allocation fails, right?

Yep, that one. The way the code is structured today, we're unfortunately kind of screwed if we can't expand the mark stack here. If this allocation fails, we can't continue traversing the heap (or if we do, we run the risk of overrunning the mark stack buffer), so we'd have to bail on the GC, but we can't do that either because we're OOM and need to free up memory immediately.

**Comment by adityamandaleeka** [comment] 2016-06-22 23:12
I've been running this locally with the change @davmason made to dispose EventListeners in the EventSource tests, and it looks like the leak has been fixed. I'll let it run a bit longer to confirm, then close this issue.

**Comment by adityamandaleeka** [comment] 2016-06-24 00:52
Closing this issue since the leak seems to have been fixed.

**Closed by adityamandaleeka** 2016-06-24 00:52 UTC
Labels: bug, reliability
