### ISSUE TITLE
Test failure: GC/Features/HeapExpansion/plug/plug.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#24228] opened 2019-04-24 20:08 UTC
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_standalone_gc_tst/455/consoleFull

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/x64_checked_osx10.12_standalone_gc_flow/545/

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/x64_release_ubuntu_standalone_gc_flow/541/

```
07:51:55         BEGIN EXECUTION
07:51:55         /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_standalone_gc_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun plug.exe ''
07:51:55         Running 100 iterations
07:51:55         
07:51:55         cmdLine:/mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_standalone_gc_tst/bin/tests/Linux.x64.Checked/GC/Features/HeapExpansion/plug/plug.sh Timed Out
07:51:55         Test Harness Exitcode is : -100
07:51:55         To run the test:
07:51:55         > set CORE_ROOT=/mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_standalone_gc_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root
07:51:55         > /mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_standalone_gc_tst/bin/tests/Linux.x64.Checked/GC/Features/HeapExpansion/plug/plug.sh
07:51:55         Expected: True
07:51:55         Actual:   False
07:51:55         Stack Trace:
07:51:55           /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/tests/Linux.x64.Checked/TestWrappers/GC.Features/GC.Features.XUnitWrapper.cs(1434,0): at GC_Features._HeapExpansion_plug_plug_._HeapExpansion_plug_plug_sh()
07:51:55         Output:
07:51:55           
07:51:55           cmdLine:/mnt/j/workspace/dotnet_coreclr/master/x64_checked_ubuntu_standalone_gc_tst/bin/tests/Linux.x64.Checked/GC/Features/HeapExpansion/plug/plug.sh Timed Out
07:51:55           
07:51:55           Return code:      -100
```

**Comment by Maoni0** [comment] 2019-07-03 22:02
in May this test was failing a bunch with this assert

>Assertion failed 'tree->IsLocal() || (tree->OperGet() == GT_RET_EXPR) || (tree->OperGet() == GT_CALL) || ((tree->gtOper == GT_ADDR) && varTypeIsSIMD(tree->gtGetOp1()))' in 'System.SpanHelpers:IndexOf(byref,ushort,int):int' (IL size 339)

but the failures were only on May 17/18 so it was likely this was caused by a bug that then got fixed. 

in June all failures were due to this:

>line 259: /home/helixbot/work/0904d5eb-bf0c-42cb-a571-5103163359c2/Work/4110b40a-8094-4ab7-a8c7-858e562b5908/Unzip/runincontext.sh: No such file or directory

I presume there was some problem with the test infra

then the failure hasn't happened since Jun 12 and the test has always passed. so I will close this issue.

**Closed by Maoni0** 2019-07-03 22:02 UTC
Labels: area-GC
