### ISSUE TITLE
Debugging exprience flawed when using AssemblyLoadContexts with shared library

### ISSUE THREAD

**Issue by per-samuelsson** [dotnet/coreclr#21199] opened 2018-11-26 20:20 UTC
Having a setup resembling this:

```
\SharedLib
    SharedLib.csproj
\Lib1
    Lib1.csproj
\Lib2
    Lib2.csproj
```

All are just trivial libraries created with `dotnet new classlib`. Lib1 and Lib2 both reference SharedLib.

I then have a hosting app with a custom ALC, one context Lib1 and one for Lib2, using `LoadAssemblyFromPath` to load them. Then a `Load` override when I resolve recerences like this:

```csharp
override Load(AssemblyName name)
{
  var file = %directory of "main" library%\name + .dll;
  return File.Exists(file) ? LoadAssemblyFromPath(file) : null;
}
```

When I invoke a method in first Lib1 then Lib2, and that method in turn invoke a method in the shared lib, I can step the first call going into the shared library, but the second one just step over.

If I change `LoadAssemblyFromPath` to `LoadFrom` in the Load override, debugging works as expected.

FWIW, I already reported it once over [here](https://github.com/natemcmaster/DotNetCorePlugins/issues/20), before I got a hint the issue might be in the Core CLR.

I can provide a repro if that is of help investigating it. Just let me know.

(Reviewed #20607 but didn't seem like a 1-1).

**Comment by jkotas** [comment] 2018-11-26 23:12
Thank you for reporting this. This is duplicate of know issue https://github.com/dotnet/coreclr/issues/20607

**Closed by jkotas** 2018-11-26 23:12 UTC
