### ISSUE TITLE
Build on Arch Linux fails

### ISSUE THREAD

**Issue by rgl** [dotnet/coreclr#2135] opened 2015-11-22 14:33 UTC
I'm trying to build on Arch Linux at https://github.com/rgl/archlinux-coreclr-build but the build is failing. Any clue on how to fix these?

I'm trying with these versions:

```
+ uname -a
Linux 223b573e9ddf 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
+ pacman -Q clang cmake llvm lldb libunwind icu uuid lttng-ust
clang 3.7.0-5
cmake 3.4.0-2
llvm 3.7.0-5
lldb 3.7.0-5
libunwind 1.1-3
icu 56.1-1
uuid 1.6.2-12
lttng-ust 2.7.0-1
+ su rgl -c 'cd /tmp/coreclr && git rev-parse HEAD'
112e6ee2e78a5727d06c6bc62effeb97c1acad5b
```

## Errors

```
Scanning dependencies of target coreclrpal
[  0%] Building CXX object src/palrt/CMakeFiles/palrt.dir/coguid.cpp.o
[  0%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o
In file included from /tmp/coreclr/src/pal/src/cruntime/file.cpp:23:
In file included from /tmp/coreclr/src/pal/src/include/pal/palinternal.h:328:
/tmp/coreclr/src/pal/inc/pal.h:2756:24: error: expected parameter declarator
typedef DECLSPEC_ALIGN(16) M128U M128A, *PM128A;
                       ^
/tmp/coreclr/src/pal/inc/pal.h:183:46: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                                             ^
/tmp/coreclr/src/pal/inc/pal.h:2756:24: error: expected ')'
/tmp/coreclr/src/pal/inc/pal.h:183:46: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                                             ^
/tmp/coreclr/src/pal/inc/pal.h:2756:9: note: to match this '('
typedef DECLSPEC_ALIGN(16) M128U M128A, *PM128A;
        ^
/tmp/coreclr/src/pal/inc/pal.h:183:45: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                                            ^
/tmp/coreclr/src/pal/inc/pal.h:2756:9: error: C++ requires a type specifier for all declarations
typedef DECLSPEC_ALIGN(16) M128U M128A, *PM128A;
        ^
/tmp/coreclr/src/pal/inc/pal.h:183:40: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                                       ^
/tmp/coreclr/src/pal/inc/pal.h:2756:9: error: C++ requires a type specifier for all declarations
typedef DECLSPEC_ALIGN(16) M128U M128A, *PM128A;
~~~~~~~ ^
/tmp/coreclr/src/pal/inc/pal.h:183:29: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                            ^
/tmp/coreclr/src/pal/inc/pal.h:2756:27: error: expected ';' after top level declarator
typedef DECLSPEC_ALIGN(16) M128U M128A, *PM128A;
                          ^
                          ;
/tmp/coreclr/src/pal/inc/pal.h:2772:5: error: unknown type name 'M128A'; did you mean 'M128U'?
    M128A FloatRegisters[8];
    ^~~~~
    M128U
/tmp/coreclr/src/pal/inc/pal.h:2753:3: note: 'M128U' declared here
} M128U, *PM128U;
  ^
/tmp/coreclr/src/pal/inc/pal.h:2773:5: error: unknown type name 'M128A'; did you mean 'M128U'?
    M128A XmmRegisters[16];
    ^~~~~
    M128U
/tmp/coreclr/src/pal/inc/pal.h:2753:3: note: 'M128U' declared here
} M128U, *PM128U;
  ^
/tmp/coreclr/src/pal/inc/pal.h:2812:16: error: elaborated type refers to a typedef
typedef struct DECLSPEC_ALIGN(16) _CONTEXT {
               ^
/tmp/coreclr/src/pal/inc/pal.h:183:29: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                            ^
/tmp/coreclr/src/pal/inc/pal.h:2756:9: note: declared here
typedef DECLSPEC_ALIGN(16) M128U M128A, *PM128A;
        ^
/tmp/coreclr/src/pal/inc/pal.h:183:29: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                            ^
/tmp/coreclr/src/pal/inc/pal.h:2812:31: error: expected parameter declarator
typedef struct DECLSPEC_ALIGN(16) _CONTEXT {
                              ^
/tmp/coreclr/src/pal/inc/pal.h:183:46: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                                             ^
/tmp/coreclr/src/pal/inc/pal.h:2812:31: error: expected ')'
/tmp/coreclr/src/pal/inc/pal.h:183:46: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                                             ^
/tmp/coreclr/src/pal/inc/pal.h:2812:16: note: to match this '('
typedef struct DECLSPEC_ALIGN(16) _CONTEXT {
               ^
/tmp/coreclr/src/pal/inc/pal.h:183:45: note: expanded from macro 'DECLSPEC_ALIGN'
#define DECLSPEC_ALIGN(x)   __declspec(align(x))
                                            ^
/tmp/coreclr/src/pal/inc/pal.h:2812:35: error: expected function body after function declarator
typedef struct DECLSPEC_ALIGN(16) _CONTEXT {
                                  ^
/tmp/coreclr/src/pal/inc/pal.h:2937:9: error: unknown type name 'PM128A'; did you mean 'PM128U'?
        PM128A FloatingContext[16];
        ^~~~~~
        PM128U
/tmp/coreclr/src/pal/inc/pal.h:2753:11: note: 'PM128U' declared here
} M128U, *PM128U;
          ^
/tmp/coreclr/src/pal/inc/pal.h:2939:13: error: unknown type name 'PM128A'; did you mean 'PM128U'?
            PM128A Xmm0;
            ^~~~~~
            PM128U
/tmp/coreclr/src/pal/inc/pal.h:2753:11: note: 'PM128U' declared here
} M128U, *PM128U;
          ^
/tmp/coreclr/src/pal/inc/pal.h:2940:13: error: unknown type name 'PM128A'; did you mean 'PM128U'?
            PM128A Xmm1;
            ^~~~~~
            PM128U
/tmp/coreclr/src/pal/inc/pal.h:2753:11: note: 'PM128U' declared here
} M128U, *PM128U;
          ^
/tmp/coreclr/src/pal/inc/pal.h:2941:13: error: unknown type name 'PM128A'; did you mean 'PM128U'?
            PM128A Xmm2;
            ^~~~~~
            PM128U
/tmp/coreclr/src/pal/inc/pal.h:2753:11: note: 'PM128U' declared here
} M128U, *PM128U;
          ^
/tmp/coreclr/src/pal/inc/pal.h:2942:13: error: unknown type name 'PM128A'; did you mean 'PM128U'?
            PM128A Xmm3;
            ^~~~~~
            PM128U
/tmp/coreclr/src/pal/inc/pal.h:2753:11: note: 'PM128U' declared here
} M128U, *PM128U;
          ^
/tmp/coreclr/src/pal/inc/pal.h:2943:13: error: unknown type name 'PM128A'; did you mean 'PM128U'?
            PM128A Xmm4;
            ^~~~~~
            PM128U
/tmp/coreclr/src/pal/inc/pal.h:2753:11: note: 'PM128U' declared here
} M128U, *PM128U;
          ^
/tmp/coreclr/src/pal/inc/pal.h:2944:13: error: unknown type name 'PM128A'; did you mean 'PM128U'?
            PM128A Xmm5;
            ^~~~~~
            PM128U
/tmp/coreclr/src/pal/inc/pal.h:2753:11: note: 'PM128U' declared here
} M128U, *PM128U;
          ^
/tmp/coreclr/src/pal/inc/pal.h:2945:13: error: unknown type name 'PM128A'; did you mean 'PM128U'?
            PM128A Xmm6;
            ^~~~~~
            PM128U
/tmp/coreclr/src/pal/inc/pal.h:2753:11: note: 'PM128U' declared here
} M128U, *PM128U;
          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
src/pal/src/CMakeFiles/coreclrpal.dir/build.make:62: recipe for target 'src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o' failed
CMakeFiles/Makefile2:166: recipe for target 'src/pal/src/CMakeFiles/coreclrpal.dir/all' failed
make[2]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/cruntime/file.cpp.o] Error 1
make[1]: *** [src/pal/src/CMakeFiles/coreclrpal.dir/all] Error 2
```

**Comment by janvorli** [comment] 2015-11-23 09:40
We don't support clang 3.7 yet. @wtgodbe since you were looking into enabling support for clang 3.7, could you please comment on the status?

**Comment by juergenhoetzel** [comment] 2015-11-27 22:36
There still more clang 3.7 issues. For example the new introduced ```-Werror=infinite-recursion``` (enabled by default) also emmits an error:

```
[ 88%] Building CXX object src/utilcode/staticnohost/CMakeFiles/utilcodestaticnohost.dir/__/hostimpl.cpp.o
/home/juergen/DotNet/coreclr/src/utilcode/hostimpl.cpp:275:1: error: all paths through this function will call itself
      [-Werror,-Winfinite-recursion]
{
^
1 error generated.
```

**Comment by wtgodbe** [comment] 2015-11-30 19:47
I've since deleted my branch with fixes for 3.7, but here is the information Jan sent me that allowed me to fix this declspec issue. Hopefully it solves your problem (although there will still be other issues).

>I’ve just found this in the Clang 3.7 release notes:
>>Major New Features
>>•	Use of the __declspec language extension for declaration attributes now requires passing the -fms-extensions or -fborland compiler flag. This language extension is also enabled when compiling CUDA code, but its use should be viewed as an implementation detail that is subject to change.
>
>So I was wondering if we could really be missing the -fms-extensions option from the PAL build.
>And we are!
>
>The option is not defined for PAL compilation. In the root CMakeLists.txt, the option is added at line 394, but the PAL folder is added for compilation at line 222.
>So we should probably move adding the option right before the line 221.

**Comment by janvorli** [comment] 2015-11-30 20:35
@wtgodbe Ah, I have thought this change was already merged in.

**Comment by juergenhoetzel** [comment] 2015-11-30 23:25
Indeed this fixed the PAL compilation.

Still more Clang 3.7 issues:

```
[ 81%] Building CXX object src/corefx/System.Globalization.Native/CMakeFiles/System.Globalization.Native.dir/localeStringData.cpp.o
/home/juergen/software/coreclr/src/utilcode/clrhost_nodependencies.cpp:402:16: error: visibility does not match previous declaration
__attribute__((visibility("hidden")))
               ^
note: previous attribute is here
/home/juergen/software/coreclr/src/utilcode/clrhost_nodependencies.cpp:426:16: error: visibility does not match previous declaration
__attribute__((visibility("hidden")))
               ^
note: previous attribute is here
/home/juergen/software/coreclr/src/utilcode/clrhost_nodependencies.cpp:501:16: error: visibility does not match previous declaration
__attribute__((visibility("hidden")))
               ^
note: previous attribute is here
/home/juergen/software/coreclr/src/utilcode/clrhost_nodependencies.cpp:517:16: error: visibility does not match previous declaration
__attribute__((visibility("hidden")))
               ^
note: previous attribute is here
4 errors generated.
```

**Comment by jashook** [comment] 2015-12-01 17:29
In fixing declspec issues, is it prefered to use c++ 11 language features to remove these warnings?

eg. use thread_local in place of __declspec(thread) and alignas in place of __declspec (align (#) )

There may be more that are not language agnostic, however those were the ones I found earlier.

**Comment by janvorli** [comment] 2015-12-01 18:56
I think it would be good to use the C++ 11 features instead of the compiler specific stuff. @jkotas do you agree?

**Comment by jkotas** [comment] 2015-12-01 19:14
Minorcleanup,  nice to have. DECLSPEC_ALIGN is in the PAL already so you just need to adjust its definition to use alignas, we may want to switch thread locals on similar DECLSPEC_THREAD plan.

I am not sure whether all compilers that are used to build CLR/CoreCLR internally support these C++ 11 features. You should double check if you would like to do more aggressive cleanup (e.g. get rid of DECLSPEC_ALIGN completely).

**Comment by juergenhoetzel** [comment] 2015-12-03 22:26
```
note: previous attribute is here
/home/juergen/software/coreclr/src/utilcode/clrhost_nodependencies.cpp:501:16: error: visibility does not match previous declaration
__attribute__((visibility("hidden")))
               ^
note: previous attribute is here
/home/juergen/software/coreclr/src/utilcode/clrhost_nodependencies.cpp:517:16: error: visibility does not match previous declaration
__attribute__((visibility("hidden")))
```
There seems no way to fix this Clang 3.7.0 issue without changing the visibility of ```new/delete``` to "default" (as defined in ```/usr/include/c++/5.2.0/new``` on GNU/Linux systems.

**Comment by jkotas** [comment] 2015-12-03 22:34
> /usr/include/c++/5.2.0/new 

System header files should not be included when building clrhost_nodependencies.cpp. It should always use local PAL header files, like `new.h` from `src\pal\inc\rt` . How does the system `new` header file get included?

**Comment by juergenhoetzel** [comment] 2015-12-03 23:04
You are right! This was just an invalid assumption. I now checked preprocessor output.

**Comment by juergenhoetzel** [comment] 2015-12-04 21:10
Build also fails using ```Clang-3.8-trunk```

@rgl: You can build ```coreclr``` using the ```clang35``` package, which is also in our extra repo.

**Comment by rgl** [comment] 2015-12-04 22:40
@juergenhoetzel indeed, with 3.5 it builds! thanks!

**Comment by Marqin** [comment] 2015-12-09 21:25
failing with clang 3.7 for me

**Comment by SirCmpwn** [comment] 2015-12-10 21:18
I can reproduce this as well.

**Comment by Marqin** [comment] 2015-12-14 23:48
I'm trying now with `clang35` and getting:
```
[ 99%] Linking CXX executable corerun
../unixcoreruncommon/libunixcoreruncommon.a(coreruncommon.cpp.o): In function `ExecuteManagedAssembly(char const*, char const*, char const*, int, char const**)':
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:270: undefined reference to `dlopen'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:273: undefined reference to `dlsym'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:274: undefined reference to `dlsym'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:275: undefined reference to `dlsym'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:369: undefined reference to `dlclose'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:376: undefined reference to `dlerror'
../unixcoreruncommon/libunixcoreruncommon.a(coreruncommon.cpp.o): In function `ExecuteManagedAssembly(char const*, char const*, char const*, int, char const**)':
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:270: undefined reference to `dlopen'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:273: undefined reference to `dlsym'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:274: undefined reference to `dlsym'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:275: undefined reference to `dlsym'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:369: undefined reference to `dlclose'
/build/coreclr-git/src/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:376: undefined reference to `dlerror'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/coreclr/hosts/unixcoreconsole/CMakeFiles/coreconsole.dir/build.make:95: recipe for target 'src/coreclr/hosts/unixcoreconsole/coreconsole' failed
make[2]: *** [src/coreclr/hosts/unixcoreconsole/coreconsole] Error 1
CMakeFiles/Makefile2:62041: recipe for target 'src/coreclr/hosts/unixcoreconsole/CMakeFiles/coreconsole.dir/all' failed
make[1]: *** [src/coreclr/hosts/unixcoreconsole/CMakeFiles/coreconsole.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
src/coreclr/hosts/unixcorerun/CMakeFiles/corerun.dir/build.make:95: recipe for target 'src/coreclr/hosts/unixcorerun/corerun' failed
make[2]: *** [src/coreclr/hosts/unixcorerun/corerun] Error 1
CMakeFiles/Makefile2:61985: recipe for target 'src/coreclr/hosts/unixcorerun/CMakeFiles/corerun.dir/all' failed
make[1]: *** [src/coreclr/hosts/unixcorerun/CMakeFiles/corerun.dir/all] Error 2
```

Is this another Arch-connected bug or someone removed linking dl?

**Comment by EricLagergren** [comment] 2016-02-15 06:37
fwiw it compiles properly with clang 3.7.1 on x64 linux 4.4.1

**Comment by juergenhoetzel** [comment] 2016-02-19 20:47
Works for me too.

@rgl  I guess this issue is fixed

**Comment by jkotas** [comment] 2016-02-19 20:52
If there are more issues on Arch Linux, let's track as new issue.

**Closed by jkotas** 2016-02-19 20:52 UTC
Labels: Build
