### ISSUE TITLE
Cleanup on shutdown

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/coreclr#1335] opened 2015-08-03 20:00 UTC
With `AppDomain` no longer supported in CoreCLR, we no longer have a `AppDomain.DomainUnload` event to hook into. What's the new Right Way to handle necessary cleanup that used to go there?

**Comment by ayende** [comment] 2015-08-04 05:21
What about AppDomain.CurrentDomain.ProcessExit ?

**Comment by masonwheeler** [comment] 2015-08-04 10:03
@ayende Sure looks like that's part of `AppDomain` too...

**Comment by whoisj** [comment] 2015-08-04 22:15
Might have to go old school. 

```
int main(string[] args)
{
    try
    {
        // ...
    }
    finally
    {
        // clean up here
    }
}
```

Won't help a library much. Perhaps make your entry-point `IDisposable`?

**Comment by kouvel** [comment] 2016-01-11 20:52
Using the dispose pattern is the only workaround that I'm aware of, a class library would require a call from consumers to do graceful cleanup, as finalizers are unreliable during shutdown. See dotnet/corefx#5205 for more details, it's is a proposal to add AssemblyLoadContext.Unload that would behave similarly to AppDomain.Unload in CoreCLR.

**Comment by kouvel** [comment] 2016-01-13 05:55
Considering this a duplicate of dotnet/corefx#5205 and closing.

**Closed by kouvel** 2016-01-13 05:55 UTC
Labels: VM
