### ISSUE TITLE
Uninitialized stack value instead of register returned by Unsafe.As<Vector<int>, int>(ref vector)

### ISSUE THREAD

**Issue by RossNordby** [dotnet/coreclr#11804] opened 2017-05-22 21:55 UTC
Using Unsafe to reinterpret a vector can load from the vector's stack memory even if the logical value has been mutated in registers and has not yet been stored. For example:
```cs
        [MethodImpl(MethodImplOptions.NoInlining)]
        static int UnsafeGrab()
        {
            var vector = new Vector<int>(4);
            return Unsafe.As<Vector<int>, int>(ref vector);
        }
        [MethodImpl(MethodImplOptions.NoInlining)]
        static int IndexerGrab()
        {
            var vector = new Vector<int>(4);
            return vector[0];
        }
```
IndexerGrab returns 4 as expected, while UnsafeGrab returns an uninitialized value like -1894710053.

UnsafeGrab assembly:
```
 mov         eax,4  
 movd        xmm0,eax  
 pshufd      xmm0,xmm0,0  
 mov         eax,dword ptr [rsp]  ;<--
 mov         eax,eax
 ret  
```
IndexerGrab assembly:
```
 mov         eax,4  
 movd        xmm0,eax  
 pshufd      xmm0,xmm0,0  
 movd        eax,xmm0
 ret  
```
Tested on NETCore.App 2.0.0-preview2-25309-07.

**Comment by karelz** [comment] 2017-05-23 10:41
@mellinoe is it 2.0 bug?

**Comment by mikedn** [comment] 2017-05-23 10:58
cc @dotnet/jit-contrib

**Comment by RussKeldorph** [comment] 2017-05-23 17:11
@BruceForstall PTAL

**Comment by mellinoe** [comment] 2017-05-23 19:13
@karelz We'll have to do more testing, but it's possible that it affects other runtimes and versions as well.

**Comment by mellinoe** [comment] 2017-05-23 19:18
This occurs on .NET Core 1.0 and 1.1 as well -- only in Release mode from my testing. Debug mode doesn't exhibit any problems.

**Comment by pgavlin** [comment] 2017-05-23 22:25
This test actually ends up hitting an assertion during LSRA when using a checked JIT:

```
Assert failure(PID 33840 [0x00008430], Thread: 14772 [0x39b4]): Assertion failed '!interval->isLocalVar' in 'C:UnsafeGrab():int' (IL size 18)

    File: c:\dev\coreclr\src\jit\lsra.cpp Line: 531
    Image: c:\dev\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
```

Here's the IR for this function:

```
------------ BB01 [000..012) (return), preds={} succs={}
N003 (  6,  5) [000007] ------------                il_offset void   IL offset: 0x0 REG NA
N005 (  1,  1) [000003] ------------        t3 =    const     int    50 REG NA $81
                                                 /--*  t3     int    
N007 (  2,  2) [000004] -------N----        t4 = *  simd      simd16 int init REG NA $41
                                                 /--*  t4     simd16 
N009 (  6,  5) [000006] DA--G-------             *  st.lclVar simd16 V00 loc0         d:3 REG NA
N011 (  3,  4) [000019] ------------       t19 =    lclFld    int    V00 loc0         u:3[+0] (last use) REG NA $140
                                                 /--*  t19    int    
N013 (  4,  5) [000015] ----G-------             *  return    int    REG NA $141
```

**Comment by CarolEidt** [comment] 2017-05-23 22:39
@pgavlin - shall I take it from here, or would you like to continue with this?

**Comment by pgavlin** [comment] 2017-05-23 22:40
Here are the allocator's intervals and ref positions:
```
Linear scan intervals BEFORE VALIDATING INTERVALS:
Interval  0: (V00) RefPositions {#5@10 #7@13} physReg:NA Preferences=[allFloat]
Interval  1: (constant) RefPositions {#1@6 #2@7} physReg:NA Preferences=[allInt]
Interval  2: RefPositions {#3@8 #4@9} physReg:NA Preferences=[allFloat] RelatedInterval <L0>[000001F7F77B9FD0]

------------
REFPOSITIONS BEFORE VALIDATING INTERVALS: 
------------
<RefPosition #0   @0   RefTypeBB BB01 regmask=[]>
<RefPosition #1   @6   ->#2   RefTypeDef <Ivl:1> CNS_INT BB01 regmask=[allInt]>
<RefPosition #2   @7   RefTypeUse <Ivl:1> BB01 regmask=[allInt] last>
<RefPosition #3   @8   ->#4   RefTypeDef <Ivl:2> SIMD BB01 regmask=[allFloat]>
<RefPosition #4   @9   RefTypeUse <Ivl:2> BB01 regmask=[allFloat] last>
<RefPosition #5   @10  ->#7   RefTypeDef <Ivl:0 V00> STORE_LCL_VAR BB01 regmask=[allFloat]>
<RefPosition #6   @13  RefTypeFixedReg <Reg:rax> BB01 regmask=[rax]>
<RefPosition #7   @13  RefTypeUse <Ivl:0 V00> LCL_FLD BB01 regmask=[rax] last>
```

@CarolEidt I'm going to dig a bit deeper before throwing in the towel :)

**Comment by BruceForstall** [comment] 2017-05-23 22:43
@pgavlin I've reassigned this to you.

**Comment by pgavlin** [comment] 2017-05-23 22:45
Thanks, @BruceForstall.

It does seem odd that `V00` is ending up a register candidate given the type punning that's happening with the `LCL_FLD`: it seems like this ought to disqualify the lclVar from enregistration.

**Comment by CarolEidt** [comment] 2017-05-23 23:12
> It does seem odd that V00 is ending up a register candidate given the type punning that's happening with the LCL_FLD: it seems like this ought to disqualify the lclVar from enregistration.

Yes, and usually the presence of a `GT_LCL_FLD` would disqualify a struct from promotion, but I suspect that there's something being missed in the special casing of `TYP_SIMD`.

**Comment by CarolEidt** [comment] 2017-05-23 23:13
Of course, SIMD nodes aren't really "promoted", but one would expect the same analysis to apply.

**Comment by pgavlin** [comment] 2017-05-23 23:18
> Yes, and usually the presence of a `GT_LCL_FLD` would disqualify a struct from promotion, but I suspect that there's something being missed in the special casing of `TYP_SIMD`.

This is essentially correct: the code in morph that would normally disqualify the lclVar from enregistration when rewriting `(IND Tx (ADDR (lclVar Ty V)))` into `(LCL_FLD Tx V)` does not do so if the lclVar is a reg struct, and only SIMD lclVars are reg structs. I think the fix is a simple as always disqualifying `V` when this rewrite is performed; I'm running tests and asm diffs now.

**Comment by CarolEidt** [comment] 2017-05-23 23:24
> I think the fix is a simple as always disqualifying V when this rewrite is performed

It is probably the case that the exception was intended to handle the issue where `TYP_SIMD8` parameters are passed and returned as `TYP_DOUBLE`. However, I don't believe we handle that correctly yet anyway - I **think** those are usually not enregistered if they are passed or returned. But that would be something to look at.

**Comment by pgavlin** [comment] 2017-05-23 23:28
> It is probably the case that the exception was intended to handle the issue where TYP_SIMD8 parameters are passed and returned as TYP_DOUBLE. However, I don't believe we handle that correctly yet anyway - I think those are usually not enregistered if they are passed or returned. But that would be something to look at.

Yup, I added a test for just that. In that case we create the `LCL_FLD` node in the importer, though I haven't yet tracked down precisely where.

**Closed** 2017-05-24 23:45 UTC
Labels: area-CodeGen, bug
