### ISSUE TITLE
[arm64\linux]Test failure:baseservices_threading._events_EventWaitHandle_ManualReset_ManualResetCtor1_ManualResetCtor1_._events_EventWaitHandle_ManualReset_ManualResetCtor1_ManualResetCtor1_sh

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21801] opened 2019-01-04 02:14 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_gcstress15_tst/13/
**Failed test:**
baseservices_threading._events_EventWaitHandle_ManualReset_ManualResetCtor1_ManualResetCtor1_._events_EventWaitHandle_ManualReset_ManualResetCtor1_ManualResetCtor1_sh

**Failed log:**
```
baseservices_threading._events_EventWaitHandle_ManualReset_ManualResetCtor1_ManualResetCtor1_._events_EventWaitHandle_ManualReset_ManualResetCtor1_ManualResetCtor1_sh [FAIL]
        /n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_gcstress15_tst/bin/tests/Linux.arm64.Checked/baseservices/threading/Reports/baseservices.threading/events/EventWaitHandle/ManualReset/ManualResetCtor1/ManualResetCtor1.output.txt/nRaw output:/nTest Harness Exitcode is : 137
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_gcstress15_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_gcstress15_tst/bin/tests/Linux.arm64.Checked/baseservices/threading/events/EventWaitHandle/ManualReset/ManualResetCtor1/ManualResetCtor1.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/baseservices.threading/baseservices.threading.XUnitWrapper.cs(1509,0): at baseservices_threading._events_EventWaitHandle_ManualReset_ManualResetCtor1_ManualResetCtor1_._events_EventWaitHandle_ManualReset_ManualResetCtor1_ManualResetCtor1_sh()
```

**Comment by RussKeldorph** [comment] 2019-01-16 21:56
Assuming duplicate of #22010.  Feel free to re-open if not.

**Closed by RussKeldorph** 2019-01-16 21:56 UTC
Labels: arch-arm64, os-linux
