### ISSUE TITLE
Allow AppDomain.SetData more than once

### ISSUE THREAD

**Issue by bricelam** [dotnet/coreclr#11453] opened 2017-05-08 20:06 UTC
There seems to be [an arbitrary limitation](https://github.com/dotnet/coreclr/blob/release/2.0.0/src/mscorlib/src/System/AppDomain.cs#L675) on Core CLR that prevents you from calling `AppDomain.SetData` more than once for the same name.

This limitation doesn't exist on .NET Framework.

We use `AppDomain.SetData` in our tests to check our usage of `AppDomain.GetData`. We typically clean up after the test by passing `null`, but this throws.

We discovered this by attempting to run our .NET Framework 4.6.1 test code on .NET Core App 2.0.

**Comment by gkhanna79** [comment] 2017-05-09 15:39
CC @danmosemsft

**Comment by danmosemsft** [comment] 2017-05-09 15:49
@AlexGhiondea any context on why this code exists? It looks like it precedes github: https://referencesource.microsoft.com/#mscorlib/system/appdomain.cs,2444

Unless there's a good reason, we should fix this. If you don't have cycles, LMK and I'll find someone.

**Comment by danmosemsft** [comment] 2017-05-09 20:17
@sepidehMS can you do this one for 5/10 ?

**Comment by sepidehMS** [comment] 2017-05-09 20:34
@danmosemsft I can't say for sure I will finish it for 5/10 with two other tasks I need to finish, but I certainly can spend time on this for investigation.

**Comment by danmosemsft** [comment] 2017-05-09 20:56
OK!

**Comment by AlexGhiondea** [comment] 2017-05-09 21:17
@sepidehMS the fix for this is to do something like what I have in this branch: https://github.com/AlexGhiondea/coreclr/tree/MakeSetData

**Comment by AlexGhiondea** [comment] 2017-05-10 21:37
I have a PR for this here: https://github.com/dotnet/coreclr/pull/11496

**Comment by danmosemsft** [comment] 2017-05-10 22:00
@ViktorHofer if @sepidehMS doesn't have time to do this today could you please get the PR in.

**Comment by AlexGhiondea** [comment] 2017-05-10 22:06
@danmosemsft the PR is approved -- I am just waiting for CI to complete

**Comment by danmosemsft** [comment] 2017-05-10 23:18
Great - thanks both of you.

**Comment by danmosemsft** [comment] 2017-05-11 00:53
Fixed right @alexghiondea

**Comment by jkotas** [comment] 2017-05-11 02:27
We need regression test in corefx

**Comment by karelz** [comment] 2017-05-11 14:57
@AlexGhiondea should we move the test part into CoreFX? (we don't have to if it is easier this way)

**Comment by stephentoub** [comment] 2017-05-11 15:24
I added a test here:
https://github.com/dotnet/corefx/issues/19657

**Closed** 2017-05-15 14:33 UTC
Labels: area-System.Runtime, bug
