### ISSUE TITLE
paltest_mapviewoffile_test1 fails when /tmp is mounted as tmpfs

### ISSUE THREAD

**Issue by ellismg** [dotnet/coreclr#5176] opened 2016-05-24 03:12 UTC
I noticed this problem on Fedora 23 (and @pgavlin had been hitting it as well).

This test wants to `open(2)` a file in `/tmp` which on Fedora is mounted as `tmpfs`, which does not support `O_DIRECT` (`O_DIRECT` is passed because the test specifies [FILE_FLAG_NO_BUFFERING](https://github.com/dotnet/coreclr/blob/master/src/pal/tests/palsuite/filemapping_memmgt/MapViewOfFile/test1/MapViewOfFile.c#L46)).

Because `O_DIRECT` is passed, open returns `EINVA`L, which gets translated into CreateFile returning `INVALID_HANDLE_VALUE`, and the test can not set up what it needs.

**Comment by ellismg** [comment] 2016-05-24 03:13
@janvorli Thoughts on the best way to handle this?  I think this means we can't get any coverage of O_DIRECT stuff when we run by default on systems where /tmp is tmpfs.

**Comment by janvorli** [comment] 2016-05-26 21:06
@ellismg I am sorry for a late reply, I have actually written it the day before yesterday and then got distracted and didn't push the comment 
I've found an interesting thread discussing O_DIRECT vs tmpfs:
https://lkml.org/lkml/2007/1/4/55
But I have a question - I don't see the test to access /tmp directly, but rather open just "test.tmp". Do we put the test binaries into the /tmp?

**Comment by ellismg** [comment] 2016-05-26 21:11
> Do we put the test binaries into the /tmp?

When I looked at it, it seemed like the CWD when the test was run was a folder in /tmp.

**Comment by janvorli** [comment] 2016-05-26 21:30
I can see it now - we use /tmp so that we can run multiple runs of the tests in parallel.
One option to fix the problem is to modify the test to create the file /var/tmp instead of /tmp. The /var/tmp is a real filesystem and so it should not have the problem of the tmpfs. Or we may change the runpaltests.sh to use /var/tmp instead of /tmp for all tests.

**Comment by ellismg** [comment] 2016-05-26 21:34
The other option (and I'm not sure if it's preferable or not) is to just use $TEMP if it is set instead of /tmp and we could have our builds set $TEMP to some non tmpfs thing (I guess by default /var/tmp persists across reboots which may mean we should be more careful about dropping files there?)

**Comment by sergiy-k** [comment] 2016-05-26 21:43
Running multiple tests in parallel is not the reason why tests are running in /tmp. We use to not run tests in the /tmp folder but that was causing some failures due to other file system issues. Please take a look at this commit: https://github.com/dotnet/coreclr/commit/e0c013e2af50bace4004e856cba67fcbec01fc00

**Comment by gkhanna79** [comment] 2017-04-12 21:47
@ellismg @janvorli Is this still actionable?

**Comment by gkhanna79** [comment] 2017-04-26 17:45
@janvorli @ellismg What are the next steps on this?

**Comment by janvorli** [comment] 2017-05-04 11:45
@ellismg @gkhanna79 after some additional investigations, my suggestion is to switch only this problematic PAL test to use /var/tmp for the target file and make sure it cleans up after itself. That should address the concern of growing amount of uncleaned garbage in the /var/tmp folder, since the garbage would stay there only if the test crashed.

**Comment by janvorli** [comment] 2017-05-04 20:20
Fixed by #11393

**Closed by janvorli** 2017-05-04 20:20 UTC
Labels: area-PAL, test bug
