### ISSUE TITLE
Access Violation Exception using System.Numerics.Vectors , with POC

### ISSUE THREAD

**Issue by vpenades** [dotnet/coreclr#22293] opened 2019-01-30 15:26 UTC
I've just stumbled upon yet another System.Numerics.Vectors exception.

As suggested [here](https://github.com/dotnet/coreclr/pull/19065#issuecomment-413612261) a while ago, I would like to catch the attention of: @eerhardt @tannergooding @AndyAyersMS and @CarolEidt

I've created a repository with the POCs that reproduces the problem (under Visual Studio 15.9.6) , Debug, AnyCPU (x64?)

The POC projects are these:

https://github.com/vpenades/NetRegressionTests/tree/master/src/VectorsAssignmentVariant1
https://github.com/vpenades/NetRegressionTests/tree/master/src/VectorsAssignmentVariant2

**Comment by vpenades** [comment] 2019-02-01 09:49
Here's the exception itself:
![imagen](https://user-images.githubusercontent.com/5433822/52115515-16c6c100-260f-11e9-97bb-aac250dac839.png)

**Comment by 0xd4d** [comment] 2019-02-01 14:36
Have you tried [the latest daily build of .NET Core 3.0](https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries)? I could repro it with .NET Core 2.2 but not 3.0.

.NET Core 2.2:
```asm
00007FFBD93216BC C4E179114D10         VMOVUPD [RBP+10H],XMM1 ; overwrite 16 bytes + arg

00007FFBD93216C2 488B4D18             MOV     RCX,[RBP+18H] ; grab input arg == garbage
00007FFBD93216C6 C4E17A104108         VMOVSS  XMM0,DWORD PTR [RCX+8] ; AV
```

**Comment by vpenades** [comment] 2019-02-01 15:08
@0xd4d thanks for confirming the issue!

I usually work with production versions of the frameworks, not with nightly builds... But it's good to know it's been fixed on net core 3.0

But then, does it mean that the solution is to wait for net core 3.0 , and the production net core 2.2 is never going to be fixed?

**Comment by CarolEidt** [comment] 2019-02-01 15:14
This looks like a duplicate of #19674 and #20657, which were fixed with #19857.
I'm not sure about porting to an earlier release, but I'll check into it.
Note that 3.0 is now available in a preview build: https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by RussKeldorph** [comment] 2019-02-01 21:00
@vpenades This could potentially be serviced in net48 (when released), though it's not likely.  It's *extremely* unlikely to be serviced in older .NET releases.  Core 2.2 could be serviced to include this fix with sufficient justification.  However, when you write, "Force our clients to use...core is out of discussion," however, it doesn't sound like this would provide you much benefit.

**Comment by RussKeldorph** [comment] 2019-02-07 00:55
@vpenades That technique would work for build-time differentiation, so you'd need a build of the library for each version.  Otherwise, you'd have to detect the version at runtime, which I understand is difficult to do reliably and therefore strongly discouraged.

For what it's worth, we strongly recommend using SIMD only on .NET Core if possible.  If you are able to get your clients to use Core 2.1 (LTS) or 2.2, it's very possible we could fix the issues you're encountering in those releases.

**Comment by vpenades** [comment] 2019-02-07 09:12
@RussKeldorph Our clients usually have a very strict policy of which frameworks they support. So far the most advanced ones allow us to support up to net framework 4.7.1

Out application is a Desktop WPF application running on net471; we're developing some components to target net standard to plan for the future. But moving our application from net471 to a different framework is out of the question.

We've began using system.numerics.vectors not only for performance reasons, but also because we consider them as a good collection of types for interoperability between libraries, so performance is important, but it is less important than safety and reliability.

So my questions are:

- How do I disable SIMD support in net471?
- It is possible to compile, or launch a net471 application so when system.numerics.vectors is used, the JITter will generate normal code, instead of SIMD optimized code?
- On Desktop Net Framework, is System.Numerics.Vectors officially supported and maintained? or is the current recommendation to not use it at all?

**Comment by RussKeldorph** [comment] 2019-02-08 18:53
@vpenades It seems like your first and second questions are related.  If not, please clarify what you mean by "disable SIMD support."  I think running the app with `COMPlus_FeatureSIMD=0` set in the environment will make the runtime fall back on the C# intrinsic implementations, which won't use SIMD operations.  Like most `COMPlus_` knobs, I believe there are also equivalents in the runtime config file and registry if the environment isn't acceptable for some reason.

System.Numerics.Vectors for .NET Framework is supported and maintained, but the [servicing bar is high](https://blogs.msdn.microsoft.com/dotnet/2018/10/04/update-on-net-core-3-0-and-net-framework-4-8/) for all features due to compat risk, and it's even higher for older releases, which is why we encourage new code to target .NET Core.

**Comment by vpenades** [comment] 2019-02-08 19:12
@RussKeldorph thanks a lot, this is exactly what I wanted to know.

I'll give a try to the COMPlus features and see if it fixes our issues

👍

**Comment by RussKeldorph** [comment] 2019-03-12 15:45
Closing at it seems primarily concerned with .NET Framework, not Core.  Feel free to open a new issue about Core if there are still problems.

**Closed by RussKeldorph** 2019-03-12 15:45 UTC
