### ISSUE TITLE
JIT : PMI now failing on System.Private.CoreLib on an x64 AES intrinsic

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#18727] opened 2018-06-30 00:11 UTC
The x64 windows run of PMI over System.Private.Corelib is now failing when trying to jit `X86.Aes.Decrypt` as this method exists in metadata and is marked as an intrinsic, but the jit does not recognize it. This is relatively new (~ last few days) behavior.

Would be nice to fix this by (say) adding in the names to the recognizer and then (for now) just compiling in the not supported variant.

cc @dotnet/jit-contrib

**Comment by tannergooding** [comment] 2018-06-30 02:22
@AndyAyersMS, I'll get a fix up tonight.

I do not believe this is new behavior, however. There hasn't been any changes to the AES intrinsics (or even any work even done on them).

**Comment by tannergooding** [comment] 2018-06-30 23:20
@AndyAyersMS, actually, before I take a closer look at this; Do you have an inkling of what changed here (or logs/repro steps)?

As indicated, no work has been done on AES yet, and there are other ISAs in the same boat (such as `Bmi1`, `Bmi2`, and `Pclmulqdq`) which were not also called out here....

**Comment by AndyAyersMS** [comment] 2018-07-01 01:15
Repro steps:

* clone the jitutils repo (say as d:\repos\jitutils)
* run bootstrap.cmd from repo root
* build checked x64 coreclr and test overlay
* run PMI.dll from jitutils\bin over system.private.corelib with PREPALL or equivalent

For example: (though now it is failing on a different intrinsic, so my diagnosis above may be off)

```
D:\repos\coreclr\bin\tests\Windows_NT.x64.checked\Tests\Core_Root\corerun.exe D:\repos\jitutils\bin\pmi.dll PREPALL-QUIET D:\repos\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\System.Private.CoreLib.dll

InvalidProgramException System.Runtime.Intrinsics.X86.Aes::Decrypt

InvalidProgramException System.Runtime.Intrinsics.X86.Aes::DecryptLast

....

InvalidProgramException System.Runtime.Intrinsics.X86.Sse42::CompareExplicitLengthUnitMask

Assert failure(PID 18868 [0x000049b4], Thread: 21344 [0x5360]): Assertion failed 'HWIntrinsicInfo::lookupIns(intrinsic, baseType) != INS_invalid' in 'System.Runtime.Intrinsics.X86.Ssse3:Shuffle(struct,struct):struct' (IL size 8)

    File: d:\repos\coreclr\src\jit\hwintrinsicxarch.cpp Line: 767
    Image: D:\repos\coreclr\bin\tests\Windows_NT.x64.checked\Tests\Core_Root\CoreRun.exe
```

**Comment by fiigii** [comment] 2018-07-01 08:40
Is this failure related to the recent API change https://github.com/dotnet/coreclr/pull/18663 ?
But it only changes the unimplemented APIs.

**Comment by tannergooding** [comment] 2018-07-01 14:59
> Is this failure related to the recent API change #18663 ?

That might it explain it, if PMI was looking at one view (such as the CoreFX reference library) as compared to the corelib view (where the APIs were reviewed).

> But it only changes the unimplemented APIs.

Right, but one of those APIs is for an ISA that is marked as fully implemented, hence the new assert. I imagine that the initial failure fell out before the CoreFX reference library was updated and made its way back to CoreCLR. While the new failure is after...

CC. @CarolEidt, @eerhardt, @fiigii. Regardless of whether the above is the cause of this issue; we need to be careful when adding/modifying APIs here and, at the very least, ensure an issue tracking the JIT implementation gets put up (so things like the new `Ssse3.Shuffle` API don't get lost in the flow).

**Comment by tannergooding** [comment] 2018-07-01 15:07
https://github.com/dotnet/coreclr/pull/18738

**Comment by tannergooding** [comment] 2018-08-02 16:41
Closing this, as https://github.com/dotnet/coreclr/pull/19247 gives us a clean PMI run.

**Closed by tannergooding** 2018-08-02 16:41 UTC
Labels: arch-x64, area-CodeGen
