### ISSUE TITLE
(sbyte) cast gives a wrong value for optimized code

### ISSUE THREAD

**Issue by perjumarcel** [dotnet/coreclr#20439] opened 2018-10-16 16:43 UTC
The problem can be reproduced with the following code sample, having NUnit 3 installed.
```C#
[TestFixture]
public class SByteFixture
{
    [Test]
    public void Test()
    {
        var data = new byte[] { 0xFF };

        sbyte x = -128;
        data[0] = (byte) x;
        byte b1 = data[0];
        var b2 = (sbyte) b1;
        Assert.AreEqual(b1.ToString(), "128");
        Assert.AreEqual(b2.ToString(), "-128");
    }
}
```

- The project should be a **class library** because in a **console application** it's not reproducible.
- Should have the optimization enabled, i.e. the following setting in the csproj file:

```XML
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>true</Optimize>
</PropertyGroup>
```

The test **passes** when **Optimize is false**, but it **fails** when **Optimize is true** (`b2.ToString()` gives `"128"`).

This can be seen using **ReSharper** for running the test or **NUnitConsole**, not reproducible with **VS Test Explorer**.

This looks like an issue in the JIT.

**Comment by AndyAyersMS** [comment] 2018-10-16 16:48
cc @dotnet/jit-contrib

**Comment by mikedn** [comment] 2018-10-16 17:55
It would be good to know what .NET kind/version you are using.

The fact that you can reproduce in a class library and not a console application might mean that you're using .NET Framework and not .NET Core. In .NET Framework console apps default to 32 bit so they use the legacy JIT32, not RyuJIT. 64 bit .NET Framework apps use RyuJIT but it's typically an older version than the one used by .NET Core.

I can reproduce this issue using 64 bit .NET Framework 4.7.2 but not the current master version of .NET Core. It can be reproduce using .NET Core 2.1 so it's likely that this was already fixed in master.

**Comment by perjumarcel** [comment] 2018-10-17 09:03
I'm also using .Net Framework 4.7.2 (r=461814)

**Comment by jakobbotsch** [comment] 2018-10-17 09:17
Probably a duplicate of #18235, the 255 byte value being the "giveaway".

**Comment by mikedn** [comment] 2018-10-17 16:32
> Probably a duplicate of #18235, the 255 byte value being the "giveaway".

Yep, I can reproduce the bug if I revert the changes in your #18627.

**Comment by briansull** [comment] 2018-10-23 17:55
Closing as this is a duplicate of #18235 
Also the next release of the Desktop CLR will contain the fix for this.

**Closed** 2018-11-06 10:37 UTC
Labels: area-CodeGen, bug
