### ISSUE TITLE
Track conversion of Intel Hardware Intrinsics tests to generated format

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#19400] opened 2018-08-10 01:46 UTC
This is an umbrella issue to track progress of conversion of all tests as detailed in #19245 and #19246

### Avx
 [ ]  Blend
 [ ]  BroadcastScalarToVector128
 [ ]  BroadcastScalarToVector256
 [ ]  BroadcastVector128ToVector256
 [ ]  CompareScalar
 [ ]  Compare
 [ ]  ConvertToSingle
 [ ]  ConvertToVector
 [ ]  DotProduct
 [ ]  HorizontalAdd
 [ ]  HorizontalSubtract
 [ ]  InsertExtractVector128
 [ ]  LoadAlignedVector256
 [ ]  LoadDquVector256
 [ ]  LoadVector256
 [ ]  MaskLoad
 [ ]  MoveMask
 [ ]  Permute2x128.Avx
 [ ]  SetAllVector256
 [ ]  SetVector256
 [ ]  SetZeroVector256
 [ ]  Sqrt
 [ ]  StaticCast
 [ ]  StoreAlignedNonTemporal
 [ ]  StoreAligned
 [ ]  Store
 [ ]  UnpackHigh
 [ ]  UnpackLow

### Avx2
 [ ]  AddSaturate
 [ ]  BroadcastVector128ToVector256
 [ ]  ConvertToVector256
 [ ]  HorizontalAdd
 [ ]  HorizontalSubtract
 [ ]  LoadAlignedVector256NonTemporal
 [ ]  MoveMask
 [ ]  Multiply
 [ ]  ShiftLeftLogicalVariable
 [ ]  ShiftRightLogicalVariable
 [ ]  SubtractSaturate
 [ ]  UnpackHigh
 [ ]  UnpackLow

### Sse
 [ ]  ConvertScalarToVector128Single
 [ ]  ConvertToInt32WithTruncation #19998
 [ ]  ConvertToInt32 #19998
 [ ]  ConvertToInt64WithTruncation #19998
 [ ]  ConvertToInt64 #19998
 [ ]  ConvertToSingle #19998
 [ ]  LoadAlignedVector128
 [ ]  LoadHigh
 [ ]  LoadLow
 [ ]  LoadScalarVector128
 [ ]  LoadVector128
 [ ]  MoveHighToLow
 [ ]  MoveLowToHigh
 [ ]  MoveMask
 [ ]  MoveScalar
 [ ]  Prefetch
 [ ]  ReciprocalScalar
 [ ]  ReciprocalSqrtScalar
 [ ]  ReciprocalSqrt
 [ ]  Reciprocal
 [ ]  SetAllVector128
 [ ]  SetScalarVector128
 [ ]  SetVector128
 [ ]  SetZeroVector128
 [ ]  Shuffle
 [ ]  SqrtScalar
 [ ]  Sqrt
 [ ]  StaticCast
 [ ]  StoreAlignedNonTemporal
 [ ]  StoreAligned
 [ ]  StoreFence
 [ ]  StoreHigh
 [ ]  StoreLow
 [ ]  StoreScalar
 [ ]  Store
 [ ]  UnpackHigh
 [ ]  UnpackLow

### Sse2
 [x]  CompareEqualOrderedScalar #19673
 [x]  CompareEqualScalar #19673
 [x]  CompareEqualUnorderedScalar #19673
 [x]  CompareGreaterThanOrderedScalar #19673
 [x]  CompareGreaterThanOrEqualOrderedScalar #19673
 [x]  CompareGreaterThanOrEqualScalar #19673
 [x]  CompareGreaterThanOrEqualUnorderedScalar #19673
 [x]  CompareGreaterThanScalar #19673
 [x]  CompareGreaterThanUnorderedScalar #19673
 [x]  CompareLessThanOrderedScalar #19673
 [x]  CompareLessThanOrEqualOrderedScalar #19673
 [x]  CompareLessThanOrEqualScalar #19673
 [x]  CompareLessThanOrEqualUnorderedScalar #19673
 [x]  CompareLessThanScalar #19673
 [x]  CompareLessThanUnorderedScalar #19673
 [x]  CompareNotEqualOrderedScalar #19673
 [x]  CompareNotEqualScalar #19673
 [x]  CompareNotEqualUnorderedScalar #19673
 [x]  CompareNotGreaterThanOrEqualScalar #19673
 [x]  CompareNotGreaterThanScalar #19673
 [x]  CompareNotLessThanOrEqualScalar #19673
 [x]  CompareNotLessThanScalar #19673
 [x]  CompareOrderedScalar #19673
 [x]  CompareUnorderedScalar #19673
 [ ]  ConvertScalarToVector128Double
 [ ]  ConvertScalarToVector128Int32 #19998
 [ ]  ConvertScalarToVector128Int64 #19998
 [ ]  ConvertScalarToVector128Single
 [ ]  ConvertScalarToVector128UInt32 #19998
 [ ]  ConvertScalarToVector128UInt64 #19998
 [x]  ConvertToDouble #19677 
 [x]  ConvertToInt32WithTruncation #19677
 [x]  ConvertToInt32 #19677
 [x]  ConvertToInt64WithTruncation #19677
 [x]  ConvertToInt64 #19677
 [x]  ConvertToUInt32 #19677
 [x]  ConvertToUInt64 #19677
 [x]  ConvertToVector128Double #19677
 [x]  ConvertToVector128Int32WithTruncation #19677
 [x]  ConvertToVector128Int32 #19677
 [x]  ConvertToVector128Single #19677
 [ ]  LoadAlignedVector128
 [ ]  LoadFence
 [ ]  LoadHigh
 [ ]  LoadLow
 [ ]  LoadScalarVector128
 [ ]  LoadVector128
 [ ]  MaskMove
 [ ]  MemoryFence
 [ ]  MoveMask
 [ ]  MoveScalar.Int64
 [ ]  MoveScalar.UInt64
 [ ]  MoveScalar
 [ ]  MultiplyHigh
 [ ]  MultiplyHorizontalAdd
 [ ]  MultiplyLow
 [ ]  Multiply
 [ ]  PackSignedSaturate #19670
 [ ]  PackUnsignedSaturate #19670
 [ ]  SetScalarVector128
 [ ]  SetVector128
 [ ]  SetZeroVector128
 [ ]  ShuffleHigh
 [ ]  ShuffleLow
 [ ]  Shuffle
 [ ]  SqrtScalar
 [ ]  Sqrt
 [ ]  StoreAlignedNonTemporal
 [ ]  StoreAligned
 [ ]  StoreHigh
 [ ]  StoreLow
 [ ]  StoreNonTemporal
 [ ]  StoreScalar
 [ ]  Store
 [ ]  SumAbsoluteDifferences
 [ ]  UnpackHigh #19670
 [ ]  UnpackLow #19670

### Sse3
 [ ]  LoadAndDuplicateToVector128
 [ ]  LoadDquVector128
 [ ]  MoveAndDuplicate
 [ ]  MoveHighAndDuplicate
 [ ]  MoveLowAndDuplicate

### Sse41
 [ ]  Blend
 [ ]  ConvertToVector128
 [ ]  DotProduct
 [ ]  LoadAlignedVector128NonTemporal
 [ ]  MinHorizontal
 [ ]  MultipleSumAbsoluteDifferences
 [ ]  Multiply

### Sse42
 [ ]  Crc32

### Ssse3
 [ ]  AlignRight

**Comment by 4creators** [comment] 2018-08-10 01:46
cc @CarolEidt @eerhardt  @fiigii @tannergooding

**Comment by tannergooding** [comment] 2019-09-20 22:47
Closing as dupe of #19246.

The list above is out of sync with the actual state of the tests that are templated vs not; so a new pass will need to be done to see what still needs fixing.

**Closed by tannergooding** 2019-09-20 22:47 UTC
Labels: area-CodeGen, test enhancement
