### ISSUE TITLE
Codegen for `LoadVector128` for a field of a struct is "poor"

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#19521] opened 2018-08-16 22:33 UTC
As per the comment here: https://github.com/dotnet/corefx/pull/31779/files#r210758497

The `SSE` implementation of `Matrix4x4.Transpose` is doing:
```csharp
var row1 = Sse.LoadVector128(&matrix.M11);
var row2 = Sse.LoadVector128(&matrix.M21);
var row3 = Sse.LoadVector128(&matrix.M31);
var row4 = Sse.LoadVector128(&matrix.M41);
```

Which leads to the following codegen:
```asm
mov      rax, rdx
vmovups  xmm0, xmmword ptr [rax]
lea      rax, bword ptr [rdx+16]
mov      r8, rax
vmovups  xmm1, xmmword ptr [r8]
lea      r8, bword ptr [rdx+32]
mov      r9, r8
vmovups  xmm2, xmmword ptr [r9]
lea      r9, bword ptr [rdx+48]
mov      r10, r9
vmovups  xmm3, xmmword ptr [r10]
```

Ideally, we should be generating the following instead:
```asm
vmovups  xmm0, xmmword ptr [rdx]
vmovups  xmm1, xmmword ptr [rdx+16]
vmovups  xmm2, xmmword ptr [rdx+32]
vmovups  xmm3, xmmword ptr [rdx+48]
```

**Comment by tannergooding** [comment] 2018-08-16 22:35
FYI. @fiigii, @CarolEidt, @eerhardt

**Comment by fiigii** [comment] 2018-08-16 22:40
The additional `LEA` is not surprising for the unsafe intrinsic. But the redundant `mov`s look so odd, we probably need look into IR with JITDump.

**Comment by tannergooding** [comment] 2018-08-16 22:45
Potentially not surprising, but still something that we should ensure is properly handled (we shouldn't be executing 3x the instructions, if we don't have to).

**Comment by 4creators** [comment] 2018-08-18 14:49
Fragment of real life code with similar solution to given above gives the following disasm (r is a pointer to struct with 4 double fields):

```asm

double* rD = (double*)r;   
-- | --
00007ffd`19ab414a 4c8d4840        lea     r9,[rax+40h] 
00007ffd`19ab414e c4c17b1209      vmovddup xmm1,mmword ptr [r9]

// No AVX

00007ffd`1a2b3f37 4c8d4840        lea     r9,[rax+40h] |  
00007ffd`1a2b3f3b f2410f1209      movddup xmm1,mmword ptr [r9]
```
Efficient codegen should most likely look like:

```asm
00007ffd`19ab414e c4c17b1209      vmovddup xmm1,mmword ptr [rax+40h]
00007ffd`1a2b3f3b f2410f1209      movddup xmm1,mmword ptr [rax+40h]
```

Seems that jit is having problems with folding struct pointer cast to `double*` pointer into load address calculation.

Another piece of code that isolates some of the above issues and show one more significant issue:

```asm
;StoreAligned(rf, Subtract(iVec, LoadAlignedVector128((double*)(items + j))));                  
00007ffd`19ab4167 4d63d9          movsxd  r11, r9d   
00007ffd`19ab416a 49c1e306        shl     r11, 6   
00007ffd`19ab416e 4c03d8          add     r11, rax   
00007ffd`19ab4171 c4c1792813      vmovapd xmm2,xmmword ptr [r11]   
00007ffd`19ab4176 c4e1715cd2      vsubpd  xmm2, xmm1, xmm2   
00007ffd`19ab417b c4c1792912      vmovapd xmmword ptr [r10],xmm2   
;StoreScalar(rf + 2, Subtract(iVec, LoadAlignedVector128(((double*)(items + j)) + 2)));                  
00007ffd`19ab4180 4983c310        add     r11, 10h  
00007ffd`19ab4184 c4c1792813      vmovapd xmm2, xmmword ptr [r11]   
00007ffd`19ab4189 c4e1715cd2      vsubpd  xmm2, xmm1, xmm2  
00007ffd`19ab418e 4983c210        add     r10,10h   
00007ffd`19ab4192 c4c17b1112      vmovsd  qword ptr [r10], xmm2

```

Expected codegen should most likely look like:

```asm

;StoreAligned(rf, Subtract(iVec, LoadAlignedVector128((double*)(items + j))));                  
00007ffd`19ab4167 4d63d9          movsxd  r11,r9d   
00007ffd`19ab416a 49c1e306        shl     r11,6   
00007ffd`19ab416e 4c03d8          add     r11,rax   
00007ffd`19ab4176 c4e1715cd2      vsubpd  xmm2, xmm1, xmmword ptr [r11]   
00007ffd`19ab417b c4c1792912      vmovapd xmmword ptr [r10],xmm2   
;StoreScalar(rf + 2, Subtract(iVec, LoadAlignedVector128(((double*)(items + j)) + 2)));                  
00007ffd`19ab4189 c4e1715cd2      vsubpd  xmm2, xmm1, xmmword ptr [r11 + 10h] 
00007ffd`19ab4192 c4c17b1112      vmovsd  qword ptr [r10 + 10h], xmm2

```

However more important hit is due to not folding memory operands into operations on `xmm` registers. This optimization opportunity is tracked by #19550.

By following @CarolEidt example the codegen gets even worse:

```C#
            double* rD = (double*)r;
            double* itemsPtr = (double*)items;
            Vextor128<double> iVec = Sse3.LoadAndDuplicateToVector128(itemsPtr + 8);
            for (int j = 2; j < N; ++j, ++k)
            {
                Sse2.StoreAligned(rD + 4 * k, Sse2.Subtract(iVec, Sse2.LoadAlignedVector128(itemsPtr + j * 8)));
                Sse2.StoreScalar(rD + 4 * k + 2, Sse2.Subtract(iVec, Sse2.LoadAlignedVector128(itemsPtr + j * 8 + 2)));
            }
```

```asm

double* rD = (double*)r;        
-- | --
00007ffd`18cb3f37 4c8bc8          mov     r9,rax  
VecD iVec = LoadAndDuplicateToVector128(itemsPtr + 8);             
00007ffd`18cb3f3a 4983c140        add     r9,40h  
00007ffd`18cb3f3e f2410f1209      movddup xmm1,mmword ptr [r9]   
for (int j = 2; j < N; ++j, ++k)            
00007ffd`18cb3f43 41b902000000    mov     r9d,2   
StoreAligned(rD + 4 * k, Subtract(iVec, LoadAlignedVector128(itemsPtr + j * 8)));                  
00007ffd`18cb3f49 458bd0          mov     r10d,r8d   
00007ffd`18cb3f4c 41c1e202        shl     r10d,2   
00007ffd`18cb3f50 4d63d2          movsxd  r10,r10d   
00007ffd`18cb3f53 4e8d14d2        lea     r10,[rdx+r10*8]   
00007ffd`18cb3f57 458bd9          mov     r11d,r9d   
00007ffd`18cb3f5a 41c1e303        shl     r11d,3   
00007ffd`18cb3f5e 4d63db          movsxd  r11,r11d  
00007ffd`18cb3f61 4e8d1cd8        lea     r11,[rax+r11*8]   
00007ffd`18cb3f65 0f28d1          movaps  xmm2,xmm1   
00007ffd`18cb3f68 66410f5c13      subpd   xmm2,xmmword ptr [r11]  
00007ffd`18cb3f6d 66410f2912      movapd  xmmword ptr [r10],xmm2   
StoreScalar(rD + 4 * k + 2, Subtract(iVec, LoadAlignedVector128(itemsPtr + j * 8 + 2)));                 
00007ffd`18cb3f72 4983c310        add     r11,10h   
00007ffd`18cb3f76 0f28d1          movaps  xmm2,xmm1   
00007ffd`18cb3f79 66410f5c13      subpd   xmm2,xmmword ptr [r11]  
00007ffd`18cb3f7e 4983c210        add     r10,10h   
00007ffd`18cb3f82 f2410f1112      movsd   mmword ptr [r10],xmm2


```

**Comment by 4creators** [comment] 2018-08-18 14:59
The good new from the above code is that in last example memory operands were folded into `subpd` instruction. 

```asm
00007ffd`18cb3f65 0f28d1          movaps  xmm2,xmm1   
00007ffd`18cb3f68 66410f5c13      subpd   xmm2,xmmword ptr [r11]  
00007ffd`18cb3f6d 66410f2912      movapd  xmmword ptr [r10],xmm2  
```

**Comment by 4creators** [comment] 2018-08-18 15:57
Another failing addressing pattern

```C#
                    StoreAligned(rD += 16, Subtract(iVec, LoadAlignedVector128(itemsPtr + 16)));
                    StoreAligned(rD += 2, Subtract(iVec, LoadAlignedVector128(itemsPtr + 18)));
                    StoreAligned(rD += 2, Subtract(iVec, LoadAlignedVector128(itemsPtr + 32)));
                    StoreAligned(rD += 2, Subtract(iVec, LoadAlignedVector128(itemsPtr + 34)));
```

```asm
StoreAligned(rD += 16, Subtract(iVec, LoadAlignedVector128(itemsPtr + 16)));                     
-- | --
00007ffd`0fbb4a40 4c8d9a80000000  lea     r11,[rdx+80h] |  
00007ffd`0fbb4a47 4c8d8080000000  lea     r8,[rax+80h] |  
00007ffd`0fbb4a4e 0f28d1          movaps  xmm2,xmm1 |  
00007ffd`0fbb4a51 66410f5c10      subpd   xmm2,xmmword ptr [r8] |  
00007ffd`0fbb4a56 66410f2913      movapd  xmmword ptr [r11],xmm2 |  
StoreAligned(rD += 2, Subtract(iVec, LoadAlignedVector128(itemsPtr + 18)));                     
00007ffd`0fbb4a5b 4d8d4310        lea     r8,[r11+10h] |  
00007ffd`0fbb4a5f 4c8d8890000000  lea     r9,[rax+90h] |  
00007ffd`0fbb4a66 0f28d1          movaps  xmm2,xmm1 |  
00007ffd`0fbb4a69 66410f5c11      subpd   xmm2,xmmword ptr [r9] |  
00007ffd`0fbb4a6e 66410f2910      movapd  xmmword ptr [r8],xmm2 |  
StoreAligned(rD += 2, Subtract(iVec, LoadAlignedVector128(itemsPtr + 32)));                     
00007ffd`0fbb4a73 4983c010        add     r8,10h |  
00007ffd`0fbb4a77 4c8d8800010000  lea     r9,[rax+100h] |  
00007ffd`0fbb4a7e 0f28d1          movaps  xmm2,xmm1 |  
00007ffd`0fbb4a81 66410f5c11      subpd   xmm2,xmmword ptr [r9] |  
00007ffd`0fbb4a86 66410f2910      movapd  xmmword ptr [r8],xmm2 |  
StoreAligned(rD += 2, Subtract(iVec, LoadAlignedVector128(itemsPtr + 34)));                     
00007ffd`0fbb4a8b 4983c010        add     r8,10h |  
00007ffd`0fbb4a8f 4c8d8810010000  lea     r9,[rax+110h] |  
00007ffd`0fbb4a96 66410f5c09      subpd   xmm1,xmmword ptr [r9] |  
00007ffd`0fbb4a9b 66410f2908      movapd  xmmword ptr [r8],xmm1



```

**Comment by fiigii** [comment] 2018-08-18 19:49
> coming into the backend (Lowering) &matrix would be in a lclVar, and the various load addresses would be that lclVar plus an offset. One might expect CSE to do that;

We could introduce a forward substitution phase in the lowering to adddress this issue.

**Comment by mikedn** [comment] 2018-09-10 17:16
To recap from the PR:

The initial case described in this issue is rather special with respect to LEAs - it happens when `matrix` is a method parameter or local variable. It's mostly caused by JIT's handling of structs and/or address taken local variables.

The tree generated for one matrix row load looks like:
```
     (  9,  8) [000031] ------------              *  STMT      void  (IL   ???...0x028)
N008 (  5,  5) [000027] -A-XG-------              |  /--*  HWIntrinsic simd16 float LoadVector128
N006 (  1,  1) [000074] ------------              |  |  |  /--*  LCL_VAR   long   V10 tmp4         
N007 (  4,  4) [000076] -A--G-------              |  |  \--*  COMMA     long  
N002 (  1,  1) [000077] ------------              |  |     |     /--*  CNS_INT   long   32 field offset Fseq[M31]
N003 (  3,  3) [000078] ------------              |  |     |  /--*  ADD       byref 
N001 (  1,  1) [000022] ------------              |  |     |  |  \--*  LCL_VAR   byref  V01 arg0         
N005 (  3,  3) [000073] -A--G---R---              |  |     \--*  ASG       long  
N004 (  1,  1) [000072] D------N----              |  |        \--*  LCL_VAR   long   V10 tmp4         
N010 (  9,  8) [000030] -A-XG---R---              \--*  ASG       simd16 (copy)
N009 (  3,  2) [000028] D------N----                 \--*  LCL_VAR   simd16 V03 loc1         
```
I haven't yet checked why it's so complicated. It's possible that struct copy morph doesn't realize that it doesn't need to field by field copying and generates and prepares to do that by storing the address into a temporary for use in subsequent field copies.

There's another approach that doesn't involve explicit intrinsic loads:
```C#
var row1 = Unsafe.As<float, Vector128<float>>(ref matrix.M11);
```
This generates smaller IR:
```
     (  6,  5) [000049] ------------              *  STMT      void  (IL   ???...  ???)
N004 (  6,  5) [000038] x---G-------              |  /--*  IND       simd16
N002 (  1,  1) [000098] ------------              |  |  |  /--*  CNS_INT   long   32 field offset Fseq[M31]
N003 (  3,  3) [000099] ------------              |  |  \--*  ADD       byref 
N001 (  1,  1) [000088] ------------              |  |     \--*  LCL_VAR   byref  V01 arg0         
N006 (  6,  5) [000048] -A--G---R---              \--*  ASG       simd16 (copy)
N005 (  1,  1) [000046] D------N----                 \--*  LCL_VAR   simd16 V07 tmp2  
```
and in the case of method parameters this actually works well. The parameter is actually an address, you get an indir, the indir gets contained etc.

However, this stops working when `matrix` is a local variable. You get:
```
     (  6,  7) [000025] ------------              *  STMT      void  (IL   ???...  ???)
N003 (  6,  7) [000014] x---G-------              |  /--*  IND       simd16 <l:$240, c:$241>
N002 (  3,  5) [000078] ----G-------              |  |  \--*  ADDR      byref  $200
N001 (  3,  4) [000081] -------N----              |  |     \--*  LCL_FLD   float  V02 loc0         u:2[+0] Fseq[M11] $180
N005 (  6,  7) [000024] -A--G---R---              \--*  ASG       simd16 (copy) $VN.Void
N004 (  1,  1) [000022] D------N----                 \--*  LCL_VAR   simd16 V07 tmp1         d:2
```
This will produce a LEA since codegen does not handle a contained LCL_FLD address. Perhaps it should. But what you really want is to have only `LCL_FLD` instead of `IND(ADDR(LCL_FLD))` to avoid taking the address of the local variables.

That's likely doable but if we get back to the original example there we have an intrinsic instead of a normal indir. If we want that to work well then we'll have to transform the intrinsic into a `LCL_FLD`.

**Comment by mikedn** [comment] 2018-09-10 17:37
>  StoreAligned(rD += 16, Subtract(iVec, LoadAlignedVector128(itemsPtr + 16)));

As far as I can tell this is all in the intrinsic implementation's backyard. The IR looks reasonable:
```
     (  8,  8) [000074] ------------              *  STMT      void  (IL   ???...  ???)
N005 (  4,  4) [000071] ---XG-------              |     /--*  HWIntrinsic simd16 float LoadAlignedVector128 $146
N003 (  1,  1) [000069] ------------              |     |  |  /--*  CNS_INT   long   72 $c4
N004 (  3,  3) [000070] ------------              |     |  \--*  ADD       long   $246
N002 (  1,  1) [000064] ------------              |     |     \--*  LCL_VAR   long   V13 tmp7         u:2 $241
N006 (  6,  6) [000072] ---XG-------              |  /--*  HWIntrinsic simd16 float Subtract $147
N001 (  1,  1) [000063] ------------              |  |  \--*  LCL_VAR   simd16 V03 loc1         u:2 $282
N008 (  8,  8) [000073] -A-XG---R---              \--*  HWIntrinsic void   float StoreAligned $148
N007 (  1,  1) [000062] ------------                 \--*  LCL_VAR   long   V08 tmp2         u:2 $245
```
Apparently intrinsic lowering does not handle address more creation and containment like indirs do.

**Comment by mikedn** [comment] 2018-09-10 19:43
> Apparently intrinsic lowering does not handle address more creation and containment like indirs do.

Yep, there's no trace of address mode containment in the intrinsic code. There's little point of talking about any other LEA issues as long as intrinsics themselves do not support this.

**Comment by tannergooding** [comment] 2018-09-10 19:52
> Yep, there's no trace of address mode containment in the intrinsic code

Right. Most of the Load/Store intrinsic code was done quickly to get it working with the plan to revisit and make it correct later.

The last discussion was that (long term) we wanted to look at just making these indir nodes with the flags since it might be more generally useful and would help limit the code duplication that existed.

**Comment by CarolEidt** [comment] 2019-02-04 04:35
In lieu of forward substitution, at least for the case of JIT-created temps, the JIT currently takes the approach of avoiding the creation of such temps when it thinks they are undesirable, e.g. the case where they can be folded into an addressing mode. I am currently looking into whether this can be done for 3.0, at least for the intrinsic loads (if not for the case of further containing such loads with contained address expressions into arithmetic ops, as suggested in #19550).

**Comment by mikedn** [comment] 2019-02-04 06:54
>  I am currently looking into whether this can be done for 3.0

Hmm, there are multiple issues related to address mode handling but the lowering/codegen part of HW intrinsics is pretty easy to fix AFAIR. I could probably make a PR this week if anyone wants that.

**Comment by CarolEidt** [comment] 2019-02-04 15:31
@mikedn - I am actually working on this (should have assigned it to myself when I set the milestone), but thanks!

**Closed** 2019-03-26 23:13 UTC
Labels: area-CodeGen, enhancement, optimization
