### ISSUE TITLE
Convert DateTime parameter of TimeZoneInfo.GetAdjustmentRuleForTime to UTC before searching for timezone rule

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#5717] opened 2016-06-11 01:43 UTC
While investigating dotnet/coreclr#5558 it was noted that if the DateTime parameter of TimeZoneInfo.GetAdjustmentRuleForTime is Local it gets converted to UTC for every timezone rule being considered over and over. Instead, we can detect if it’s not Utc and do the conversion once outside the loop and make the method not do the check and always use the cheaper Utc path.

**Comment by AlexGhiondea** [comment] 2017-02-02 05:58
@tarekgh @erozenfeld is this something we would like to do for 2.0?

**Comment by erozenfeld** [comment] 2017-02-02 08:01
This is something I found when investigating Linux vs. Windows perf differences for some benchmarks back in June. I don't know if this is still an issue and can't comment on when this should be addressed.

**Comment by tarekgh** [comment] 2017-02-02 16:51
Hey @AlexGhiondea, TimeZoneInfo has a lot of work need to be done. there is a future plans (other issues tracking that). this issue and the other #5716 are kind of old but I think they are still valid. I don't think these are urgent for 2.0 but I'll leave this to you decide if you think otherwise. I have un-assigned myself for these 2 issues as I am not planning to work on these now. I'll be happy to help if this is decided to be high priority. @danmosemsft can advise about that too.

**Comment by tarekgh** [comment] 2017-02-02 16:53
I would suggest to change the milestone and mark these issues up-for-grab.

**Comment by danmosemsft** [comment] 2017-02-02 17:00
Woudl be great to make any perf improvement, but if it's not a regression or showing up in our key perf benchmarks it does not have to be done to ship

**Comment by karelz** [comment] 2017-03-22 23:56
This blocks dotnet/corefx#16636, flipping to 2.0

**Comment by mazong1123** [comment] 2017-04-12 03:05
Anyone working on this? If not, I'm willing to help.

**Comment by danmosemsft** [comment] 2017-04-12 03:25
@mazong1123 go for it! @karelz can you please assign to @mazong1123

**Comment by mazong1123** [comment] 2017-04-12 07:25
@erozenfeld I just went through the code and found the Utc converting is based on `previousRule`:
https://github.com/dotnet/coreclr/blob/f355c5789d5d7cd6ea10bee326c66f04641cfc90/src/mscorlib/src/System/TimeZoneInfo.cs#L1110-L1112

I may misunderstand something but seems like to move the converting out of `CompareAdjustmentRuleToDateTime` and keep the logic, we should ensure each rule has same `DaylightDelta` and `BaseUtcOffsetDelta`. Rules are loaded from [CompareAdjustmentRuleToDateTime](https://github.com/dotnet/coreclr/blob/cdff8b0babe5d82737058ccdae8b14d8ae90160d/src/mscorlib/src/System/TimeZoneInfo.Unix.cs#L820-L822) and seems like each rule may have different `DaylightDelta` and `BaseUtcOffsetDelta`. Please let me know if I missed something.

**Comment by mazong1123** [comment] 2017-04-12 10:20
Another performance improvement for DateTime.Now is leveraging the fact we live at the time after `1991-09-14`. `1991-09-14` is the last adjustment rule so if user calling DateTime.Now, we are likely to fall into the last adjustment rule's range. So if we just add following code before the binary search:

```cpp
if (dateTime >= _adjustmentRules[_adjustmentRules.Length - 1].DateStart)
{
    return _adjustmentRules[_adjustmentRules.Length - 1];
}
```

The performance gain for `DateTime.Now` is dramatic. I've borrowed the microbenchmark from [here](https://github.com/dotnet/coreclr/pull/10507). I only ran on Unix but I think Windows performance should be improved as well:

**Without my change:**
136<br>116<br>119<br>122<br>116<br>116<br>116<br>116<br>116<br>117<br>116<br>116<br>117<br>116<br>116<br>117<br>117<br>117<br>117<br>116<br>

**With my change:**
76<br>57<br>57<br>57<br>62<br>57<br>57<br>57<br>57<br>57<br>57<br>58<br>57<br>57<br>57<br>57<br>57<br>57<br>57<br>57<br>

**Comment by tarekgh** [comment] 2017-04-12 15:44
CC @eerhardt

**Comment by mazong1123** [comment] 2017-04-13 13:27
Hi guys, any update for this issue? Should I wait for @eerhardt 's work because he is already working on this. Please find https://github.com/dotnet/corefx/issues/3571#issuecomment-293762131

**Comment by tarekgh** [comment] 2017-04-13 15:46
@mazong1123 As you mentioned @eerhardt is looking at the perf of DateTime.Now and I am expecting he'll reply soon. thank you.

**Comment by eerhardt** [comment] 2017-04-13 19:52
@mazong1123 - here's some general information on how the TimeZoneInfo class works on both Windows and Unix: https://github.com/dotnet/corefx/issues/2465#issuecomment-127645308.  This is good information to know whenever dealing with changing how TimeZoneInfo deals with this AdjustmentRules.

> That means if we call ConvertToUtc earlier outside the loop, we have no chance to know which DaylightDelta and BaseUtcOffsetDelta should be passed in. Please let me know if I missed something.

You are correct here, you can't convert the time to UTC outside the loop because you don't know how to adjust the time.  That's what this code is trying to figure out - which rule should be used to adjust the UTC time to the specified time zone.  These rules change historically, and to be accurate you can't assume things like this time zone has always been +8 hrs ahead of UTC, and DaylightSavings was always in effect, etc.

> Another performance improvement for DateTime.Now is leveraging the fact we live at the time after 1991-09-14. 1991-09-14 is the start time of last adjustment rule 

Which time zone are you referring to?  This definitely isn't the case for the `America/Chicago` (Central Time) or `America/Los_Angeles` (Pacific Time) time zones.  On my ubuntu14.04 machine, the last rule's start date is around the year 2038.

> And any thoughts on adding this code before the binary search?

Before we do something like that, I'd like to see how many time zones this would actually apply to.  If it is only a few, I don't think it would help and it only slows down the code for most time zones.

### General Thoughts
I think I've learned my lesson on guessing at perf problems. Profiling the scenario was a lot more helpful to me than trying to guess where the issues lied.  In https://github.com/dotnet/corefx/issues/3571#issuecomment-293762131, I made a bunch of changes where I thought was the problem, only to find out after profiling that the real issue lied in a place I didn't even think to look.

@mazong1123 - if you want to try out profiling, I was very successful following these steps: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md.  Also, my suggestion would be to try your fix with various time zones.  You can easily do this by `set TZ=America/Los_Angeles` or any other time zone ID, before running the micro benchmark.

I'm going to go ahead with the fix I described in https://github.com/dotnet/corefx/issues/3571#issuecomment-293762131, which gets us pretty far on the `DateTime.Now` scenario.

**Comment by mazong1123** [comment] 2017-04-14 16:02
I'm running a microbenchmark for all timezones. I may generate a more accurate result tomorrow but currently I know we have 270 in total 424 timezones have their last adjustment rule behind current datetime . Add a pre-check before the binary search save 50% time for these timezones. We'll see what the cost of adding the pre-check for the left 154 timezones after the result generated.

**Comment by mazong1123** [comment] 2017-04-15 05:42
I just ran the whole 774 timezones on my Ubuntu 16.04 LTS x64 box. Attached is the benchmark for each timezone.

To summary the result, adding precheck will save 40% - 50% time for the timezones have their last adjustment rule behind current datetime, and for those timezones have their last adjustment rule after current datetime, there's no benifit from the precheck, and some have no impact to the performance, some have small impact to the performance.

Below are several examples. Please find the full benchmark in the attached file.

**Precheck saved 40% - 50% time:**
<table>
<th>Without Precheck</th>
<th>With Precheck</th>
 <tr>
  <td colspan="2">Marshall Islands Time</td>
 </tr>
 <tr>
  <td>118</td>
  <td>59</td>
 </tr>
 <tr>
  <td>116</td>
  <td>73</td>
 </tr>
 <tr>
  <td>116</td>
  <td>64</td>
 </tr>
 <tr>
  <td>116</td>
  <td>63</td>
 </tr>
 <tr>
  <td>115</td>
  <td>59</td>
 </tr>
 <tr>
  <td>115</td>
  <td>57</td>
 </tr>
 <tr>
  <td>117</td>
  <td>56</td>
 </tr>
 <tr>
  <td>116</td>
  <td>56</td>
 </tr>
 <tr>
  <td>116</td>
  <td>56</td>
 </tr>
 <tr>
  <td>115</td>
  <td>56</td>
 </tr>
 <tr>
  <td>116</td>
  <td>56</td>
 </tr>
 <tr>
  <td>116</td>
  <td>56</td>
 </tr>
 <tr>
  <td>115</td>
  <td>56</td>
 </tr>
 <tr>
  <td>115</td>
  <td>56</td>
 </tr>
 <tr>
  <td>118</td>
  <td>56</td>
 </tr>
 <tr>
  <td>114</td>
  <td>56</td>
 </tr>
 <tr>
  <td>114</td>
  <td>56</td>
 </tr>
 <tr>
  <td>114</td>
  <td>56</td>
 </tr>
 <tr>
  <td>115</td>
  <td>56</td>
 </tr>
<tr>
  <td colspan="2">West Africa Standard Time</td>
 </tr>
 <tr>
  <td></td>
 </tr>
 <tr>
  <td>143</td>
  <td>102</td>
 </tr>
 <tr>
  <td>141</td>
  <td>101</td>
 </tr>
 <tr>
  <td>142</td>
  <td>100</td>
 </tr>
 <tr>
  <td>141</td>
  <td>100</td>
 </tr>
 <tr>
  <td>142</td>
  <td>100</td>
 </tr>
 <tr>
  <td>140</td>
  <td>100</td>
 </tr>
 <tr>
  <td>141</td>
  <td>99</td>
 </tr>
 <tr>
  <td>142</td>
  <td>99</td>
 </tr>
 <tr>
  <td>141</td>
  <td>101</td>
 </tr>
 <tr>
  <td>142</td>
  <td>101</td>
 </tr>
 <tr>
  <td>142</td>
  <td>100</td>
 </tr>
 <tr>
  <td>139</td>
  <td>100</td>
 </tr>
 <tr>
  <td>140</td>
  <td>100</td>
 </tr>
 <tr>
  <td>141</td>
  <td>101</td>
 </tr>
 <tr>
  <td>143</td>
  <td>100</td>
 </tr>
 <tr>
  <td>141</td>
  <td>100</td>
 </tr>
 <tr>
  <td>141</td>
  <td>100</td>
 </tr>
 <tr>
  <td>140</td>
  <td>99</td>
 </tr>
 <tr>
  <td>142</td>
  <td>100</td>
 </tr>
 <tr>
  <td>141</td>
  <td>100</td>
 </tr>
</table>

**No benifit from the precheck and have no impact to the performance**
<table>
<th>Without Precheck</th>
<th>With Precheck</th>
 <tr>
  <td colspan="2">Central Standard Time</td>
 </tr>
 <tr>
  <td></td>
 </tr>
 <tr>
  <td>1116</td>
  <td>1149</td>
 </tr>
 <tr>
  <td>1113</td>
  <td>1105</td>
 </tr>
 <tr>
  <td>1196</td>
  <td>1102</td>
 </tr>
 <tr>
  <td>1432</td>
  <td>1102</td>
 </tr>
 <tr>
  <td>1344</td>
  <td>1101</td>
 </tr>
 <tr>
  <td>1114</td>
  <td>1104</td>
 </tr>
 <tr>
  <td>1115</td>
  <td>1103</td>
 </tr>
 <tr>
  <td>1112</td>
  <td>1103</td>
 </tr>
 <tr>
  <td>1115</td>
  <td>1104</td>
 </tr>
 <tr>
  <td>1315</td>
  <td>1101</td>
 </tr>
 <tr>
  <td>1305</td>
  <td>1106</td>
 </tr>
 <tr>
  <td>1114</td>
  <td>1102</td>
 </tr>
 <tr>
  <td>1119</td>
  <td>1104</td>
 </tr>
 <tr>
  <td>1114</td>
  <td>1103</td>
 </tr>
 <tr>
  <td>1114</td>
  <td>1102</td>
 </tr>
 <tr>
  <td>1349</td>
  <td>1102</td>
 </tr>
 <tr>
  <td>1272</td>
  <td>1103</td>
 </tr>
 <tr>
  <td>1113</td>
  <td>1103</td>
 </tr>
 <tr>
  <td>1114</td>
  <td>1103</td>
 </tr>
 <tr>
  <td>1114</td>
  <td>1104</td>
 </tr>
</table>

**No benifit from the precheck but have small impact to the performance**
<table>
<tr>
  <td colspan="2">Pacific Standard Time</td>
 </tr>
 <tr>
  <td></td>
 </tr>
 <tr>
  <td>1831</td>
  <td>1934</td>
 </tr>
 <tr>
  <td>1824</td>
  <td>1930</td>
 </tr>
 <tr>
  <td>1839</td>
  <td>1930</td>
 </tr>
 <tr>
  <td>1848</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1823</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1833</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1823</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1823</td>
  <td>1930</td>
 </tr>
 <tr>
  <td>1824</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1823</td>
  <td>1930</td>
 </tr>
 <tr>
  <td>1821</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1823</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1821</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1821</td>
  <td>1930</td>
 </tr>
 <tr>
  <td>1820</td>
  <td>1932</td>
 </tr>
 <tr>
  <td>1822</td>
  <td>1931</td>
 </tr>
 <tr>
  <td>1821</td>
  <td>1960</td>
 </tr>
 <tr>
  <td>1821</td>
  <td>1932</td>
 </tr>
 <tr>
  <td>1821</td>
  <td>1932</td>
 </tr>
 <tr>
  <td>1819</td>
  <td>1930</td>
 </tr>
</table>

It's a tradeoff. IMO if we really sick of the performance, it's worth to do the precheck and opimize the regressed ones because it saves 40% - 50% for some timezones. We may somehow do the binary search directly for those regressed ones and do the precheck for others.

@eerhardt do you think is it worth going further more in this direction?

[timezone_benchmark.xlsx](https://github.com/dotnet/coreclr/files/923324/timezone_benchmark.xlsx)

**Comment by eerhardt** [comment] 2017-04-17 15:15
> @eerhardt do you think is it worth going further more in this direction?

It looks like it does really cut time off for some time zones.  So I think continuing to investigate how we can eliminate this search is worthwhile.

What do you think of this approach?  https://github.com/eerhardt/coreclr/commit/3ccc8be6f6cd13890c077442860fa047c1a109f2.  Basically it is caching the "current" AdjustmentRule for DateTime.Now for the Local time zone.  This should move all time zones towards the results you are seeing since we won't have to do this search.

Thoughts?

**Comment by eerhardt** [comment] 2017-04-19 14:38
I'm going to close this issue for the following reasons:

1. As noted in [@mazong1123's comment](https://github.com/dotnet/coreclr/issues/5717#issuecomment-293496104) and [my comment](https://github.com/dotnet/coreclr/issues/5717#issuecomment-294004669) you can't do what the issue is asking and be 100% correct for all time zone rules.  There is no way to convert the DateTime to Utc before finding the appropriate rule to use to do the conversion.
1. With the merge of https://github.com/dotnet/coreclr/pull/10507 and https://github.com/dotnet/coreclr/pull/10948 the scenario is much faster.  We should re-profile https://github.com/dotnet/coreclr/issues/5558 and see what the next set of perf bottlenecks are.

@mazong1123 - feel free to continue your investigation and log separate issues, if necessary.

**Closed by eerhardt** 2017-04-19 14:38 UTC
Labels: area-System.Runtime, tenet-performance, up-for-grabs
