### ISSUE TITLE
Test failure on Windows - JitBlue_devdiv_902271_DevDiv_902271_DevDiv_902271_._

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2536] opened 2016-01-05 21:59 UTC
This is a Windows failure...
d:\repos\coreclr\tests\src\TestWrappers_x64_debug\JIT\JIT.XUnitWrapper.cs(234485): error : JIT._Regression_JitBlue_devdiv_902271_DevDiv_902271_DevDiv_902271_._
Regression_JitBlue_devdiv_902271_DevDiv_902271_DevDiv_902271_cmd [FAIL] [D:\repos\coreclr\tests\runtest.proj]

  Process is terminated due to StackOverflowException.

  Raw output:      D:\repos\coreclr\bin\tests\Windows_NT.x64.debug\Reports\JIT\Regression\JitBlue\devdiv_902271\DevDiv_902271\DevDiv_902271.output.txt
  To run the test:
  > set CORE_ROOT=D:\repos\coreclr\bin\tests\Windows_NT.x64.debug\Tests\Core_Root
  > D:\repos\coreclr\bin\tests\Windows_NT.x64.debug\JIT\Regression\JitBlue\devdiv_902271\DevDiv_902271\DevDiv_902271.cmd

        Expected: True
        Actual:   False
          src\TestWrappers_x64_debug\JIT\JIT.XUnitWrapper.cs(234485,0): at JIT._Regression_JitBlue_devdiv_902271_DevDiv_902271_DevDiv_902271_._Regression_JitBl
  ue_devdiv_902271_DevDiv_902271_DevDiv_902271_cmd()

**Comment by sivarv** [comment] 2016-01-06 01:16
Closing this as it is a duplicate of issue #2334

**Closed by sivarv** 2016-01-06 01:16 UTC
Labels: bug, CodeGen
