### ISSUE TITLE
Test failed:  Loader_NativeLibs._FromNativePaths_FromNativePaths_._FromNativePaths_FromNativePaths_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22675] opened 2019-02-18 01:32 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_jitstress2_jitstressregs4_tst/50/

**Failed tests:**
Loader_NativeLibs._FromNativePaths_FromNativePaths_._FromNativePaths_FromNativePaths_sh

**Log:**
```
Loader_NativeLibs._FromNativePaths_FromNativePaths_._FromNativePaths_FromNativePaths_sh [FAIL]
        /n/nReturn code:      1/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs4_tst/bin/tests/Linux.arm.Checked/Loader/NativeLibs/Reports/Loader.NativeLibs/FromNativePaths/FromNativePaths.output.txt/nRaw output:/nBEGIN EXECUTION
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs4_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun FromNativePaths.exe ''
        FromNativePaths failed: Failed to load the native library: Unable to find an entry point named 'NativeFunc' in shared library 'FromNativePaths_lib'.
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs4_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_jitstress2_jitstressregs4_tst/bin/tests/Linux.arm.Checked/Loader/NativeLibs/FromNativePaths/FromNativePaths.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/bin/tests/Linux.arm.Checked/TestWrappers/Loader.NativeLibs/Loader.NativeLibs.XUnitWrapper.cs(109,0): at Loader_NativeLibs._FromNativePaths_FromNativePaths_._FromNativePaths_FromNativePaths_sh()
```

**Comment by VincentBu** [comment] 2019-02-18 01:32
related with https://github.com/dotnet/coreclr/issues/12521

**Comment by RussKeldorph** [comment] 2019-02-19 21:03
Duplicate of #22549

**Closed by RussKeldorph** 2019-02-19 21:03 UTC
