### ISSUE TITLE
How to train your dragon!

### ISSUE THREAD

**Issue by richlander** [dotnet/coreclr#744] opened 2015-04-20 18:45 UTC
As you know, the .NET Team, as a broad group, is new to open source. We're doing some things right and other things less so. We might as well just get this out in the open and detail the specific things that  could/would/should go better. It's an issue!

Certain contributors (*cough* @kangaroo) have been doing an excellent job pointing out various things that MS folks need to change for .NET Core to be a truly successful OSS project. We've been changing some of those things, although maybe not at the scale we should be. I'm sure other folks have ideas too of what could be going better.

Here's are the specific issues that I've heard. Please pile on, with as much detail as needed (including pointing to PRs and issues as examples). It's OK. Point to the specific examples. It's the only way to fix things. The center of the issue is the firewall between the internal MS process and the GitHub repo and community. We need to remove the firewall, not just open ports in it.

I've written several detailed points below. I think that they all boil down to this advice for MS engineers:

> Invest as little time as possible before creating an issue or pushing code to the community. Sharing is a much higher concern than quality.

- **DO** create issues as soon as possible, even before you fully understand the problem. Self-assign or make up-for-grabs.
- **DO** use public feature branches (personal or central) for work in progress.
- **DO** start work in the open as soon as possible, well before you are done, even before you quite know what you are doing. ```git rebase -i``` and ```git branch -D mybranch``` are your friends.
- **DO** use Issues. **DON'T** use email (as much as possible). Internal technical discussions don't help the community learn and don't enable them to participate. It's like keeping a new hire off of mail threads, for reasons.
- **DO** share snapshots of progress externally on an issue if there is an internal discussion going on. Take a picture of a whiteboard and share it!

**Comment by Petermarcu** [comment] 2015-04-20 21:24
@richlander Should we open a similar issue on other core repos?

**Comment by richlander** [comment] 2015-04-20 21:43
@Petermarcu That's a fine idea. There are some repo-specific challenges that would make more sense in that context. Also, people primarily contributing to the other repos are free to join this conversation, too.

What I said must be all perfect, since we haven't heard anything back yet. _Awesome!_

**Comment by Petermarcu** [comment] 2015-04-20 21:47
I just created another one in dotnet/corefx pointing back to this one. https://github.com/dotnet/corefx/issues/1445

**Comment by ellismg** [comment] 2015-04-21 01:06
FWIW, I don't think a general catchall issue is the right approach here.  I would much prefer that we take the guidance you outlined and add it to a contributing guide, ideally shared across all of the dotnet foundation projects.

For instances where we aren't doing the right thing, let's open specific issues about the problem and address them.  Trying to slam a chat-room into GitHub issues seems counter productive to me.

**Comment by richlander** [comment] 2015-04-21 02:27
@ellismg Good feedback. We have been discussing some of these issues in the CoreCLR room. The problem with a chat room is that it's not great for making a statement (with formatting!) for folks to see (for more than 5 mins until it scrolls out of view). So far, we don't seem to be drowning in the chat response here.

I agree that this is great to include in the contributing guide for all the projects. That said, the contributing guide has had more of a bias to advising external contributors. This is specifically oriented on changing Microsoft employee behavior. I'm happy to add this to the guide eventually, but was looking for something more "in your face" initially (since MS employees probably don't look at the guide much).

**Comment by khellang** [comment] 2015-04-21 12:02
> **DO** use Issues. **DON'T** use email (as much as possible).

This :100: times. There are still way too much going on in email threads.

See https://github.com/NuGet/NuGetGallery/issues/2400#issuecomment-91590177 as an example:

> it is faster to reach our emails than a github issue.

**Comment by kangaroo** [comment] 2015-04-21 13:17
If people think 'email is faster than github' then they really should tune their github notification settings to get emails :)

**Comment by n8ohu** [comment] 2015-04-21 18:11
@kangaroo: Agreed, since github provides the tools that can make this work, it's up to the folks in Redmond (or wherever) to learn to use them to the fullest extent possible.

**Comment by M-Zuber** [comment] 2015-04-22 04:06
Re the comments on github vs email - would a dedicated app (desktop or Web) for github issues change anything?

**Comment by richlander** [comment] 2015-04-22 04:29
@M-Zuber All depends what the app did! Certainly, I don't really appreciate the level of email that GitHub generates. I have a rule in outlook setup to alert me to "@richlander" references in email so that I can stay on top of questions or requests for me to do something.

I'd want to know the following (not necessarily in the same view) for a set of repos:

- Issues / PRs that @ me.
- Issues / PRs that are getting lot of activity in a short period of time.
- New issues / PRs as they hit the repo.

I quite like the gitter experience. It makes it super easy to subscribe to repos. It'd need to be like that.

If you want to discuss this further, let's do that separate from this issue (off topic).

**Comment by richlander** [comment] 2015-04-22 04:53
This, I believe, is a great case study to focus on: #770. Three main good points:

- Clear statement of problem (what looks like) before any investigation was done. "It's broken and we have no idea why!"
- Important artifacts are shared.
- Excellent use of markdown, making the issue pleasant to look at.

Any other thoughts? Is my analysis correct?

/cc @sergiy-k, @kangaroo

**Comment by sharwell** [comment] 2015-04-22 05:02
For external contributors, it's a good idea to attempt to reproduce the issue before requesting more information (alternatively worded "don't assume the user provided too little, until you *know* they provided too little). In the case of #770, this issue was created by someone who appears more closely related to the project, so I would make a suggestion that they add a brief note at the top indicating they are currently evaluating the issue. For example:

> This is my preliminary report of an issue which is currently being investigated.

Note that you can't assume tags are always appropriate, because a relatively small number of contributors have the ability to set tags for issues.

**Comment by kangaroo** [comment] 2015-04-22 09:38
@richlander I think #770 is definitely going in the right direction.  Its clear, concise and with the right amount of detail, at least for me.  What @sharwell said is right tho, is it 'up for grabs' or is @sergiy-k working on it.  I think 1 more piece of detail is needed:

' I'm working on this right now '

or

' I'm not working on this right now, so if someone wants to pick it up let me know '

Thoughts?

**Comment by janvorli** [comment] 2015-04-22 14:30
I have thought that the "up for grabs" tag is the marker to indicate whether the creator of the issue wants someone else to look into that. I understand the unassigned state as "I want to assign it to someone specific, but I have not figured out to whom yet". Say that we have a bug in the jitter and I am trying to figure out who on the jitter team should take a look.

**Comment by kangaroo** [comment] 2015-04-22 14:59
@janvorli If you can't figured out who to assign it to yet, isn't it inherently up-for-grabs for the community?  I mean you can always remove the label and assign it in the future if/when you figure out where you want to assign it.

Thoughts?

**Comment by stephentoub** [comment] 2015-04-22 15:26
Time will tell whether it's a good scheme or not, but the current approach employed by the corefx repo is outlined at https://github.com/dotnet/corefx/wiki/Issue-Guide.  In short, the goal is that every issue is assigned to someone from Microsoft, but that really just means that person is responsible for keeping an eye on the issue, making sure it's not lost, etc.  If that person is actually working on fixing it, then the "grabbed by assignee" label is used.  If someone from the community has grabbed it, the "grabbed by community" label is used and the comments on the issue highlight who's working on it.  Etc.

**Comment by kangaroo** [comment] 2015-04-22 16:26
@stephentoub I don't think it should be strictly required that all the projects follow the exact same rule-set.  While in an ideal world that would be nice, it may not turn out to be practical.

**Comment by stephentoub** [comment] 2015-04-22 16:30
@kangaroo, totally agree, was just sharing the approach as a reference point.

**Comment by kangaroo** [comment] 2015-04-22 16:30
:+1:

**Comment by ellismg** [comment] 2015-04-22 21:12
> That said, the contributing guide has had more of a bias to advising external contributors.

I think the goal here is that we blur the lines between Microsoft folks and External folks.  Perhaps we should stop thinking in terms of "internal" and "external" contributors, with respect to the contribution guide and just have that be the place we list best practices.  Then we shift the problem from: "This Microsoft person isn't behaving the right way." to "A contributor isn't following the guide."

> I'm happy to add this to the guide eventually, but was looking for something more "in your face" initially (since MS employees probably don't look at the guide much).

I don't mean to be glib, but I don't think an issue title "how to train your dragon!" is the right way to accomplish that goal.  My hunch is that looking at every issue is not something most folks do on a day to day basis.

I really dislike the idea of issues where we don't understand what success looks like.

I get this is a hard problem, but it's not clear to me this is the solution.  I would much prefer a model where we discuss specific changes we'd like to see in specific issues.  If the community as a whole thinks they are reasonable to adopt, we add them into the contributors guide.  If we are worried about a large number of Microsoft folks not seeing them (which honestly, I think is likely given that a fair portion of the team is focused on .NET Native), we can always send a friendly internal reminder to the team about major changes we've made the the contributors guide.

**Comment by richlander** [comment] 2015-04-22 21:36
I agree that blurring the lines between MS and community folks is a very good goal. I'm very happy to update the contributor guide along those lines.

This was an experiment. I was expecting a few more "DO"/"DON'T" suggestions than I've seen added. This is partially because I stole a bunch of the ones that various folks had already raised on specific issue/pr threads.

For me, success was simply an updated set of community-validated contributor guidance, largely based on observed Microsoft contributor behavior. I have slightly under a half-dozen new pieces of guidance. The count doesn't so much matter, but I (and you) have a better sense of what the community wants engagement to look like. 

I'm not looking for this thread to continue much longer. I'll leave it open for the rest of the week and then close it (provided that folks aren't still talking). I'll then pull together the guidance and update the contribution guide. We can then have future discussions on this general topic in whatever forum is appropriate.

**Comment by MattWhilden** [comment] 2015-04-23 08:32
I've been tagging things here rather haphazardly in my free minutes "while code compiles". If we can develop a reasonable set of meta information that helps everyone know what's up, I'm super happy to review and retag to that reality.

**Comment by kangaroo** [comment] 2015-04-23 09:52
@ellismg Touches on a point I've raised a few times.  Please, please please do not have 'internal/external' contributor blurred lines.  If the bar for commit is code review, 2 developer sign off, etc.  Do that for every PR.  This is not happening today fwiw.

**Comment by richlander** [comment] 2015-04-23 20:32
@kangaroo I'm not sure that's against was @ellismg said. I interpreted what @ellismg said as being very aligned with what you are saying. I all depends what one means by "blurred". I take that as one unified set of guidance that everyone follows, not two distinct sets.

**Comment by ellismg** [comment] 2015-04-23 20:44
> If the bar for commit is code review, 2 developer sign off, etc. Do that for every PR. This is not happening today fwiw.

In CoreFx (and I think this has bleed into the other repositories) we were given guidance that two Microsoft folks needed to sign off on every change.  I think we've been good about following that, with the following caveats:

1. We have always taken the guidance to mean that for changes authored by Microsoft folks, the author counts as one code reviewer.  So changes authored by Microsoft folks usually only have one other Microsoft person LGTM them.
2. For changes which are authored internally and mirrored over by the Git -> TFS mirror, we normally do a quick glance to make sure the mirroring process looks reasonable and then merge them.  The rationale is they already went through CR internally.  Folks are more than welcome to raise issues but we want to merge the code quickly in most cases because we want to keep the trees in sync, so we err towards merge and address feedback later.
3. I've seen a handful cases where trivial changes (updates to .md files, changing around `.gitmirror` files, etc.) are merged without review.

If there are other cases where we're falling down here, I'd love to know about it.  It may just be a case where we haven't written down externally the full policy.  I understand the Microsoft author counts as a CR thing is a little weird.  I suspect that if/when we add community members to the core team (e.g. give them commit permissions) we would only require one other member from the core team to sign off on changes as well.

**Comment by kangaroo** [comment] 2015-04-23 21:58
@richlander @ellismg 

> We have always taken the guidance to mean that for changes authored by Microsoft folks, the author counts as one code reviewer. So changes authored by Microsoft folks usually only have one other Microsoft person LGTM them.

This is a perfect example of what I meant.  You cannot inherently self code-review.  If the bar to commit is 2 reviews, make it 2 reviews across the board.

> For changes which are authored internally and mirrored over by the Git -> TFS mirror, we normally do a quick glance to make sure the mirroring process looks reasonable and then merge them. The rationale is they already went through CR internally. Folks are more than welcome to raise issues but we want to merge the code quickly in most cases because we want to keep the trees in sync, so we err towards merge and address feedback later.

This should be a long term goal to go away imo.

> I've seen a handful cases where trivial changes (updates to .md files, changing around .gitmirror files, etc.) are merged without review.

Rules are made to be broken?  Please define trivial so that its clear to everyone.

Again, its not about falling down, its about clear and consistent guidelines and contribution bars.

Make sense?

**Comment by ellismg** [comment] 2015-04-23 22:11
> This should be a long term goal to go away imo.

We are working towards that.  Depending on the project, we'll what "success" looks like will ultimately be different.  Roslyn doesn't do any development out of TFS anymore, AFAIK.  CoreFX still has a bunch of code we are working to open source and changes which impact both the closed and open source components are often done out of TFS so we can validate everything atomically.  Or there are changes from other branches and it's easier to integrate them via TFS.  Long term, we want to get everything there Open Source and I expect the work in TFS will drop to near zero.  CoreCLR will probably continue to have cases where we have work that cuts across the open source CoreCLR components and the closed source desktop components, so you'll always see some co-development.  We are trying to figure out how to get more teams to work out of git (e.g. right now a majority of the JIT folks have their own branch they work out of and they will probably continue to do so for a few more months before they have bandwidth to start moving over to git, which is a function of the desktop release cycle) but it's going to take some time.

> Again, its not about falling down, its about clear and consistent guidelines and contribution bars.

Agree.  There is some disconnect between the guidance we have internally (e.g. the code review bar) and what we've published externally.  It's probably something Rich and Immo can do better at codifying.  My point is you shouldn't assume folks are being malicious, folks are still learning and operating using the internal guidance we've been given.

**Comment by kangaroo** [comment] 2015-04-24 09:48
> Agree. There is some disconnect between the guidance we have internally (e.g. the code review bar) and what we've published externally. It's probably something Rich and Immo can do better at codifying. My point is you shouldn't assume folks are being malicious, folks are still learning and operating using the internal guidance we've been given.

No malice assumed here, just stating that I think some effort invested in consistency is well placed.

**Comment by OtherCrashOverride** [comment] 2015-04-24 16:48
The communication issue I feel needs more attention is status updates.  When your boss asks "How is the project going?" what do you tell him/her?

Where is the roadmap? Where are the milestones? How long till release? The CI says the code compiles, but does it actually work? GitHub "issues" is a very poor way to communicate status.  There probably needs to be a real bug tracker and project WWW site. A lot of the issues in "Issues" are not actual issues that preclude a release.

What is everybody working on? What needs more attention before an actual release? If I don't know, I cant help.

Once there is an actual 1.0 release, it gets easier to be a contributor: I fix/add the things I encounter.  Until then, my only gauge of where this project is at comes from collating information from chat, commits, issues, and random blogs on the internet.

Not being in the club and knowing the secret handshake should not preclude someone from knowing whether there are 5 years or 5 months till a 1.0 release.  Right now I am waiting for the BUILD event to find out what secrets and surprises have been going on behind the curtain.

**Comment by mj1856** [comment] 2015-05-01 23:55
> I agree that blurring the lines between MS and community folks is a very good goal. I'm very happy to update the contributor guide along those lines.

I think this goal is essential.  Just to blur the lines a bit more, please consider that not all Microsoft employees that are contributors (or would like to be contributors) are working in the .NET team.  Even though they may have access to internal resources, they may not necessarily have the same level of knowledge that a core team member would have.

If there's a .NET developer working over in Office, or Dynamics, or Xbox, etc., that wants to contribute, that should be cool with everyone.

Blurring even more, their contributions might be quasi-internal, done on work time and important to their role or project at MS, or they might just be a hobbyist chipping in on their off-time, like any other external community member.

**Comment by MattWhilden** [comment] 2015-05-07 17:38
Here's a rough summary of this thread:
- Potentially having consistency between the CoreFX/CoreCLR repo for tagging is useful
- Having a page that describes with the tags mean is useful
- Making sure that external contributors and MS folks are held to the same standard is treated as an very valuable litmus test 
- Everyone can feel more engaged if our planning and messaging were clearer

Thanks everyone for the feedback and please feel free to open issues in the future if you think things can be improved. We'll come up with some schemes to address the above and post issues for further discussion of them individually.

**Closed by MattWhilden** 2015-05-07 17:38 UTC

**Comment by OtherCrashOverride** [comment] 2015-05-09 18:41
There have been lots of misleading news posts from 3rd parties regarding the status of coreclr.  An example is the news of the FreeBSD port.  Its being represented as if the project is complete for FreeBSD and it can run everything today.

BUILD did a very good job of presenting the reality of the current status in a couple of slides.  It would be nice if this information were present in the README.  It also underscores the point that nobody "on the outside" knows where this project is at or how long it will take to get where its going.  It was mentioned somewhere that there is a schedule that Microsoft is working towards with regards to release.  Care to share that information?

**Comment by MattWhilden** [comment] 2015-05-09 20:58
Thanks @OtherCrashOverride we've noticed the same confusion and will hopefully have a clearer picture going forward. I consider that information included as part of the fourth bullet above but probably should have been more explicit.

Again, thanks for the feedback.
