### ISSUE TITLE
[armel][2.1.1] Incorrect stepping in debugger

### ISSUE THREAD

**Issue by alpencolt** [dotnet/coreclr#19255] opened 2018-08-02 18:57 UTC
After setting break point we try to make step but CoreCLR crash with abort.
If we attach with gdb we'll see several `SIGTRAP` it's ok for ARM and CoreCLR handle them well but one of this SIGTRAP aren't handled by runtime which cause abort in `sigtrap_handler()`.

We've checked latest master and it works. There are several PRs which fix stepping after 2.1 release:
https://github.com/dotnet/coreclr/pull/17617
https://github.com/dotnet/coreclr/pull/17879
https://github.com/dotnet/coreclr/pull/17990
https://github.com/dotnet/coreclr/pull/18129
https://github.com/dotnet/coreclr/pull/18247
They help but not at all - application crashed but little bit later with the same abort.
Are there any others fixes which we've missed?

cc @jkotas @BruceForstall @kbaladurin @BredPet

**Comment by BruceForstall** [comment] 2018-08-02 19:38
also cc @dotnet/arm32-contrib @noahfalk

**Comment by noahfalk** [comment] 2018-08-03 18:29
@chsienki - Any other fixes @alpencolt missed from your recent ARM bug fixes?
@mikem8361 -You are probably the right person to take over

@alpencolt - Do you have repro we could look at? 
Thanks!

**Comment by alpencolt** [comment] 2018-08-03 18:39
We've solved issue. It's enough PR https://github.com/dotnet/coreclr/pull/18129 to fix original crash.
Our next crashes were caused by enabled gdbjit and attached at the same moment gdb%)

Is there chance to port  https://github.com/dotnet/coreclr/pull/18129 commits to 2.1 branch?
cc @danmosemsft @karelz

**Comment by danmosemsft** [comment] 2018-08-03 18:56
@RussKeldorph would own driving any fix into servicing. He may be on vacation at the moment in which case @AaronRobinsonMSFT could probably help.

**Comment by BruceForstall** [comment] 2018-08-16 23:44
@RussKeldorph @chsienki ping -- @alpencolt is requesting #18129 to get ported to 2.1. Is that possible?

**Comment by RussKeldorph** [comment] 2018-08-16 23:48
@dotnet/dotnet-diag would need to make the call.  Specifically @tommcdon or his delegate.

**Comment by tommcdon** [comment] 2018-08-17 00:55
Assigned to @hoyosjs to investigate porting to 2.2

**Comment by danmosemsft** [comment] 2018-08-31 16:57
Removing servicing label as that's for PR's. @noahfalk linked PR got merged into 2.1 can this be closed?

**Comment by noahfalk** [comment] 2018-08-31 20:35
@alpencolt - let us know if this issue was intended to track some work that hasn't been done yet and we can reopen

**Closed by noahfalk** 2018-08-31 20:35 UTC
Labels: area-Diagnostics
