### ISSUE TITLE
Test failure on Linux: JIT/Methodical/delegate/_simpleoddpower_il_r/_simpleoddpower_il_r.sh

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2538] opened 2016-01-05 22:06 UTC
FAILED   - JIT/Methodical/delegate/_simpleoddpower_il_r/_simpleoddpower_il_r.sh
               BEGIN EXECUTION
               /home/lubo/coreclr-tests/Windows_NT.x64.Debug/Tests/coreoverlay/corerun _simpleoddpower_il_r.exe
               
               Assert failure(PID 32398 [0x00007e8e], Thread: 32398 [0x7e8e]): Assertion failed 'GetType() == TI_METHOD' in 'OddPower:Main():int' (IL size 666)
               
                   File: /home/lubo/SVS/src/jit/_typeinfo.h Line: 545
                   Image: /home/lubo/coreclr-tests/Windows_NT.x64.Debug/Tests/coreoverlay/corerun
               
               **** MessageBox invoked, title 'corerun - Assert Failure (PID 32398, Thread 32398/0x7e8e)' ****
                 Assertion failed 'GetType() == TI_METHOD' in 'OddPower:Main():int' (IL size 666)
               
               
               /home/lubo/SVS/src/jit/_typeinfo.h, Line: 545
               
               Abort - Kill program
               Retry - Debug
               Ignore - Keep running
               
               
               Image:
               /home/lubo/coreclr-tests/Windows_NT.x64.Debug/Tests/coreoverlay/corerun
               
               ********
               
               ./_simpleoddpower_il_r.sh: line 55: 32398 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" _simpleoddpower_il_r.exe $CLRTestExecutionArguments $Host_Args
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED

**Comment by sivarv** [comment] 2016-01-06 01:11
Closing this as it is a duplicate of issue #2407

**Closed by sivarv** 2016-01-06 01:11 UTC
Labels: bug, CodeGen, Linux
