### ISSUE TITLE
GC/Scenarios/DoublinkList/doublinkgen failed on Linux

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#6575] opened 2016-08-02 19:11 UTC
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/3747/

11:24:48 FAILED   - GC/Scenarios/DoublinkList/doublinkgen/doublinkgen.sh
11:24:48                BEGIN EXECUTION
11:24:48                /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun doublinkgen.exe
11:24:48                Test should return with ExitCode 100 ...
11:24:48                999 DLinkNodes finalized
11:24:48                Test Failed
11:24:48                Expected: 100
11:24:48                Actual: 1
11:24:48                END EXECUTION - FAILED

**Comment by adityamandaleeka** [comment] 2016-08-02 19:12
Looks like I beat you to this by a minute :smile:

Dupe of #6574

**Closed by adityamandaleeka** 2016-08-02 19:12 UTC
