### ISSUE TITLE
Intermittent failures in Fma test

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#18467] opened 2018-06-14 16:46 UTC
I have seen a couple of failures in this test that I can't repro, even with various combinations of the `COMPlus_Enable` flags for the various ISAs. Not sure what's going on, but there's no way that changing an ARM-only #define should cause this to fail. See https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_release_windows_nt_innerloop_prtest/4371/ and also https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_release_windows_nt_innerloop_prtest/4376/

The impacted test is Windows_NT.x86.Release\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\Fma_ro.cmd

It seems to pass on retry.

**Comment by CarolEidt** [comment] 2018-06-14 16:46
cc @tannergooding @fiigii 

It might be useful, when a HW intrinsic test fails, for the test to print the various values of `IsSupported` in case that might help with a repro.

**Comment by tannergooding** [comment] 2018-06-14 17:06
👍. We should probably also be printing the seed.

The issue is probably some combination of inputs is failing the expectedResult comparison test (which is basically `Math.Round(a * b + c, digits) == Math.Round(result, digits)`.

The "proper" fix is to implement a software FMA function that does `(a * b)` to "infinite" precision, adds `c`, and then finally rounds (where-as the normal behavior is to do `(a * b)` to "infinite" precision, round, add `c` at "infinite precision", and then round again.

**Comment by tannergooding** [comment] 2018-06-14 17:06
A "temporary" fix would be to reduce the number of digits compared.

**Comment by mikedn** [comment] 2018-06-14 17:11
I thought it was agreed that we don't test instruction behavior, just that the needed instruction is generated. As such, the use of random numbers is dubious.

**Comment by CarolEidt** [comment] 2018-06-14 17:15
As suggested in https://github.com/dotnet/coreclr/issues/10585, we should be using a fixed seed for random number generation. We should also ensure that we're not comparing beyond the precision preservation guaranteed by FMA.

**Comment by tannergooding** [comment] 2018-06-14 17:20
> As suggested in #10585, we should be using a fixed seed for random number generation.

I don't believe the issue is that a fixed seed is being used. The issue is that there are many tests which do not tell you the seed that was used, which causes an inability to reproduce. If the test prints the seed, you can always reproduce and there is no issue (and you still get the benefits from using random numbers).

> We should also ensure that we're not comparing beyond the precision preservation guaranteed by FMA.

The issue is not that we are comparing beyond the precision preservation guarantees (which would mean that `FMA.PrecisionGuarantee is less than normal`). The issue is that the precision preservation guarantees are greater than the individual operations.

**Comment by tannergooding** [comment] 2018-06-14 17:27
> As such, the use of random numbers is dubious.

@Mikedn, there were at least a couple tests where the use of random numbers caught issues with the encoding after the fact.

That being said, I think a better situation would be if we just had tests that:
* Validated that a managed `Isa.Method` call produced the correct `GenTreeHWIntrinsic` node type
* Validated that `GenTreeHWIntrinsic` nodes generated "valid asm" 

Which would actually allow us to test instruction generation without any reliance on instruction behavior.

**Comment by mikedn** [comment] 2018-06-14 17:41
> there were at least a couple tests where the use of random numbers caught issues with the encoding after the fact.

Examples? Was the use of random numbers really a benefit or was it actually the reason why it took a while to catch the bug?

> That being said, I think a better situation would be if we just had tests that:

Except that it's not trivial to do that and there's no guarantee that the tests themselves are correct. For example, some intrinsic failures where caused by incorrect data in the intrinsic table. If that table cannot be populated correctly then there's also a good chance that tests can also be incorrect.

From this point of view the current tests might actually be better as they actually run the code and compare it with results obtained by other means. The problem is picking some reasonable inputs...

**Comment by tannergooding** [comment] 2018-06-14 17:52
> Was the use of random numbers really a benefit or was it actually the reason why it took a while to catch the bug?

Random numbers are beneficial because they are random. Any use can pick some arbitrary values that cover known edge cases or special inputs, but there is always the chance they miss something.

Random gives "arbitrary" inputs, so it (hopefully) covers things that the dev didn't think about.

> Examples?

Will try to dig up the issues that were fixed

> Except that it's not trivial to do that and there's no guarantee that the tests themselves are correct.

But it might be better if we had the option (see below).

> From this point of view the current tests might actually be better as they actually run the code and compare it with results obtained by other means.

Right, but at the same time, you are relaying on "currently hit" code paths to be correct. The JIT is large and complex, there is no guarantee that the managed code I write will definitely cause `emitIns_SIMD_R_R_AM` to be hit (for example). Having native unit tests that will definitely execute that code path would be beneficial as it ensures that "if" the user writes code that causes `R_R_AM` to be hit (rather than `R_R_A`, `R_R_S`, `R_R_C`, or `R_R_R`) that it will still generate the correct code.

From the high level, we only really care that the various `Sse.Add` generates `addps op1, op2`

From the implementation level, we currently expect that `Sse.Add` will generate a `GenTreeHWIntrinsic` node with type `NI_SSE_Add` and with two operands of the appropriate type and that it ultimately causes `addps` to be generated.

**Comment by mikedn** [comment] 2018-06-14 18:09
> Random numbers are beneficial because they are random.

Well, if you say so...

> The JIT is large and complex, there is no guarantee that the managed code I write will definitely cause emitIns_SIMD_R_R_AM to be hit (for example). 

Except that most of the JIT doesn't care about intrinsics so in general there should be no problem to generate IL code that hits the right paths. And if the JIT did care about intrinsics (e.g. optimize them) then tests would not help too much because there would far too many cases to consider.

**Comment by echesakovMSFT** [comment] 2018-07-05 18:53
Since I got this issue assigned to me I have been thinking about taking this approach:  
1. Remove all `var random = new Random()` in all the templates in tests\src\JIT\HardwareIntrinsics\X86
2. Replace all `random.NextX()` with one of the existing `TestLibrary.Generator.GetX()` (which would use a fixed seed in Innerloop tests) in GenerateTests.csx
3. Regenerate all the tests

@mikedn @tannergooding @dotnet/jit-contrib What is your thoughts?

**Comment by CarolEidt** [comment] 2018-07-06 23:02
@echesakovMSFT - that sounds like the right approach. I would love to see this fixed :-)

**Comment by fiigii** [comment] 2018-07-07 00:30
@echesakovMSFT I remember that some test files were generated from the template and manually modified later. Probably, we need to create more templates to cover all the test files.

**Comment by tannergooding** [comment] 2018-07-13 15:33
This should be resolved now that #18838 is merged.

**Closed by tannergooding** 2018-07-13 15:33 UTC
Labels: arch-x86, area-CodeGen, bug
