### ISSUE TITLE
CoreCLR failed to build due to error MSB4062 with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [dotnet/coreclr#26745] opened 2019-09-17 08:16 UTC
We tried to build CoreCLR and it failed to build due to error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly with MSVC on windows. It can be reproduced on latest d31557c revision and it can build pass on 456afea revision.  It should be a CoreCLR source issue. Could you look at this issue? Thanks a lot.

Repro steps:
1.git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2.Open a clean x86 prompt and browse to D:\CoreCLR\src
3.build x86 release -- /clp:ShowCommandLine

[log_x86_build.log](https://github.com/dotnet/coreclr/files/3620026/log_x86_build.log)

Error info:
D:\CoreCLR\src\.packages\microsoft.net.compilers.toolset\3.2.0-beta2-19272-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly 
D:\CoreCLR\src\.packages\microsoft.net.compilers.toolset\3.2.0-beta2-19272-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error MSB4062: The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly

**Comment by jkotas** [comment] 2019-09-17 17:14
This error is caused by multiple conflicting versions of Roslyn being used during the build. One from Arcade and a different one from BuildTools.

This should get fixed by https://github.com/dotnet/coreclr/pull/26108 . cc @sbomer 

@spacelg In the meantime, you can workaround it by skipping the tests during the build: `build x86 release skiptests -- /clp:ShowCommandLine`

**Comment by jkotas** [comment] 2019-09-17 22:23
I have verified that this is fixed now that #26108 is merged.

**Closed by jkotas** 2019-09-17 22:23 UTC
Labels: area-Build
