### ISSUE TITLE
JIT does not handle invalid file descriptors during startup

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#6460] opened 2016-07-25 15:45 UTC
In Jitstartup, JIT creates a file descriptor for stdout and unconditionally passes it to setmode, without checking for failures. This happens at https://github.com/dotnet/coreclr/blob/ee680783778ed0abb186ae41a8c861d5cdcadccd/src/jit/ee_il_dll.cpp#L76.

Failure to check for invalid descriptors can result in setmode triggering failfast.

CC @russellhadley @RussKeldorph @pgavlin

**Comment by mikedn** [comment] 2016-07-25 15:49
Duplicate of #6356 ?

**Comment by gkhanna79** [comment] 2016-07-25 15:50
Yes @mikedn - duplicate indeed.

**Comment by russellhadley** [comment] 2016-07-25 17:30
I have a proposed fix I'm beginning testing on.

**Comment by russellhadley** [comment] 2016-07-25 21:37
My fix resolves the issue the powershell team is having.  PR coming soon.

**Comment by russellhadley** [comment] 2016-07-26 19:51
Closed with #6464

**Closed by russellhadley** 2016-07-26 19:51 UTC
Labels: blocking-partner, blocking-release, bug, CodeGen
