### ISSUE TITLE
Improve codegen for upper vector saving.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#20669] opened 2018-10-29 16:50 UTC
When `FEATURE_PARTIAL_SIMD_CALLEE_SAVE` is enabled we need to save the upper half of each vector register before each call. For that we have `RefTypeUpperVectorSaveDef` ref type and lsra always allocates a callee-saved register for them (`xmm4, xmm5` on x86). But if there are many vector registers that need to be saved then we allocate `xmm4` and spill it many times and end up with such code:
```
IN001c: 00010B vextractf128 ymm4, ymm7 1
IN001d: 000111 vmovupd  xmmword ptr [TEMP_10 rsp+180H], xmm4 
IN001e: 00011B vextractf128 ymm4, ymm8, 1
IN001f: 000121 vmovupd  xmmword ptr [TEMP_09 rsp+170H], xmm4
IN0020: 00012B vextractf128 ymm4, ymm9, 1
IN0021: 000131 vmovupd  xmmword ptr [TEMP_08 rsp+160H], xmm4
IN0022: 00013B vextractf128 ymm4, ymm10, 1
IN0023: 000141 vmovupd  xmmword ptr [TEMP_07 rsp+150H], xmm4
IN0024: 00014B call     DevDiv_714266:CallWithoutUsesAndDefs()
IN0025: 000150 vmovupd  xmm4, xmmword ptr [TEMP_07 rsp+150H]
IN0026: 00015A vinsertf128 ymm10, ymm4, 1
IN0027: 000160 vmovupd  xmm4, xmmword ptr [TEMP_08 rsp+160H]
IN0028: 00016A vinsertf128 ymm9, ymm4, 1
IN0029: 000170 vmovupd  xmm4, xmmword ptr [TEMP_09 rsp+170H]
IN002a: 00017A vinsertf128 ymm8, ymm4, 1
IN002b: 000180 vmovupd  xmm4, xmmword ptr [TEMP_10 rsp+180H]
IN002c: 00018A vinsertf128 ymm7, ymm4, 1
```
instead we can directly spill and reload using the stack:
```
IN001c: 00010B vextractf128 xmmword ptr [TEMP_10 rsp+180H], ymm7 1
IN001e: 00011B vextractf128 xmmword ptr [TEMP_09 rsp+170H], ymm8, 1
IN0020: 00012B vextractf128 xmmword ptr [TEMP_08 rsp+160H], ymm9, 1
IN0022: 00013B vextractf128 xmmword ptr [TEMP_07 rsp+150H], ymm10, 1
IN0024: 00014B call     DevDiv_714266:CallWithoutUsesAndDefs()
IN0026: 00015A vinsertf128 ymm10, ymm10, xmmword ptr [TEMP_07 rsp+150H], 1
IN0028: 00016A vinsertf128 ymm9, ymm9,  xmmword ptr [TEMP_08 rsp+160H], 1
IN002a: 00017A vinsertf128 ymm8, ymm8, xmmword ptr [TEMP_09 rsp+170H], 1
IN002c: 00018A vinsertf128 ymm7, ymm7, xmmword ptr [TEMP_10 rsp+180H], 1
```

link #20623

**Comment by voinokin** [comment] 2018-10-29 19:22
Link #18144

**Comment by CarolEidt** [comment] 2018-10-29 20:26
I think this is just a duplicate of #18144 - I don't know why we need this as well.

**Comment by sandreenko** [comment] 2018-10-29 20:38
I have missed the previous issue.
However, there are several issues there so we will have to split it sooner or later.

**Comment by CarolEidt** [comment] 2018-10-29 20:41
@sandreenko - Please just add to #18144, and if, at the time we address that, there are additional issues, they can be opened at that time.

**Closed** 2018-10-29 20:44 UTC
Labels: area-CodeGen, optimization
