### ISSUE TITLE
Undo workaround that moved PAL to separate module

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#728] opened 2015-04-16 23:01 UTC
Change #704 is supposed to be a short term workaround to help debugger. This issue tracks undoing it.

**Comment by jkotas** [comment] 2015-04-16 23:02
#724 should be rolled back as part of this change

**Comment by jkotas** [comment] 2015-04-16 23:03
https://github.com/dotnet/corefx/pull/1413 should be rolled back as part of this change

**Comment by jkotas** [comment] 2015-04-16 23:04
#719 should be rolled back as part of this change

**Comment by jkotas** [comment] 2015-04-17 01:18
https://github.com/aspnet/dnx/issues/1663 should be rolled back as part of this change

**Comment by kangaroo** [comment] 2015-04-17 02:34
What is the exact problem (and proposed solution) with the debugger module(s) right now?  Basically, why are we temporarily taking on this technical debt?

**Comment by jkotas** [comment] 2015-04-17 02:56
@mikem8361 Could you please share the plan you have for this?

I have not realized that the workaround will spread to this many places...

**Comment by mikem8361** [comment] 2015-04-17 03:09
@jkotas, @kangaroo - Here are a few emails (most recent first) that address this issue:

1.	Short term (for initially getting debugging working end-to-end and for Build)
a.	Change the debugger module builds to share one PAL and share the PAL in the CoreClr module.  I’ll make the dbi/dac/sos/dbgshim changes and Prem will make the VS changes.
b.	The hardware exception interaction between CoreClr and the DAC will need to be addressed. PAL_SetHardwareExceptionHandler only allows one handler (global) and we are sharing one PAL now.
c.	The VS team has some additional APIs that needed to be added to the CoreClr PAL.  

2.	Long term
a.	Separate statically linked PALs in VS, dbi/dac/sos, dbgshim and coreclr.
b.	PAL thread data for “foreign” threads is created on the fly.  PAL_Entry can still be called and any error handled there, but if it hasn’t the CPalThread object is allocated in InternalGetCurrentThread. A C++ exception is thrown if the creation fails (out of memory is the only failure).
c.	PAL module handles will not be passed across PAL instance boundaries. 
d.	Suspend/resume signals (SIGUSR1/2) need only to be hooked by the CoreClr PAL.  The other PAL instances will only support creating a suspended thread with CreateThread. This can be done without signals.
e.	Hardware signals can be chained at the Linux level like vectored exception handling in Windows.  The “sigaction” API returns the previous handler. There still the interaction between the DAC and the CoreClr to figure out. Cannot depend on the CoreClr/DAC PAL initialization order. 
f.	The SIGINT (Ctrl-C) is only hooked by the CoreClr PAL.
g.	The CoreClr and the debugger modules will not be unloaded (it hasn’t been supported in the past by Windows) so chaining signal handlers won’t have that problem.

The goal long term is remove any dependencies between the PALs so there doesn’t have to a master or a global list of modules containing PAL instances.  Hardware signals is the only tricky interaction because it difficult to determine if need to throw an exception or chain to the previous handler.  

------------------------------------------------------------------------------------------------------

1.	Can we get rid of multiple PAL instances? Things would be so much simpler if we could, but because of future versioning I think we will be stuck with separate (statically linked) PALs in following modules (version bubbles as Noah calls them): VS, dbgshim, dbi/dac/sos (these 3 modules share the same PAL instance) and coreclr. This version will also apply to multiple coreclr instances running in the same process side-by-side. 
2.	Finding/tracking all the modules containing a PAL.  Because the global resources listed in the previous emails (below) need to be “managed” across multiple PAL instances, we need to find or track all the PALs in the process. Both loading and unloading of modules containing PALs needs to be considered.
a.	Via LoadLibrary/FreeLibrary. In the current scenarios, one PAL instance loads the other modules containing a PAL so we could create a handshake that registers/tracks all the modules containing a PAL.  For example, the VS native code starts and loads dbgshim which loads mscordbi which loads mscordac all via their PALs LoadLibrary.  Since VS will also run managed code, it will probably use LoadLibrary to load coreclr and the hosting APIs to initialize it.  The downside is if modules containing a PAL are somehow loaded independently and/or directly (via dlopen, etc.) without using our PAL.
b.	Enumerate all the modules during a PAL’s initialization to find all the other PALs (via /proc/<process id>/maps pseudo-file on Linux. Not sure about OSx). Each time a PAL is loaded it looks at all the modules already loaded for PAL’s and registers itself with the other PALs. The “handshake” between the PALs needs to determine who is the “master” PAL that actually hooks the signals, etc.  This handshake needs some more thought especially considering the current master could be unloaded.
c.	Create a separate small (hopefully as platform independent as possible) common PAL module that tracks and dispatches between all the PALs. This common PAL would allow all the PAL modules to be tracked easily even if unloaded. This common PAL module needs to be as thin as possible so it rarely changes across versions of the other modules and maintains compatibility with previous versions. If we put too much in the common PAL (like all of the PAL thread and/or the signal management), we are back to the same versioning problems of having the whole PAL in a separate module. To keep this option workable, it should only dispatch (I’m hand waving  a lot of details) between PAL modules registered but even then maintaining a module list (at least the way our PAL currently does) pulls in a lot of code to implement the cross platform critical sections, etc.
3.	H/W exceptions and suspend/resume (SIGUSR1/2) signals need be hooked by only one PAL and “sent” to all the other PALs. The debugger DLLs do not need the full suspend/resume logic just enough to resume a newly created suspend thread. Only coreclr needs to suspend/resume threads arbitrarily. So we could also simplify the CreateThread suspended logic not to use signals for the debugger DLLs. 
4.	Having each PAL instance create their own CPalThread object could have some problems.  It provides unsafe suspend/resume region count (used around “internal” critical sections), synchronization info (including a thread state),  APC info, etc.  I think as long as the debugger module PALs don’t use these thread features, the coreclr PAL will be fine.  
5.	For the debugger modules (VS, dbgshim, dbi/dac/sos), a subset of the full PAL could be statically linked to enforce things like no thread suspend/resume, APCs, etc. that only coreclr needs.  The subset could be some of the threading APIs, critical sections, some module APIs (LoadLibrary/FreeLibrary), etc. This idea is completely separate from the common PAL idea. Having only a subset of the PAL in the debugger modules will reduces the interactions with the full PAL in coreclr. But adding more ifdefs is a downside.

--------------------------------------------------------------------------------------------------------

I’ve been thinking about the various problems with our native debugger modules (DBI, DAC and SOS), the dbgshim and VS having their own statically linked copy of the PAL.  The coreclr PAL is also part of this because VS and mdbg have/are managed code.  

The following global resources need to be managed across PALs:

1) module handles – this currently isn’t a problem right now because the APIs expose across the current boundaries don’t pass around module handles.
2) threads – threads that are created by one PAL that call into another need the CPalThread data allocated.  
3) hardware signals – the DAC needs to hook the hardware signals and throw a C++ except because it uses try/catch to validate data/addresses read from the target coreclr process.
4) the SIGUSR1/2 signals – thread resume/suspend uses these signals even when creating a thread (the build flag USE_SIGNALS_FOR_THREAD_SUSPENSION is defined). 

Some questions:

1) It looks like hooking signals is per process, but it looks like signals can be masked per thread. Is this accurate?
2) MAC ports look like they are per thread?
3) If we do create the thread data on demand (my current plan), what do we do with out-of-memory failures? Assert/abandon?
4) Any other global resources I’ve missed?
5) Can we build the PALs with different flags like turning off USE_SIGNALS_FOR_THREAD_SUSPENSION for the debugger/VS modules and on for coreclr. This would depend on why we use signals for thread suspension; I don’t understand it yet.  It looks like an semaphore is involved but maybe on some platforms signals are necessary to wake up a thread?

**Comment by kangaroo** [comment] 2015-04-17 03:23
Is there a particular reason we need multiple PALs?  If everything is loaded in the same process space, can't we link the PAL into coreclr and export the required functions from there?

I'll take a crack at some of your questions:

1. Signals are per process.  They can be delivered process wide, or thread specific -- but they are registered on a process basis.
2. mach_port_t's are a bit weird, but the fundamental point is they can be registered per thread or task (process).

Q: Is there a specific reason your design requires per-thread signal/exc registration?

**Comment by noahfalk** [comment] 2015-04-17 03:33
@mikem8361 
I was chatting with Gregg today and there were signs that managers may be backing away from the demo goal. Perhaps you should chat with him to see if the short term workaround is even necessary any more? 

@kangaroo 
The reason for multiple PALs is for versioning independence. The DAC dll which is loaded is tightly bound to the CoreCLR version in the debuggee, and may be completely different from the version of CoreCLR loaded in the debugger process (if coreclr is even loaded in the debugger process at all). Any API (such as PAL) that we expose across that boundary needs to be careful monitored for back-compatibility similar to BCL APIs. I'd prefer to keep PAL free of those kinds of constraints wherever possible.

**Comment by kangaroo** [comment] 2015-04-17 04:13
@noahfalk If there is process isolation between the debugee and debugger I'm not sure I understand the thread specific or signal registration issues, since those are inherently process specific anyways?

**Comment by noahfalk** [comment] 2015-04-17 05:47
@kangaroo 
The signal registration issue comes up because both DAC and CoreCLR expect to be able to handle access violations from within their own code. You can ignore that DAC is used for debugging, and treat it merely as some other module that sometimes exists in the same process as coreclr.  On Linux the only way I am aware of for threads to handle their own access violations is by registering a global signal handler. If DAC registers a signal handler and CoreCLR also registers one then either they need a strategy to cooperate or one of the signal handlers isn't going to be called. 

If you are wondering why does DAC need to handle access violation at all, that answer is a little complex but I'll try to give the short version.  In CLR there are numerous data types that have pointers and offsets in them and the runtime expects the data to well-formed. For instance we expect various pointers won't be NULL, or offsets won't point outside array bounds. If that isn't true then the process will probably have an access violation while manipulating that data and terminate with a fatal error. DAC recompiles this exact same code that is used for CLR, modified with smart pointers and various macros. At debugging time it copies memory from the debuggee process (or dump) into the debugger process and then executes that code which doesn't check for bad pointers or array bounds. If the debuggee memory space was corrupted, then the debugger process is likely to trigger the same access violations as the debuggee. However being a debugger we can't reasonably terminate the process everytime the debuggee has memory corruption. Instead we assume that any access violation triggered by the DAC code represents bad debuggee state, and we translate the access violation into a failing HRESULT for the debugging API call that is in progress. Its fast and loose with handling access violation, but in practice it works and it would be an expensive engineering task to shift to a different approach.

HTH,
  -Noah

**Comment by kangaroo** [comment] 2015-04-17 05:52
@noahfalk So, if thats really the big problem it just seems like we need an infrastructure to have 'vectored' signal handlers when a debugger is attached so that DAC gets a 'first chance' at exceptions?

This seems like a much simpler problem to solve than 500 PALs in 200 modules with different API/ABIs.

**Comment by noahfalk** [comment] 2015-04-17 06:11
@kangaroo 
We need some arrangement that gives DAC a chance to get exceptions, but I'm not sure how that eliminates the need for dac, dbi, dbgshim, VS... to have access to PAL functionality as well. It sounds like you have an alternate solution in mind but I'm not sure I understand what it is?

**Comment by kangaroo** [comment] 2015-04-17 06:39
@noahfalk I don't think I have a clear understanding yet of all the requirements of dac, obi, dbgshim, VS, etc.  You're listing a lot of modules that clearly have interdependencies, and I don't fully grok them.

My point so far from what I do grok is -- if the problem is a PAL boundary in process between DAC and PAL, we can design a clean API to let DAC opt-in and opt-out (on load/unload with so constructors maybe? not sure yet?) a chance to chain exceptions.

If you / mike can give a clear picture of the entire dependency chain than I can certainly weigh in further, but so far from what I can parse, a lot of what you're listing is out of process, and not involved?!?  What am I missing?

**Comment by noahfalk** [comment] 2015-04-17 07:48
@kangaroo 
Sure thing, hopefully this additional context helps. We anticipate the end-to-end Visual Studio remote debugging scenario probably uses 4 processes across two machines:
1) Visual Studio process (devenv.exe) running on the developer machine displays the UI and takes input from the developer. Internally VS has an interface boundary between the UI and the backend debug engines, and they will create a very simple that proxies those API calls via a network connection.
2) A remote listener process on the Linux machine listens to the other end of the network communication. It will convert the network messages to console input and pass them to the debugger process. The debugger process has structured output which will be converted to network messages and sent back.
3) The debugger process runs Visual Studio's .Net debugging engine. This code is a port of the code that would normally run on windows within devenv.exe or msvsmon.exe. Folks on the Visual Studio debugger team are working to port this code now, and they are making use of the PAL to help bring up their implementation faster. In order to get access to CoreCLR specific debug information, the debugger first loads dbgshim.dll. The debugger uses APIs in this module to get attached to a specific process running CoreCLR, and to get access to an ICorDebug interface. Dbgshim's primary purpose is to handle versioning. It interrogates the debuggee process, then loads the appropriate versions of mscordbi.dll (DBI) and mscordaccore.dll (DAC). If you wanted to debug 5 different processes with 5 different coreclr versions inside of them then the debugger process would have one dbgshim.dll loaded + 5 pairs of dbi/dac. DBI implements the ICorDebug interface, and DAC is a support library used by DBI. It probably isn't too relevant what the division of responsibility between them is, but I can get into that if needed. DAC and DBI use various inter-process communication techniques to get and send data to the debuggee process. On windows that consists of shared memory, OS events, Read/WriteVirtualMemory, and OS debug APIs like WaitForDebugEvent. On Linux I believe Eugene has replaced some of these with alternate schemes like named pipes.
It also happens that Visual Studio's .Net debugger is partially implemented in managed code, so at some point the debugger process will load coreclr to execute that code. This coreclr loaded in the debugger is completely an implementation detail of the way VS chose to write their debugger. It would be just as reasonable to have an alternate debugger that is written in pure C++ and never loads coreclr in the debugger process. This means dbgshim, dac, and dbi can't make any assumption about coreclr.dll being loaded in the debugger, and if it is loaded they can't make assumptions about the relative load order or the version of coreclr that will be present.
4) Last we've got the debuggee process which has coreclr loaded inside of it. There is a helper thread that runs listening and responding to requests from the debugger.


There are several PAL issues that needed to be solved, and I think we've got some tentative medium to long term solutions:
1) Each of the components in the debugger process (VS debugger, dbgshim, dac, dbi, coreclr) originally targeted windows and now needs to run xplat so PAL functionality is useful. POR is to statically link a copy of the PAL into each of those components. Potentially dbi/dac would share a single copy between themselves because those two modules version together tightly. These PALs don't necessarily have to be the same because the components don't all need the same APIs, but for simplicity we would probably start with everything the same and then customize if there is a substantial benefit.
2) DAC and coreclr both want to hook signal handlers that are process global. We think the Linux APIs will provide us with the previous handler when registering a new one. DAC, coreclr, and any other future 3rd party component that wanted to register a handler would all need to abide by a convention of chaining back to the previous handler. This part would be a behavioral contract that needs to maintained across versions. If the chaining wasn't sufficient then we could also solve it by creating an official API to let DAC opt-in/opt-out as you suggested. Things do get a little tricky there because load order isn't guaranteed... DAC might load and run first and coreclr would be second.

Mikem has some other issues listed above + proposed solutions so I don't want to get too repetitive with what he already wrote, but I'm happy to keep drilling into this until the full situation is clear and everyone is happy with the proposed solutions.

HTH,
  -Noah

**Comment by noahfalk** [comment] 2015-04-20 23:56
@kangaroo
Just wanted to check if this info was helpful and if you still had questions/feedback on the current approach? Thanks!

**Comment by kangaroo** [comment] 2015-04-21 07:26
@noahfalk Sorry, I'm traveling right now and haven't had time to fully go through this yet.  Its certainly a non-blocker, but it is on my todo list.

**Comment by noahfalk** [comment] 2015-04-21 20:35
no rush at all, just wanted to ensure you saw it. Happy travels ; )

**Comment by mikem8361** [comment] 2015-04-28 22:27
The coreclr changes were merged in #858. corefx in #1566.

**Closed** 2015-04-28 22:33 UTC
