### ISSUE TITLE
Unhandled Exception in xunit running Linux/arm64 testing

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19983] opened 2018-09-15 17:17 UTC
I've seen this in several CI test jobs. It doesn't affect the job result (which can still pass). Note that these are 48-core machines; perhaps there is a race somewhere.

```
21:05:19   Unhandled Exception: System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
21:05:19      at System.Collections.Generic.Stack`1.Enumerator.MoveNext()
21:05:19      at Xunit.Sdk.DisposalTracker.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\DisposalTracker.cs:line 26
21:05:19      at Xunit.Sdk.ExtensibilityPointFactory.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs:line 53
21:05:19      at Xunit.Sdk.TestFramework.Dispose() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestFramework.cs:line 48
21:05:19      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
21:05:19      at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
21:05:19      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
21:05:19   --- End of stack trace from previous location where exception was thrown ---
21:05:19      at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
21:05:19      at System.Threading.ThreadPoolWorkQueue.Dispatch()
21:05:19      at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs4_tst_prtest/1/console
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstressregs0x1000_tst_prtest/1/console
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstressregs2_tst_prtest/1/console
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_ubuntu16.04_zapdisable_tst_prtest/1/console

**Comment by BruceForstall** [comment] 2018-09-19 03:58
Yes, looks the same.

Another case:
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress2_tst_prtest/3/consoleFull

**Comment by BruceForstall** [comment] 2018-10-22 16:16
I thought this wasn't causing test failures, but it apparently is causing these following tests to fail, leading to very few job successes:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_ubuntu16.04_tst/26/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_ubuntu16.04_tst/25/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_ubuntu16.04_tst/24/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_release_ubuntu16.04_tst/23/consoleFull

**Comment by BruceForstall** [comment] 2018-12-17 23:31
Still seeing this frequently, e.g.

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_jitstress2_jitstressregs3_tst/70/consoleFull

**Comment by BruceForstall** [comment] 2018-12-17 23:32
@echesakovMSFT Didn't you have a proposed xunit fix for this? If so, can you link it here?

**Comment by RussKeldorph** [comment] 2019-01-16 22:51
Assuming duplicate of #19890.

**Closed by RussKeldorph** 2019-01-16 22:51 UTC
Labels: arch-arm64, os-linux
