### ISSUE TITLE
Resource assemblies not loaded when load context is collectible

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/coreclr#22458] opened 2019-02-07 05:31 UTC
Load contexts created with `isCollectible: true` do not behave the same as non-collectible load context with respect to loading resource assemblies. When isCollectible is false, `AssemblyLoadContext.Load(AssemblyName assemblyName)` is invoked by .NET Core giving the context the opportunity to specify where to find the resource assembly. But when isCollectible is true, `.Load` is not called.

### Repro steps

1. Extract this minimal, self-contained repro: 
[repro.zip](https://github.com/dotnet/coreclr/files/2839427/repro.zip)

2. Using .NET Core 3.0 Preview 2, execute `dotnet run --project ConsoleApp/ConsoleApp.csproj`

### Details 

This repro produces two assemblies

(1) an assembly with an entry point that prints a message from a localized resource.
```c#
    public static void Main()
    {
        Console.WriteLine(MyLocalizedAssembly.Strings.Greeting);
    }
```

"Strings.resx" contains:
```xml
    <data name="Greeting">
        <value>Hello world</value>
    </data>
```
"Strings.**es**.resx" contains:
```xml
    <data name="Greeting">
        <value>Hola mundo</value>
    </data>
```

(2) a console app which creates a load context thats load this first assembly and invokes the assembly entry point.

```c#
        private static void CreateContextAndExecuteMethod(bool isCollectible)
        {
            Console.WriteLine($"====== MyLoadContext: isCollectible = {isCollectible} ======");
            var context = new MyLoadContext(isCollectible);
            var assembly = context.LoadFromAssemblyName(new AssemblyName("MyLocalizedAssembly"));
            assembly.EntryPoint.Invoke(null, Array.Empty<object>());
        }

// ...

    class MyLoadContext : AssemblyLoadContext
    {
        public MyLoadContext(bool isCollectible) : base(isCollectible) { }

        protected override Assembly Load(AssemblyName name)
        {
            Console.WriteLine($"MyLoadContext.Load({name})");
            // .... (find and load assembly. Implementation in the repro project)
        }
   }
```

## Expected

Resource loading behavior is the same, regardless of `isCollectible`.

## Actual

When `isCollectible = true` and thread culture is `"es"`, the `.Load(AssemblyName)` method on the custom load context is not invoked to find and return the resource assembly. 

`CreateContextAndExecuteMethod(isCollectible: false)`
```
====== MyLoadContext: isCollectible = False ======
MyLoadContext.Load(MyLocalizedAssembly, Culture=neutral, PublicKeyToken=null)
MyLoadContext.Load(MyLocalizedAssembly.resources, Version=1.0.0.0, Culture=es, PublicKeyToken=null)

Hola mundo
```
`CreateContextAndExecuteMethod(isCollectible: true)`
```
====== MyLoadContext: isCollectible = True ======
MyLoadContext.Load(MyLocalizedAssembly, Culture=neutral, PublicKeyToken=null)

Hello world
```

**Comment by AaronRobinsonMSFT** [comment] 2019-02-07 06:12
cc @sdmaclea @janvorli

**Comment by janvorli** [comment] 2019-02-07 15:37
I am looking into it.

**Comment by janvorli** [comment] 2019-02-07 16:10
The cause of the problem is due to the same issue as #22270, closing this issue as a duplicate.
With a quick fix, I get this output:
```
====== MyLoadContext: isCollectible = False ======
MyLoadContext.Load(MyLocalizedAssembly, Culture=neutral, PublicKeyToken=null)
MyLoadContext.Load(System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
MyLoadContext.Load(System.Console, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
MyLoadContext.Load(System.Resources.ResourceManager, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
MyLoadContext.Load(MyLocalizedAssembly.resources, Version=1.0.0.0, Culture=es, PublicKeyToken=null)
Hola mundo
====== MyLoadContext: isCollectible = True ======
MyLoadContext.Load(MyLocalizedAssembly, Culture=neutral, PublicKeyToken=null)
MyLoadContext.Load(System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
MyLoadContext.Load(System.Console, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
MyLoadContext.Load(System.Resources.ResourceManager, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
MyLoadContext.Load(MyLocalizedAssembly.resources, Version=1.0.0.0, Culture=es, PublicKeyToken=null)
Hola mundo
```

**Closed by janvorli** 2019-02-07 16:10 UTC
Labels: area-VM
