### ISSUE TITLE
[x64/Linux] error : One or more tests failed while running tests from 'System.Memory.Tests'

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20946] opened 2018-11-12 07:10 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_baseline/751/

**Log:**
```
/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/dir.traversal.targets(77,5): error : (No message specified) [/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/tests.builds]

Build FAILED.

/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/Tools/tests.targets(576,5): warning MSB3073: The command "/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/artifacts/bin/tests/System.Memory.Tests/netcoreapp-Linux-Release-x64/RunTests.sh /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-x64/" exited with code 134. [/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/System.Memory/tests/System.Memory.Tests.csproj]
/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/Tools/tests.targets(584,5): error : One or more tests failed while running tests from 'System.Memory.Tests' please check /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/artifacts/bin/tests/System.Memory.Tests/netcoreapp-Linux-Release-x64/testResults.xml for details! [/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/System.Memory/tests/System.Memory.Tests.csproj]
/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/dir.traversal.targets(77,5): error : (No message specified) [/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/tests.builds]
    1 Warning(s)
    2 Error(s)

```

**Comment by echesakovMSFT** [comment] 2018-11-14 01:20
Duplicate of https://github.com/dotnet/coreclr/issues/20958

**Closed by echesakovMSFT** 2018-11-14 01:20 UTC
Labels: arch-x64, os-linux
