### ISSUE TITLE
Test failed: JIT_jit64._gc_misc_funclet_funclet_._gc_misc_funclet_funclet_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25412] opened 2019-06-26 02:16 UTC
**Job:**
https://mc.dot.net/#/user/coreclr-ci/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190625.38/workItem/JIT.jit64/analysis/xunit/JIT_jit64._gc_misc_funclet_funclet_~2F_gc_misc_funclet_funclet_cmd

**Failed tests:**
JIT_jit64._gc_misc_funclet_funclet_._gc_misc_funclet_funclet_cmd

**Log:**
```
Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\30a0ed73-ecd5-4ebb-a44a-f594f075cd5a\\Exec\\JIT\\jit64\\Reports\\JIT.jit64\\gc\\misc\\funclet\\funclet.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload\\corerun.exe\" funclet.exe 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Payload
> C:\\dotnetbuild\\work\\25c6d9f5-cf44-4040-ae58-3ef21e1bb95c\\Work\\30a0ed73-ecd5-4ebb-a44a-f594f075cd5a\\Exec\\JIT\\jit64\\gc\\misc\\funclet\\funclet.cmd
Expected: True
Actual:   False
```

**Comment by BruceForstall** [comment] 2019-06-26 16:24
https://github.com/dotnet/coreclr/pull/25429

**Comment by RussKeldorph** [comment] 2019-06-26 23:57
Assuming duplicate of #25376

**Closed by RussKeldorph** 2019-06-26 23:57 UTC
Labels: arch-arm32, os-windows
