### ISSUE TITLE
error MSB4020 in arm_cross_checked_windows_nt_r2r_tst

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22674] opened 2019-02-18 01:12 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_r2r_tst/45/

**Log:**
```
C:\j\workspace\arm_cross_che---583430d8\tests\dir.props(111,3): error MSB4020: The value "" of the "Project" attribute in element <Import> is invalid. [C:\j\workspace\arm_cross_che---583430d8\tests\runtest.proj]
```

**Comment by RussKeldorph** [comment] 2019-02-19 20:48
Duplicate of #22654

**Closed by RussKeldorph** 2019-02-19 20:48 UTC
Labels: arch-arm32
