### ISSUE TITLE
Cannot run tests by following windows-test-instructions.md

### ISSUE THREAD

**Issue by petertiedemann** [dotnet/coreclr#7040] opened 2016-09-02 17:53 UTC
I am trying to follow the instructions given here:

https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-test-instructions.md

I have succesfully followed the build instructions found (after starting with a clean VM and installing only exactly what was required):

https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md

I can succesfully use `build-test.cmd` to build the tests (at least it says it succeeds), but when i execute `run-tests.cmd` i end up with this error:

```
RUNTEST: Invoking msbuild
C:\git\coreclr\tests\tests.targets(21,5): error :  The wrappers must be compiled and placed at C:\git\coreclr\tests\\..
\bin\tests\Windows_NT..Debug\\tests\\*\ before they can be run, Do a clean Test Run [C:\git\coreclr\tests\runtest.proj]
```

Additionally i get the following:

```
RUNTEST: Error: msbuild failed. Refer to the log files for details:
    C:\git\coreclr\tests\..\bin\Logs\TestRunResults_Windows_NT__x64__Debug.log
    C:\git\coreclr\tests\..\bin\Logs\TestRunResults_Windows_NT__x64__Debug.wrn
    C:\git\coreclr\tests\..\bin\Logs\TestRunResults_Windows_NT__x64__Debug.err
Test Run failed. Refer to the following:
    Html report: C:\git\coreclr\tests\..\bin\Logs\TestRun_Windows_NT__x64__Debug.html
```

However, the file `C:\git\coreclr\tests\..\bin\Logs\TestRun_Windows_NT__x64__Debug.html` does not exist.

**Comment by rahku** [comment] 2016-09-02 19:20
check the log file C:\git\coreclr\tests\..\bin\Logs\TestRunResults_Windows_NT__x64__Debug.log  for errors. C:\git\coreclr\tests\..\bin\Logs\TestRun_Windows_NT__x64__Debug.html does not exist as it failed before any test execution started.Ensure that you have files name d C:\git\coreclr\bin\tests\Windows_NT.x86.Checked\baseservices\baseservices.XUnitWrapper.dll. The error you got compains that it did not find the above file

**Comment by petertiedemann** [comment] 2016-09-03 05:42
@rahku thanks for the reply. The .log file does not contain any additional information as far as i can tell (i guess i should have made that clear above:

```
Invoking: "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\git\coreclr\tests\runtest.proj" /p:Runtests=true /clp:showcommandline /nologo /nodeReuse:false  /p:Platform= /maxcpucount /fileloggerparameters:Verbosity=normal;LogFile="C:\git\coreclr\tests\..\bin\Logs\TestRunResults_Windows_NT__x64__Debug.log";Append /fileloggerparameters1:WarningsOnly;LogFile="C:\git\coreclr\tests\..\bin\Logs\TestRunResults_Windows_NT__x64__Debug.wrn" /fileloggerparameters2:ErrorsOnly;LogFile="C:\git\coreclr\tests\..\bin\Logs\TestRunResults_Windows_NT__x64__Debug.err" /consoleloggerparameters:Summary /verbosity:minimal 
Build started 9/2/2016 5:43:02 PM.
     1>Project "C:\git\coreclr\tests\runtest.proj" on node 1 (default targets).
     1>Project "C:\git\coreclr\tests\runtest.proj" (1) is building "C:\git\coreclr\tests\runtest.proj" (1:2) on node 1 (RunTests target(s)).
     1>C:\git\coreclr\tests\tests.targets(21,5): error :  The wrappers must be compiled and placed at C:\git\coreclr\tests\\..\bin\tests\Windows_NT..Debug\\tests\\*\ before they can be run, Do a clean Test Run [C:\git\coreclr\tests\runtest.proj]
     1>Done Building Project "C:\git\coreclr\tests\runtest.proj" (RunTests target(s)) -- FAILED.
     1>Done Building Project "C:\git\coreclr\tests\runtest.proj" (default targets) -- FAILED.

Build FAILED.

       "C:\git\coreclr\tests\runtest.proj" (default target) (1) ->
       "C:\git\coreclr\tests\runtest.proj" (RunTests target) (1:2) ->
       (FindTestDirectories target) -> 
         C:\git\coreclr\tests\tests.targets(21,5): error :  The wrappers must be compiled and placed at C:\git\coreclr\tests\\..\bin\tests\Windows_NT..Debug\\tests\\*\ before they can be run, Do a clean Test Run [C:\git\coreclr\tests\runtest.proj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.03

```

I will try another rebuild from scratch and check the file location.

**Comment by petertiedemann** [comment] 2016-09-03 05:51
@rahku I have the mentioned DLL at C:\git\coreclr\bin\tests\Windows_NT.x64.Debug\baseservices (which makes sense as i was building for Debug). Thats also where the error says its looking for it.

Do i need to build for Checked to run the tests?

**Comment by rahku** [comment] 2016-09-06 16:49
no it is not required to build checked to run tests. You have pasted the log output near
"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\git\coreclr\tests\runtest.proj" /p:Runtests=true 

Before above is invoked runtest.cmd also invokes msbuild for runtest.proj passing "BuildWrappers=true" param
"%__ProjectFilesDir%\runtest.proj" /p:BuildWrappers=true
This should generate the wrappers which seems to be missing for you. Can you verify that "%__ProjectFilesDir%\runtest.proj" /p:BuildWrappers=true is run from your C:\git\coreclr\tests..\bin\Logs\TestRunResults_Windows_NT__x64__Debug.log  file.

**Comment by erozenfeld** [comment] 2016-09-07 00:32
I was getting this error about wrappers when running runtest.cmd checked. When I ran runtest.cmd x64 checked, the error went away. I didn't investigate the root cause.

**Comment by petertiedemann** [comment] 2016-09-07 06:32
@erozenfeld That worked for me as well, pretty weird, considering it says its looking for x64 and I build for x64.

@rahku I pasted the entire log file above. 

As @erozenfeld mentions, if I try running again without specifying x64 it fails. It also works with `runtest.cmd x64 Debug` which is interesting as `runtest /?` lists those as the default values. I guess there is a problem somewhere in the script?

**Comment by wtgodbe** [comment] 2017-05-02 20:04
This was indeed an issue with the script, and was fixed by https://github.com/dotnet/coreclr/pull/7509.

**Closed by wtgodbe** 2017-05-02 20:04 UTC
Labels: area-Infrastructure, documentation
