### ISSUE TITLE
MSB4094 when publishing WPF app with PublishReadyToRun and PublishTrimmed

### ISSUE THREAD

**Issue by grubioe** [dotnet/coreclr#25846] opened 2019-07-23 20:07 UTC
@vegardlarsen commented on [Sat Jul 20 2019](https://github.com/dotnet/wpf/issues/1327)

* .NET Core Version: 3.0.100-preview6-012264
* Windows version: Windows 10 version 1903 (OS Build 18362.239)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: N/A

 
 
 **Problem description:**
 
When creating a blank WPF app, and setting PublishTrimmed and PublishReadyToRun, you will get a MSB4094 error when publishing the app.

 **Actual behavior:** 

```
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(281,28): error MSB4094: "obj\release\netcoreapp3.0\win-x86\linked\Microsoft.Win32.Registry.dll;obj\release\netcoreapp3.0\win-x86\linked\Microsoft.Win32.Registry.dll" is an invalid value for the "CompilationEntry" parameter of the "RunReadyToRunCompiler" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem". [C:\test\test.csproj]
```
 
 **Minimal repro:**

```
dotnet new wpf --name test
```

Make the `.csproj` file look like this:

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="4.5.0" />
  </ItemGroup>
</Project>
```

Then try to publish this project using:

```
dotnet publish -c release
```
 

---

@grubioe commented on [Tue Jul 23 2019](https://github.com/dotnet/wpf/issues/1327#issuecomment-514324275)

@jeffschwMSFT - do you know where this should be routed to?  Thanks

---

@jeffschwMSFT commented on [Tue Jul 23 2019](https://github.com/dotnet/wpf/issues/1327#issuecomment-514325150)

Please route to dotnet/coreclr

cc @fadimounir

**Comment by sbomer** [comment] 2019-07-24 21:09
This is a duplicate of https://github.com/dotnet/sdk/issues/3257, which has been fixed. @vegardlarsen you should be able to get this working with a newer preview - please let us know if you have any other issues!

**Closed by sbomer** 2019-07-24 21:09 UTC
Labels: area-ReadyToRun

**Comment by fadimounir** [comment] 2019-08-05 21:52
I was able to repro this with the latest Preview9 bits. Looks like a different bug with the same symptoms (double writes), which causes the R2R task to fail.
I filed https://github.com/dotnet/sdk/issues/3510 since it's an SDK issue
