### ISSUE TITLE
_tracecontrol_tracecontrol_sh test failed in CI on arm

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#20296] opened 2018-10-07 11:19 UTC
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/1798/consoleText
```
      tracing_tracecontrol._tracecontrol_tracecontrol_._tracecontrol_tracecontrol_sh [FAIL]
        
        cmdLine:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh Timed Out
        /n/nReturn code:      -100/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/Reports/tracing.tracecontrol/tracecontrol/tracecontrol.output.txt/nRaw output:/nBEGIN EXECUTION
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun tracecontrol.exe
        Calculated config file path: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/tracecontrol.eventpipeconfig
        Wrote contents of config file.
        Waiting 5 seconds for the config file to be picked up by the next poll operation.
        Do some work that will be captured by the trace.
        Done with the work.
        Deleted the config file.
        
        cmdLine:/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh Timed Out
        Test Harness Exitcode is : -100
        /nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_no_tiered_compilation_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/TestWrappers/tracing.tracecontrol/tracing.tracecontrol.XUnitWrapper.cs(109,0): at tracing_tracecontrol._tracecontrol_tracecontrol_._tracecontrol_tracecontrol_sh()
```

**Comment by stephentoub** [comment] 2018-10-09 19:45
Failed again here:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_tst_prtest/4653/
```
#################################################################
Output of failing tests:

[/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh]: 


cmdLine:/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh Timed Out
/n/nReturn code:      -100/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/Reports/tracing.tracecontrol/tracecontrol/tracecontrol.output.txt/nRaw output:/nBEGIN EXECUTION
/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun tracecontrol.exe
Calculated config file path: /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/tracecontrol.eventpipeconfig
Wrote contents of config file.
Waiting 5 seconds for the config file to be picked up by the next poll operation.
Do some work that will be captured by the trace.
Done with the work.
Deleted the config file.

cmdLine:/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh Timed Out
Test Harness Exitcode is : -100
/nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh/n
Expected: True
Actual:   False

cmdLine:/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh Timed Out


Return code:      -100
Raw output file:      /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/Reports/tracing.tracecontrol/tracecontrol/tracecontrol.output.txt
Raw output:
BEGIN EXECUTION
/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun tracecontrol.exe
Calculated config file path: /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/tracecontrol.eventpipeconfig
Wrote contents of config file.
Waiting 5 seconds for the config file to be picked up by the next poll operation.
Do some work that will be captured by the trace.
Done with the work.
Deleted the config file.

cmdLine:/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh Timed Out
Test Harness Exitcode is : -100

To run the test:
> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root
> /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh

Expected: True
Actual:   False


#################################################################
End of output of failing tests
#################################################################
```

**Comment by BruceForstall** [comment] 2018-10-11 15:51
Seems to fail relatively regularly for Ubuntu arm:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_flow_prtest/

E.g.,
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_innerloop_tst_prtest/4723/consoleFull
```
00:33:33 
      tracing_tracecontrol._tracecontrol_tracecontrol_._tracecontrol_tracecontrol_sh [FAIL]
00:33:33         
00:33:33         cmdLine:/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh Timed Out
00:33:33         /n/nReturn code:      -100/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/Reports/tracing.tracecontrol/tracecontrol/tracecontrol.output.txt/nRaw output:/nBEGIN EXECUTION
00:33:33         /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun tracecontrol.exe
00:33:33         Calculated config file path: /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/tracecontrol.eventpipeconfig
00:33:33         Wrote contents of config file.
00:33:33         Waiting 5 seconds for the config file to be picked up by the next poll operation.
00:33:33         Do some work that will be captured by the trace.
00:33:33         Done with the work.
00:33:33         Deleted the config file.
00:33:33         
00:33:33         cmdLine:/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh Timed Out
00:33:33         Test Harness Exitcode is : -100
00:33:33         /nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/tracing/tracecontrol/tracecontrol/tracecontrol.sh/n
00:33:33         Expected: True
00:33:33         Actual:   False
00:33:33         Stack Trace:
00:33:33           /ssd/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu_innerloop_tst_prtest/bin/tests/Linux.arm.Checked/TestWrappers/tracing.tracecontrol/tracing.tracecontrol.XUnitWrapper.cs(109,0): at tracing_tracecontrol._tracecontrol_tracecontrol_._tracecontrol_tracecontrol_sh()
```

**Comment by brianrob** [comment] 2018-10-11 18:44
Duplicate of #20299.

**Closed by brianrob** 2018-10-11 18:44 UTC
Labels: area-Tracing
