### ISSUE TITLE
Regression  for hashing on netcoreapp3.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/coreclr#21583] opened 2018-12-18 19:03 UTC
MurmurHash function is slower on netcoreapp3.0 as compared to netcore2.1. This is most probably due to codegen.
The numbers are
sdk = 3.0.100-preview-009841
``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17134.471 (1803/April2018Update/Redstone4)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-alpha1-009630
  [Host]     : .NET Core 3.0.0-preview1-26928-03 (CoreCLR 4.6.26927.03, CoreFX 4.6.26927.03), 64bit RyuJIT
  Job-GLYGMU : .NET Core 3.0.0-preview1-26928-03 (CoreCLR 4.6.26927.03, CoreFX 4.6.26927.03), 64bit RyuJIT

BuildConfiguration=Release-Intrinsics  Toolchain=netcoreapp3.0  MaxIterationCount=20  
WarmupCount=1  

```
|              Method |     Mean |    Error |   StdDev | Extra Metric |
|-------------------- |---------:|---------:|---------:|-------------:|
| MurmurHashBenchmark | 231.0 ns | 4.122 ns | 3.654 ns |            - |

``` ini
 sdk version 2.1.401

```
|              Method |     Mean |     Error |    StdDev | Extra Metric |
|-------------------- |---------:|----------:|----------:|-------------:|
| MurmurHashBenchmark | 197.8 ns | 0.9518 ns | 0.8438 ns |            - |

the associated code is 
```C#
char[] input2;
uint arg;

[GlobalSetup(Target = nameof(MurmurHashBenchmark))]
public void setup2()
{
    int min = 0;
    int max = 100;
    Random randNum = new Random();
    arg = (uint)randNum.Next(min, max);

    input2 = new char[max];

    for (int i = 0; i < input2.Length; i++)
    {
        input2[i] = (char)randNum.Next(min, 128);
    }

}

[Benchmark]
public void MurmurHashBenchmark()
{
    ReadOnlySpan<char> _t = input2.AsSpan();
    MurmurHash(arg, _t);
}

public void MurmurHash(uint hash, ReadOnlySpan<char> span)
{
    ulong cur = 0;
    int bits = 0;
    for (int ich = 0; ich < span.Length; ich++)
    {
        uint ch = span[ich];
        cur |= ch << bits;
        bits += 8;

        if (bits >= 32)
        {
            hash = MurmurRound(hash, (uint)cur);
            cur = cur >> 32;
            bits -= 32;
        }
    }
}

public static uint MurmurRound(uint hash, uint chunk)
{
    chunk *= 0xCC9E2D51;
    chunk = Rotate(chunk, 15);
    chunk *= 0x1B873593;

    hash ^= chunk;
    hash = Rotate(hash, 13);
    hash *= 5;
    hash += 0xE6546B64;

    return hash;
}

private static uint Rotate(uint x, int r)
{
    return (x << r) | (x >> (32 - r));
}

```

cc @danmosemsft @tannergooding @eerhardt

**Comment by Anipik** [comment] 2018-12-18 19:04
cc @jkotas

**Comment by eerhardt** [comment] 2018-12-18 19:31
The baseline above is for .NET Core 2.1 correct?  That’s what you mean instead of “as compared netstandard”.

**Comment by Anipik** [comment] 2018-12-18 19:33
yes I corrected it to 2.1

**Comment by danmosemsft** [comment] 2018-12-18 19:37
@Anipik I see `input2.AsSpan();` -- could this just be another manifestation of the AsSpan regression? Perhaps you can subtract the timing you get when you remove all the code other than the AsSpan part. (Although, that might get elided, not sure how to avoid that)

**Comment by Anipik** [comment] 2018-12-18 19:39
@danmosemsft its not that manifestation the ```input.AsSpan()```  takes just 1 ns to run which is negligible as compared to the total time

**Comment by Tornhoof** [comment] 2018-12-18 22:31
You could try disabling tiered jit in 3.0 to see if it makes a difference.

**Comment by jkotas** [comment] 2018-12-19 02:43
The only asm-diff that I can see is in the `Rotate(UInt32, Int32)` method:

Before:
```
mov     eax,ecx
mov     ecx,edx
rol     eax,cl
ret
```

After:
```
nop     dword ptr [rax+rax]
mov     eax,ecx
mov     ecx,edx
rol     eax,cl
ret
```

The extra no-op is padding for ReJIT that was introduced by #18762.

@kouvel @noahfalk Do we really need the padding for ReJIT with tiered JITing enabled? ReJIT should be able to use the same code replacement strategy as tiered JIT. We should not need to pay for both the extra indirections and padding.

**Comment by kouvel** [comment] 2018-12-27 20:03
The extra padding is only added when tiering is disabled. With tiering, it uses the precode instead for entry point replacement and there is no additional padding.

On my machine the perf seems to be multimodal (2-3 modes) when precodes or the padding are involved. Some observations:
- As written, the callees (`Rotate` and `MurmurRound`) would not be jitted by the time the caller is jitted, so the call goes through a precode even in 2.1. In that sense, there is no difference between 2.1 and 3.0 regarding tiering. However, I'm seeing bimodal perf in 3.0 (with and without tiering) and not in 2.1.
- I tried adding calls to `Rotate` and `MurmurRound` in `setup2` such that they would be jitted in an order to avoid precodes in the call sequences (I called it "jit priming" below). With that the perf is slightly better in 2.1. The code in 3.0 with tiering would still have precodes but in the fast mode I'm not seeing a significant difference between 3.0 with tiering and 2.1 without tiering.
- The only other difference in code generated is the code for the `MurmurHash` loop body, which seems to be slightly better in 3.0, though perhaps negligibly
- The only other thing I see changing on each run is the alignment of code relative to a cache line. My theory is that certain relative alignments negatively affect how well prefetching works, causing the multimodality. Based on that theory, a fix for https://github.com/dotnet/coreclr/issues/20282 should solve the issue and give consistently fast perf.
- I also tried placing `AggressiveInlining` on `Rotate`, as it is small enough to be inlined but is not getting inlined for some reason. Perf improves significantly with this change and the best fix for this issue is probably to inline `Rotate` automatically. Actually after inlining `Rotate`, the code for `MurmurRound` becomes much smaller and it becomes a better candidate for inlining as well. @AndyAyersMS, any idea why `Rotate` would not be inlined here?

Numbers

2.1, original, fast

```
BenchmarkDotNet=v0.11.3.900-nightly, OS=Windows 10.0.17763.195 (1809/October2018Update/Redstone5)
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview-009844
  [Host]     : .NET Core ? (CoreCLR 4.6.27217.02, CoreFX 4.7.18.61304), 64bit RyuJIT
  Job-LCJPKB : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT

Runtime=Core  Toolchain=netcoreapp2.1  InvocationCount=4194304

              Method |     Mean |    Error |   StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|---------:|---------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 178.0 ns | 2.045 ns | 1.913 ns | 0.4939 ns | 174.9 ns | 176.9 ns | 177.7 ns | 179.7 ns | 181.4 ns | 5,617,415.4 |
```

2.1, original, slow

```
              Method |     Mean |    Error |   StdDev |   StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 255.0 ns | 4.856 ns | 4.769 ns | 1.192 ns | 248.4 ns | 250.8 ns | 255.0 ns | 258.4 ns | 264.3 ns | 3,922,021.7 |
```

3.0, original, no tiering, fast

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 182.3 ns | 0.6742 ns | 0.5977 ns | 0.1597 ns | 181.7 ns | 181.8 ns | 182.1 ns | 182.5 ns | 183.7 ns | 5,485,730.7 |
```

3.0, original, no tiering, slow

```
              Method |     Mean |    Error |   StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|---------:|---------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 198.7 ns | 3.361 ns | 3.144 ns | 0.8117 ns | 194.4 ns | 194.9 ns | 199.8 ns | 200.2 ns | 205.4 ns | 5,033,626.5 |
```

3.0, original, tiering, fast

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 217.8 ns | 0.5477 ns | 0.4855 ns | 0.1298 ns | 217.2 ns | 217.5 ns | 217.7 ns | 218.1 ns | 218.9 ns | 4,590,976.5 |
```

3.0, original, tiering, slow

```
              Method |     Mean |    Error |   StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|---------:|---------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 241.8 ns | 1.778 ns | 1.485 ns | 0.4118 ns | 238.2 ns | 241.1 ns | 242.3 ns | 242.7 ns | 244.5 ns | 4,135,368.4 |
```

2.1, jit priming

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 161.0 ns | 0.4530 ns | 0.4238 ns | 0.1094 ns | 160.4 ns | 160.5 ns | 160.9 ns | 161.2 ns | 161.8 ns | 6,212,194.3 |
```

3.0, jit priming, no tiering, fast

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 173.4 ns | 0.5924 ns | 0.5542 ns | 0.1431 ns | 172.9 ns | 173.0 ns | 173.3 ns | 173.7 ns | 174.9 ns | 5,767,026.3 |
```

3.0, jit priming, no tiering, slow

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 203.2 ns | 0.7102 ns | 0.6643 ns | 0.1715 ns | 202.5 ns | 202.7 ns | 202.9 ns | 203.8 ns | 204.9 ns | 4,920,494.8 |
```

3.0, jit priming, tiering, fast

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 167.7 ns | 0.7419 ns | 0.6577 ns | 0.1758 ns | 166.4 ns | 167.4 ns | 167.7 ns | 168.2 ns | 168.6 ns | 5,964,488.5 |
```

3.0, jit priming, tiering, slow

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 216.4 ns | 0.5669 ns | 0.5025 ns | 0.1343 ns | 215.7 ns | 216.1 ns | 216.3 ns | 216.5 ns | 217.4 ns | 4,621,196.1 |
```

2.1, inlining Rotate

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 116.6 ns | 0.3480 ns | 0.3085 ns | 0.0824 ns | 116.2 ns | 116.4 ns | 116.7 ns | 116.8 ns | 117.3 ns | 8,573,160.1 |
```

3.0, inlining Rotate, no tiering, fast

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 114.0 ns | 0.5839 ns | 0.5462 ns | 0.1410 ns | 113.3 ns | 113.4 ns | 113.9 ns | 114.4 ns | 115.3 ns | 8,772,974.1 |
```

3.0, inlining Rotate, no tiering, slow

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 129.3 ns | 0.5726 ns | 0.4471 ns | 0.1291 ns | 128.4 ns | 129.2 ns | 129.3 ns | 129.8 ns | 129.9 ns | 7,731,159.1 |
```

3.0, inlining Rotate, tiering, fast

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 113.4 ns | 0.3506 ns | 0.3279 ns | 0.0847 ns | 113.0 ns | 113.1 ns | 113.4 ns | 113.7 ns | 114.0 ns | 8,818,486.6 |
```

3.0, inlining Rotate, tiering, slow

```
              Method |     Mean |     Error |    StdDev |    StdErr |      Min |       Q1 |   Median |       Q3 |      Max |        Op/s |
-------------------- |---------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|------------:|
 MurmurHashBenchmark | 128.4 ns | 0.3643 ns | 0.3408 ns | 0.0880 ns | 127.9 ns | 128.0 ns | 128.4 ns | 128.6 ns | 129.0 ns | 7,790,432.2 |
```

**Comment by AndyAyersMS** [comment] 2019-01-04 21:48
`Rotate` is not seen as a good inlining candidate. Note the heuristics can't easily spot that the IL for rotate is an idiomatic rotate sequence that will optimize down to a small bit of native code.
```
Inline candidate callsite is boring.  Multiplier increased to 1.3.
calleeNativeSizeEstimate=189
callsiteNativeSizeEstimate=115
benefit multiplier=1.3
threshold=149
Native estimate for function size exceeds threshold for inlining 18.9 > 14.9 (multiplier = 1.3)
```

**Comment by kouvel** [comment] 2019-01-07 19:15
I see, I thought the code was small enough despite folding down to `rol`, but I guess the code size would still be slightly smaller without inlining. Even without folding to `rol`, I doubt that inlining this always would have too much negative consequence compared to the reduction in code executed, but maybe. I'll go ahead a close this as a duplicate of https://github.com/dotnet/coreclr/issues/20282.

**Closed by kouvel** 2019-01-07 19:15 UTC
Labels: area-TieredCompilation, bug, tenet-performance
