### ISSUE TITLE
[JitStress][OSX][Unix] Assertion failed 'varDsc->lvSize() == 16'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#8896] opened 2017-01-11 17:38 UTC
JIT/Regression/JitBlue/GitHub_8220/GitHub_8220 fails with COMPlus_JitStress=1, COMPlus_JitStress=2 on unix/osx x64

```
16:09:26 FAILED   - JIT/Regression/JitBlue/GitHub_8220/GitHub_8220/GitHub_8220.sh
16:09:26                BEGIN EXECUTION
16:09:26                /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx_jitstress1_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx_jitstress1_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/jit-dasm.dll --crossgen /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx_jitstress1_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/crossgen.exe --platform /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx_jitstress1_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay --output D:/j/workspace/checked_windo---3c72507e/bin/tests//Windows_NT.x64.Checked/dasm/JIT/Regression/JitBlue/GitHub_8220/GitHub_8220 GitHub_8220.exe
16:09:26                Managed assembly not found: No such file or directory
16:09:26                ./GitHub_8220.sh: line 83: [: -ne: unary operator expected
16:09:26                /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx_jitstress1_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun GitHub_8220.exe
16:09:26                Testing Dot Product
16:09:26                Testing Equals
16:09:26                
16:09:26                Assert failure(PID 70835 [0x000114b3], Thread: 23321826 [0x163dce2]): Assertion failed 'varDsc->lvSize() == 16' in 'Test.Program:testEquals(struct):int' (IL size 127)
16:09:26                
16:09:26                    File: /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx/src/jit/lower.cpp Line: 240
16:09:26                    Image: /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_osx_jitstress1_tst/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun
16:09:26                
16:09:26                ./GitHub_8220.sh: line 130: 70835 Abort trap: 6           (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" GitHub_8220.exe $CLRTestExecutionArguments
16:09:26                Expected: 100
16:09:26                Actual: 134
16:09:26                END EXECUTION - FAILED
```

**Comment by adiaaida** [comment] 2017-01-11 17:44
@CarolEidt It looks like this test has been failing jit stress modes on unix/osx since you added it. Do you have any background on the bug the test was meant to test against?

**Comment by CarolEidt** [comment] 2017-01-11 18:00
The bug was that we were incorrectly using the upper bits of Vector3 in the dot product and boolean equality intrinsics. I'm not sure what would cause this to fail in stress modes; it would require some investigation.

**Comment by adiaaida** [comment] 2017-01-11 18:22
It looks like a TYP_SIMD12 var has a size of 0, when it should have a size of 16 on x64.

**Comment by RussKeldorph** [comment] 2017-01-11 18:50
Duplicate of #8550.  Please use that instead.

**Closed** 2017-01-12 18:15 UTC
Labels: area-CodeGen, bug, JitStress, os-linux, os-mac-os-x
