### ISSUE TITLE
Test Failure in test managed._Compilation_Compilation_Compilation_._Compilation_Compilation_Compilation_cmd on Windows

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#2535] opened 2016-01-05 20:57 UTC
On Windows I get the following failure. It looks like tailcall isuue:
d:\repos\coreclr\tests\src\TestWrappers_x64_debug\managed\managed.XUnitWrapper.cs(80): error : managed._Compilation_Compilation_Compilation_._Compilation_Compi
lation_Compilation_cmd [FAIL] [D:\repos\coreclr\tests\runtest.proj]

        Assert failure(PID 4272 [0x000010b0], Thread: 712 [0x02c8]): rangeOffset >= (offset + (sizeof(void*) * 3))

        CORECLR! EncodeGCOffsets + 0x331 (0x00007ffd`a7936ad1)
        CORECLR! StubLinkerCPU::CreateTailCallCopyArgsThunk + 0x1499 (0x00007ffd`a7933109)
        CORECLR! CEEInfo::getTailCallCopyArgsThunk + 0x2B1 (0x00007ffd`a7b477a1)
        CORECLR! Compiler::fgMorphTailCall + 0x564 (0x00007ffd`a85b8074)
        CORECLR! Compiler::fgMorphCall + 0x62D (0x00007ffd`a85a5e4d)
        CORECLR! Compiler::fgMorphTree + 0x531 (0x00007ffd`a85b8651)
        CORECLR! Compiler::fgMorphSmpOp + 0x14D4 (0x00007ffd`a85b08a4)
        CORECLR! Compiler::fgMorphTree + 0x48E (0x00007ffd`a85b85ae)
        CORECLR! Compiler::fgMorphStmts + 0x2F0 (0x00007ffd`a85b6f00)
        CORECLR! Compiler::fgMorphBlocks + 0x187 (0x00007ffd`a85a4e87)
            File: d:\repos\coreclr\src\vm\i386\stublinkerx86.cpp Line: 6052
            Image: D:\repos\coreclr\bin\tests\Windows_NT.x64.debug\Tests\Core_Root\CoreRun.exe

  Raw output:      D:\repos\coreclr\bin\tests\Windows_NT.x64.debug\Reports\managed\Compilation\Compilation\Compilation.output.txt
  To run the test:
  > set CORE_ROOT=D:\repos\coreclr\bin\tests\Windows_NT.x64.debug\Tests\Core_Root
  > D:\repos\coreclr\bin\tests\Windows_NT.x64.debug\managed\Compilation\Compilation\Compilation.cmd

        Expected: True
        Actual:   False

**Comment by sivarv** [comment] 2016-01-06 01:19
Closing this issue as it is a duplicate of #2508

**Closed by sivarv** 2016-01-06 01:19 UTC
Labels: bug, CodeGen
