### ISSUE TITLE
JIT.Performance.CodeQuality.Serialization.Serialize.Serialize failing

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#9733] opened 2017-02-23 09:35 UTC
The JIT.Performance.CodeQuality.Serialization.Deserialize.Deserialize and JIT.Performance.CodeQuality.Serialization.Serialize.Serialize tests are failing with 
`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'xunit.performance.core, Version=1.0.0.40, Culture=neutral, PublicKeyToken=67066efe964d3b03'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040 (FUSION_E_REF_DEF_MISMATCH))`

**Comment by janvorli** [comment] 2017-02-23 09:40
They fail on Ubuntu starting with build https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/2806/

**Comment by janvorli** [comment] 2017-02-23 09:58
CC: @gkhanna79

**Comment by gkhanna79** [comment] 2017-02-23 16:46
@pgavlin Can you PTAL as it appears to have commenced from your PR?

**Comment by AndyAyersMS** [comment] 2017-02-23 17:02
This is an issue caused by CoreFX update. See #9733.

**Comment by gkhanna79** [comment] 2017-02-23 17:05
@AndyAyersMS the link you shared is for this issue itself. Which CoreFX update issue are you referring to?

**Comment by AndyAyersMS** [comment] 2017-02-23 17:07
Ah, sorry, there are notes on this over in #9729.

**Comment by brianrob** [comment] 2017-02-23 20:15
CI should be unblocked now that #9741 is merged.  I'll follow-up on re-enabling these tests.

**Comment by wtgodbe** [comment] 2017-02-24 18:54
https://github.com/dotnet/coreclr/pull/9749 fixes this issue

**Closed by wtgodbe** 2017-02-24 18:54 UTC
Labels: area-Meta, os-linux
