### ISSUE TITLE
Fix paltest_queryperformancecounter_test1

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#10209] opened 2017-03-15 22:35 UTC
This test started failing in CI after upgrading the CI machines to Sierra. It was disabled in https://github.com/dotnet/coreclr/pull/10173 to get the upgrade unblocked.

**Comment by gkhanna79** [comment] 2017-04-27 19:17
CC @janvorli

**Comment by gkhanna79** [comment] 2017-05-09 15:43
@janvorli Did you get a chance to look into this?

**Comment by janvorli** [comment] 2017-05-09 15:54
@gkhanna79 yes, I was trying to repro it locally and I was unable to get anything close to a repro. I have added some detailed logging to the test. On my OSX machine, the max delta was 9ms and it is mostly stable. On the lab machines, it consistently fails. The delta fluctuates heavily and often goes upto 150ms, which is ridiculous since it would seem as if the scheduling quantum on those machines was that long and it doesn't make sense.
I have also tried to change the time measurement method in the QueryPerformanceCounter / Frequency and got the same results.
I've experimented with the changes in my WIP PR #11291.

**Comment by gkhanna79** [comment] 2017-05-09 19:08
@mmitche Can you please get @janvorli a Mac machine from the CI lab for him to investigate this?

**Comment by gkhanna79** [comment] 2017-05-09 22:04
@mmitche Were you able to get a machine to @janvorli since we are tracking this for ZBB tomorrow?

**Comment by janvorli** [comment] 2017-05-09 22:12
@gkhanna79, @mmitche has provided me with all the information necessary to access the machine. I am now in a process of resolving access issues to the Mac machine.

**Comment by janvorli** [comment] 2017-05-09 23:41
The results of the test run on the dci-mac-build-043 are even more ridiculous. They are actually consistently better than on my local Mac! Where on my mac I was getting average delta time between the Sleep and time measured by the QueryPerformanceTimer of 9ms, on the lab machine when I've ran the stuff manually I am now getting 3ms.
So the only explanation I can see is that something in the Jenkins interferes with the test. A theory that I have is that something else is consuming nontrivial amount of CPU while the test is running and since the test repeats sleeping for 100ms, the CPU scheduler somehow detects that and adaptively modifies the scheduling quantum to a large value to give more time to the CPU heavy thread instead. And that would mean that it would take upto the scheduling quantum between the Sleep end and the thread running again.

**Comment by janvorli** [comment] 2017-05-10 00:51
Hmm, I've tried to run coreclr build in one console and the test in another on my local Mac and there was no such effect. On the contrary, the diff went down from 9ms to 2ms. After cancelling the build, the diff goes back to 9ms. It is a reproducible behavior, I've tried multiple times.
So I have currently no idea on what can be causing the strange behavior in the CI. The only clear thing is that it has something to do with Jenkins or something else that runs in parallel with the tests in Jenkins.
@mmitche do you know if Jenkins somehow tweaks the execution environment settings - like adding some CPU cap or anything like that?

**Comment by gkhanna79** [comment] 2017-05-10 16:28
@janvorli Sounds like it has been confirmed this is not a product issue. Given that, can we move it out of 2.0 and mark this as an infrastructure issue that we can continue to investigate?

**Comment by janvorli** [comment] 2017-05-10 16:32
@gkhanna79 sounds good to me. I've done that.

**Comment by RussKeldorph** [comment] 2019-05-22 17:36
@janvorli Just checking on old bugs.  Is this still on your plate for for 3.0?

**Comment by janvorli** [comment] 2019-05-22 17:48
I've actually retried the test run about a week ago the lab and it passed, so it might have been an issue specific to the OSX version we were using in the past. I'm going to reenable the test and then close this issue.

**Closed** 2019-05-24 02:33 UTC
Labels: area-Infrastructure, test bug
