### ISSUE TITLE
Evaluate JIT_MonEnter/JIT_MonExit lock helper optimization for 64 bits Linux

### ISSUE THREAD

**Issue by helloguo** [dotnet/coreclr#7401] opened 2016-09-28 16:22 UTC
The lock helpers such as JIT_MonEnter/JIT_MonExit are in the top hotspots in TechEmpower Plaintext scenario (measured on 64 bits Ubuntu 14.04 LTS, Intel® Xeon® Processor  E5-2699 v4).

![issue](https://cloud.githubusercontent.com/assets/18431130/18922292/d838fb24-855c-11e6-9853-3e83765adf9a.PNG)

Currently, 64 bits Linux has a portable version for these lock helpers. An optimized assembly version may be worth evaluating and implementing.

**Comment by benaadams** [comment] 2016-09-28 16:56
Windows uses the versions in JitHelpers_InlineGetThread could these be used? (Don't know if they are Windows specific)  e.g. https://github.com/dotnet/coreclr/blob/master/src/vm/amd64/JitHelpers_InlineGetThread.asm#L405-L639

**Comment by jkotas** [comment] 2016-09-28 17:47
The difference is caused by slower TLS access on Linux - rewriting it in assembly is unlikely to help. @kouvel spent quite a bit of time on it.

**Comment by kouvel** [comment] 2016-09-28 18:25
The issue with TLS access is most likely due to dynamically loading CoreCLR instead of statically linking it. The following explain the issue in more detail:
- http://david-grs.github.io/tls_performance_overhead_cost_linux/
- https://www.akkadia.org/drepper/tls.pdf

**Comment by kouvel** [comment] 2017-09-15 19:06
Closing, issue https://github.com/dotnet/coreclr/issues/13949 tracks investigating improvements to Monitor spinning on all platforms

**Closed by kouvel** 2017-09-15 19:06 UTC
Labels: area-System.Threading, tenet-performance
