### ISSUE TITLE
Building coreclr on OS X gives boot disk space warnings

### ISSUE THREAD

**Issue by thejayvm** [dotnet/coreclr#281] opened 2015-02-16 21:42 UTC
I built the Core CLR on my MBP pro last night using the instructions found [here](http://praeclarum.org/post/110552954728/building-and-running-nets-coreclr-on-os-x). Upon running

    ./build.sh amd64 debug

I got a warning from my OS saying that my boot disk was getting full. I also checked my free space and what was once 96GB free was now less than 1GB. I panicked and cancelled the build and took to twitter, where @kangaroo assured me that was "normal." And sure enough I have my 96 gb back and the CLR is built and running on my system.

He also asked me to create this issue as he had something in mind to alleviate the... concerns some of us unsuspecting developers might have from building this.

Cheers!

**Comment by kangaroo** [comment] 2015-02-16 22:35
This is caused by the following configure checks:

HAVE_FTRUNCATE_LARGE_LENGTH_SUPPORT
HAS_FTRUNCATE_LENGTH_BUG

We may just want to put those in as binary commits and not runtime probe them.

**Comment by janvorli** [comment] 2015-02-16 23:44
@kangaroo I believe that we should do that. It is especially nasty on VMs where it explodes the virtual hard drive size that doesn't shrink back.

**Comment by kangaroo** [comment] 2015-02-17 00:53
PR: https://github.com/dotnet/coreclr/pull/283

**Comment by kangaroo** [comment] 2015-02-18 04:01
PR merged, can someone close this out please?

**Comment by ellismg** [comment] 2015-02-18 05:39
Fixed via #283

**Closed by ellismg** 2015-02-18 05:39 UTC
