### ISSUE TITLE
Failure in corefx System.Diagnostics.StackTrace.Tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17583] opened 2018-04-16 17:11 UTC
Consistent failure in COMPlus_JitStress=2 runs of corefx tests, in System.Diagnostics.StackTrace.Tests:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_jitstress2_tst/10/consoleText

```
Running: C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Diagnostics.StackTrace.Tests\netcoreapp-Windows_NT-Release-arm\RunTests.cmd C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm
Using C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm as the test runtime folder.
Executing in C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Diagnostics.StackTrace.Tests\netcoreapp-Windows_NT-Release-arm\ 
----- start 23:12:41.18 ===============  To repro directly: ===================================================== 
pushd C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Diagnostics.StackTrace.Tests\netcoreapp-Windows_NT-Release-arm\
set COMPlus_JitStress=2
call C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe System.Diagnostics.StackTrace.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Diagnostics.StackTrace.Tests\netcoreapp-Windows_NT-Release-arm>set COMPlus_JitStress=2 

C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Diagnostics.StackTrace.Tests\netcoreapp-Windows_NT-Release-arm>call C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe System.Diagnostics.StackTrace.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Diagnostics.StackTrace.Tests
Discovered:  System.Diagnostics.StackTrace.Tests
Starting:    System.Diagnostics.StackTrace.Tests
   System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpected [FAIL]
      Assert.NotEqual() Failure
      Expected: Not Void SkipFrames_CallMethod_ReturnsExpected()
      Actual:   Void SkipFrames_CallMethod_ReturnsExpected()
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(69,0): at System.Diagnostics.Tests.StackFrameTests.SkipFrames_CallMethod_ReturnsExpected()
Finished:    System.Diagnostics.StackTrace.Tests

=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.StackTrace.Tests  Total: 103, Errors: 0, Failed: 1, Skipped: 0, Time: 4.276s
----- end 23:12:50.46 ----- exit code 1 ----------------------------------------------------------
COREFX TEST FAILED
```

**Comment by RussKeldorph** [comment] 2018-04-18 01:31
Shows the classic signs of a test that is sensitive to JIT optimization, e.g. inlining.  Please move to corefx and indicate problem if so.  We'll have to figure out how to exclude tests like this in our various stress modes in the future.

**Comment by RussKeldorph** [comment] 2018-04-19 17:18
Duplicate of #17558.

**Closed by RussKeldorph** 2018-04-19 17:18 UTC
Labels: JitStress, test bug
