### ISSUE TITLE
 AccessViolationException on implicit conversion of explicit layout unions when optimizations enabled

### ISSUE THREAD

**Issue by RossNordby** [dotnet/coreclr#8775] opened 2017-01-02 23:48 UTC
Calling Test in the following causes an AccessViolationException when optimizations are enabled. 
```cs
    static class Repro
    {
        struct Type1
        {
            long Thing1;
            long Thing2;

        }
        struct Type2
        {
            public long Thing;
        }

        [StructLayout(LayoutKind.Explicit)]
        struct Union
        {
            [FieldOffset(0)]
            public Type1 One;

            [FieldOffset(0)]
            public Type2 Two;
        }

        struct TestStruct
        {
            public Union Union;

            //If conversion inlining is disabled, there is no error.
            //(Suppressing optimizations here, on the other hand, does not help.)
            //[MethodImpl(MethodImplOptions.NoInlining)]
            public static implicit operator TestStruct(Type2 two)
            {
                var testStruct = new TestStruct();
                //If the union is explicitly constructed, there is no error.
                //testStruct.Union = new Union();
                testStruct.Union.Two = two;
                return testStruct;
            }

        }

        //If optimizations are suppressed, there is no error.
        //[MethodImpl(MethodImplOptions.NoOptimization)]
        public static void Test()
        {
            //If the struct is directly constructed rather than using a implicit conversion, there is no error.
            //var test = new TestStruct();
            //test.Union.Two = new Type2();

            TestStruct test = new Type2();

            Console.WriteLine($"Contents: {test.Union.Two.Thing}");
        }
    }
```

**Comment by janvorli** [comment] 2017-01-02 23:55
@RossNordby what OS / architecture have you tested it on?

**Comment by RossNordby** [comment] 2017-01-03 00:08
Woops, forgot to mention- Windows 10, x64. Doesn't seem to happen under x86.

**Comment by mikedn** [comment] 2017-01-03 08:36
Can't reproduce with the current CoreCLR version. In the desktop .NET Framework this crashes RyuJIT in:
```
ValueNumStore::VNApplySelectorsTypeCheck
ValueNumStore::VNPairApplySelectors
Compiler::fgValueNumberBlock
Compiler::fgValueNumber
Compiler::compCompile
```
The crash seems to be caused by indexing `m_chunks` by `0x0000000003ffffff`, that's `NoVN >> 6` so this was probably fixed by #7958.

cc @JosephTremoulet @pgavlin

**Comment by gkhanna79** [comment] 2017-01-30 19:01
CC @RussKeldorph @russellhadley

**Comment by JosephTremoulet** [comment] 2017-01-30 19:53
I've verified that this doesn't repro in CodegenMirror.

**Closed** 2017-01-31 01:11 UTC
Labels: area-CodeGen
