### ISSUE TITLE
[JitStress]  Assertion failed '!\"Incompatible types for gtNewTempAssign\"

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#27290] opened 2019-10-18 18:10 UTC
JIT/Directed/VectorABI/VectorMgdMgd_ro/VectorMgdMgd started to fail in different stress modes on different platforms, [example](https://dev.azure.com/dnceng/public/_build/results?buildId=389381&view=ms.vss-test-web.build-test-results-tab&runId=12060358&paneView=debug&resultId=100858)

[The last successful run](https://dev.azure.com/dnceng/public/_build/results?buildId=387947) 10-14,
[the first failed run](https://dev.azure.com/dnceng/public/_build/results?buildId=389381) 10-15.

Could be related to #27289

cc @dotnet/jit-contrib

**Comment by echesakovMSFT** [comment] 2019-10-18 18:31
I think my PR https://github.com/dotnet/coreclr/pull/26549 exposed this issue https://github.com/dotnet/coreclr/issues/26491

So this one is a duplicate of #26491

**Comment by echesakovMSFT** [comment] 2019-10-18 18:32
We should disable tests that fail with this assertion and link them to the issue

**Comment by echesakovMSFT** [comment] 2019-10-18 18:32
This is a repro of the issue https://github.com/dotnet/coreclr/pull/26518

**Comment by sandreenko** [comment] 2019-10-18 18:47
> We should disable tests that fail with this assertion and link them to the issue

Yes, but it would be useful to confirm that it is the same issue and why it started to fail 3 days ago (before the test was passing).

**Comment by echesakovMSFT** [comment] 2019-10-18 18:53
> We should disable tests that fail with this assertion and link them to the issue
> 
> Yes, but it would be useful to confirm that it is the same issue and why it started to fail 3 days ago (before the test was passing).

Because the new stress mode exposed the issue? I merged my PR three days ago

**Comment by CarolEidt** [comment] 2019-10-18 22:01
These failures seem to raise the priority of fixing this issue. We could probably come up with a "workaround" fix, but I think the right fix is to defer the handling of `compRetNativeType` to `Lowering` as part of the overall plan to defer ABI-specific transformations.

**Closed** 2019-10-18 22:46 UTC
Labels: JitStress, area-CodeGen
