### ISSUE TITLE
GCStress Failure: JIT._Regression_CLR_x86_JIT_V1_M11_Beta1_b29351

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3768] opened 2016-03-16 19:13 UTC
JIT._Regression_CLR_x86_JIT_V1_M11_Beta1_b29351_b29351_b29351_._Regression_CLR_x86_JIT_V1_M11_Beta1_b29351_b29351_b29351_cmd
cmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b29351\b29351\b29351.cmd Timed Out\r\n\n\nRaw output:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Reports\JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b29351\b29351\b29351.output.txt\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x64.Release\JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b29351\b29351\b29351.cmd\n\r\nExpected: True\r\nActual:   False
   at JIT._Regression_CLR_x86_JIT_V1_M11_Beta1_b29351_b29351_b29351_._Regression_CLR_x86_JIT_V1_M11_Beta1_b29351_b29351_b29351_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x64_Release\JIT\JIT.XUnitWrapper.cs:line 260571

**Comment by AndyAyersMS** [comment] 2016-03-17 01:00
@LLITCHEV is going to triage these, so reassigning.

**Comment by LLITCHEV** [comment] 2016-03-18 19:11
I tried reproducing this several times locally using a fresh enlistment and could not. It seems to work fine. Could you give me steps how you get it to happen locally, please?

**Comment by gkhanna79** [comment] 2016-03-19 17:40
Repro steps: 

1) Build Pri1 tests with GCstress 15 using instructions at https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-test-instructions.md.

Example: tests\buildtests.cmd clean Release crossgen priority 1 gcstresslevel 15

2) Run the tests

Example: tests\runtest.cmd Release

3) Take a look at the results and repro steps in the failure report.

**Comment by LLITCHEV** [comment] 2016-03-21 00:00
In checked build this passes. In Release build crossgen.exe gets in an infinite loop. Trying to get where exactly.

**Comment by LLITCHEV** [comment] 2016-03-21 00:34
It looks like the recursion in the gtTreeHasSideEffects call chanin - line 11310 in gentree.cpp - in release build is quite big and we get there is a lot of analysis to be done. in this particular case, so it is slow - really slow. Eventually we get out, but the tests eventually times out.
The call chain is:
gtTreeHasSideEffects - line 11310 of gentree.cpp
gtTreeHasSideEffects - line 11240 of gentree.cpp
gtTreeHasSideEffects - line 11293 of gentree.cpp
optIsCSEcandidate - line 2178 of optcse.cpp
optOptimizevalnumCSEs - line 2089 of gentree.cpp

**Closed** 2016-04-01 04:54 UTC
Labels: 2 - In Progress, blocking-release, bug, CodeGen, GCStress, ReadyToRun
