### ISSUE TITLE
Alpine-Linux: System.DllNotFoundException when calling native library via P/Invoke

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#20952] opened 2018-11-12 16:07 UTC
_From @rjsathome on November 12, 2018 11:54_

I have a nuget package containing native code which is called via p/invoke fromt the .NET Core assembly.

When using this on Alpine Linux I get:

```sh
vmalpine64 (1)$ dotnet run
Using launch settings from /home/rjs/src/pdflib-9.1.x/dist/PDFlib/PDFlib-9.1.2p8-Alpine-Linux-x86_64-.NET-Core/bind/dotnetcore/csharp/hello/Properties/launchSettings.json...

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'PDFlib_dotnetcore_native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libPDFlib_dotnetcore_native: No such file or directory
   at PDFlib_dotnet.PDFlib.PInvoke.PDF_new()
   at PDFlib_dotnet.PDFlib..ctor()
   at Hello.Main(String[] args) in /home/rjs/src/pdflib-9.1.x/dist/PDFlib/PDFlib-9.1.2p8-Alpine-Linux-x86_64-.NET-Core/bind/dotnetcore/csharp/hello/hello.cs:line 15
```

The minmal code to reproduce is:

```csharp
using PDFlib_dotnet;
class Hello {
    static void Main(string[] args) {
        PDFlib p;
        p = new PDFlib();
    }
}
```

The Nuget package content is:

```sh
vmalpine64 (1)$ unzip -l ../../PDFlib_dotnet.1.2.8.nupkg
Archive:  ../../PDFlib_dotnet.1.2.8.nupkg
  Length      Date    Time    Name
---------  ---------- -----   ----
      503  11-06-2018 15:00   _rels/.rels
      748  11-06-2018 15:00   PDFlib_dotnet.nuspec
    35840  11-06-2018 14:00   lib/netstandard2.0/PDFlib_dotnet.dll
       36  10-22-2018 18:47   readme.txt
  8617128  11-06-2018 14:00   runtimes/alpine-x64/native/PDFlib_dotnetcore_native.so
      582  11-06-2018 15:00   [Content_Types].xml
      706  11-06-2018 15:00   package/services/metadata/core-properties/5c87229948e04d93aab4633ed8c7fcc5.psmdcp
 --------                     -------
  8655543                     7 files
```

I would expect that `dotnet run` finds the nativ library at runtimes/alpine-x64/native/PDFlib_dotnetcore_native.so in the nuget package. 

When I check with strace where dotnet searches I find:

```sh
vmalpine64 (1)$ strace -f -o strace.txt dotnet run
Using launch settings from /home/rjs/src/pdflib-9.1.x/dist/PDFlib/PDFlib-9.1.2p8-Alpine-Linux-x86_64-.NET-Core/bind/dotnetcore/csharp/hello/Properties/launchSettings.json...

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'PDFlib_dotnetcore_native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libPDFlib_dotnetcore_native: No such file or directory
   at PDFlib_dotnet.PDFlib.PInvoke.PDF_new()
   at PDFlib_dotnet.PDFlib..ctor()
   at Hello.Main(String[] args) in /home/rjs/src/pdflib-9.1.x/dist/PDFlib/PDFlib-9.1.2p8-Alpine-Linux-x86_64-.NET-Core/bind/dotnetcore/csharp/hello/hello.cs:line 7
vmalpine64 (1)$ grep dotnetcore_native strace.txt
#16906 open("/home/rjs/dotnet/shared/Microsoft.NETCore.App/2.1.2/PDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/home/rjs/.nuget/packages/pdflib_dotnet/1.2.8/lib/netstandard2.0/PDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/lib/PDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/usr/local/lib/PDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/usr/lib/PDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/home/rjs/dotnet/shared/Microsoft.NETCore.App/2.1.2/libPDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/home/rjs/.nuget/packages/pdflib_dotnet/1.2.8/lib/netstandard2.0/libPDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/lib/libPDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/usr/local/lib/libPDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/usr/lib/libPDFlib_dotnetcore_native.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/home/rjs/dotnet/shared/Microsoft.NETCore.App/2.1.2/PDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/home/rjs/.nuget/packages/pdflib_dotnet/1.2.8/lib/netstandard2.0/PDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/lib/PDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/usr/local/lib/PDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/usr/lib/PDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/home/rjs/dotnet/shared/Microsoft.NETCore.App/2.1.2/libPDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/home/rjs/.nuget/packages/pdflib_dotnet/1.2.8/lib/netstandard2.0/libPDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/lib/libPDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/usr/local/lib/libPDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
16906 open("/usr/lib/libPDFlib_dotnetcore_native", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

On Alpine-Linux `donet run` only looks in the "/home/rjs/.nuget/packages/pdflib_dotnet/1.2.8/lib/netstandard2.0/" directory, not int the "runtimes/alpine-x64/native/" directory.

The dotnet version is:
```sh
vmalpine64 (1)$  dotnet --version
2.1.400
````

I also tested it with the 2.1.403 version. 

Alpine LInux is:

```sh
vmalpine64 (1)$ uname -a
Linux vmalpine64 4.14.69-0-vanilla #1-Alpine SMP Mon Sep 10 19:33:23 UTC 2018 x86_64 Linux
vmalpine64 (1)$ cat /etc/alpine-release
3.8.1
````

On macOS or Ubuntu it is working as expected.

_Copied from original issue: dotnet/corefx#33409_

**Comment by jkotas** [comment] 2018-11-12 16:07
cc @swaroop-sridhar  @AaronRobinsonMSFT  @jkoritzinsky

**Comment by rjsathome** [comment] 2018-11-13 09:10
> Hi @rjsathome, is the error specific to this project? Are you able to run other test binaries successfully on Alpine linux?

I have many test examples for this package which all behave the same way. But I don't have another nuget package that uses native code to test with.

But as mentioned before the same code runs fine on other platforms (tested with mac OS, Windows and Ubuntu)

I even can run this project successful when I copy PDFlib_dotnetcore_native.so to the ".nuget/packages/pdflib_dotnet/1.2.8/lib/netstandard2.0/" directory. 

> Can you please share the host trace for the run?
> set COREHOST_TRACE=1
> set COREHOST_TRACE_VERBOSITY=4

Here is the trace:
[trace.txt](https://github.com/dotnet/coreclr/files/2575371/trace.txt)


```trace
...
Using /home/rjs/src/pdflib-9.1.x/dist/PDFlib/PDFlib-9.1.2p8-Alpine-Linux-x86_64-.NET-Core/bind/dotnetcore/csharp/hello/bin/Debug/netcoreapp2.0/hello.deps.json deps file
Loading deps file... /home/rjs/src/pdflib-9.1.x/dist/PDFlib/PDFlib-9.1.2p8-Alpine-Linux-x86_64-.NET-Core/bind/dotnetcore/csharp/hello/bin/Debug/netcoreapp2.0/hello.deps.json as framework dependent=[1]
Adding runtimeTargets native asset runtimes/alpine-x64/native/PDFlib_dotnetcore_native.so rid=alpine-x64 assemblyVersion= fileVersion=0.0.0.0 from PDFlib_dotnet/1.2.8
HostRID is alpine.3.8-x64
Falling back to base HostRID: linux-x64
...
````

For me it looks like "alpine.3.8-x64" is detected which falls back directly to "linux-x64". As our native library should work for all 64bit alpine Linux versions I did choose "alpine-x64" as RID (inspired by https://docs.microsoft.com/en-us/dotnet/core/rid-catalog).


If you would like to test with the package you can find it here: http://support.pdflib.com/PDFlib-9.1.2p8-Alpine-Linux-x86_64-.NET-Core.tar.gz

**Comment by jkotas** [comment] 2018-11-13 13:17
> netcoreapp2.0

Alpine was not fully supported in netcoreapp2.0. It had number of bugs.

Do you see the same problem with netcoreapp2.1?

**Comment by jkotas** [comment] 2018-11-13 13:44
Also, if all you depend from Alpine is musl, you may consider using linux-musl-x64 RID in your package. It will make it work for all musl-based distros, not just Alpine. https://github.com/dotnet/corefx/pull/28560 has the details.

**Comment by rjsathome** [comment] 2018-11-13 19:46
> > netcoreapp2.0
> 
> Alpine was not fully supported in netcoreapp2.0. It had number of bugs.
> 
> Do you see the same problem with netcoreapp2.1?

I changed my project file to build as netcoreapp2.1, but the result is still the same. 

I'm quite new to dotnetcore so I hope I did it correct for netcoreapp2.1, here my projectfile  (the .net version on my Alpine box is 2.1.400):
```sh
vmalpine64 (1)$ cat hello.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PDFlib_dotnet" Version="1.2.8" />
  </ItemGroup>
</Project>
```

Thanks for the tip with "linux-musl-x64" RID. I tried this however the behaviour did not change. 

Here the new trace:
[trace-linux-musl.txt](https://github.com/dotnet/coreclr/files/2577761/trace-linux-musl.txt)

**Comment by jkotas** [comment] 2018-11-13 21:19
@vitek-karas @sdmaclea The trace-linux-musl.txt log says: `Adding runtimeTargets native asset runtimes/linux-musl-x64/native/PDFlib_dotnetcore_native.so rid=linux-musl-x64 assemblyVersion= fileVersion=0.0.0.0 from PDFlib_dotnet/1.2.8`
But the path to this library does not end up in `NATIVE_DLL_SEARCH_DIRECTORIES`  at the end. Any ideas?

**Comment by rjsathome** [comment] 2018-11-13 21:52
Sorry, I don't know the internas of your code. 

When I look at the trace I search for our library "PDFlib_dotnetcore_native.so" and try to guess what is happening, the rest is more or less a miracle for me ;-)

what I see that is a bit strange for me is:

```
Adding runtimeTargets native asset runtimes/linux-musl-x64/native/PDFlib_dotnetcore_native.so rid=linux-musl-x64 assemblyVersion= fileVersion=0.0.0.0 from PDFlib_dotnet/1.2.8
HostRID is alpine.3.8-x64
Falling back to base HostRID: linux-x64
```
in the trace on Alpine.

or another look:

```
vmalpine64 (1)$ grep dotnetcore_native trace.txt
Adding runtimeTargets native asset runtimes/linux-musl-x64/native/PDFlib_dotnetcore_native.so rid=linux-musl-x64 assemblyVersion= fileVersion=0.0.0.0 from PDFlib_dotnet/1.2.8
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'PDFlib_dotnetcore_native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libPDFlib_dotnetcore_native: No such file or directory
```

when I do the same on ubuntu I get:

```
amira (1)$ grep dotnetcore_native trace.txt
Adding runtimeTargets native asset runtimes/linux-x64/native/PDFlib_dotnetcore_native.so rid=linux-x64 assemblyVersion= fileVersion=0.0.0.0 from PDFlib_dotnet/1.2.8
Parsed native deps entry 0 for asset name: PDFlib_dotnetcore_native from package: PDFlib_dotnet, library version: 1.2.8, relpath: runtimes/linux-x64/native/PDFlib_dotnetcore_native.so, assemblyVersion , fileVersion 0.0.0.0
Processing native/culture for deps entry [PDFlib_dotnet, 1.2.8, runtimes/linux-x64/native/PDFlib_dotnetcore_native.so]
  Considering entry [PDFlib_dotnet/1.2.8/runtimes/linux-x64/native/PDFlib_dotnetcore_native.so], probe dir [], probe fx level:0, entry fx level:0
    Relative path query did not exist /home_disk/rjs/src/pdflib-9.1.x/dist/PDFlib/PDFlib-9.1.2p8-Linux-x86_64-.NET-Core/bind/dotnetcore/csharp/hello/bin/Debug/netcoreapp2.0/runtimes/linux-x64/native/PDFlib_dotnetcore_native.so
  Considering entry [PDFlib_dotnet/1.2.8/runtimes/linux-x64/native/PDFlib_dotnetcore_native.so], probe dir [/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.2], probe fx level:1, entry fx level:0
  Considering entry [PDFlib_dotnet/1.2.8/runtimes/linux-x64/native/PDFlib_dotnetcore_native.so], probe dir [/home_disk/rjs/.nuget/packages], probe fx level:-1, entry fx level:0
    Relative path query exists /home_disk/rjs/.nuget/packages/pdflib_dotnet/1.2.8/runtimes/linux-x64/native/PDFlib_dotnetcore_native.so
    Probed package dir and matched '/home_disk/rjs/.nuget/packages/pdflib_dotnet/1.2.8/runtimes/linux-x64/native/PDFlib_dotnetcore_native.so'
```

So if you ask me for an idea:

- I think the RID tree for  Alpine Linux is somehow broken.
- I don't know wich RID tree is used in the alpine dotnet command. A bit searching and I found this: https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json. Here it stops with "alpine.3.7-x64", so my idea would be that alpine.3.8-x64 is to new??

**Comment by vitek-karas** [comment] 2018-11-13 22:00
I agree that the fact that apline.3.8 is not in the RID graph is the primary reason for why this doesn't work. The code does read the entry in `.deps.json`, then it tries to filter all entries to just those which apply to the current RID. This file effectively fails here, since it considers the current RID to be `linux-x64` due to the lack of `alpine.3.8` entries in the RID graph (it constructs the RID, but since it can't find it, it falls back to the basic RID which is `linux-x64`).

That said, the other interesting question is why this works for the frameworks.

**Comment by vitek-karas** [comment] 2018-11-13 22:16
So to answer my question about frameworks - it works there because the frameworks don't carry any RID specific assets. The framework itself is RID specific, so once the framework is picked, all its assets are used - no RID filtering is performed. The fact that the framework uses the same folder structure (`runtimes/linux-x64/native/...`) is really not understood by the runtime - it's a packaging detail.

The answer I think is that unfortunately alpine 3.8 is just too new. I vaguely remember that there's been a discussion somewhere about the fact that .NET Core has trouble supporting "new" distros basically due to this problem, but I can't find it right now.

**Comment by sdmaclea** [comment] 2018-11-13 22:41
@janvorli FYI

**Comment by rjsathome** [comment] 2018-11-14 11:07
I can confirm that it works as expected on Alpine Linux 3.7.

**Comment by vitek-karas** [comment] 2018-11-14 11:21
Thanks a lot @rjsathome for the confirmation. In theory you should be able to "hack" it to work even on 3.8. Go to the location where the shared framework Microsoft.NETCore.App is store on the machine, it should have `Microsoft.NETCore.App.deps.json` file in it. Open that and near the end of the file it has the RID fallback graph. Add alpine.3.8 by basically copying the 3.7 entries. And retry - that should make it work. Obviously not a solution, but if you need to make it work on one specific machine...

**Comment by jeffschwMSFT** [comment] 2019-02-21 19:02
Closing this issue and tracking https://github.com/dotnet/corefx/issues/34316

**Closed by jeffschwMSFT** 2019-02-21 19:02 UTC
Labels: area-Interop
