### ISSUE TITLE
arrres.il test fail with unexpected exception on Windows 64

### ISSUE THREAD

**Issue by richardlford** [dotnet/coreclr#2330] opened 2015-12-14 20:10 UTC
The following two tests:

- JIT\Methodical\Arrays\misc\_il_dbgarrres\_il_dbgarrres.cmd
- JIT\Methodical\Arrays\misc\_il_relarrres\_il_relarrres.cmd

fail with 

```
Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
           at GCTest.Test.Main()
```

on a Windows 64 debug build.

**Comment by sivarv** [comment] 2016-01-05 00:15
This looks to be a duplicate of issue #2352 filed on Linux.

**Comment by LLITCHEV** [comment] 2016-01-07 19:35
This looks like a bad test. The issue is that manipulation of the array (adding/removing elemens, etc.) is done in the same test method as the testing code. The Jit assigns the current element of the array to a temp that holds a live reference to the last element till the end of the method, thus not collecting (finalizing) the last element.
The fix would be to establish the array manipulation code in separate methods, so no temp introduced by the Jit interfere with the lifetime oif the object (as the test requires). Another possibility is to just exclude the test on all the platforms.

**Closed** 2016-05-15 00:41 UTC
Labels: 2 - In Progress, CodeGen, Test-Issue
