### ISSUE TITLE
AppDomain members blocking use on UWP

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#9914] opened 2017-03-02 18:46 UTC
Generally we're expecting the .NET Core tests to throw up breaks of this sort but since these are explicit blocks and I saw them, let's have this issue to make sure we don't miss it.

If you know/see other cases where we explicitly block UWP, please do create more issues.

```
C:\git\coreclr\src\mscorlib\src\System\AppDomain.cs:
  522  #if FEATURE_APPX
  523              if (IsAppXModel())
  524:                 throw new NotSupportedException(Environment.GetResourceString("NotSupported_AppX", "Assembly.LoadFrom"));
  525  #endif
  526          }
  ...
  534  #if FEATURE_APPX
  535              if (IsAppXModel())
  536:                 throw new NotSupportedException(Environment.GetResourceString("NotSupported_AppX", "Assembly.LoadFile"));
  537  #endif
  538          }
  ...
  546  #if FEATURE_APPX
  547              if (IsAppXModel())
  548:                 throw new NotSupportedException(Environment.GetResourceString("NotSupported_AppX", "Assembly.ReflectionOnlyLoad"));
  549  #endif
  550          }
  ...
  558  #if FEATURE_APPX
  559              if (IsAppXModel())
  560:                 throw new NotSupportedException(Environment.GetResourceString("NotSupported_AppX", "Assembly.Load(byte[], ...)"));
  561  #endif
  562          }

```

@rahku

**Comment by danmosemsft** [comment] 2017-03-02 22:09
@gkhanna79

**Comment by ViktorHofer** [comment] 2017-05-17 05:15
Is there a reason why we are still blocking them? They should be supported in UWP

**Comment by mikedn** [comment] 2017-05-17 05:18
UWP uses AOT compilation, how is something like `Assembly.Load` support to work in that environment?!

**Comment by ViktorHofer** [comment] 2017-05-17 05:25
Duplicate of https://github.com/dotnet/coreclr/issues/9912

**Closed by ViktorHofer** 2017-05-17 05:25 UTC
Labels: area-System.Runtime
