### ISSUE TITLE
 An assembly specified in the application dependencies manifest was not found

### ISSUE THREAD

**Issue by Seekeer** [dotnet/coreclr#18157] opened 2018-05-29 12:11 UTC
I got the following error when I am trying to start asp.net core server not on my dev system:

	  An assembly specified in the application dependencies manifest (PublishError.deps.json) was not found:
		package: 'HtmlAgilityPack', version: '1.8.4'
		path: 'lib/netstandard2.0/HtmlAgilityPack.dll'

Now server is Win 10 , but I got this error both on Windows and Linux. On Windows I got not only runtime but also an sdk - doesnt help .

Sample project can be [found here](https://drive.google.com/open?id=1H0ecF5kqkbSCkPM6_Bi9CGX6DlBf9ApS
).

**Comment by jkotas** [comment] 2018-05-29 14:37
You will get this error if you try to copy over app that was not published properly. Could you please try to copy over and run published copy of the app, ie what's in `bin\release\netcoreapp2.0\publish` directory?

We know that the distinction between `dotnet run` and `dotnet publish` is pretty confusing. We are looking into how to make it better for .NET Core 3.0.

**Comment by Seekeer** [comment] 2018-05-29 22:01
@jkotas I've copied the result of `dotnet publish -c release -r win10-x64` command. Ive also tried `dotnet publish -c release -r win10-x64 /p:TargetManifestFiles=` with the same result. Publish folder size is about 140 MB and I see HtmlAgilityPack.dll in it.

**Comment by jkotas** [comment] 2018-05-29 23:39
> Publish folder size is about 140 MB

The size of `bin\release\netcoreapp2.0\win10-x64\publish` directory is only about 100MB after running `dotnet publish -c release -r win10-x64`. And the result works fine for me across different machines.

Could you please share output of `dotnet --version` and upload `bin\release\netcoreapp2.0\win10-x64\publish` directory that you are getting, or if it is too big - upload just `PublishError.deps.json` file from the same directory?

**Comment by Seekeer** [comment] 2018-05-30 09:29
[Here is](https://drive.google.com/open?id=1thRWpuHj1EUqDXlz9EToJ9n6vw7PG_sg) build folder. 

> Could you please share output of dotnet --version
`2.1.4`

**Comment by jkotas** [comment] 2018-05-30 12:34
The build folder you have shared has a mix of .NET Core 1.0 and .NET Core 2.0 binaries, e.g. coreclr.dll is from .NET Core 2.0 and System.Private.CoreLib.dll is from .NET Core 1.0. I am not able to reproduce the situation, even with the exact SDK version you have shared. Have you upgraded this app from .NET Core 1.0 to .NET Core 2.0?Could you please try deleting the `bin` and `obj` directories and do a clean build and publish of your app?

**Comment by Seekeer** [comment] 2018-05-30 12:45
Yep, sorry that was build of main project with the same error.
[Here is](https://drive.google.com/open?id=1GEL8VIq2BVDzgu-AY_kA6tti2McvhiNB) builded sample project.
It was created as core 2.0 app a day ago in VS 2017 15.5.6

**Comment by jkotas** [comment] 2018-05-30 13:07
It works fine for me when I run:
```
cd PublishError\bin\release\netcoreapp2.0\win10-x64\publish
PublishError.exe
```

I see the error when I run:
```
cd PublishError\bin\release\netcoreapp2.0\win10-x64
PublishError.exe
```
This directory does not contain the right published bits. It is the unfortunate run vs. publish confusion that I have mentioned.

Do you see the same results?

**Comment by Seekeer** [comment] 2018-05-30 22:15
Thanks a lot, that works!
But only for Windows. 
Ive tried to make [same build for Linux](https://drive.google.com/open?id=1bDK09F91pOBe7Od70gyMz4zb4tfCKqhP): `dotnet publish -c release -r ubuntu.16.04-x64`. When I am running it on Ubuntu, I get:
	osboxes@osboxes:~/Documents/ubuntu/publish$ ./PublishError
	Failed to initialize CoreCLR, HRESULT: 0x80004005

I've installed core runtime by [this manual](https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/runtime-2.0.7).

**Comment by jkotas** [comment] 2018-05-30 22:36
This is most likely https://github.com/dotnet/coreclr/issues/15243 . It is caused by non-accessible `/tmp`. Does writable `/tmp` exists on Ubuntu that you are running on?

The way to diagnose this for sure is run the command under strace, like: `strace ./PublishError` and look for the recent failing syscall.

**Comment by Seekeer** [comment] 2018-05-31 09:51
Well, I've found /tmp folder and execute `sudo chmod 777 /tmp` for it. But I am still getting this errors.
Stacktrace [is here](https://drive.google.com/open?id=1MX9k3B30ZWO6ABNjdEtLMCBmy_ZzpJuA).

**Comment by jeffschwMSFT** [comment] 2019-04-30 19:59
Closing this question... though please let us know if you are still seeing this issue.

**Closed by jeffschwMSFT** 2019-04-30 19:59 UTC
Labels: area-AssemblyLoader, question
