### ISSUE TITLE
Unexpected TypeLoadException?

### ISSUE THREAD

**Issue by LEI-Hongfaan** [dotnet/coreclr#15997] opened 2018-01-24 18:06 UTC
Consider the following code:
```
class Generic<T> {
    public struct Nested { }
}
struct Foo {
    Generic<Foo>.Nested bar;
}
class Program {
    static void Main(string[] args) {
        Foo foo; // TypeLoadException
    }
}
```
This code compiles but fails at runtime with a `TypeLoadException`:
>An unhandled exception of type 'System.TypeLoadException' occurred in Unknown Module.
Could not load type 'Test1.Foo' from assembly 'Test1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

The struct `Foo` has an acyclic finite flattening graph (see ECMA-335 §II.13) and is legal.

**Comment by jkotas** [comment] 2018-01-24 22:08
Thank you for reporting this. This issue is duplicate of https://github.com/dotnet/coreclr/issues/7957

**Closed by jkotas** 2018-01-24 22:08 UTC
Labels: area-TypeSystem
