### ISSUE TITLE
Linux .Net Core calling 32bit .so library file issue

### ISSUE THREAD

**Issue by yb101** [dotnet/coreclr#13267] opened 2017-08-08 11:08 UTC
I'm using .Net Core in Linux and able to invoke the functions of my .so library file (64bit). But it will fail if I call the 32bit .so library. The error is simply saying the function can't be found. We would like to know if it's by design. Or if there is a way to call 32bit .so library from Linux .Net Core program? Please kindly advise. @yizhang82 Thanks.

Yuan Bin

**Comment by yatli** [comment] 2017-08-08 18:59
I think this is by design. You cannot call a 32bit native binary in a 64bit process with P/Invoke on Windows, either.

**Comment by borrrden** [comment] 2017-08-08 22:14
The runtime itself is actually a native process, and being a native process it can only load libraries that match its architecture.  .NET Core for Linux only supports 64-bit (and community supports ARM) as far as I know so the libraries it loads must also be 64-bit.  You need a 32-bit runtime if you are going to load 32-bit libraries.

**Comment by yb101** [comment] 2017-08-10 01:38
Does anyone know if there is a plan to roll out 32bit .Net Core runtime in Linux?

**Comment by borrrden** [comment] 2017-08-10 01:53
Looks like on the [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) It is listed as a "goal" to have a high quality x86 port.

**Comment by tijoytom** [comment] 2017-09-01 22:24
@yb101  As mentioned this is by design since the process is 64 bit , 32 bit coreclr is a much bigger issue . I am closing  this bug assuming your question is answered.

**Closed** 2017-11-09 17:24 UTC
Labels: area-Interop, question
