### ISSUE TITLE
Implement out-of-proc native stackwalk for DAC

### ISSUE THREAD

**Issue by Djuffin** [dotnet/coreclr#1659] opened 2015-10-01 04:23 UTC
Managed debugger and SOS need an implementation of PAL_VirtualUnwindOutOfProc in order to be able to step out of HelperMethodFrame when it's the leaf Frame in a Frame chain.

We have a Linux implementation that's using libunwind-ptrace, but it's ifdefed out because RPM Linux distros currently don't have libunwind-ptrace.so. (see #1571)

All in all, we need a solution(s) that works on all Linux distros and Mac OS.

**Comment by mikem8361** [comment] 2015-12-03 20:53
I already have issue #1787 (https://github.com/dotnet/coreclr/issues/1787) assigned to me.

mikem

**Comment by tzwlai** [comment] 2016-01-14 17:57
Closing this as a dupe of #1787.

CC @mikem8361

**Closed by tzwlai** 2016-01-14 17:57 UTC
Labels: Diagnostics, Linux, OSX
