### ISSUE TITLE
Regression in AsSpan for uint[] Datatype

### ISSUE THREAD

**Issue by Anipik** [dotnet/coreclr#21594] opened 2018-12-17 20:54 UTC
Netcoreapp 3.0
Sdk Version 3.0.100-preview-009841
``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17134.471 (1803/April2018Update/Redstone4)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-alpha1-009630
  [Host]     : .NET Core 3.0.0-preview1-26928-03 (CoreCLR 4.6.26927.03, CoreFX 4.6.26927.03), 64bit RyuJIT
  Job-TQETEJ : .NET Core 3.0.0-preview1-26928-03 (CoreCLR 4.6.26927.03, CoreFX 4.6.26927.03), 64bit RyuJIT

BuildConfiguration=Release-Intrinsics  Toolchain=netcoreapp3.0  InvocationCount=1  
MaxIterationCount=20  UnrollFactor=1  WarmupCount=1  

```
|                 Method |     Mean |     Error |    StdDev |    Median | Extra Metric |
|----------------------- |---------:|----------:|----------:|----------:|-------------:|
| AsSpanForUnitBenchmark | 1.445 us | 0.8379 us | 0.9649 us | 0.8400 us |            - |

Sdk version 2.1.401
Netcoreapp2.1
``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17134.471 (1803/April2018Update/Redstone4)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-alpha1-009630
  [Host]     : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT
  Job-JARWGC : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT

BuildConfiguration=Release  Toolchain=netcoreapp2.1  InvocationCount=1  
MaxIterationCount=20  UnrollFactor=1  WarmupCount=1  

```
|                 Method |     Mean |    Error |   StdDev |   Median | Extra Metric |
|----------------------- |---------:|---------:|---------:|---------:|-------------:|
| AsSpanForUnitBenchmark | 48.75 ns | 29.60 ns | 29.07 ns | 65.00 ns |            - |

The code for this benchmark is
``` C#

public uint[] input;
public int end;

 [IterationSetup(Target = nameof(AsSpanForUnitBenchmark))]
public void setup()
 {
       int min = 0;
        int max = 100000;
       Random randNum = new Random();
       end = randNum.Next(min, max);

        input = new uint[max]
       for (int i = 0; i < input.Length; i++)
        {
               input[i] = (uint)randNum.Next(min, max);
        }
}

[Benchmark]
public void AsSpanForUnitBenchmark()
{
    input.AsSpan(0, end);
}
```

cc @danmosemsft @adamsitnik @GrabYourPitchforks

**Comment by jkotas** [comment] 2018-12-19 02:47
@CarolEidt @AndyAyersMS How hard would it be to get rid of the redundant movs that seems to be causing the regression?

**Comment by mikedn** [comment] 2018-12-19 06:32
I'll take a look, recently I stumbled upon a JIT change that gets rid of some of these funny moves. Maybe we're lucky and it's the same case.

Also, the second `mov` in 
```asm
mov     ecx,dword ptr [rax+8]
mov     ecx,ecx
```
might be eliminated by another change I have.

**Comment by mikedn** [comment] 2018-12-19 18:30
> Also, the second mov in might be eliminated by another change I have.

Yep, that's definitely #12676.

Still looking at the funny moves. Some unrelated change I have does get rid of some such `Span` related funny moves but not in this case. Still, I suspect they're related so I'm still looking.

**Comment by adamsitnik** [comment] 2018-12-19 19:12
> I don't see benchmark coverage of this scenario.

I just sent a PR for that https://github.com/dotnet/performance/pull/206

**Comment by mikedn** [comment] 2018-12-19 19:56
And let's not miss the fact that when `start` is 0 the comparison should be narrowed to 32 bit
```asm
mov     ecx,dword ptr [rax+8]
mov     ecx,ecx
mov     r8d,edx
cmp     rcx,r8
jb      AsSpanForUnitBenchmark()+..
```
should be
```asm
cmp     dword ptr [rax+8],edx
jb      AsSpanForUnitBenchmark()+..
```

**Comment by CarolEidt** [comment] 2018-12-20 01:35
I have a WIP PR #19429. I just updated it, and verified that it gets rid of two of the three `mov`s after the `add`. Like most register allocation changes, it had both positive and negative impact (though more positive by a good margin), but was reticent to merge it without perf results. I'll give the perf runs another go.

**Comment by mikedn** [comment] 2018-12-20 02:52
> Like most register allocation changes, it had both positive and negative impact (though more positive by a good margin), but was reticent to merge it without perf results

But is it LSRA's job to deal with poor IR generated by previous phases?

**Comment by CarolEidt** [comment] 2018-12-20 15:17
> But is it LSRA's job to deal with poor IR generated by previous phases?

Not entirely. But given phase ordering and all, I think it's generally accepted that a register allocator should incorporate copy elimination, either as part of its function, or done prior to.

**Comment by AndyAyersMS** [comment] 2018-12-20 17:11
@mikedn I take it you meant #20771?

The only change early on in the jit IR is from that source-level change to the validation logic in the span constructor.

It would be interesting to revert #20771 and see if perf goes back to where it was in 2.1. If so perhaps we need to evaluate that optimization more broadly.

**Comment by mikedn** [comment] 2018-12-20 17:37
> @mikedn I take it you meant #20771? The only change early on in the jit IR is from that source-level change to the validation logic in the span constructor.

@jkotas found that. I think there are actually 2 unrelated problems. One was that change, it came with the 64 bit compare that the JIT doesn't narrow to 32 bit. The other is the "funny move" problem, that's probably not related to #20771, it's the usual problem the JIT has with some `Span` code due to problems with struct promotion.

**Comment by mikedn** [comment] 2018-12-20 21:00
OK, I tried to revert the change done in #20771. Indeed, the validation logic change did cause the apparition of those funny moves, even though they're actually generated by the `ByReference` assignment that follows the validation. I'll take a closer look, it's a bit strange how one caused the other.

**Comment by AndyAyersMS** [comment] 2019-02-07 05:09
This should have been be improved by #19429 and #22454 ...

```asm
;;; 2.1

G_M12530_IG04:
       83780800             cmp      dword ptr [rax+8], 0
       721D                 jb       SHORT G_M12530_IG09
       395008               cmp      dword ptr [rax+8], edx
       7218                 jb       SHORT G_M12530_IG09

G_M12530_IG05:
       488D4810             lea      rcx, bword ptr [rax+16]

G_M12530_IG06:
       48894C2428           mov      bword ptr [rsp+28H], rcx
       89542430             mov      dword ptr [rsp+30H], edx
```
and master with the above PRs merged does show promise....
```asm
;;; master plus 22454

G_M12530_IG04:
       8B4808               mov      ecx, dword ptr [rax+8]
       448BC2               mov      r8d, edx
       493BC8               cmp      rcx, r8
       721B                 jb       SHORT G_M12530_IG09

G_M12530_IG05:
       4883C010             add      rax, 16
       488BC8               mov      rcx, rax

G_M12530_IG06:
       48894C2428           mov      bword ptr [rsp+28H], rcx
       89542430             mov      dword ptr [rsp+30H], edx
```

**Comment by AndyAyersMS** [comment] 2019-02-07 08:25
Still room for improvement -- looks like maybe LSRA is not using casts for preferencing?

**Comment by AndyAyersMS** [comment] 2019-02-19 21:17
I don't see much perf difference between 3.0 Preview 2 and 2.1 on the test case that was added in dotnet/performance#260 to try and capture this issue.
```
BenchmarkDotNet=v0.11.3.1003-nightly, OS=Windows 10.0.18323
Intel Core i7-4770HQ CPU 2.20GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview4-010309
  [Host]     : .NET Core 2.1.7 (CoreCLR 4.6.27129.04, CoreFX 4.6.27129.04), 64bit RyuJIT
  Job-WTCAUC : .NET Core 2.1.7 (CoreCLR 4.6.27129.04, CoreFX 4.6.27129.04), 64bit RyuJIT
  Job-YHFHGF : .NET Core 3.0.0-preview-27412-2 (CoreCLR 4.6.27411.71, CoreFX 4.7.19.11201), 64bit RyuJIT

Runtime=Core  IterationTime=250.0000 ms  MaxIterationCount=20
MinIterationCount=15  WarmupCount=1
```

|                 Method |     Toolchain |      Mean |     Error |    StdDev |    Median |       Min |       Max | Ratio | RatioSD | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|----------------------- |-------------- |----------:|----------:|----------:|----------:|----------:|----------:|------:|--------:|------------:|------------:|------------:|--------------------:|
| ArrayAsSpanStartLength | netcoreapp2.1 | 0.3919 ns | 0.0134 ns | 0.0125 ns | 0.3879 ns | 0.3705 ns | 0.4164 ns |  1.00 |    0.00 |           - |           - |           - |                   - |
| ArrayAsSpanStartLength | netcoreapp3.0 | 0.4198 ns | 0.0288 ns | 0.0269 ns | 0.4166 ns | 0.3848 ns | 0.4819 ns |  1.07 |    0.08 |           - |           - |           - |                   - |

@Anipik can you remeasure your test with 3.0 preview 2?

**Comment by AndyAyersMS** [comment] 2019-02-26 00:47
Am going to close since I think this is fixed -- please reopen if that's not the case.

**Closed by AndyAyersMS** 2019-02-26 00:47 UTC
Labels: area-CodeGen, bug, tenet-performance

**Comment by danmosemsft** [comment] 2019-02-26 00:59
@Anipik please post back when you've verified 3.0 preview 2 or later..

**Comment by Anipik** [comment] 2019-02-26 01:00
yeah I am on it

**Comment by Anipik** [comment] 2019-02-26 01:27
@AndyAyersMS I verified and regression is no longer there. thanks for all the help and effort in resolving this
