### ISSUE TITLE
RyuJIT: suboptimal code after inlining a method accessing a field via ref

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#1226] opened 2015-07-10 07:28 UTC
There is a small difference between code generated for  direct reading of a volatile variable and doing it via Volatile.Read. 

``` C#
volatile int sharedVar;

public int Test()
{
    return sharedVar;
}

public int Test2()
{
    return Volatile.Read(ref sharedVar);
}
```

``` ASM
       mov      eax, dword ptr [rcx+8]
       ret  

;vs

       cmp      dword ptr [rcx], ecx
       lea      rax, bword ptr [rcx+8]
       mov      eax, dword ptr [rax]
       ret  
```

category:cq
theme:basic-cq
skill-level:expert
cost:large

**Comment by mikedn** [comment] 2015-07-10 11:25
Ah, those `lea` instructions, they're like cockroaches, as soon as you get rid of one another one pops up in another place. 

Note that this has nothing to do with volatile, the following produces the same assembly code:
```C#
using System.Runtime.CompilerServices;

class Program {
    int sharedVar;
    public int Read(ref int x) {
        return x;
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public int Test() {
        return Read(ref sharedVar);
    }
    static int Main() {
        return new Program().Test();
    }
}
```

**Comment by omariom** [comment] 2015-07-10 13:35
> Note that this has nothing to do with volatile

I hope that as it is related to volatiles it will get more attention :wink:

**Comment by masonwheeler** [comment] 2015-07-10 15:06
@mikedn What's so bad about `lea`, aside from the horrendously unintuitive name?

**Comment by mikedn** [comment] 2015-07-10 15:28
@masonwheeler There's nothing wrong with the instruction itself. The problem is that the x86 JIT has a propensity for using them in places where they're not needed. I reported this kind of stuff on Connect in the past and supposedly the issues were fixed but every time I look at a new version they just pop somewhere else. And RyuJIT inherited this from the x86 JIT.

**Comment by cmckinsey** [comment] 2015-07-19 23:41
That sequence is pretty bad in all dimensions (size, speed, registers). We need forward-propagation of addressing-expressions followed by null-check folding. This should be doable.

**Comment by jasonwilliams200OK** [comment] 2015-08-19 07:10
> Ah, those lea instructions, they're like cockroaches, as soon as you get rid of one another one pops up in another place.

@mikedn, Reading this: http://stackoverflow.com/a/11041820 after your comment, now `lea` instruction seems to have unique significance... and like @leppie, i am confused too! :smile: (not sure if this behavior/issue exists in CoreCLR as well?)

**Comment by mikedn** [comment] 2015-08-19 10:02
@jasonwilliams200OK That's a different use of `lea` and it's completely unrelated to this issue. Besides, that SO thread looks like it was hit by the truck of fail with an answer post that doesn't really answer anything and a most voted post that concludes that `lea ecx, [ecx+ecx*4]` is somehow slower than the equivalent `imul` without even bothering to check the latency of those instructions. And the only post that actually says something useful gets only one vote. Awesome.

**Comment by GSPP** [comment] 2015-08-20 13:13
@mikedn imul is 3 cycles and lea is 1, correct? The conclusion of the highest voted answer seems correct. Also, he tested that theory by plugging in different constants.

**Comment by mikedn** [comment] 2015-08-20 13:30
@GSPP Yes, on Intels `imul` needs 3 cycles and that particular form of `lea` needs only 1 (there are forms that need 3 cycles as well). His conclusion appears to be that using `lea` like that is a pessimization and that's pretty much impossible. He claims that changing the constant affects performance but he doesn't provide any actual results and I cannot reproduce that. Additionally, RyuJIT doesn't use `lea` in that case but the performance issue described in the question persists.

**Comment by GSPP** [comment] 2015-08-20 13:32
@mikedn I see what you mean. I read the answer the other way around.

**Comment by omariom** [comment] 2016-07-27 12:25
@erozenfeld
Is it still for the `Future`?

**Comment by erozenfeld** [comment] 2016-07-27 20:41
@omariom  I have some changes that eliminate the null check in your example. Do you have a real scenario where this fix would speed up some product? With my prototype a number of null checks were eliminated but none of the benchmarks we have got faster (the code size did get smaller of course). If you have such a real example (not a benchmark specifically tailored for this), that would help us prioritize getting this optimization checked in.

**Comment by omariom** [comment] 2016-07-27 21:05
@erozenfeld No, I don't have such an example. And I understand there are more important things to do in JIT. Just thought after 1.0 it would get a more specific milestone )

**Comment by erozenfeld** [comment] 2016-08-22 20:08
#6631 eliminated the null check in this issue's test case. The `lea` is still there so I'm keeping the issue open.

**Comment by omariom** [comment] 2020-01-03 02:02
@erozenfeld 
I think it [can be closed now](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgBUALWbAEwEsAdgHMA3DRrEAzE1IMAwgxoBvGgzUMAbhAA22DH20wGgjAwBmfGNp5jq6xXfUmGAWQAUASgYBeAHwMANR09AxgWACUYXjdYM3NLaw9be1UnAVMXUk8ffwsrGxoAXyA).

**Closed** 2020-01-03 02:33 UTC
Labels: area-CodeGen, enhancement, optimization, tenet-performance
