### ISSUE TITLE
[Linux] Suggestion: Official Dist Support 

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#10183] opened 2017-03-15 00:59 UTC
Many, if not most, Linux supporting software packages have official dist files for well-known Linux distros.

As coreclr is a native component and Linux is one of supported main OS, why don't you have official dist files so that many Linux distro users may maintain & build & install easily.

I'd suggest to have .spec (for Tizen/Fedora/Redhat/openSUSE) and .deb (for Debian/Ubuntu) as the official dist files. With these files included officially, you will potentially be able to include dotnet/coreclr as a default or standard pacakge in such Linux distros as well, which I'd recommend to start with PPA (Ubuntu) and home projects of build.opensuse.org (supporting many distros simultaneously). This will also be much helpful on cleaning up build schemes of coreclr for Linux because you will have clear vision on what to do and what not to do in the due process. You may have your release process (for those distros) automated and have less worries on dependencies and OS version issues. 

Frankly speaking, without official dist support, for Linux, packages still look like prototypes.

**Comment by myungjoo** [comment] 2017-03-15 01:27
We have starting points:

https://build.opensuse.org/package/view_file/home:Simmphonie:mono/coreclr/coreclr.spec?expand=1
https://launchpad.net/~xyziemba/+archive/ubuntu/dotnet/+packages

**Comment by jkotas** [comment] 2017-03-15 03:56
cc @Petermarcu

**Comment by Petermarcu** [comment] 2017-03-15 05:43
cc @ellismg @shawnro

**Comment by hqueue** [comment] 2017-03-15 08:01
I would like to vote +1 for the idea.

**Comment by gkhanna79** [comment] 2017-03-15 15:51
CC @rakeshsinghranchi @vivmishra

**Comment by parjong** [comment] 2017-03-16 00:39
#808 seems to be related.

**Comment by ellismg** [comment] 2017-03-16 00:44
Previously we had not been thinking of CoreCLR as a standalone thing that we would package by itself.  Instead CoreCLR is a component of a larger product (for example the .NET Core Shared Framework) and we'd package that.

The plan for 2.0 is that we will provide platform specific packages of both the .NET Core SDK and the .NET Core Shared Framework, but there's no plan to make standalone packages of just CoreCLR. If we did that, would that be sufficient?  If not, what's the desire in having a package that's just CoreCLR?  Do folks want to host CoreCLR themselves and bring their own framework with them?

**Comment by myungjoo** [comment] 2017-03-16 00:51
Even if CoreCLR is not useful without its neighbor packages, having CoreCLR as a package, not a component inside a package helps control the version and the dependency chains of CoreCLR. You may see vastly many cases of such in most Linux distros, having a lot of multiple packages (or subpackages), which may have their own version, for a single "functionality".

For example, if we have coreclr.rpm, corefx.rpm, dotnet-launcher.rpm, nuget.rpm, ... as separated packages, we can have coreclr 2.0.1-100, corefx 3.0.1-100 and update corefx 3.0.1-100 to 3.0.1-101 without worrying about coreclr 2.0.1-100 unless there are explicit version dependencies, which are embedded as metadata in packages (rpm/deb). For integration / easy-to-install purpose,  you may release an empty meta-package which only describes that it requires coreclr, corefx, or whatever you need for dotnet.

**Comment by ellismg** [comment] 2017-03-16 00:57
> Even if CoreCLR is not useful without its neighbor packages, having CoreCLR as a package, not a component inside a package helps control the version and the dependency chains of CoreCLR. You may see vastly many cases of such in most Linux distros, having a lot of multiple packages (or subpackages), which may have their own version, for a single "functionality".

In https://github.com/dotnet/core-setup/issues/1599 we are discussing how the CLI will be packaged.  We do plan to segment the CLI itself into a few packages, with a metapackage that just has dependencies on other (and name and version them in such a way that things that should be able to be installed side by side can be).  But the plan is not not have such a fine grained dependency such that CoreFX and CoreCLR could be separated from one another.

The team today doesn't see the value is breaking things apart further than the "dotnet host" "tooling" and "shared framework" boundaries.  We don't see interesting cases where you want to mix and match different versions of CoreCLR with CoreFX.

There's also no plans to break different tools out from the SDK and into their own packages.  So while `dotnet-sdk` will bring with it some bits of NuGet and MSBuild in order to implement features like `dotnet restore` and `dotnet build`, we don't plan to break out the components into independently installable packages that can be mixed and matched.  You either install `dotnet-sdk` and get all the tools or you don't.

**Comment by RheaAyase** [comment] 2017-03-16 01:29
@ellismg said:
> You either install dotnet-sdk and get all the tools or you don't.

And I'll agree with this, splitting it off would be more work with no bonus fruit at the end of it... And the same I would think of coreCLR being part of shared framework.

I would even consider this discussion to be a duplicate of https://github.com/dotnet/core-setup/issues/1599 to be honest. Does it make sense to perhaps continue the discussion there, or continue it here in which case I would simply sum it up there when(if) we have something to sum up?

@myungjoo said:
> ... With these files included officially, you will potentially be able to include dotnet/coreclr as a default or standard pacakge in such Linux distros as well...

I believe that this is not the responsibility of the .NET Foundation, but instead that of the individual distributions / package maintainers.

> You may have your release process (for those distros) automated and have less worries on dependencies and OS version issues.

Similar answer actually, package maintainers for specific distributions know in's and out's of their packaging guidelines and practices which very often differ in one way or another from the other distributions. It is not a good idea to try to transfer this responsibility onto _upstream_. I don't see this working out well. It's a -1 from me on both topics - CoreCLR being a package, and this upstream being responsible for official distro packages...

> I'd recommend to start with PPA (Ubuntu) and home projects of build.opensuse.org

Why not Fedora/RedHat? We've got an army of redhatters here ;)

**Comment by jkotas** [comment] 2017-12-02 06:53
Duplicate of dotnet/core-setup#1599

**Closed by jkotas** 2017-12-02 06:53 UTC
Labels: area-Infrastructure, enhancement
